import type { AulaGeoV1 } from "../../types";
import { url as cidade } from "@/assets/ciencias-5ano/u5-a1/cidade.jpg.asset.json";
import { url as solar } from "@/assets/ciencias-5ano/u5-a1/solar.jpg.asset.json";
import { url as hidro } from "@/assets/ciencias-5ano/u5-a1/hidreletrica.jpg.asset.json";
import { url as eolica } from "@/assets/ciencias-5ano/u5-a1/eolica.jpg.asset.json";
import { url as lampada } from "@/assets/ciencias-5ano/u5-a1/lampada.jpg.asset.json";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-energia-tecnologia",
  titulo: "Energia e Tecnologia",
  iconeTrilha: "⚡",
  bncc: ["EF05CI03"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela cidade iluminada. Encontre de onde vem toda essa energia.",
    mapaUrl: cidade,
    imagemDestaqueUrl: lampada,
    aurora: "Toda essa luz não aparece do nada. Vem de USINAS distantes — algumas movidas pela água, outras pelo sol, pelo vento. Tudo tem uma origem.",
    falaFinal: "Cientista pergunta 'de onde vem?'. Cidadão consciente pergunta 'quanto custa ao planeta?'.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "No Brasil, qual é a MAIOR fonte de eletricidade?",
    pergunta: "De onde vem a maior parte da nossa luz?",
    fotoUrl: hidro,
    opcoes: [
      { id: "hidro", titulo: "HIDRELÉTRICA", subtitulo: "força da água", emoji: "💧", cor: "from-cyan-400 to-sky-700" },
      { id: "solar", titulo: "SOLAR", subtitulo: "luz do sol", emoji: "☀️", cor: "from-amber-400 to-orange-700" },
      { id: "eolica", titulo: "EÓLICA", subtitulo: "força do vento", emoji: "💨", cor: "from-slate-400 to-slate-700" },
    ],
    respostaCerta: "hidro",
    feedbackAcerto: "Certo. Cerca de 60% da eletricidade do Brasil vem de HIDRELÉTRICAS.",
    feedbackErro: "Brasil tem muitos rios grandes. A HIDRELÉTRICA é nossa principal fonte.",
    falaFinal: "Cada país tem sua matriz. A do Brasil é rica em água — por isso hidrelétrica domina.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco conceitos essenciais sobre energia.",
    instrucao: "Vocabulário de energia",
    cadernos: [
      { id: "energia", capa: "ENERGIA", emoji: "⚡", cor: "from-amber-500 to-orange-700",
        conteudo: "Capacidade de fazer algo acontecer: iluminar, aquecer, movimentar.",
        exemplo: "Ex.: energia elétrica na tomada.", fotoUrl: lampada },
      { id: "renovavel", capa: "RENOVÁVEL", emoji: "♻️", cor: "from-emerald-500 to-green-700",
        conteudo: "Fonte que se REPÕE naturalmente e não acaba: sol, vento, água.",
        exemplo: "Ex.: sol brilha todo dia; vento sempre volta.", fotoUrl: solar },
      { id: "naorenovavel", capa: "NÃO RENOVÁVEL", emoji: "🛢️", cor: "from-slate-500 to-slate-700",
        conteudo: "Fonte finita — quando acaba, acabou. Poluente e demora milhões de anos pra formar.",
        exemplo: "Ex.: petróleo, carvão, gás.", fotoUrl: cidade },
      { id: "usina", capa: "USINA", emoji: "🏭", cor: "from-cyan-500 to-sky-700",
        conteudo: "Instalação que TRANSFORMA uma fonte de energia em ELETRICIDADE.",
        exemplo: "Ex.: hidrelétrica de Itaipu.", fotoUrl: hidro },
      { id: "consumo", capa: "CONSUMO", emoji: "📉", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Quanto de energia você usa. Reduzir consumo = menos usinas, menos poluição.",
        exemplo: "Ex.: apagar luz que não usa; LED em vez de lâmpada comum.", fotoUrl: lampada },
    ],
    falaFinal: "Renovável ou não, toda energia veio de algum lugar. E toda escolha tem impacto.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A cidade à noite. Toca em cada elemento pra ver a fonte de energia por trás.",
    instrucao: "Toque em cada elemento",
    mapaUrl: cidade,
    pontos: [
      { id: "predios", x: 30, y: 55, emoji: "🏢", cor: "from-slate-500 to-slate-700",
        titulo: "Prédios", texto: "Grande parte do consumo urbano — iluminação, ar-condicionado, elevadores.",
        fotoUrl: cidade },
      { id: "postes", x: 55, y: 75, emoji: "💡", cor: "from-amber-500 to-orange-700",
        titulo: "Postes de luz", texto: "Iluminação pública 24h. Usar LED reduz o consumo em até 60%.",
        fotoUrl: lampada },
      { id: "usinaH", x: 15, y: 30, emoji: "💧", cor: "from-cyan-500 to-sky-700",
        titulo: "Origem: Hidrelétrica", texto: "Água em queda gira turbinas — energia mecânica vira elétrica.",
        fotoUrl: hidro },
      { id: "usinaS", x: 80, y: 30, emoji: "☀️", cor: "from-yellow-500 to-orange-700",
        titulo: "Origem: Solar", texto: "Painéis captam luz e convertem em eletricidade limpa.",
        fotoUrl: solar },
      { id: "usinaE", x: 80, y: 55, emoji: "💨", cor: "from-teal-500 to-emerald-700",
        titulo: "Origem: Eólica", texto: "Vento move hélices gigantes; movimento vira eletricidade.",
        fotoUrl: eolica },
    ],
    falaFinal: "Cada lâmpada tem uma usina lá longe alimentando. Nada é mágica.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de energia.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Qual fonte de energia NÃO acaba?",
        fotoUrl: solar,
        cards: [
          { id: "a", emoji: "☀️", titulo: "Sol (renovável)", cor: "from-amber-500 to-orange-700" },
          { id: "b", emoji: "🛢️", titulo: "Petróleo (não renovável)", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🪨", titulo: "Carvão (não renovável)", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Sol é a fonte renovável mais abundante do planeta.",
        feedbackErro: "Petróleo e carvão são FINITOS. O SOL é renovável." },
      { id: "q2", pergunta: "Como uma hidrelétrica gera eletricidade?",
        fotoUrl: hidro,
        cards: [
          { id: "a", emoji: "💧", titulo: "Água em queda gira turbinas", cor: "from-cyan-500 to-sky-700" },
          { id: "b", emoji: "🔥", titulo: "Queimando água", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "🌡️", titulo: "Aquecendo água", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Força mecânica da água em queda gira turbinas — que geram eletricidade.",
        feedbackErro: "Não se queima nem se aquece água. A QUEDA gira a turbina." },
      { id: "q3", pergunta: "Reduzir o consumo de energia ajuda o quê?",
        fotoUrl: lampada,
        cards: [
          { id: "a", emoji: "🌍", titulo: "O planeta — menos usinas, menos poluição", cor: "from-emerald-500 to-green-700" },
          { id: "b", emoji: "🤷", titulo: "Nada, não faz diferença", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "💸", titulo: "Só a conta de luz", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Menos consumo = menos usinas necessárias = menos impacto ambiental.",
        feedbackErro: "Consumo consciente reduz demanda por energia — beneficia PLANETA todo, não só sua conta." },
    ],
    falaFinal: "Você entende o básico da matriz energética. Escolhas conscientes começam com informação.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "A energia divide-se em RENOVÁVEIS (limpas) e NÃO RENOVÁVEIS (finitas e poluentes). Liga cada camada.",
    instrucao: "Toque nos interruptores",
    mapaUrl: cidade,
    camadas: [
      { id: "renovaveis", rotulo: "Renováveis", emoji: "♻️", cor: "from-emerald-500 to-green-700",
        rect: { x: 2, y: 25, w: 96, h: 35 },
        descricao: "Sol, vento, água. Não acabam, poluem pouco. Futuro da matriz mundial.",
        fotoUrl: solar },
      { id: "naorenovaveis", rotulo: "Não Renováveis", emoji: "🛢️", cor: "from-slate-500 to-slate-700",
        rect: { x: 2, y: 65, w: 96, h: 30 },
        descricao: "Petróleo, carvão, gás. Vão acabar. Poluem muito. Ainda usadas por conveniência.",
        fotoUrl: cidade },
    ],
    falaFinal: "O mundo caminha do não renovável para o renovável. É a transição energética.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte o caminho da energia da fonte até sua casa.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Como a energia chega na tomada?",
    paradas: [
      { id: "fonte", emoji: "💧", rotulo: "1. Fonte", descricao: "Rio, vento, sol ou combustível — a fonte primária de energia.", fotoUrl: hidro },
      { id: "usina", emoji: "🏭", rotulo: "2. Usina", descricao: "Transforma a fonte em ELETRICIDADE.", fotoUrl: hidro },
      { id: "linhas", emoji: "🔌", rotulo: "3. Linhas", descricao: "Fios gigantes levam energia por centenas de quilômetros.", fotoUrl: cidade },
      { id: "poste", emoji: "🗼", rotulo: "4. Poste", descricao: "Poste da rua distribui pra cada residência.", fotoUrl: cidade },
      { id: "tomada", emoji: "🔋", rotulo: "5. Tomada", descricao: "Chega em casa pronta pra ser usada.", fotoUrl: lampada },
    ],
    ordemCerta: ["fonte", "usina", "linhas", "poste", "tomada"],
    feedbackAcerto: "Rota completa. Da queda d'água à sua tomada em segundos.",
    feedbackErro: "Repense: sempre começa na FONTE, passa pela USINA, viaja em LINHAS.",
    falaFinal: "A eletricidade viaja quase à velocidade da luz. Da usina à tomada em milissegundos.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Leitura autônoma. Estuda o guia da engenheira.",
    tituloLivro: "📓 Guia da Engenheira Elétrica",
    subtitulo: "Como a energia move o mundo",
    paragrafos: [
      { id: "p1", texto:
          "ENERGIA é a capacidade de fazer alguma coisa acontecer: iluminar, aquecer, mover. A maior parte da que você usa em casa é elétrica — e ela precisa ser GERADA em algum lugar antes de chegar à sua tomada.",
        chaves: ["energia", "gerada"],
        definicoes: {
          energia: "Capacidade de realizar trabalho — mover, aquecer, iluminar.",
          gerada: "Produzida em usinas a partir de uma fonte primária.",
        }, fotoUrl: lampada },
      { id: "p2", texto:
          "Fontes RENOVÁVEIS (sol, vento, água) se repõem naturalmente. Fontes NÃO RENOVÁVEIS (petróleo, carvão) demoram milhões de anos pra formar — e poluem quando queimadas. O planeta caminha rumo às renováveis.",
        chaves: ["renováveis", "não renováveis"],
        definicoes: {
          renováveis: "Fontes que se repõem e não acabam.",
          "não renováveis": "Fontes finitas e poluentes.",
        }, fotoUrl: solar },
      { id: "p3", texto:
          "Cada aparelho que você desliga é MENOS energia que a usina precisa gerar. Consumo CONSCIENTE (LED, desligar chuveiro, tirar aparelho da tomada) reduz demanda e ajuda o planeta. Toda ação individual soma.",
        chaves: ["consciente"],
        definicoes: {
          consciente: "Uso pensado, evitando desperdício.",
        }, fotoUrl: cidade },
    ],
    falaFinal: "Você entende o sistema elétrico. Agora suas escolhas de consumo fazem sentido.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra uma fonte de energia — identifique o TIPO.",
    instrucao: "⏱️ Leia e escolha o tipo correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "renovavel", emoji: "♻️", rotulo: "Renovável" },
      { id: "naorenovavel", emoji: "🛢️", rotulo: "Não Renovável" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Painel solar", emoji: "☀️", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "Luz do sol", emoji: "🌞", cor: "from-yellow-500 to-orange-700" },
        contexto: "Painel capta energia do sol que brilha todo dia.",
        pecaCertaId: "renovavel", fotoUrl: solar,
        feedbackAcerto: "Sim. Sol nunca acaba = RENOVÁVEL.",
        feedbackErro: "Sol brilha todo dia. Fonte que não acaba = RENOVÁVEL." },
      { id: "r2", municipioA: { nome: "Poço de petróleo", emoji: "🛢️", cor: "from-slate-500 to-slate-700" },
        municipioB: { nome: "Combustível fóssil", emoji: "⛽", cor: "from-red-500 to-rose-700" },
        contexto: "Petróleo levou milhões de anos pra se formar e vai acabar em algumas décadas.",
        pecaCertaId: "naorenovavel", fotoUrl: cidade,
        feedbackAcerto: "Perfeito. Fóssil finito = NÃO RENOVÁVEL.",
        feedbackErro: "Petróleo demora milhões de anos pra formar. É NÃO RENOVÁVEL." },
      { id: "r3", municipioA: { nome: "Turbina eólica", emoji: "💨", cor: "from-teal-500 to-emerald-700" },
        municipioB: { nome: "Força do vento", emoji: "🌪️", cor: "from-cyan-500 to-sky-700" },
        contexto: "Vento gira hélices gigantes que geram eletricidade limpa.",
        pecaCertaId: "renovavel", fotoUrl: eolica,
        feedbackAcerto: "Isso. Vento sempre volta = RENOVÁVEL.",
        feedbackErro: "Vento é constante no planeta. Fonte RENOVÁVEL." },
      { id: "r4", municipioA: { nome: "Hidrelétrica", emoji: "💧", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Água em queda", emoji: "🏞️", cor: "from-emerald-500 to-green-700" },
        contexto: "Rios continuam correndo, chuvas continuam caindo — água sempre volta.",
        pecaCertaId: "renovavel", fotoUrl: hidro,
        feedbackAcerto: "Sim. Ciclo da água nunca para = RENOVÁVEL.",
        feedbackErro: "Ciclo da água é contínuo. Fonte RENOVÁVEL." },
      { id: "r5", municipioA: { nome: "Mina de carvão", emoji: "🪨", cor: "from-slate-600 to-slate-800" },
        municipioB: { nome: "Combustível fóssil", emoji: "🔥", cor: "from-red-500 to-rose-700" },
        contexto: "Carvão foi formado por matéria orgânica há milhões de anos e vai se esgotar.",
        pecaCertaId: "naorenovavel", fotoUrl: cidade,
        feedbackAcerto: "Perfeito. Combustível fóssil finito = NÃO RENOVÁVEL.",
        feedbackErro: "Carvão é fóssil. Recursos fósseis são NÃO RENOVÁVEIS." },
    ],
    falaFinal: "Você classifica qualquer fonte de energia. Base pra decisões conscientes.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "A energia divide-se em duas metades: GERAR (usinas + fontes) e CONSUMIR (uso doméstico consciente).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: cidade,
    fatias: [
      { id: "gerar", rotulo: "Gerar", emoji: "🏭", percentual: 50, cor: "#0891b2",
        descricao: "De onde vem: hidro, solar, eólica, térmica. Cada uma com custo ambiental diferente.",
        exemplos: ["Hidrelétrica", "Solar", "Eólica"], fotoUrl: hidro },
      { id: "consumir", rotulo: "Consumir Consciente", emoji: "💡", percentual: 50, cor: "#f59e0b",
        descricao: "Como usar: LED, banho curto, aparelhos desligados. Ações que reduzem demanda.",
        exemplos: ["LED", "Desligar aparelhos", "Banho curto"], fotoUrl: lampada },
    ],
    falaFinal: "Metade da solução é gerar limpo. A outra metade é consumir com consciência.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Engenheiro Eco te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: cidade,
    perguntas: [
      { id: "q1", pergunta: "Uma fonte que NÃO acaba é chamada de:",
        fotoUrl: solar,
        opcoes: [
          { id: "a", texto: "Renovável", correta: true },
          { id: "b", texto: "Não renovável" },
        ],
        feedbackAcerto: "Sim. Fonte que se repõe = RENOVÁVEL.",
        feedbackErro: "Fonte que não acaba é RENOVÁVEL. Não renovável = finita." },
      { id: "q2", pergunta: "Qual dessas é renovável?",
        fotoUrl: eolica,
        opcoes: [
          { id: "a", texto: "Vento", correta: true },
          { id: "b", texto: "Petróleo" },
        ],
        feedbackAcerto: "Correto. Vento é renovável — sempre existirá enquanto houver atmosfera.",
        feedbackErro: "Petróleo é fóssil finito. VENTO é renovável." },
      { id: "q3", pergunta: "Trocar lâmpada comum por LED faz diferença?",
        fotoUrl: lampada,
        opcoes: [
          { id: "a", texto: "Sim, gasta muito menos energia", correta: true },
          { id: "b", texto: "Não, é igual" },
        ],
        feedbackAcerto: "Sim. LED gasta até 80% menos que lâmpadas antigas.",
        feedbackErro: "LED é MUITO mais eficiente. Diferença enorme no consumo." },
    ],
    selo: {
      nome: "Engenheiro Eco",
      subtitulo: "Missão Planeta Vivo · Laboratório 5 concluído",
      emoji: "⚡",
      cor: "from-amber-400 via-orange-500 to-yellow-700",
    },
    falaFinal: "Engenheiro eco aprovado. Próximo laboratório: nosso lugar no universo.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Engenheiro Eco" },
};
