// Rotina de Escrita Diária — 3º ano (8 anos)
// Mesmo formato do 1º e 2º ano, calibrado para quem já escreve frases:
// o foco vai para ORTOGRAFIA CONTEXTUAL, ACENTUAÇÃO, PARÁGRAFO e
// PRODUÇÃO DE GÊNEROS (carta, receita, notícia, anúncio, relatório).
// 40 semanas: frase da semana (lousa), 5 frases do dia (caderno),
// palavras da lousa e ditado com dica falada.

import type { SemanaEscrita } from "./rotina-escrita";

// [foco, fraseSemana, frases(5) separadas por |, palavras separadas por espaço, ditado "palavra=dica"]
type Linha = [string, string, string, string, string];

const LINHAS: Linha[] = [
  ["Retomada: frase e parágrafo", "Escrevo frases e junto ideias em parágrafo.", "Eu já escrevo frases inteiras.|Cada frase começa com maiúscula.|O ponto fecha a ideia.|Um parágrafo junta frases do mesmo assunto.|Este ano eu vou escrever textos.", "frase parágrafo ideia ponto texto início", "parágrafo=um grupo de frases sobre o mesmo assunto|frase=uma ideia completa|texto=várias frases com sentido juntas|ponto=fecha a frase|maiúscula=letra grande do começo|assunto=aquilo de que se fala"],
  ["S e SS entre vogais", "O passeio da professora foi ótimo.", "O passeio foi no parque.|A professora chamou a turma.|A casa tem um pássaro.|A rosa cheira bem.|Nossa massa ficou boa.", "passeio professora pássaro casa rosa massa", "passeio=quando saímos para andar e ver coisas|professora=quem ensina na escola|pássaro=animal que voa e canta|casa=lugar onde moramos|rosa=flor com espinhos|massa=macarrão ou mistura de bolo"],
  ["Ç antes de A, O, U", "O açúcar caiu no coração do laço.", "O açúcar é doce.|Eu faço a lição sozinho.|O coração bate forte.|A caça ao tesouro começou.|A poça de água secou.", "açúcar faço coração caça poça licença", "açúcar=deixa a comida doce|faço=quando eu realizo algo|coração=bate dentro do peito|caça=procura por algo|poça=água parada no chão|licença=quando pedimos permissão"],
  ["C antes de E e I", "A cidade acordou com cheiro de cebola.", "A cidade é grande.|A cebola faz chorar.|Fomos ao cinema.|O cimento secou.|Ele acendeu a luz.", "cidade cebola cinema cimento acender cesta", "cidade=lugar com muitas casas e ruas|cebola=legume que faz chorar|cinema=lugar de assistir filme|cimento=usado para construir|acender=fazer a luz ligar|cesta=usada para carregar coisas"],
  ["R e RR", "O carro correu perto do morro.", "O carro parou na esquina.|O cachorro correu atrás.|O morro é bem alto.|A terra está molhada.|A serra cortou madeira.", "carro cachorro morro terra serra caro", "carro=veículo de quatro rodas|cachorro=late e abana o rabo|morro=uma subida de terra|terra=o chão onde plantamos|serra=ferramenta que corta|caro=custa muito dinheiro"],
  ["G e GU / C e QU", "Quase a guitarra caiu no queijo.", "A guitarra toca alto.|O queijo é branco.|Eu quero água gelada.|A guerra acabou.|A garrafa é minha.", "guitarra queijo quero guerra garrafa quinze", "guitarra=instrumento de cordas|queijo=alimento feito de leite|quero=tenho vontade de|guerra=briga entre países|garrafa=guarda líquido com tampa|quinze=vem depois do catorze"],
  ["M antes de P e B", "O campo tem um bambu bonito.", "O campo é verde.|Eu também vou.|O bombom acabou.|A lâmpada acendeu.|O tempo passou rápido.", "campo também bombom lâmpada tempo sempre", "campo=lugar aberto fora da cidade|também=quando é igual|bombom=doce de chocolate|lâmpada=acende e ilumina|tempo=as horas que passam|sempre=todas as vezes"],
  ["Sons do nariz: ÃO e AM", "Ontem eles cantaram e amanhã cantarão.", "As crianças brincaram.|Elas brincarão amanhã.|O pão está quente.|Meu irmão chegou.|Os leões rugiram.", "cantaram cantarão pão irmão leões balões", "cantaram=já cantaram, no passado|cantarão=vão cantar, no futuro|pão=comemos no café|irmão=filho dos mesmos pais|leões=mais de um leão|balões=mais de um balão"],
  ["Dígrafos LH, NH, CH", "O passarinho fez ninho no galho.", "O filho abriu os olhos.|O ninho tem ovos.|A chuva molhou a chave.|O trabalho acabou.|Eu tive um sonho.", "filho ninho chuva trabalho sonho telhado", "filho=o menino dos pais|ninho=casa do passarinho|chuva=água que cai do céu|trabalho=o serviço das pessoas|sonho=o que vemos dormindo|telhado=cobre a casa"],
  ["Sílabas: contar e separar", "Casa tem duas sílabas e escola tem três.", "Ca-sa tem duas sílabas.|Es-co-la tem três sílabas.|Pá tem uma sílaba.|Bor-bo-le-ta tem quatro.|Eu conto batendo palma.", "sílaba monossílaba dissílaba trissílaba polissílaba palma", "sílaba=cada batida da palavra|monossílaba=palavra de uma sílaba|dissílaba=palavra de duas sílabas|trissílaba=palavra de três sílabas|polissílaba=palavra de quatro ou mais|palma=batemos para contar sílabas"],
  ["Sílaba tônica", "A batida forte da palavra tem nome.", "Ca-FÉ é oxítona.|BO-ne-ca é paroxítona.|SÁ-ba-do é proparoxítona.|A batida forte é a tônica.|Eu bato palma na mais forte.", "tônica oxítona paroxítona proparoxítona forte batida", "tônica=a sílaba mais forte da palavra|oxítona=palavra com a força na última sílaba|paroxítona=força na penúltima sílaba|proparoxítona=força na antepenúltima|forte=onde a voz bate mais|batida=cada golpe de voz na sílaba"],
  ["Acento agudo", "O café do sofá caiu no cipó.", "O café está quente.|O sofá é azul.|A vovó fez bolo.|O cipó subiu no muro.|O pé dói.", "café sofá vovó cipó pé jacaré", "café=bebida quente escura|sofá=móvel de sentar|vovó=a mãe da mãe|cipó=planta que sobe|pé=fica no fim da perna|jacaré=animal de rio com couro duro"],
  ["Acento circunflexo", "O avô comprou três bolos.", "O avô chegou hoje.|Eu li três livros.|O vovô contou histórias.|O pêssego é doce.|Ele pôs a mesa.", "avô vovô três pêssego você mês", "avô=o pai do pai|vovô=jeito carinhoso de chamar o avô|três=vem depois do dois|pêssego=fruta macia e doce|você=quando falamos com alguém|mês=trinta dias mais ou menos"],
  ["Ponto, interrogação e exclamação", "Você viu? Que legal!", "Onde está meu livro?|Que susto eu levei!|A aula começou.|Quem chegou agora?|Parabéns para você!", "pergunta resposta susto aviso ponto exclamação", "pergunta=quando queremos saber algo|resposta=o que se fala de volta|susto=quando levamos uma surpresa|aviso=quando informamos algo|ponto=fecha a frase|exclamação=mostra emoção forte"],
  ["Dois-pontos e travessão no diálogo", "— Você viu a joia? — perguntou Marina.", "— Bom dia! — disse Aurora.|Marina respondeu: — Eu vi.|— Onde estava? — quis saber Theo.|— Na gaveta — contou ela.|O diálogo usa travessão.", "diálogo travessão dois-pontos fala responder perguntar", "diálogo=conversa entre personagens|travessão=risquinho que abre a fala|dois-pontos=anunciam a fala ou a lista|fala=o que o personagem diz|responder=dizer de volta|perguntar=querer saber algo"],
  ["Vírgula na lista e no aviso", "Comprei pão, leite, queijo e ovo.", "Trouxe lápis, régua e cola.|Gosto de uva, pera e maçã.|Marina, venha aqui.|Depois do almoço, vamos ler.|Vi cães, gatos e aves.", "vírgula lista pausa item chamado ordem", "vírgula=faz uma pausa curta|lista=vários itens em sequência|pausa=parada rápida na leitura|item=cada coisa da lista|chamado=quando falamos o nome de alguém|ordem=a sequência certa"],
  ["Substantivo comum e próprio", "Rex é o nome do meu cachorro.", "O cachorro late alto.|Rex é o nome dele.|Marina mora em Recife.|A cidade é grande.|Nomes próprios têm maiúscula.", "substantivo comum próprio nome cidade maiúscula", "substantivo=a palavra que dá nome às coisas|comum=serve para qualquer um do grupo|próprio=é o nome de um só|nome=como chamamos alguém ou algo|cidade=lugar com muitas ruas|maiúscula=letra grande"],
  ["Adjetivo", "O gato preto é muito esperto.", "O gato é preto.|A casa é grande.|O dia está bonito.|A prova foi difícil.|Minha amiga é alegre.", "adjetivo preto grande bonito difícil alegre", "adjetivo=diz como é a coisa ou a pessoa|preto=cor bem escura|grande=de tamanho maior|bonito=agradável de ver|difícil=que dá trabalho|alegre=quem está feliz"],
  ["Verbo: ação e tempo", "Ontem eu corri, hoje eu corro, amanhã correrei.", "Eu corro no parque.|Ontem eu corri muito.|Amanhã eu correrei.|Ela escreve um bilhete.|Nós lemos o texto.", "verbo ação presente passado futuro correr", "verbo=palavra que mostra a ação|ação=aquilo que alguém faz|presente=acontece agora|passado=já aconteceu|futuro=vai acontecer|correr=ir bem rápido"],
  ["Aumentativo e diminutivo", "O gatinho virou um gatão.", "O gatinho é pequeno.|O gatão é enorme.|A casinha é de boneca.|O portão é grande.|O livrinho é fininho.", "gatinho gatão casinha portão livrinho narigão", "gatinho=gato pequeno|gatão=gato grande|casinha=casa pequena|portão=porta bem grande|livrinho=livro pequeno|narigão=nariz grande"],
  ["Prefixo e sufixo", "Refazer é fazer de novo.", "Refiz a lição.|O trabalho é infeliz? Não, é feliz.|O padeiro faz pão.|A leiteira guarda leite.|Desfiz o nó.", "refazer desfazer padeiro leiteira infeliz felizmente", "refazer=fazer outra vez|desfazer=desmontar o que foi feito|padeiro=quem faz pão|leiteira=recipiente do leite|infeliz=sem felicidade|felizmente=por sorte"],
  ["Sinônimo e antônimo", "Alegre é o contrário de triste.", "Alegre é o mesmo que feliz.|Triste é o contrário de alegre.|Grande e pequeno.|Bonito e feio.|Perto e longe.", "sinônimo antônimo alegre triste grande pequeno", "sinônimo=palavra de sentido parecido|antônimo=palavra de sentido contrário|alegre=quem está feliz|triste=sem alegria|grande=de tamanho maior|pequeno=de tamanho menor"],
  ["Bilhete de verdade", "Deixei um bilhete na porta da geladeira.", "Escrevo a data no bilhete.|Digo para quem é.|Escrevo o recado curto.|Assino meu nome.|Entrego o bilhete.", "bilhete data recado assinatura destinatário aviso", "bilhete=recado curto escrito|data=o dia, o mês e o ano|recado=a mensagem|assinatura=nome escrito no fim|destinatário=quem vai receber|aviso=quando informamos algo"],
  ["Carta pessoal", "Escrevi uma carta para a minha avó.", "Coloco a cidade e a data.|Começo com Querida vovó.|Conto as novidades.|Termino com um abraço.|Assino meu nome.", "carta remetente destinatário saudação despedida envelope", "carta=texto mais longo enviado a alguém|remetente=quem envia|destinatário=quem recebe|saudação=o cumprimento do começo|despedida=o fim carinhoso|envelope=guarda a carta"],
  ["Diário", "No meu diário eu conto o meu dia.", "Escrevo a data de hoje.|Conto o que aconteceu.|Digo como eu me senti.|Escrevo na primeira pessoa.|Guardo o diário comigo.", "diário data sentimento lembrança dia relato", "diário=caderno em que contamos nosso dia|data=o dia de hoje|sentimento=o que sentimos|lembrança=o que guardamos na memória|dia=das 24 horas|relato=quando contamos o que viveu"],
  ["Receita: ingredientes e modo", "A receita tem ingredientes e modo de fazer.", "Escrevo os ingredientes.|Coloco a quantidade certa.|Numero os passos.|Uso verbos de ordem: misture.|Digo o tempo do forno.", "receita ingrediente quantidade passo misture forno", "receita=ensina a fazer comida|ingrediente=cada coisa que entra|quantidade=quanto se usa de cada|passo=cada etapa|misture=juntar mexendo|forno=assa a comida"],
  ["Instruções de jogo", "As regras dizem como jogar.", "Escrevo os materiais.|Explico como começa.|Digo a ordem das jogadas.|Explico quem ganha.|Leio para um amigo testar.", "regra material jogada vencedor ordem instrução", "regra=o que se pode e não se pode|material=o que é preciso ter|jogada=cada vez que alguém joga|vencedor=quem ganha|ordem=a sequência|instrução=explicação de como fazer"],
  ["Notícia: manchete e lide", "Gato é resgatado em árvore da praça.", "Escrevo a manchete curta.|O lide diz quem e o quê.|Digo quando e onde.|Conto como aconteceu.|Não coloco opinião.", "manchete lide notícia repórter fato ocorrido", "manchete=título curto da notícia|lide=primeiro parágrafo com quem, o quê, quando e onde|notícia=texto que informa um fato|repórter=quem apura e escreve|fato=o que realmente aconteceu|ocorrido=aquilo que se passou"],
  ["Fato e opinião", "O jogo foi 3 a 1. Eu achei bonito.", "O jogo terminou 3 a 1.|Eu acho que foi bonito.|Choveu no domingo.|Na minha opinião, é o melhor.|Fato se confere, opinião se discute.", "fato opinião conferir achar discutir prova", "fato=o que pode ser conferido|opinião=o que alguém acha|conferir=checar se é verdade|achar=ter uma opinião|discutir=trocar ideias|prova=o que confirma um fato"],
  ["Carta do leitor", "Escrevi ao jornal para pedir uma praça limpa.", "Digo para quem escrevo.|Explico o problema.|Dou um argumento.|Peço uma solução.|Agradeço e assino.", "leitor jornal problema argumento solução pedido", "leitor=quem lê|jornal=traz as notícias|problema=aquilo que está errado|argumento=a razão que sustenta a ideia|solução=o jeito de resolver|pedido=o que se solicita"],
  ["Anúncio e campanha", "Economize água: feche a torneira!", "Uso frase curta e forte.|Escolho palavras que convencem.|Uso verbo de ordem.|Explico o motivo.|Coloco uma imagem.", "anúncio campanha convencer slogan público motivo", "anúncio=texto que divulga algo|campanha=ação para mudar um hábito|convencer=fazer alguém concordar|slogan=frase curta que fica na cabeça|público=quem vai ler|motivo=a razão de algo"],
  ["Relato de observação", "Observei a planta por cinco dias.", "Escrevo o que observei.|Anoto a data de cada dia.|Descrevo o que mudou.|Uso números e medidas.|Escrevo a conclusão.", "observar anotar medida mudança conclusão registro", "observar=olhar com atenção|anotar=escrever para não esquecer|medida=quanto algo tem|mudança=quando algo fica diferente|conclusão=o que aprendemos no fim|registro=a anotação guardada"],
  ["Relatório de pesquisa", "Pesquisei sobre abelhas em dois livros.", "Escolho o tema da pesquisa.|Escrevo as perguntas.|Busco em livro e site confiável.|Escrevo com minhas palavras.|Digo de onde tirei.", "pesquisa tema fonte confiável resumo referência", "pesquisa=busca de informação sobre um tema|tema=o assunto escolhido|fonte=de onde vem a informação|confiável=em que se pode acreditar|resumo=texto curto com o principal|referência=onde a informação foi achada"],
  ["Parágrafo com tópico frasal", "Cada parágrafo começa com a ideia principal.", "A primeira frase diz a ideia.|As outras explicam.|Um exemplo ajuda o leitor.|O parágrafo fecha a ideia.|Depois começo outro parágrafo.", "tópico ideia explicação exemplo fechamento recuo", "tópico=a frase que abre o parágrafo|ideia=aquilo que queremos dizer|explicação=quando detalhamos algo|exemplo=um caso que mostra a ideia|fechamento=o fim do parágrafo|recuo=o espaço no começo do parágrafo"],
  ["Descrever lugar e pessoa", "Minha rua é estreita e cheia de árvores.", "A rua é estreita.|As árvores dão sombra.|Minha amiga é alta e alegre.|O cabelo dela é cacheado.|Uso adjetivos para descrever.", "descrever estreita sombra cacheado detalhe característica", "descrever=dizer como é|estreita=pouco larga|sombra=onde o sol não bate|cacheado=cabelo com cachos|detalhe=uma parte pequena|característica=aquilo que a coisa tem de próprio"],
  ["Narrar: começo, conflito e desfecho", "A história tem começo, problema e fim.", "No começo tudo estava calmo.|Então apareceu um problema.|O personagem tentou resolver.|Ele conseguiu com ajuda.|No fim todos ficaram bem.", "começo conflito desfecho personagem cenário solução", "começo=onde a história inicia|conflito=o problema da história|desfecho=como a história termina|personagem=quem vive a história|cenário=onde acontece|solução=o jeito de resolver"],
  ["Poema: verso, estrofe e rima", "Cada linha é um verso e o grupo é estrofe.", "Escrevo quatro versos.|As linhas rimam no fim.|Junto os versos em estrofe.|Leio em voz alta no ritmo.|Escolho palavras que rimam.", "verso estrofe rima ritmo poema sonoridade", "verso=cada linha do poema|estrofe=grupo de versos|rima=sons iguais no fim dos versos|ritmo=a batida da leitura|poema=texto em versos|sonoridade=o som das palavras juntas"],
  ["Palavras que enganam", "Eu quero mais bolo, mas não tenho fome.", "Eu quero mais suco.|Fui à feira, mas não comprei.|Ele é mau aluno? Não!|Eu me sinto mal hoje.|Há um ano eu vim aqui.", "mais mas mau mal há a", "mais=indica quantidade|mas=indica o contrário|mau=o contrário de bom|mal=o contrário de bem|há=existe ou tempo passado|a=artigo ou para onde vamos"],
  ["Revisar o próprio texto", "Releio, conserto e passo a limpo.", "Releio o meu rascunho.|Confiro maiúscula e ponto.|Vejo se falta palavra.|Corrijo a ortografia duvidosa.|Passo a limpo com capricho.", "rascunho revisão correção limpo capricho conferir", "rascunho=a primeira versão|revisão=quando conferimos tudo|correção=arrumar o erro|limpo=a versão final|capricho=feito com cuidado|conferir=checar se está certo"],
  ["Sou autor de verdade", "Eu escrevo, revejo e publico meus textos.", "Escolho o gênero do texto.|Planejo antes de escrever.|Escrevo o rascunho.|Revejo com a lista de conferência.|Leio para a turma.", "autor gênero planejar rascunho publicar apresentar", "autor=quem escreve o texto|gênero=o tipo de texto (carta, receita, notícia)|planejar=pensar antes de fazer|rascunho=primeira versão|publicar=deixar outros lerem|apresentar=mostrar para as pessoas"],
];

export const SEMANAS_ESCRITA_3ANO: SemanaEscrita[] = LINHAS.map((l, i) => ({
  semana: i + 1,
  foco: l[0],
  fraseSemana: l[1],
  frasesDia: l[2].split("|"),
  palavrasLousa: l[3].split(" "),
  ditado: l[4].split("|").map((d) => {
    const [palavra, dica] = d.split("=");
    return { palavra, dica };
  }),
}));
