// Rotina de Escrita Diária — 2º ano (7 anos)
// Mesmo formato do 1º ano, mas calibrado para quem já decodifica:
// o foco sai da sílaba e vai para a ORTOGRAFIA, a pontuação e o texto curto.
// 40 semanas: frase da semana (lousa), 5 frases do dia (caderno),
// palavras da lousa e ditado com dica falada.

import type { SemanaEscrita } from "./rotina-escrita";

// [foco, fraseSemana, frases(5) separadas por |, palavras separadas por espaço, ditado "palavra=dica"]
type Linha = [string, string, string, string, string];

const LINHAS: Linha[] = [
  ["Retomada: sílabas e frase", "Eu já sei ler e escrever frases.", "Eu leio todo dia.|A escola começou.|Meu caderno é novo.|Eu escrevo meu nome.|Nós vamos aprender muito.", "escola caderno lápis nome turma leitura", "escola=lugar onde a gente estuda|caderno=onde escrevemos as lições|lápis=serve para escrever e apagar|turma=o grupo de colegas da sala|leitura=quando lemos um texto|amigo=quem brinca e ajuda a gente"],
  ["M antes de P e B", "O campo tem um bambu bonito.", "O campo é verde.|A bomba faz barulho.|Eu como um bombom.|A lâmpada acendeu.|O tempo passou rápido.", "campo tempo bombom lâmpada bamba sempre", "campo=lugar aberto fora da cidade|tempo=as horas que passam|bombom=doce de chocolate|lâmpada=acende e ilumina a casa|sempre=todas as vezes|comprido=o contrário de curto"],
  ["N antes das outras letras", "A ponte fica longe da onda.", "A ponte é de ferro.|A onda quebrou na praia.|O lanche está pronto.|Eu conto até dez.|O vento balançou a janela.", "ponte onda lanche vento conta janela", "ponte=passa por cima do rio|onda=a água que sobe no mar|lanche=comida do meio da tarde|vento=o ar que sopra|janela=abre para entrar luz|conta=quando somamos números"],
  ["R no meio: cara e carra", "O carro parou perto da cara.", "O carro é azul.|A cara dela é alegre.|O barco navega no mar.|A barriga do bebê.|Eu corro no parque.", "carro caro barco barriga corro coro", "carro=anda na rua com quatro rodas|caro=custa muito dinheiro|barco=anda na água|barriga=fica embaixo do peito|corro=quando eu vou rápido|coro=grupo que canta junto"],
  ["RR entre vogais", "O cachorro correu no morro.", "O cachorro late.|Eu corri até a esquina.|O morro é alto.|A terra está molhada.|A barriga do jarro.", "cachorro correu morro terra jarro serra", "cachorro=late e abana o rabo|morro=uma subida de terra|terra=o chão onde plantamos|jarro=guarda água ou flores|serra=corta madeira|garrafa=guarda líquido com tampa"],
  ["R no fim da sílaba", "Quero cantar e brincar.", "Vou cantar uma música.|Ele quer correr.|Eu vou dormir cedo.|Nós vamos partir.|Ela sabe pular.", "cantar correr dormir pular partir sorvete", "cantar=fazer música com a voz|correr=ir bem rápido com as pernas|dormir=fechar os olhos e descansar|pular=dar um salto|partir=ir embora|sorvete=gelado e doce"],
  ["S no começo: sapo", "O sapo saltou no sábado.", "O sapo é verde.|Eu sei somar.|A sopa está quente.|O sino tocou.|Sábado eu descanso.", "sapo sopa sino sala sede sábado", "sapo=pula e vive perto da água|sopa=comida quentinha de colher|sino=faz dim-dom na igreja|sala=cômodo da casa|sede=vontade de beber água|sábado=vem depois da sexta"],
  ["S entre vogais soa Z", "A casa da rosa é linda.", "A casa é grande.|A rosa é vermelha.|A camisa é nova.|A mesa está posta.|Eu uso o casaco.", "casa rosa camisa mesa asa vaso", "casa=lugar onde moramos|rosa=flor com espinhos|camisa=roupa do corpo|mesa=onde a gente come|asa=a ave voa com ela|vaso=guarda a planta"],
  ["SS entre vogais", "Nossa massa ficou boa.", "A massa está pronta.|Nossa turma é unida.|Eu passo o pão.|Ele assou o bolo.|A pessoa chegou.", "massa nossa passo pessoa assar osso", "massa=macarrão ou a mistura do bolo|nossa=algo que é de nós|passo=um pé na frente do outro|pessoa=um ser humano|assar=cozinhar no forno|osso=fica dentro do corpo"],
  ["Ç antes de A, O, U", "O açúcar caiu no laço.", "O açúcar é doce.|O laço é bonito.|Eu faço a lição.|A poça de água.|O caçador andou.", "açúcar laço faço poça caçar moça", "açúcar=deixa a comida doce|laço=fita amarrada|faço=quando eu realizo algo|poça=água parada no chão|caçar=ir atrás de algo|moça=mulher jovem"],
  ["C e QU: casa e quase", "Quase caiu o queijo quente.", "O queijo é branco.|Quase acabei a lição.|A casa é minha.|Eu quero água.|A cuca do bolo.", "queijo quase quero casa cuca quinze", "queijo=vem do leite|quase=por pouco|quero=tenho vontade de algo|cuca=cobertura do bolo|quinze=vem depois do catorze|quintal=pátio atrás da casa"],
  ["G e GU: gato e guerra", "O gato viu a guitarra.", "O gato dorme.|A guitarra toca.|A gota caiu.|O guarda ajudou.|A goiaba é doce.", "gato gota guarda guitarra goiaba gude", "gato=mia e gosta de dormir|gota=pinguinho de água|guarda=quem protege|guitarra=instrumento de cordas|goiaba=fruta rosada por dentro|gude=bolinha de brincar"],
  ["G e J com E e I", "O gelo do jeito certo.", "O gelo é frio.|O jeito dela é calmo.|A girafa é alta.|O jipe passou.|A gente brincou.", "gelo girafa gente jeito jipe janela", "gelo=água congelada|girafa=tem pescoço bem comprido|gente=as pessoas|jeito=a maneira de fazer|jipe=carro forte de estrada de terra|janela=por onde entra o sol"],
  ["CH: chuva e chave", "A chuva molhou a chave.", "A chuva caiu forte.|A chave abriu a porta.|O chão está limpo.|O chapéu é meu.|Eu cheguei cedo.", "chuva chave chão chapéu chulé chinelo", "chuva=água que cai do céu|chave=abre a fechadura|chão=onde pisamos|chapéu=protege a cabeça do sol|chinelo=sapato de andar em casa|chamar=falar o nome de alguém"],
  ["LH: filho e olho", "O filho abriu os olhos.", "O filho é pequeno.|O olho vê tudo.|A folha caiu.|A palha do telhado.|O trabalho acabou.", "filho olho folha palha telhado trabalho", "filho=o menino dos pais|olho=com ele enxergamos|folha=nasce na árvore ou é papel|palha=capim seco|telhado=cobre a casa|trabalho=o serviço das pessoas"],
  ["NH: ninho e sonho", "O passarinho fez um ninho.", "O ninho tem ovos.|Eu tive um sonho.|O banho é morno.|A caminho da escola.|O carinho da mamãe.", "ninho sonho banho caminho carinho manhã", "ninho=casa do passarinho|sonho=o que vemos dormindo|banho=quando lavamos o corpo|caminho=o percurso até um lugar|carinho=um abraço com amor|manhã=começo do dia"],
  ["Ponto final e maiúscula", "Toda frase começa grande e termina com ponto.", "O sol nasceu cedo.|Maria foi à escola.|Nós comemos bolo.|O gato subiu no muro.|A aula terminou.", "ponto frase maiúscula início término espaço", "ponto=fecha a frase|frase=ideia completa em palavras|maiúscula=letra grande do começo|início=onde algo começa|término=o fim|espaço=separa uma palavra da outra"],
  ["Ponto de interrogação", "Você quer brincar comigo?", "Onde está meu livro?|Quem chegou agora?|Como você se chama?|Por que o céu é azul?|Quando vamos sair?", "onde quem como quando pergunta resposta", "onde=pergunta sobre o lugar|quem=pergunta sobre a pessoa|como=pergunta sobre o jeito|quando=pergunta sobre o tempo|pergunta=quando queremos saber algo|resposta=o que se fala de volta"],
  ["Ponto de exclamação", "Que legal! Eu consegui!", "Que susto!|Eu venci!|Cuidado com o carro!|Que dia bonito!|Parabéns para você!", "susto venci cuidado parabéns oba viva", "susto=quando levamos um choque de surpresa|venci=ganhei|cuidado=aviso para tomar atenção|parabéns=falamos quando alguém conquista algo|oba=grito de alegria|viva=comemoração"],
  ["Vírgula na lista", "Comprei pão, leite, queijo e ovo.", "Trouxe lápis, borracha e régua.|Gosto de uva, maçã e pera.|Vi cães, gatos e aves.|Comi arroz, feijão e carne.|Levei bola, corda e pipa.", "vírgula lista pausa item último enumerar", "vírgula=faz uma pausa curta|lista=vários itens em sequência|pausa=parada rápida na leitura|item=cada coisa da lista|último=o que fica no fim|enumerar=citar um por um"],
  ["Palavras com AO e ÃO", "O pão do irmão caiu no chão.", "O pão está quente.|Meu irmão chegou.|O chão é frio.|A mão está limpa.|O caminhão passou.", "pão irmão chão mão caminhão coração", "pão=comemos no café|irmão=filho dos mesmos pais|chão=o piso|mão=fica no fim do braço|caminhão=carro grande de carga|coração=bate dentro do peito"],
  ["Plural com S e ÕES", "Os leões comeram os pães.", "Os leões rugiram.|Comprei dois pães.|Vi três balões.|As mãos estão frias.|Os irmãos brincaram.", "leões pães balões mãos irmãos aviões", "leões=mais de um leão|pães=mais de um pão|balões=mais de um balão|mãos=as duas juntas|irmãos=mais de um irmão|aviões=mais de um avião"],
  ["Acento agudo", "O café é do vovô e da vovó.", "O café está quente.|A vovó fez bolo.|O pé dói.|Eu vi o avô.|A água é fria.", "café pé vovó avô água hérói", "café=bebida quente escura|pé=fica no fim da perna|vovó=a mãe da mãe|avô=o pai do pai|água=bebemos todo dia|herói=quem faz coisas corajosas"],
  ["Til: ã e õ", "A irmã do avião viu o limão.", "A irmã chegou.|O avião voou alto.|O limão é azedo.|A manhã está clara.|A ração do cachorro.", "irmã avião limão manhã ração maçã", "irmã=filha dos mesmos pais|avião=voa pelo céu|limão=fruta azeda e verde|manhã=parte do dia antes do almoço|ração=comida do bichinho|maçã=fruta vermelha e doce"],
  ["Encontros BR, CR, DR", "O braço do cravo na dracena.", "O braço dói.|A cruz é branca.|O dragão soltou fogo.|Eu bebo o creme.|A brisa é boa.", "braço branco cruz dragão creme brisa", "braço=parte do corpo com a mão na ponta|branco=cor da neve|cruz=duas linhas que se cortam|dragão=bicho de história que solta fogo|creme=mistura mole e macia|brisa=vento leve"],
  ["Encontros FL, CL, PL", "A flor da classe é do plano.", "A flor abriu.|A classe está limpa.|O plano deu certo.|A flauta tocou.|O clima é quente.", "flor classe plano flauta clima planta", "flor=nasce na planta|classe=a sala de aula|plano=o que combinamos fazer|flauta=instrumento de sopro|clima=o tempo de um lugar|planta=nasce da terra"],
  ["Encontros GR, TR, PR", "O trem grande passou perto.", "O trem apitou.|A grama cresceu.|O prato quebrou.|Eu trouxe o pão.|O prêmio é meu.", "trem grama prato prêmio grande trilho", "trem=anda nos trilhos|grama=capim verde|prato=comemos nele|prêmio=o que ganhamos|grande=o contrário de pequeno|trilho=por onde o trem anda"],
  ["Sílabas com L no fim", "O sol some no final do dia.", "O sol brilha.|O papel é branco.|O sal é salgado.|O anzol pegou o peixe.|O jornal chegou.", "sol papel sal anzol jornal álbum", "sol=ilumina o dia|papel=escrevemos nele|sal=deixa a comida salgada|anzol=pega peixe|jornal=traz as notícias|álbum=guarda fotos"],
  ["Bilhete de verdade", "Escrevi um bilhete para a professora.", "Escrevo o bilhete.|Coloco a data.|Escrevo o recado.|Assino meu nome.|Entrego o bilhete.", "bilhete data recado assinatura envelope aviso", "bilhete=recado curto escrito|data=o dia, o mês e o ano|recado=a mensagem que passamos|assinatura=o nome que escrevemos no fim|envelope=guarda a carta|aviso=quando informamos algo"],
  ["Lista e receita", "Fiz a lista de compras da semana.", "Escrevo a lista.|Compro arroz e feijão.|A receita tem ovos.|Misturo a farinha.|Levo ao forno.", "lista receita ingrediente farinha forno mistura", "lista=itens um embaixo do outro|receita=ensina a fazer comida|ingrediente=cada coisa da receita|farinha=pó branco do bolo|forno=assa a comida|mistura=quando juntamos tudo"],
  ["Convite", "Você está convidado para minha festa!", "Escrevo o convite.|Coloco o dia e a hora.|Escrevo o lugar.|Entrego ao amigo.|Espero a resposta.", "convite festa hora lugar convidado resposta", "convite=chamamos alguém para um evento|festa=comemoração com amigos|hora=o momento marcado|lugar=onde vai acontecer|convidado=quem foi chamado|resposta=quando dizem sim ou não"],
  ["Descrição de um lugar", "Meu quarto é pequeno e azul.", "Meu quarto é azul.|A cama fica na janela.|O armário é grande.|Tem um tapete no chão.|Eu gosto do meu quarto.", "quarto cama armário tapete parede janela", "quarto=onde dormimos|cama=onde deitamos|armário=guarda as roupas|tapete=fica no chão|parede=fecha o cômodo|janela=deixa entrar a luz"],
  ["Descrição de pessoa", "Minha amiga tem cabelo cacheado.", "Ela é alta e alegre.|O cabelo é cacheado.|Os olhos são castanhos.|Ela gosta de ler.|Ela é minha amiga.", "cabelo olhos alegre alta castanho sorriso", "cabelo=nasce na cabeça|olhos=com eles enxergamos|alegre=quem está feliz|alta=o contrário de baixa|castanho=cor de marrom claro|sorriso=quando a boca fica feliz"],
  ["Narrar: começo, meio e fim", "No começo eu corri, no fim eu venci.", "No começo eu acordei.|Depois eu me arrumei.|Então saí de casa.|Mais tarde eu brinquei.|No fim eu dormi.", "começo depois então tarde fim ordem", "começo=onde a história inicia|depois=o que vem em seguida|então=quando algo acontece na sequência|tarde=parte do dia após o almoço|fim=onde termina|ordem=a sequência certa"],
  ["Reconto de história", "Recontei a história com minhas palavras.", "O personagem saiu de casa.|Ele encontrou um problema.|Pediu ajuda a um amigo.|Resolveu tudo com coragem.|Voltou feliz para casa.", "personagem problema ajuda coragem final história", "personagem=quem vive a história|problema=a dificuldade que aparece|ajuda=quando alguém apoia|coragem=enfrentar o medo|final=o desfecho|história=narrativa com começo e fim"],
  ["Palavras parecidas", "O mais e o mas não são iguais.", "Eu quero mais bolo.|Eu fui, mas não vi.|A casa é dela.|Eu vou à escola.|Ele mora aqui há um ano.", "mais mas há a dela nele", "mais=quando queremos quantidade|mas=indica o contrário|há=quando falamos do tempo passado|dela=algo que pertence a ela|nele=dentro dele|também=quando é igual"],
  ["Sinônimos e antônimos", "Alegre é o contrário de triste.", "Alegre é feliz.|Triste é o contrário.|Grande e pequeno.|Quente e frio.|Perto e longe.", "alegre triste grande pequeno quente frio", "alegre=quem está feliz|triste=quem está sem alegria|grande=de tamanho maior|pequeno=de tamanho menor|quente=com muito calor|frio=com pouco calor"],
  ["Texto informativo", "A abelha faz mel na colmeia.", "A abelha voa nas flores.|Ela leva o pólen.|Faz o mel na colmeia.|O mel é doce.|A abelha ajuda a natureza.", "abelha flor pólen colmeia mel natureza", "abelha=inseto que faz mel|flor=nasce na planta|pólen=pozinho da flor|colmeia=casa das abelhas|mel=doce e dourado|natureza=tudo que existe sem o ser humano"],
  ["Revisar o que escrevi", "Eu leio e conserto o que escrevi.", "Eu releio a frase.|Confiro a maiúscula.|Coloco o ponto.|Vejo o espaço entre palavras.|Passo a limpo.", "reler conferir corrigir limpo revisão erro", "reler=ler de novo|conferir=checar se está certo|corrigir=arrumar o erro|limpo=a versão final e caprichada|revisão=quando conferimos tudo|erro=o que precisa ser arrumado"],
  ["Sou autor de verdade", "Eu escrevo meus próprios textos!", "Eu escolho o tema.|Escrevo o rascunho.|Revejo meu texto.|Passo a limpo.|Leio para a turma.", "tema rascunho revisão limpo autor texto", "tema=o assunto do texto|rascunho=a primeira versão|revisão=quando conferimos e melhoramos|limpo=a versão final|autor=quem escreve|texto=um conjunto de frases com sentido"],
];

export const SEMANAS_ESCRITA_2ANO: SemanaEscrita[] = LINHAS.map((l, i) => ({
  semana: i + 1,
  foco: l[0],
  fraseSemana: l[1],
  frasesDia: l[2].split("|"),
  palavrasLousa: l[3].split(" "),
  ditado: l[4].split("|").map((d) => {
    const [palavra, dica] = d.split("=");
    return { palavra, dica };
  }),
}));
