// Rotina de Escrita Diária — 4º ano (9 anos)
// Mesmo formato do 1º, 2º e 3º ano, calibrado para quem já escreve
// parágrafos: o foco vai para COESÃO TEXTUAL, ACENTUAÇÃO (paroxítona,
// hiato), GRAMÁTICA EM USO (concordância, tempos verbais, conectivos)
// e PRODUÇÃO DE GÊNEROS (reportagem, verbete, carta de leitor, anúncio,
// texto teatral). 40 semanas: frase da semana (lousa), 5 frases do dia
// (caderno), palavras da lousa e ditado com dica falada.

import type { SemanaEscrita } from "./rotina-escrita";

// [foco, fraseSemana, frases(5) separadas por |, palavras separadas por espaço, ditado "palavra=dica"]
type Linha = [string, string, string, string, string];

const LINHAS: Linha[] = [
  [
    "Retomada: parágrafo com tópico frasal",
    "A primeira frase do parágrafo anuncia a ideia.",
    "Eu já escrevo parágrafos.|A primeira frase é o tópico.|As outras frases explicam a ideia.|Um parágrafo trata de um só assunto.|Este ano eu escrevo textos maiores.",
    "parágrafo tópico ideia assunto explicação texto",
    "parágrafo=grupo de frases sobre um assunto|tópico=frase que abre o parágrafo|ideia=aquilo que se quer dizer|assunto=de que se fala|explicação=detalhe que esclarece|texto=conjunto de parágrafos",
  ],
  [
    "Acentuação: paroxítona terminada em L, N, R, X, PS",
    "O açúcar e o revólver ficaram no túnel.",
    "O açúcar é doce.|O revólver é perigoso.|O túnel é escuro.|O caráter dela é firme.|O fácil vira difícil.",
    "açúcar revólver túnel caráter fácil útil",
    "açúcar=deixa a comida doce|revólver=arma de fogo pequena|túnel=passagem sob a terra|caráter=jeito de ser da pessoa|fácil=que não dá trabalho|útil=que serve para algo",
  ],
  [
    "Acentuação: paroxítona terminada em I, US, UM",
    "O júri viu o vírus no álbum.",
    "O júri decide o caso.|O vírus é pequeno.|O álbum guarda fotos.|O lápis está na mesa.|O tênis é confortável.",
    "júri vírus álbum lápis tênis ônibus",
    "júri=grupo que julga um caso|vírus=causa doenças|álbum=guarda fotos ou figurinhas|lápis=usado para escrever|tênis=calçado esportivo|ônibus=transporte coletivo",
  ],
  [
    "Ditongo e hiato",
    "O saguão tinha um baú cheio de moedas.",
    "O saguão é grande.|O baú guarda tesouros.|Eu comi saída de manhã cedo.|O país é enorme.|A saúde vem em primeiro lugar.",
    "saguão baú saída país saúde ruído",
    "saguão=entrada grande de um lugar|baú=caixa para guardar coisas|saída=por onde se sai|país=nação com governo próprio|saúde=bem-estar do corpo|ruído=som forte e incômodo",
  ],
  [
    "Dígrafos e encontros consonantais",
    "O astronauta trouxe uma pedra estranha.",
    "O astronauta viajou ao espaço.|A pedra é estranha.|O planeta gira sozinho.|A estrela brilha à noite.|O foguete decolou rápido.",
    "astronauta estranha planeta estrela foguete transporte",
    "astronauta=viaja ao espaço|estranha=diferente do comum|planeta=corpo que gira ao redor do sol|estrela=brilha no céu à noite|foguete=leva o astronauta ao espaço|transporte=meio de se locomover",
  ],
  [
    "Concordância nominal",
    "As meninas espertas resolveram o enigma difícil.",
    "As meninas são espertas.|Os meninos são espertos.|A prova foi difícil.|Os problemas foram difíceis.|As casas antigas são bonitas.",
    "espertas espertos difícil difíceis antigas concordar",
    "espertas=plural feminino de esperto|espertos=plural masculino de esperto|difícil=singular|difíceis=plural de difícil|antigas=plural feminino de antigo|concordar=combinar gênero e número",
  ],
  [
    "Concordância verbal",
    "Os alunos estudaram e a professora explicou.",
    "Os alunos estudaram muito.|A turma aprendeu rápido.|Eu e você resolvemos o problema.|Nós fizemos o trabalho.|Elas terminaram primeiro.",
    "estudaram aprendeu resolvemos fizemos terminaram sujeito",
    "estudaram=verbo concordando com plural|aprendeu=verbo concordando com singular|resolvemos=nós resolvemos|fizemos=nós fizemos|terminaram=elas terminaram|sujeito=quem pratica a ação",
  ],
  [
    "Verbo no presente, passado e futuro",
    "Eu estudo hoje, estudei ontem e estudarei amanhã.",
    "Eu estudo todo dia.|Ontem eu estudei história.|Amanhã eu estudarei geografia.|Ela lê um livro agora.|Amanhã ela lerá outro.",
    "estudo estudei estudarei leio li lerei",
    "estudo=presente de estudar|estudei=passado de estudar|estudarei=futuro de estudar|leio=presente de ler|li=passado de ler|lerei=futuro de ler",
  ],
  [
    "Pronomes pessoais e possessivos",
    "Eu trouxe o meu livro, e ela trouxe o dela.",
    "Eu trouxe meu caderno.|Ele perdeu o seu lápis.|Nós levamos nossa bola.|Elas guardaram suas mochilas.|Você viu a sua agenda?",
    "meu seu nossa suas eu você",
    "meu=pertence a mim|seu=pertence a ele ou você|nossa=pertence a nós|suas=pertence a elas, no plural|eu=quem fala|você=com quem se fala",
  ],
  [
    "Conectivos de adição e oposição",
    "Estudei muito, mas ainda tenho dúvidas.",
    "Eu estudei e também revisei.|Gosto de matemática, mas prefiro português.|Ela correu, porém chegou depois.|Além disso, ela treinou bastante.|Apesar da chuva, fomos à escola.",
    "mas porém além apesar contudo entretanto",
    "mas=liga ideias opostas|porém=indica contraste|além=acrescenta uma informação|apesar=mostra um obstáculo superado|contudo=liga ideias com contraste|entretanto=indica oposição",
  ],
  [
    "Conectivos de causa e consequência",
    "Choveu muito, por isso a aula foi cancelada.",
    "Estudei bastante, por isso fui bem.|Não dormi, portanto estou cansado.|Como choveu, ficamos em casa.|A ponte quebrou, então mudamos a rota.|Ele treinou muito, logo melhorou.",
    "portanto por isso então logo como consequência",
    "portanto=indica consequência|por isso=liga causa e efeito|então=mostra o resultado|logo=indica consequência rápida|como=introduz a causa|consequência=o que resulta de algo",
  ],
  [
    "Discurso direto e indireto",
    "Ela disse: — Eu vou ganhar. Ela disse que ia ganhar.",
    "— Eu vou ganhar — disse Marina.|Marina disse que ia ganhar.|— Estou com fome — falou Theo.|Theo falou que estava com fome.|O discurso direto usa travessão.",
    "discurso direto indireto travessão falar disse",
    "discurso=forma de reproduzir a fala|direto=reproduz exatamente o que foi dito|indireto=conta o que foi dito sem citar|travessão=marca a fala direta|falar=comunicar algo|disse=passado de dizer",
  ],
  [
    "Pontuação: vírgula em aposto e vocativo",
    "Marina, minha amiga, chegou cedo.",
    "João, meu vizinho, é gentil.|Venha aqui, Pedro.|O Brasil, meu país, é enorme.|Ana, você viu meu livro?|A capital, Brasília, é planejada.",
    "aposto vocativo vírgula explicação chamado nome",
    "aposto=explica ou detalha o substantivo|vocativo=chama alguém na frase|vírgula=pausa curta na escrita|explicação=informação extra|chamado=quando se dirige a alguém|nome=identifica pessoa ou lugar",
  ],
  [
    "Substantivos coletivos",
    "O cardume nadou perto do enxame de abelhas.",
    "O cardume tem muitos peixes.|O enxame tem muitas abelhas.|A matilha tem vários cães.|A tropa tem muitos soldados.|O arquipélago tem várias ilhas.",
    "cardume enxame matilha tropa arquipélago coletivo",
    "cardume=grupo de peixes|enxame=grupo de abelhas|matilha=grupo de cães|tropa=grupo de soldados|arquipélago=grupo de ilhas|coletivo=palavra que nomeia um grupo",
  ],
  [
    "Prefixos e sufixos avançados",
    "O impossível se tornou possível com paciência.",
    "Isso é impossível? Não, é possível.|A atitude foi desleal.|Ela é uma pessoa gentileza.|O trabalho ficou incompleto.|A leitura é agradável.",
    "impossível desleal gentileza incompleto agradável desfazer",
    "impossível=não é possível|desleal=sem lealdade|gentileza=qualidade de ser gentil|incompleto=que falta algo|agradável=que agrada|desfazer=desmontar algo pronto",
  ],
  [
    "Sinônimos e antônimos em contexto",
    "Veloz é o mesmo que rápido; lento é o oposto.",
    "Veloz e rápido têm o mesmo sentido.|Lento é o oposto de rápido.|Feliz e alegre são sinônimos.|Triste é antônimo de alegre.|Grande e enorme são parecidos.",
    "veloz lento sinônimo antônimo contexto sentido",
    "veloz=muito rápido|lento=devagar|sinônimo=palavra de sentido parecido|antônimo=palavra de sentido oposto|contexto=situação em que a palavra aparece|sentido=o significado da palavra",
  ],
  [
    "Reportagem: título e fonte",
    "A reportagem traz título, fonte e dados.",
    "Escrevo um título chamativo.|Cito a fonte da informação.|Uso dados e números.|Entrevisto uma pessoa envolvida.|Organizo em parágrafos curtos.",
    "reportagem título fonte dado entrevista parágrafo",
    "reportagem=texto jornalístico mais detalhado|título=nome que resume o texto|fonte=de onde vem a informação|dado=número ou fato comprovado|entrevista=conversa para colher informação|parágrafo=bloco de texto sobre uma ideia",
  ],
  [
    "Verbete de enciclopédia",
    "O verbete explica o que é a palavra com clareza.",
    "Escrevo o nome do termo.|Explico o que ele significa.|Dou um exemplo de uso.|Uso linguagem clara e objetiva.|Não coloco opinião no verbete.",
    "verbete termo definição exemplo objetivo enciclopédia",
    "verbete=texto que explica uma palavra|termo=a palavra explicada|definição=o significado dado|exemplo=um caso que ilustra|objetivo=sem opinião pessoal|enciclopédia=livro com muitos verbetes",
  ],
  [
    "Carta de leitor",
    "Escrevi ao jornal para defender minha opinião.",
    "Digo para quem escrevo.|Apresento o assunto.|Defendo minha opinião com argumento.|Sugiro uma solução.|Assino com meu nome.",
    "carta leitor opinião argumento sugestão assinatura",
    "carta=texto enviado a alguém|leitor=quem lê o jornal|opinião=o que a pessoa pensa|argumento=razão que sustenta a opinião|sugestão=proposta de solução|assinatura=nome no fim do texto",
  ],
  [
    "Anúncio publicitário",
    "Experimente já: sabor que conquista!",
    "Uso frase curta e chamativa.|Escolho palavras que convencem.|Destaco a vantagem do produto.|Uso verbo de ordem.|Coloco uma imagem que atrai.",
    "anúncio slogan vantagem convencer produto público",
    "anúncio=texto que divulga um produto|slogan=frase curta que fica na memória|vantagem=o que o produto oferece de bom|convencer=fazer alguém concordar|produto=o que está sendo vendido|público=quem vai receber a mensagem",
  ],
  [
    "Texto teatral: rubrica e fala",
    "(Sorrindo) — Que dia lindo! — disse Marina.",
    "Escrevo o nome do personagem.|Escrevo a rubrica entre parênteses.|Escrevo a fala depois dos dois-pontos.|Divido a peça em cenas.|Leio em voz alta com entonação.",
    "rubrica personagem cena fala entonação teatro",
    "rubrica=indicação de gesto ou tom, entre parênteses|personagem=quem fala na peça|cena=parte da peça teatral|fala=o texto dito pelo personagem|entonação=jeito de dizer a fala|teatro=arte de representar uma história",
  ],
  [
    "Fato, opinião e argumento",
    "Choveu ontem. Eu acho que a chuva foi boa, porque encheu o rio.",
    "Choveu ontem é um fato.|Eu acho que a chuva foi boa é opinião.|Porque encheu o rio é o argumento.|Fato se confere, opinião se discute.|Um bom argumento convence o leitor.",
    "fato opinião argumento conferir convencer discutir",
    "fato=o que pode ser confirmado|opinião=o que alguém pensa|argumento=a razão que sustenta a opinião|conferir=checar se é verdade|convencer=fazer alguém concordar|discutir=trocar ideias sobre algo",
  ],
  [
    "Resumo de texto",
    "O resumo conta o essencial em poucas frases.",
    "Leio o texto com atenção.|Escolho as ideias principais.|Deixo de fora os detalhes.|Escrevo com minhas palavras.|Releio para conferir o sentido.",
    "resumo essencial detalhe ideia releitura síntese",
    "resumo=versão curta de um texto|essencial=o que é mais importante|detalhe=informação secundária|ideia=o que se quer comunicar|releitura=ler novamente para conferir|síntese=reunião do essencial de um texto",
  ],
  [
    "Relato pessoal com reflexão",
    "No passeio ao museu, eu aprendi sobre os dinossauros.",
    "Conto onde fui.|Digo o que vi e aprendi.|Explico como me senti.|Relaciono com o que já sabia.|Concluo com uma reflexão.",
    "relato reflexão aprendizado sentimento conclusão vivência",
    "relato=texto que conta uma experiência|reflexão=pensamento sobre o que se viveu|aprendizado=o que se aprendeu|sentimento=o que se sentiu|conclusão=o fechamento da ideia|vivência=experiência vivida",
  ],
  [
    "Parágrafo de comparação",
    "O cão late; já o gato mia baixinho.",
    "O cão é maior que o gato.|Já o peixe vive na água.|Enquanto o pássaro voa, o peixe nada.|Os dois são animais domésticos.|Ambos precisam de cuidado.",
    "comparação enquanto já ambos diferença semelhança",
    "comparação=quando se compara duas coisas|enquanto=liga ações que acontecem ao mesmo tempo|já=indica contraste entre duas partes|ambos=os dois juntos|diferença=o que não é igual|semelhança=o que é parecido",
  ],
  [
    "E-mail e mensagem formal",
    "Prezado professor, escrevo para pedir informações.",
    "Começo com uma saudação formal.|Explico o motivo da mensagem.|Uso linguagem educada.|Termino com uma despedida.|Assino com meu nome completo.",
    "e-mail saudação formal despedida assinatura educado",
    "e-mail=mensagem eletrônica|saudação=cumprimento inicial|formal=linguagem mais cuidadosa|despedida=fechamento da mensagem|assinatura=nome de quem escreve|educado=respeitoso e gentil",
  ],
  [
    "Instruções e manual",
    "Para montar o brinquedo, siga os passos numerados.",
    "Numero cada passo.|Uso verbos de ordem: encaixe, gire.|Explico com clareza.|Uso desenhos quando possível.|Confiro se ficou entendível.",
    "manual passo instrução verbo ordem clareza",
    "manual=texto que ensina a fazer algo|passo=cada etapa da instrução|instrução=explicação de como fazer|verbo=palavra de ação usada na ordem|ordem=comando de como agir|clareza=quando o texto é fácil de entender",
  ],
  [
    "Diário de bordo da pesquisa",
    "Anotei no meu diário de bordo cada descoberta da pesquisa.",
    "Escrevo a data de cada anotação.|Registro o que pesquisei.|Anoto as dúvidas que surgiram.|Escrevo as descobertas.|Faço uma conclusão no fim.",
    "diário bordo pesquisa registro descoberta conclusão",
    "diário=caderno de anotações|bordo=registro de uma jornada ou pesquisa|pesquisa=busca de informação|registro=anotação do que aconteceu|descoberta=algo novo que se aprendeu|conclusão=o que se concluiu no fim",
  ],
  [
    "Texto de opinião com argumento e contra-argumento",
    "Uns acham que é cedo, mas eu acredito que já é hora.",
    "Apresento minha opinião.|Dou um argumento forte.|Reconheço a opinião contrária.|Explico por que discordo dela.|Concluo reafirmando minha ideia.",
    "opinião argumento contra-argumento reafirmar concluir defender",
    "opinião=o que a pessoa pensa|argumento=razão que sustenta a opinião|contra-argumento=ideia contrária considerada|reafirmar=dizer de novo com força|concluir=fechar a ideia|defender=sustentar um ponto de vista",
  ],
  [
    "Crase (uso simples)",
    "Fui à escola e à biblioteca depois.",
    "Vou à feira todo sábado.|Cheguei à casa da vovó.|Fui à praia no verão.|Entreguei à professora o trabalho.|Voltei à sala depois do recreio.",
    "crase à feira biblioteca escola artigo",
    "crase=junção da preposição a com o artigo a|à=indica destino ou lugar, com crase|feira=onde se compra e vende|biblioteca=lugar com muitos livros|escola=onde se estuda|artigo=palavra que acompanha o substantivo",
  ],
  [
    "Ortografia: por que, porque, por quê, porquê",
    "Por que você chorou? Porque estava triste.",
    "Por que você faltou à aula?|Faltei porque estava doente.|Não sei o motivo, o porquê.|Ele se calou, por quê?|Explique o porquê da demora.",
    "porque por que porquê por quê motivo pergunta",
    "porque=explica uma causa|por que=usado em perguntas|porquê=substantivo, o motivo|por quê=usado no fim da frase|motivo=a razão de algo|pergunta=quando se quer saber algo",
  ],
  [
    "Revisar coesão do texto",
    "Releio para ver se as ideias se conectam bem.",
    "Releio o texto inteiro.|Confiro os conectivos usados.|Vejo se as frases se ligam.|Troco repetições por sinônimos.|Passo a limpo com capricho.",
    "coesão conectivo repetição sinônimo revisão capricho",
    "coesão=ligação entre as partes do texto|conectivo=palavra que liga ideias|repetição=quando a mesma palavra aparece demais|sinônimo=palavra de sentido parecido|revisão=quando se relê para corrigir|capricho=cuidado ao fazer algo",
  ],
  [
    "Notícia com pirâmide invertida",
    "A notícia começa pelo mais importante e detalha depois.",
    "Escrevo o fato principal primeiro.|Digo quem, o quê, quando e onde.|Depois explico como aconteceu.|Deixo os detalhes para o fim.|Não coloco opinião na notícia.",
    "pirâmide invertida notícia fato detalhe imparcial",
    "pirâmide invertida=do mais importante para o menos importante|notícia=texto que informa um fato|fato=o que realmente aconteceu|detalhe=informação secundária|imparcial=sem tomar partido",
  ],
  [
    "Convite e bilhete formal",
    "Você está convidado para a festa da escola.",
    "Digo o motivo do convite.|Informo data, hora e local.|Uso linguagem educada.|Peço confirmação de presença.|Assino com meu nome.",
    "convite data hora local confirmação assinatura",
    "convite=pedido para participar de um evento|data=dia do acontecimento|hora=momento marcado|local=onde vai acontecer|confirmação=resposta de que vai participar|assinatura=nome de quem convida",
  ],
  [
    "Descrição técnica de objeto",
    "O objeto é feito de metal, tem forma redonda e pesa pouco.",
    "Descrevo o material.|Descrevo a forma.|Descrevo o tamanho e o peso.|Explico para que serve.|Uso linguagem objetiva.",
    "material forma tamanho peso função objetivo",
    "material=do que o objeto é feito|forma=o formato do objeto|tamanho=quão grande ou pequeno é|peso=quanto pesa|função=para que serve|objetivo=sem opinião pessoal",
  ],
  [
    "Poema com metáfora",
    "O sol é uma moeda de ouro no céu.",
    "Escrevo versos com metáfora.|Comparo uma coisa a outra sem usar 'como'.|Junto os versos em estrofes.|Leio em voz alta com ritmo.|Escolho palavras com sonoridade bonita.",
    "metáfora verso estrofe ritmo comparação sonoridade",
    "metáfora=comparação sem usar 'como'|verso=cada linha do poema|estrofe=grupo de versos|ritmo=a batida da leitura|comparação=quando se compara duas coisas|sonoridade=o som das palavras juntas",
  ],
  [
    "Narrativa com narrador em 1ª e 3ª pessoa",
    "Eu vi tudo (1ª pessoa). Ela viu tudo (3ª pessoa).",
    "Na 1ª pessoa, eu conto a história.|Na 3ª pessoa, alguém de fora conta.|Eu fui ao parque ontem.|Marina foi ao parque ontem.|Escolho o narrador antes de escrever.",
    "narrador primeira terceira pessoa história contar",
    "narrador=quem conta a história|primeira pessoa=o eu que vive a história|terceira pessoa=alguém de fora que observa|história=o que é narrado|contar=relatar os fatos",
  ],
  [
    "Revisão de acentuação geral",
    "Máquina, água e história têm acento em lugares diferentes.",
    "Máquina é proparoxítona.|Água tem hiato acentuado.|História tem acento na sílaba tônica.|Fácil é paroxítona com acento.|Café é oxítona com acento.",
    "máquina água história fácil café proparoxítona",
    "máquina=equipamento que funciona sozinho|água=líquido essencial à vida|história=relato de fatos passados|fácil=que não é difícil|café=bebida quente|proparoxítona=força na antepenúltima sílaba",
  ],
  [
    "Planejar antes de escrever",
    "Antes de escrever, faço um esquema com as partes do texto.",
    "Escolho o tema.|Penso no gênero do texto.|Faço uma lista de ideias.|Organizo a ordem das partes.|Só depois escrevo o rascunho.",
    "planejar esquema tema gênero ordem rascunho",
    "planejar=organizar antes de fazer|esquema=plano com as partes do texto|tema=o assunto escolhido|gênero=o tipo de texto|ordem=a sequência das ideias|rascunho=primeira versão do texto",
  ],
  [
    "Sou autor: publicar e apresentar",
    "Eu escrevo, revejo e publico meus textos para a turma.",
    "Escolho o gênero do texto.|Planejo e escrevo o rascunho.|Revejo com a lista de conferência.|Passo a limpo com capricho.|Leio ou publico para a turma.",
    "autor gênero planejar revisar publicar apresentar",
    "autor=quem escreve o texto|gênero=o tipo de texto produzido|planejar=organizar antes de escrever|revisar=conferir e corrigir|publicar=deixar outros lerem|apresentar=mostrar o texto para a turma",
  ],
];

export const SEMANAS_ESCRITA_4ANO: SemanaEscrita[] = LINHAS.map((l, i) => ({
  semana: i + 1,
  foco: l[0],
  fraseSemana: l[1],
  frasesDia: l[2].split("|"),
  palavrasLousa: l[3].split(" "),
  ditado: l[4].split("|").map((d) => {
    const [palavra, dica] = d.split("=");
    return { palavra, dica };
  }),
}));
