DELETE FROM public.mascot_catalog_items WHERE type = 'costume';
INSERT INTO public.mascot_catalog_items (name, description, type, category, required_level, required_coins, image_url) VALUES 
('Pip T-Rex', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 1, 120, 'SKIN:dinossauros'),
('Pip Tricerátops', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 1, 240, 'SKIN:dinossauros'),
('Pip Velociraptor', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 1, 360, 'SKIN:dinossauros'),
('Pip Pterodáctilo', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 1, 480, 'SKIN:dinossauros'),
('Pip Braquiossauro', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 1, 600, 'SKIN:dinossauros'),
('Pip Espinossauro', 'Uma transformação exclusiva de Dinossauros para sua jornada!', 'costume', 'Dinossauros', 2, 720, 'SKIN:dinossauros'),
('Pip Astronauta', 'Uma transformação exclusiva de Espaço para sua jornada!', 'costume', 'Espaço', 2, 840, 'SKIN:espaco'),
('Pip Capitão Galáctico', 'Uma transformação exclusiva de Espaço para sua jornada!', 'costume', 'Espaço', 2, 960, 'SKIN:espaco'),
('Pip Viajante Estelar', 'Uma transformação exclusiva de Espaço para sua jornada!', 'costume', 'Espaço', 2, 1080, 'SKIN:espaco'),
('Pip Cadete Espacial', 'Uma transformação exclusiva de Espaço para sua jornada!', 'costume', 'Espaço', 2, 1200, 'SKIN:espaco'),
('Pip Explorador de Marte', 'Uma transformação exclusiva de Espaço para sua jornada!', 'costume', 'Espaço', 3, 1320, 'SKIN:espaco'),
('Pip Super Pip', 'Uma transformação exclusiva de Heróis para sua jornada!', 'costume', 'Heróis', 3, 1440, 'SKIN:super-herois'),
('Pip Defensor da Justiça', 'Uma transformação exclusiva de Heróis para sua jornada!', 'costume', 'Heróis', 3, 1560, 'SKIN:super-herois'),
('Pip Herói do Saber', 'Uma transformação exclusiva de Heróis para sua jornada!', 'costume', 'Heróis', 3, 1680, 'SKIN:super-herois'),
('Pip Guardião da Escola', 'Uma transformação exclusiva de Heróis para sua jornada!', 'costume', 'Heróis', 3, 1800, 'SKIN:super-herois'),
('Pip Mestre da Leitura', 'Uma transformação exclusiva de Educação para sua jornada!', 'costume', 'Educação', 4, 1920, 'SKIN:arte'),
('Pip Gênio da Matemática', 'Uma transformação exclusiva de Educação para sua jornada!', 'costume', 'Educação', 4, 2040, 'SKIN:arte'),
('Pip Pequeno Cientista', 'Uma transformação exclusiva de Educação para sua jornada!', 'costume', 'Educação', 4, 2160, 'SKIN:arte'),
('Pip Pintor Criativo', 'Uma transformação exclusiva de Educação para sua jornada!', 'costume', 'Educação', 4, 2280, 'SKIN:arte'),
('Pip Escritor Mirim', 'Uma transformação exclusiva de Educação para sua jornada!', 'costume', 'Educação', 4, 2400, 'SKIN:arte'),
('Pip Piloto Aventureiro', 'Uma transformação exclusiva de Veículos para sua jornada!', 'costume', 'Veículos', 5, 2520, 'SKIN:veiculos'),
('Pip Comandante do Ar', 'Uma transformação exclusiva de Veículos para sua jornada!', 'costume', 'Veículos', 5, 2640, 'SKIN:veiculos'),
('Pip Navegador dos Sete Mares', 'Uma transformação exclusiva de Veículos para sua jornada!', 'costume', 'Veículos', 5, 2760, 'SKIN:veiculos'),
('Pip Motorista Alegre', 'Uma transformação exclusiva de Veículos para sua jornada!', 'costume', 'Veículos', 5, 2880, 'SKIN:veiculos'),
('Pip Piloto de Fórmula 1', 'Uma transformação exclusiva de Trânsito para sua jornada!', 'costume', 'Trânsito', 5, 3000, 'SKIN:carros'),
('Pip Mecânico Esperto', 'Uma transformação exclusiva de Trânsito para sua jornada!', 'costume', 'Trânsito', 6, 3120, 'SKIN:carros'),
('Pip Fiscal de Trânsito', 'Uma transformação exclusiva de Trânsito para sua jornada!', 'costume', 'Trânsito', 6, 3240, 'SKIN:carros'),
('Pip Aventureiro das Pistas', 'Uma transformação exclusiva de Trânsito para sua jornada!', 'costume', 'Trânsito', 6, 3360, 'SKIN:carros'),
('Pip Maquinista de Trem', 'Uma transformação exclusiva de Ferrovia para sua jornada!', 'costume', 'Ferrovia', 6, 3480, 'SKIN:trens'),
('Pip Condutor de Aventuras', 'Uma transformação exclusiva de Ferrovia para sua jornada!', 'costume', 'Ferrovia', 6, 3600, 'SKIN:trens'),
('Pip Chefe da Estação', 'Uma transformação exclusiva de Ferrovia para sua jornada!', 'costume', 'Ferrovia', 7, 3720, 'SKIN:trens'),
('Pip Pip Android', 'Uma transformação exclusiva de Robótica para sua jornada!', 'costume', 'Robótica', 7, 3840, 'SKIN:robos'),
('Pip Robô Amigo', 'Uma transformação exclusiva de Robótica para sua jornada!', 'costume', 'Robótica', 7, 3960, 'SKIN:robos'),
('Pip Engenheiro Espacial', 'Uma transformação exclusiva de Robótica para sua jornada!', 'costume', 'Robótica', 7, 4080, 'SKIN:robos'),
('Pip Mestre da Tecnologia', 'Uma transformação exclusiva de Robótica para sua jornada!', 'costume', 'Robótica', 7, 4200, 'SKIN:robos'),
('Pip Fazendeiro Pip', 'Uma transformação exclusiva de Fazenda para sua jornada!', 'costume', 'Fazenda', 8, 4320, 'SKIN:fazendinha'),
('Pip Cuidador de Animais', 'Uma transformação exclusiva de Fazenda para sua jornada!', 'costume', 'Fazenda', 8, 4440, 'SKIN:fazendinha'),
('Pip Protetor da Natureza', 'Uma transformação exclusiva de Fazenda para sua jornada!', 'costume', 'Fazenda', 8, 4560, 'SKIN:fazendinha'),
('Pip Pequeno Cultivador', 'Uma transformação exclusiva de Fazenda para sua jornada!', 'costume', 'Fazenda', 8, 4680, 'SKIN:fazendinha'),
('Pip Príncipe da Sabedoria', 'Uma transformação exclusiva de Realeza para sua jornada!', 'costume', 'Realeza', 8, 4800, 'SKIN:princesas'),
('Pip Cavaleiro Gentil', 'Uma transformação exclusiva de Realeza para sua jornada!', 'costume', 'Realeza', 9, 4920, 'SKIN:princesas'),
('Pip Guardião do Castelo', 'Uma transformação exclusiva de Realeza para sua jornada!', 'costume', 'Realeza', 9, 5040, 'SKIN:princesas'),
('Pip Construtor de Blocos', 'Uma transformação exclusiva de Minecraft para sua jornada!', 'costume', 'Minecraft', 9, 5160, 'SKIN:minecraft'),
('Pip Minerador de Ideias', 'Uma transformação exclusiva de Minecraft para sua jornada!', 'costume', 'Minecraft', 9, 5280, 'SKIN:minecraft'),
('Pip Arquiteto de Mundos', 'Uma transformação exclusiva de Minecraft para sua jornada!', 'costume', 'Minecraft', 9, 5400, 'SKIN:minecraft'),
('Pip Maestro Pip', 'Uma transformação exclusiva de Música para sua jornada!', 'costume', 'Música', 10, 5520, 'SKIN:musica'),
('Pip Pequeno Pianista', 'Uma transformação exclusiva de Música para sua jornada!', 'costume', 'Música', 10, 5640, 'SKIN:musica'),
('Pip Estrela do Rock', 'Uma transformação exclusiva de Música para sua jornada!', 'costume', 'Música', 10, 5760, 'SKIN:musica'),
('Pip Mestre do Ritmo', 'Uma transformação exclusiva de Música para sua jornada!', 'costume', 'Música', 10, 5880, 'SKIN:musica'),
('Pip Veterinário Pip', 'Uma transformação exclusiva de Natureza para sua jornada!', 'costume', 'Natureza', 10, 6000, 'SKIN:animais');