DELETE FROM public.mascot_catalog_items;
INSERT INTO public.mascot_catalog_items (name, description, type, category, required_level, required_coins, image_url) VALUES 
('Pip Dinossauros ', 'Uma incrível transformação temática de Dinossauros para o seu Pip!', 'costume', 'Dinossauros', 1, 150, 'SKIN:dinossauros'),
('Pip Espaço ', 'Uma incrível transformação temática de Espaço para o seu Pip!', 'costume', 'Espaço', 1, 300, 'SKIN:espaco'),
('Pip Arte ', 'Uma incrível transformação temática de Arte para o seu Pip!', 'costume', 'Arte', 1, 450, 'SKIN:arte'),
('Pip Animais ', 'Uma incrível transformação temática de Animais para o seu Pip!', 'costume', 'Animais', 1, 600, 'SKIN:animais'),
('Pip Música ', 'Uma incrível transformação temática de Música para o seu Pip!', 'costume', 'Música', 2, 750, 'SKIN:musica'),
('Pip Fazendinha ', 'Uma incrível transformação temática de Fazendinha para o seu Pip!', 'costume', 'Fazendinha', 2, 900, 'SKIN:fazendinha'),
('Pip Super-Heróis ', 'Uma incrível transformação temática de Super-Heróis para o seu Pip!', 'costume', 'Super-Heróis', 2, 1050, 'SKIN:super-herois'),
('Pip Princesas ', 'Uma incrível transformação temática de Princesas para o seu Pip!', 'costume', 'Princesas', 2, 1200, 'SKIN:princesas'),
('Pip Minecraft ', 'Uma incrível transformação temática de Minecraft para o seu Pip!', 'costume', 'Minecraft', 2, 1350, 'SKIN:minecraft'),
('Pip Carros ', 'Uma incrível transformação temática de Carros para o seu Pip!', 'costume', 'Carros', 3, 1500, 'SKIN:carros'),
('Pip Trens ', 'Uma incrível transformação temática de Trens para o seu Pip!', 'costume', 'Trens', 3, 1650, 'SKIN:trens'),
('Pip Robôs ', 'Uma incrível transformação temática de Robôs para o seu Pip!', 'costume', 'Robôs', 3, 1800, 'SKIN:robos'),
('Pip Veículos ', 'Uma incrível transformação temática de Veículos para o seu Pip!', 'costume', 'Veículos', 3, 1950, 'SKIN:veiculos'),
('Pip Maestro ', 'Uma incrível transformação temática de Maestro para o seu Pip!', 'costume', 'Maestro', 3, 2100, 'SKIN:musica'),
('Pip Astronauta ', 'Uma incrível transformação temática de Astronauta para o seu Pip!', 'costume', 'Astronauta', 4, 2250, 'SKIN:espaco'),
('Pip Explorador ', 'Uma incrível transformação temática de Explorador para o seu Pip!', 'costume', 'Explorador', 4, 2400, 'SKIN:dinossauros'),
('Pip Construtor ', 'Uma incrível transformação temática de Construtor para o seu Pip!', 'costume', 'Construtor', 4, 2550, 'SKIN:minecraft'),
('Pip Dinossauros V2', 'Uma incrível transformação temática de Dinossauros para o seu Pip!', 'costume', 'Dinossauros', 4, 2700, 'SKIN:dinossauros'),
('Pip Espaço V2', 'Uma incrível transformação temática de Espaço para o seu Pip!', 'costume', 'Espaço', 4, 2850, 'SKIN:espaco'),
('Pip Arte V2', 'Uma incrível transformação temática de Arte para o seu Pip!', 'costume', 'Arte', 5, 3000, 'SKIN:arte'),
('Pip Animais V2', 'Uma incrível transformação temática de Animais para o seu Pip!', 'costume', 'Animais', 5, 3150, 'SKIN:animais'),
('Pip Música V2', 'Uma incrível transformação temática de Música para o seu Pip!', 'costume', 'Música', 5, 3300, 'SKIN:musica'),
('Pip Fazendinha V2', 'Uma incrível transformação temática de Fazendinha para o seu Pip!', 'costume', 'Fazendinha', 5, 3450, 'SKIN:fazendinha'),
('Pip Super-Heróis V2', 'Uma incrível transformação temática de Super-Heróis para o seu Pip!', 'costume', 'Super-Heróis', 5, 3600, 'SKIN:super-herois'),
('Pip Princesas V2', 'Uma incrível transformação temática de Princesas para o seu Pip!', 'costume', 'Princesas', 6, 3750, 'SKIN:princesas'),
('Pip Minecraft V2', 'Uma incrível transformação temática de Minecraft para o seu Pip!', 'costume', 'Minecraft', 6, 3900, 'SKIN:minecraft'),
('Pip Carros V2', 'Uma incrível transformação temática de Carros para o seu Pip!', 'costume', 'Carros', 6, 4050, 'SKIN:carros'),
('Pip Trens V2', 'Uma incrível transformação temática de Trens para o seu Pip!', 'costume', 'Trens', 6, 4200, 'SKIN:trens'),
('Pip Robôs V2', 'Uma incrível transformação temática de Robôs para o seu Pip!', 'costume', 'Robôs', 6, 4350, 'SKIN:robos'),
('Pip Veículos V2', 'Uma incrível transformação temática de Veículos para o seu Pip!', 'costume', 'Veículos', 7, 4500, 'SKIN:veiculos'),
('Pip Maestro V2', 'Uma incrível transformação temática de Maestro para o seu Pip!', 'costume', 'Maestro', 7, 4650, 'SKIN:musica'),
('Pip Astronauta V2', 'Uma incrível transformação temática de Astronauta para o seu Pip!', 'costume', 'Astronauta', 7, 4800, 'SKIN:espaco'),
('Pip Explorador V2', 'Uma incrível transformação temática de Explorador para o seu Pip!', 'costume', 'Explorador', 7, 4950, 'SKIN:dinossauros'),
('Pip Construtor V3', 'Uma incrível transformação temática de Construtor para o seu Pip!', 'costume', 'Construtor', 7, 5100, 'SKIN:minecraft'),
('Pip Dinossauros V3', 'Uma incrível transformação temática de Dinossauros para o seu Pip!', 'costume', 'Dinossauros', 8, 5250, 'SKIN:dinossauros'),
('Pip Espaço V3', 'Uma incrível transformação temática de Espaço para o seu Pip!', 'costume', 'Espaço', 8, 5400, 'SKIN:espaco'),
('Pip Arte V3', 'Uma incrível transformação temática de Arte para o seu Pip!', 'costume', 'Arte', 8, 5550, 'SKIN:arte'),
('Pip Animais V3', 'Uma incrível transformação temática de Animais para o seu Pip!', 'costume', 'Animais', 8, 5700, 'SKIN:animais'),
('Pip Música V3', 'Uma incrível transformação temática de Música para o seu Pip!', 'costume', 'Música', 8, 5850, 'SKIN:musica'),
('Pip Fazendinha V3', 'Uma incrível transformação temática de Fazendinha para o seu Pip!', 'costume', 'Fazendinha', 9, 6000, 'SKIN:fazendinha'),
('Pip Super-Heróis V3', 'Uma incrível transformação temática de Super-Heróis para o seu Pip!', 'costume', 'Super-Heróis', 9, 6150, 'SKIN:super-herois'),
('Pip Princesas V3', 'Uma incrível transformação temática de Princesas para o seu Pip!', 'costume', 'Princesas', 9, 6300, 'SKIN:princesas'),
('Pip Minecraft V3', 'Uma incrível transformação temática de Minecraft para o seu Pip!', 'costume', 'Minecraft', 9, 6450, 'SKIN:minecraft'),
('Pip Carros V3', 'Uma incrível transformação temática de Carros para o seu Pip!', 'costume', 'Carros', 9, 6600, 'SKIN:carros'),
('Pip Trens V3', 'Uma incrível transformação temática de Trens para o seu Pip!', 'costume', 'Trens', 10, 6750, 'SKIN:trens'),
('Pip Robôs V3', 'Uma incrível transformação temática de Robôs para o seu Pip!', 'costume', 'Robôs', 10, 6900, 'SKIN:robos'),
('Pip Veículos V3', 'Uma incrível transformação temática de Veículos para o seu Pip!', 'costume', 'Veículos', 10, 7050, 'SKIN:veiculos'),
('Pip Maestro V3', 'Uma incrível transformação temática de Maestro para o seu Pip!', 'costume', 'Maestro', 10, 7200, 'SKIN:musica'),
('Pip Astronauta V3', 'Uma incrível transformação temática de Astronauta para o seu Pip!', 'costume', 'Astronauta', 10, 7350, 'SKIN:espaco'),
('Pip Explorador V3', 'Uma incrível transformação temática de Explorador para o seu Pip!', 'costume', 'Explorador', 11, 7500, 'SKIN:dinossauros'),
('Blocos de Montar', 'Um brinquedo que ajuda o Pip a aprender blocos de montar com você!', 'toy', 'Educativo', 1, 200, NULL),
('Robô Educativo', 'Um brinquedo que ajuda o Pip a aprender robô educativo com você!', 'toy', 'Educativo', 1, 400, NULL),
('Quebra-Cabeça Solar', 'Um brinquedo que ajuda o Pip a aprender quebra-cabeça solar com você!', 'toy', 'Educativo', 1, 600, NULL),
('Kit de Pintura Mágica', 'Um brinquedo que ajuda o Pip a aprender kit de pintura mágica com você!', 'toy', 'Educativo', 2, 800, NULL),
('Telescópio Estelar', 'Um brinquedo que ajuda o Pip a aprender telescópio estelar com você!', 'toy', 'Educativo', 2, 1000, NULL),
('Lupa de Explorador', 'Um brinquedo que ajuda o Pip a aprender lupa de explorador com você!', 'toy', 'Educativo', 2, 1200, NULL),
('Piano de Cristais', 'Um brinquedo que ajuda o Pip a aprender piano de cristais com você!', 'toy', 'Educativo', 3, 1400, NULL),
('Mini Laboratório', 'Um brinquedo que ajuda o Pip a aprender mini laboratório com você!', 'toy', 'Educativo', 3, 1600, NULL),
('Ábaco de Ouro', 'Um brinquedo que ajuda o Pip a aprender ábaco de ouro com você!', 'toy', 'Educativo', 3, 1800, NULL),
('Livro Falante', 'Um brinquedo que ajuda o Pip a aprender livro falante com você!', 'toy', 'Educativo', 4, 2000, NULL),
('Globo Terrestre', 'Um brinquedo que ajuda o Pip a aprender globo terrestre com você!', 'toy', 'Educativo', 4, 2200, NULL),
('Microscópio', 'Um brinquedo que ajuda o Pip a aprender microscópio com você!', 'toy', 'Educativo', 4, 2400, NULL),
('Drone de Estudo', 'Um brinquedo que ajuda o Pip a aprender drone de estudo com você!', 'toy', 'Educativo', 5, 2600, NULL),
('Tablet de Desenho', 'Um brinquedo que ajuda o Pip a aprender tablet de desenho com você!', 'toy', 'Educativo', 5, 2800, NULL),
('Xilofone', 'Um brinquedo que ajuda o Pip a aprender xilofone com você!', 'toy', 'Educativo', 5, 3000, NULL),
('Cubo Mágico', 'Um brinquedo que ajuda o Pip a aprender cubo mágico com você!', 'toy', 'Educativo', 6, 3200, NULL),
('Trem de Letras', 'Um brinquedo que ajuda o Pip a aprender trem de letras com você!', 'toy', 'Educativo', 6, 3400, NULL),
('Foguete de Papelão', 'Um brinquedo que ajuda o Pip a aprender foguete de papelão com você!', 'toy', 'Educativo', 6, 3600, NULL),
('Castelo de Areia', 'Um brinquedo que ajuda o Pip a aprender castelo de areia com você!', 'toy', 'Educativo', 7, 3800, NULL),
('Pipa Cromática', 'Um brinquedo que ajuda o Pip a aprender pipa cromática com você!', 'toy', 'Educativo', 7, 4000, NULL),
('Bola de Sabão', 'Um brinquedo que ajuda o Pip a aprender bola de sabão com você!', 'toy', 'Educativo', 7, 4200, NULL),
('Jogo da Memória', 'Um brinquedo que ajuda o Pip a aprender jogo da memória com você!', 'toy', 'Educativo', 8, 4400, NULL),
('Dominó de Números', 'Um brinquedo que ajuda o Pip a aprender dominó de números com você!', 'toy', 'Educativo', 8, 4600, NULL),
('Tangram', 'Um brinquedo que ajuda o Pip a aprender tangram com você!', 'toy', 'Educativo', 8, 4800, NULL),
('Bússola', 'Um brinquedo que ajuda o Pip a aprender bússola com você!', 'toy', 'Educativo', 9, 5000, NULL),
('Relógio Solar', 'Um brinquedo que ajuda o Pip a aprender relógio solar com você!', 'toy', 'Educativo', 9, 5200, NULL),
('Kaleidoscópio', 'Um brinquedo que ajuda o Pip a aprender kaleidoscópio com você!', 'toy', 'Educativo', 9, 5400, NULL),
('Maquete Vulcão', 'Um brinquedo que ajuda o Pip a aprender maquete vulcão com você!', 'toy', 'Educativo', 10, 5600, NULL),
('Kit Robótica', 'Um brinquedo que ajuda o Pip a aprender kit robótica com você!', 'toy', 'Educativo', 10, 5800, NULL),
('Mapa do Tesouro', 'Um brinquedo que ajuda o Pip a aprender mapa do tesouro com você!', 'toy', 'Educativo', 10, 6000, NULL);