import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, BookOpenCheck, CheckCircle2, Printer } from "lucide-react";
import { useState } from "react";
import { TeacherShell as Shell } from "@/components/teacher/TeacherShell";
import { CURSO_ALFABETIZACAO_PROFESSOR } from "@/data/curso-alfabetizacao-professor";
export const Route = createFileRoute("/area-professor/alfabetizacao")({ component: CursoAlfabetizacao });
function CursoAlfabetizacao() {
  const [modulo,setModulo]=useState(0); const atual=CURSO_ALFABETIZACAO_PROFESSOR[modulo];
  return <Shell><main className="mx-auto max-w-6xl space-y-5 print:max-w-none"><header className="rounded-3xl bg-gradient-to-r from-emerald-700 to-teal-600 p-6 text-white print:bg-white print:text-black"><Link to="/area-professor" className="inline-flex items-center gap-2 font-bold text-white/80 print:hidden"><ArrowLeft/> Área do Professor</Link><div className="mt-5 flex items-start justify-between"><div><p className="text-sm font-black uppercase tracking-widest">Formação docente</p><h1 className="text-3xl font-black md:text-5xl">Curso de Alfabetização</h1><p className="mt-2 max-w-2xl">Formação prática, explícita e inclusiva para planejar, ensinar, observar e intervir.</p></div><BookOpenCheck size={52}/></div></header>
  <div className="grid gap-5 lg:grid-cols-[300px_1fr]"><nav className="space-y-2 print:hidden">{CURSO_ALFABETIZACAO_PROFESSOR.map((m,i)=><button key={m.titulo} onClick={()=>setModulo(i)} className={`w-full rounded-2xl border p-3 text-left font-bold ${i===modulo?"border-emerald-600 bg-emerald-50 text-emerald-900":"bg-white"}`}>{m.titulo}</button>)}</nav><article className="rounded-3xl border bg-white p-6 shadow-sm md:p-9"><div className="flex justify-between gap-3"><div><p className="font-black text-emerald-700">Módulo {modulo+1} de {CURSO_ALFABETIZACAO_PROFESSOR.length}</p><h2 className="mt-1 text-3xl font-black">{atual.titulo}</h2></div><button onClick={()=>window.print()} className="print:hidden"><Printer/></button></div><p className="mt-4 rounded-2xl bg-emerald-50 p-4 text-lg"><b>Objetivo:</b> {atual.objetivo}</p><h3 className="mt-6 text-xl font-black">O que orienta o ensino</h3><ul className="mt-2 space-y-2">{atual.fundamentos.map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="shrink-0 text-emerald-600"/>{x}</li>)}</ul><h3 className="mt-6 text-xl font-black">Aplicação em sala</h3><ol className="mt-2 space-y-3">{atual.pratica.map((x,i)=><li key={x} className="rounded-xl bg-slate-50 p-3"><b>{i+1}.</b> {x}</li>)}</ol><div className="mt-6 rounded-2xl border-2 border-amber-300 bg-amber-50 p-4"><b>Verificação pedagógica:</b> {atual.verificacao}</div><div className="mt-7 flex justify-between print:hidden"><button disabled={modulo===0} onClick={()=>setModulo(m=>m-1)} className="rounded-xl border px-4 py-2 font-bold disabled:opacity-30">Anterior</button><button disabled={modulo===CURSO_ALFABETIZACAO_PROFESSOR.length-1} onClick={()=>setModulo(m=>m+1)} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-30">Próximo módulo</button></div><footer className="mt-8 border-t pt-3 text-center text-xs font-bold text-slate-400">NeuroBrilha Kids · material de formação docente</footer></article></div></main></Shell>;
}
