import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowLeft, Printer } from "lucide-react";
import { supabase } from "@/database/supabase/client";
import { Shell } from "@/components/Layout";
import { Button } from "@/components/ui/button";

export const Route=createFileRoute("/area-professor/aula-inclusiva/$lessonId")({component:InclusiveLesson});
type Page={title?:string;purpose?:string;sections?:Array<{heading?:string;content?:string|string[]}>;instruction?:string;content?:string;activity?:string;support?:string};
type Lesson={codigo_bncc:string;title:string;school_year:string;subject:string;learning_goal:string;teacher_pages:Page[];student_pages:Page[];answer_key:unknown[]};
function InclusiveLesson(){const {lessonId}=Route.useParams();const [lesson,setLesson]=useState<Lesson|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{(async()=>{const {data}=await(supabase as any).rpc("teacher_get_inclusive_lesson",{selected_id:lessonId});setLesson(data?.[0]??null);setLoading(false);})();},[lessonId]);if(loading)return <Shell><p className="p-8 text-center">Carregando material…</p></Shell>;if(!lesson)return <Shell><p className="p-8 text-center">Material não encontrado ou ainda não aprovado.</p></Shell>;
  const renderPage=(page:Page,index:number,kind:"teacher"|"student")=><article key={`${kind}-${index}`} className="print:break-after-page min-h-[70vh] rounded-2xl border bg-white p-6 md:p-10"><p className="text-xs font-black uppercase tracking-wider text-indigo-600">{kind==="teacher"?"Orientação ao professor":"Aula adaptada da criança"} · Página {index+1}</p><h2 className="mt-3 text-2xl font-black">{page.title||lesson.title}</h2>{page.purpose&&<p className="mt-3 rounded-xl bg-indigo-50 p-4 font-semibold">{page.purpose}</p>}{page.instruction&&<p className="mt-5 text-lg font-bold">{page.instruction}</p>}{page.content&&<p className="mt-4 whitespace-pre-wrap text-lg leading-relaxed">{page.content}</p>}{page.activity&&<div className="mt-6 rounded-xl border-2 p-5 text-lg">{page.activity}</div>}{page.support&&<p className="mt-4 rounded-xl bg-amber-50 p-4 text-sm"><b>Apoio:</b> {page.support}</p>}{page.sections?.map((s,i)=><section key={i} className="mt-6"><h3 className="text-lg font-black">{s.heading}</h3>{Array.isArray(s.content)?<ul className="mt-2 list-disc space-y-2 pl-6">{s.content.map((x,j)=><li key={j}>{x}</li>)}</ul>:<p className="mt-2 whitespace-pre-wrap leading-relaxed">{s.content}</p>}</section>)}</article>;
  return <Shell><main className="mx-auto max-w-4xl space-y-5 p-4 md:p-6"><div className="print:hidden flex justify-between gap-3"><Link to="/area-professor/biblioteca-inclusiva" className="inline-flex min-h-11 items-center gap-2 font-bold text-primary"><ArrowLeft className="h-4 w-4"/>Biblioteca</Link><Button onClick={()=>window.print()}><Printer className="mr-2 h-4 w-4"/>Imprimir</Button></div><header className="rounded-2xl bg-indigo-700 p-6 text-white"><p className="font-mono font-bold">{lesson.codigo_bncc} · {lesson.school_year} · {lesson.subject}</p><h1 className="mt-2 text-3xl font-black">{lesson.title}</h1><p className="mt-2">{lesson.learning_goal}</p></header>{lesson.teacher_pages.map((p,i)=>renderPage(p,i,"teacher"))}{lesson.student_pages.map((p,i)=>renderPage(p,i,"student"))}</main></Shell>}

