import type { AulaGeoV1 } from "../../types";
import { url as floresta } from "@/assets/ciencias-5ano/u2-a1/ecossistema-floresta.jpg.asset.json";
import { url as cadeia } from "@/assets/ciencias-5ano/u2-a1/cadeia-alimentar.jpg.asset.json";
import { url as produtor } from "@/assets/ciencias-5ano/u2-a1/produtor-planta.jpg.asset.json";
import { url as consumidor } from "@/assets/ciencias-5ano/u2-a1/consumidor-onca.jpg.asset.json";
import { url as decompositor } from "@/assets/ciencias-5ano/u2-a1/decompositor-fungo.jpg.asset.json";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-ecossistemas",
  titulo: "Vida nos Ecossistemas",
  iconeTrilha: "🌿",
  bncc: ["EF05CI04"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passa a lupa pela floresta. Encontre os três tipos de seres vivos que fazem tudo funcionar.",
    mapaUrl: floresta,
    imagemDestaqueUrl: consumidor,
    aurora: "Toda floresta é uma máquina viva. Plantas capturam energia do sol, animais comem, e fungos reciclam o que sobra. Se um elo quebra, tudo desmorona.",
    falaFinal: "Ecossistema é uma equipe. Cada função é essencial — do menor fungo à maior onça.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Numa cadeia alimentar, quem SEMPRE aparece primeiro?",
    pergunta: "Toda cadeia começa por qual tipo de ser vivo?",
    fotoUrl: cadeia,
    opcoes: [
      { id: "produtor", titulo: "PRODUTOR", subtitulo: "planta", emoji: "🌱", cor: "from-emerald-400 to-green-700" },
      { id: "consumidor", titulo: "CONSUMIDOR", subtitulo: "animal", emoji: "🐆", cor: "from-amber-400 to-orange-700" },
      { id: "decompositor", titulo: "DECOMPOSITOR", subtitulo: "fungo", emoji: "🍄", cor: "from-fuchsia-400 to-purple-700" },
    ],
    respostaCerta: "produtor",
    feedbackAcerto: "Certo. Plantas capturam energia SOLAR — ninguém mais faz isso. Toda cadeia começa nelas.",
    feedbackErro: "Sem planta, ninguém come. A base é sempre o PRODUTOR (planta).",
    falaFinal: "Sem produtor, a cadeia inteira desaba. Plantas são a fundação da vida.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco papéis que todo ser vivo cumpre no ecossistema.",
    instrucao: "Vocabulário técnico da ecologia",
    cadernos: [
      { id: "produtor", capa: "PRODUTOR", emoji: "🌱", cor: "from-emerald-500 to-green-700",
        conteudo: "Planta que capta luz do sol e fabrica seu próprio alimento (fotossíntese).",
        exemplo: "Ex.: capim, mangueira, alface.", fotoUrl: produtor },
      { id: "consumidor1", capa: "CONSUMIDOR 1º", emoji: "🐇", cor: "from-teal-500 to-cyan-700",
        conteudo: "Herbívoro — só come plantas. É o primeiro elo animal da cadeia.",
        exemplo: "Ex.: coelho, capivara, gafanhoto.", fotoUrl: floresta },
      { id: "consumidor2", capa: "CONSUMIDOR 2º", emoji: "🐆", cor: "from-amber-500 to-orange-700",
        conteudo: "Carnívoro — come outros animais. Regula a população de herbívoros.",
        exemplo: "Ex.: onça, gavião, cobra.", fotoUrl: consumidor },
      { id: "decompositor", capa: "DECOMPOSITOR", emoji: "🍄", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Fungo ou bactéria que quebra restos de plantas e animais mortos, devolvendo nutrientes pra terra.",
        exemplo: "Ex.: cogumelos, bolor, minhocas.", fotoUrl: decompositor },
      { id: "teia", capa: "TEIA ALIMENTAR", emoji: "🕸️", cor: "from-cyan-500 to-sky-700",
        conteudo: "Rede de várias cadeias interligadas. Mostra que na natureza os elos se cruzam.",
        exemplo: "Ex.: onça come capivara E veado.", fotoUrl: cadeia },
    ],
    falaFinal: "Produtor, consumidor e decompositor. Sem qualquer um dos três, o ecossistema quebra.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A floresta. Toca em cada elemento pra ver o papel dele.",
    instrucao: "Toque em cada elemento",
    mapaUrl: floresta,
    pontos: [
      { id: "arvore", x: 25, y: 40, emoji: "🌳", cor: "from-emerald-500 to-green-700",
        titulo: "Árvore", texto: "Produtor. Faz fotossíntese e sustenta toda a cadeia com sua energia armazenada.",
        fotoUrl: produtor },
      { id: "onca", x: 65, y: 55, emoji: "🐆", cor: "from-amber-500 to-orange-700",
        titulo: "Onça", texto: "Consumidor de topo. Controla a população de herbívoros — sem ela, a floresta desequilibra.",
        fotoUrl: consumidor },
      { id: "fungo", x: 45, y: 85, emoji: "🍄", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Fungo", texto: "Decompositor. Devolve nutrientes do solo pras plantas crescerem — fecha o ciclo.",
        fotoUrl: decompositor },
      { id: "sol", x: 80, y: 15, emoji: "☀️", cor: "from-amber-400 to-orange-600",
        titulo: "Sol", texto: "Fonte de energia inicial. Sem sol, não há fotossíntese — nem vida como conhecemos.",
        fotoUrl: floresta },
      { id: "solo", x: 15, y: 90, emoji: "🌱", cor: "from-teal-500 to-emerald-700",
        titulo: "Solo", texto: "Recebe nutrientes dos decompositores e devolve pras raízes das plantas.",
        fotoUrl: decompositor },
    ],
    falaFinal: "Sol → planta → animal → fungo → solo → planta. É um ciclo, não uma linha reta.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de ecologia.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "De onde vem a energia inicial de qualquer cadeia alimentar?",
        fotoUrl: produtor,
        cards: [
          { id: "a", emoji: "☀️", titulo: "Do Sol, através das plantas", cor: "from-amber-500 to-orange-700" },
          { id: "b", emoji: "🌍", titulo: "Do centro da Terra", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🌧️", titulo: "Da chuva", cor: "from-cyan-500 to-sky-700" },
        ], correta: "a",
        feedbackAcerto: "Isso. Toda energia biológica vem do Sol, capturada pelas plantas.",
        feedbackErro: "A fonte é sempre o Sol. Plantas convertem luz em alimento — daí a energia flui." },
      { id: "q2", pergunta: "O que aconteceria se todos os decompositores desaparecessem?",
        fotoUrl: decompositor,
        cards: [
          { id: "a", emoji: "🗑️", titulo: "Restos se acumulariam e nutrientes acabariam", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "🎉", titulo: "Nada mudaria", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🌳", titulo: "Mais árvores nasceriam", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Sem decompositores, os nutrientes não voltam ao solo e as plantas morrem.",
        feedbackErro: "Decompositores fecham o ciclo. Sem eles, o solo vira estéril." },
      { id: "q3", pergunta: "Qual a diferença entre CADEIA e TEIA alimentar?",
        fotoUrl: cadeia,
        cards: [
          { id: "a", emoji: "➡️", titulo: "Cadeia é linear; teia tem vários cruzamentos", cor: "from-teal-500 to-emerald-700" },
          { id: "b", emoji: "🤝", titulo: "São a mesma coisa", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🕸️", titulo: "Só teia tem plantas", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Cadeia é uma sequência simples; teia é a rede real, com muitos elos cruzados.",
        feedbackErro: "Cadeia = linha reta. Teia = rede com várias cadeias interligadas." },
    ],
    falaFinal: "Você entende como a energia flui no planeta. É base pra qualquer ecologia.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "O ecossistema tem duas camadas: a VIVA (seres) e a NÃO-VIVA (sol, solo, água). Liga as duas.",
    instrucao: "Toque nos interruptores",
    mapaUrl: floresta,
    camadas: [
      { id: "viva", rotulo: "Camada Viva", emoji: "🌿", cor: "from-emerald-500 to-green-700",
        rect: { x: 2, y: 25, w: 96, h: 45 },
        descricao: "Plantas, animais e fungos — os SERES do ecossistema.",
        fotoUrl: consumidor },
      { id: "naoviva", rotulo: "Camada Não-Viva", emoji: "☀️", cor: "from-amber-500 to-orange-700",
        rect: { x: 2, y: 70, w: 96, h: 28 },
        descricao: "Sol, solo, água, ar. Não são vivos, mas sustentam toda a vida.",
        fotoUrl: floresta },
    ],
    falaFinal: "Sem a camada não-viva, a viva não existe. Os dois lados são interdependentes.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte o fluxo de energia numa cadeia alimentar.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Do sol ao fungo — qual a sequência?",
    paradas: [
      { id: "sol", emoji: "☀️", rotulo: "1. Sol", descricao: "Fonte primária de energia.", fotoUrl: floresta },
      { id: "planta", emoji: "🌱", rotulo: "2. Planta", descricao: "Produtor — captura energia solar.", fotoUrl: produtor },
      { id: "herbivoro", emoji: "🐇", rotulo: "3. Herbívoro", descricao: "Consumidor 1º — come planta.", fotoUrl: floresta },
      { id: "carnivoro", emoji: "🐆", rotulo: "4. Carnívoro", descricao: "Consumidor 2º — come herbívoro.", fotoUrl: consumidor },
      { id: "fungo", emoji: "🍄", rotulo: "5. Decompositor", descricao: "Devolve nutrientes ao solo.", fotoUrl: decompositor },
    ],
    ordemCerta: ["sol", "planta", "herbivoro", "carnivoro", "fungo"],
    feedbackAcerto: "Fluxo completo. Energia flui do sol até virar terra fértil de novo.",
    feedbackErro: "Repense: sempre começa no SOL, depois planta, depois animais.",
    falaFinal: "Esse fluxo acontece em qualquer floresta, savana ou oceano. É universal.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura autônoma. Estuda o registro do biólogo.",
    tituloLivro: "📓 Diário do Biólogo · Mata Atlântica",
    subtitulo: "Observação de campo, semana 3",
    paragrafos: [
      { id: "p1", texto:
          "Passei o dia observando um trecho da Mata Atlântica. Anotei PRODUTORES (samambaias, palmeiras, cipós) que captam luz do sol. Sem eles, nada mais funciona — toda energia da floresta começa aqui.",
        chaves: ["produtores"], definicoes: { produtores: "Plantas que fabricam alimento com luz solar." },
        fotoUrl: produtor },
      { id: "p2", texto:
          "Vi CONSUMIDORES em ação: tucanos comendo frutos, macacos-prego roubando ovos, uma onça-pintada descansando na sombra. Cada um ocupa um NÍVEL da cadeia — herbívoro, onívoro ou carnívoro.",
        chaves: ["consumidores", "nível"],
        definicoes: {
          consumidores: "Animais que comem outros seres vivos.",
          nível: "Posição de um ser na cadeia alimentar.",
        }, fotoUrl: consumidor },
      { id: "p3", texto:
          "Sob o tronco caído: DECOMPOSITORES fazendo o trabalho invisível. Cogumelos, bolor e cupins reduzindo a madeira a nutrientes. Esse material vai virar solo — e alimentar as próximas plantas. A TEIA se fecha.",
        chaves: ["decompositores", "teia"],
        definicoes: {
          decompositores: "Seres que reciclam matéria morta.",
          teia: "Rede completa de cadeias alimentares interligadas.",
        }, fotoUrl: decompositor },
    ],
    falaFinal: "Você acabou de ler um diário de campo real. É assim que biólogos documentam a vida.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra um ser vivo — identifica o PAPEL dele no ecossistema.",
    instrucao: "⏱️ Leia e escolha o papel correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "produtor", emoji: "🌱", rotulo: "Produtor" },
      { id: "consumidor", emoji: "🐆", rotulo: "Consumidor" },
      { id: "decompositor", emoji: "🍄", rotulo: "Decompositor" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Mangueira", emoji: "🥭", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Faz fotossíntese", emoji: "☀️", cor: "from-amber-500 to-orange-700" },
        contexto: "Uma mangueira absorve luz e fabrica seu próprio alimento.",
        pecaCertaId: "produtor", fotoUrl: produtor,
        feedbackAcerto: "Sim. Faz fotossíntese = PRODUTOR.",
        feedbackErro: "Plantas fazem fotossíntese e produzem alimento — são PRODUTORES." },
      { id: "r2", municipioA: { nome: "Onça-pintada", emoji: "🐆", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "Come outros animais", emoji: "🥩", cor: "from-red-500 to-rose-700" },
        contexto: "A onça caça capivaras e queixadas na floresta.",
        pecaCertaId: "consumidor", fotoUrl: consumidor,
        feedbackAcerto: "Perfeito. Come outros seres = CONSUMIDOR.",
        feedbackErro: "Quem se alimenta de outros seres é CONSUMIDOR." },
      { id: "r3", municipioA: { nome: "Cogumelo", emoji: "🍄", cor: "from-fuchsia-500 to-purple-700" },
        municipioB: { nome: "Vive em tronco caído", emoji: "🪵", cor: "from-slate-500 to-slate-700" },
        contexto: "Cogumelos crescem em madeira morta, transformando-a em nutrientes pro solo.",
        pecaCertaId: "decompositor", fotoUrl: decompositor,
        feedbackAcerto: "Isso. Recicla matéria morta = DECOMPOSITOR.",
        feedbackErro: "Fungos que reciclam matéria morta são DECOMPOSITORES." },
      { id: "r4", municipioA: { nome: "Capivara", emoji: "🐹", cor: "from-teal-500 to-emerald-700" },
        municipioB: { nome: "Come capim", emoji: "🌾", cor: "from-emerald-500 to-green-700" },
        contexto: "Capivara passa o dia pastando às margens do rio.",
        pecaCertaId: "consumidor", fotoUrl: floresta,
        feedbackAcerto: "Sim. Come planta = CONSUMIDOR (herbívoro).",
        feedbackErro: "Herbívoros também são CONSUMIDORES — só que do 1º nível." },
      { id: "r5", municipioA: { nome: "Bactéria do solo", emoji: "🦠", cor: "from-purple-500 to-fuchsia-700" },
        municipioB: { nome: "Quebra folhas mortas", emoji: "🍂", cor: "from-amber-500 to-orange-700" },
        contexto: "Bactérias microscópicas decompõem folhas caídas devolvendo minerais à terra.",
        pecaCertaId: "decompositor", fotoUrl: decompositor,
        feedbackAcerto: "Isso. Bactérias e fungos são DECOMPOSITORES.",
        feedbackErro: "Se quebra matéria morta e devolve nutrientes ao solo = DECOMPOSITOR." },
    ],
    falaFinal: "Você classifica qualquer ser vivo pela função ecológica. É como biólogo pensa.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "O ecossistema em duas grandes partes: FLUXO DE ENERGIA (linear, do sol pros consumidores) e CICLO DE MATÉRIA (circular, através dos decompositores).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: floresta,
    fatias: [
      { id: "energia", rotulo: "Fluxo de Energia", emoji: "☀️", percentual: 45, cor: "#f59e0b",
        descricao: "Energia entra pelo sol, passa pelas plantas e animais, e SE PERDE como calor.",
        exemplos: ["Sol", "Planta", "Herbívoro", "Carnívoro"], fotoUrl: produtor },
      { id: "materia", rotulo: "Ciclo de Matéria", emoji: "🔄", percentual: 55, cor: "#059669",
        descricao: "Os átomos rodam pra sempre: planta → animal → decompositor → solo → planta.",
        exemplos: ["Folha cai", "Fungo decompõe", "Solo fértil", "Nova planta"], fotoUrl: decompositor },
    ],
    falaFinal: "Energia flui e se dispersa. Matéria circula pra sempre. Duas leis básicas da ecologia.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas de ecologia — sua carteira de Ecologista Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: floresta,
    perguntas: [
      { id: "q1", pergunta: "Sem plantas, o que aconteceria com os animais?",
        fotoUrl: produtor,
        opcoes: [
          { id: "a", texto: "Ficariam sem base de energia e morreriam", correta: true },
          { id: "b", texto: "Nada, animais podem viver sem plantas" },
        ],
        feedbackAcerto: "Isso. Plantas são a base — sem elas, toda a cadeia colapsa.",
        feedbackErro: "Toda energia da cadeia vem das plantas. Sem elas, ninguém come." },
      { id: "q2", pergunta: "Fungos e bactérias são importantes para o quê?",
        fotoUrl: decompositor,
        opcoes: [
          { id: "a", texto: "Reciclar matéria morta e alimentar o solo", correta: true },
          { id: "b", texto: "Só causar doenças" },
        ],
        feedbackAcerto: "Correto. A maioria dos fungos e bactérias trabalha reciclando — não causando doença.",
        feedbackErro: "Sem decompositores, o planeta seria uma pilha de matéria morta." },
      { id: "q3", pergunta: "Cadeia alimentar sempre começa por qual tipo de ser?",
        fotoUrl: cadeia,
        opcoes: [
          { id: "a", texto: "Produtor (planta)", correta: true },
          { id: "b", texto: "Consumidor (animal)" },
        ],
        feedbackAcerto: "Sim. Sempre começa no produtor — quem captura a energia solar.",
        feedbackErro: "Sem produtor, não há energia. A base é sempre a planta." },
    ],
    selo: {
      nome: "Ecologista Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 2 concluído",
      emoji: "🌿",
      cor: "from-emerald-400 via-green-500 to-teal-700",
    },
    falaFinal: "Você virou ecologista júnior. Próxima parada: seu próprio corpo por dentro.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Ecologista Júnior" },
};
