import type { AulaGeoV1 } from "../../types";
import biomas from "@/assets/geografia-6ano/biomas-brasil.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-biomas-brasileiros",
  titulo: "Biomas Brasileiros",
  iconeTrilha: "🌳",
  bncc: ["EF06GE13"],
  duracaoMin: 25,
  estilo: "teen",

  cena01_motivacao: {
    tipo: "mesaCartografo",
    estilo: "teen",
    instrucao: "6 biomas, 1 país. Cada um com plantas, bichos e vidas únicas.",
    mapaUrl: biomas,
    imagemDestaqueUrl: biomas,
    aurora:
      "Explorador, o Brasil é MEGADIVERSO. Aqui vivem 20% de todas as espécies do planeta. E não por acaso: temos 6 biomas — AMAZÔNIA, CERRADO, CAATINGA, MATA ATLÂNTICA, PAMPA e PANTANAL. Cada um com clima, solo e vegetação próprios.",
    falaFinal: "6 biomas = 6 laboratórios da natureza. Vamos conhecer cada um.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Qual bioma cobre a MAIOR parte do Brasil?",
    pergunta: "O gigante do país é:",
    opcoes: [
      { id: "amaz", titulo: "AMAZÔNIA", subtitulo: "floresta tropical úmida", emoji: "🌳", cor: "from-emerald-400 to-green-700" },
      { id: "mata", titulo: "MATA ATLÂNTICA", subtitulo: "floresta do litoral", emoji: "🌲", cor: "from-teal-400 to-emerald-700" },
    ],
    respostaCerta: "amaz",
    feedbackAcerto:
      "Exato! AMAZÔNIA ocupa 49% do território — quase metade do Brasil.",
    feedbackErro: "Mata Atlântica cobre pouco (10%). AMAZÔNIA = quase metade.",
    falaFinal: "Amazônia é o gigante verde. Guarde: 49% do Brasil.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "6 biomas, 4 palavras-chave pra entender.",
    instrucao: "Toque em cada caderno",
    cadernos: [
      { id: "bioma", capa: "1. Bioma", emoji: "🌿", cor: "from-emerald-500 to-green-700",
        conteudo: "BIOMA é um conjunto de ecossistemas com CLIMA, SOLO e VEGETAÇÃO parecidos, ocupando uma grande região.",
        exemplo: "Ex.: Amazônia = clima úmido + solo pobre + floresta densa." },
      { id: "biodiv", capa: "2. Biodiversidade", emoji: "🐆", cor: "from-amber-500 to-orange-700",
        conteudo: "BIODIVERSIDADE é a variedade de vida — quantas espécies diferentes existem numa região.",
        exemplo: "Ex.: Amazônia tem MAIS biodiversidade que Caatinga." },
      { id: "endemica", capa: "3. Espécie endêmica", emoji: "🦜", cor: "from-purple-500 to-fuchsia-700",
        conteudo: "ENDÊMICA é uma espécie que só existe NAQUELE lugar do mundo, em nenhum outro.",
        exemplo: "Ex.: Mico-leão-dourado só existe na Mata Atlântica." },
      { id: "desmate", capa: "4. Desmatamento", emoji: "🪓", cor: "from-red-500 to-rose-700",
        conteudo: "DESMATAMENTO é a destruição da vegetação nativa por corte ou queimada. Reduz biodiversidade.",
        exemplo: "Ex.: Mata Atlântica já perdeu 88% da área original." },
    ],
    falaFinal: "Bioma, biodiversidade, endêmica, desmate. 4 palavras que salvam a natureza.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "Aponte cada bioma do Brasil.",
    instrucao: "Toque em cada balão",
    mapaUrl: biomas,
    pontos: [
      { id: "amaz", x: 25, y: 30, emoji: "🌳", cor: "from-emerald-500 to-green-700",
        titulo: "AMAZÔNIA (49%)",
        texto: "Maior floresta tropical do mundo. Rios gigantes, árvores altíssimas, milhões de espécies. Pulmão do planeta." },
      { id: "cerra", x: 55, y: 55, emoji: "🌾", cor: "from-amber-500 to-orange-700",
        titulo: "CERRADO (24%)",
        texto: "Savana brasileira. Árvores baixas e tortas, gramíneas. Chamado 'berço das águas' — nascentes de rios importantes." },
      { id: "caat", x: 75, y: 45, emoji: "🌵", cor: "from-yellow-500 to-orange-700",
        titulo: "CAATINGA (10%)",
        texto: "Único bioma exclusivamente brasileiro. Semiárido: cactos, plantas espinhosas, chuva rara mas vida abundante." },
      { id: "mata", x: 75, y: 70, emoji: "🌲", cor: "from-teal-500 to-emerald-700",
        titulo: "MATA ATLÂNTICA (10%)",
        texto: "Floresta do litoral, do NE ao Sul. 88% já destruída. Ainda concentra 70% da população do país." },
      { id: "pamp", x: 50, y: 90, emoji: "🐎", cor: "from-lime-500 to-green-700",
        titulo: "PAMPA (2%)",
        texto: "Campos do RS. Gramíneas, poucas árvores. Terra do gaúcho e do gado de corte." },
      { id: "pant", x: 40, y: 65, emoji: "💧", cor: "from-sky-500 to-blue-700",
        titulo: "PANTANAL (2%)",
        texto: "Maior planície alagável do mundo. Ecossistema misto. Onça, jacaré, tuiuiú, capivara — vida animal explosiva." },
    ],
    falaFinal: "6 biomas, 6 caras do Brasil. Da Amazônia ao Pampa.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de biólogo.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Bioma EXCLUSIVAMENTE brasileiro:",
        cards: [
          { id: "c", emoji: "🌵", titulo: "Caatinga", cor: "from-amber-500 to-orange-700" },
          { id: "a", emoji: "🌳", titulo: "Amazônia", cor: "from-emerald-500 to-green-700" },
          { id: "m", emoji: "🌲", titulo: "Mata Atlântica", cor: "from-teal-500 to-emerald-700" },
        ], correta: "c",
        feedbackAcerto: "Isso! CAATINGA só existe no Brasil.", feedbackErro: "Amazônia se estende por 9 países. CAATINGA é só nossa." },
      { id: "q2", pergunta: "Maior planície alagável do mundo:",
        cards: [
          { id: "p", emoji: "💧", titulo: "Pantanal", cor: "from-sky-500 to-blue-700" },
          { id: "a", emoji: "🌳", titulo: "Amazônia", cor: "from-emerald-500 to-green-700" },
          { id: "pa", emoji: "🐎", titulo: "Pampa", cor: "from-lime-500 to-green-700" },
        ], correta: "p",
        feedbackAcerto: "Isso! PANTANAL = maior planície alagável.", feedbackErro: "Amazônia é floresta. Pampa é campo. PANTANAL alaga." },
      { id: "q3", pergunta: "Bioma mais AMEAÇADO (88% destruído):",
        cards: [
          { id: "ma", emoji: "🌲", titulo: "Mata Atlântica", cor: "from-teal-500 to-emerald-700" },
          { id: "am", emoji: "🌳", titulo: "Amazônia", cor: "from-emerald-500 to-green-700" },
          { id: "pa", emoji: "🐎", titulo: "Pampa", cor: "from-lime-500 to-green-700" },
        ], correta: "ma",
        feedbackAcerto: "Isso! MATA ATLÂNTICA perdeu 88%.", feedbackErro: "MATA ATLÂNTICA está mais destruída (88%)." },
    ],
    falaFinal: "Radar afiado. Bora ao mapa.",
  },

  cena06_personagensLugar: {
    tipo: "mapaBrasilInterativo",
    aurora:
      "A AMAZÔNIA ocupa 9 estados do Norte. Marque os principais.",
    instrucao: "Acenda os estados da Amazônia Legal (Norte)",
    missao: {
      tipo: "selecionar",
      siglas: ["AM", "PA", "AC", "RO", "RR", "AP", "TO"],
      pergunta: "Quais estados compõem a Amazônia?",
    },
    falaFinal:
      "7 estados do Norte. Mais MT e MA fecham a Amazônia Legal. Um Brasil dentro do Brasil.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Organize os biomas do MAIOR pro MENOR em área.",
    instrucao: "Toque na ordem",
    pergunta: "Do maior pro menor bioma:",
    paradas: [
      { id: "am", emoji: "🌳", rotulo: "1. Amazônia (49%)",
        descricao: "Quase metade do território nacional." },
      { id: "ce", emoji: "🌾", rotulo: "2. Cerrado (24%)",
        descricao: "Segundo maior. Domina o Centro-Oeste." },
      { id: "ma", emoji: "🌲", rotulo: "3. Mata Atlântica (13%)",
        descricao: "Litoral do NE ao Sul. Muito reduzida." },
      { id: "ca", emoji: "🌵", rotulo: "4. Caatinga (10%)",
        descricao: "Sertão nordestino." },
      { id: "pa", emoji: "🐎", rotulo: "5. Pampa (2%)",
        descricao: "Campos do Rio Grande do Sul." },
      { id: "pt", emoji: "💧", rotulo: "6. Pantanal (2%)",
        descricao: "Planície alagável do Centro-Oeste." },
    ],
    ordemCerta: ["am", "ce", "ma", "ca", "pa", "pt"],
    feedbackAcerto: "Perfeito! Ranking correto dos biomas.",
    feedbackErro: "Amazônia domina (49%), Cerrado é o segundo. Ordena por tamanho.",
    falaFinal: "Amazônia + Cerrado = 73% do Brasil. Assustador.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua vez.",
    tituloLivro: "📘 Manual do Explorador Planetário",
    subtitulo: "Capítulo 6 — Biomas",
    paragrafos: [
      { id: "p1", texto: "O Brasil tem SEIS biomas: Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampa e Pantanal.",
        chaves: ["seis", "biomas", "amazônia"] },
      { id: "p2", texto: "A AMAZÔNIA é o maior bioma, cobrindo QUASE METADE do território nacional (49%).",
        chaves: ["amazônia", "maior", "49"] },
      { id: "p3", texto: "A CAATINGA é o único bioma EXCLUSIVAMENTE brasileiro, com cactos e plantas espinhosas.",
        chaves: ["caatinga", "exclusivamente", "brasileiro"] },
      { id: "p4", texto: "A MATA ATLÂNTICA é o bioma MAIS AMEAÇADO — já perdeu 88% de sua área original.",
        chaves: ["mata", "atlântica", "ameaçado", "88"] },
    ],
    falaFinal: "Leu tudo?",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Minijogo BIÓLOGO EXPRESS! Que bioma é esse?",
    instrucao: "⏱️ Identifique o bioma",
    duracaoSegundos: 12,
    pecas: [
      { id: "am", emoji: "🌳", rotulo: "Amazônia" },
      { id: "ce", emoji: "🌾", rotulo: "Cerrado" },
      { id: "ca", emoji: "🌵", rotulo: "Caatinga" },
      { id: "ma", emoji: "🌲", rotulo: "Mata Atlântica" },
      { id: "pa", emoji: "🐎", rotulo: "Pampa" },
      { id: "pt", emoji: "💧", rotulo: "Pantanal" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Onça-pintada, tuiuiú", emoji: "🐆", cor: "from-sky-400 to-blue-600" },
        municipioB: { nome: "Alaga na cheia", emoji: "💧", cor: "from-blue-400 to-indigo-600" },
        contexto: "Planície gigante que alaga trazendo vida animal explosiva. Que bioma?",
        pecaCertaId: "pt",
        feedbackAcerto: "Isso! PANTANAL — planície alagável.", feedbackErro: "Alagamento e onça = PANTANAL." },
      { id: "r2", municipioA: { nome: "Mandacaru, xique-xique", emoji: "🌵", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Chuva rara, sertão", emoji: "☀️", cor: "from-yellow-400 to-red-600" },
        contexto: "Cactos e plantas espinhosas no sertão nordestino. Que bioma?",
        pecaCertaId: "ca",
        feedbackAcerto: "Isso! CAATINGA — único brasileiro.", feedbackErro: "Cactos + sertão = CAATINGA." },
      { id: "r3", municipioA: { nome: "Chuva o ano todo", emoji: "☔", cor: "from-emerald-400 to-green-600" },
        municipioB: { nome: "Rio Amazonas", emoji: "🌊", cor: "from-sky-400 to-blue-600" },
        contexto: "Maior floresta tropical do mundo. Que bioma?",
        pecaCertaId: "am",
        feedbackAcerto: "Isso! AMAZÔNIA — pulmão do planeta.", feedbackErro: "Floresta gigante + Amazonas = AMAZÔNIA." },
      { id: "r4", municipioA: { nome: "Árvores tortas", emoji: "🌾", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Berço das águas", emoji: "💧", cor: "from-sky-400 to-blue-600" },
        contexto: "Savana com árvores baixas e tortas — Brasília fica aqui. Que bioma?",
        pecaCertaId: "ce",
        feedbackAcerto: "Isso! CERRADO — savana brasileira.", feedbackErro: "Savana + Brasília = CERRADO." },
      { id: "r5", municipioA: { nome: "Mico-leão-dourado", emoji: "🐒", cor: "from-emerald-400 to-teal-600" },
        municipioB: { nome: "88% destruída", emoji: "🌲", cor: "from-red-400 to-rose-600" },
        contexto: "Floresta original do litoral, 88% já foi devastada. Que bioma?",
        pecaCertaId: "ma",
        feedbackAcerto: "Isso! MATA ATLÂNTICA — a mais ameaçada.", feedbackErro: "Litoral + mico-leão + 88% = MATA ATLÂNTICA." },
      { id: "r6", municipioA: { nome: "Campos abertos", emoji: "🌱", cor: "from-lime-400 to-green-600" },
        municipioB: { nome: "Gaúcho e churrasco", emoji: "🐎", cor: "from-amber-400 to-orange-600" },
        contexto: "Campos com pouca árvore no RS. Que bioma?",
        pecaCertaId: "pa",
        feedbackAcerto: "Isso! PAMPA — campos gaúchos.", feedbackErro: "Campos + RS = PAMPA." },
    ],
    falaFinal: "6 biomas, 6 acertos!",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "Pizza dos BIOMAS por área.",
    instrucao: "Toque em cada fatia",
    fatias: [
      { id: "am", rotulo: "Amazônia (49%)", emoji: "🌳", percentual: 49, cor: "#059669",
        descricao: "Metade do país. Floresta tropical úmida com o maior rio do mundo em vazão.",
        exemplos: ["🌳 Castanheira", "🐆 Onça", "🐟 Pirarucu"] },
      { id: "outros", rotulo: "Outros 5 biomas (51%)", emoji: "🌍", percentual: 51, cor: "#d97706",
        descricao: "Cerrado, Caatinga, Mata Atlântica, Pampa e Pantanal juntos.",
        exemplos: ["🌾 Cerrado", "🌵 Caatinga", "💧 Pantanal"] },
    ],
    falaFinal: "1 bioma toma quase metade. Os outros 5 dividem o resto.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 finais.",
    instrucao: "Responda as 3",
    perguntas: [
      { id: "av1", pergunta: "Quantos biomas o Brasil possui?",
        opcoes: [
          { id: "a", texto: "3 biomas", correta: false },
          { id: "b", texto: "6 biomas", correta: true },
          { id: "c", texto: "10 biomas", correta: false },
        ],
        feedbackAcerto: "Isso! 6 biomas.", feedbackErro: "SEIS biomas: Amazônia, Cerrado, Caatinga, Mata Atlântica, Pampa, Pantanal." },
      { id: "av2", pergunta: "Bioma EXCLUSIVO do Brasil:",
        opcoes: [
          { id: "a", texto: "Amazônia", correta: false },
          { id: "b", texto: "Caatinga", correta: true },
          { id: "c", texto: "Mata Atlântica", correta: false },
        ],
        feedbackAcerto: "Isso! CAATINGA só existe aqui.", feedbackErro: "Amazônia e Mata Atlântica estão em outros países. CAATINGA é só nossa." },
      { id: "av3", pergunta: "Bioma MAIS destruído do Brasil:",
        opcoes: [
          { id: "a", texto: "Mata Atlântica (88% perdida)", correta: true },
          { id: "b", texto: "Amazônia", correta: false },
          { id: "c", texto: "Pampa", correta: false },
        ],
        feedbackAcerto: "Isso! MATA ATLÂNTICA perdeu 88%.", feedbackErro: "MATA ATLÂNTICA é o mais ameaçado (88% perdida)." },
    ],
    selo: { nome: "Biólogo Iniciante", subtitulo: "Insígnia do Explorador Planetário", emoji: "🌳", cor: "from-emerald-500 to-green-700" },
    falaFinal: "Insígnia conquistada!",
  },

  recompensa: { xp: 400, moedas: 300, medalha: "Biólogo Iniciante" },
};
