import type { AulaGeoV1 } from "../../types";
import { url as lab } from "@/assets/ciencias-5ano/u4-a1/laboratorio.jpg.asset.json";
import { url as aguaOleo } from "@/assets/ciencias-5ano/u4-a1/agua-oleo.jpg.asset.json";
import { url as filtro } from "@/assets/ciencias-5ano/u4-a1/filtracao.jpg.asset.json";
import { url as vapor } from "@/assets/ciencias-5ano/u4-a1/evaporacao.jpg.asset.json";
import { url as gelo } from "@/assets/ciencias-5ano/u4-a1/gelo-agua.jpg.asset.json";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-materia-transformacao",
  titulo: "Matéria em Transformação",
  iconeTrilha: "🧪",
  bncc: ["EF05CI02"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela bancada. Encontre os estados e as misturas que a equipe vai investigar.",
    mapaUrl: lab,
    imagemDestaqueUrl: aguaOleo,
    aurora: "Tudo que existe é MATÉRIA. Nesta bancada temos matéria em três estados e várias misturas. Vamos ver como uma pode virar a outra.",
    falaFinal: "A matéria muda de forma o tempo todo. Cientista aprende a controlar essa transformação.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Se você mistura água e óleo, o que acontece?",
    pergunta: "Como o óleo se comporta na água?",
    fotoUrl: aguaOleo,
    opcoes: [
      { id: "cima", titulo: "SOBE", subtitulo: "menos denso", emoji: "⬆️", cor: "from-amber-400 to-orange-700" },
      { id: "mistura", titulo: "MISTURA", subtitulo: "vira homogêneo", emoji: "🌀", cor: "from-slate-400 to-slate-700" },
      { id: "some", titulo: "SOME", subtitulo: "desaparece", emoji: "❓", cor: "from-red-400 to-rose-700" },
    ],
    respostaCerta: "cima",
    feedbackAcerto: "Certo. Óleo é MENOS DENSO que a água — flutua acima dela.",
    feedbackErro: "Óleo não some nem mistura com água. Ele fica em cima porque é MENOS denso.",
    falaFinal: "Densidade decide quem vai pra cima. Menos denso flutua, mais denso afunda.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco palavras que você precisa dominar em Química básica.",
    instrucao: "Vocabulário da matéria",
    cadernos: [
      { id: "solido", capa: "SÓLIDO", emoji: "🧊", cor: "from-cyan-500 to-sky-700",
        conteudo: "Forma e volume próprios. Partículas bem juntas e organizadas.",
        exemplo: "Ex.: pedra, ferro, gelo.", fotoUrl: gelo },
      { id: "liquido", capa: "LÍQUIDO", emoji: "💧", cor: "from-teal-500 to-emerald-700",
        conteudo: "Volume próprio, mas forma do recipiente. Partículas soltas mas próximas.",
        exemplo: "Ex.: água, suco, azeite.", fotoUrl: aguaOleo },
      { id: "gasoso", capa: "GASOSO", emoji: "💨", cor: "from-slate-400 to-slate-700",
        conteudo: "Sem forma nem volume próprios. Partículas separadas e em movimento.",
        exemplo: "Ex.: ar, vapor d'água, gás butano.", fotoUrl: vapor },
      { id: "homogenea", capa: "MIST. HOMOGÊNEA", emoji: "🥛", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Uma fase visível — não dá pra ver o que está misturado.",
        exemplo: "Ex.: água com sal dissolvido.", fotoUrl: lab },
      { id: "heterogenea", capa: "MIST. HETEROGÊNEA", emoji: "🥗", cor: "from-orange-500 to-amber-700",
        conteudo: "Duas ou mais fases visíveis — dá pra separar os componentes.",
        exemplo: "Ex.: água + óleo, salada, granola.", fotoUrl: aguaOleo },
    ],
    falaFinal: "3 estados + 2 tipos de mistura. Este é o alfabeto da matéria.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A bancada de química. Toca em cada item pra ver o experimento.",
    instrucao: "Toque em cada item",
    mapaUrl: lab,
    pontos: [
      { id: "bequer", x: 30, y: 55, emoji: "🧪", cor: "from-red-500 to-rose-700",
        titulo: "Béquer vermelho", texto: "Solução aquosa homogênea — corante dissolvido em água.",
        fotoUrl: lab },
      { id: "azul", x: 65, y: 55, emoji: "💧", cor: "from-cyan-500 to-sky-700",
        titulo: "Frasco azul", texto: "Outro exemplo de mistura homogênea — não conseguimos separar visualmente.",
        fotoUrl: lab },
      { id: "oleo", x: 15, y: 75, emoji: "🌀", cor: "from-amber-500 to-orange-700",
        titulo: "Água + óleo", texto: "Mistura HETEROGÊNEA clássica — duas camadas bem visíveis.",
        fotoUrl: aguaOleo },
      { id: "filtro", x: 80, y: 75, emoji: "☕", cor: "from-emerald-500 to-green-700",
        titulo: "Filtração", texto: "Separa sólidos de líquidos usando papel filtro — água limpa passa, sujeira fica.",
        fotoUrl: filtro },
      { id: "oculos", x: 50, y: 85, emoji: "🥽", cor: "from-slate-500 to-slate-700",
        titulo: "Óculos de proteção", texto: "Segurança no laboratório é regra — proteção dos olhos é obrigatória.",
        fotoUrl: lab },
    ],
    falaFinal: "Cada experimento mostra uma propriedade diferente da matéria.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de matéria.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Ao aquecer água, ela vira vapor. Qual mudança é essa?",
        fotoUrl: vapor,
        cards: [
          { id: "a", emoji: "☀️", titulo: "Evaporação (líquido → gás)", cor: "from-cyan-500 to-sky-700" },
          { id: "b", emoji: "🧊", titulo: "Solidificação (líquido → sólido)", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "💧", titulo: "Condensação (gás → líquido)", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Água quente vira vapor — é EVAPORAÇÃO.",
        feedbackErro: "Líquido virando gás por calor é EVAPORAÇÃO." },
      { id: "q2", pergunta: "Água + óleo é qual tipo de mistura?",
        fotoUrl: aguaOleo,
        cards: [
          { id: "a", emoji: "🌀", titulo: "Homogênea (uma fase só)", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "🥗", titulo: "Heterogênea (duas fases visíveis)", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "❓", titulo: "Não é mistura", cor: "from-slate-500 to-slate-700" },
        ], correta: "b",
        feedbackAcerto: "Correto. Dá pra ver duas camadas separadas — é HETEROGÊNEA.",
        feedbackErro: "Se dá pra ver duas fases distintas, a mistura é HETEROGÊNEA." },
      { id: "q3", pergunta: "Filtrando um copo de terra com água, o que fica no filtro?",
        fotoUrl: filtro,
        cards: [
          { id: "a", emoji: "🌍", titulo: "A terra (partícula grande)", cor: "from-amber-500 to-orange-700" },
          { id: "b", emoji: "💧", titulo: "A água (partícula pequena)", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "❌", titulo: "Nada", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Isso. Partículas grandes não passam pelo papel — água atravessa, terra fica.",
        feedbackErro: "Água atravessa o filtro. A terra (sólido) fica retida." },
    ],
    falaFinal: "Você entende os fundamentos das transformações da matéria.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "A bancada divide-se em duas zonas: MISTURAS (o que fazer) e SEPARAÇÕES (como desmisturar). Liga cada uma.",
    instrucao: "Toque nos interruptores",
    mapaUrl: lab,
    camadas: [
      { id: "misturas", rotulo: "Zona de Misturas", emoji: "🧪", cor: "from-red-500 to-rose-700",
        rect: { x: 2, y: 30, w: 48, h: 65 },
        descricao: "Béqueres coloridos e frascos com misturas homogêneas e heterogêneas prontas pra estudar.",
        fotoUrl: lab },
      { id: "separacoes", rotulo: "Zona de Separações", emoji: "☕", cor: "from-emerald-500 to-green-700",
        rect: { x: 50, y: 30, w: 48, h: 65 },
        descricao: "Filtros, funis e béqueres pra separar componentes das misturas.",
        fotoUrl: filtro },
    ],
    falaFinal: "Misturar é fácil; separar é ciência. Cada método serve pra um tipo de mistura.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a sequência de estados da água ao ser aquecida.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Do gelo ao vapor — qual a ordem?",
    paradas: [
      { id: "gelo", emoji: "🧊", rotulo: "1. Gelo", descricao: "Estado sólido — partículas organizadas.", fotoUrl: gelo },
      { id: "fusao", emoji: "💧", rotulo: "2. Fusão", descricao: "Aquecendo, o gelo derrete e vira água líquida.", fotoUrl: gelo },
      { id: "agua", emoji: "🚰", rotulo: "3. Água", descricao: "Estado líquido — partículas soltas.", fotoUrl: aguaOleo },
      { id: "evaporacao", emoji: "🔥", rotulo: "4. Evaporação", descricao: "Água aquecida perde forma e vira vapor.", fotoUrl: vapor },
      { id: "vapor", emoji: "💨", rotulo: "5. Vapor", descricao: "Estado gasoso — partículas espalhadas.", fotoUrl: vapor },
    ],
    ordemCerta: ["gelo", "fusao", "agua", "evaporacao", "vapor"],
    feedbackAcerto: "Sequência completa. Calor faz partículas se soltarem — sólido → líquido → gás.",
    feedbackErro: "Repense: sólido derrete antes de virar líquido; líquido evapora antes de virar gás.",
    falaFinal: "Essa é a base do ciclo da água — que abastece rios, lagos e chuvas.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Leitura autônoma. Estuda o registro do químico.",
    tituloLivro: "📓 Diário do Químico · Experimento 12",
    subtitulo: "Estados físicos e misturas",
    paragrafos: [
      { id: "p1", texto:
          "Toda MATÉRIA é feita de partículas. Nos SÓLIDOS, elas ficam bem juntas e organizadas — por isso o gelo tem forma fixa. Nos LÍQUIDOS, as partículas ficam próximas mas soltas, e o líquido se adapta ao formato do recipiente.",
        chaves: ["matéria", "sólidos", "líquidos"],
        definicoes: {
          matéria: "Tudo que ocupa espaço e tem massa.",
          sólidos: "Estado com forma e volume próprios.",
          líquidos: "Estado com volume próprio mas forma variável.",
        }, fotoUrl: gelo },
      { id: "p2", texto:
          "Nos GASES, as partículas estão bem espalhadas e em alta velocidade. Um gás ocupa todo o espaço disponível. Ao aquecer água líquida, ela EVAPORA — as partículas ganham energia e escapam como vapor.",
        chaves: ["gases", "evapora"],
        definicoes: {
          gases: "Estado sem forma nem volume próprios.",
          evapora: "Líquido virando gás por aquecimento.",
        }, fotoUrl: vapor },
      { id: "p3", texto:
          "Quando duas substâncias se juntam, formamos uma MISTURA. Se dá pra ver as duas partes (água + óleo), é HETEROGÊNEA. Se parece uma coisa só (água + sal), é HOMOGÊNEA. Podemos SEPARAR misturas por filtração, decantação ou evaporação.",
        chaves: ["mistura", "heterogênea", "homogênea", "separar"],
        definicoes: {
          mistura: "União de duas ou mais substâncias.",
          heterogênea: "Mistura com fases visíveis distintas.",
          homogênea: "Mistura que parece uma substância só.",
          separar: "Desfazer a mistura em seus componentes.",
        }, fotoUrl: aguaOleo },
    ],
    falaFinal: "Você acabou de aprender a base da química que estudará por muitos anos.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra uma cena — identifica o ESTADO ou tipo de mistura.",
    instrucao: "⏱️ Leia e escolha o conceito",
    duracaoSegundos: 20,
    pecas: [
      { id: "solido", emoji: "🧊", rotulo: "Sólido" },
      { id: "liquido", emoji: "💧", rotulo: "Líquido" },
      { id: "gasoso", emoji: "💨", rotulo: "Gasoso" },
      { id: "homogenea", emoji: "🥛", rotulo: "Homogênea" },
      { id: "heterogenea", emoji: "🥗", rotulo: "Heterogênea" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Cubo de gelo", emoji: "🧊", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Forma fixa", emoji: "🔷", cor: "from-slate-500 to-slate-700" },
        contexto: "Um cubo de gelo mantém forma quadrada mesmo fora do freezer.",
        pecaCertaId: "solido", fotoUrl: gelo,
        feedbackAcerto: "Sim. Forma fixa = SÓLIDO.",
        feedbackErro: "Forma própria significa estado SÓLIDO." },
      { id: "r2", municipioA: { nome: "Suco no copo", emoji: "🧃", cor: "from-orange-500 to-amber-700" },
        municipioB: { nome: "Toma forma do vidro", emoji: "🥛", cor: "from-cyan-500 to-sky-700" },
        contexto: "O suco toma a forma exata do copo onde foi despejado.",
        pecaCertaId: "liquido", fotoUrl: aguaOleo,
        feedbackAcerto: "Perfeito. Toma forma do recipiente = LÍQUIDO.",
        feedbackErro: "Se toma a forma do recipiente é LÍQUIDO." },
      { id: "r3", municipioA: { nome: "Vapor da chaleira", emoji: "💨", cor: "from-slate-400 to-slate-700" },
        municipioB: { nome: "Sem forma nem volume", emoji: "🌫️", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Vapor sobe da chaleira e se espalha por toda a cozinha.",
        pecaCertaId: "gasoso", fotoUrl: vapor,
        feedbackAcerto: "Isso. Sem forma nem volume = GASOSO.",
        feedbackErro: "Se espalha por todo o ambiente sem forma = GASOSO." },
      { id: "r4", municipioA: { nome: "Café com açúcar", emoji: "☕", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "Não dá pra ver o açúcar", emoji: "🥛", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Você mexe o café com açúcar e a mistura fica uniforme — o açúcar 'some'.",
        pecaCertaId: "homogenea", fotoUrl: lab,
        feedbackAcerto: "Sim. Uma fase só = HOMOGÊNEA.",
        feedbackErro: "Quando parece uma coisa só, é mistura HOMOGÊNEA." },
      { id: "r5", municipioA: { nome: "Salada de frutas", emoji: "🥗", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Vê cada fruta", emoji: "🍓", cor: "from-red-500 to-rose-700" },
        contexto: "Salada de frutas — dá pra ver morango, maçã e uva separadamente.",
        pecaCertaId: "heterogenea", fotoUrl: aguaOleo,
        feedbackAcerto: "Perfeito. Fases visíveis = HETEROGÊNEA.",
        feedbackErro: "Se você vê as partes distintas, é mistura HETEROGÊNEA." },
    ],
    falaFinal: "Você classifica qualquer matéria e mistura. Fundamento da química.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "A matéria em dois grandes assuntos: ESTADOS FÍSICOS (sólido/líquido/gás) e MISTURAS (homo/hetero + separações).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: lab,
    fatias: [
      { id: "estados", rotulo: "Estados Físicos", emoji: "🧊", percentual: 40, cor: "#0891b2",
        descricao: "Sólido, líquido, gasoso — e as mudanças entre eles (fusão, evaporação, condensação).",
        exemplos: ["Gelo → água", "Água → vapor", "Vapor → nuvem"], fotoUrl: gelo },
      { id: "misturas", rotulo: "Misturas e Separações", emoji: "🧪", percentual: 60, cor: "#059669",
        descricao: "Como classificar misturas e como separá-las por filtração, decantação e evaporação.",
        exemplos: ["Água + óleo (heterogênea)", "Água + sal (homogênea)", "Filtrar", "Evaporar"], fotoUrl: aguaOleo },
    ],
    falaFinal: "Estados e misturas são o começo da química. Base pra tudo que vem depois.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Químico Júnior liberada.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: lab,
    perguntas: [
      { id: "q1", pergunta: "Ao derreter, o gelo passa de qual estado pra qual?",
        fotoUrl: gelo,
        opcoes: [
          { id: "a", texto: "Sólido para líquido", correta: true },
          { id: "b", texto: "Gasoso para líquido" },
        ],
        feedbackAcerto: "Sim. Fusão = SÓLIDO → LÍQUIDO.",
        feedbackErro: "Gelo é sólido, água é líquida. Derreter = SÓLIDO → LÍQUIDO." },
      { id: "q2", pergunta: "Água + areia é qual tipo de mistura?",
        fotoUrl: filtro,
        opcoes: [
          { id: "a", texto: "Heterogênea (dá pra ver as partes)", correta: true },
          { id: "b", texto: "Homogênea (parece uma coisa só)" },
        ],
        feedbackAcerto: "Correto. Areia visível na água = HETEROGÊNEA.",
        feedbackErro: "Se você VÊ os componentes, é HETEROGÊNEA." },
      { id: "q3", pergunta: "Qual método separa areia de água?",
        fotoUrl: filtro,
        opcoes: [
          { id: "a", texto: "Filtração", correta: true },
          { id: "b", texto: "Congelamento" },
        ],
        feedbackAcerto: "Isso. FILTRAÇÃO — sólido fica no papel, líquido passa.",
        feedbackErro: "Congelar não separa. FILTRAÇÃO é o método correto." },
    ],
    selo: {
      nome: "Químico Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 4 concluído",
      emoji: "⚗️",
      cor: "from-cyan-400 via-teal-500 to-emerald-700",
    },
    falaFinal: "Químico júnior aprovado. Próximo laboratório: energia e tecnologia.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Químico Júnior" },
};
