import type { CursoEI, AulaEI } from "@/escola-brilha/curso-portugues-ei/types";
import { url as brilha } from "@/assets/neuro-treino/objetos/esquilo-brilha.png.asset.json";
import { url as bola } from "@/assets/neuro-treino/objetos/bola.png.asset.json";
import { url as estrela } from "@/assets/neuro-treino/objetos/estrela.png.asset.json";
import { url as flor } from "@/assets/neuro-treino/objetos/flor.png.asset.json";
import { url as joaninha } from "@/assets/neuro-treino/objetos/joaninha.png.asset.json";
import { url as balao } from "@/assets/neuro-treino/objetos/balao.png.asset.json";
import { url as maca } from "@/assets/neuro-treino/objetos/maca.png.asset.json";

import { url as n0 } from "@/assets/banco-midias/numeros/numero-0.png.asset.json";
import { url as n1 } from "@/assets/banco-midias/numeros/numero-1.png.asset.json";
import { url as n2 } from "@/assets/banco-midias/numeros/numero-2.png.asset.json";
import { url as n3 } from "@/assets/banco-midias/numeros/numero-3.png.asset.json";
import { url as n4 } from "@/assets/banco-midias/numeros/numero-4.png.asset.json";
import { url as n5 } from "@/assets/banco-midias/numeros/numero-5.png.asset.json";
import { url as n6 } from "@/assets/banco-midias/numeros/numero-6.png.asset.json";
import { url as n7 } from "@/assets/banco-midias/numeros/numero-7.png.asset.json";
import { url as n8 } from "@/assets/banco-midias/numeros/numero-8.png.asset.json";
import { url as n9 } from "@/assets/banco-midias/numeros/numero-9.png.asset.json";
import n10 from "@/assets/banco-midias/numeros/numero-10.png";

/**
 * Contar com Pip — FASE 6 · Comparação de Magnitude
 * -------------------------------------------------
 * Mais / Menos / Igual. Percepção direta (ANS · Approximate Number
 * System) → comparação exata via contagem → comparação de numerais
 * usando distância na linha numérica e âncoras (5 e 10).
 *
 * Base:
 *  - Dehaene (1997) — senso numérico e magnitude.
 *  - Halberda & Feigenson (2008) — ANS em pré-escolares.
 *  - Griffin (Number Worlds) — sequência mais/menos/igual.
 *  - Ramani & Siegler (2008) — distância na linha numérica.
 *
 * Semana 1 · MAIS e MENOS (percepção direta, grupos bem diferentes)
 * Semana 2 · IGUAL / correspondência 1-a-1 (grupos parecidos)
 * Semana 3 · Comparando NUMERAIS (0–10) — número maior = mais
 * Semana 4 · Mestre da Comparação + DIPLOMA
 */

const mascote = brilha;

const NUM: Record<number, string> = {
  0: n0, 1: n1, 2: n2, 3: n3, 4: n4, 5: n5,
  6: n6, 7: n7, 8: n8, 9: n9, 10: n10,
};

const opN = (n: number, correta: boolean) => ({
  nome: String(n),
  imagemUrl: NUM[n],
  correta,
  quantidade: 1 as const,
});

// ============================================================
// SEMANA 1 · MAIS e MENOS (percepção direta)
// ============================================================

const dia01: AulaEI = {
  slug: "pip-f6-s1-d1-mais-e-menos",
  titulo: "Dia 1 · Quem tem MAIS?",
  icone: "➕",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Fase 6! Hoje comparamos grupos: quem tem MAIS e quem tem MENOS. Sem contar, só de olhada!" },
    { tipo: "compararGrupos", instrucaoAudio: "Olha os dois grupos.",
      perguntaAudio: "Qual grupo tem MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 1, correta: false }, { qtd: 6, correta: true }],
      feedbackAcerto: "Isso! 6 é MAIS que 1.", feedbackErro: "O grupo com 6 tem mais." },
    { tipo: "compararGrupos", instrucaoAudio: "De novo.",
      perguntaAudio: "Qual grupo tem MAIS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "mais",
      opcoes: [{ qtd: 5, correta: true }, { qtd: 2, correta: false }],
      feedbackAcerto: "5 é MAIS que 2!", feedbackErro: "5 tem mais que 2." },
    { tipo: "compararGrupos", instrucaoAudio: "Olha.",
      perguntaAudio: "Qual grupo tem MAIS flores?", imagemUrl: flor, itemPlural: "flores",
      alvo: "mais",
      opcoes: [{ qtd: 3, correta: false }, { qtd: 7, correta: true }],
      feedbackAcerto: "7 é MAIS que 3.", feedbackErro: "7 é mais." },
    { tipo: "compararGrupos", instrucaoAudio: "Mais uma.",
      perguntaAudio: "Qual grupo tem MAIS joaninhas?", imagemUrl: joaninha, itemPlural: "joaninhas",
      alvo: "mais",
      opcoes: [{ qtd: 8, correta: true }, { qtd: 4, correta: false }],
      feedbackAcerto: "8 é mais que 4!", feedbackErro: "8 é maior." },
    { tipo: "compararGrupos", instrucaoAudio: "Última.",
      perguntaAudio: "Qual tem MAIS balões?", imagemUrl: balao, itemPlural: "balões",
      alvo: "mais",
      opcoes: [{ qtd: 2, correta: false }, { qtd: 9, correta: true }],
      feedbackAcerto: "9 tem MUITO mais que 2!", feedbackErro: "9 é mais que 2." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Prato mais cheio",
      convite: "Coloque uvas em dois pratos (5 e 2). Pergunte: 'Qual prato tem MAIS?' Deixe a criança escolher.",
      dicaAdulto: "Comparação com objetos reais reforça magnitude (Dehaene)." },
    { tipo: "celebracao", medalha: "Dia 1 · Vi o MAIS", mascoteUrl: mascote,
      falaFinal: "Você já enxerga o MAIS!" },
  ],
  baseCientifica: "Percepção direta de magnitude (ANS · Halberda 2008).",
};

const dia02: AulaEI = {
  slug: "pip-f6-s1-d2-quem-tem-menos",
  titulo: "Dia 2 · Quem tem MENOS?",
  icone: "➖",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Hoje é o contrário: quem tem MENOS? MENOS quer dizer o grupo bem pequeno." },
    { tipo: "compararGrupos", instrucaoAudio: "Olha os grupos.",
      perguntaAudio: "Qual grupo tem MENOS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "menos",
      opcoes: [{ qtd: 2, correta: true }, { qtd: 7, correta: false }],
      feedbackAcerto: "2 é MENOS que 7!", feedbackErro: "2 é menos que 7." },
    { tipo: "compararGrupos", instrucaoAudio: "De novo.",
      perguntaAudio: "Qual tem MENOS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "menos",
      opcoes: [{ qtd: 6, correta: false }, { qtd: 1, correta: true }],
      feedbackAcerto: "1 é o menor!", feedbackErro: "1 é menos que 6." },
    { tipo: "compararGrupos", instrucaoAudio: "Continua.",
      perguntaAudio: "Qual tem MENOS flores?", imagemUrl: flor, itemPlural: "flores",
      alvo: "menos",
      opcoes: [{ qtd: 8, correta: false }, { qtd: 3, correta: true }],
      feedbackAcerto: "3 é menos que 8.", feedbackErro: "3 é o menor." },
    { tipo: "compararGrupos", instrucaoAudio: "Vamos.",
      perguntaAudio: "Qual tem MENOS maçãs?", imagemUrl: maca, itemPlural: "maçãs",
      alvo: "menos",
      opcoes: [{ qtd: 4, correta: true }, { qtd: 9, correta: false }],
      feedbackAcerto: "4 é menos que 9!", feedbackErro: "4 é menos." },
    { tipo: "compararGrupos", instrucaoAudio: "Última.",
      perguntaAudio: "Qual tem MENOS balões?", imagemUrl: balao, itemPlural: "balões",
      alvo: "menos",
      opcoes: [{ qtd: 5, correta: false }, { qtd: 2, correta: true }],
      feedbackAcerto: "2!", feedbackErro: "2 é menos que 5." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Menos petiscos",
      convite: "Dois pratos com biscoitos (2 e 6). Pergunte qual tem MENOS. Depois pergunte qual ela prefere e por quê.",
      dicaAdulto: "Trabalha vocabulário matemático + preferência (linguagem)." },
    { tipo: "celebracao", medalha: "Dia 2 · Vi o MENOS", mascoteUrl: mascote,
      falaFinal: "MENOS aprendido!" },
  ],
  baseCientifica: "Contraste MAIS × MENOS estabiliza o par comparativo (Griffin).",
};

const dia03: AulaEI = {
  slug: "pip-f6-s1-d3-mais-perto",
  titulo: "Dia 3 · Comparação apertada",
  icone: "🤏",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "E quando os grupos são PARECIDOS? Aí a gente conta pra ter certeza!" },
    { tipo: "compararGrupos", instrucaoAudio: "Olha bem.",
      perguntaAudio: "Qual tem MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 4, correta: false }, { qtd: 5, correta: true }],
      feedbackAcerto: "5 é 1 a mais que 4!", feedbackErro: "5 é mais que 4." },
    { tipo: "compararGrupos", instrucaoAudio: "Difícil.",
      perguntaAudio: "Qual tem MAIS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "mais",
      opcoes: [{ qtd: 6, correta: true }, { qtd: 5, correta: false }],
      feedbackAcerto: "6 é 1 a mais que 5.", feedbackErro: "6 é maior." },
    { tipo: "compararGrupos", instrucaoAudio: "Cuidado.",
      perguntaAudio: "Qual tem MENOS flores?", imagemUrl: flor, itemPlural: "flores",
      alvo: "menos",
      opcoes: [{ qtd: 7, correta: false }, { qtd: 6, correta: true }],
      feedbackAcerto: "6 é 1 a menos que 7.", feedbackErro: "6 é menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 4 e 5, qual é MAIOR?",
      opcoes: [opN(5, true), opN(4, false), opN(3, false)],
      feedbackAcerto: "5 é maior!", feedbackErro: "5 vem depois de 4, então é maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 7 e 8, qual é MAIOR?",
      opcoes: [opN(8, true), opN(7, false), opN(6, false)],
      feedbackAcerto: "8!", feedbackErro: "8 vem depois de 7." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Empate parecido",
      convite: "Faça duas fileiras com 4 e 5 objetos. Peça pra criança emparelhar 1 a 1: sobra um → esse tem MAIS.",
      dicaAdulto: "Correspondência 1-a-1 é a técnica formal de comparação (Piaget)." },
    { tipo: "celebracao", medalha: "Dia 3 · Comparação de perto", mascoteUrl: mascote,
      falaFinal: "Você comparou grupos parecidos!" },
  ],
  baseCientifica: "Comparação de números vizinhos exige contagem (Griffin).",
};

const dia04: AulaEI = {
  slug: "pip-f6-s1-d4-mais-um-menos-um",
  titulo: "Dia 4 · 1 a mais, 1 a menos",
  icone: "⬆️",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "1 a mais é o próximo. 1 a menos é o anterior. Vamos treinar!" },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MAIS que 3 é?",
      opcoes: [opN(4, true), opN(2, false), opN(5, false)],
      feedbackAcerto: "4!", feedbackErro: "3, 4. É 4." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MAIS que 6 é?",
      opcoes: [opN(7, true), opN(5, false), opN(8, false)],
      feedbackAcerto: "7!", feedbackErro: "6, 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MENOS que 5 é?",
      opcoes: [opN(4, true), opN(6, false), opN(3, false)],
      feedbackAcerto: "4!", feedbackErro: "1 antes de 5 é 4." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MENOS que 8 é?",
      opcoes: [opN(7, true), opN(9, false), opN(6, false)],
      feedbackAcerto: "7!", feedbackErro: "1 antes de 8 é 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MAIS que 9 é?",
      opcoes: [opN(10, true), opN(8, false), opN(9, false)],
      feedbackAcerto: "10!", feedbackErro: "9, 10." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Sobe um, desce um",
      convite: "Diga um número (ex: 4). Peça 1 a MAIS. Depois 1 a MENOS. Alternem.",
      dicaAdulto: "Fluência em +1/-1 é preditor de sucesso em soma (Baroody)." },
    { tipo: "celebracao", medalha: "Dia 4 · Vizinhos dominados", mascoteUrl: mascote,
      falaFinal: "Você anda pra frente e pra trás na sequência!" },
  ],
  baseCientifica: "Fluência com +1/-1 conecta contagem a operações.",
};

const dia05: AulaEI = {
  slug: "pip-f6-s1-d5-revisao-mais-menos",
  titulo: "Dia 5 · Revisão MAIS/MENOS",
  icone: "🏅",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Última da semana! Prova rápida do MAIS e MENOS." },
    { tipo: "compararGrupos", instrucaoAudio: "Rápido.",
      perguntaAudio: "MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 3, correta: false }, { qtd: 8, correta: true }],
      feedbackAcerto: "8!", feedbackErro: "8 tem mais." },
    { tipo: "compararGrupos", instrucaoAudio: "Rápido.",
      perguntaAudio: "MENOS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "menos",
      opcoes: [{ qtd: 2, correta: true }, { qtd: 9, correta: false }],
      feedbackAcerto: "2!", feedbackErro: "2 tem menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MAIS que 4?",
      opcoes: [opN(5, true), opN(3, false), opN(6, false)],
      feedbackAcerto: "5!", feedbackErro: "5." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 a MENOS que 7?",
      opcoes: [opN(6, true), opN(8, false), opN(5, false)],
      feedbackAcerto: "6!", feedbackErro: "6." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 5 e 9, qual é MAIOR?",
      opcoes: [opN(9, true), opN(5, false), opN(7, false)],
      feedbackAcerto: "9!", feedbackErro: "9 vem depois de 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 2 e 6, qual é MENOR?",
      opcoes: [opN(2, true), opN(6, false), opN(4, false)],
      feedbackAcerto: "2!", feedbackErro: "2 vem antes de 6." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Medalha da semana",
      convite: "Aplauda a criança: 'Você aprendeu MAIS e MENOS!' Fale 3 exemplos do dia (mais uva, menos suco...).",
      dicaAdulto: "Vocabulário matemático se transfere quando usado em contexto real." },
    { tipo: "celebracao", medalha: "MEDALHA · MAIS e MENOS", mascoteUrl: mascote,
      falaFinal: "Medalha da Semana 1 conquistada!" },
  ],
  baseCientifica: "Revisão sistemática consolida (spaced practice).",
};

// ============================================================
// SEMANA 2 · IGUAL / Correspondência 1-a-1
// ============================================================

const dia06: AulaEI = {
  slug: "pip-f6-s2-d1-igual",
  titulo: "Dia 6 · Quando é IGUAL?",
  icone: "🟰",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "IGUAL é quando os dois grupos têm a MESMA quantidade. Nem mais, nem menos." },
    { tipo: "contarBolas", imagemUrl: bola, quantidade: 3,
      itemSingular: "bola", itemPlural: "bolas",
      instrucaoAudio: "Conta esse grupo.", elogio: "3!" },
    { tipo: "contarBolas", imagemUrl: bola, quantidade: 3,
      itemSingular: "bola", itemPlural: "bolas",
      instrucaoAudio: "Agora esse.", elogio: "3! IGUAL!" },
    { tipo: "compreensaoImagem", perguntaAudio: "Se um grupo tem 3 e o outro tem 3, eles são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[3], correta: true, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[5], correta: false, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[8], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "Se têm a mesma quantidade, são iguais." },
    { tipo: "compreensaoImagem", perguntaAudio: "5 e 5 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[5], correta: true, quantidade: 1 },
               { nome: "5 é mais", imagemUrl: NUM[6], correta: false, quantidade: 1 },
               { nome: "5 é menos", imagemUrl: NUM[4], correta: false, quantidade: 1 }],
      feedbackAcerto: "5 e 5 são IGUAIS.", feedbackErro: "Mesmo número = igual." },
    { tipo: "compreensaoImagem", perguntaAudio: "7 e 7 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[7], correta: true, quantidade: 1 },
               { nome: "diferentes", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "mais", imagemUrl: NUM[9], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "7 = 7." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Divisão igual",
      convite: "Coloque 6 uvas e peça pra criança dividir IGUAL pra 2 pratos. 3 e 3.",
      dicaAdulto: "Igualdade concreta antecipa noção de metade e divisão justa." },
    { tipo: "celebracao", medalha: "Dia 6 · IGUAL descoberto", mascoteUrl: mascote,
      falaFinal: "Agora você tem: MAIS, MENOS e IGUAL!" },
  ],
  baseCientifica: "Equivalência é a base do sinal de igualdade (Baroody).",
};

const dia07: AulaEI = {
  slug: "pip-f6-s2-d2-emparelhar",
  titulo: "Dia 7 · Emparelhar 1 a 1",
  icone: "🔗",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Um jeito seguro: EMPARELHAR. Uma da esquerda pra uma da direita. Sobrou? Esse tem MAIS!" },
    { tipo: "compararGrupos", instrucaoAudio: "Empareia mentalmente.",
      perguntaAudio: "Qual tem MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 5, correta: false }, { qtd: 6, correta: true }],
      feedbackAcerto: "6! Empareia 5 com 5, sobra 1.", feedbackErro: "6 sobra 1." },
    { tipo: "compararGrupos", instrucaoAudio: "Empareia.",
      perguntaAudio: "Qual tem MAIS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "mais",
      opcoes: [{ qtd: 4, correta: false }, { qtd: 5, correta: true }],
      feedbackAcerto: "5!", feedbackErro: "5 sobra 1." },
    { tipo: "compararGrupos", instrucaoAudio: "Empareia.",
      perguntaAudio: "Qual tem MENOS flores?", imagemUrl: flor, itemPlural: "flores",
      alvo: "menos",
      opcoes: [{ qtd: 4, correta: true }, { qtd: 6, correta: false }],
      feedbackAcerto: "4! Sobram 2 no de 6.", feedbackErro: "4 é menos." },
    { tipo: "compararGrupos", instrucaoAudio: "Iguais?",
      perguntaAudio: "Qual tem MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 5, correta: false }, { qtd: 7, correta: true }],
      feedbackAcerto: "7!", feedbackErro: "7 é mais que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Se empareio 4 com 4 e não sobra nada, é?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[4], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[8], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[1], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "Se não sobra, é igual." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Copo e canudo",
      convite: "Coloque 5 copos e 6 canudos. Peça pra colocar um canudo em cada copo. Sobrou? Tem MAIS canudo!",
      dicaAdulto: "Emparelhamento é comparação sem contar (Piaget)." },
    { tipo: "celebracao", medalha: "Dia 7 · Emparelhei", mascoteUrl: mascote,
      falaFinal: "Emparelhar é sua nova ferramenta!" },
  ],
  baseCientifica: "Correspondência 1-a-1 (Gelman & Gallistel).",
};

const dia08: AulaEI = {
  slug: "pip-f6-s2-d3-igual-nao-igual",
  titulo: "Dia 8 · Igual ou diferente?",
  icone: "🤔",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Rápido: os grupos são IGUAIS ou DIFERENTES?" },
    { tipo: "compreensaoImagem", perguntaAudio: "Grupo de 4 e grupo de 4 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[4], correta: true, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[9], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "4 = 4." },
    { tipo: "compreensaoImagem", perguntaAudio: "Grupo de 3 e grupo de 6 são?",
      opcoes: [{ nome: "DIFERENTES", imagemUrl: NUM[6], correta: true, quantidade: 1 },
               { nome: "IGUAIS", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "IGUAIS", imagemUrl: NUM[0], correta: false, quantidade: 1 }],
      feedbackAcerto: "DIFERENTES.", feedbackErro: "3 ≠ 6." },
    { tipo: "compreensaoImagem", perguntaAudio: "Grupo de 10 e grupo de 10 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[10], correta: true, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[5], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[1], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "10 = 10." },
    { tipo: "compreensaoImagem", perguntaAudio: "Grupo de 8 e grupo de 2 são?",
      opcoes: [{ nome: "DIFERENTES", imagemUrl: NUM[8], correta: true, quantidade: 1 },
               { nome: "IGUAIS", imagemUrl: NUM[2], correta: false, quantidade: 1 },
               { nome: "IGUAIS", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "DIFERENTES.", feedbackErro: "8 ≠ 2." },
    { tipo: "compreensaoImagem", perguntaAudio: "5 e 5?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[5], correta: true, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[6], correta: false, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[7], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "5 = 5." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Caça ao igual",
      convite: "Achem em casa 2 grupos iguais (2 sapatos, 2 pratos...). Falem: 'IGUAL!'",
      dicaAdulto: "Igualdade no mundo real ajuda a criança generalizar." },
    { tipo: "celebracao", medalha: "Dia 8 · Igual e diferente", mascoteUrl: mascote,
      falaFinal: "Você sabe distinguir igual de diferente!" },
  ],
  baseCientifica: "Discriminação categórica de equivalência (Griffin).",
};

const dia09: AulaEI = {
  slug: "pip-f6-s2-d4-mais-menos-igual",
  titulo: "Dia 9 · MAIS, MENOS ou IGUAL?",
  icone: "🎲",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Agora tudo junto: pode ser MAIS, MENOS ou IGUAL." },
    { tipo: "compreensaoImagem", perguntaAudio: "6 comparado com 3 é?",
      opcoes: [{ nome: "MAIS", imagemUrl: NUM[6], correta: true, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[3], correta: false, quantidade: 1 }],
      feedbackAcerto: "6 é MAIS que 3.", feedbackErro: "6 é mais." },
    { tipo: "compreensaoImagem", perguntaAudio: "2 comparado com 7 é?",
      opcoes: [{ nome: "MENOS", imagemUrl: NUM[2], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[7], correta: false, quantidade: 1 }],
      feedbackAcerto: "2 é MENOS que 7.", feedbackErro: "2 é menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "4 comparado com 4 é?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[4], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[6], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[2], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL.", feedbackErro: "4 = 4." },
    { tipo: "compreensaoImagem", perguntaAudio: "9 comparado com 5 é?",
      opcoes: [{ nome: "MAIS", imagemUrl: NUM[9], correta: true, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[5], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "9 é mais!", feedbackErro: "9 é mais que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "1 comparado com 8 é?",
      opcoes: [{ nome: "MENOS", imagemUrl: NUM[1], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[8], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[8], correta: false, quantidade: 1 }],
      feedbackAcerto: "1 é MUITO menos.", feedbackErro: "1 é menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "10 comparado com 10?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[10], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[9], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[8], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL!", feedbackErro: "10 = 10." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Três pilhas",
      convite: "Faça 3 pilhas de biscoitos (2, 5, 5). Pergunte: 'Quais são IGUAIS? Qual tem MENOS?'",
      dicaAdulto: "Comparar 3 grupos exige coordenação — desafio saudável." },
    { tipo: "celebracao", medalha: "Dia 9 · Três palavras", mascoteUrl: mascote,
      falaFinal: "MAIS, MENOS, IGUAL — tudo no bolso!" },
  ],
  baseCientifica: "Discriminação tripla (Griffin).",
};

const dia10: AulaEI = {
  slug: "pip-f6-s2-d5-medalha-igual",
  titulo: "Dia 10 · Medalha do IGUAL",
  icone: "🏅",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Última da semana! Prova rápida com IGUAL e correspondência." },
    { tipo: "compararGrupos", instrucaoAudio: "Empareia.",
      perguntaAudio: "MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 6, correta: false }, { qtd: 7, correta: true }],
      feedbackAcerto: "7!", feedbackErro: "7 sobra 1." },
    { tipo: "compararGrupos", instrucaoAudio: "Empareia.",
      perguntaAudio: "MENOS flores?", imagemUrl: flor, itemPlural: "flores",
      alvo: "menos",
      opcoes: [{ qtd: 3, correta: true }, { qtd: 4, correta: false }],
      feedbackAcerto: "3!", feedbackErro: "3 é menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "6 e 6 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[6], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "6 = 6." },
    { tipo: "compreensaoImagem", perguntaAudio: "8 comparado com 8 é?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[8], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[9], correta: false, quantidade: 1 },
               { nome: "MENOS", imagemUrl: NUM[7], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL!", feedbackErro: "8 = 8." },
    { tipo: "compreensaoImagem", perguntaAudio: "0 e 0 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[0], correta: true, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[1], correta: false, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[2], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS! Nenhum = nenhum.", feedbackErro: "0 = 0." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Cerimônia da igualdade",
      convite: "Diga: 'Você aprendeu MAIS, MENOS e IGUAL!' Aplausos e um abraço.",
      dicaAdulto: "Reconhecimento afetivo consolida aprendizado (Dweck)." },
    { tipo: "celebracao", medalha: "MEDALHA · IGUAL & Emparelhar", mascoteUrl: mascote,
      falaFinal: "Medalha da Semana 2 conquistada!" },
  ],
  baseCientifica: "Fechamento da Semana 2.",
};

// ============================================================
// SEMANA 3 · Comparando NUMERAIS (0–10)
// ============================================================

const dia11: AulaEI = {
  slug: "pip-f6-s3-d1-numeros-comparar",
  titulo: "Dia 11 · Comparando NÚMEROS",
  icone: "🔢",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Sem grupos hoje. Comparamos só o NÚMERO. Quem vem DEPOIS na sequência é MAIOR!" },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 2 ou 5?",
      opcoes: [opN(5, true), opN(2, false), opN(3, false)],
      feedbackAcerto: "5! Vem depois de 2.", feedbackErro: "5 é maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 7 ou 3?",
      opcoes: [opN(7, true), opN(3, false), opN(5, false)],
      feedbackAcerto: "7!", feedbackErro: "7 vem depois." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 9 ou 6?",
      opcoes: [opN(9, true), opN(6, false), opN(8, false)],
      feedbackAcerto: "9!", feedbackErro: "9 é maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MENOR: 4 ou 8?",
      opcoes: [opN(4, true), opN(8, false), opN(6, false)],
      feedbackAcerto: "4! Vem antes.", feedbackErro: "4 é menor." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MENOR: 3 ou 1?",
      opcoes: [opN(1, true), opN(3, false), opN(2, false)],
      feedbackAcerto: "1!", feedbackErro: "1 vem antes." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 10 ou 7?",
      opcoes: [opN(10, true), opN(7, false), opN(8, false)],
      feedbackAcerto: "10!", feedbackErro: "10 é o maior até agora." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Duelo de números",
      convite: "Escreva 2 números. Peça pra criança apontar o MAIOR. Trocando os papéis a cada rodada.",
      dicaAdulto: "Jogos de comparação numérica (Ramani & Siegler 2008)." },
    { tipo: "celebracao", medalha: "Dia 11 · Números comparados", mascoteUrl: mascote,
      falaFinal: "Você compara só olhando o número!" },
  ],
  baseCientifica: "Comparação de numerais na linha numérica (Dehaene).",
};

const dia12: AulaEI = {
  slug: "pip-f6-s3-d2-longe-perto",
  titulo: "Dia 12 · Bem longe, bem perto",
  icone: "📏",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Alguns pares são LONGE (1 e 9) e outros PERTO (5 e 6). Longe é fácil, perto exige atenção!" },
    { tipo: "compreensaoImagem", perguntaAudio: "Fácil: qual é MAIOR: 1 ou 9?",
      opcoes: [opN(9, true), opN(1, false), opN(5, false)],
      feedbackAcerto: "9! Muito longe do 1.", feedbackErro: "9 é maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Difícil: qual é MAIOR: 5 ou 6?",
      opcoes: [opN(6, true), opN(5, false), opN(4, false)],
      feedbackAcerto: "6! 1 a mais que 5.", feedbackErro: "6 vem depois." },
    { tipo: "compreensaoImagem", perguntaAudio: "Fácil: qual é MENOR: 2 ou 10?",
      opcoes: [opN(2, true), opN(10, false), opN(5, false)],
      feedbackAcerto: "2!", feedbackErro: "2 é o menor." },
    { tipo: "compreensaoImagem", perguntaAudio: "Difícil: qual é MENOR: 7 ou 8?",
      opcoes: [opN(7, true), opN(8, false), opN(9, false)],
      feedbackAcerto: "7! Vem antes de 8.", feedbackErro: "7 é menor." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 3 ou 4?",
      opcoes: [opN(4, true), opN(3, false), opN(2, false)],
      feedbackAcerto: "4!", feedbackErro: "4 vem depois de 3." },
    { tipo: "compreensaoImagem", perguntaAudio: "Qual é MAIOR: 8 ou 9?",
      opcoes: [opN(9, true), opN(8, false), opN(7, false)],
      feedbackAcerto: "9!", feedbackErro: "9 vem depois de 8." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Longe e perto",
      convite: "Diga 2 números. Pergunte: 'Estão LONGE ou PERTO?' (1 e 9 = longe; 4 e 5 = perto)",
      dicaAdulto: "Efeito distância (Dehaene): pares próximos custam mais tempo." },
    { tipo: "celebracao", medalha: "Dia 12 · Efeito distância", mascoteUrl: mascote,
      falaFinal: "Perto ou longe, você compara!" },
  ],
  baseCientifica: "Efeito distância na comparação numérica (Dehaene).",
};

const dia13: AulaEI = {
  slug: "pip-f6-s3-d3-mais-que-menos-que",
  titulo: "Dia 13 · Maior que 5? Menor que 5?",
  icone: "🎯",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "5 é a ÂNCORA. Vamos ver quem é MAIOR que 5 e quem é MENOR que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "7 é MAIOR ou MENOR que 5?",
      opcoes: [{ nome: "MAIOR", imagemUrl: NUM[7], correta: true, quantidade: 1 },
               { nome: "MENOR", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "MAIOR!", feedbackErro: "7 vem depois de 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "3 é MAIOR ou MENOR que 5?",
      opcoes: [{ nome: "MENOR", imagemUrl: NUM[3], correta: true, quantidade: 1 },
               { nome: "MAIOR", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "MENOR!", feedbackErro: "3 vem antes de 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "8 é maior que 5?",
      opcoes: [{ nome: "SIM (maior)", imagemUrl: NUM[8], correta: true, quantidade: 1 },
               { nome: "NÃO", imagemUrl: NUM[2], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "Sim!", feedbackErro: "8 é maior que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "2 é maior que 5?",
      opcoes: [{ nome: "NÃO (é menor)", imagemUrl: NUM[2], correta: true, quantidade: 1 },
               { nome: "SIM", imagemUrl: NUM[8], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "Não, 2 é menor.", feedbackErro: "2 é menor que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "5 é maior que 5?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[5], correta: true, quantidade: 1 },
               { nome: "MAIOR", imagemUrl: NUM[6], correta: false, quantidade: 1 },
               { nome: "MENOR", imagemUrl: NUM[4], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL! Nem maior, nem menor.", feedbackErro: "5 = 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "9 é maior que 5?",
      opcoes: [{ nome: "SIM", imagemUrl: NUM[9], correta: true, quantidade: 1 },
               { nome: "NÃO", imagemUrl: NUM[1], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "Sim!", feedbackErro: "9 é maior." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Time do 5",
      convite: "Diga números de 0 a 10. Peça: 'Time do MENOR (< 5) ou time do MAIOR (> 5)?'",
      dicaAdulto: "Ancoragem no 5 antecipa arredondamento e estimativa." },
    { tipo: "celebracao", medalha: "Dia 13 · Âncora do 5", mascoteUrl: mascote,
      falaFinal: "5 virou seu ponto de referência!" },
  ],
  baseCientifica: "Uso de âncoras na comparação (Van de Walle).",
};

const dia14: AulaEI = {
  slug: "pip-f6-s3-d4-ordenar-numeros",
  titulo: "Dia 14 · Ordenando 3 números",
  icone: "🪜",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "3 números. Qual é o MAIOR? Qual é o MENOR? Qual fica no MEIO?" },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 2, 5 e 8, qual é o MAIOR?",
      opcoes: [opN(8, true), opN(5, false), opN(2, false)],
      feedbackAcerto: "8!", feedbackErro: "8 é o maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 2, 5 e 8, qual é o MENOR?",
      opcoes: [opN(2, true), opN(5, false), opN(8, false)],
      feedbackAcerto: "2!", feedbackErro: "2 é o menor." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 1, 4 e 7, qual é o MAIOR?",
      opcoes: [opN(7, true), opN(4, false), opN(1, false)],
      feedbackAcerto: "7!", feedbackErro: "7 é o maior." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 1, 4 e 7, qual está no MEIO?",
      opcoes: [opN(4, true), opN(1, false), opN(7, false)],
      feedbackAcerto: "4 fica no meio.", feedbackErro: "4 está entre 1 e 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 3, 6, 9, qual é o MENOR?",
      opcoes: [opN(3, true), opN(6, false), opN(9, false)],
      feedbackAcerto: "3!", feedbackErro: "3 é o menor." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 3, 6, 9, qual fica no MEIO?",
      opcoes: [opN(6, true), opN(3, false), opN(9, false)],
      feedbackAcerto: "6!", feedbackErro: "6 está entre 3 e 9." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Escada de números",
      convite: "Escreva 3 números fora de ordem. Peça pra criança montar do MENOR pro MAIOR.",
      dicaAdulto: "Ordenação é aplicação estendida de comparação." },
    { tipo: "celebracao", medalha: "Dia 14 · Ordenei 3 números", mascoteUrl: mascote,
      falaFinal: "Você já ordena números!" },
  ],
  baseCientifica: "Seriação de 3 elementos (Piaget).",
};

const dia15: AulaEI = {
  slug: "pip-f6-s3-d5-medalha-numerais",
  titulo: "Dia 15 · Medalha dos numerais",
  icone: "🏅",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Última da semana! Prova com números." },
    { tipo: "compreensaoImagem", perguntaAudio: "MAIOR: 6 ou 4?",
      opcoes: [opN(6, true), opN(4, false), opN(5, false)],
      feedbackAcerto: "6!", feedbackErro: "6." },
    { tipo: "compreensaoImagem", perguntaAudio: "MENOR: 3 ou 8?",
      opcoes: [opN(3, true), opN(8, false), opN(5, false)],
      feedbackAcerto: "3!", feedbackErro: "3." },
    { tipo: "compreensaoImagem", perguntaAudio: "5 é maior que 7?",
      opcoes: [{ nome: "NÃO", imagemUrl: NUM[5], correta: true, quantidade: 1 },
               { nome: "SIM", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[6], correta: false, quantidade: 1 }],
      feedbackAcerto: "Não! 5 é menor.", feedbackErro: "5 é menor que 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 1, 5, 10 o MAIOR é?",
      opcoes: [opN(10, true), opN(5, false), opN(1, false)],
      feedbackAcerto: "10!", feedbackErro: "10." },
    { tipo: "compreensaoImagem", perguntaAudio: "Entre 2, 6, 9 o do MEIO é?",
      opcoes: [opN(6, true), opN(2, false), opN(9, false)],
      feedbackAcerto: "6!", feedbackErro: "6." },
    { tipo: "compreensaoImagem", perguntaAudio: "9 é maior que 5?",
      opcoes: [{ nome: "SIM", imagemUrl: NUM[9], correta: true, quantidade: 1 },
               { nome: "NÃO", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "Sim!", feedbackErro: "9 é maior." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Medalha",
      convite: "Aplauda: 'Você compara números como campeão!'",
      dicaAdulto: "Reconhecer o progresso alimenta mentalidade de crescimento." },
    { tipo: "celebracao", medalha: "MEDALHA · Numerais comparados", mascoteUrl: mascote,
      falaFinal: "Medalha da Semana 3 conquistada!" },
  ],
  baseCientifica: "Fechamento da Semana 3.",
};

// ============================================================
// SEMANA 4 · Mestre da Comparação + DIPLOMA
// ============================================================

const dia16: AulaEI = {
  slug: "pip-f6-s4-d1-vida-real",
  titulo: "Dia 16 · Comparação na vida real",
  icone: "🍎",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Comparar serve na vida! Quem tem mais uva? Quem esperou menos? Quem tem irmãos iguais?" },
    { tipo: "compararGrupos", instrucaoAudio: "Cesta de frutas.",
      perguntaAudio: "Qual cesta tem MAIS maçãs?", imagemUrl: maca, itemPlural: "maçãs",
      alvo: "mais",
      opcoes: [{ qtd: 3, correta: false }, { qtd: 7, correta: true }],
      feedbackAcerto: "7!", feedbackErro: "7 é mais." },
    { tipo: "compararGrupos", instrucaoAudio: "Festa de aniversário.",
      perguntaAudio: "Qual bandeja tem MENOS balões?", imagemUrl: balao, itemPlural: "balões",
      alvo: "menos",
      opcoes: [{ qtd: 4, correta: true }, { qtd: 9, correta: false }],
      feedbackAcerto: "4!", feedbackErro: "4 é menos." },
    { tipo: "compreensaoImagem", perguntaAudio: "Ana tem 5 doces, Bia tem 8. Quem tem MAIS?",
      opcoes: [{ nome: "Bia (8)", imagemUrl: NUM[8], correta: true, quantidade: 1 },
               { nome: "Ana (5)", imagemUrl: NUM[5], correta: false, quantidade: 1 },
               { nome: "Iguais", imagemUrl: NUM[6], correta: false, quantidade: 1 }],
      feedbackAcerto: "Bia!", feedbackErro: "8 é mais que 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Pai tem 6 uvas, Filho tem 6. Como está?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[6], correta: true, quantidade: 1 },
               { nome: "Pai tem mais", imagemUrl: NUM[7], correta: false, quantidade: 1 },
               { nome: "Filho tem mais", imagemUrl: NUM[8], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL — dividiram certinho.", feedbackErro: "6 = 6." },
    { tipo: "compreensaoImagem", perguntaAudio: "Time A: 4 gols. Time B: 2 gols. Quem tem MAIS?",
      opcoes: [{ nome: "Time A (4)", imagemUrl: NUM[4], correta: true, quantidade: 1 },
               { nome: "Time B (2)", imagemUrl: NUM[2], correta: false, quantidade: 1 },
               { nome: "Empate", imagemUrl: NUM[3], correta: false, quantidade: 1 }],
      feedbackAcerto: "Time A!", feedbackErro: "4 é mais." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Comparo comendo",
      convite: "Na hora do lanche, comparem: 'Você tem mais ou menos que eu?' Compartilhem se der.",
      dicaAdulto: "Matematização de rotinas (Clements & Sarama)." },
    { tipo: "celebracao", medalha: "Dia 16 · Comparo no dia a dia", mascoteUrl: mascote,
      falaFinal: "Comparação virou parte da sua vida!" },
  ],
  baseCientifica: "Transferência para contexto real (Clements & Sarama).",
};

const dia17: AulaEI = {
  slug: "pip-f6-s4-d2-quanto-mais",
  titulo: "Dia 17 · Quanto a mais?",
  icone: "➕",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Agora não é só 'quem tem mais', é 'QUANTO a mais'. Vai preparar você pra soma e subtração!" },
    { tipo: "compreensaoImagem", perguntaAudio: "5 tem quantos a MAIS que 3?",
      opcoes: [opN(2, true), opN(3, false), opN(5, false)],
      feedbackAcerto: "2! 3+2 = 5.", feedbackErro: "3, 4, 5 — são 2 passos." },
    { tipo: "compreensaoImagem", perguntaAudio: "6 tem quantos a MAIS que 4?",
      opcoes: [opN(2, true), opN(1, false), opN(4, false)],
      feedbackAcerto: "2!", feedbackErro: "4 + 2 = 6." },
    { tipo: "compreensaoImagem", perguntaAudio: "7 tem quantos a MAIS que 5?",
      opcoes: [opN(2, true), opN(3, false), opN(1, false)],
      feedbackAcerto: "2!", feedbackErro: "5 + 2 = 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "10 tem quantos a MAIS que 9?",
      opcoes: [opN(1, true), opN(2, false), opN(0, false)],
      feedbackAcerto: "1!", feedbackErro: "9 + 1 = 10." },
    { tipo: "compreensaoImagem", perguntaAudio: "8 tem quantos a MAIS que 5?",
      opcoes: [opN(3, true), opN(2, false), opN(5, false)],
      feedbackAcerto: "3! 5 + 3 = 8.", feedbackErro: "8 = 5 + 3." },
    { tipo: "compreensaoImagem", perguntaAudio: "10 tem quantos a MAIS que 5?",
      opcoes: [opN(5, true), opN(4, false), opN(6, false)],
      feedbackAcerto: "5! Duas fileiras cheias.", feedbackErro: "10 = 5 + 5." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Quantas a mais?",
      convite: "Coloque 3 e 5 objetos. Pergunte: 'Quantos a MAIS o outro grupo tem?'",
      dicaAdulto: "Prepara subtração como comparação (CGI Compare)." },
    { tipo: "celebracao", medalha: "Dia 17 · Diferença descoberta", mascoteUrl: mascote,
      falaFinal: "Você achou a DIFERENÇA!" },
  ],
  baseCientifica: "Comparação quantitativa antecipa subtração (Carpenter).",
};

const dia18: AulaEI = {
  slug: "pip-f6-s4-d3-estimativa",
  titulo: "Dia 18 · Palpite rápido",
  icone: "👁️",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Sem contar, só de OLHADA. Um palpite bem chegado já ajuda!" },
    { tipo: "compararGrupos", instrucaoAudio: "Rápido.",
      perguntaAudio: "Qual grupo é MUITO maior?", imagemUrl: joaninha, itemPlural: "joaninhas",
      alvo: "mais",
      opcoes: [{ qtd: 1, correta: false }, { qtd: 10, correta: true }],
      feedbackAcerto: "10! Muito maior que 1.", feedbackErro: "10 é enorme perto de 1." },
    { tipo: "compararGrupos", instrucaoAudio: "Rápido.",
      perguntaAudio: "Qual grupo é MUITO menor?", imagemUrl: flor, itemPlural: "flores",
      alvo: "menos",
      opcoes: [{ qtd: 2, correta: true }, { qtd: 9, correta: false }],
      feedbackAcerto: "2!", feedbackErro: "2 é bem menor que 9." },
    { tipo: "compararGrupos", instrucaoAudio: "Rápido.",
      perguntaAudio: "Qual grupo tem MAIS?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "mais",
      opcoes: [{ qtd: 3, correta: false }, { qtd: 10, correta: true }],
      feedbackAcerto: "10!", feedbackErro: "10." },
    { tipo: "compreensaoImagem", perguntaAudio: "Está mais perto de 0 ou de 10 o número 2?",
      opcoes: [opN(0, true), opN(10, false), opN(5, false)],
      feedbackAcerto: "Perto de 0!", feedbackErro: "2 está perto do 0." },
    { tipo: "compreensaoImagem", perguntaAudio: "Está mais perto de 0 ou de 10 o número 9?",
      opcoes: [opN(10, true), opN(0, false), opN(5, false)],
      feedbackAcerto: "Perto de 10!", feedbackErro: "9 está perto do 10." },
    { tipo: "compreensaoImagem", perguntaAudio: "5 está mais perto de 0, de 10 ou no meio?",
      opcoes: [opN(5, true), opN(0, false), opN(10, false)],
      feedbackAcerto: "5! É bem no meio.", feedbackErro: "5 fica no meio." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Palpite",
      convite: "Peça pra criança dar um palpite: 'Quantas colheres na gaveta?' Depois contem juntos.",
      dicaAdulto: "Estimativa (ANS) fortalece número aproximado (Halberda)." },
    { tipo: "celebracao", medalha: "Dia 18 · Palpite treinado", mascoteUrl: mascote,
      falaFinal: "Palpite bom = mente numérica boa!" },
  ],
  baseCientifica: "Approximate Number System (Halberda & Feigenson).",
};

const dia19: AulaEI = {
  slug: "pip-f6-s4-d4-simulado",
  titulo: "Dia 19 · Simulado da Fase 6",
  icone: "📝",
  bncc: ["EI03ET07"],
  duracaoMin: 10,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Simulado! Um pouquinho de cada coisa que aprendemos." },
    { tipo: "compararGrupos", instrucaoAudio: "1.",
      perguntaAudio: "MAIS bolas?", imagemUrl: bola, itemPlural: "bolas",
      alvo: "mais",
      opcoes: [{ qtd: 2, correta: false }, { qtd: 9, correta: true }],
      feedbackAcerto: "9!", feedbackErro: "9." },
    { tipo: "compararGrupos", instrucaoAudio: "2.",
      perguntaAudio: "MENOS estrelas?", imagemUrl: estrela, itemPlural: "estrelas",
      alvo: "menos",
      opcoes: [{ qtd: 4, correta: true }, { qtd: 8, correta: false }],
      feedbackAcerto: "4!", feedbackErro: "4." },
    { tipo: "compreensaoImagem", perguntaAudio: "3. IGUAL: 7 e 7?",
      opcoes: [{ nome: "SIM", imagemUrl: NUM[7], correta: true, quantidade: 1 },
               { nome: "NÃO", imagemUrl: NUM[3], correta: false, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[9], correta: false, quantidade: 1 }],
      feedbackAcerto: "SIM!", feedbackErro: "7 = 7." },
    { tipo: "compreensaoImagem", perguntaAudio: "4. MAIOR: 8 ou 5?",
      opcoes: [opN(8, true), opN(5, false), opN(7, false)],
      feedbackAcerto: "8!", feedbackErro: "8." },
    { tipo: "compreensaoImagem", perguntaAudio: "5. 6 tem quantos a MAIS que 4?",
      opcoes: [opN(2, true), opN(1, false), opN(3, false)],
      feedbackAcerto: "2!", feedbackErro: "6 - 4 = 2." },
    { tipo: "compreensaoImagem", perguntaAudio: "6. 9 é maior ou menor que 5?",
      opcoes: [{ nome: "MAIOR", imagemUrl: NUM[9], correta: true, quantidade: 1 },
               { nome: "MENOR", imagemUrl: NUM[1], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "MAIOR!", feedbackErro: "9 > 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "7. Entre 3, 7 e 10, MENOR?",
      opcoes: [opN(3, true), opN(7, false), opN(10, false)],
      feedbackAcerto: "3!", feedbackErro: "3." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Simulado em família",
      convite: "Repitam 3 perguntas de comparação juntos. Celebrem cada acerto.",
      dicaAdulto: "Simulado com adulto reduz ansiedade e reforça (Vygotsky · ZDP)." },
    { tipo: "celebracao", medalha: "Dia 19 · Simulado feito", mascoteUrl: mascote,
      falaFinal: "Pronto pro diploma!" },
  ],
  baseCientifica: "Prática interleaved (Rohrer & Taylor).",
};

const dia20: AulaEI = {
  slug: "pip-f6-s4-d5-diploma",
  titulo: "Dia 20 · DIPLOMA · Mestre da Comparação",
  icone: "🎓",
  bncc: ["EI03ET07"],
  duracaoMin: 12,
  momentos: [
    { tipo: "boasVindas", mascoteUrl: mascote,
      falaMascote: "Dia do DIPLOMA! Última prova e você vira MESTRE DA COMPARAÇÃO!" },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 1: MAIOR entre 4 e 9?",
      opcoes: [opN(9, true), opN(4, false), opN(6, false)],
      feedbackAcerto: "9!", feedbackErro: "9." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 2: MENOR entre 6 e 2?",
      opcoes: [opN(2, true), opN(6, false), opN(4, false)],
      feedbackAcerto: "2!", feedbackErro: "2." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 3: 5 e 5 são?",
      opcoes: [{ nome: "IGUAIS", imagemUrl: NUM[5], correta: true, quantidade: 1 },
               { nome: "DIFERENTES", imagemUrl: NUM[6], correta: false, quantidade: 1 },
               { nome: "MAIS", imagemUrl: NUM[7], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAIS!", feedbackErro: "5 = 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 4: 8 é maior que 5?",
      opcoes: [{ nome: "SIM", imagemUrl: NUM[8], correta: true, quantidade: 1 },
               { nome: "NÃO", imagemUrl: NUM[2], correta: false, quantidade: 1 },
               { nome: "IGUAL", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "SIM!", feedbackErro: "8 > 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 5: 10 tem quantos a MAIS que 5?",
      opcoes: [opN(5, true), opN(4, false), opN(6, false)],
      feedbackAcerto: "5!", feedbackErro: "10 - 5 = 5." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova 6: Entre 2, 5, 8, o MAIOR?",
      opcoes: [opN(8, true), opN(5, false), opN(2, false)],
      feedbackAcerto: "8!", feedbackErro: "8." },
    { tipo: "compreensaoImagem", perguntaAudio: "Prova final: 7 comparado com 7?",
      opcoes: [{ nome: "IGUAL", imagemUrl: NUM[7], correta: true, quantidade: 1 },
               { nome: "MAIOR", imagemUrl: NUM[9], correta: false, quantidade: 1 },
               { nome: "MENOR", imagemUrl: NUM[5], correta: false, quantidade: 1 }],
      feedbackAcerto: "IGUAL! MESTRE DA COMPARAÇÃO!", feedbackErro: "7 = 7." },
    { tipo: "missaoFamilia", titulo: "Missão Família · Cerimônia do diploma",
      convite: "Mostre o diploma! Peça pra criança comparar 3 coisas em casa: mais, menos e igual.",
      dicaAdulto: "Fase 7 (soma e subtração visual) libera na sequência." },
    { tipo: "celebracao", medalha: "DIPLOMA · Mestre da Comparação", mascoteUrl: mascote,
      falaFinal: "DIPLOMA CONQUISTADO! Você é MESTRE DA COMPARAÇÃO!" },
  ],
  baseCientifica: "Cerimônia de fechamento Fase 6.",
};

// ============================================================
// CURSO
// ============================================================

export const cursoContarComPipFase6: CursoEI = {
  slug: "contar-com-pip-f6",
  serie: "pre2",
  serieLabel: "Contar com Pip · Fase 6",
  titulo: "Fase 6 · Comparação de Magnitude",
  descricao:
    "Mais, menos, igual. De grupos bem diferentes (ANS) até comparar numerais e achar a diferença — pronto para soma e subtração.",
  corPrimaria: "#14b8a6",
  corSecundaria: "#134e4a",
  mascoteUrl: mascote,
  unidades: [
    {
      slug: "pip-f6-s1",
      numero: 1,
      titulo: "Semana 1 · MAIS e MENOS",
      subtitulo: "Percepção direta em grupos diferentes",
      aulas: [dia01, dia02, dia03, dia04, dia05],
    },
    {
      slug: "pip-f6-s2",
      numero: 2,
      titulo: "Semana 2 · IGUAL e emparelhar",
      subtitulo: "Correspondência 1-a-1 e equivalência",
      aulas: [dia06, dia07, dia08, dia09, dia10],
    },
    {
      slug: "pip-f6-s3",
      numero: 3,
      titulo: "Semana 3 · Comparando numerais",
      subtitulo: "0–10 sem contar grupos, ancorando no 5",
      aulas: [dia11, dia12, dia13, dia14, dia15],
    },
    {
      slug: "pip-f6-s4",
      numero: 4,
      titulo: "Semana 4 · Mestre da Comparação (DIPLOMA)",
      subtitulo: "Vida real, diferença exata, estimativa e diploma",
      aulas: [dia16, dia17, dia18, dia19, dia20],
    },
  ],
};

export function getAulaContarComPipFase6(slug: string): AulaEI | undefined {
  for (const u of cursoContarComPipFase6.unidades) {
    const a = u.aulas.find((x) => x.slug === slug);
    if (a) return a;
  }
  return undefined;
}
