import type { AulaGeoV1 } from "../../types";
import clima from "@/assets/geografia-6ano/clima-atmosfera.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-clima-tempo",
  titulo: "Clima e Tempo",
  iconeTrilha: "🌦️",
  bncc: ["EF06GE12"],
  duracaoMin: 25,
  estilo: "teen",

  cena01_motivacao: {
    tipo: "mesaCartografo",
    estilo: "teen",
    instrucao: "Tempo é hoje. Clima é a média de décadas.",
    mapaUrl: clima,
    imagemDestaqueUrl: clima,
    aurora:
      "Explorador, atenção: TEMPO e CLIMA não são a mesma coisa. TEMPO é como está agora — chuva, sol, calor. CLIMA é o padrão de anos e anos. Manaus tem CLIMA tropical úmido: chove sempre. Mesmo se hoje faltar chuva lá, o clima continua o mesmo.",
    falaFinal: "Tempo muda todo dia. Clima leva décadas pra mudar. Guarde essa diferença.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Por que o Nordeste do Brasil tem SECA e o Norte tem CHUVA quase o ano todo?",
    pergunta: "O que explica essa diferença?",
    opcoes: [
      { id: "massas", titulo: "MASSAS DE AR diferentes", subtitulo: "úmidas no Norte, secas no NE", emoji: "💨", cor: "from-sky-400 to-blue-600" },
      { id: "distancia", titulo: "Estão em CONTINENTES diferentes", subtitulo: "só por isso", emoji: "🌍", cor: "from-slate-400 to-gray-600" },
    ],
    respostaCerta: "massas",
    feedbackAcerto:
      "Exato! Massa de ar úmida do Atlântico entra pelo Norte e chove muito. No NE, o relevo bloqueia a umidade — sertão seco.",
    feedbackErro: "Norte e Nordeste estão no MESMO país. A diferença são as MASSAS DE AR e o RELEVO.",
    falaFinal: "Massa de ar + relevo + latitude = clima. 3 ingredientes.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "4 conceitos que todo meteorologista usa.",
    instrucao: "",
    cadernos: [
      { id: "tempo", capa: "1. Tempo", emoji: "🌤️", cor: "from-sky-500 to-blue-700",
        conteudo: "TEMPO é o estado da atmosfera AGORA, num lugar específico. Muda de hora em hora.",
        exemplo: "Ex.: 'Hoje faz sol em SP com 22°C.'" },
      { id: "clima", capa: "2. Clima", emoji: "🌍", cor: "from-emerald-500 to-teal-700",
        conteudo: "CLIMA é a MÉDIA do tempo ao longo de MUITOS anos (30+). Diz o padrão de uma região.",
        exemplo: "Ex.: 'SP tem clima tropical de altitude.'" },
      { id: "massa", capa: "3. Massa de ar", emoji: "💨", cor: "from-purple-500 to-fuchsia-700",
        conteudo: "MASSA DE AR é um bloco enorme de atmosfera com temperatura e umidade próprias. Se move pelo planeta.",
        exemplo: "Ex.: mEc (equatorial continental) traz chuva pra Amazônia." },
      { id: "fatores", capa: "4. Fatores do clima", emoji: "📊", cor: "from-amber-500 to-orange-700",
        conteudo: "FATORES são o que INFLUENCIA o clima: LATITUDE, altitude, relevo, distância do mar, correntes marítimas, vegetação.",
        exemplo: "Ex.: quanto mais perto do Equador, mais quente." },
    ],
    falaFinal: "Tempo ≠ Clima. Massas movem, fatores definem. 4 chaves.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "Aponte cada zona climática do planeta.",
    instrucao: "Toque em cada balão",
    mapaUrl: clima,
    pontos: [
      { id: "equatorial", x: 50, y: 55, emoji: "🌴", cor: "from-emerald-500 to-green-700",
        titulo: "ZONA EQUATORIAL",
        texto: "Perto do Equador. Sol a pino o ano todo. Muito quente e muito úmido. Onde vive a Amazônia." },
      { id: "tropical", x: 65, y: 65, emoji: "☀️", cor: "from-amber-500 to-orange-700",
        titulo: "ZONA TROPICAL",
        texto: "Entre trópicos. Duas estações: úmida e seca. Grande parte do Brasil está aqui." },
      { id: "temperada", x: 35, y: 25, emoji: "🍂", cor: "from-sky-500 to-blue-700",
        titulo: "ZONA TEMPERADA",
        texto: "Entre trópicos e polares. Quatro estações bem marcadas. Europa, EUA, Sul do Brasil." },
      { id: "polar", x: 20, y: 15, emoji: "❄️", cor: "from-slate-500 to-gray-700",
        titulo: "ZONA POLAR",
        texto: "Perto dos polos. Frio extremo o ano todo. Sol quase não sobe no inverno. Antártica, Ártico." },
    ],
    falaFinal: "4 zonas climáticas do planeta. Latitude manda no clima.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de meteorologista.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "'Hoje faz 28°C com sol em Recife' é:",
        cards: [
          { id: "t", emoji: "🌤️", titulo: "Tempo", cor: "from-sky-500 to-blue-700" },
          { id: "c", emoji: "🌍", titulo: "Clima", cor: "from-emerald-500 to-teal-700" },
          { id: "m", emoji: "💨", titulo: "Massa de ar", cor: "from-purple-500 to-fuchsia-700" },
        ], correta: "t",
        feedbackAcerto: "Isso! Estado da atmosfera AGORA = TEMPO.", feedbackErro: "Hoje = TEMPO. Ao longo de anos = clima." },
      { id: "q2", pergunta: "Qual desses é FATOR do clima?",
        cards: [
          { id: "l", emoji: "🌐", titulo: "Latitude", cor: "from-emerald-500 to-teal-700" },
          { id: "e", emoji: "🎂", titulo: "Idade das pessoas", cor: "from-amber-500 to-orange-700" },
          { id: "d", emoji: "💰", titulo: "Dinheiro", cor: "from-red-500 to-rose-700" },
        ], correta: "l",
        feedbackAcerto: "Isso! LATITUDE é fator natural do clima.", feedbackErro: "Fatores são naturais: LATITUDE, altitude, relevo." },
      { id: "q3", pergunta: "Zona climática do EQUADOR é:",
        cards: [
          { id: "eq", emoji: "🌴", titulo: "Equatorial (quente + úmida)", cor: "from-emerald-500 to-teal-700" },
          { id: "po", emoji: "❄️", titulo: "Polar", cor: "from-sky-500 to-indigo-700" },
          { id: "de", emoji: "🌵", titulo: "Desértica", cor: "from-amber-500 to-orange-700" },
        ], correta: "eq",
        feedbackAcerto: "Isso! Equador = quente e úmido.", feedbackErro: "Polar é frio. Deserto é seco. Equador = quente e úmido." },
    ],
    falaFinal: "Radar afiado. Bora ver o Brasil.",
  },

  cena06_personagensLugar: {
    tipo: "mapaBrasilInterativo",
    aurora:
      "O SEMIÁRIDO (clima seco típico) domina 9 estados do NORDESTE. Marque quais.",
    instrucao: "Acenda os estados do Nordeste com sertão semiárido",
    missao: {
      tipo: "selecionar",
      siglas: ["BA", "PE", "PB", "RN", "CE", "PI", "SE", "AL", "MA"],
      pergunta: "Onde fica o semiárido brasileiro?",
    },
    falaFinal:
      "9 estados do Nordeste. Chuva escassa, sertão duro — mas com biodiversidade única (caatinga).",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Organize o CICLO DA ÁGUA na atmosfera.",
    instrucao: "Toque na ordem",
    pergunta: "Como a chuva se forma?",
    paradas: [
      { id: "sol", emoji: "☀️", rotulo: "1. Sol esquenta a água",
        descricao: "Rios, lagos, oceanos recebem calor solar." },
      { id: "evap", emoji: "💨", rotulo: "2. Evaporação",
        descricao: "Água vira vapor invisível e sobe pra atmosfera." },
      { id: "cond", emoji: "☁️", rotulo: "3. Condensação",
        descricao: "Lá em cima esfria e vira gotículas — se formam nuvens." },
      { id: "prec", emoji: "🌧️", rotulo: "4. Precipitação",
        descricao: "Gotículas se juntam, ficam pesadas e caem como chuva." },
      { id: "esc", emoji: "🌊", rotulo: "5. Escoamento e volta",
        descricao: "Água escorre pra rios, retorna ao mar, ciclo recomeça." },
    ],
    ordemCerta: ["sol", "evap", "cond", "prec", "esc"],
    feedbackAcerto: "Ciclo perfeito! Sol move o clima do planeta inteiro.",
    feedbackErro: "Comece com o sol esquentando, depois evapora, condensa, chove, volta.",
    falaFinal: "Sol → vapor → nuvem → chuva → mar. Ciclo eterno.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua vez.",
    tituloLivro: "📘 Manual do Explorador Planetário",
    subtitulo: "Capítulo 5 — Clima e Tempo",
    paragrafos: [
      { id: "p1", texto: "TEMPO é o estado da atmosfera num MOMENTO. CLIMA é a média do tempo em muitos ANOS.",
        chaves: ["tempo", "clima", "momento", "anos"] },
      { id: "p2", texto: "As MASSAS DE AR são blocos de atmosfera que carregam umidade e temperatura para as regiões.",
        chaves: ["massas", "umidade", "temperatura"] },
      { id: "p3", texto: "A LATITUDE é o principal fator do clima: perto do Equador é QUENTE, perto dos polos é FRIO.",
        chaves: ["latitude", "quente", "frio", "equador"] },
      { id: "p4", texto: "O CICLO DA ÁGUA (evaporação → condensação → precipitação) mantém a vida no planeta.",
        chaves: ["ciclo", "evaporação", "condensação", "precipitação"] },
    ],
    falaFinal: "Leu tudo?",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Minijogo METEOROLOGISTA EXPRESS!",
    instrucao: "⏱️ Que zona climática?",
    duracaoSegundos: 12,
    pecas: [
      { id: "eq", emoji: "🌴", rotulo: "Equatorial" },
      { id: "tr", emoji: "☀️", rotulo: "Tropical" },
      { id: "te", emoji: "🍂", rotulo: "Temperada" },
      { id: "po", emoji: "❄️", rotulo: "Polar" },
      { id: "de", emoji: "🌵", rotulo: "Desértica" },
      { id: "se", emoji: "🏜️", rotulo: "Semiárida" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Amazônia", emoji: "🌳", cor: "from-emerald-400 to-teal-600" },
        municipioB: { nome: "Chove todo dia", emoji: "🌧️", cor: "from-sky-400 to-blue-600" },
        contexto: "Quente e chuvoso o ano todo, perto do Equador. Que clima?",
        pecaCertaId: "eq",
        feedbackAcerto: "Isso! Amazônia = EQUATORIAL.", feedbackErro: "Quente + úmido + Equador = EQUATORIAL." },
      { id: "r2", municipioA: { nome: "Antártica", emoji: "🐧", cor: "from-sky-400 to-blue-600" },
        municipioB: { nome: "-40°C", emoji: "❄️", cor: "from-slate-400 to-gray-600" },
        contexto: "Frio extremo o ano inteiro. Que clima?",
        pecaCertaId: "po",
        feedbackAcerto: "Isso! Antártica = POLAR.", feedbackErro: "Frio extremo = POLAR." },
      { id: "r3", municipioA: { nome: "Saara", emoji: "🌵", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Sem chuva, muita areia", emoji: "🏜️", cor: "from-yellow-400 to-red-600" },
        contexto: "Muito seco, quase sem chuva, calor extremo. Que clima?",
        pecaCertaId: "de",
        feedbackAcerto: "Isso! Saara = DESÉRTICO.", feedbackErro: "Sem chuva + calor = DESÉRTICO." },
      { id: "r4", municipioA: { nome: "Sertão nordestino", emoji: "🌾", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Caatinga", emoji: "🌵", cor: "from-yellow-400 to-orange-600" },
        contexto: "Pouca chuva, mas com vegetação — o sertão. Que clima?",
        pecaCertaId: "se",
        feedbackAcerto: "Isso! Sertão = SEMIÁRIDO.", feedbackErro: "Nordeste seco mas com vida = SEMIÁRIDO." },
      { id: "r5", municipioA: { nome: "Europa Central", emoji: "🍂", cor: "from-sky-400 to-blue-600" },
        municipioB: { nome: "4 estações claras", emoji: "🌷", cor: "from-pink-400 to-rose-600" },
        contexto: "Tem primavera, verão, outono e inverno bem marcados. Que clima?",
        pecaCertaId: "te",
        feedbackAcerto: "Isso! 4 estações = TEMPERADO.", feedbackErro: "4 estações claras = TEMPERADO." },
      { id: "r6", municipioA: { nome: "Rio de Janeiro", emoji: "🌴", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Verão úmido, inverno seco", emoji: "☀️", cor: "from-red-400 to-rose-600" },
        contexto: "Quente o ano todo, com estação úmida e estação seca. Que clima?",
        pecaCertaId: "tr",
        feedbackAcerto: "Isso! RJ = TROPICAL.", feedbackErro: "2 estações + calor = TROPICAL." },
    ],
    falaFinal: "6 climas, 6 acertos!",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "Pizza TEMPO vs CLIMA.",
    instrucao: "Toque em cada fatia",
    fatias: [
      { id: "tempo", rotulo: "TEMPO (curto prazo)", emoji: "🌤️", percentual: 50, cor: "#0ea5e9",
        descricao: "Estado da atmosfera AGORA ou nos próximos dias. Muda o tempo todo.",
        exemplos: ["🌦️ Previsão do tempo", "☔ Chuva de hoje", "🌡️ Temperatura atual"] },
      { id: "clima", rotulo: "CLIMA (longo prazo)", emoji: "🌍", percentual: 50, cor: "#059669",
        descricao: "Padrão climático de uma região em 30+ anos. Muito estável.",
        exemplos: ["🌴 Tropical úmido", "❄️ Polar", "🌵 Semiárido"] },
    ],
    falaFinal: "Tempo é fofoca do dia. Clima é biografia da região.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 finais.",
    instrucao: "Responda as 3",
    perguntas: [
      { id: "av1", pergunta: "A diferença entre TEMPO e CLIMA é:",
        opcoes: [
          { id: "a", texto: "Tempo é geral, clima é local", correta: false },
          { id: "b", texto: "Tempo é agora, clima é a média de anos", correta: true },
          { id: "c", texto: "São a mesma coisa", correta: false },
        ],
        feedbackAcerto: "Isso! TEMPO = agora. CLIMA = média longa.", feedbackErro: "TEMPO = agora. CLIMA = anos de padrão." },
      { id: "av2", pergunta: "O principal fator do clima é:",
        opcoes: [
          { id: "a", texto: "A latitude", correta: true },
          { id: "b", texto: "A cor do céu", correta: false },
          { id: "c", texto: "A idade da terra", correta: false },
        ],
        feedbackAcerto: "Isso! LATITUDE define o quanto o sol bate direto.", feedbackErro: "LATITUDE é o principal fator." },
      { id: "av3", pergunta: "No ciclo da água, a EVAPORAÇÃO acontece quando:",
        opcoes: [
          { id: "a", texto: "A água vira gelo", correta: false },
          { id: "b", texto: "A água vira vapor e sobe", correta: true },
          { id: "c", texto: "A chuva cai", correta: false },
        ],
        feedbackAcerto: "Isso! EVAPORAÇÃO = água líquida → vapor.", feedbackErro: "Evaporação = água vira VAPOR e sobe." },
    ],
    selo: { nome: "Meteorologista Iniciante", subtitulo: "Insígnia do Explorador Planetário", emoji: "🌦️", cor: "from-sky-500 to-blue-700" },
    falaFinal: "Insígnia conquistada!",
  },

  recompensa: { xp: 400, moedas: 300, medalha: "Meteorologista Iniciante" },
};
