BEGIN;
-- Biblioteca Inclusiva · Ciências do 1º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF01CI01','src/escola-brilha/curso-v4/ciencias-1ano/unidade-1/aula-01-objetos.ts','Objetos e materiais','Comparar características de materiais presentes em objetos do cotidiano e discutir descarte responsável.','Classifique objetos seguros por material, rigidez, transparência e flexibilidade.','Escolha um objeto, identifique o material e explique por que ele é adequado ao uso.','A resposta deve relacionar propriedade, material e uso; aceite mais de uma solução bem justificada.'),
('EF01CI02','src/escola-brilha/curso-v4/ciencias-1ano/unidade-2/aula-01-corpo.ts','Partes do corpo','Localizar, nomear e representar partes do corpo, relacionando-as a funções e respeitando diferentes corpos.','Monte uma figura corporal com cartões e associe partes a ações possíveis, sem pressupor que todos se movem do mesmo modo.','Indique em desenho, modelo ou no próprio corpo três partes e uma função de cada.','Exemplos: olhos ajudam a ver; mãos podem tocar; pernas podem apoiar movimentos. Respostas devem respeitar diferenças corporais.'),
('EF01CI03','src/escola-brilha/curso-v4/ciencias-1ano/unidade-3/aula-01-higiene.ts','Hábitos de higiene','Explicar por que hábitos de higiene do corpo ajudam a cuidar da saúde.','Ordene cartões de uma rotina de lavar as mãos e explique a função de cada etapa.','Escolha uma situação cotidiana e mostre o cuidado de higiene adequado.','Relacionar o hábito à redução de sujeira e microrganismos, sem prometer prevenção absoluta de doenças.'),
('EF01CI04','src/escola-brilha/curso-v4/ciencias-1ano/unidade-7/aula-01-diversidade.ts','Semelhanças, diferenças e respeito','Comparar características físicas entre pessoas, reconhecendo diversidade e respeito sem hierarquizar corpos.','Observe personagens diversos e registre semelhanças e diferenças com linguagem neutra e respeitosa.','Faça autorretrato ou descrição por cartões e diga uma característica compartilhada com outra pessoa.','Não há aparência certa; avaliar observação, respeito e reconhecimento da diversidade.'),
('EF01CI05','src/escola-brilha/curso-v4/ciencias-1ano/unidade-4/aula-01-dia-noite.ts','Escalas de tempo','Identificar e nomear períodos do dia e sequências de dias, semanas, meses e anos.','Organize cenas de manhã, tarde e noite usando pistas de luz e atividades, discutindo exceções de rotina.','Monte uma sequência de três acontecimentos e indique quando ocorrem.','A ordem deve ser coerente com a rotina apresentada; diferentes rotinas podem ter respostas distintas.'),
('EF01CI06','src/escola-brilha/curso-v4/ciencias-1ano/unidade-5/aula-01-escalas-tempo.ts','Ritmos do cotidiano','Relacionar sucessão de dias e noites a ritmos de atividades de pessoas e outros seres vivos.','Compare uma rotina humana e a de um animal diurno ou noturno em linha do tempo.','Marque uma atividade do dia e outra da noite e explique a pista temporal.','Resposta deve usar uma pista observável e reconhecer que rotinas variam.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Prepare com segurança','content',jsonb_build_array('Use somente objetos limpos, sem pontas, peças pequenas soltas, calor, vidro quebrável ou substâncias desconhecidas.','Apresente o objetivo com imagem real e uma frase curta; deixe visível a sequência observar, comparar, registrar e explicar.')),
  jsonb_build_object('heading','Ensine investigando','content',jsonb_build_array('Pergunte o que a criança percebe antes de explicar; aceite hipótese e depois teste com evidência observável.','Modele uma comparação por vez e ensine a diferença entre eu observei e eu acho.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Use blocos curtos definidos pela resposta da criança, não por diagnóstico.','Dê uma instrução por vez, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, objetos, cartões, desenho, foto, digitação ou escrita.')),
  jsonb_build_object('heading','Critério','content','Observa, compara e explica quatro de cinco situações usando ao menos uma evidência.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Observar de verdade','instruction','Olhe, toque somente quando for seguro e descreva sem adivinhar.','activity','Registre duas características do exemplo.','support','Objeto real ou foto ampliada, escolha visual e leitura em voz alta.'),
  jsonb_build_object('title','2. Investigar com apoio','instruction','Compare dois casos e mostre a evidência.','activity',guided,'support','Quadro igual-diferente, cartões e modelagem do professor.'),
  jsonb_build_object('title','3. Explicar com autonomia','instruction','Aplique a descoberta em uma nova situação.','activity',independent,'support','Resposta oral, apontada, montada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Duas características observáveis.'),jsonb_build_object('page',2,'answer','Comparação coerente e evidência indicada.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre a hipótese, evidência usada, apoio eficaz e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','objects','cards','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-1ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ciências do 2º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF02CI01','src/escola-brilha/curso-v4/ciencias-2ano/unidade-1/aula-01-metodo-cientista.ts','Materiais dos objetos','Identificar materiais usados em objetos cotidianos, comparar seus usos no presente e no passado.','Separe objetos ou fotos por material e compare um objeto atual com outro usado antigamente.','Escolha um objeto, nomeie o material e explique uma mudança em seu uso ou fabricação.','Identificar material e apresentar comparação temporal coerente com a evidência.'),
('EF02CI02','src/escola-brilha/curso-v4/ciencias-2ano/unidade-2/aula-01-materiais.ts','Propriedades e escolha de materiais','Relacionar propriedades como flexibilidade, transparência e resistência à finalidade dos objetos.','Teste apenas objetos seguros e registre qual dobra, deixa passar luz ou resiste à pressão leve.','Escolha o melhor material para um objeto e justifique pela propriedade necessária.','Aceitar soluções diferentes quando propriedade e uso estiverem bem relacionados.'),
('EF02CI03','src/escola-brilha/curso-v4/ciencias-2ano/unidade-3/aula-01-seguranca.ts','Prevenção de acidentes domésticos','Reconhecer situações de risco e propor atitudes seguras, buscando ajuda de um adulto.','Classifique cenas em segura, precisa de cuidado e chamar um adulto, sem encenar o risco.','Escolha uma cena e explique como torná-la mais segura.','A ação deve afastar-se do risco, avisar um adulto e não experimentar a situação perigosa.'),
('EF02CI04','src/escola-brilha/curso-v4/ciencias-2ano/unidade-4/aula-01-seres-vivos.ts','Características de plantas e animais','Descrever características de plantas e animais do cotidiano e relacioná-las ao ambiente em que vivem.','Compare dois seres vivos por cobertura, partes, movimento, alimentação ou ambiente.','Registre um ser vivo, duas características e uma relação com seu ambiente.','Características observáveis e relação coerente; evitar definir seres vivos apenas pelo movimento.'),
('EF02CI05','src/escola-brilha/curso-v4/ciencias-2ano/unidade-5/aula-01-agua-luz.ts','Água e luz para as plantas','Investigar a importância da água e da luz para a manutenção da vida das plantas.','Compare plantas semelhantes sob condições planejadas pelo adulto, alterando somente água ou luz e registrando ao longo dos dias.','Observe registros e conclua qual condição mudou e qual efeito foi percebido.','Conclusão limitada aos dados observados; não arrancar ou ingerir plantas e não usar espécies desconhecidas.'),
('EF02CI06','src/escola-brilha/curso-v4/ciencias-2ano/unidade-6/aula-01-partes-planta.ts','Partes da planta e suas funções','Identificar raiz, caule, folhas, flores e frutos e relacionar cada parte a funções básicas.','Monte um diagrama de planta e ligue partes a absorção, sustentação, trocas com o ambiente e reprodução.','Indique três partes em foto ou desenho e explique uma função.','Raiz absorve água e fixa; caule sustenta e transporta; folhas participam da produção de alimento e trocas gasosas.'),
('EF02CI07','src/escola-brilha/curso-v4/ciencias-2ano/unidade-7/aula-01-sol-sombra.ts','Posição do Sol e sombras','Observar posições aparentes do Sol e relacioná-las à direção e ao tamanho das sombras.','Compare fotos ou medições feitas por adulto em horários distintos, sem olhar diretamente para o Sol.','Ordene três registros e descreva como a sombra mudou.','A sombra muda de direção e tamanho conforme a posição aparente do Sol; usar dados do registro.'),
('EF02CI08','src/escola-brilha/curso-v4/ciencias-2ano/unidade-7/aula-01-sol-sombra.ts','Luz, calor e materiais','Comparar o efeito da radiação solar em superfícies de cores e materiais diferentes com procedimento seguro.','Compare temperaturas registradas por adulto em superfícies claras e escuras, sem tocar superfícies muito quentes.','Leia o registro e indique qual superfície aqueceu mais, sem generalizar além do teste.','Conclusão baseada nos dados; diferenças dependem também do material, tempo e condições do ambiente.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Segurança primeiro','content',jsonb_build_array('O professor seleciona materiais e demonstra procedimentos; a criança não manipula calor, eletricidade, vidro, substâncias desconhecidas ou situações de risco.','Não olhar diretamente para o Sol nem provar plantas ou materiais.')),
  jsonb_build_object('heading','Pensar como cientista','content',jsonb_build_array('Registre pergunta, hipótese, observação e conclusão em campos separados.','Mude uma condição por vez quando houver comparação e ensine que a conclusão vale para o que foi observado.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Use instruções curtas, modelo visual e pausa planejada conforme a resposta observada.','Aceite fala, apontamento, objeto, cartões, desenho, foto, digitação ou escrita.','Retire apoios gradualmente sem diminuir o objetivo científico.')),
  jsonb_build_object('heading','Critério','content','Observa, compara, registra e explica quatro de cinco situações com evidência pertinente.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Perguntar e prever','instruction','Observe o caso e registre uma hipótese sem tratá-la como resposta final.','activity','Escolha uma previsão e diga qual pista levou a ela.','support','Foto ampliada, escolha visual e leitura em voz alta.'),
  jsonb_build_object('title','2. Investigar com apoio','instruction','Compare mantendo visível o que mudou e o que permaneceu igual.','activity',guided,'support','Tabela visual, cartões e modelagem do professor.'),
  jsonb_build_object('title','3. Concluir com evidência','instruction','Responda à pergunta usando somente o que foi observado.','activity',independent,'support','Resposta oral, apontada, montada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese ligada a uma pista observável.'),jsonb_build_object('page',2,'answer','Comparação registrada de modo coerente.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre hipótese, evidência, nível de ajuda e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','objects','cards','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'adult_supervision',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-2ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ciências do 3º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF03CI01','src/escola-brilha/curso-v4/ciencias-3ano/unidade-6/aula-01-som-vibracao.ts','Som e vibração','Produzir sons com objetos seguros e explicar que diferentes vibrações geram sons.','Observe grãos sobre uma membrana vibrando com som moderado e compare vibração visível e som ouvido.','Escolha um objeto sonoro seguro, indique o que vibra e compare som forte/fraco sem elevar o volume.','O som resulta de vibração; intensidade e altura não são a mesma característica.'),
('EF03CI02','src/escola-brilha/curso-v4/ciencias-3ano/unidade-5/aula-01-luz-sombras.ts','Luz e interação com materiais','Investigar passagem, reflexão e bloqueio da luz em materiais transparentes, translúcidos e opacos.','Com lanterna de baixa intensidade, compare materiais sem direcionar luz aos olhos.','Classifique um material pela passagem de luz e mostre a evidência.','Transparente deixa passar mais luz; translúcido parcialmente; opaco bloqueia a passagem.'),
('EF03CI03','src/escola-brilha/curso-v4/ciencias-3ano/unidade-7/aula-01-saude-sentidos.ts','Saúde auditiva e visual','Reconhecer condições prejudiciais à audição e à visão e propor cuidados cotidianos.','Classifique cenas de volume, distância de telas, iluminação e proteção como cuidado ou risco.','Escolha uma situação e proponha uma mudança segura, procurando adulto ou profissional quando necessário.','Reduzir volume e exposição, usar iluminação adequada e não olhar fontes intensas; sintomas exigem avaliação de adulto/profissional.'),
('EF03CI04','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Características e modos de vida dos animais','Comparar alimentação, deslocamento, reprodução, cobertura corporal e ambiente de animais.','Preencha tabela de dois animais usando somente informações de fotos e textos curtos.','Descreva um animal por três características e relacione uma ao ambiente.','Descrição coerente com a fonte; não usar apenas tamanho ou aparência para classificar.'),
('EF03CI05','src/escola-brilha/curso-v4/ciencias-3ano/unidade-3/aula-01-ciclo-vida.ts','Ciclo de vida dos animais','Descrever mudanças desde o nascimento até a fase adulta e reconhecer reprodução e desenvolvimento.','Ordene etapas documentadas de um ciclo de vida sem afirmar que todos os animais seguem o mesmo padrão.','Compare o ciclo de dois animais e indique uma semelhança e uma diferença.','A sequência e comparação devem corresponder às espécies estudadas.'),
('EF03CI06','src/escola-brilha/curso-v4/ciencias-3ano/unidade-2/aula-01-vertebrados-invertebrados.ts','Agrupamento de animais','Comparar animais e formar grupos por características externas observáveis.','Agrupe cartões por cobertura, número de patas, presença de asas ou modo de locomoção e explicite o critério.','Crie um agrupamento diferente e explique por que cada animal pertence a ele.','Mais de um agrupamento é válido quando o critério é observável e usado de forma consistente.'),
('EF03CI07','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Características da Terra','Reconhecer forma aproximadamente esférica, presença de água e continentes em representações e observações indiretas.','Compare globo, mapa e imagem da Terra, discutindo o que cada representação mostra e distorce.','Indique duas evidências ou representações usadas para estudar a Terra.','A Terra é aproximadamente esférica; mapa plano e globo são modelos com vantagens e limites.'),
('EF03CI08','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Observação do céu','Registrar posições aparentes do Sol, Lua, estrelas e outros astros em horários distintos com segurança.','Analise registros preparados pelo professor e organize data, horário, direção e desenho observado.','Compare dois registros e descreva uma mudança sem concluir além dos dados.','Mudanças aparentes dependem do horário e da posição do observador; nunca olhar diretamente para o Sol.'),
('EF03CI09','src/escola-brilha/curso-v4/ciencias-3ano/unidade-1/aula-01-composicao-solo.ts','Características do solo','Comparar amostras seguras de solo por cor, textura, tamanho dos grãos, cheiro e permeabilidade.','Observe amostras previamente verificadas, usando colher e recipiente, sem tocar rosto ou levar material à boca.','Registre duas diferenças e proponha uma explicação que possa ser testada.','Descrever dados observáveis; hipótese não deve ser apresentada como certeza.'),
('EF03CI10','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Usos do solo','Identificar usos do solo na agricultura, construção e conservação e discutir impactos e cuidados.','Compare imagens de solo coberto por vegetação, cultivado e pavimentado, relacionando uso e efeito.','Escolha um uso e proponha um cuidado para reduzir erosão, contaminação ou desperdício.','A proposta deve se relacionar ao problema observado e reconhecer que diferentes usos exigem cuidados distintos.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Segurança e materiais','content',jsonb_build_array('O professor seleciona materiais limpos e seguros; não usar alto volume, luz nos olhos, calor, substâncias desconhecidas ou observação direta do Sol.','Antecipe regras em sequência visual e interrompa a atividade se houver desconforto sensorial.')),
  jsonb_build_object('heading','Investigue sem entregar a resposta','content',jsonb_build_array('Separe pergunta, hipótese, procedimento, observação e conclusão.','Compare uma variável por vez e ensine a citar dados; hipótese diferente do resultado não é erro.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Alterne demonstração, investigação guiada, pausa e retomada conforme resposta observada.','Dê uma instrução por vez e ofereça participação por fala, apontamento, tabela, desenho, foto, digitação ou escrita.','Retire apoios gradualmente sem reduzir o objetivo.')),
  jsonb_build_object('heading','Critério','content','Registra comparação e explica quatro de cinco situações usando evidência pertinente.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Formular hipótese','instruction','Observe o problema, escolha uma previsão e diga qual pista a sustenta.','activity','Registre hipótese sem apagar depois do resultado.','support','Foto ampliada, leitura em voz alta e opções visuais.'),
  jsonb_build_object('title','2. Observar e comparar','instruction','Siga o procedimento seguro e registre o que aconteceu.','activity',guided,'support','Tabela antes-durante-depois e modelagem do professor.'),
  jsonb_build_object('title','3. Concluir e aplicar','instruction','Responda à pergunta usando dados e aplique a ideia em novo caso.','activity',independent,'support','Resposta oral, apontada, tabelada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese associada a uma pista.'),jsonb_build_object('page',2,'answer','Observação e comparação coerentes.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre evidência citada, apoio eficaz e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','table','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'sensory_exit',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'adult_supervision',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-3ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ciências do 4º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF04CI01','unidade-2/aula-01-misturas-transformacoes.ts','Misturas do cotidiano'),
('EF04CI02','unidade-2/aula-01-misturas-transformacoes.ts','Transformações reversíveis e irreversíveis'),
('EF04CI03','unidade-2/aula-01-misturas-transformacoes.ts','Mudanças causadas por aquecimento e resfriamento'),
('EF04CI04','unidade-3/aula-01-cadeia-alimentar.ts','Cadeias alimentares e fluxo de energia'),
('EF04CI05','unidade-3/aula-01-cadeia-alimentar.ts','Ciclo da matéria e decomposição'),
('EF04CI06','unidade-4/aula-01-microrganismos.ts','Microrganismos e seus papéis'),
('EF04CI07','unidade-4/aula-01-microrganismos.ts','Microrganismos na produção de alimentos'),
('EF04CI08','unidade-4/aula-01-microrganismos.ts','Prevenção de doenças transmissíveis'),
('EF04CI09','unidade-5/aula-01-sol-pontos-cardeais.ts','Pontos cardeais e posição do Sol'),
('EF04CI10','unidade-5/aula-01-sol-pontos-cardeais.ts','Sombras e orientação'),
('EF04CI11','unidade-6/aula-01-estacoes-ano.ts','Lua, estações e calendários')
), prepared AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-4ano/'||rel source_key,title,'Investigar '||lower(title)||', registrar evidências e explicar conclusões adequadas ao 4º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','4º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Segurança primeiro','content',jsonb_build_array('Professor seleciona materiais e demonstra procedimentos; criança não manipula calor, fogo, culturas de microrganismos, substâncias desconhecidas nem olha diretamente para o Sol.','Use imagens ou dados prontos quando a observação direta não for segura.')),
 jsonb_build_object('heading','Método científico','content',jsonb_build_array('Separe pergunta, hipótese, variável, observação, dado e conclusão.','Altere uma condição por vez e não trate hipótese como resultado.','Em saúde, use fontes confiáveis e não substitua orientação profissional.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use organizador visual, pausa planejada e retomada clara.','Aceite resposta oral, apontada, tabelada, desenhada, fotografada, digitada ou escrita.','Retire apoios gradualmente sem reduzir o objetivo.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando dados, relação causal ou modelo pertinente.')))),
jsonb_build_array(
 jsonb_build_object('title','1. Prever e modelar','instruction','Observe o problema e construa uma previsão ou modelo inicial.','activity','Registre hipótese e indique a pista usada.','support','Imagem ampliada, leitura em voz alta e esquema visual.'),
 jsonb_build_object('title','2. Comparar evidências','instruction','Analise dados ou observações mantendo visível o que mudou.','activity','Compare dois casos de '||lower(title)||' e registre semelhança, diferença e evidência.','support','Tabela, cartões e exemplo resolvido.'),
 jsonb_build_object('title','3. Explicar e transferir','instruction','Responda à pergunta e aplique o modelo em nova situação.','activity','Produza conclusão limitada aos dados e indique o que ainda precisaria ser investigado.','support','Resposta oral, apontada, tabelada, desenhada, digitada ou escrita.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese ligada a uma pista.'),jsonb_build_object('page',2,'answer','Comparação coerente com evidência.'),jsonb_build_object('page',3,'answer','Conclusão baseada nos dados, sem extrapolação.','teacher_note','Registre autonomia, apoio eficaz e próximo passo.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','table','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'adult_supervision',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-4ano'
FROM prepared ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();

-- Biblioteca Inclusiva · Ciências do 5º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF05CI01','unidade-4/aulas-bncc-materia-agua.ts','Propriedades físicas dos materiais'),
('EF05CI02','unidade-4/aulas-bncc-materia-agua.ts','Estados físicos e mudanças da água'),
('EF05CI03','unidade-4/aulas-bncc-materia-agua.ts','Ciclo da água'),
('EF05CI04','unidade-4/aulas-bncc-materia-agua.ts','Cobertura vegetal e ciclo da água'),
('EF05CI05','unidade-4/aula-02-consumo-consciente.ts','Consumo consciente e reciclagem'),
('EF05CI06','unidade-3/aula-01.ts','Sistema digestório e nutrição'),
('EF05CI07','unidade-3/aula-02-sistema-circulatorio.ts','Sistema circulatório'),
('EF05CI08','unidade-3/aula-03-cardapio-equilibrado.ts','Alimentação variada e contexto'),
('EF05CI09','unidade-3/aula-04-disturbios-nutricionais.ts','Saúde alimentar sem estigma'),
('EF05CI10','unidade-6/aulas-bncc-observacao-do-ceu.ts','Constelações e observação do céu'),
('EF05CI11','unidade-6/aulas-bncc-observacao-do-ceu.ts','Rotação da Terra e movimento aparente'),
('EF05CI12','unidade-6/aula-02-fases-da-lua.ts','Fases da Lua'),
('EF05CI13','unidade-6/aula-03-instrumentos-opticos.ts','Instrumentos ópticos')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-5ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' com modelos, dados e linguagem científica adequada ao 5º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare e proteja','content',jsonb_build_array('Professor seleciona e demonstra materiais; não usar calor, substâncias desconhecidas, dissecação nem observação direta do Sol.','Instrumentos ópticos apontam apenas para alvos seguros e nunca para o Sol.')),
 jsonb_build_object('heading','Ensino por modelos','content',jsonb_build_array('Separe o que foi observado, o que o modelo representa e o que foi inferido.','Use tabelas, diagramas e setas para tornar relações sistêmicas visíveis.','Em alimentação e saúde, não pesar, comparar corpos, prescrever dieta ou atribuir culpa; encaminhar dúvidas clínicas à família e profissional.')),
 jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Dê uma instrução por vez, use pausa planejada e retomada clara.','Aceite resposta oral, apontada, diagramada, desenhada, fotografada, digitada ou escrita.','Retire pistas gradualmente sem reduzir o objetivo.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando dados, modelo ou relação causal pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Prever e representar','instruction','Observe o problema e construa hipótese ou modelo inicial.','activity','Registre componentes e relações principais.','support','Imagem ampliada, glossário e diagrama parcialmente preenchido.'),jsonb_build_object('title','2. Analisar dados','instruction','Compare registros e diferencie observação de inferência.','activity','Complete tabela ou modelo de '||lower(title)||' e cite evidência.','support','Exemplo resolvido e redução gradual das pistas.'),jsonb_build_object('title','3. Explicar e aplicar','instruction','Use o modelo em nova situação e diga seus limites.','activity','Produza conclusão baseada nos dados e uma pergunta para investigação futura.','support','Resposta oral, apontada, diagramada, digitada ou escrita.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Modelo inicial coerente.'),jsonb_build_object('page',2,'answer','Análise com evidência.'),jsonb_build_object('page',3,'answer','Conclusão limitada aos dados e ao modelo.','teacher_note','Registre autonomia, apoio eficaz e próximo passo.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'safety_screened',true,'adult_supervision',true,'body_neutral',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-5ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();

-- Biblioteca Inclusiva · Ciências do 6º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF06CI01','unidade-4/aula-04-misturas.ts','Misturas homogêneas e heterogêneas'),
('EF06CI02','unidade-4/aula-01.ts','Transformações químicas'),
('EF06CI03','unidade-4/aula-02.ts','Separação de materiais'),
('EF06CI04','unidade-4/aula-03.ts','Materiais sintéticos e medicamentos'),
('EF06CI05','unidade-2/aula-01.ts','Célula como unidade da vida'),
('EF06CI06','unidade-2/aulas-organizacao-visao.ts','Níveis de organização dos seres vivos'),
('EF06CI07','unidade-2/aula-02-comando-central.ts','Sistema nervoso e coordenação'),
('EF06CI08','unidade-2/aulas-organizacao-visao.ts','Visão e correção óptica'),
('EF06CI09','unidade-2/aula-03-corpo-em-acao.ts','Sistemas locomotor e nervoso'),
('EF06CI10','unidade-2/aula-04-substancias-e-cerebro.ts','Efeitos de substâncias no sistema nervoso'),
('EF06CI11','unidade-6/aula-01.ts','Camadas internas da Terra'),
('EF06CI12','unidade-6/aulas-rochas-terra-sol.ts','Rochas e formação de fósseis'),
('EF06CI13','unidade-6/aulas-rochas-terra-sol.ts','Forma e movimentos da Terra'),
('EF06CI14','unidade-6/aulas-rochas-terra-sol.ts','Movimentos Terra–Sol e sombras')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-6ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' com modelos, dados, relações causais e linguagem científica do 6º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto e critério; use modelo visual sem reduzir o conteúdo científico.','Professor controla materiais e demonstra procedimentos; não usar chama, reagentes, pressão, dissecação, amostras biológicas ou substâncias desconhecidas.')),
 jsonb_build_object('heading','Modelar e investigar','content',jsonb_build_array('Separe observação, modelo, inferência e conclusão; altere uma variável por vez quando aplicável.','Use diagramas de sistemas e escalas, deixando claro que modelos representam aspectos e têm limites.','Na habilidade EF06CI10, trabalhar somente prevenção, efeitos e busca de adulto/profissional; nunca demonstrar, normalizar ou instruir acesso ou uso de substâncias.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida tarefas longas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo linguagem adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, dado, relação causal ou evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o sistema','instruction','Identifique componentes, escala, variável e pergunta.','activity','Construa hipótese ou modelo inicial e marque o que ele representa.','support','Glossário curto, diagrama e texto em blocos.'),jsonb_build_object('title','2. Analisar evidências','instruction','Compare dados, modelos ou procedimentos e diferencie observação de inferência.','activity','Complete tabela ou diagrama de '||lower(title)||' e cite evidência.','support','Exemplo resolvido e redução gradual de pistas.'),jsonb_build_object('title','3. Explicar e avaliar limites','instruction','Aplique o modelo em nova situação e explique onde ele não basta.','activity','Produza conclusão baseada nos dados e uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Sistema e hipótese delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com evidência.'),jsonb_build_object('page',3,'answer','Conclusão limitada ao modelo e aos dados.','teacher_note','Registre autonomia, apoio eficaz e próximo passo.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-6ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();

-- Biblioteca Inclusiva · Ciências do 7º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF07CI01','unidade-5/aulas-maquinas-calor.ts','Máquinas simples no cotidiano'),
('EF07CI02','unidade-5/aulas-maquinas-calor.ts','Temperatura, calor e equilíbrio térmico'),
('EF07CI03','unidade-5/aulas-maquinas-calor.ts','Propagação do calor e materiais'),
('EF07CI04','unidade-5/aula-02-equilibrio-termico.ts','Equilíbrio térmico e vida'),
('EF07CI05','unidade-5/aula-03-combustiveis-historia.ts','Combustíveis, máquinas térmicas e sociedade'),
('EF07CI06','unidade-5/aula-04-automacao-trabalho.ts','Novos materiais, tecnologias e trabalho'),
('EF07CI07','unidade-4/aulas-ecossistemas-impactos.ts','Ecossistemas brasileiros'),
('EF07CI08','unidade-4/aulas-ecossistemas-impactos.ts','Impactos ambientais nos ecossistemas'),
('EF07CI09','unidade-3/aula-02-indicadores-saude.ts','Indicadores e políticas de saúde pública'),
('EF07CI10','unidade-2/aula-02-tecnologia-qualidade-vida.ts','Vacinação e saúde coletiva'),
('EF07CI11','unidade-2/aula-02-tecnologia-qualidade-vida.ts','Tecnologia e qualidade de vida'),
('EF07CI12','unidade-6/aulas-atmosfera-tectonica.ts','Composição do ar'),
('EF07CI13','unidade-6/aulas-atmosfera-tectonica.ts','Efeito estufa e mudanças climáticas'),
('EF07CI14','unidade-6/aulas-atmosfera-tectonica.ts','Camada de ozônio'),
('EF07CI15','unidade-6/aulas-atmosfera-tectonica.ts','Fenômenos naturais e placas tectônicas'),
('EF07CI16','unidade-6/aulas-atmosfera-tectonica.ts','Deriva continental')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-7ano/'||rel source_key,title,'Investigar, analisar e explicar '||lower(title)||' com modelos, dados, relações causais e linguagem científica do 7º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto e critério; use apoio visual sem reduzir o conteúdo científico.','Professor controla materiais e demonstra procedimentos; não usar chama, combustíveis, eletricidade de rede, pressão, ferramentas cortantes, produtos desconhecidos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar e investigar','content',jsonb_build_array('Separe observação, dado, modelo, inferência e conclusão; altere uma variável por vez quando aplicável.','Use diagramas de sistemas, fluxos, escalas e linhas do tempo, explicitando que modelos representam aspectos e têm limites.','Em saúde, clima e ambiente, compare fontes e evidências; trabalhe prevenção, responsabilidade coletiva e busca de adulto ou profissional, sem diagnóstico individual.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida tarefas longas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo linguagem concreta e adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, dado, relação causal ou evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o sistema','instruction','Identifique componentes, escala, variável, período e pergunta.','activity','Construa hipótese ou modelo inicial e marque o que ele representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar evidências','instruction','Compare dados, fontes, modelos ou procedimentos e diferencie observação de inferência.','activity','Complete tabela, gráfico, linha do tempo ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Explicar e avaliar limites','instruction','Aplique o modelo em nova situação, identifique relações causais e explique onde ele não basta.','activity','Produza conclusão baseada nos dados e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Sistema, variável e hipótese delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com dados e fonte indicada.'),jsonb_build_object('page',3,'answer','Conclusão limitada ao modelo e às evidências.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-7ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ciências do 8º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF08CI01','unidade-5/aula-01.ts','Fontes e tipos de energia'),
('EF08CI02','unidade-5/aula-01.ts','Circuitos elétricos'),
('EF08CI03','unidade-5/aula-01.ts','Transformações de energia'),
('EF08CI04','unidade-5/aula-01.ts','Consumo de energia elétrica'),
('EF08CI05','unidade-5/aula-01.ts','Uso consciente da energia'),
('EF08CI06','unidade-5/aula-01.ts','Usinas e impactos socioambientais'),
('EF08CI07','unidade-1/aula-02-processos-reprodutivos.ts','Processos reprodutivos em seres vivos'),
('EF08CI08','unidade-2/aula-01.ts','Puberdade e ação hormonal'),
('EF08CI09','unidade-2/aula-02-saude-respeito-prevencao.ts','Métodos contraceptivos e responsabilidade'),
('EF08CI10','unidade-2/aula-02-saude-respeito-prevencao.ts','Dimensões da sexualidade, respeito e direitos'),
('EF08CI11','unidade-2/aula-02-saude-respeito-prevencao.ts','Prevenção de infecções sexualmente transmissíveis'),
('EF08CI12','unidade-6/aulas-sol-terra-lua-clima.ts','Fases da Lua e eclipses'),
('EF08CI13','unidade-6/aulas-sol-terra-lua-clima.ts','Estações do ano'),
('EF08CI14','unidade-6/aulas-sol-terra-lua-clima.ts','Circulação atmosférica, oceânica e climas'),
('EF08CI15','unidade-7/aula-01.ts','Variáveis meteorológicas e previsão do tempo'),
('EF08CI16','unidade-7/aula-01.ts','Alterações climáticas e ações humanas')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-8ano/'||rel source_key,title,'Investigar, analisar e explicar '||lower(title)||' com modelos, dados, fontes confiáveis, relações causais e linguagem científica do 8º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto e critério; use apoio visual sem reduzir o conteúdo científico.','Professor controla materiais e demonstra procedimentos; não montar circuito na rede elétrica nem usar tomadas, fios desencapados, chama, pressão, reagentes, medicamentos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar, comparar e argumentar','content',jsonb_build_array('Separe observação, dado, modelo, inferência e conclusão; identifique variável, escala, período e fonte.','Use diagramas de fluxo, sistemas, escalas, gráficos e linhas do tempo; explicite que modelos representam aspectos e têm limites.','Em saúde e sexualidade, use informação científica apropriada à idade, respeito, privacidade, consentimento, prevenção e busca de adulto ou profissional; não diagnosticar, não expor vivências pessoais e não solicitar relatos íntimos.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida tarefas longas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo vocabulário científico explicado e linguagem adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, cálculo, dado, relação causal ou evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o problema','instruction','Identifique sistema, componentes, variável, escala, período, fonte e pergunta.','activity','Construa hipótese, previsão ou modelo inicial e marque o que ele representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar dados e fontes','instruction','Compare dados, cálculos, fontes, modelos ou procedimentos e diferencie associação de causalidade.','activity','Complete tabela, gráfico, linha do tempo, circuito esquemático ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Explicar, decidir e avaliar limites','instruction','Aplique o modelo em nova situação, justifique uma decisão e explique incertezas ou limites.','activity','Produza conclusão baseada nos dados e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Problema, variáveis e hipótese delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com cálculo, dado e fonte indicada.'),jsonb_build_object('page',3,'answer','Conclusão limitada ao modelo e às evidências.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo; preserve privacidade.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-8ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ciências do 9º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF09CI01','unidade-3/aulas-materia-transformacoes.ts','Estados físicos e modelo de partículas'),
('EF09CI02','unidade-3/aulas-materia-transformacoes.ts','Proporções e conservação nas reações'),
('EF09CI03','unidade-3/aula-01.ts','Estrutura da matéria e transformações químicas'),
('EF09CI04','unidade-4/aulas-luz-radiacoes.ts','Luz, cores e sistema RGB'),
('EF09CI05','unidade-4/aulas-luz-radiacoes.ts','Comunicação e espectro eletromagnético'),
('EF09CI06','unidade-4/aulas-luz-radiacoes.ts','Ondas eletromagnéticas e tecnologias'),
('EF09CI07','unidade-4/aulas-luz-radiacoes.ts','Radiações na saúde e na medicina'),
('EF09CI08','unidade-1/aula-01.ts','Hereditariedade e transmissão de características'),
('EF09CI09','unidade-1/aula-01.ts','Ideias de Mendel e probabilidade genética'),
('EF09CI10','unidade-1/aulas-evolucao-conservacao.ts','Lamarck, Darwin e seleção natural'),
('EF09CI11','unidade-1/aula-01.ts','Evolução e diversidade biológica'),
('EF09CI12','unidade-1/aulas-evolucao-conservacao.ts','Unidades de conservação e biodiversidade'),
('EF09CI13','unidade-6/aula-01.ts','Sustentabilidade e ações coletivas'),
('EF09CI14','unidade-5/aula-01.ts','Sistema Solar e estrutura do Universo'),
('EF09CI15','unidade-5/aulas-astronomia.ts','Céus, culturas e modelos de origem'),
('EF09CI16','unidade-5/aulas-astronomia.ts','Condições para vida fora da Terra'),
('EF09CI17','unidade-5/aulas-astronomia.ts','Nascimento, evolução e morte das estrelas')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-9ano/'||rel source_key,title,'Investigar, analisar, modelar e argumentar sobre '||lower(title)||' com dados, cálculos, fontes confiáveis e linguagem científica do 9º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto, vocabulário e critério; use apoio visual sem reduzir a complexidade científica.','Professor controla materiais e demonstra procedimentos; não usar rede elétrica, laser, fontes de radiação, chama, reagentes, pressão, medicamentos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar, calcular e argumentar','content',jsonb_build_array('Separe observação, medida, modelo, inferência e conclusão; declare variável, escala, período, incerteza e fonte.','Use modelos de partículas, diagramas, proporções, heredogramas fictícios, gráficos, escalas e linhas do tempo, explicitando limites de cada representação.','Em genética e saúde, não fazer diagnóstico, previsão individual ou coleta de dados familiares reais; usar casos fictícios, privacidade, linguagem não determinista e orientação de adulto ou profissional.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida a investigação em etapas curtas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo termos científicos explicados e linguagem adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, cálculo, dado, mecanismo causal ou evidência pertinente e reconhece limites.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o problema e o modelo','instruction','Identifique sistema, componentes, variável, escala, período, fonte, incerteza e pergunta.','activity','Construa hipótese, previsão ou modelo inicial e indique o que ele representa e não representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar dados e explicações','instruction','Compare medidas, cálculos, fontes, modelos ou teorias e diferencie evidência de opinião e associação de causalidade.','activity','Complete tabela, gráfico, proporção, linha do tempo ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar e avaliar limites','instruction','Aplique o modelo em nova situação, justifique uma conclusão e explicite incertezas, implicações e limites.','activity','Produza argumento baseado em evidências e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Problema, variáveis, hipótese e limites do modelo delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com cálculo, dado e fonte indicada.'),jsonb_build_object('page',3,'answer','Argumento limitado às evidências e incertezas.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo; preserve privacidade.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'non_deterministic_language',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-9ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
