BEGIN;
-- Biblioteca Inclusiva · História do 1º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF01HI01','src/escola-brilha/data/EF01HI01.ts','O álbum das descobertas','Identificar aspectos do próprio crescimento por meio de registros e lembranças, respeitando diferentes trajetórias.'),
('EF01HI02','src/escola-brilha/data/EF01HI02.ts','Minha família, minha história','Reconhecer relações entre histórias pessoais e histórias de grupos familiares e comunitários diversos.'),
('EF01HI03','src/escola-brilha/data/EF01HI03.ts','Meus papéis em cada lugar','Distinguir papéis e responsabilidades na família, escola e comunidade sem estereótipos.'),
('EF01HI04','src/escola-brilha/data/EF01HI04.ts','Casa, escola e comunidade','Comparar características, hábitos e regras de diferentes ambientes de convivência.'),
('EF01HI05','src/escola-brilha/data/EF01HI05.ts','As brincadeiras de ontem e de hoje','Comparar brincadeiras atuais e de outras épocas e lugares usando fontes acessíveis.'),
('EF01HI06','src/escola-brilha/data/EF01HI06.ts','Cada pessoa tem sua história','Conhecer histórias da família e da escola preservando privacidade e acolhendo diferentes configurações.'),
('EF01HI07','src/escola-brilha/data/EF01HI07.ts','Famílias que mudam com o tempo','Identificar mudanças e permanências nas formas de organização familiar.'),
('EF01HI08','src/escola-brilha/data/EF01HI08.ts','As festas que nos unem','Reconhecer sentidos de festas e comemorações escolares e comunitárias, respeitando participação e diversidade cultural ou religiosa.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com acolhimento','content',jsonb_build_array('Use personagens, fotografias públicas, objetos ou cartões fornecidos pela escola; nunca exija fotografia, documento, endereço, religião ou relato familiar da criança.','Apresente objetivo e sequência visual: observar, ordenar, comparar e contar.')),
 jsonb_build_object('heading','Ensine a pensar historicamente','content',jsonb_build_array('Modele a diferença entre antes, agora e depois e entre mudança e permanência.','Compare duas fontes simples e pergunte quem produziu, o que mostra e o que não permite saber.','Mostre famílias, moradias, culturas, corpos e modos de viver diversos sem tratar um modelo como padrão.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, desenho, foto fornecida pela escola, digitação, escrita ou tecnologia assistiva.','Não avalie memória familiar, habilidade de leitura ou fala como se fossem compreensão histórica.')),
 jsonb_build_object('heading','Critério','content','Ordena, compara ou explica quatro de cinco situações usando uma pista temporal ou evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar a fonte','instruction','Observe personagem, imagem, objeto ou relato fictício e identifique pistas.','activity','Marque o que a fonte mostra e uma coisa que ela não permite saber.','support','Vocabulário visual, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Ordenar e comparar','instruction','Organize cenas em antes, agora e depois; compare mudança e permanência.','activity','Monte linha do tempo de cartões ou tabela de duas colunas sobre '||lower(title)||'.','support','Modelo pronto, pistas graduadas e Prática guiada antes da independente.'),jsonb_build_object('title','3. Contar com evidência','instruction','Conte o que mudou ou permaneceu e aponte a pista usada.','activity','Escolha fala, sequência, desenho, cartões ou escrita para apresentar a conclusão.','support','Resposta oral, apontada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica ao menos uma pista observável e um limite da fonte.'),jsonb_build_object('page',2,'answer','Ordena ou compara com coerência temporal.'),jsonb_build_object('page',3,'answer','Conclusão ligada à pista selecionada.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre informações familiares sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'family_diversity',true,'cultural_religious_respect',true,'fictional_alternative',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 2º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF02HI01','unidade-7/aula-02-comunidades-convivencia.ts','Comunidades e espaços de convivência'),
('EF02HI02','unidade-7/aula-02-comunidades-convivencia.ts','Práticas, papéis e convivência'),
('EF02HI03','unidade-6/aula-01-costumes-que-mudaram.ts','Costumes, relações e mudanças'),
('EF02HI04','unidade-2/aula-01-arvore-genealogica.ts','Fontes de histórias pessoais e familiares'),
('EF02HI05','unidade-5/aula-01-objetos-do-passado.ts','Objetos, documentos e memória'),
('EF02HI06','unidade-1/aula-01-ontem-hoje-amanha.ts','Sucessão do tempo: antes, durante e depois'),
('EF02HI07','unidade-1/aula-02-marcadores-tempo.ts','Calendários, relógios e marcadores do tempo'),
('EF02HI08','unidade-4/aula-01-historia-do-bairro.ts','Memórias e história da comunidade'),
('EF02HI09','unidade-3/aula-01-historia-da-escola.ts','Mudanças e permanências na escola'),
('EF02HI10','unidade-6/aula-02-trabalho-ambiente.ts','Trabalho, sobrevivência e natureza'),
('EF02HI11','unidade-6/aula-02-trabalho-ambiente.ts','Impactos do trabalho no ambiente')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-2ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, sequências temporais, comparações e linguagem histórica do 2º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com acolhimento','content',jsonb_build_array('Use personagens, mapas fictícios, fotografias públicas, objetos ou cartões fornecidos pela escola; nunca exija fotografia, certidão, endereço, religião, ocupação ou relato familiar da criança.','Troque árvore genealógica obrigatória por rede de pessoas importantes ou família fictícia quando necessário.')),
 jsonb_build_object('heading','Investigar fontes e tempo','content',jsonb_build_array('Modele passado, presente e futuro; antes, durante e depois; mudança e permanência.','Compare fonte material, escrita, oral e visual perguntando quem produziu, quando, para quê, o que mostra e o que não permite saber.','Diferencie evidência, lembrança e opinião; memórias podem variar sem que uma pessoa esteja mentindo.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem não estigmatizante ao tratar trabalho, moradia, família, comunidade e mudanças ambientais.')),
 jsonb_build_object('heading','Critério','content','Ordena, compara ou explica quatro de cinco situações usando marcador temporal e evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler a fonte','instruction','Observe fonte fictícia ou pública e identifique autoria, tempo, pistas e limites.','activity','Marque o que a fonte mostra e uma pergunta que ela não responde.','support','Vocabulário visual, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Ordenar e comparar','instruction','Organize acontecimentos e compare mudanças, permanências e pontos de vista.','activity','Monte linha do tempo, quadro ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar com evidência','instruction','Relacione tempo, espaço, pessoas e ambiente e indique a fonte usada.','activity','Apresente conclusão por fala, sequência, desenho, cartões ou escrita.','support','Resposta oral, apontada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica pista, tempo e limite da fonte.'),jsonb_build_object('page',2,'answer','Ordena ou compara com coerência temporal.'),jsonb_build_object('page',3,'answer','Conclusão ligada à evidência selecionada.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre dados familiares sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'family_diversity',true,'fictional_alternative',true,'multiple_perspectives',true,'non_stigmatizing_language',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-2ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 3º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF03HI01','unidade-5/aula-02-grupos-perspectivas.ts','Grupos que formam a história local'),
('EF03HI02','unidade-1/aula-02-fontes-historia-local.ts','Fontes da história local'),
('EF03HI03','unidade-5/aula-02-grupos-perspectivas.ts','Perspectivas sobre acontecimentos locais'),
('EF03HI04','unidade-4/aula-01-surgimento-cidades-patrimonio.ts','Formação das cidades e patrimônio'),
('EF03HI05','unidade-4/aula-01-surgimento-cidades-patrimonio.ts','Marcos históricos e memória coletiva'),
('EF03HI06','unidade-4/aula-02-nomes-memoria.ts','Nomes, monumentos e disputas de memória'),
('EF03HI07','unidade-2/aulas-comunidades-trabalho.ts','Comunidades da cidade e do campo'),
('EF03HI08','unidade-2/aulas-comunidades-trabalho.ts','Modos de vida urbanos e rurais'),
('EF03HI09','unidade-6/aula-02-espacos-cidade.ts','Espaços públicos, privados e protegidos'),
('EF03HI10','unidade-6/aula-02-espacos-cidade.ts','Diferenças entre espaços domésticos, públicos e de conservação'),
('EF03HI11','unidade-2/aulas-comunidades-trabalho.ts','Trabalho na cidade e no campo'),
('EF03HI12','unidade-7/aula-02-lazer-tempo.ts','Lazer e uso do tempo na cidade e no campo')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-3ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, mapas, sequências temporais, comparações e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes e perspectivas','content',jsonb_build_array('Use mapas fictícios ou públicos, imagens, objetos, depoimentos publicados e cartões fornecidos pela escola; não exija endereço, fotografia, origem familiar, renda, profissão ou relato pessoal.','Inclua indígenas, povos africanos e afro-brasileiros, migrantes e outros grupos como sujeitos históricos diversos, com presente e agência; não os reduza a uma mistura homogênea ou contribuição folclórica.')),
 jsonb_build_object('heading','Investigar história local','content',jsonb_build_array('Compare autoria, data, finalidade, contexto, evidências, silêncios e limites de fontes materiais, escritas, orais, visuais e cartográficas.','Organize mudança e permanência; conecte campo e cidade sem hierarquizar modos de vida.','Trate nomes de ruas, monumentos e patrimônios como escolhas de memória que podem incluir, excluir ou ser debatidas.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, mapa, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem não estigmatizante ao tratar território, trabalho, moradia, lazer, cultura e ambiente.')),
 jsonb_build_object('heading','Critério','content','Compara ou explica quatro de cinco situações usando marcador temporal, localização, perspectiva e evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e ler fontes','instruction','Localize tempo e espaço e identifique autoria, finalidade, pistas, silêncios e limites.','activity','Marque o que duas fontes mostram, em que divergem e uma pergunta ainda aberta.','support','Vocabulário visual, mapa simples, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar mudanças e perspectivas','instruction','Organize acontecimentos e compare permanências, grupos e pontos de vista.','activity','Monte linha do tempo, quadro comparativo ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar com evidências','instruction','Relacione tempo, território, grupos, trabalho, cultura e ambiente e cite as fontes usadas.','activity','Apresente uma conclusão e reconheça outra perspectiva ou limite.','support','Resposta oral, apontada, mapeada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fonte, identifica pista, perspectiva e limite.'),jsonb_build_object('page',2,'answer','Compara com coerência temporal e espacial sem hierarquizar grupos.'),jsonb_build_object('page',3,'answer','Conclusão ligada às evidências e aberta a outra perspectiva.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre dados pessoais sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'contested_memory',true,'non_stigmatizing_language',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-3ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 4º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF04HI01','unidade-1/aula-02-historia-cidades.ts','História, ação humana e transformações'),
('EF04HI02','unidade-1/aula-01-primeiros-deslocamentos.ts','Mudanças e permanências ao longo do tempo'),
('EF04HI03','unidade-1/aula-02-historia-cidades.ts','Formação e transformação das cidades'),
('EF04HI04','unidade-1/aula-01-primeiros-deslocamentos.ts','Nomadismo, agricultura e ocupação humana'),
('EF04HI05','unidade-2/aula-02-ocupacao-comunicacao.ts','Ocupação do campo e relação com a natureza'),
('EF04HI06','unidade-2/aula-02-ocupacao-comunicacao.ts','Comunicação, circulação e transformações sociais'),
('EF04HI07','unidade-4/aula-01-diaspora-africana.ts','Rotas, comércio e deslocamentos humanos'),
('EF04HI08','unidade-4/aula-01-diaspora-africana.ts','Migração forçada, diáspora africana e resistência'),
('EF04HI09','unidade-5/aula-01-imigracao.ts','Imigrações para o Brasil nos séculos XIX e XX'),
('EF04HI10','unidade-6/aula-01-migracoes-internas.ts','Migrações internas no Brasil'),
('EF04HI11','unidade-6/aula-01-migracoes-internas.ts','Migrações e transformações regionais')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-4ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, mapas, cronologia, causas, consequências e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','4º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize sem apagar sujeitos','content',jsonb_build_array('Use mapas, linhas do tempo e fontes públicas ou fictícias; não solicite origem, situação migratória ou história familiar da criança.','Diferencie migração voluntária, deslocamento forçado e escravização; não use linguagem que transforme pessoas em mercadorias ou apresente violência de modo gráfico.','Apresente povos africanos e afro-brasileiros e povos indígenas como diversos, com conhecimentos, decisões, resistências, continuidades e presença atual.')),
 jsonb_build_object('heading','Investigue rotas e transformações','content',jsonb_build_array('Compare autoria, contexto, finalidade, evidências, silêncios e limites de mapas, objetos, textos, imagens e relatos publicados.','Relacione deslocamentos a causas e consequências políticas, econômicas, ambientais, culturais e tecnológicas, evitando explicações únicas.','Analise circulação e ocupação territorial também pelos impactos sobre povos originários, populações locais e natureza.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, mapa, linha do tempo, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem adequada à idade, não estigmatizante e sem simulações de opressão ou encenação de sofrimento.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco processos usando localização, cronologia, causa, consequência, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar rotas e fontes','instruction','Localize tempo, espaço, grupos, autoria, finalidade, pistas e limites.','activity','Leia mapa e duas fontes para identificar percurso, contexto e perguntas abertas.','support','Vocabulário visual, mapa simplificado, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar causas e experiências','instruction','Compare migrações, permanências, interesses, escolhas, coerções e perspectivas.','activity','Monte linha do tempo, quadro causal ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar transformações','instruction','Relacione deslocamentos, circulação, território, tecnologia, cultura e ambiente com evidências.','activity','Apresente conclusão que reconheça agência dos grupos, consequência e limite das fontes.','support','Resposta oral, apontada, mapeada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa rota, grupos, fonte e limite.'),jsonb_build_object('page',2,'answer','Compara causas e experiências sem apagar coerção ou agência.'),jsonb_build_object('page',3,'answer','Explicação causal ligada às evidências e perspectivas.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados familiares e migratórios.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','timeline','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'forced_migration_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-4ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 5º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF05HI01','unidade-1/aula-02-povos-identidades.ts','Povos, culturas e formação social'),
('EF05HI02','unidade-3/aula-01-formas-governo.ts','Formas de organização política e social'),
('EF05HI03','unidade-1/aula-02-povos-identidades.ts','Territórios, identidades e culturas'),
('EF05HI04','unidade-1/aula-01-cidadania-antiguidade.ts','Cidadania na Antiguidade e no presente'),
('EF05HI05','unidade-4/aula-01-direitos-sociais.ts','Conquistas sociais e cidadania'),
('EF05HI06','unidade-7/aula-02-linguagens-tempo.ts','Linguagens e transmissão de saberes'),
('EF05HI07','unidade-5/aula-02-memoria-marcos.ts','Marcos, calendários e memória'),
('EF05HI08','unidade-7/aula-02-linguagens-tempo.ts','Formas de marcar e organizar o tempo'),
('EF05HI09','unidade-6/aula-02-temas-contemporaneos.ts','Fontes e temas contemporâneos'),
('EF05HI10','unidade-5/aula-01-patrimonio-unesco.ts','Patrimônios materiais, imateriais e diversidade')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-5ano/'||rel source_key,title,'Investigar, comparar e argumentar sobre '||lower(title)||' usando fontes, cronologia, conceitos históricos e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize conceitos','content',jsonb_build_array('Explique que cidadania, direitos, governo, tempo e patrimônio mudam entre sociedades e períodos; evite apresentar modelos antigos ou atuais como universais.','Mostre quem participou, quem foi excluído, quem reivindicou mudanças e quais limites permaneceram, usando linguagem adequada à idade e sem detalhes gráficos.','Apresente povos indígenas, africanos e afro-brasileiros e pessoas com deficiência como sujeitos diversos, produtores de conhecimento, cultura e ação política.')),
 jsonb_build_object('heading','Investigue fontes e argumentos','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de textos, imagens, objetos, relatos e patrimônios.','Diferencie fato verificável, interpretação, opinião e desinformação; confirme temas contemporâneos em mais de uma fonte confiável.','Analise marcos e patrimônios perguntando quem escolheu preservar, quais memórias aparecem e quais podem estar ausentes.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, linha do tempo, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não peça que a criança revele religião, posição política, deficiência, origem, renda ou experiência de discriminação.')),
 jsonb_build_object('heading','Critério','content','Compara ou argumenta em quatro de cinco situações usando contexto, cronologia, conceito, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Contextualizar e ler fontes','instruction','Identifique sociedade, período, grupos, autoria, finalidade, pistas, silêncios e limites.','activity','Compare duas fontes e registre convergência, diferença e pergunta aberta.','support','Glossário visual, linha do tempo, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar conceitos e perspectivas','instruction','Compare cidadania, poder, linguagem, tempo, memória ou patrimônio entre contextos.','activity','Monte quadro, linha do tempo ou mapa conceitual de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com evidências','instruction','Formule conclusão, cite fontes, reconheça outra perspectiva e limite do argumento.','activity','Apresente argumento curto em formato acessível e revise após uma pergunta crítica.','support','Resposta oral, apontada, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Contextualiza fonte, grupos e limite.'),jsonb_build_object('page',2,'answer','Compara conceitos sem anacronismo ou universalização.'),jsonb_build_object('page',3,'answer','Argumento ligado às evidências e aberto a revisão.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados sensíveis e opiniões pessoais.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','timeline','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'disability_agency',true,'source_verification',true,'contested_memory',true,'non_graphic',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-5ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 6º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF06HI01','unidade-1/aula-02-tempo-periodizacao.ts','Tempo histórico e formas de periodização'),
('EF06HI02','unidade-1/aula-01-ciencia-da-historia.ts','Fontes e produção do conhecimento histórico'),
('EF06HI03','unidade-2/aula-02-origens-povoamento.ts','Origens humanas e deslocamentos'),
('EF06HI04','unidade-2/aula-02-origens-povoamento.ts','Povoamento das Américas'),
('EF06HI05','unidade-3/aula-01-civilizacoes-hidraulicas.ts','Sociedades antigas, natureza e cultura'),
('EF06HI06','unidade-2/aula-02-origens-povoamento.ts','Povos originários das Américas'),
('EF06HI07','unidade-4/aula-02-mundos-antigo-medieval.ts','Formação do mundo antigo'),
('EF06HI08','unidade-4/aula-02-mundos-antigo-medieval.ts','Espaços e culturas do mundo antigo'),
('EF06HI09','unidade-4/aula-02-mundos-antigo-medieval.ts','Passagens do mundo antigo ao medieval'),
('EF06HI10','unidade-4/aula-01-grecia-antiga.ts','Grécia antiga, pólis e cultura'),
('EF06HI11','unidade-5/aula-01-roma-antiga.ts','Roma: monarquia, república e império'),
('EF06HI12','unidade-4/aula-01-grecia-antiga.ts','Cidadania, política e exclusões na Antiguidade'),
('EF06HI13','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Impérios, contatos e circulação mediterrânica'),
('EF06HI14','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Culturas, religiões e poder no Mediterrâneo'),
('EF06HI15','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Reinos e sociedades africanas antigas'),
('EF06HI16','unidade-7/aula-02-cidades-trabalho.ts','Cidades, abastecimento e organização social'),
('EF06HI17','unidade-7/aula-02-cidades-trabalho.ts','Trabalho livre, servidão e escravização'),
('EF06HI18','unidade-7/aula-03-cristianismo-mulheres.ts','Cristianismo, poder e transformações sociais'),
('EF06HI19','unidade-7/aula-03-cristianismo-mulheres.ts','Experiências e papéis das mulheres na Antiguidade e no medievo')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-6ano/'||rel source_key,title,'Analisar e explicar '||lower(title)||' usando fontes, cronologia, espacialização, conceitos e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize sem simplificar demais','content',jsonb_build_array('Apresente periodizações como escolhas de historiadores, não como divisões naturais ou universais; inclua cronologias africanas, americanas, asiáticas e europeias.','Evite a ideia de civilização superior, evolução linear ou povo sem história; povos originários e sociedades africanas aparecem com diversidade, conhecimentos, agência e presença atual.','Ao tratar guerras, escravização, perseguições e desigualdades, use descrição informativa e não gráfica; não faça simulações de opressão ou sofrimento.')),
 jsonb_build_object('heading','Analisar evidências e conceitos','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de fontes arqueológicas, materiais, escritas, orais e visuais.','Relacione território, ambiente, trabalho, religião, gênero, cidadania, poder e intercâmbios sem reduzir processos a uma causa única.','Diferencie escravização, servidão e trabalho livre e reconheça resistência e ação histórica das pessoas submetidas à coerção.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida textos e tarefas em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, digitada, escrita ou com tecnologia assistiva.','Use glossário, linha do tempo, mapa, fonte ampliada e prática guiada, retirando pistas gradualmente.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco situações usando contexto, cronologia, espaço, conceito, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar problema e fontes','instruction','Identifique período, espaço, grupos, autoria, finalidade, pistas, silêncios e limites.','activity','Compare duas fontes ou periodizações e formule pergunta histórica.','support','Glossário, linha do tempo, mapa, leitura apoiada e exemplo resolvido.'),jsonb_build_object('title','2. Relacionar processos','instruction','Compare organizações sociais e conecte ambiente, trabalho, cultura, poder, gênero e religião.','activity','Monte quadro causal, mapa, linha do tempo ou diagrama de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar historicamente','instruction','Formule explicação com evidências, reconheça agência, outra perspectiva e limites.','activity','Produza argumento curto, cite fontes e revise diante de contraexemplo.','support','Resposta oral, apontada, mapeada, diagramada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fontes e identifica pistas, silêncios e limites.'),jsonb_build_object('page',2,'answer','Relaciona processos sem hierarquia cultural ou causa única.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidências e múltiplas perspectivas.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre religião, origem ou experiência pessoal sensível.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_african_agency',true,'periodization_plurality',true,'forced_labor_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-6ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 7º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF07HI01','unidade-1/aula-02-modernidade-conexoes.ts','Modernidade, conexões e exclusões'),
('EF07HI02','unidade-1/aula-02-modernidade-conexoes.ts','Humanismos e transformações da modernidade'),
('EF07HI03','unidade-2/aula-01-renascimento-ciencia.ts','Renascimentos artísticos e culturais'),
('EF07HI04','unidade-2/aula-01-renascimento-ciencia.ts','Ciência, imprensa e circulação de ideias'),
('EF07HI05','unidade-3/aula-01-reformas-religiosas.ts','Reformas religiosas e conflitos europeus'),
('EF07HI06','unidade-5/aula-01-grandes-navegacoes.ts','Expansões marítimas europeias'),
('EF07HI07','unidade-4/aula-01-absolutismo-mercantilismo.ts','Monarquias europeias e centralização política'),
('EF07HI08','unidade-6/aula-02-sociedades-antes-conquista.ts','Áfricas e Américas antes da conquista'),
('EF07HI09','unidade-6/aula-01-conquista-america.ts','Conquista europeia e sociedades americanas'),
('EF07HI10','unidade-6/aula-01-conquista-america.ts','Alianças, conflitos e resistências indígenas'),
('EF07HI11','unidade-7/aula-02-territorios-populacoes.ts','Territórios e populações da América colonial'),
('EF07HI12','unidade-7/aula-02-territorios-populacoes.ts','Distribuição territorial e diversidade étnico-cultural'),
('EF07HI13','unidade-4/aula-01-absolutismo-mercantilismo.ts','Mercantilismo e dominação colonial'),
('EF07HI14','unidade-7/aula-03-comercio-africa-asia.ts','Redes comerciais africanas e asiáticas'),
('EF07HI15','unidade-7/aula-01-brasil-colonial.ts','Economia açucareira e sociedade colonial'),
('EF07HI16','unidade-7/aula-01-brasil-colonial.ts','Escravização, resistências e quilombos'),
('EF07HI17','unidade-4/aula-01-absolutismo-mercantilismo.ts','Comércio atlântico e circulação colonial')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-7ano/'||rel source_key,title,'Analisar e argumentar sobre '||lower(title)||' usando fontes, mapas, cronologia, causalidade e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize encontros e conflitos','content',jsonb_build_array('Problematize termos como descobrimento, conquista, civilização e Novo Mundo, identificando quem os produziu e quais perspectivas silenciam.','Apresente Áfricas e Américas antes da conquista como espaços diversos, complexos e conectados; povos indígenas e africanos aparecem com conhecimentos, decisões, alianças, conflitos, resistências e presença atual.','Trate epidemias, guerras, perseguições e escravização de modo informativo e não gráfico; não proponha encenação de opressão, sofrimento ou negociação de pessoas.')),
 jsonb_build_object('heading','Analisar fontes, redes e poder','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de mapas, crônicas, imagens, objetos e relatos.','Relacione religião, ciência, comércio, Estado, território, trabalho e circulação sem atribuir superioridade cultural ou uma causa única.','Diferencie comércio entre sociedades de sistemas coloniais coercitivos e analise a agência de indígenas, africanos, afro-brasileiros e quilombolas.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida textos e tarefas em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, digitada, escrita ou com tecnologia assistiva.','Use glossário, mapas comparáveis, cronologia, fonte ampliada e prática guiada, retirando pistas gradualmente.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco processos usando contexto, cronologia, território, causalidade, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar fontes e conceitos','instruction','Identifique período, território, grupos, autoria, finalidade, linguagem, pistas, silêncios e limites.','activity','Compare duas fontes e questione um conceito ou representação histórica.','support','Glossário, mapa, linha do tempo, leitura apoiada e exemplo resolvido.'),jsonb_build_object('title','2. Relacionar redes, interesses e coerções','instruction','Compare conexões, interesses, alianças, conflitos, resistências e relações de poder.','activity','Monte quadro causal, mapa de fluxos ou linha do tempo de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar com múltiplas perspectivas','instruction','Formule explicação com evidências, reconheça agência, consequência, outra perspectiva e limites.','activity','Produza argumento curto, cite fontes e revise diante de contraexemplo.','support','Resposta oral, apontada, mapeada, diagramada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fontes, conceitos, perspectivas e limites.'),jsonb_build_object('page',2,'answer','Relaciona redes e poder sem superioridade cultural ou causa única.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidências e agência histórica.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre religião, origem ou experiência pessoal sensível.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_african_quilombola_agency',true,'contested_terms',true,'forced_labor_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-7ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 8º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF08HI01','unidade-1/aula-01-iluminismo.ts','Iluminismo e crítica ao Antigo Regime'),
('EF08HI02','unidade-1/aula-02-revolucoes-inglesas.ts','Revoluções inglesas e parlamentarismo'),
('EF08HI03','unidade-2/aula-02-circulacao-industrial.ts','Revolução Industrial, circulação e trabalho'),
('EF08HI04','unidade-3/aula-01-revolucao-francesa.ts','Revolução Francesa e seus desdobramentos'),
('EF08HI05','unidade-3/aula-02-rebelioes-america-portuguesa.ts','Rebeliões na América portuguesa'),
('EF08HI06','unidade-5/aula-02-estado-nacao-independencias.ts','Estado, nação e território'),
('EF08HI07','unidade-5/aula-02-estado-nacao-independencias.ts','Independências americanas e projetos nacionais'),
('EF08HI08','unidade-5/aula-01-haiti-hispanoamerica.ts','Revolução de São Domingo e Haiti'),
('EF08HI09','unidade-5/aula-01-haiti-hispanoamerica.ts','Independências hispano-americanas'),
('EF08HI10','unidade-5/aula-01-haiti-hispanoamerica.ts','Lideranças e grupos nas independências'),
('EF08HI11','unidade-5/aula-01-haiti-hispanoamerica.ts','Pan-americanismo e projetos políticos'),
('EF08HI12','unidade-4/aula-01-napoleao-corte.ts','Era napoleônica e corte portuguesa no Brasil'),
('EF08HI13','unidade-6/aula-01-independencia-brasil.ts','Independência do Brasil e permanências sociais'),
('EF08HI14','unidade-6/aula-07-tutela-participacao.ts','Tutela indígena e participação negra'),
('EF08HI15','unidade-6/aula-02-disputas-politicas-imperio.ts','Primeiro Reinado, Regências e Segundo Reinado'),
('EF08HI16','unidade-6/aula-03-revoltas-regenciais.ts','Revoltas regenciais e disputas sociais'),
('EF08HI17','unidade-6/aula-04-fronteiras-conflitos.ts','Fronteiras, territórios e povos indígenas'),
('EF08HI18','unidade-6/aula-05-guerra-paraguai.ts','Guerra do Paraguai e diferentes interpretações'),
('EF08HI19','unidade-6/aula-06-legado-escravidao.ts','Legados da escravização nas Américas'),
('EF08HI20','unidade-6/aula-10-legados-acoes-afirmativas.ts','Pós-abolição, desigualdades e ações afirmativas'),
('EF08HI21','unidade-6/aula-08-politicas-indigenistas.ts','Políticas indigenistas no Império'),
('EF08HI22','unidade-6/aula-09-romantismo-identidade.ts','Romantismo e construção da identidade nacional'),
('EF08HI23','unidade-7/aula-01-imperialismo.ts','Imperialismo europeu na África e na Ásia'),
('EF08HI24','unidade-7/aula-02-produtos-africanos-imperialismo.ts','Produtos africanos e exploração imperialista'),
('EF08HI25','unidade-7/aula-03-eua-america-latina.ts','Estados Unidos e América Latina no século XIX'),
('EF08HI26','unidade-7/aula-01-imperialismo.ts','Resistências africanas e asiáticas ao imperialismo'),
('EF08HI27','unidade-7/aula-01-imperialismo.ts','Nacionalismos e tensões territoriais')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-8ano/'||rel source_key,title,'Analisar, comparar e argumentar sobre '||lower(title)||' usando fontes, cronologia, causalidade, conceitos e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize revoluções e impérios','content',jsonb_build_array('Compare liberdade, cidadania, nação e direitos perguntando quem foi incluído, excluído e mobilizado em cada contexto.','Apresente independências como processos disputados, com participação de mulheres, indígenas, africanos, afrodescendentes, trabalhadores e elites, evitando narrativas de herói único.','Ao tratar revoluções, guerras, escravização, racismo e imperialismo, use linguagem informativa e não gráfica; não faça encenação de combate, opressão ou sofrimento.')),
 jsonb_build_object('heading','Analisar fontes, causalidade e legados','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de leis, mapas, jornais, imagens, cartas e testemunhos publicados.','Relacione ideias, economia, trabalho, território, raça, gênero, Estado e resistências sem causa única, determinismo ou justificativa civilizatória.','Diferencie evento, processo, interpretação e memória; conecte escravização e imperialismo a legados atuais sem reduzir pessoas a vítimas ou culpar estudantes.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida textos e tarefas em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, digitada, escrita ou com tecnologia assistiva.','Use glossário, mapas comparáveis, cronologia, fontes ampliadas e prática guiada, retirando pistas gradualmente.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco processos usando contexto, cronologia, causalidade, conceito, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar fontes e conceitos','instruction','Identifique período, território, grupos, autoria, finalidade, linguagem, pistas, silêncios e limites.','activity','Compare duas fontes e formule uma pergunta histórica verificável.','support','Glossário, mapa, linha do tempo, leitura apoiada e exemplo resolvido.'),jsonb_build_object('title','2. Explicar processos e disputas','instruction','Relacione ideias, interesses, coerções, resistências, mudanças e permanências.','activity','Monte quadro causal, mapa de fluxos ou linha do tempo de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar e revisar interpretações','instruction','Formule argumento com evidências, reconheça agência, outra interpretação, legado e limites.','activity','Cite fontes, confronte contraexemplo e revise a conclusão.','support','Resposta oral, apontada, mapeada, diagramada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fontes, conceitos, grupos e limites.'),jsonb_build_object('page',2,'answer','Explica processo sem herói único, causa única ou superioridade cultural.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidências e aberto a revisão.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve origem, raça, religião, política e vivências pessoais.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_descendant_agency',true,'women_workers_agency',true,'contested_interpretations',true,'forced_labor_context',true,'non_graphic',true,'no_violence_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-8ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · História do 9º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF09HI01','unidade-4/aula-02-republica-pos-abolicao.ts','República e pós-abolição'),('EF09HI02','unidade-4/aula-01-era-vargas.ts','República e transformações políticas'),('EF09HI03','unidade-4/aula-02-republica-pos-abolicao.ts','Protagonismo negro na República'),('EF09HI04','unidade-4/aula-02-republica-pos-abolicao.ts','Povos indígenas na República'),('EF09HI05','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Urbanização e modernização'),('EF09HI06','unidade-4/aula-01-era-vargas.ts','Era Vargas e mundo do trabalho'),('EF09HI07','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Diversidade e cidadania'),('EF09HI08','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Direitos das mulheres'),('EF09HI09','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Questões indígena e negra contemporâneas'),
('EF09HI10','unidade-1/aula-01-primeira-guerra-russa.ts','Primeira Guerra Mundial'),('EF09HI11','unidade-1/aula-01-primeira-guerra-russa.ts','Revolução Russa e seus desdobramentos'),('EF09HI12','unidade-2/aula-01-crise-totalitarismo.ts','Crise de 1929 e totalitarismos'),('EF09HI13','unidade-3/aula-01-segunda-guerra-holocausto.ts','Segunda Guerra Mundial e genocídio nazista'),('EF09HI14','unidade-3/aula-02-colonialismo-resistencias.ts','Colonialismo e resistências na África e Ásia'),('EF09HI15','unidade-7/aula-07-onu-organismos.ts','Organização das Nações Unidas'),('EF09HI16','unidade-7/aula-07-onu-organismos.ts','Organismos multilaterais e ordem mundial'),
('EF09HI17','unidade-6/aula-07-brasil-1946-1964.ts','Brasil entre 1946 e 1964'),('EF09HI18','unidade-6/aula-07-brasil-1946-1964.ts','Transformações sociais e culturais no Brasil'),('EF09HI19','unidade-6/aula-02-golpe-memoria-justica.ts','Golpe de 1964, memória e justiça'),('EF09HI20','unidade-6/aula-03-resistencias-reorganizacao.ts','Resistências e reorganização democrática'),('EF09HI21','unidade-6/aula-04-indigenas-quilombolas-desenvolvimentismo.ts','Indígenas, quilombolas e desenvolvimentismo'),('EF09HI22','unidade-6/aula-05-diretas-ja.ts','Diretas Já e redemocratização'),('EF09HI23','unidade-6/aula-06-cf88-direitos.ts','Constituição de 1988 e direitos'),
('EF09HI24','unidade-7/aula-02-brasil-pos-1989.ts','Brasil pós-1989'),('EF09HI25','unidade-7/aula-03-sociedade-civil.ts','Sociedade civil e participação'),('EF09HI26','unidade-7/aula-04-violencia-marginalizados.ts','Direitos humanos e populações marginalizadas'),('EF09HI27','unidade-7/aula-05-brasil-globalizacao.ts','Brasil e globalização'),('EF09HI28','unidade-5/aula-02-tensoes-dentro-dos-blocos.ts','Tensões dentro dos blocos da Guerra Fria'),('EF09HI29','unidade-5/aula-03-ditaduras-america-latina.ts','Ditaduras na América Latina'),('EF09HI30','unidade-5/aula-03-ditaduras-america-latina.ts','Contestações e resistências latino-americanas'),('EF09HI31','unidade-5/aula-04-descolonizacao.ts','Descolonização da África e Ásia'),
('EF09HI32','unidade-7/aula-01-globalizacao-digital.ts','Globalização e mudanças sociais'),('EF09HI33','unidade-7/aula-01-globalizacao-digital.ts','Era digital, informação e trabalho'),('EF09HI34','unidade-7/aula-06-neoliberalismo.ts','Políticas neoliberais e globalização'),('EF09HI35','unidade-7/aula-08-terrorismo-migracoes.ts','Terrorismo, migrações e conflitos contemporâneos'),('EF09HI36','unidade-7/aula-09-diversidades.ts','Diversidades e identidades no século XXI')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-9ano/'||rel source_key,title,'Analisar criticamente '||lower(title)||' usando fontes, cronologia, causalidade, conceitos, memória e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize o tempo presente','content',jsonb_build_array('Diferencie democracia, autoritarismo, totalitarismo, golpe, revolução, genocídio, colonialismo e terrorismo sem banalizar ou igualar fenômenos distintos.','Guerras, genocídios, ditaduras, perseguições e violações de direitos devem ser tratados de modo informativo, não gráfico e adequado à idade; não exiba imagens chocantes nem proponha encenação de violência, opressão ou sofrimento.','Inclua protagonismo negro, indígena, quilombola, feminino, juvenil, trabalhador, migrante e de pessoas com deficiência sem reduzir grupos a vítimas.')),
 jsonb_build_object('heading','Verificar fontes, memória e desinformação','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de documentos, imprensa, propaganda, estatísticas, testemunhos publicados e mídias digitais.','Diferencie fato documentado, interpretação historiográfica, memória, opinião, propaganda e desinformação; verifique afirmações controversas em fontes institucionais e pesquisas reconhecidas.','Analise causas múltiplas, escalas local e global, continuidades, rupturas, responsabilidades institucionais e resistências, sem falsa equivalência entre evidência e negação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida fontes e textos em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, gravada, digitada, escrita ou com tecnologia assistiva.','Não solicite posição partidária, experiência de violência, discriminação, migração, religião, raça ou identidade pessoal do estudante.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco processos usando contexto, cronologia, causalidade, conceito, fonte verificada, perspectiva e limite interpretativo.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e verificar fontes','instruction','Identifique período, escala, grupos, autoria, finalidade, linguagem, evidências, silêncios e limites.','activity','Compare fontes e classifique fato documentado, interpretação, memória, propaganda ou opinião.','support','Glossário, linha do tempo, mapa, fonte ampliada e exemplo resolvido.'),jsonb_build_object('title','2. Explicar processos e disputas','instruction','Relacione causas, estruturas, decisões, resistências, mudanças, permanências e consequências.','activity','Monte matriz causal, mapa de fluxos ou cronologia de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar e revisar','instruction','Formule argumento com evidências verificadas, reconheça agência, outra interpretação e limites sem falsa equivalência.','activity','Cite fontes, confronte contraexemplo e revise a conclusão.','support','Resposta oral, apontada, mapeada, diagramada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa e verifica fontes, perspectivas e limites.'),jsonb_build_object('page',2,'answer','Explica processo por causas múltiplas e evidências.'),jsonb_build_object('page',3,'answer','Argumento verificável, contextualizado e aberto a revisão.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados pessoais e políticos sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'source_verification',true,'anti_disinformation',true,'marginalized_groups_agency',true,'memory_and_justice',true,'non_graphic',true,'no_violence_roleplay',true,'no_shocking_media',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-9ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
