BEGIN;
-- Biblioteca Inclusiva · Geografia do 1º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF01GE01','src/escola-brilha/data/EF01GE01.ts','Comparando os lugares onde vivemos','Descrever características de lugares de vivência por imagens e cenários fictícios.'),
('EF01GE02','src/escola-brilha/data/EF01GE02.ts','Brincadeiras de tempos e lugares diferentes','Comparar jogos e brincadeiras de diferentes épocas e lugares sem hierarquizar culturas.'),
('EF01GE03','src/escola-brilha/data/EF01GE03.ts','Como usamos os espaços públicos','Identificar usos e possibilidades de participação em espaços públicos acessíveis.'),
('EF01GE04','src/escola-brilha/data/EF01GE04.ts','Regras para conviver bem','Discutir acordos de convivência em diferentes espaços com inclusão e segurança.'),
('EF01GE05','src/escola-brilha/data/EF01GE05.ts','Ritmos da natureza','Observar ritmos naturais e relacioná-los a atividades cotidianas diversas.'),
('EF01GE06','src/escola-brilha/data/EF01GE06.ts','Moradias e materiais','Comparar tipos e materiais de moradias sem associá-los a valor, mérito ou condição pessoal.'),
('EF01GE07','src/escola-brilha/data/EF01GE07.ts','Trabalhos e vida em comunidade','Reconhecer diferentes trabalhos e sua contribuição sem estereótipos de gênero ou classe.'),
('EF01GE08','src/escola-brilha/data/EF01GE08.ts','Mapas e trajetos','Criar e ler mapas simples de cenários fictícios usando símbolos, legendas e trajetos.'),
('EF01GE09','src/escola-brilha/data/EF01GE09.ts','Referenciais espaciais','Usar referenciais espaciais por diferentes formas de percepção, orientação e movimento.'),
('EF01GE10','src/escola-brilha/data/EF01GE10.ts','O lugar muda com as épocas','Comparar mudanças e permanências em paisagens por imagens de diferentes tempos.'),
('EF01GE11','src/escola-brilha/data/EF01GE11.ts','Tempo, estações e cuidados','Relacionar condições do tempo a escolhas cotidianas seguras, considerando variações regionais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare um espaço seguro','content',jsonb_build_array('Use mapas, trajetos, casas, quartos, bairros e rotinas fictícios; nunca peça endereço, geolocalização, fotografia da moradia, trajeto real, planta do quarto ou horário da criança.','Escolha imagens de moradias, trabalhos, corpos, famílias, culturas e modos de deslocamento diversos sem classificar um tipo como melhor.')),
 jsonb_build_object('heading','Ensine a observar e representar','content',jsonb_build_array('Modele lugar, paisagem, posição, direção, distância aproximada, trajeto, símbolo e legenda com objetos e imagens.','Compare elemento natural e construído, uso do espaço, mudança e permanência sem culpar indivíduos por problemas coletivos.','Referenciais corporais devem admitir diferentes lateralidades, mobilidades, percepções visuais e formas de orientação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, maquete, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não avalie coordenação motora, visão, leitura ou fala como se fossem compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Localiza, compara ou representa quatro de cinco situações usando referência espacial ou evidência da paisagem.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar o lugar','instruction','Identifique elementos, usos, pessoas, condições e pistas em imagem ou maquete fictícia.','activity','Separe o que observa do que imagina e escolha uma pergunta.','support','Vocabulário visual, exploração tátil opcional e exemplo resolvido.'),jsonb_build_object('title','2. Localizar e comparar','instruction','Use posição, direção, trajeto, símbolo, legenda, mudança ou permanência.','activity','Monte mapa, sequência, maquete ou quadro de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar ou representar','instruction','Mostre a relação entre elementos, pessoas, natureza e usos do espaço.','activity','Apresente conclusão por fala, cartões, mapa, maquete, desenho ou escrita.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos e uma pista observável.'),jsonb_build_object('page',2,'answer','Localiza ou compara usando referência coerente.'),jsonb_build_object('page',3,'answer','Representação ou explicação ligada às evidências.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre localização ou rotina real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'housing_dignity',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 2º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF02GE01','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-01-lugares-onde-vivemos.ts','Convivência, histórias e migrações','Comparar costumes, relações e histórias de pessoas em diferentes lugares com respeito às origens e aos deslocamentos.'),
('EF02GE02','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-06-costumes-tradicoes.ts','Costumes e tradições da comunidade','Reconhecer costumes e tradições de diferentes grupos sem hierarquizar culturas ou exigir relato familiar.'),
('EF02GE03','src/escola-brilha/curso-v4/geografia-2ano/unidade-2/aula-03-transportes-e-comunicacao.ts','Transportes e comunicação','Comparar meios de transporte e comunicação, seus usos e mudanças, considerando acessibilidade.'),
('EF02GE04','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-03-trabalho-campo-cidade.ts','Trabalho no campo e na cidade','Relacionar atividades e trabalhos de diferentes lugares sem estereótipos de gênero, território ou condição social.'),
('EF02GE05','src/escola-brilha/curso-v4/geografia-2ano/unidade-5/aula-01-maquina-do-tempo-da-paisagem.ts','Mudanças e permanências nas paisagens','Analisar mudanças e permanências por imagens de tempos diferentes, distinguindo ação humana e processos naturais.'),
('EF02GE06','src/escola-brilha/curso-v4/geografia-2ano/unidade-2/aula-05-dia-noite-atividades.ts','Atividades do dia e da noite','Relacionar atividades sociais a diferentes períodos do dia sem apresentar uma única rotina como padrão.'),
('EF02GE07','src/escola-brilha/curso-v4/geografia-2ano/unidade-3/aula-01-do-campo-pra-mesa.ts','Campo, cidade, transportes e comunicação','Explicar conexões entre campo e cidade pela produção, circulação, transporte e comunicação.'),
('EF02GE08','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-02-seguranca-no-transito.ts','Riscos e cuidados nos lugares','Identificar situações de risco em cenários ilustrados e propor cuidados coletivos e acessíveis.'),
('EF02GE09','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-06-visoes-representacoes.ts','Visões e representações dos objetos','Comparar objetos e lugares vistos de cima, de frente e de lado com apoio visual ou tátil.'),
('EF02GE10','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-07-localizacao-referencias.ts','Localização e pontos de referência','Aplicar referenciais espaciais em mapas e maquetes fictícios, admitindo diferentes lateralidades e mobilidades.'),
('EF02GE11','src/escola-brilha/curso-v4/geografia-2ano/unidade-5/aula-05-solo-agua.ts','Solo e água: usos e cuidados','Reconhecer usos do solo e da água e propor formas coletivas de cuidado em diferentes contextos.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare o cenário protegido','content',jsonb_build_array('Use município, bairro, moradia, trajeto, rotina e história familiar fictícios; nunca peça endereço, geolocalização, fotografia da moradia, caminho real, horário ou história migratória pessoal da criança.','Apresente moradias, culturas, famílias, trabalhos e modos de deslocamento diversos sem classificar um como superior.')),
 jsonb_build_object('heading','Modele o raciocínio geográfico','content',jsonb_build_array('Ensine a observar pistas, localizar, comparar, relacionar e justificar com imagem, mapa, maquete, sequência temporal ou objetos.','Diferencie fato observado de hipótese e mostre relações entre pessoas, lugares, natureza, trabalho, transporte e comunicação.','Referenciais espaciais devem admitir diferentes lateralidades, percepções visuais, mobilidades e formas de orientação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, reduza estímulos concorrentes, modele um exemplo e use pistas graduadas.','Aceite fala, apontamento, cartões, objetos, maquete, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não avalie memória, leitura, visão, fala ou coordenação motora como se fossem compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações usando ao menos uma pista espacial, temporal, ambiental ou social coerente.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e identificar','instruction','Observe imagem, objeto, mapa ou maquete fictícia e identifique pistas relevantes.','activity','Separe o que pode ser observado do que ainda precisa ser investigado.','support','Vocabulário visual, exploração tátil opcional e exemplo resolvido.'),jsonb_build_object('title','2. Localizar, ordenar ou comparar','instruction','Use posição, visão, sequência temporal, mudança, permanência ou conexão entre lugares.','activity','Organize cartões, símbolos, objetos ou trechos de mapa relacionados a '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Relacionar e explicar','instruction','Explique a relação entre pessoas, natureza, trabalho, circulação e usos do espaço.','activity','Apresente uma conclusão e a pista que a sustenta.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos e uma pista observável.'),jsonb_build_object('page',2,'answer','Localiza, ordena ou compara com referência coerente.'),jsonb_build_object('page',3,'answer','Explica uma relação apoiada em evidência.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre localização, rota, rotina ou história familiar real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_personal_migration_disclosure',true,'housing_dignity',true,'cultural_respect',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-2ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 3º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF03GE01','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-01-nosso-municipio.ts','Cidade, campo e diversidade cultural','Comparar aspectos culturais de grupos do campo e da cidade sem hierarquizar modos de vida.'),
('EF03GE02','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-02-marcas-dos-vovos.ts','Marcas culturais nas paisagens','Identificar contribuições culturais presentes em paisagens e comunidades sem exigir história familiar pessoal.'),
('EF03GE03','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-03-modos-de-vida.ts','Modos de vida tradicionais','Reconhecer modos de vida de povos e comunidades tradicionais com respeito, contexto e sem estereótipos.'),
('EF03GE04','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-04-paisagens-em-transformacao.ts','Paisagens naturais e transformadas','Explicar mudanças nas paisagens por evidências, diferenciando elementos naturais e ações humanas.'),
('EF03GE05','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-02-de-onde-vem.ts','Produtos, matéria-prima e trabalho','Relacionar produtos a matérias-primas, trabalho e circulação em cadeias simples de produção.'),
('EF03GE06','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-03-mapa-vivo.ts','Representações cartográficas','Interpretar diferentes representações de paisagens usando ponto de vista, símbolos e organização espacial.'),
('EF03GE07','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-04-legendas-simbolos.ts','Legendas e símbolos nos mapas','Ler e elaborar legendas com símbolos acessíveis, distinguíveis também sem depender apenas de cor.'),
('EF03GE08','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-05-producao-consumo-lixo.ts','Produção, consumo e resíduos','Relacionar produção, consumo e resíduos e propor ações coletivas de redução, reutilização e descarte correto.'),
('EF03GE09','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-06-usos-da-agua.ts','Usos e importância da água','Investigar usos da água no campo e na cidade por dados e cenários, sem expor hábitos domésticos pessoais.'),
('EF03GE10','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-07-cuidados-com-agua.ts','Cuidados com a água','Comparar usos responsáveis da água e formular soluções coletivas adequadas a diferentes contextos.'),
('EF03GE11','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-08-impactos-ambientais.ts','Impactos ambientais no campo e na cidade','Analisar impactos ambientais e responsabilidades compartilhadas sem culpabilizar indivíduos ou comunidades.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes e cenários protegidos','content',jsonb_build_array('Use municípios, comunidades, moradias, mapas, hábitos de consumo e histórias familiares fictícios; nunca peça endereço, geolocalização, rota, foto da moradia, conta de água, origem familiar ou hábitos domésticos pessoais.','Selecione fontes que representem povos, comunidades tradicionais, campo, cidade, trabalhos e condições de vida com dignidade e contexto.')),
 jsonb_build_object('heading','Modele a investigação','content',jsonb_build_array('Ensine a observar, formular hipótese, localizar evidência, comparar fontes e justificar uma conclusão.','Trabalhe paisagem, território, representação, cadeia produtiva, consumo, água e impacto ambiental conectando causas, consequências e responsabilidades coletivas.','Em mapas e legendas, combine cor com forma, textura, contorno, texto ou padrão; ofereça versão tátil quando possível.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida a tarefa em blocos curtos, antecipe termos, modele um exemplo e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, objetos, maquete, mapa, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não confunda velocidade, memória, leitura, fala, visão ou coordenação motora com compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e justifica ao menos três respostas com evidência espacial, ambiental, cultural ou produtiva.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e perguntar','instruction','Observe mapa, imagem, objeto, sequência ou tabela de um cenário fictício.','activity','Identifique duas pistas e formule uma pergunta investigável.','support','Vocabulário visual, leitura mediada, ampliação e exploração tátil opcional.'),jsonb_build_object('title','2. Comparar e relacionar','instruction','Compare lugares, tempos, representações, etapas produtivas, usos de recursos ou impactos.','activity','Organize cartões, mapa, quadro causa-consequência ou cadeia relacionada a '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Concluir com evidência','instruction','Escolha uma conclusão e indique a pista que a sustenta.','activity','Explique uma relação e proponha uma ação coletiva quando pertinente.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica duas pistas pertinentes e uma pergunta possível.'),jsonb_build_object('page',2,'answer','Compara ou organiza relações de modo coerente.'),jsonb_build_object('page',3,'answer','Conclusão sustentada por evidência; solução coletiva viável quando solicitada.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, origem familiar ou hábitos domésticos reais.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','map','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_family_origin_disclosure',true,'no_household_consumption_disclosure',true,'housing_dignity',true,'cultural_respect',true,'traditional_communities_respect',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-3ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 4º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF04GE01','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-02-culturas-brasileiras.ts','Território brasileiro e diversidade cultural','Reconhecer a formação cultural brasileira com respeito aos diferentes povos, grupos e territórios.'),
('EF04GE02','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-01-populacao-e-migracoes.ts','População e migrações','Analisar fluxos populacionais e contribuições culturais sem exigir origem ou trajetória familiar pessoal.'),
('EF04GE03','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-03-poder-publico-participacao.ts','Poder público e participação social','Distinguir funções públicas e formas seguras e coletivas de participação cidadã em situações fictícias.'),
('EF04GE04','src/escola-brilha/curso-v4/geografia-4ano/unidade-3/aula-02-campo-cidade.ts','Campo e cidade interligados','Explicar relações de interdependência entre campo e cidade por fluxos de pessoas, produtos e serviços.'),
('EF04GE05','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-02-estados-e-df.ts','Unidades político-administrativas','Localizar município, unidade federativa, região e país em mapas de escalas diferentes.'),
('EF04GE06','src/escola-brilha/curso-v4/geografia-4ano/unidade-4/aula-02-territorios-tradicionais.ts','Territórios indígenas e quilombolas','Reconhecer territórios indígenas e quilombolas, seus direitos e sua diversidade sem generalizações ou estereótipos.'),
('EF04GE07','src/escola-brilha/curso-v4/geografia-4ano/unidade-5/aula-01-trabalho-e-economia.ts','Trabalho e atividades econômicas','Comparar atividades econômicas e tipos de trabalho sem hierarquização social ou estereótipos de gênero.'),
('EF04GE08','src/escola-brilha/curso-v4/geografia-4ano/unidade-5/aula-02-producao-circulacao-consumo.ts','Produção, circulação e consumo','Representar etapas e fluxos entre produção, circulação e consumo, incluindo efeitos socioambientais.'),
('EF04GE09','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-03-rosa-dos-ventos.ts','Direções e localização','Aplicar direções cardeais em mapas e grades fictícias com alternativas visuais, táteis e corporais acessíveis.'),
('EF04GE10','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-04-ler-o-mapa.ts','Elementos constitutivos dos mapas','Interpretar título, legenda, orientação, escala e fonte em mapas que não dependam apenas de cores.'),
('EF04GE11','src/escola-brilha/curso-v4/geografia-4ano/unidade-3/aula-01-relevo-e-rios.ts','Paisagens naturais e antrópicas','Comparar relevo, hidrografia e transformações das paisagens usando evidências cartográficas e visuais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','4º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Selecione fontes seguras e contextualizadas','content',jsonb_build_array('Use mapas, municípios, trajetórias migratórias, problemas públicos e cadeias produtivas fictícios; nunca peça endereço, geolocalização, rota, origem familiar, documento, fotografia da moradia ou posicionamento político da criança.','Apresente povos indígenas e comunidades quilombolas no presente, em sua diversidade, com direitos territoriais e protagonismo; evite fantasias, caricaturas e generalizações.')),
 jsonb_build_object('heading','Modele a análise geográfica','content',jsonb_build_array('Ensine a formular pergunta, verificar título e fonte, localizar evidências, comparar escalas e justificar conclusões.','Conecte território, população, campo e cidade, trabalho, produção, circulação, consumo, relevo e rios por relações de causa, consequência e interdependência.','Em mapas, combine cor com texto, forma, textura, contorno e padrão; disponibilize orientação verbal ou versão tátil quando necessário.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe conceitos, divida mapas complexos em camadas, dê uma instrução por vez e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, objetos, mapa, maquete, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala ou coordenação motora como medida isolada de compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com elemento cartográfico, territorial, econômico ou ambiental pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler a fonte','instruction','Identifique título, fonte, escala, legenda, orientação, lugar e período quando estiverem disponíveis.','activity','Registre duas informações observáveis e uma dúvida sobre o material.','support','Leitura mediada, ampliação, camadas reduzidas e exploração tátil opcional.'),jsonb_build_object('title','2. Comparar e conectar','instruction','Compare mapas, paisagens, territórios, fluxos ou situações sociais de um cenário fictício.','activity','Monte quadro, mapa, esquema de fluxo ou relação causa-consequência sobre '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com evidência','instruction','Escolha uma conclusão, indique a evidência e reconheça limites da fonte.','activity','Explique a relação e proponha ação coletiva quando pertinente.','support','Resposta oral, apontada, tátil, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Localiza elementos da fonte e duas informações verificáveis.'),jsonb_build_object('page',2,'answer','Compara ou conecta elementos com coerência espacial.'),jsonb_build_object('page',3,'answer','Conclusão sustentada por evidência e com limite reconhecido.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, origem familiar ou opinião política real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','map','model','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_family_origin_disclosure',true,'no_political_opinion_collection',true,'cultural_respect',true,'indigenous_quilombola_present_day_respect',true,'territorial_rights_context',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-4ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 5º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF05GE01','src/escola-brilha/curso-v4/geografia-5ano/unidade-1/aula-01-populacao-crescimento.ts','Dinâmica populacional','Interpretar crescimento, distribuição e características populacionais por dados contextualizados.'),
('EF05GE02','src/escola-brilha/curso-v4/geografia-5ano/unidade-1/aula-02-migracoes-internas.ts','Migrações internas e diversidade','Analisar migrações internas e diversidade cultural sem exigir trajetória familiar ou origem pessoal.'),
('EF05GE03','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-01-urbanizacao.ts','Urbanização e funções das cidades','Distinguir funções e características de cidades de diferentes tamanhos sem hierarquizar seus habitantes.'),
('EF05GE04','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-02-campo-cidade-conectados.ts','Campo e cidade conectados','Explicar interdependências entre campo e cidade por fluxos de produtos, pessoas, informação e serviços.'),
('EF05GE05','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-03-trabalho-tecnologia.ts','Trabalho e tecnologia','Analisar mudanças no trabalho provocadas pela tecnologia, considerando benefícios, desigualdades e acessibilidade.'),
('EF05GE06','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-04-transportes-comunicacoes.ts','Transportes e comunicações','Comparar redes de transporte e comunicação e seus efeitos na integração territorial e no acesso a serviços.'),
('EF05GE07','src/escola-brilha/curso-v4/geografia-5ano/unidade-4/aula-02-impactos-energia.ts','Fontes de energia e impactos','Comparar fontes de energia por disponibilidade, usos e impactos socioambientais sem soluções simplistas.'),
('EF05GE08','src/escola-brilha/curso-v4/geografia-5ano/unidade-3/aula-03-paisagens-no-tempo.ts','Transformações das paisagens urbanas','Comparar paisagens urbanas de tempos diferentes e relacionar mudanças a processos sociais e econômicos.'),
('EF05GE09','src/escola-brilha/curso-v4/geografia-5ano/unidade-3/aula-01-mapas-tematicos.ts','Mapas temáticos e diferenças regionais','Interpretar mapas temáticos, legendas e dados regionais usando símbolos que não dependam apenas de cor.'),
('EF05GE10','src/escola-brilha/curso-v4/geografia-5ano/unidade-5/aula-02-qualidade-ambiental.ts','Qualidade ambiental urbana','Analisar indicadores ambientais urbanos e comparar propostas coletivas de melhoria e acessibilidade.'),
('EF05GE11','src/escola-brilha/curso-v4/geografia-5ano/unidade-6/aula-01-consumo-residuos.ts','Consumo, resíduos e tecnologia','Relacionar consumo, geração de resíduos e soluções tecnológicas sem expor renda ou hábitos familiares.'),
('EF05GE12','src/escola-brilha/curso-v4/geografia-5ano/unidade-7/aula-02-participacao-ambiental.ts','Participação e soluções para a cidade','Avaliar propostas para problemas socioambientais e planejar participação cidadã segura em cenários fictícios.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare dados e cenários protegidos','content',jsonb_build_array('Use cidades, trajetórias migratórias, perfis populacionais, consumo, trabalho e problemas ambientais fictícios ou dados públicos agregados; nunca peça endereço, geolocalização, renda, conta doméstica, ocupação dos responsáveis, hábitos de consumo, origem ou trajetória familiar da criança.','Contextualize desigualdades como fenômenos sociais e territoriais; não associe condição econômica, lugar de origem, deficiência ou tipo de trabalho a mérito pessoal.')),
 jsonb_build_object('heading','Modele a análise crítica','content',jsonb_build_array('Ensine a verificar título, fonte, data, escala, legenda, unidade de medida e recorte territorial antes de interpretar.','Compare dados e mapas, identifique padrões, conecte causas e consequências e diferencie evidência, inferência e opinião.','Em propostas ambientais, considere impacto, viabilidade, responsabilidade pública e coletiva, acessibilidade e possíveis efeitos não previstos.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe conceitos, divida gráficos e mapas em camadas, dê uma instrução por vez e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala, cálculo ou coordenação motora como medida isolada da compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com dado, elemento cartográfico ou relação territorial pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Verificar a fonte','instruction','Localize título, fonte, data, legenda, escala, unidade e recorte quando disponíveis.','activity','Registre duas informações verificáveis e uma limitação do material.','support','Leitura mediada, ampliação, tabela simplificada e descrição verbal ou tátil.'),jsonb_build_object('title','2. Identificar padrões e relações','instruction','Compare dados, mapas, paisagens, redes ou fluxos de cenários fictícios.','activity','Monte quadro, gráfico acessível, mapa ou cadeia causa-consequência sobre '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Avaliar e argumentar','instruction','Apresente uma conclusão, cite a evidência e considere outra explicação possível.','activity','Compare propostas por impacto, viabilidade, equidade e responsabilidade coletiva.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, duas informações e uma limitação.'),jsonb_build_object('page',2,'answer','Reconhece padrão ou relação sem extrapolar os dados.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidência e avaliação equilibrada da proposta.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, renda, consumo ou trajetória familiar real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_income_collection',true,'no_household_consumption_disclosure',true,'no_family_origin_disclosure',true,'no_parent_occupation_collection',true,'inequality_contextualized',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-5ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 6º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF06GE01','Paisagens e transformações','Comparar paisagens em tempos distintos e identificar mudanças, permanências e agentes transformadores.'),
('EF06GE02','Paisagens de diferentes sociedades','Analisar transformações territoriais realizadas por diferentes sociedades com respeito a conhecimentos e direitos.'),
('EF06GE03','Movimentos da Terra e dinâmica climática','Relacionar movimentos da Terra, circulação atmosférica e ritmos climáticos usando modelos e evidências.'),
('EF06GE04','Ciclo da água e bacias hidrográficas','Explicar ciclo da água, escoamento e bacias relacionando cobertura vegetal, solo e ações humanas.'),
('EF06GE05','Clima e circulação atmosférica','Distinguir tempo e clima e interpretar fatores e elementos climáticos em diferentes escalas.'),
('EF06GE06','Geodinâmica e tectônica de placas','Explicar processos internos da Terra e sua relação com relevo e distribuição de fenômenos geológicos.'),
('EF06GE07','Paisagens climatobotânicas','Relacionar clima, relevo, solo, água e vegetação em grandes conjuntos de paisagens mundiais.'),
('EF06GE08','Escalas e distâncias','Aplicar escala gráfica e numérica para comparar distâncias e níveis de detalhamento cartográfico.'),
('EF06GE09','Curvas de nível e perfil topográfico','Interpretar curvas de nível e perfis topográficos por altitude, declividade e forma do relevo.'),
('EF06GE10','Uso do solo e da água','Analisar transformações do solo e da água no campo e na cidade por atividades econômicas e infraestrutura.'),
('EF06GE11','Sociedade, natureza e biodiversidade','Explicar interações entre componentes naturais, biodiversidade e ações sociais em diferentes escalas.'),
('EF06GE12','Consumo de água','Comparar usos da água por setor, território e tecnologia sem reduzir a questão ao consumo individual.'),
('EF06GE13','Práticas humanas e consequências ambientais','Avaliar consequências ambientais de práticas humanas, grupos envolvidos e alternativas sustentáveis.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-6ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes verificáveis e seguras','content',jsonb_build_array('Use mapas, imagens, modelos, séries históricas e dados públicos agregados; cenários locais devem ser fictícios e nunca solicitar endereço, geolocalização, rota, conta de água, consumo doméstico, local de trabalho familiar ou fotografia da moradia.','Contextualize povos originários, comunidades e atividades econômicas com diversidade, protagonismo, direitos e fontes confiáveis, evitando generalizações.')),
 jsonb_build_object('heading','Modele o raciocínio científico-geográfico','content',jsonb_build_array('Comece por pergunta, hipótese e previsão; identifique escala espacial e temporal; compare evidências; revise a hipótese e comunique a conclusão.','Diferencie correlação de causalidade e fenômeno natural de risco socialmente construído; não apresente desastre ou impacto como culpa inevitável de moradores.','Em mapas, gráficos, diagramas e modelos, combine cor com rótulo, forma, textura, contorno ou padrão e ofereça descrição textual ou tátil.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe vocabulário, segmente textos densos, revele mapas e gráficos em camadas e ofereça exemplo resolvido e pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, modelo, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala, cálculo ou coordenação motora como medida isolada do domínio conceitual.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com evidência, escala e relação geográfica adequadas.')))),
jsonb_build_array(jsonb_build_object('title','1. Formular e prever','instruction','Leia a questão, defina conceitos, escala e evidências necessárias.','activity','Registre hipótese e previsão antes de observar os dados de '||lower(title)||'.','support','Glossário visual, texto segmentado, leitura mediada e organizador de hipótese.'),jsonb_build_object('title','2. Analisar evidências','instruction','Compare mapa, gráfico, imagem, modelo ou dados e procure padrões e exceções.','activity','Construa tabela, perfil, mapa, diagrama ou cadeia causal adequada ao problema.','support','Camadas de informação, exemplo resolvido e pistas graduadas.'),jsonb_build_object('title','3. Concluir e revisar','instruction','Responda à questão, cite evidências, revise a hipótese e reconheça limites.','activity','Explique a relação e avalie alternativas por impacto, escala, viabilidade e equidade.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese pertinente, previsão verificável e escala identificada.'),jsonb_build_object('page',2,'answer','Representação coerente com padrões, exceções e unidades preservadas.'),jsonb_build_object('page',3,'answer','Conclusão sustentada, hipótese revisada e limite reconhecido.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização ou consumo doméstico real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','model','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_local_scenarios',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_household_consumption_disclosure',true,'no_family_workplace_collection',true,'indigenous_community_rights_context',true,'disaster_risk_contextualized',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-6ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 7º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF07GE01','Formação territorial do Brasil','Analisar a formação territorial brasileira por mapas, tratados e processos históricos de modo crítico e não gráfico.'),
('EF07GE02','Fluxos econômicos, populacionais e território','Relacionar fluxos de mercadorias, pessoas e capitais à organização do território brasileiro.'),
('EF07GE03','Territorialidades e direitos','Reconhecer territorialidades, direitos e protagonismo de povos indígenas, quilombolas e comunidades tradicionais.'),
('EF07GE04','Dinâmica demográfica','Interpretar indicadores, pirâmides etárias e transição demográfica usando dados públicos agregados.'),
('EF07GE05','Do mercantilismo ao capitalismo','Comparar processos econômicos históricos e sua influência na organização territorial e nas desigualdades.'),
('EF07GE06','Produção, circulação e consumo','Analisar redes de produção, circulação e consumo e seus efeitos sociais, econômicos e ambientais.'),
('EF07GE07','Redes de transporte e comunicação','Avaliar como redes de transporte e comunicação integram territórios e distribuem acessos de modo desigual.'),
('EF07GE08','Industrialização e urbanização','Relacionar industrialização, urbanização, metropolização e desigualdades socioespaciais no Brasil.'),
('EF07GE09','Mapas temáticos do Brasil','Interpretar mapas temáticos brasileiros por título, fonte, legenda, escala, recorte e variável representada.'),
('EF07GE10','Gráficos e indicadores','Ler e comparar gráficos e indicadores socioeconômicos sem confundir associação estatística com causalidade.'),
('EF07GE11','Complexos regionais e diversidade','Analisar diversidade natural, econômica e cultural das regiões sem reduzir territórios a estereótipos.'),
('EF07GE12','Unidades de conservação','Distinguir tipos e objetivos de unidades de conservação e avaliar proteção ambiental e participação social.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-7ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise territorial — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes seguras e contextualizadas','content',jsonb_build_array('Use mapas históricos, mapas temáticos, gráficos e dados públicos agregados; nunca peça endereço, geolocalização, renda, origem familiar, migração pessoal, autodeclaração étnica, opinião política ou dados demográficos da turma.','Ao tratar expansão territorial, colonização, conflitos e regimes políticos, use linguagem histórica, informativa e não gráfica, explicando direitos, agentes, disputas e consequências sem simulação imersiva.')),
 jsonb_build_object('heading','Garanta respeito territorial e regional','content',jsonb_build_array('Apresente povos indígenas, quilombolas e comunidades tradicionais no presente, com diversidade, protagonismo e direitos; não solicite que estudante represente identidade que não é a sua.','Evite reduzir Norte, Nordeste, áreas rurais, periferias ou qualquer população a pobreza, atraso, clima ou um único costume.')),
 jsonb_build_object('heading','Modele a análise','content',jsonb_build_array('Verifique autoria, fonte, data, escala, recorte, variável e método; compare materiais e identifique ausências ou interesses na representação.','Relacione território, população, economia, redes e ambiente; diferencie correlação, causalidade, dado absoluto, proporção e taxa.','Mapas e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual ou tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e aceite pausas e pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, esquema, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões com evidência, escala e contexto adequados.')))),
jsonb_build_array(jsonb_build_object('title','1. Interrogar a fonte','instruction','Identifique autoria, data, escala, recorte, variável, método e contexto.','activity','Registre duas evidências, uma ausência e uma pergunta investigável sobre '||lower(title)||'.','support','Glossário, texto segmentado, leitura mediada e fonte ampliada ou descrita.'),jsonb_build_object('title','2. Comparar e explicar','instruction','Cruze mapa, gráfico, texto ou linha do tempo e procure padrões, contrastes e exceções.','activity','Construa quadro comparativo, mapa, gráfico acessível ou cadeia causal.','support','Exemplo resolvido, informação em camadas e pistas graduadas.'),jsonb_build_object('title','3. Argumentar e avaliar','instruction','Apresente conclusão, evidências, limite e explicação alternativa.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade e responsabilidade pública.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, duas evidências e uma ausência relevante.'),jsonb_build_object('page',2,'answer','Compara materiais e explica padrão sem extrapolar os dados.'),jsonb_build_object('page',3,'answer','Argumento sustentado, limite reconhecido e proposta avaliada por critérios.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, localização, renda ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_income_collection',true,'no_family_origin_disclosure',true,'no_ethnicity_collection',true,'no_political_opinion_collection',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'indigenous_quilombola_present_day_respect',true,'territorial_rights_context',true,'regional_anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-7ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 8º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF08GE01','Regionalização e distribuição populacional','Interpretar regionalizações e distribuição populacional mundial por mapas e dados agregados.'),
('EF08GE02','Ordem mundial e regionalizações','Comparar critérios de regionalização, relações de poder e mudanças na ordem mundial.'),
('EF08GE03','Dinâmica demográfica mundial','Analisar indicadores e deslocamentos populacionais sem coletar dados pessoais ou familiares.'),
('EF08GE04','Migrações, refúgio e xenofobia','Explicar migrações e refúgio e combater xenofobia com abordagem informativa, não gráfica e baseada em direitos.'),
('EF08GE05','Globalização e divisão do trabalho','Analisar globalização e divisão internacional do trabalho por redes, agentes e desigualdades.'),
('EF08GE06','Produção e trabalho no mundo','Relacionar cadeias globais, trabalho, tecnologia e distribuição desigual de valor.'),
('EF08GE07','Corporações e organizações econômicas','Avaliar a influência territorial de corporações e organismos econômicos internacionais.'),
('EF08GE08','Integração mundial e tecnologia','Relacionar transporte e comunicação a fluxos globais de capital, mercadorias e informação.'),
('EF08GE09','Recursos naturais e geopolítica','Analisar recursos estratégicos, cooperação e disputas sem simular conflitos ou naturalizar violência.'),
('EF08GE10','Estados Unidos e poder global','Examinar dimensões econômica, política, tecnológica e cultural do poder dos Estados Unidos.'),
('EF08GE11','Relações econômicas e influência','Comparar redes de influência e dependência usando fontes múltiplas e escalas distintas.'),
('EF08GE12','Integração americana','Comparar objetivos e limites de blocos e organismos de integração nas Américas.'),
('EF08GE13','Organizações internacionais','Analisar funções, limites e interesses em organizações internacionais e blocos econômicos.'),
('EF08GE14','África e fronteiras coloniais','Explicar efeitos territoriais do colonialismo e da descolonização de modo histórico e não gráfico.'),
('EF08GE15','África: diversidade e desafios','Analisar diversidade regional africana e desafios socioeconômicos sem generalizações ou estereótipos.'),
('EF08GE16','América Latina na ordem mundial','Avaliar inserções latino-americanas na economia mundial e relações de dependência e cooperação.'),
('EF08GE17','Características da América Latina','Comparar sub-regiões latino-americanas por aspectos físicos, populacionais, urbanos, políticos e econômicos.'),
('EF08GE18','Economias latino-americanas','Relacionar atividades econômicas, redes urbanas, infraestrutura e fluxos de exportação.'),
('EF08GE19','Cartografia da América e África','Interpretar mapas temáticos da América e África por variável, fonte, escala e método.'),
('EF08GE20','Desigualdades urbanas','Analisar segregação e acesso desigual a serviços como processos socioespaciais, sem culpabilizar moradores.'),
('EF08GE21','Indicadores latino-americanos','Comparar países por conjuntos de indicadores sem transformar médias em retratos individuais.'),
('EF08GE22','Recursos hídricos latino-americanos','Explicar bacias e aquíferos transfronteiriços e a necessidade de gestão compartilhada.'),
('EF08GE23','Paisagens da América Latina','Relacionar relevo, clima, vegetação e ocupação humana na formação das paisagens.'),
('EF08GE24','Biodiversidade e ambientes','Avaliar pressões sobre domínios naturais, biodiversidade e clima em diferentes escalas.'),
('EF08GE25','Povos e territórios','Reconhecer territorialidades e direitos de povos indígenas, afrodescendentes e comunidades tradicionais.'),
('EF08GE26','Antártica e geopolítica','Analisar acordos, pesquisa científica e proteção ambiental na Antártica.'),
('EF08GE27','Sustentabilidade na América Latina','Avaliar políticas e ações cooperativas para problemas ambientais latino-americanos.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-8ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise geopolítica e territorial — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes seguras e plurais','content',jsonb_build_array('Use mapas, gráficos, documentos e dados públicos agregados de mais de uma fonte; nunca peça nacionalidade, etnia, religião, renda, opinião política, endereço, geolocalização ou história migratória da criança e da família.','Migrações forçadas, xenofobia, colonialismo, disputas territoriais e conflitos devem receber tratamento histórico e informativo, sem detalhes gráficos, encenação ou simulação imersiva.')),
 jsonb_build_object('heading','Evite visões únicas e estereótipos','content',jsonb_build_array('Não apresente África, América Latina, migrantes, refugiados, povos indígenas, afrodescendentes ou comunidades tradicionais como grupos homogêneos; mostre diversidade, agência, produção de conhecimento e direitos.','Termos como desenvolvimento, centro, periferia, hegemonia e dependência devem ser tratados como conceitos debatidos, definidos pelo contexto e sustentados por indicadores múltiplos.')),
 jsonb_build_object('heading','Modele a análise multiescalar','content',jsonb_build_array('Verifique autoria, instituição, data, recorte, escala, variável, unidade, método e interesse; compare fontes e identifique silêncios ou divergências.','Mapeie atores, redes, fluxos, interesses, relações de poder, causas e consequências; diferencie fato, inferência, opinião, correlação e causalidade.','Mapas e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual, tabela equivalente ou alternativa tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos densos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e ofereça pistas graduadas e pausa.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, diagrama, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões com fontes, escala, atores e evidências pertinentes.')))),
jsonb_build_array(jsonb_build_object('title','1. Examinar a fonte','instruction','Identifique autoria, data, recorte, escala, variável, método, propósito e contexto.','activity','Registre duas evidências, um silêncio ou divergência e uma pergunta investigável.','support','Glossário, texto segmentado, leitura mediada e versão ampliada, descrita ou tabular.'),jsonb_build_object('title','2. Mapear relações','instruction','Compare fontes e localize atores, redes, fluxos, interesses, padrões e exceções.','activity','Construa mapa, gráfico acessível, matriz de atores ou cadeia causal sobre '||lower(title)||'.','support','Exemplo resolvido, dados em camadas e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com limites','instruction','Apresente conclusão, evidências, explicação alternativa e limites das fontes.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade e cooperação.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, evidências e silêncio ou divergência relevante.'),jsonb_build_object('page',2,'answer','Representa atores e relações sem generalizar territórios ou grupos.'),jsonb_build_object('page',3,'answer','Argumento multiescalar sustentado, com alternativa e limites reconhecidos.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, localização, renda, migração ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','actor_matrix','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_nationality_collection',true,'no_ethnicity_collection',true,'no_religion_collection',true,'no_income_collection',true,'no_political_opinion_collection',true,'no_family_migration_disclosure',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'migration_rights_context',true,'africa_latin_america_anti_stereotype',true,'indigenous_afrodescendant_rights_context',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-8ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Geografia do 9º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF09GE01','Da bipolaridade à multipolaridade','Analisar mudanças da ordem mundial por atores, alianças, redes e diferentes escalas.'),
('EF09GE02','Poder e nova ordem mundial','Comparar dimensões econômica, política, militar, tecnológica e cultural do poder global.'),
('EF09GE03','Corporações e organismos mundiais','Avaliar como corporações e organismos econômicos influenciam decisões e territórios.'),
('EF09GE04','Manifestações culturais e minorias','Reconhecer diversidade cultural e reivindicações por direitos sem expor identidades pessoais.'),
('EF09GE05','Europa e Ásia na ordem mundial','Comparar papéis e interdependências de países e blocos europeus e asiáticos.'),
('EF09GE06','Integração europeia','Analisar formação, funcionamento, potencialidades e tensões da integração europeia.'),
('EF09GE07','Europa: economia, política e população','Relacionar redes econômicas, dinâmicas populacionais e desigualdades territoriais europeias.'),
('EF09GE08','Espaço pós-soviético','Analisar fragmentação territorial, redes e relações de poder no espaço pós-soviético.'),
('EF09GE09','Rússia e Leste Europeu','Comparar fatores energéticos, econômicos e geopolíticos no Leste Europeu com fontes atualizadas.'),
('EF09GE10','Ascensão chinesa','Explicar transformações econômicas e territoriais ligadas à ascensão chinesa.'),
('EF09GE11','Redes e disputas tecnológicas','Analisar infraestrutura, comércio e tecnologia nas relações entre China, Ásia e mundo.'),
('EF09GE12','Oriente Médio e recursos estratégicos','Relacionar fronteiras, petróleo, água e redes de poder com abordagem informativa e não gráfica.'),
('EF09GE13','Diversidade e geopolítica do Oriente Médio','Analisar diversidade cultural, religiosa e política sem reduzir grupos a conflitos ou estereótipos.'),
('EF09GE14','Produção agropecuária europeia e asiática','Comparar sistemas agropecuários por fatores naturais, tecnologia, políticas e relações de trabalho.'),
('EF09GE15','Industrialização europeia e asiática','Relacionar indústria, energia, inovação, redes urbanas, trabalho e impactos ambientais.'),
('EF09GE16','Globalização e impactos ambientais','Analisar impactos ambientais globais, responsabilidades diferenciadas e escalas de ação.'),
('EF09GE17','Acordos e sustentabilidade global','Avaliar acordos climáticos e soluções por evidência, equidade, viabilidade e governança.'),
('EF09GE18','Cartografia da Europa, Ásia e Oceania','Interpretar mapas temáticos e anamorfoses sem confundir variável representada com área territorial.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-9ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de síntese geopolítica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes atuais, plurais e seguras','content',jsonb_build_array('Use mapas, gráficos, documentos e dados públicos agregados de instituições identificadas; nunca peça religião, etnia, nacionalidade, renda, posicionamento político, endereço, geolocalização ou história familiar do estudante.','Guerra Fria, colonialismo, migrações, extremismo, disputas e conflitos atuais devem ser abordados historicamente, de modo informativo e não gráfico, sem encenação, simulação estratégica ou atribuição de culpa coletiva.')),
 jsonb_build_object('heading','Evite simplificações culturais e geopolíticas','content',jsonb_build_array('Não reduza povos, religiões, minorias, Europa, Ásia, Oriente Médio ou Oceania a blocos homogêneos; mostre diversidade interna, agência, direitos e mudanças no tempo.','Diferencie descrição, interpretação e julgamento; sinalize quando dados ou alianças podem ter mudado e exija data e fonte.')),
 jsonb_build_object('heading','Modele a síntese multicausal','content',jsonb_build_array('Verifique autoria, instituição, data, recorte, escala, variável, método e interesse; triangule ao menos duas fontes quando houver controvérsia.','Construa matriz de atores, interesses, recursos, redes, escalas, causas e consequências; teste explicações alternativas e reconheça incertezas.','Mapas, anamorfoses e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual, tabela equivalente ou alternativa tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos densos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e ofereça pistas graduadas e pausa.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, matriz de atores, mapa conceitual, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões triangulando fontes, escalas, atores e evidências.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar e verificar','instruction','Defina questão, período, território, escala e conceitos; verifique autoria, data, método e propósito.','activity','Registre duas evidências, uma divergência e uma informação que precisa ser atualizada.','support','Glossário, texto segmentado, leitura mediada e fonte ampliada, descrita ou tabular.'),jsonb_build_object('title','2. Triangular e modelar','instruction','Compare ao menos duas fontes e mapeie atores, interesses, redes, causas e consequências.','activity','Construa matriz de atores, mapa conceitual, gráfico acessível ou cenário comparativo sobre '||lower(title)||'.','support','Exemplo resolvido, dados em camadas e pistas graduadas.'),jsonb_build_object('title','3. Sintetizar e avaliar','instruction','Apresente tese, evidências convergentes e divergentes, alternativa e grau de incerteza.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade, governança e efeitos indiretos.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Delimita questão e identifica evidências, divergência e necessidade de atualização.'),jsonb_build_object('page',2,'answer','Triangula fontes e representa relações sem atribuir culpa coletiva.'),jsonb_build_object('page',3,'answer','Síntese sustentada, incerteza explícita e proposta avaliada por critérios.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, religião, localização, renda ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','actor_matrix','concept_map','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'current_source_date_required',true,'source_triangulation',true,'no_live_geolocation',true,'no_nationality_collection',true,'no_ethnicity_collection',true,'no_religion_collection',true,'no_income_collection',true,'no_political_opinion_collection',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'no_collective_blame',true,'minority_rights_context',true,'religious_cultural_anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-9ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
