BEGIN;
-- Biblioteca Inclusiva · Arte do 1º ao 5º ano · códigos compartilhados EF15AR.
WITH lessons(code,title,goal) AS (VALUES
('EF15AR01','Artes visuais de diferentes contextos','Apreciar formas distintas de artes visuais, reconhecendo contextos, sentidos e diversidade cultural.'),
('EF15AR02','Elementos das artes visuais','Explorar ponto, linha, forma, cor, espaço, movimento, textura, luz e volume por diferentes percepções.'),
('EF15AR03','Matrizes estéticas e culturais','Reconhecer influências culturais nas artes visuais sem hierarquizar povos ou apropriar práticas sagradas.'),
('EF15AR04','Materialidades nas artes visuais','Experimentar materiais e suportes seguros, acessíveis e adequados às necessidades sensoriais e motoras.'),
('EF15AR05','Criação em artes visuais','Criar individual e coletivamente, fazendo escolhas, experimentando e revisando processos.'),
('EF15AR06','Diálogo sobre a criação','Descrever escolhas e dialogar sobre produções sem classificar trabalhos ou corpos como melhores.'),
('EF15AR07','Sistemas das artes visuais','Relacionar artistas, artesãos, curadores, educadores, públicos, espaços e instituições culturais.'),
('EF15AR08','Danças de diferentes contextos','Apreciar e experimentar danças diversas com respeito cultural, consentimento e alternativas de participação.'),
('EF15AR09','Relações corporais na dança','Perceber relações entre partes do corpo e corpo inteiro sem impor padrão corporal ou amplitude de movimento.'),
('EF15AR10','Espaço e ritmo na dança','Explorar direções, níveis, trajetórias, pausas e ritmos por movimentos possíveis para cada estudante.'),
('EF15AR11','Criação e improvisação em dança','Criar e revisar sequências de movimento individualmente e em grupo, sem contato físico obrigatório.'),
('EF15AR12','Reflexão e respeito na dança','Compartilhar percepções sobre dança sem ridicularização, comparação corporal ou exposição forçada.'),
('EF15AR13','Músicas de diferentes contextos','Apreciar músicas de culturas e épocas diversas com escuta regulável e respeito à autoria.'),
('EF15AR14','Elementos da música','Explorar altura, intensidade, timbre, melodia e ritmo com recursos visuais, táteis e sonoros reguláveis.'),
('EF15AR15','Fontes sonoras','Investigar sons do corpo, natureza, objetos, voz e instrumentos com segurança auditiva e material.'),
('EF15AR16','Notação e registro musical','Criar e interpretar registros convencionais ou inventados em formatos visuais, táteis ou digitais.'),
('EF15AR17','Criação musical','Improvisar, compor e sonorizar histórias em processos colaborativos com papéis flexíveis.'),
('EF15AR18','Teatro em diferentes contextos','Apreciar manifestações teatrais e reconhecer múltiplas funções, espaços e modos de participação.'),
('EF15AR19','Teatralidades no cotidiano','Investigar gesto, voz, ação e espaço sem imitar pessoas reais para ridicularizar ou expor.'),
('EF15AR20','Elementos teatrais','Experimentar corpo, voz, espaço e transformação simbólica usando objetos e cenários seguros.'),
('EF15AR21','Criação teatral coletiva','Planejar, improvisar, apresentar e revisar cenas com escuta, consentimento e divisão flexível de papéis.'),
('EF15AR22','Personagens, movimento e voz','Criar personagens sem caricaturar deficiência, etnia, religião, gênero, sotaque ou condição social.'),
('EF15AR23','Artes integradas','Integrar artes visuais, dança, música e teatro em torno de uma intenção compartilhada.'),
('EF15AR24','Matrizes culturais brasileiras','Conhecer brincadeiras, danças, histórias e canções de diferentes matrizes com fonte, contexto e respeito.'),
('EF15AR25','Patrimônio cultural','Distinguir patrimônio material e imaterial e propor valorização sem tocar, remover ou danificar bens.'),
('EF15AR26','Arte e tecnologia','Criar com recursos digitais respeitando autoria, privacidade, consentimento e proteção de dados.')
), normalized AS (
 SELECT code,'src/escola-brilha/data/'||code||'.ts' AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º ao 5º Ano','Arte',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia de experiência artística inclusiva — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com segurança e escolha','content',jsonb_build_array('Ofereça materiais atóxicos e sem pontas, lâminas, chama, solventes ou cola quente ao alcance dos estudantes; verifique alergias e disponibilize alternativa sem contato com o material.','Antecipe som, luz, textura, cheiro, movimento e contato; permita abafador, volume reduzido, pausa, lugar calmo e participação sem tocar, dançar, cantar, atuar ou ser fotografado.','Não publique voz, imagem, nome, localização ou obra identificável sem autorização apropriada; use cenário e dados fictícios.')),
 jsonb_build_object('heading','Garanta cultura, autoria e dignidade','content',jsonb_build_array('Contextualize autoria, povo, território, época e função; não apresente cultura como fantasia, não reproduza prática sagrada fora do contexto e não classifique uma matriz como superior.','Use obras autorizadas, licenciadas ou em domínio público conforme aplicável; trabalhe trechos necessários sem reproduzir letras ou obras integrais protegidas.','Não avalie aparência, corpo, fala, visão, audição, coordenação, afinação ou virtuosismo como se fossem compreensão artística.')),
 jsonb_build_object('heading','Diferencie a progressão','content',jsonb_build_array('1º–2º anos: observar, escolher e experimentar uma variável com modelo concreto e instrução única.','3º–4º anos: comparar referências, combinar duas ou mais escolhas, explicar intenção e revisar um detalhe.','5º ano: pesquisar fonte, planejar processo, testar alternativas, documentar decisões, realizar curadoria e avaliar o resultado.')),
 jsonb_build_object('heading','Critério inclusivo','content','Registre intenção, experimentação, percepção, escolhas, revisão e diálogo; aceite participação individual, em dupla, coletiva, de bastidor ou por tecnologia assistiva.')))),
jsonb_build_array(jsonb_build_object('title','1. Apreciar e perceber','instruction','Observe, escute ou explore uma referência artística em modalidade acessível.','activity','Escolha dois elementos percebidos e uma pergunta sobre '||lower(title)||'.','support','Audiodescrição, legenda, imagem ampliada, recurso tátil, volume regulável e tempo de processamento.'),jsonb_build_object('title','2. Experimentar e criar','instruction','Escolha materiais, movimentos, sons, palavras, imagens ou funções compatíveis com seu modo de participar.','activity','Crie uma versão, compare o efeito de uma mudança e revise uma escolha.','support','Modelo concreto, etapas visuais, ferramenta adaptada, papel de bastidor e alternativa sem desempenho público.'),jsonb_build_object('title','3. Compartilhar e refletir','instruction','Apresente processo ou resultado apenas no formato consentido e explique uma escolha.','activity','Descreva intenção, descoberta, revisão e próximo teste sem julgar pessoas ou corpos.','support','Fala, apontamento, cartões, exposição silenciosa, áudio, vídeo sem identificação, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Percebe dois elementos por modalidade acessível e formula pergunta pertinente.'),jsonb_build_object('page',2,'answer','Experimenta, faz escolha intencional e revisa ao menos um aspecto.'),jsonb_build_object('page',3,'answer','Comunica processo ou reflexão no formato consentido e respeita leituras diferentes.','teacher_note','Registre escolhas e apoios eficazes; não registre diagnóstico, recusa sensorial como falha, imagem, voz ou identidade cultural pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','visual_art','movement_optional','sound_optional','backstage_role','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'sensory_preview',true,'volume_control',true,'no_forced_touch',true,'no_forced_performance',true,'no_forced_recording',true,'privacy_preserving',true,'fictional_scenarios',true,'safe_nontoxic_materials',true,'no_student_access_to_blades_flame_solvents_hot_glue',true,'allergy_alternative',true,'body_dignity',true,'cultural_context_required',true,'sacred_practice_respect',true,'anti_stereotype',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Arte do 6º ao 9º ano · códigos compartilhados EF69AR.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF69AR01','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-01-arqueologia-cor.ts','Artes visuais em contextos históricos','Pesquisar e apreciar artes visuais relacionando contextos, artistas, obras e diversidade cultural.'),
('EF69AR02','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-01-arqueologia-cor.ts','Estilos e contextos visuais','Comparar estilos, movimentos e contextos sem criar hierarquias culturais universais.'),
('EF69AR03','src/escola-brilha/curso-v4/arte-6ano/unidade-2/aula-01-matriz-simbolos.ts','Artes visuais brasileiras','Analisar artes visuais brasileiras e suas matrizes com autoria, território e contexto.'),
('EF69AR04','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-01-arqueologia-cor.ts','Elementos visuais','Analisar e experimentar ponto, linha, forma, cor, textura, espaço, movimento, luz e volume.'),
('EF69AR05','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-01-arqueologia-cor.ts','Materialidades e técnicas','Experimentar materiais, instrumentos e técnicas seguros, acessíveis e adequados às necessidades sensoriais.'),
('EF69AR06','src/escola-brilha/curso-v4/arte-6ano/unidade-4/aula-01-estetica-metais.ts','Processos de criação visual','Planejar, testar, documentar e revisar processos individuais e colaborativos.'),
('EF69AR07','src/escola-brilha/curso-v4/arte-6ano/unidade-2/aula-01-matriz-simbolos.ts','Princípios de composição','Aplicar equilíbrio, contraste, ritmo, proporção, ênfase e unidade em composições acessíveis.'),
('EF69AR08','src/escola-brilha/curso-v4/arte-6ano/unidade-4/aula-01-estetica-metais.ts','Artistas e sistemas das artes','Relacionar artistas, artesãos, curadores, instituições, públicos, mercado e circulação cultural.'),
('EF69AR09','src/escola-brilha/curso-v4/arte-6ano/unidade-7/index.ts','Danças e contextos','Pesquisar danças em seus contextos históricos e culturais com respeito e fontes.'),
('EF69AR10','src/escola-brilha/curso-v4/arte-6ano/unidade-7/index.ts','Elementos do movimento','Analisar corpo, espaço, tempo, peso e fluência sem impor padrões corporais.'),
('EF69AR11','src/escola-brilha/curso-v4/arte-6ano/unidade-7/index.ts','Fatores do movimento','Experimentar direções, níveis, trajetórias, ritmos e dinâmicas por movimentos possíveis.'),
('EF69AR12','src/escola-brilha/curso-v4/arte-6ano/unidade-7/index.ts','Dança e pensamento corporal','Investigar relações corporais e espaciais com alternativas sem toque ou apresentação obrigatória.'),
('EF69AR13','src/escola-brilha/curso-v4/arte-6ano/unidade-8/index.ts','Improvisação e composição em dança','Improvisar, selecionar, compor, registrar e revisar movimentos com consentimento.'),
('EF69AR14','src/escola-brilha/curso-v4/arte-6ano/unidade-8/index.ts','Processos de criação em dança','Desenvolver autoria e colaboração em dança com papéis flexíveis e participação acessível.'),
('EF69AR15','src/escola-brilha/curso-v4/arte-6ano/unidade-8/index.ts','Dança, identidade e respeito','Discutir dança e identidades sem exposição pessoal, preconceito ou apropriação cultural.'),
('EF69AR16','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-02-voz-do-tempo.ts','Músicas em contextos','Analisar músicas por contexto, função, circulação, autoria e diversidade cultural.'),
('EF69AR17','src/escola-brilha/curso-v4/arte-6ano/unidade-9/index.ts','Elementos musicais','Analisar altura, duração, intensidade, timbre, ritmo, melodia, harmonia e forma.'),
('EF69AR18','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-02-voz-do-tempo.ts','Música e mídias','Analisar produção, circulação e consumo musical em mídias e tecnologias.'),
('EF69AR19','src/escola-brilha/curso-v4/arte-6ano/unidade-9/index.ts','Estilos e práticas musicais','Comparar estilos e práticas musicais sem hierarquizar gostos ou comunidades.'),
('EF69AR20','src/escola-brilha/curso-v4/arte-6ano/unidade-9/index.ts','Notação e registro musical','Interpretar e criar notações convencionais, gráficas, táteis ou digitais.'),
('EF69AR21','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-02-voz-do-tempo.ts','Música, identidade e cultura','Debater funções sociais da música sem exigir identidade, religião ou experiência pessoal.'),
('EF69AR22','src/escola-brilha/curso-v4/arte-6ano/unidade-10/index.ts','Criação musical','Improvisar, compor, registrar, escutar e revisar música com controle sensorial e autoria.'),
('EF69AR23','src/escola-brilha/curso-v4/arte-6ano/unidade-11/index.ts','Teatro em contextos','Analisar manifestações teatrais por tempo, sociedade, espaço, estilo e função.'),
('EF69AR24','src/escola-brilha/curso-v4/arte-6ano/unidade-11/index.ts','Estilos cênicos','Comparar estilos cênicos e relações entre atuação, espaço e público.'),
('EF69AR25','src/escola-brilha/curso-v4/arte-6ano/unidade-11/index.ts','Elementos da cena','Analisar corpo, voz, texto, espaço, cenário, figurino, luz, som e público.'),
('EF69AR26','src/escola-brilha/curso-v4/arte-6ano/unidade-11/index.ts','Profissionais do teatro','Reconhecer funções de artistas, técnicos e demais profissionais da cena.'),
('EF69AR27','src/escola-brilha/curso-v4/arte-6ano/unidade-12/index.ts','Pesquisa e criação teatral','Investigar temas e estímulos para criar cenas sem exposição pessoal obrigatória.'),
('EF69AR28','src/escola-brilha/curso-v4/arte-6ano/unidade-12/index.ts','Improvisação teatral','Improvisar situações e relações com acordos, consentimento e alternativas de bastidor.'),
('EF69AR29','src/escola-brilha/curso-v4/arte-6ano/unidade-12/index.ts','Personagem, corpo e voz','Criar personagens sem caricaturar deficiência, etnia, religião, gênero, sotaque ou condição social.'),
('EF69AR30','src/escola-brilha/curso-v4/arte-6ano/unidade-12/index.ts','Composição e dramaturgia','Selecionar ações, imagens, palavras e sons para compor e revisar dramaturgias.'),
('EF69AR31','src/escola-brilha/curso-v4/arte-6ano/unidade-3/aula-01-geometria-monumentos.ts','Artes e outras áreas','Relacionar Arte a conhecimentos históricos, científicos, matemáticos, tecnológicos e sociais.'),
('EF69AR32','src/escola-brilha/curso-v4/arte-6ano/unidade-6/aula-01-codice-decifrado.ts','Artes integradas','Integrar linguagens artísticas com intenção, funções definidas e coerência.'),
('EF69AR33','src/escola-brilha/curso-v4/arte-6ano/unidade-1/aula-01-arqueologia-cor.ts','Matrizes culturais e patrimônio','Analisar matrizes culturais e patrimônios com contexto, direitos e participação das comunidades.'),
('EF69AR34','src/escola-brilha/curso-v4/arte-6ano/unidade-2/aula-01-matriz-simbolos.ts','Patrimônio material e imaterial','Investigar patrimônio sem remover, tocar, expor ou reproduzir indevidamente bens e saberes.'),
('EF69AR35','src/escola-brilha/curso-v4/arte-6ano/unidade-6/aula-01-codice-decifrado.ts','Arte e tecnologia','Criar com tecnologias respeitando autoria, licença, privacidade, consentimento e segurança digital.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º ao 9º Ano','Arte',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação artística — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Segurança, consentimento e regulação sensorial','content',jsonb_build_array('Use materiais atóxicos e ferramentas adequadas; estudantes não acessam lâminas, chama, solventes, aerossóis ou cola quente. Verifique alergias e ofereça alternativa sem contato.','Antecipe som, luz, textura, cheiro, movimento, contato e gravação; permita volume reduzido, abafador, pausa, espaço calmo e participação por análise, criação digital, dramaturgia, técnica ou bastidor.','Não obrigue toque, dança, canto, atuação, exposição, fotografia ou gravação; nunca publique nome, imagem, voz, localização ou obra identificável sem autorização apropriada.')),
 jsonb_build_object('heading','Contexto, direitos e autoria','content',jsonb_build_array('Identifique autoria, povo, território, época, função e fonte; não transforme cultura ou religião em fantasia, não encene prática sagrada e não peça que estudante represente identidade que não é a sua.','Aborde conflitos e violências históricas apenas de modo informativo e não gráfico, sem dramatização imersiva.','Use obras autorizadas, licenciadas ou em domínio público conforme aplicável; trabalhe somente trechos necessários e ensine crédito, citação, licença e transformação autoral.')),
 jsonb_build_object('heading','Progressão do 6º ao 9º ano','content',jsonb_build_array('6º ano: identificar elementos, contexto e técnica; experimentar com roteiro e registrar escolhas.','7º ano: comparar referências, relacionar arte e território, testar alternativas e revisar processo.','8º ano: analisar circulação, mídia, identidade, poder e sistemas da arte com fontes múltiplas.','9º ano: formular problema autoral, pesquisar, planejar, produzir, documentar, fazer curadoria e avaliar impacto, ética e acessibilidade.')),
 jsonb_build_object('heading','Critério inclusivo','content','Avalie pesquisa, intenção, experimentação, escolhas, revisão, autoria, contextualização e reflexão; não use aparência, corpo, voz, visão, audição, coordenação ou virtuosismo como medida isolada.')))),
jsonb_build_array(jsonb_build_object('title','1. Pesquisar e analisar','instruction','Examine referência, contexto, autoria, linguagem, elementos, técnica, circulação e fonte.','activity','Registre duas evidências, uma questão e uma comparação relacionada a '||lower(title)||'.','support','Texto segmentado, audiodescrição, legenda, ampliação, recurso tátil, volume regulável e leitura mediada.'),jsonb_build_object('title','2. Experimentar e desenvolver','instruction','Planeje, teste materiais ou funções acessíveis, compare efeitos e documente decisões.','activity','Produza uma versão, receba retorno respeitoso e revise uma escolha.','support','Etapas visuais, ferramenta adaptada, modelo parcial, papel técnico ou de bastidor e alternativa sem apresentação pública.'),jsonb_build_object('title','3. Apresentar e avaliar','instruction','Compartilhe somente no formato consentido, contextualize fontes e explique decisões.','activity','Avalie intenção, processo, acessibilidade, ética, autoria, impacto e próximo teste.','support','Fala, apontamento, cartões, exposição silenciosa, portfólio, áudio, vídeo sem identificação, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Analisa referência com evidências, contexto e fonte.'),jsonb_build_object('page',2,'answer','Testa alternativas, documenta decisões e revisa intencionalmente.'),jsonb_build_object('page',3,'answer','Apresenta no formato consentido e avalia processo, autoria, ética e acessibilidade.','teacher_note','Registre escolhas e apoios eficazes; não registre diagnóstico, identidade sensível, imagem, voz ou recusa sensorial como falha.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','visual_art','movement_optional','sound_optional','technical_role','backstage_role','portfolio','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'sensory_preview',true,'volume_control',true,'no_forced_touch',true,'no_forced_performance',true,'no_forced_recording',true,'privacy_preserving',true,'safe_nontoxic_materials',true,'no_student_access_to_blades_flame_solvents_aerosols_hot_glue',true,'allergy_alternative',true,'body_dignity',true,'cultural_context_required',true,'sacred_practice_respect',true,'no_identity_impersonation',true,'historical_non_graphic',true,'no_immersive_violence_dramatization',true,'copyright_respect',true,'license_and_credit',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/arte-6ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
