BEGIN;
-- Biblioteca Inclusiva · Inglês complementar do 1º ao 5º ano.
-- NBEN identifica currículo próprio do NeuroBrilha; não é código BNCC.
WITH lessons(code,year_label,source_key,title,goal) AS (VALUES
('NBEN01A01','1º Ano','src/escola-brilha/ingles-1ano/u1-a01-hello/data.ts','Hello!','Compreender e usar cumprimentos e apresentação simples com fala opcional.'),
('NBEN01A02','1º Ano','src/escola-brilha/ingles-1ano/u1-a02-hello-friend/data.ts','Hello, my friend','Reconhecer expressões de amizade e interação respeitosa em diálogos curtos.'),
('NBEN01A03','1º Ano','src/escola-brilha/ingles-1ano/u1-a03-colors/data.ts','My colors everywhere','Nomear e identificar cores com símbolos e formas que não dependam apenas da visão cromática.'),
('NBEN01A04','1º Ano','src/escola-brilha/ingles-1ano/u1-a04-passport/data.ts','English passport','Revisar cumprimentos, nomes e cores em uma jornada totalmente fictícia.'),
('NBEN01A05','1º Ano','src/escola-brilha/ingles-1ano/u1-a05-school/data.ts','My school','Reconhecer objetos e ações escolares sem pedir dados da escola real.'),
('NBEN01A06','1º Ano','src/escola-brilha/ingles-1ano/u1-a06-body/data.ts','My body','Nomear partes do corpo com dignidade, sem comparação física ou toque obrigatório.'),
('NBEN01A07','1º Ano','src/escola-brilha/ingles-1ano/u1-a07-world/data.ts','English around the world','Integrar vocabulário inicial reconhecendo diferentes países, línguas e sotaques.'),
('NBEN02A01','2º Ano','src/escola-brilha/ingles-2ano/u2-a01-routine/data.ts','My daily routine','Compreender ações cotidianas usando personagem e rotina fictícios.'),
('NBEN02A02','2º Ano','src/escola-brilha/ingles-2ano/u2-a02-house/data.ts','My house','Nomear espaços e objetos de moradias diversas sem expor a casa real.'),
('NBEN02A03','2º Ano','src/escola-brilha/ingles-2ano/u2-a03-food/data.ts','Food time','Comunicar preferências alimentares sem julgamento, dieta ou obrigação de revelar hábitos.'),
('NBEN02A04','2º Ano','src/escola-brilha/ingles-2ano/u2-a04-clothes/data.ts','Clothes and weather','Relacionar roupas e clima sem comentários sobre corpo, gênero ou condição econômica.'),
('NBEN02A05','2º Ano','src/escola-brilha/ingles-2ano/u2-a05-community/data.ts','My community','Reconhecer lugares e serviços em comunidade fictícia sem endereço ou rota real.'),
('NBEN02A06','2º Ano','src/escola-brilha/ingles-2ano/u2-a06-hobbies/data.ts','Hobbies and sports','Expressar interesses com alternativas motoras e sem competição obrigatória.'),
('NBEN02A07','2º Ano','src/escola-brilha/ingles-2ano/u2-a07-world/data.ts','Around the world','Integrar frases simples sobre rotina, casa, comida, roupa, comunidade e interesses.'),
('NBEN03A01','3º Ano','src/escola-brilha/ingles-3ano/u3-a01-welcome/data.ts','Welcome to my world','Apresentar personagem fictício usando repertório pessoal básico sem exposição real.'),
('NBEN03A02','3º Ano','src/escola-brilha/ingles-3ano/u3-a02-school/data.ts','My amazing school','Descrever disciplinas, objetos e espaços de escola fictícia.'),
('NBEN03A03','3º Ano','src/escola-brilha/ingles-3ano/u3-a03-healthy/data.ts','My healthy life','Compreender vocabulário de cuidados e hábitos sem prescrição, dieta ou julgamento corporal.'),
('NBEN03A04','3º Ano','src/escola-brilha/ingles-3ano/u3-a04-animals/data.ts','Animals around the world','Descrever animais, habitats e características com apoio multimodal.'),
('NBEN03A05','3º Ano','src/escola-brilha/ingles-3ano/u3-a05-city/data.ts','My city','Localizar lugares em mapa fictício sem geolocalização ou trajeto pessoal.'),
('NBEN03A06','3º Ano','src/escola-brilha/ingles-3ano/u3-a06-travel/data.ts','Time to travel','Planejar viagem imaginária sem documentos, localização ou experiência familiar.'),
('NBEN03A07','3º Ano','src/escola-brilha/ingles-3ano/u3-a07-adventure/data.ts','English adventure','Integrar vocabulário e estruturas do ano em desafio acessível e cooperativo.'),
('NBEN04A01','4º Ano','src/escola-brilha/ingles-4ano/u4-a01-friends/data.ts','My life and my friends','Descrever personagens, relações e preferências sem exigir informações familiares ou sociais reais.'),
('NBEN04A02','4º Ano','src/escola-brilha/ingles-4ano/u4-a02-school/data.ts','School projects','Planejar projeto escolar fictício usando colaboração e funções flexíveis.'),
('NBEN04A03','4º Ano','src/escola-brilha/ingles-4ano/u4-a03-healthy/data.ts','Healthy habits','Interpretar linguagem de autocuidado sem dieta, diagnóstico ou comparação corporal.'),
('NBEN04A04','4º Ano','src/escola-brilha/ingles-4ano/u4-a04-nature/data.ts','Amazing nature','Descrever ambientes e relações ecológicas com vocabulário contextualizado.'),
('NBEN04A05','4º Ano','src/escola-brilha/ingles-4ano/u4-a05-city/data.ts','Around my city','Dar e compreender direções em cidade fictícia sem rota ou localização real.'),
('NBEN04A06','4º Ano','src/escola-brilha/ingles-4ano/u4-a06-holidays/data.ts','Holidays and adventures','Comparar celebrações e viagens com respeito cultural e sem expor crença ou renda.'),
('NBEN04A07','4º Ano','src/escola-brilha/ingles-4ano/u4-a07-challenge/data.ts','English challenge','Organizar portfólio fictício e demonstrar compreensão por múltiplos formatos.'),
('NBEN05A01','5º Ano','src/escola-brilha/ingles-5ano/u5-a01-dreams/data.ts','My life, my story','Criar narrativa de personagem sobre planos e experiências sem exposição pessoal.'),
('NBEN05A02','5º Ano','src/escola-brilha/ingles-5ano/u5-a02-world/data.ts','Amazing places','Comparar lugares por fontes e imagens sem rastrear localização.'),
('NBEN05A03','5º Ano','src/escola-brilha/ingles-5ano/u5-a03-science/data.ts','Healthy life and sports','Usar linguagem de saúde e esporte sem metas físicas, dieta ou desempenho obrigatório.'),
('NBEN05A04','5º Ano','src/escola-brilha/ingles-5ano/u5-a04-stories/data.ts','Science and discoveries','Ler e produzir explicações simples sobre descobertas com evidências.'),
('NBEN05A05','5º Ano','src/escola-brilha/ingles-5ano/u5-a05-planet/data.ts','Stories around the world','Comparar narrativas de diferentes contextos respeitando cultura e direitos autorais.'),
('NBEN05A06','5º Ano','src/escola-brilha/ingles-5ano/u5-a06-city/data.ts','Our planet','Argumentar sobre cuidado ambiental usando cenário coletivo e linguagem acessível.'),
('NBEN05A07','5º Ano','src/escola-brilha/ingles-5ano/u5-a07-mission/data.ts','English mission','Integrar repertório do ano em portfólio multimodal, privado e consentido.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1',year_label,'Língua Inglesa','Currículo complementar NeuroBrilha · '||title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Inglês — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Alinhamento correto','content',jsonb_build_array('Esta aula é currículo complementar do NeuroBrilha para o 1º ao 5º ano; o identificador NBEN é interno e não deve ser apresentado como código BNCC.','Mantenha ligação com a aula-fonte e registre somente evidências pedagógicas necessárias.')),
 jsonb_build_object('heading','Compreensão antes da produção','content',jsonb_build_array('Apresente significado por imagem, objeto, gesto consentido, tradução curta e áudio regulável; depois modele som, palavra e frase.','Fala e repetição em público são opcionais. Aceite apontamento, seleção, ordenação, comunicação alternativa, áudio privado, digitação ou escrita.','Trate sotaques e variedades do inglês com respeito; avalie inteligibilidade e compreensão, não imitação de sotaque nativo.')),
 jsonb_build_object('heading','Privacidade, cultura e bem-estar','content',jsonb_build_array('Use nomes, famílias, casas, rotinas, cidades, viagens, escolas e perfis fictícios; nunca peça endereço, geolocalização, documento, foto de casa, rota, renda, religião, diagnóstico ou história familiar.','Temas de corpo, roupa, alimentação, saúde e esporte não podem gerar comparação corporal, dieta, meta física ou exposição de hábito pessoal.','Use áudio e textos autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e comunica três significados por qualquer modo acessível, com apoio progressivamente reduzido.')))),
jsonb_build_array(jsonb_build_object('title','1. Compreender','instruction','Observe ou escute a palavra ou frase ligada a imagem, objeto ou cena fictícia.','activity','Associe três itens e identifique uma pista de significado.','support','Tradução curta, áudio repetível e regulável, legenda, imagem ampliada e tempo de processamento.'),jsonb_build_object('title','2. Construir','instruction','Organize cartões, símbolos ou palavras para formar significado.','activity','Complete ou monte duas frases sobre '||lower(title)||'.','support','Modelo resolvido, banco de palavras, código de cores combinado com rótulos e pistas graduadas.'),jsonb_build_object('title','3. Comunicar','instruction','Escolha como demonstrar compreensão sem fala pública obrigatória.','activity','Responda por seleção, gesto consentido, cartões, fala, áudio privado, digitação ou escrita.','support','Comunicação alternativa, leitor de tela, resposta privada e tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Associa significado por pista visual, auditiva, tátil ou textual.'),jsonb_build_object('page',2,'answer','Constrói frases compreensíveis com apoio adequado ao ano.'),jsonb_build_object('page',3,'answer','Comunica significado no modo escolhido; variação de sotaque não é erro.','teacher_note','Registre compreensão, apoio eficaz e próximo passo; não registre voz, imagem, localização, saúde ou identidade pessoal.')),
jsonb_build_object('curriculum_alignment','neurobrilha_complementary_not_bncc','response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'volume_control',true,'no_forced_speaking',true,'accent_dignity',true,'privacy_preserving',true,'fictional_personal_context',true,'no_live_geolocation',true,'no_family_disclosure',true,'no_health_disclosure',true,'body_neutral',true,'no_diet_or_fitness_target',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Língua Inglesa do 6º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06LI01','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Interação oral em inglês','Interagir em situações escolares com preparação, apoio visual e fala opcional.'),
('EF06LI02','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Coleta de informações no grupo','Solicitar e registrar informações de personagens fictícios sem exposição pessoal.'),
('EF06LI03','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Pedidos de esclarecimento','Pedir repetição, ajuda e explicação usando expressões respeitosas e acessíveis.'),
('EF06LI04','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Assunto e informações em textos orais','Reconhecer assunto e informações por palavras-chave, entonação e contexto.'),
('EF06LI05','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Sentimentos, gostos e preferências','Comunicar preferências de personagens sem exigir sentimento ou experiência pessoal.'),
('EF06LI06','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Planejamento de apresentação','Planejar apresentação curta com roteiro, ensaio privado e formatos alternativos.'),
('EF06LI07','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Hipóteses sobre finalidade textual','Formular hipóteses sobre público e finalidade por título, imagens e organização.'),
('EF06LI08','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Assunto de um texto','Identificar tema e ideia central com skimming e pistas contextuais.'),
('EF06LI09','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Informações específicas','Localizar detalhes com scanning sem exigir tradução palavra por palavra.'),
('EF06LI10','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Uso de dicionário bilíngue','Consultar verbete, classe, acepção e exemplo em dicionário seguro.'),
('EF06LI11','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Ferramentas digitais de aprendizagem','Usar recursos digitais sem conta pessoal, rastreamento ou publicação de dados.'),
('EF06LI12','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Compartilhamento de interpretações','Comparar interpretações e citar pistas textuais com discordância respeitosa.'),
('EF06LI13','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Planejamento por lista de ideias','Gerar e selecionar ideias adequadas a objetivo, gênero e público.'),
('EF06LI14','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Organização de ideias','Ordenar ideias em abertura, desenvolvimento e fechamento.'),
('EF06LI15','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Produção escrita autoral','Planejar, redigir, revisar e compartilhar texto sem expor dados pessoais.'),
('EF06LI16','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Expressões de sala de aula','Compreender e usar instruções e pedidos escolares em modalidades acessíveis.'),
('EF06LI17','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Inglês no mundo','Reconhecer inglês como língua materna, oficial ou franca em contextos diversos.'),
('EF06LI18','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Pronúncia e inteligibilidade','Comparar sons e tonicidade respeitando sotaques e variedades linguísticas.'),
('EF06LI19','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Presente simples','Usar presente simples para fatos e rotinas de personagens fictícios.'),
('EF06LI20','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Presente contínuo','Descrever ações em andamento com apoio de imagens e sequência.'),
('EF06LI21','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Imperativo em instruções','Interpretar e produzir instruções claras e respeitosas sem obediência corporal obrigatória.'),
('EF06LI22','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Caso genitivo','Expressar pertencimento e relações em cenários fictícios.'),
('EF06LI23','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Adjetivos possessivos','Usar adjetivos possessivos com referentes claros e perfis fictícios.'),
('EF06LI24','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Países e usos do inglês','Investigar usos do inglês sem reduzir a língua a um país ou sotaque.'),
('EF06LI25','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Inglês no contexto brasileiro','Analisar palavras e usos do inglês no Brasil com fontes e contexto.'),
('EF06LI26','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Produtos culturais em inglês','Avaliar autoria, público, circulação, pontos de vista e representações em produtos culturais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Compreensão e comunicação acessíveis','content',jsonb_build_array('Apresente contexto, objetivo e palavras-chave antes do áudio ou texto; permita repetição, velocidade reduzida, legenda, transcrição e pausas.','Fala pública, leitura em voz alta e repetição coral são opcionais. Aceite apontamento, cartões, comunicação alternativa, ensaio privado, áudio privado, digitação ou escrita.','Avalie compreensão e inteligibilidade, não imitação de sotaque nativo; reconheça variedades do inglês e repertórios multilíngues.')),
 jsonb_build_object('heading','Leitura e escrita estratégicas','content',jsonb_build_array('Modele previsão, skimming, scanning, inferência por contexto e consulta de dicionário; não exija tradução palavra por palavra.','Divida escrita em propósito, público, ideias, organização, rascunho, revisão e versão final; forneça modelo parcial, banco de palavras e organizador visual.','Use textos e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.')),
 jsonb_build_object('heading','Privacidade e segurança cultural','content',jsonb_build_array('Use nomes, famílias, rotinas, escolas, fotos, perfis e localizações fictícios; nunca peça endereço, geolocalização, conta digital, foto pessoal, rotina real, diagnóstico, religião, nacionalidade ou história familiar.','Ferramentas digitais devem funcionar sem perfil público; não publique voz, imagem, texto identificável ou localização.','Temas culturais devem mostrar diversidade e evitar que inglês, país, sotaque ou cultura sejam apresentados como superiores.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz três significados adequados ao contexto por qualquer modo acessível, citando pista quando a tarefa for interpretativa.')))),
jsonb_build_array(jsonb_build_object('title','1. Antecipar e compreender','instruction','Observe gênero, contexto, título e pistas antes de ler ou escutar.','activity','Identifique assunto, palavras-chave e duas informações sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável e repetível, tradução seletiva, texto segmentado e leitor de tela.'),jsonb_build_object('title','2. Praticar com apoio','instruction','Associe significado, estrutura e uso em exemplos fictícios.','activity','Ordene, complete ou transforme três itens com banco de palavras e modelo.','support','Exemplo resolvido, cartões, organizador visual, pistas graduadas e tempo ampliado.'),jsonb_build_object('title','3. Comunicar e revisar','instruction','Produza resposta adequada ao propósito no formato escolhido e revise o sentido.','activity','Explique uma escolha ou cite pista do texto, áudio ou contexto.','support','Apontamento, comunicação alternativa, fala opcional, áudio privado, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica assunto e informações por pistas pertinentes.'),jsonb_build_object('page',2,'answer','Relaciona forma, significado e uso com apoio adequado.'),jsonb_build_object('page',3,'answer','Comunica sentido e revisa com base no propósito; sotaque não é penalizado.','teacher_note','Registre compreensão, estratégia e apoio eficaz; não registre voz, localização, saúde ou identidade pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'accent_dignity',true,'multilingual_respect',true,'privacy_preserving',true,'fictional_personal_context',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_public_posting',true,'no_family_disclosure',true,'no_health_disclosure',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Língua Inglesa do 7º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF07LI01','Interação oral colaborativa','Participar de trocas com preparação, turnos flexíveis e fala opcional.'),
('EF07LI02','Entrevistas e coleta de informações','Formular perguntas e registrar respostas de personagens ou fontes públicas, sem exposição pessoal.'),
('EF07LI03','Conhecimentos prévios na compreensão oral','Ativar repertório, contexto e previsões antes de escutar.'),
('EF07LI04','Contexto e finalidade de textos orais','Identificar interlocutores, assunto, intenção e situação comunicativa.'),
('EF07LI05','Informações principais em textos orais','Selecionar fatos e acontecimentos relevantes em narrativas e relatos.'),
('EF07LI06','Composição de textos orais','Planejar sequência, palavras-chave e recursos de apoio para comunicação multimodal.'),
('EF07LI07','Leitura rápida para sentido geral','Usar título, início, fim e palavras repetidas para captar assunto.'),
('EF07LI08','Objetivos de leitura','Definir estratégia conforme finalidade, gênero e informação procurada.'),
('EF07LI09','Informações específicas em textos','Localizar detalhes e citar pistas sem tradução palavra por palavra.'),
('EF07LI10','Relações entre parágrafos','Reconhecer continuidade, contraste, causa, consequência e sequência.'),
('EF07LI11','Pesquisa e fontes confiáveis','Avaliar autoria, instituição, data, evidências e finalidade em fontes digitais.'),
('EF07LI12','Planejamento da escrita','Definir público, objetivo, gênero, suporte e recursos antes de produzir.'),
('EF07LI13','Organização em parágrafos','Agrupar ideias e usar títulos, tópicos e conectores para orientar o leitor.'),
('EF07LI14','Produção de textos diversos','Produzir e revisar textos com cenários e personagens fictícios.'),
('EF07LI15','Passado simples e contínuo','Distinguir fatos concluídos e ações em andamento em narrativas.'),
('EF07LI16','Conectores de sequência e causa','Usar before, after, when, while e because para articular acontecimentos.'),
('EF07LI17','Polissemia e contexto','Inferir sentidos de palavras polissêmicas pelo contexto e gênero.'),
('EF07LI18','Pronúncia do passado regular','Reconhecer variantes de pronúncia de -ed sem penalizar sotaque.'),
('EF07LI19','Pronomes sujeito e objeto','Usar pronomes conforme função sintática e referente claro.'),
('EF07LI20','Can e could','Expressar habilidades presentes e passadas em personagens fictícios.'),
('EF07LI21','Inglês como língua global','Analisar circulação mundial do inglês sem tratar uma variedade como superior.'),
('EF07LI22','Variação linguística','Reconhecer sotaques e vocabulários diversos como legítimos e contextuais.'),
('EF07LI23','Língua, identidade e respeito','Combater preconceito linguístico e valorizar repertórios multilíngues.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-7ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Entrada acessível e comunicação consentida','content',jsonb_build_array('Antecipe gênero, contexto, finalidade e palavras-chave; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição e pausas.','Fala pública, leitura em voz alta e entrevista entre colegas são opcionais. Use personagem fictício, fonte pública, roteiro escrito, comunicação alternativa, ensaio ou áudio privado.','Avalie compreensão e inteligibilidade, não imitação de sotaque; aceite tempo de processamento e formas multilíngues de construir sentido.')),
 jsonb_build_object('heading','Pesquisa, leitura e escrita','content',jsonb_build_array('Modele previsão, leitura global, busca de detalhes, relações entre parágrafos e verificação de autoria, instituição, data, evidência e finalidade.','Escrita segue público, propósito, ideias, organização, rascunho, revisão e versão final; biografia e entrevista devem usar personagens ou figuras públicas com fontes adequadas.','Ferramentas digitais não exigem perfil público, contato com desconhecidos ou publicação; dados e exemplos devem ser fictícios ou públicos agregados.')),
 jsonb_build_object('heading','Privacidade, identidade e autoria','content',jsonb_build_array('Nunca peça história de vida, memória difícil, foto, nome completo, endereço, geolocalização, rotina, habilidade pessoal, diagnóstico, religião, nacionalidade, etnia ou informação familiar.','Não apresente sotaque, país, inglês nativo ou cultura como superiores; discuta língua e identidade sem exigir autodeclaração.','Use textos e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz três significados adequados ao contexto, citando evidência e revisando a resposta no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Prever e compreender','instruction','Ative repertório, identifique contexto e escolha estratégia antes de ler ou escutar.','activity','Registre assunto, finalidade, duas informações e uma pista sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, glossário e leitor de tela.'),jsonb_build_object('title','2. Relacionar e praticar','instruction','Conecte forma, significado, função e evidência em exemplos fictícios.','activity','Organize, complete ou transforme três itens e explique uma escolha.','support','Modelo resolvido, cartões, linha do tempo, banco de palavras e pistas graduadas.'),jsonb_build_object('title','3. Produzir e revisar','instruction','Planeje resposta para propósito e público, produza no formato escolhido e revise sentido e forma.','activity','Cite evidência ou explique estratégia sem fala pública obrigatória.','support','Apontamento, comunicação alternativa, fala opcional, áudio privado, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica contexto, finalidade, informações e pista pertinente.'),jsonb_build_object('page',2,'answer','Relaciona forma e significado e explica escolha com apoio adequado.'),jsonb_build_object('page',3,'answer','Produz e revisa resposta adequada; sotaque e comunicação alternativa não são penalizados.','teacher_note','Registre compreensão, estratégia e apoio eficaz; não registre voz, história pessoal, identidade ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'no_peer_interview_required',true,'accent_dignity',true,'multilingual_respect',true,'privacy_preserving',true,'fictional_biography_only',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_life_story_disclosure',true,'no_health_disclosure',true,'no_religion_ethnicity_nationality_collection',true,'source_verification',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-7ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Língua Inglesa do 8º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF08LI01','Negociação de sentido','Esclarecer mal-entendidos por paráfrase, pergunta e confirmação em formatos acessíveis.'),
('EF08LI02','Opiniões com justificativa','Expressar e comparar pontos de vista com razões e evidências, sem exposição pessoal.'),
('EF08LI03','Recursos paralinguísticos','Interpretar pausas, entonação e expressão sem exigir contato visual ou gesto corporal.'),
('EF08LI04','Planos e previsões','Comunicar planos e previsões de personagens e cenários fictícios.'),
('EF08LI05','Sentido global em textos orais','Relacionar partes, assunto e informações relevantes em textos orais e multimodais.'),
('EF08LI06','Apreciação literária','Apreciar narrativas legalmente acessíveis, observando linguagem, cenário e efeitos no leitor.'),
('EF08LI07','Manifestações culturais','Comparar manifestações em inglês com contexto, autoria e respeito cultural.'),
('EF08LI08','Inferências e perspectivas','Inferir informações implícitas e comparar seleção de fatos, vozes e evidências.'),
('EF08LI09','Planejamento da escrita','Definir finalidade, público, gênero, suporte e recursos antes de escrever.'),
('EF08LI10','Revisão entre pares','Usar critérios objetivos para oferecer e receber retorno respeitoso, com alternativa privada.'),
('EF08LI11','Reconstrução e edição textual','Cortar, acrescentar, reformular e editar preservando autoria e sentido.'),
('EF08LI12','Produção sobre o futuro','Criar textos sobre futuros fictícios sem exigir projeto de vida ou dado pessoal.'),
('EF08LI13','Formação de palavras','Inferir e formar palavras com prefixos e sufixos em contexto.'),
('EF08LI14','Comparativos e superlativos','Comparar características e quantidades sem classificar pessoas ou corpos.'),
('EF08LI15','Quantificadores','Usar some, any, many e much conforme substantivos e contexto.'),
('EF08LI16','Pronomes relativos','Articular informações com who, which, that e whose, usando referentes claros.'),
('EF08LI17','Futuro e possibilidade','Distinguir be going to, will, may e might em planos, previsões e possibilidades.'),
('EF08LI18','Publicação responsável','Preparar produto final acessível sem postagem pública, nome real ou imagem identificável.'),
('EF08LI19','Comunicação intercultural','Investigar diferenças de sentido em gestos e expressões sem imitar identidades.'),
('EF08LI20','Prevenção de ruídos culturais','Perguntar, esclarecer e reparar mal-entendidos com respeito e sem generalizações.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-8ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Comunicação multimodal e consentida','content',jsonb_build_array('Antecipe contexto, gênero, finalidade e vocabulário; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição e pausas.','Fala pública, leitura em voz alta, gesto, contato visual, dramatização e revisão por colega são opcionais; aceite retorno privado do professor e comunicação alternativa.','Avalie compreensão, inteligibilidade, argumentação e uso de evidências, não imitação de sotaque, rapidez ou performance corporal.')),
 jsonb_build_object('heading','Leitura crítica, literatura e mídia','content',jsonb_build_array('Diferencie informação explícita, inferência e opinião; compare enquadramento, vozes presentes, ausências, argumentos e evidências.','Use contos, imagens, vídeos e outros materiais autorizados, licenciados ou em domínio público conforme aplicável; não reproduza obras integrais protegidas.','Não exponha estudante a fórum público, comentários abertos, contato com desconhecidos ou coleta de comportamento digital.')),
 jsonb_build_object('heading','Escrita e interculturalidade protegidas','content',jsonb_build_array('Planeje finalidade e público, produza rascunho, revise por critérios, reformule e prepare versão final acessível; publicação significa circulação controlada na atividade, não postagem aberta.','Use personagens e futuros fictícios; nunca peça projeto de vida, carreira, crença, identidade, foto, localização, perfil digital, diagnóstico ou história familiar.','Investigue gestos e expressões como variáveis de contexto; não peça imitação de povo, sotaque, deficiência, religião ou identidade.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz argumento ou texto adequado ao contexto com evidência, revisão e respeito intercultural no modo escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Interpretar perspectivas','instruction','Identifique contexto, propósito, explícitos, implícitos, vozes e evidências.','activity','Compare duas perspectivas e registre uma inferência sustentada sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, glossário e leitor de tela.'),jsonb_build_object('title','2. Construir e negociar','instruction','Relacione forma, significado, interlocutor e efeito; use paráfrase ou pergunta para confirmar.','activity','Organize ou transforme três exemplos e justifique uma escolha.','support','Modelo resolvido, cartões, matriz de perspectivas, banco de palavras e pistas graduadas.'),jsonb_build_object('title','3. Produzir, revisar e compartilhar','instruction','Planeje, produza, revise por critérios e circule apenas no ambiente controlado e consentido.','activity','Explique decisões, evidências, mudança feita e cuidado intercultural.','support','Comunicação alternativa, fala opcional, áudio privado, portfólio local, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Distingue explícito e inferência e compara perspectivas por evidências.'),jsonb_build_object('page',2,'answer','Negocia sentido e relaciona forma, uso e efeito com apoio adequado.'),jsonb_build_object('page',3,'answer','Produz e revisa resposta autoral, acessível e interculturalmente respeitosa.','teacher_note','Registre estratégias e apoio eficaz; não registre voz, projeto de vida, perfil, identidade ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_feedback','private_audio','local_portfolio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'no_forced_eye_contact',true,'no_forced_gesture',true,'no_forced_peer_review',true,'accent_dignity',true,'privacy_preserving',true,'fictional_future_only',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_behavioral_tracking',true,'no_life_plan_disclosure',true,'licensed_materials_only',true,'perspective_and_source_analysis',true,'no_identity_impersonation',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-8ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Língua Inglesa do 9º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF09LI01','Pontos de vista e argumentação oral','Expor tese, razões e evidências em formato acessível, sem debate público obrigatório.'),
('EF09LI02','Notas de textos orais','Registrar palavras-chave, tese, razões, evidências e contra-argumentos com organizador visual.'),
('EF09LI03','Análise de posicionamentos','Comparar argumentos e contra-argumentos sem coletar opinião política ou crença pessoal.'),
('EF09LI04','Apresentação de pesquisa','Apresentar método, amostra, dados e limites por fala opcional ou produto multimodal.'),
('EF09LI05','Recursos de persuasão','Analisar palavras, imagens, enquadramento, cor e tamanho usados para persuadir.'),
('EF09LI06','Fato e opinião','Distinguir afirmações verificáveis, interpretações e avaliações pessoais.'),
('EF09LI07','Argumentos e evidências','Avaliar pertinência, suficiência e relação entre tese, argumento e evidência.'),
('EF09LI08','Validade das fontes','Verificar autoria, instituição, data, referências, método, finalidade e conflitos de interesse.'),
('EF09LI09','Pesquisa para produção textual','Pesquisar em fontes seguras, registrar referências e selecionar informações relevantes.'),
('EF09LI10','Organização argumentativa','Ordenar tese, argumentos, evidências, contraponto e conclusão com conectores.'),
('EF09LI11','Recursos multimodais','Integrar texto, tabela, gráfico e imagem de forma acessível e sem manipulação.'),
('EF09LI12','Campanha ética','Criar campanha sobre situação fictícia ou coletiva usando evidência e circulação controlada.'),
('EF09LI13','Escrita digital e contexto','Interpretar abreviações, símbolos e pictogramas conforme público, gênero e propósito.'),
('EF09LI14','Conectores argumentativos','Usar conectores de adição, oposição, condição, conclusão e síntese.'),
('EF09LI15','Orações condicionais','Distinguir condições possíveis e hipotéticas em problemas fictícios.'),
('EF09LI16','Verbos modais','Expressar recomendação, obrigação, necessidade e probabilidade com precisão.'),
('EF09LI17','Expansão histórica do inglês','Analisar migração, comércio e colonialismo de modo histórico, informativo e não gráfico.'),
('EF09LI18','Inglês em ciência, economia e política','Avaliar usos internacionais do inglês e desigualdades de acesso sem apresentar uma língua como superior.'),
('EF09LI19','Inglês, identidades e multilinguismo','Debater língua, poder e identidade valorizando multilinguismo e direitos linguísticos.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-9ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Argumentação acessível e segura','content',jsonb_build_array('Antecipe tema, conceitos e vocabulário; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição, notas guiadas e pausas.','Fala pública, debate, campanha, gravação e revisão por colegas são opcionais. Aceite texto, infográfico acessível, apresentação gravada privada, comunicação alternativa ou mediação do professor.','Use temas fictícios ou questões coletivas não partidárias; nunca peça posicionamento político, religião, identidade, experiência sensível ou confronto com colegas.')),
 jsonb_build_object('heading','Pesquisa, mídia e dados','content',jsonb_build_array('Verifique autoria, instituição, data, método, amostra, referências, finalidade, financiamento e conflitos de interesse; diferencie fato, opinião, inferência e evidência.','Use apenas dados públicos agregados ou conjuntos fictícios; não colete localização, rota escolar, contato, perfil digital, saúde, renda, opinião ou comportamento da turma.','Gráficos combinam cor com rótulo, padrão e forma, possuem descrição textual e não distorcem eixos, proporções ou amostras.')),
 jsonb_build_object('heading','Autoria, história e circulação','content',jsonb_build_array('Planeje tese, público e propósito; pesquise, rascunhe, revise, cite fontes e compartilhe somente em ambiente escolar controlado.','Use textos, imagens e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.','Colonialismo, coerção e supressão linguística recebem abordagem histórica informativa e não gráfica, sem encenação imersiva; valorize multilinguismo e direitos linguísticos.')),
 jsonb_build_object('heading','Critério','content','Interpreta quatro de cinco itens e produz argumento adequado com tese, evidência, fonte, contraponto e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Verificar e anotar','instruction','Identifique autoria, propósito, tese, fatos, opiniões, evidências, método e limites.','activity','Registre palavras-chave e classifique quatro elementos sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, tabela de notas e leitor de tela.'),jsonb_build_object('title','2. Comparar e argumentar','instruction','Compare fontes, argumentos, evidências e recursos verbais ou visuais.','activity','Monte mapa argumentativo com tese, razão, evidência, contraponto e resposta.','support','Modelo resolvido, cartões, matriz de fonte, dados acessíveis e pistas graduadas.'),jsonb_build_object('title','3. Produzir e revisar','instruction','Crie produto para cenário fictício ou coletivo, cite fontes e revise ética e acessibilidade.','activity','Explique escolha, limite, revisão e efeito esperado sem apresentação pública obrigatória.','support','Comunicação alternativa, fala opcional, áudio privado, infográfico acessível, portfólio local, digitação ou escrita.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Classifica elementos e registra fonte, método e limite pertinente.'),jsonb_build_object('page',2,'answer','Relaciona tese, evidência e contraponto sem ataque pessoal.'),jsonb_build_object('page',3,'answer','Produção fundamentada, citada, revisada, acessível e de circulação controlada.','teacher_note','Registre estratégias e apoio eficaz; não registre voz, opinião, identidade, perfil ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','accessible_infographic','local_portfolio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_campaign',true,'no_forced_peer_review',true,'accent_dignity',true,'privacy_preserving',true,'fictional_or_collective_topics',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_route_collection',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_behavioral_tracking',true,'no_political_opinion_collection',true,'no_sensitive_identity_disclosure',true,'source_method_sample_check',true,'accessible_nonmisleading_charts',true,'historical_non_graphic',true,'no_immersive_oppression_simulation',true,'multilingual_rights',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-9ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
