BEGIN;
-- Biblioteca Inclusiva · Ensino Religioso do 5º ano completo.
-- Abordagem não confessional: estudar tradições não exige crença, prática ou exposição pessoal.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF05ER01','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-1/aula-01-acontecimentos-sagrados.ts','Acontecimentos sagrados e memória','Identificar acontecimentos sagrados de diferentes culturas e tradições como parte da preservação da memória, sem hierarquizar crenças.'),
('EF05ER02','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Mitos de criação em diferentes culturas','Identificar mitos de criação em diferentes culturas, distinguindo narrativa religiosa ou cultural de explicação científica sem chamar mito de mentira.'),
('EF05ER03','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Funções e mensagens dos mitos de criação','Reconhecer concepções de mundo, valores, relações e responsabilidades comunicadas por mitos de criação.'),
('EF05ER04','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-4/aula-01-tradicao-oral.ts','Tradição oral e memória religiosa','Reconhecer a importância da tradição oral para preservar memórias e conhecimentos religiosos e culturais.'),
('EF05ER05','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-5/aula-01-oralidade-culturas.ts','Oralidade em culturas diversas','Identificar elementos da tradição oral em culturas indígenas, afro-brasileiras e dos povos Rom, Calon e Sinti com linguagem respeitosa e contextualizada.'),
('EF05ER06','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Sábios, anciãos e memória coletiva','Identificar o papel de pessoas mais velhas, sábios e lideranças reconhecidas pelas comunidades na transmissão responsável de memórias.'),
('EF05ER07','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Ensinamentos em textos orais','Reconhecer ensinamentos sobre modos de ser e viver em textos orais sem transformar o conteúdo estudado em regra religiosa obrigatória.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional','content',jsonb_build_array('Apresente o conteúdo como conhecimento histórico, cultural e religioso: estudar não significa acreditar, aderir, concordar ou praticar.','Não conduza oração, rito, oferenda, canto, recitação, dramatização de prática sagrada, uso de vestimenta ritual ou representação de divindade. Sempre ofereça atividade neutra equivalente.','Nunca peça que estudante revele religião, ausência de religião, tradição familiar, objeto sagrado, fotografia, experiência íntima ou participação comunitária.')),
 jsonb_build_object('heading','Investigação respeitosa','content',jsonb_build_array('Use excertos breves, paráfrases, imagens autorizadas e fontes produzidas ou validadas pelas próprias comunidades; preserve autoria, contexto, diversidade interna e contemporaneidade.','Diferencie narrativa religiosa ou cultural e explicação científica por finalidade e método. Mito não significa mentira, e nenhuma tradição deve ser tratada como superior, exótica ou homogênea.','Ao abordar povos indígenas, culturas afro-brasileiras e povos Rom, Calon e Sinti, use os nomes específicos disponíveis, reconheça protagonismo atual e não peça imitação de sotaque, canto, rito, liderança ou identidade.')),
 jsonb_build_object('heading','Acesso, escolha e privacidade','content',jsonb_build_array('Antecipe vocabulário e sequência; ofereça leitura segmentada, descrição de imagem, áudio regulável, legenda, transcrição, pausa planejada, cartões e modelo resolvido.','Aceite apontar, selecionar, ordenar cartões, completar quadro comparativo, comunicação alternativa, digitação, escrita, fala opcional ou áudio privado.','Evite exposição individual. Compare apenas materiais fornecidos pelo professor e permita recusa ou troca de qualquer atividade sem redução da avaliação.')),
 jsonb_build_object('heading','Critério','content','Identifica e relaciona pelo menos quatro de cinco elementos da habilidade usando evidências do material, linguagem respeitosa e o modo de resposta acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e contextualizar','instruction','Localize autoria, comunidade, tempo, lugar, gênero e finalidade no material fornecido.','activity','Associe quatro cartões de contexto a trechos, imagens ou resumos sobre '||lower(title)||'.','support','Leitura fácil, pictogramas, fonte ampliada, contraste, descrição de imagem, áudio com legenda e transcrição.'),jsonb_build_object('title','2. Comparar sem hierarquizar','instruction','Organize semelhanças e diferenças sem decidir qual tradição seria melhor ou verdadeira.','activity','Complete quadro com contexto, forma de transmissão, mensagem, evidência e cuidado de linguagem.','support','Modelo resolvido, banco de palavras, cartões móveis, pista gradual e mediador de comunicação.'),jsonb_build_object('title','3. Explicar com respeito','instruction','Escolha uma evidência e explique a relação com a habilidade, sem falar sobre crença pessoal.','activity','Produza resposta curta, sequência visual, mapa de conceitos ou áudio privado e revise termos respeitosos.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica contexto e evidência pertinentes sem atribuir crença ao estudante ou à comunidade inteira.'),jsonb_build_object('page',2,'answer','Compara elementos por finalidade, mensagem e contexto sem hierarquização.'),jsonb_build_object('page',3,'answer','Explicação coerente, respeitosa e sustentada pelo material.','teacher_note','Registre estratégia e apoio eficaz; não registre religião, não religião, tradição familiar, voz, fotografia ou experiência pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_prayer',true,'no_forced_ritual',true,'no_forced_recitation',true,'no_sacred_practice_simulation',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_sacred_object_request',true,'no_personal_experience_request',true,'privacy_preserving',true,'compare_provided_materials_only',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'science_religion_method_distinction',true,'community_authority',true,'indigenous_afro_brazilian_romani_dignity',true,'no_identity_impersonation',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-5ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ensino Religioso do 6º ano completo.
-- Abordagem não confessional, com estudo contextualizado de textos, narrativas, ritos e símbolos.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06ER01','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-1/aula-01-tradicao-escrita.ts','Tradição escrita e memória','Reconhecer o papel da tradição escrita no registro e na preservação de memórias, acontecimentos e ensinamentos religiosos.'),
('EF06ER02','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-2/aula-01-diversidade-textos.ts','Diversidade de textos religiosos','Reconhecer e valorizar a diversidade de textos religiosos escritos e tradições orais, considerando autoria, comunidade e contexto.'),
('EF06ER03','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-3/aula-01-ensinamentos-viver.ts','Ensinamentos sobre modos de viver','Reconhecer em textos religiosos ensinamentos relacionados a modos de ser, conviver e cuidar, sem convertê-los em regra obrigatória para a turma.'),
('EF06ER04','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-4/aula-01-usos-diversos.ts','Diferentes usos dos textos religiosos','Identificar diferentes usos de textos religiosos pelas comunidades, estudando finalidade e contexto sem executar práticas sagradas.'),
('EF06ER05','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-5/aula-01-interpretacao-textos.ts','Interpretação dos textos religiosos','Discutir como diferentes tradições e lideranças interpretam seus textos, reconhecendo diversidade interna e autoridade comunitária.'),
('EF06ER06','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-6/aula-01-mitos-ritos-textos.ts','Mitos, ritos, símbolos e textos','Reconhecer relações entre narrativas, textos, ritos e símbolos em diferentes tradições por análise documental não imersiva.'),
('EF06ER07','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-7/aula-01-relacao-mito-rito-simbolo.ts','Relações entre mito, rito e símbolo','Explicar como mito, rito e símbolo se relacionam em práticas celebrativas sem reproduzir ou dramatizar a prática estudada.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Ensino não confessional','content',jsonb_build_array('Explique que a aula estuda textos, narrativas, símbolos e práticas como manifestações religiosas e culturais; conhecer não significa acreditar, aderir, concordar ou praticar.','Não conduza oração, recitação devocional, meditação religiosa, rito, canto, dança, gesto, dramatização, oferenda, uso ritual de objeto ou representação de divindade. Ofereça análise documental neutra.','Não peça religião, não religião, tradição familiar, texto sagrado pessoal, local frequentado, fotografia, experiência íntima ou justificativa de crença. Recusa e alternativa neutra não reduzem a avaliação.')),
 jsonb_build_object('heading','Fontes e interpretação','content',jsonb_build_array('Utilize excertos breves, paráfrases e imagens autorizadas, licenciadas ou em domínio público; informe fonte, tradução, autoria quando conhecida, comunidade, gênero, época e finalidade. Não reproduza obra extensa.','Diferencie descrição, interpretação acadêmica e interpretação interna da tradição. Apresente diversidade dentro de cada comunidade e não transforme uma liderança em porta-voz de todas as pessoas.','Mito não significa mentira. Compare função, estrutura e contexto sem hierarquizar tradições nem usar textos religiosos para validar ou invalidar explicações científicas.')),
 jsonb_build_object('heading','Análise acessível e respeitosa','content',jsonb_build_array('Antecipe vocabulário potencialmente desconhecido; use organizador visual com texto ou narrativa, contexto, ensinamento, uso, símbolo e evidência.','Quando houver rito ou celebração, analise material fornecido por descrição, fotografia autorizada, diagrama ou vídeo com legenda e transcrição; não peça encenação, imitação, vestimenta ou manuseio de objeto sagrado.','Aceite apontar, selecionar, ordenar cartões, comunicação alternativa, quadro comparativo, digitação, escrita, fala opcional ou áudio privado; nunca obrigue leitura pública.')),
 jsonb_build_object('heading','Critério','content','Identifica e relaciona quatro de cinco elementos da habilidade com evidência, contexto, linguagem respeitosa e o modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler o contexto','instruction','Identifique fonte, comunidade, gênero, época, finalidade e modo de transmissão no material fornecido.','activity','Associe cartões de contexto a excertos breves, paráfrases, descrições ou imagens sobre '||lower(title)||'.','support','Texto segmentado, leitura fácil, glossário visual, fonte ampliada, descrição de imagem, áudio regulável, legenda e transcrição.'),jsonb_build_object('title','2. Analisar relações','instruction','Relacione narrativa ou texto, ensinamento, uso, rito e símbolo somente quando os elementos estiverem documentados.','activity','Complete quadro comparativo e destaque uma evidência para cada relação, sem hierarquizar tradições.','support','Modelo resolvido, cartões móveis, código por forma e rótulo, pista gradual, mediador e tempo ampliado.'),jsonb_build_object('title','3. Explicar sem praticar','instruction','Explique a relação observada como estudo cultural e religioso, sem reproduzir a prática.','activity','Produza mapa de conceitos, sequência visual, resposta curta ou áudio privado e revise fonte, contexto e termos.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fonte, comunidade, gênero, época e finalidade sem inferir a crença do estudante.'),jsonb_build_object('page',2,'answer','Relaciona elementos documentados e reconhece interpretações possíveis sem generalização ou hierarquia.'),jsonb_build_object('page',3,'answer','Explica com evidência, contexto e linguagem respeitosa sem executar prática religiosa.','teacher_note','Registre somente estratégia e apoio eficaz; não registre crença, não crença, voz, imagem, comunidade frequentada ou dado familiar.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','concept_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_reading',true,'no_forced_prayer',true,'no_forced_recitation',true,'no_forced_ritual',true,'no_sacred_practice_simulation',true,'no_sacred_object_handling',true,'documentary_analysis_only',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_personal_sacred_text_request',true,'no_worship_place_disclosure',true,'no_personal_experience_request',true,'privacy_preserving',true,'compare_provided_materials_only',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'science_religion_method_distinction',true,'internal_diversity',true,'community_authority',true,'no_identity_impersonation',true,'brief_authorized_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ensino Religioso do 7º ano completo.
-- O curso ativo zera os códigos das sete aulas antigas e concentra EF07ER01–08 nas oficinas BNCC.
WITH lessons(code,title,goal) AS (VALUES
('EF07ER01','Práticas de comunicação com divindades','Reconhecer práticas de comunicação com divindades em diferentes tradições por análise contextual, sem participação devocional.'),
('EF07ER02','Espiritualidade em situações específicas','Identificar práticas de espiritualidade usadas por algumas pessoas em situações específicas, preservando autonomia e distinguindo apoio espiritual de serviços profissionais.'),
('EF07ER03','Papéis das lideranças religiosas','Reconhecer papéis atribuídos a lideranças religiosas conforme cada tradição, sem tratá-las como representantes absolutos de grupos diversos.'),
('EF07ER04','Contribuições sociais de lideranças','Exemplificar contribuições sociais verificáveis de lideranças religiosas em diferentes tempos e espaços, analisando fontes, contexto, efeitos e limites.'),
('EF07ER05','Estratégias de convivência ética','Discutir estratégias que promovam convivência ética entre religiões, filosofias de vida e pessoas sem religião, com direitos, diálogo e limites.'),
('EF07ER06','Princípios éticos e práticas sociais','Identificar princípios éticos em tradições religiosas e filosofias de vida e relacioná-los criticamente a condutas e práticas sociais.'),
('EF07ER07','Lideranças e direitos humanos','Discutir o papel de lideranças religiosas e seculares na defesa e promoção dos direitos humanos com base em ações e fontes verificáveis.'),
('EF07ER08','Liberdade de consciência, crença e convicção','Reconhecer o direito de ter, mudar ou não ter religião ou convicção e questionar coerção e discriminação sem exigir relato pessoal.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/ensino-religioso-7ano/oficinas-bncc.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional','content',jsonb_build_array('Apresente religião, espiritualidade, filosofia de vida, liderança, ética e direitos como objetos de estudo; conhecer não significa acreditar, concordar, aderir ou praticar.','Não conduza oração, meditação religiosa, canto, recitação, oferenda, rito, gesto, dança, dramatização, aconselhamento espiritual ou simulação de situação vulnerável. Use casos fictícios e análise documental.','Não peça crença, ausência de crença, mudança de religião, prática familiar, liderança frequentada, experiência difícil, opinião íntima ou posicionamento público. Sempre aceite alternativa neutra e recusa sem prejuízo.')),
 jsonb_build_object('heading','Direitos, segurança e serviços','content',jsonb_build_array('Ensine liberdade de consciência como direito de ter, mudar ou não ter religião ou convicção, dentro do respeito aos direitos das outras pessoas.','Em casos de discriminação, priorize interromper a conduta, proteger a pessoa afetada, registrar pelos canais institucionais e acionar responsáveis e rede de proteção conforme o protocolo escolar; não obrigue confronto, mediação ou reconciliação.','Apoio religioso ou espiritual pode coexistir com cuidado profissional, mas não substitui saúde, emergência, proteção civil, assistência social ou políticas públicas. O professor não diagnostica nem recomenda prática religiosa.')),
 jsonb_build_object('heading','Investigação crítica e acessível','content',jsonb_build_array('Pesquise contribuições e controvérsias por ações, datas, contexto, fontes confiáveis e efeitos; não use número de seguidores, fama ou identidade religiosa como prova de mérito.','Reconheça diversidade interna, lideranças religiosas e seculares, filosofias de vida e pessoas sem religião. Evite generalizar, hierarquizar ou transformar uma liderança em porta-voz total.','Ofereça texto segmentado, glossário visual, legenda, transcrição, descrição de imagem, áudio regulável, casos fictícios, cartões e organizadores; aceite comunicação alternativa, seleção, escrita, digitação, fala opcional ou áudio privado.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com direito aplicável, evidência, contexto, efeito e proposta segura, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Identificar o caso','instruction','Leia um caso fictício e identifique prática, pessoas envolvidas, direito, papel de liderança e serviço profissional quando pertinente.','activity','Classifique cartões de fato, interpretação, direito, apoio e ação segura sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, áudio regulável, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Verificar fontes e efeitos','instruction','Compare duas fontes, separe afirmação de evidência e reconheça diversidade interna e limites.','activity','Complete quadro com autoria, data, contexto, ação, efeito, direito e informação ainda necessária.','support','Modelo resolvido, cartões móveis, pistas graduadas, código por forma e rótulo, tempo ampliado e mediação.'),jsonb_build_object('title','3. Propor resposta ética','instruction','Escolha uma resposta que preserve autonomia, dignidade, segurança, direitos e serviços adequados.','activity','Monte sequência de ação para caso fictício, sem revelar crença ou experiência pessoal e sem apresentação pública obrigatória.','support','Apontar, selecionar, comunicação alternativa, mapa, digitação, escrita, fala opcional, áudio privado ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fato, direito e papel sem presumir crença, intenção ou identidade.'),jsonb_build_object('page',2,'answer','Usa fonte e contexto para avaliar ação, efeito, contribuição ou limite sem generalização.'),jsonb_build_object('page',3,'answer','Propõe resposta que protege autonomia e direitos e encaminha ao serviço adequado quando necessário.','teacher_note','Registre estratégia e apoio eficaz; não registre religião, não religião, mudança de crença, voz, experiência difícil, opinião ou vínculo comunitário.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','rights_map','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_position',true,'no_forced_prayer',true,'no_forced_meditation',true,'no_forced_recitation',true,'no_forced_ritual',true,'no_spiritual_counseling_by_teacher',true,'no_vulnerability_simulation',true,'fictional_cases_only',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_conversion_history_disclosure',true,'no_family_religion_disclosure',true,'no_worship_place_disclosure',true,'no_vulnerability_disclosure',true,'privacy_preserving',true,'freedom_of_conscience',true,'human_rights_framework',true,'anti_discrimination_response',true,'no_forced_confrontation',true,'no_forced_reconciliation',true,'professional_services_not_replaced',true,'no_diagnosis',true,'source_context_effect_check',true,'internal_diversity',true,'religious_secular_and_nonreligious_inclusion',true,'no_leader_generalization',true,'no_belief_hierarchy',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-7ano/oficinas-bncc/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ensino Religioso do 8º ano completo (EF08ER01–EF08ER07).
-- A BNCC oficial inclui EF08ER07; a aula antiga da unidade 6 tem o código EF08ER06 desativado pelo curso.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF08ER01','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-1/aula-01-crencas-escolhas.ts','Crenças, convicções e escolhas','Discutir como crenças e convicções podem influenciar escolhas pessoais e coletivas sem solicitar posicionamento íntimo do estudante.'),
('EF08ER02','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-2/aula-01-etica-tradicoes.ts','Princípios éticos das tradições e filosofias','Analisar filosofias de vida, manifestações e tradições religiosas, destacando princípios éticos com contexto e diversidade interna.'),
('EF08ER03','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-3/aula-01-vida-e-morte.ts','Concepções de mundo, vida e morte','Analisar concepções de mundo, vida e morte em diferentes doutrinas de modo informativo, não gráfico e sem relatos pessoais.'),
('EF08ER04','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-4/aula-01-religiao-esfera-publica.ts','Religião e esfera pública','Discutir como filosofias, tradições e instituições religiosas podem influenciar política, saúde, educação e economia usando fontes e casos coletivos.'),
('EF08ER05','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-5/aula-01-estado-laico.ts','Possibilidades e limites na esfera pública','Debater possibilidades e limites da atuação de tradições religiosas na esfera pública à luz do Estado laico, dos direitos e da igualdade.'),
('EF08ER06','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-5/aula-02-liberdade-politicas-publicas.ts','Liberdade em práticas, projetos e políticas','Analisar práticas, projetos e políticas públicas que promovam liberdade de pensamento, crença e convicção com evidências verificáveis.'),
('EF08ER07','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-7/aula-01-transmissao-tradicoes.ts','Religiões, mídias e tecnologias','Analisar usos de mídias e tecnologias por diferentes denominações religiosas, considerando finalidade, autoria, alcance, privacidade e segurança digital.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional e segura','content',jsonb_build_array('Estude crenças, filosofias, doutrinas e instituições como fenômenos culturais e sociais; conhecer não significa acreditar, concordar, aderir ou praticar.','Não conduza oração, rito, debate confessional, campanha política ou religiosa, simulação de luto, cerimônia, aconselhamento espiritual ou representação de identidade. Use casos fictícios ou coletivos.','Não solicite crença, não crença, religião familiar, opinião política, experiência de perda, informação de saúde, comunidade frequentada ou conteúdo de conta pessoal. Aceite alternativa neutra e recusa sem prejuízo.')),
 jsonb_build_object('heading','Esfera pública e direitos','content',jsonb_build_array('Estado laico não significa Estado contra religiões: garante liberdade de consciência e tratamento público igual, sem religião oficial nem imposição de crença.','Analise influência na política, saúde, educação e economia por fontes, ações, interesses, efeitos, direitos e limites. Diferencie opinião religiosa, evidência científica, norma jurídica e política pública.','Não apresente prática religiosa como substituta de saúde, proteção, educação ou serviço público. O professor não diagnostica, prescreve, recomenda adesão religiosa nem dirige posição político-partidária.')),
 jsonb_build_object('heading','Mídia, fontes e acessibilidade','content',jsonb_build_array('Use postagens e perfis fictícios ou capturas anonimizadas fornecidas pelo professor. Não exija conta, acesso a rede social, contato com desconhecidos, publicação, rastreamento, geolocalização ou coleta de dados.','Verifique autoria, data, fonte, finalidade, patrocínio, edição e evidência; discuta alcance e recomendação algorítmica sem afirmar que popularidade comprova verdade ou representatividade.','Antecipe vocabulário; ofereça texto segmentado, descrição de imagem, legenda, transcrição, áudio regulável, cartões e matriz de fontes. Aceite apontar, comunicação alternativa, escrita, digitação, fala opcional ou áudio privado.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com fonte, contexto, direito, evidência e efeito, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Identificar e classificar','instruction','Leia caso fictício ou fonte fornecida e diferencie crença, princípio ético, fato, opinião, evidência, norma e política.','activity','Classifique quatro elementos relacionados a '||lower(title)||' sem declarar opinião ou experiência pessoal.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, descrição de imagem, legenda, transcrição e áudio regulável.'),jsonb_build_object('title','2. Verificar contexto e direitos','instruction','Registre autoria, data, finalidade, interesse, público, direito envolvido, evidência e limite.','activity','Compare duas fontes ou propostas usando matriz acessível e dados públicos agregados ou fictícios.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, código por forma e rótulo e mediação.'),jsonb_build_object('title','3. Explicar efeitos e limites','instruction','Explique influência, efeito, direito e limite sem campanha, exposição pessoal ou publicação.','activity','Produza quadro, mapa, sequência, texto curto ou áudio privado para o caso fornecido.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Classifica elementos sem presumir crença, convicção, saúde, luto ou posição política.'),jsonb_build_object('page',2,'answer','Compara fontes e identifica direito, evidência, interesse e limite pertinente.'),jsonb_build_object('page',3,'answer','Explica influência e efeito com linguagem respeitosa, fonte e proposta compatível com direitos.','teacher_note','Registre apenas estratégia e apoio eficaz; não registre crença, política, saúde, perda, voz, conta, comunidade ou histórico digital.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','rights_map','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_public_position',true,'no_forced_religious_practice',true,'no_grief_simulation',true,'historical_and_doctrinal_non_graphic',true,'fictional_or_collective_cases',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_political_opinion_collection',true,'no_health_disclosure',true,'no_loss_disclosure',true,'privacy_preserving',true,'secular_state_accuracy',true,'freedom_of_conscience',true,'human_rights_framework',true,'science_law_religion_distinction',true,'professional_services_not_replaced',true,'no_diagnosis',true,'no_partisan_direction',true,'provided_fictional_or_anonymized_media',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_tracking',true,'no_geolocation',true,'source_date_purpose_sponsorship_check',true,'algorithmic_literacy',true,'popularity_is_not_evidence',true,'internal_diversity',true,'no_belief_hierarchy',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-8ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Ensino Religioso do 9º ano completo.
-- Fontes mapeadas pelos campos BNCC ativos; a unidade 4 é aprofundamento complementar desativado no curso.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF09ER01','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-1/aula-01-cuidado-vida.ts','Princípios para o cuidado da vida','Analisar princípios e orientações para o cuidado da vida em tradições religiosas e filosofias de vida sem prescrição religiosa ou coleta de experiência pessoal.'),
('EF09ER02','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-1/aula-02-vida-nas-midias.ts','Valorização da vida nas mídias','Analisar como mídias podem valorizar ou desrespeitar a vida e a dignidade usando materiais selecionados, não gráficos e com leitura crítica.'),
('EF09ER03','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-5/aula-01-sentido-vida.ts','Sentidos do viver e do morrer','Identificar sentidos do viver e do morrer em mitos fundantes por análise cultural informativa, sem depoimentos pessoais ou prática religiosa.'),
('EF09ER04','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-2/aula-01-vida-morte.ts','Concepções de vida, morte e ritos fúnebres','Identificar concepções de vida e morte por descrições contextualizadas de ritos fúnebres, sem imagens gráficas, encenação ou exposição de perda.'),
('EF09ER05','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-3/aula-01-imortalidade-ancestralidade.ts','Ideias de imortalidade','Analisar ideias de ancestralidade, reencarnação, transmigração, ressurreição e memória com diversidade interna e sem hierarquizar crenças.'),
('EF09ER06','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-7/aula-01-sociedades-justas.ts','Coexistência e dignidade humana','Reconhecer coexistência, respeito à vida e dignidade humana como referências éticas para relações plurais e respostas à discriminação.'),
('EF09ER07','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-6/aula-01-projeto-vida.ts','Princípios éticos e projetos de vida','Identificar princípios familiares, religiosos, culturais e seculares que podem sustentar projetos de vida sem exigir revelação de convicções ou planos pessoais.'),
('EF09ER08','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-6/aula-01-projeto-vida.ts','Construção ética de projetos de vida','Construir ou analisar projeto de vida assentado em valores éticos, com opção fictícia, direito de revisão e proteção de dados pessoais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional e sensível','content',jsonb_build_array('Apresente doutrinas, mitos, ritos, valores e filosofias como objetos de estudo. Conhecer não significa acreditar, concordar, aderir ou praticar.','Vida e morte recebem tratamento informativo e não gráfico. Não mostre conteúdo perturbador, não simule rito fúnebre ou situação de perda e não solicite relato de luto, saúde, risco, crença ou experiência íntima.','Não conduza oração, rito, aconselhamento espiritual, debate confessional ou representação de identidade. Ofereça material alternativo neutro, pausa ou recusa sem prejuízo.')),
 jsonb_build_object('heading','Mídia, dignidade e coexistência','content',jsonb_build_array('Use matérias fictícias, anonimizadas ou previamente selecionadas; não peça busca aberta por violência, sofrimento ou conteúdo sensível. Prefira descrição verbal neutra e avise previamente o tema.','Verifique autoria, data, fonte, evidência, contexto, enquadramento, pessoas ouvidas, interesse e efeito. Não compartilhe humilhação nem exposição para demonstrar desrespeito.','Em discriminação, interrompa a conduta, proteja a pessoa afetada e siga o protocolo escolar. Não obrigue confronto, relato público, mediação ou reconciliação.')),
 jsonb_build_object('heading','Projeto de vida acessível e privado','content',jsonb_build_array('Permita analisar personagem fictício ou plano hipotético em vez de expor objetivos, religião, família, relacionamento, saúde, finanças ou futuro do estudante.','Apresente projeto de vida como flexível e revisável, não como promessa permanente nem previsão de sucesso; evite comparar ritmos, carreiras ou escolhas entre estudantes.','Aceite cartões, linha do tempo fictícia, mapa de valores, comunicação alternativa, escrita, digitação, fala opcional ou áudio privado. Compartilhamento com turma ou família depende de escolha explícita do estudante.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com fonte, contexto, dignidade, princípio ético e justificativa, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler e contextualizar','instruction','Identifique gênero, fonte, comunidade, época, princípio, mensagem e finalidade no material fornecido.','activity','Classifique quatro elementos relacionados a '||lower(title)||' sem revelar crença, perda ou plano pessoal.','support','Texto segmentado, leitura fácil, aviso prévio do tema, glossário visual, fonte ampliada, descrição neutra, legenda, transcrição e áudio regulável.'),jsonb_build_object('title','2. Comparar com dignidade','instruction','Compare concepções, princípios ou representações por evidências, sem hierarquia e sem imagens perturbadoras.','activity','Complete quadro com contexto, princípio, evidência, semelhança, diferença e cuidado ético.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, pausa, alternativa neutra e mediação.'),jsonb_build_object('title','3. Aplicar a caso fictício','instruction','Use os princípios estudados para analisar mídia, convivência ou projeto hipotético.','activity','Produza sequência, mapa, texto curto ou áudio privado com escolha justificada e possibilidade de revisão.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fonte, contexto e princípio sem presumir crença, perda ou experiência.'),jsonb_build_object('page',2,'answer','Compara concepções e representações com dignidade, evidência e sem hierarquização.'),jsonb_build_object('page',3,'answer','Aplica princípio ético a caso fictício com justificativa, proteção e possibilidade de revisão.','teacher_note','Registre somente estratégia e apoio eficaz; não registre crença, saúde, perda, plano pessoal, voz, família, relacionamento, finanças ou futuro.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','fictional_timeline','values_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'neutral_image_description',true,'visual_glossary',true,'visual_schedule',true,'content_preview',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_sharing',true,'no_forced_religious_practice',true,'no_funeral_simulation',true,'non_graphic_life_and_death',true,'no_open_search_for_distressing_media',true,'fictional_anonymized_or_curated_media',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_grief_disclosure',true,'no_health_disclosure',true,'no_risk_disclosure',true,'no_personal_project_disclosure',true,'privacy_preserving',true,'source_context_framing_effect_check',true,'do_not_reshare_humiliation',true,'anti_discrimination_response',true,'no_forced_confrontation',true,'no_forced_reconciliation',true,'internal_diversity',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'fictional_project_option',true,'project_is_flexible_and_revisable',true,'no_student_comparison',true,'student_controlled_sharing',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-9ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
