BEGIN;
-- Biblioteca Inclusiva · Filosofia do 6º ano completa.
-- EF06FI01–EF06FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06FI01','src/escola-brilha/curso-v4/filosofia-6ano/unidade-1/aula-01-espanto-filosofico.ts','Espanto e pergunta filosófica','Reconhecer admiração, dúvida e pergunta como pontos de partida da investigação filosófica.'),
('EF06FI02','src/escola-brilha/curso-v4/filosofia-6ano/unidade-2/aula-01-mito-ao-logos.ts','Mito, logos e primeiros filósofos','Comparar explicações míticas e investigações racionais em seus contextos históricos sem tratar mito como simples mentira.'),
('EF06FI03','src/escola-brilha/curso-v4/filosofia-6ano/unidade-3/aula-01-socrates-maieutica.ts','Sócrates e investigação por perguntas','Aplicar perguntas de esclarecimento, razões e consequências a afirmações fictícias sem constranger ou interrogar colegas.'),
('EF06FI04','src/escola-brilha/curso-v4/filosofia-6ano/unidade-4/aula-01-argumento-vs-opiniao.ts','Argumento, opinião e falácias','Distinguir opinião, premissa, conclusão, evidência e falácias em exemplos adequados à idade.'),
('EF06FI05','src/escola-brilha/curso-v4/filosofia-6ano/unidade-5/aula-01-etica-amizade.ts','Ética e concepções de amizade','Analisar concepções filosóficas de amizade e vida boa sem avaliar, classificar ou expor relações pessoais do estudante.'),
('EF06FI06','src/escola-brilha/curso-v4/filosofia-6ano/unidade-6/aula-01-caverna-platao.ts','Alegoria da caverna e conhecimento','Interpretar a alegoria da caverna como investigação sobre aparência, opinião, conhecimento e educação, com abordagem histórica não gráfica.'),
('EF06FI07','src/escola-brilha/curso-v4/filosofia-6ano/unidade-7/aula-01-coragem-pensar.ts','Autonomia intelectual','Desenvolver autonomia para perguntar, verificar, mudar de posição diante de razões e reconhecer limites do próprio conhecimento.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar', 'fundamental_2','6º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Identificação curricular correta','content',jsonb_build_array('Este material é um componente autoral complementar do NeuroBrilha. O código '||code||' é interno e não deve ser apresentado como habilidade oficial da BNCC do Ensino Fundamental.','Use os códigos para organização e busca dentro do aplicativo, mantendo nos relatórios a indicação currículo complementar.','Apresente ideias filosóficas com contexto, autoria, época e possibilidade de crítica; não transforme a posição de um filósofo em resposta obrigatória ou verdade final.')),
 jsonb_build_object('heading','Diálogo protegido','content',jsonb_build_array('Discussão oral, debate, pergunta socrática e apresentação são opcionais. Aceite análise silenciosa, cartões, escrita, digitação, comunicação alternativa ou áudio privado.','Use afirmações, dilemas e personagens fictícios. Não peça exposição de religião, política, amizade, conflito, medo, família, identidade, experiência íntima ou opinião diante da turma.','Discordâncias devem examinar ideias e razões, sem ataque pessoal, ridicularização, pressão do grupo ou obrigação de defender posição contrária à própria convicção. Permita mudar de resposta.')),
 jsonb_build_object('heading','Fontes, história e acessibilidade','content',jsonb_build_array('Use paráfrases, excertos breves autorizados ou em domínio público e traduções identificadas. Diferencie citação, paráfrase e interpretação; não reproduza obras extensas.','Aborde conflitos e acontecimentos históricos de forma informativa e não gráfica, sem encenação imersiva. Mito é narrativa cultural, não sinônimo de mentira; logos não torna povos ou épocas inferiores.','Antecipe vocabulário; ofereça texto segmentado, glossário visual, mapa de argumento, legenda, transcrição, descrição de imagem, áudio regulável, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Identifica pergunta, conceito, razão, evidência e conclusão em quatro de cinco itens, justificando no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Perguntar e definir','instruction','Escolha um caso fictício, destaque a pergunta e esclareça os conceitos sem perguntar sobre a vida do colega.','activity','Associe quatro perguntas de esclarecimento a afirmações sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, áudio regulável, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Mapear razões','instruction','Separe afirmação, premissa, evidência, inferência, conclusão e possível falácia.','activity','Complete mapa de argumento e indique qual informação ainda seria necessária.','support','Modelo resolvido, cartões móveis, cores com rótulos e formas, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Comparar e revisar','instruction','Compare duas interpretações e revise a resposta quando surgir razão melhor.','activity','Produza quadro, sequência, texto curto ou áudio privado, citando o material fornecido.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Formula pergunta pertinente e define conceito sem exposição pessoal.'),jsonb_build_object('page',2,'answer','Distingue premissa, evidência e conclusão e identifica limite ou falácia.'),jsonb_build_object('page',3,'answer','Compara interpretações, justifica e admite revisão diante de nova razão.','teacher_note','Registre somente estratégia e apoio eficaz; não registre voz, opinião, amizade, medo, crença, política, família ou experiência pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_public_opinion',true,'fictional_cases_only',true,'no_personal_friendship_disclosure',true,'no_belief_disclosure',true,'no_political_opinion_collection',true,'no_fear_disclosure',true,'privacy_preserving',true,'idea_not_person',true,'no_ridicule',true,'no_peer_pressure',true,'right_to_revise',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'myth_is_not_lie',true,'no_cultural_hierarchy',true,'brief_authorized_or_public_domain_excerpts',true,'citation_paraphrase_interpretation_distinction',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Filosofia do 7º ano completa.
-- EF07FI01–EF07FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF07FI01','src/escola-brilha/curso-v4/filosofia-7ano/unidade-1/aula-01-justica-agora.ts','Platão e a pergunta pela justiça','Analisar concepções platônicas de justiça por conceitos e situações fictícias, distinguindo descrição histórica de concordância pessoal.'),
('EF07FI02','src/escola-brilha/curso-v4/filosofia-7ano/unidade-2/aula-01-aristoteles-vida-boa.ts','Aristóteles, virtude e vida boa','Relacionar virtude, hábito, meio-termo e florescimento humano sem prescrever um modelo único de vida boa.'),
('EF07FI03','src/escola-brilha/curso-v4/filosofia-7ano/unidade-3/aula-01-estoicos-epicuristos.ts','Estoicos, epicuristas e modos de viver','Comparar propostas estoicas e epicuristas em contexto histórico sem convertê-las em aconselhamento emocional ou regra de conduta.'),
('EF07FI04','src/escola-brilha/curso-v4/filosofia-7ano/unidade-4/aula-01-fe-e-razao.ts','Fé e razão na filosofia medieval','Analisar relações entre fé e razão em pensadores medievais com abordagem histórica, não confessional e sem hierarquizar crença ou não crença.'),
('EF07FI05','src/escola-brilha/curso-v4/filosofia-7ano/unidade-5/aula-01-contrato-social.ts','Teorias do contrato social','Comparar ideias de Hobbes, Locke e Rousseau sobre autoridade, direitos e pacto político usando sociedades hipotéticas.'),
('EF07FI06','src/escola-brilha/curso-v4/filosofia-7ano/unidade-6/aula-01-liberdade-igualdade.ts','Liberdade, igualdade e direitos','Investigar ideias iluministas, Revolução Francesa e direitos humanos, reconhecendo contexto, exclusões históricas e ampliação de direitos.'),
('EF07FI07','src/escola-brilha/curso-v4/filosofia-7ano/unidade-7/aula-01-justica-hoje.ts','Rawls e justiça contemporânea','Aplicar critérios de justiça e o recurso hipotético do véu da ignorância a casos coletivos sem coletar vulnerabilidades ou posições políticas pessoais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','7º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Identificação e contexto','content',jsonb_build_array('Este é currículo autoral complementar. O código '||code||' organiza o NeuroBrilha e não é habilidade oficial da BNCC do Ensino Fundamental.','Apresente cada teoria com autor, época, problema, conceitos, argumentos, críticas e limites; estudar uma teoria não exige concordar com ela.','Evite narrativas de progresso simples: reconheça contribuições, exclusões históricas e outras tradições de pensamento sem declarar um povo, período ou autor superior.')),
 jsonb_build_object('heading','Diálogo, religião e política','content',jsonb_build_array('Debate, exposição oral e defesa de posição são opcionais. Use cidades, regras, dilemas e decisões fictícias ou coletivas, nunca votação partidária ou avaliação da opinião pessoal.','Na relação fé e razão, não conduza prática religiosa nem peça crença, não crença ou tradição familiar. Apresente interpretações religiosas, seculares e acadêmicas com respeito.','Ataque ideias e argumentos, não pessoas. Não aceite ridicularização, pressão do grupo ou obrigação de representar identidade, grupo político, classe social, religião ou personagem histórico.')),
 jsonb_build_object('heading','Segurança, direitos e acessibilidade','content',jsonb_build_array('Revoluções, punições e conflitos históricos recebem abordagem informativa e não gráfica, sem dramatização imersiva. Direitos humanos funcionam como referência de dignidade e proteção.','Exercícios de justiça usam dados públicos agregados ou cenários fictícios; não coletem renda, religião, saúde, deficiência, conflito familiar, opinião política ou experiência de discriminação da turma.','Ofereça texto segmentado, glossário visual, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Compara duas posições por problema, conceito, argumento, consequência e limite, justificando no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar a teoria','instruction','Identifique autor, época, problema e conceitos no material fornecido.','activity','Associe cartões de contexto e conceitos sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Comparar argumentos','instruction','Reconstrua duas posições por premissas, conclusão, consequência e crítica.','activity','Complete matriz comparativa usando casos fictícios e evidências do material.','support','Modelo resolvido, cartões móveis, mapa de argumentos, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Aplicar critério de justiça','instruction','Avalie um caso coletivo fictício por direitos, distribuição, liberdade, igualdade e efeitos.','activity','Produza quadro, sequência, texto curto ou áudio privado e indique um limite da solução.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa teoria, problema e conceitos sem atribuir posição ao estudante.'),jsonb_build_object('page',2,'answer','Compara argumentos, consequências e críticas com evidência.'),jsonb_build_object('page',3,'answer','Aplica critério de justiça e reconhece direito, efeito e limite.','teacher_note','Registre somente estratégia e apoio; não registre crença, política, renda, saúde, deficiência, família ou discriminação pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','comparison_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'fictional_or_collective_cases',true,'no_partisan_vote',true,'non_confessional_faith_reason',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_identity_impersonation',true,'idea_not_person',true,'no_ridicule',true,'no_peer_pressure',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'human_rights_framework',true,'aggregated_or_fictional_data',true,'no_income_collection',true,'no_health_collection',true,'no_disability_disclosure',true,'no_family_conflict_disclosure',true,'no_political_opinion_collection',true,'no_discrimination_experience_collection',true,'privacy_preserving',true,'historical_exclusions_acknowledged',true,'no_cultural_hierarchy',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-7ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Filosofia do 8º ano completa.
-- EF08FI01–EF08FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF08FI01','src/escola-brilha/curso-v4/filosofia-8ano/unidade-1/aula-01-duvida-metodica.ts','Descartes e dúvida metódica','Distinguir dúvida metódica de negar tudo indiscriminadamente e reconstruir o argumento cartesiano em contexto histórico.'),
('EF08FI02','src/escola-brilha/curso-v4/filosofia-8ano/unidade-2/aula-01-empirismo-racionalismo.ts','Empirismo e racionalismo','Comparar teses empiristas e racionalistas sobre conhecimento, experiência e razão sem reduzir tradições diversas a dois times rígidos.'),
('EF08FI03','src/escola-brilha/curso-v4/filosofia-8ano/unidade-3/aula-01-kant-revolucao-copernicana.ts','Kant, conhecimento e moral','Analisar a proposta kantiana sobre experiência, categorias e universalização moral, reconhecendo interpretações e limites.'),
('EF08FI04','src/escola-brilha/curso-v4/filosofia-8ano/unidade-4/aula-01-hegel-dialetica.ts','Hegel, dialética e história','Interpretar contradição, reconhecimento e mudança histórica em Hegel, indicando que a fórmula tese-antítese-síntese é uma simplificação didática contestada.'),
('EF08FI05','src/escola-brilha/curso-v4/filosofia-8ano/unidade-5/aula-01-marx-trabalho-alienacao.ts','Marx, trabalho e alienação','Analisar trabalho, alienação, classe e crítica do capitalismo como teoria histórica, sem propaganda partidária ou coleta de situação econômica pessoal.'),
('EF08FI06','src/escola-brilha/curso-v4/filosofia-8ano/unidade-6/aula-01-nietzsche-alem-bem-mal.ts','Nietzsche e genealogia dos valores','Examinar a genealogia dos valores e a transvaloração em contexto, esclarecendo que o termo além-do-humano não define superioridade racial, corporal, de gênero ou deficiência.'),
('EF08FI07','src/escola-brilha/curso-v4/filosofia-8ano/unidade-7/aula-01-existencialismo-liberdade.ts','Existencialismo, liberdade e responsabilidade','Analisar liberdade, situação, responsabilidade e construção social em Sartre e Beauvoir sem transformar a aula em aconselhamento pessoal ou cobrança por escolhas de vida.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','8º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Enquadramento e precisão','content',jsonb_build_array('Este é currículo autoral complementar. O código '||code||' é interno do NeuroBrilha e não uma habilidade oficial da BNCC do Ensino Fundamental.','Apresente autor, época, problema, conceitos, argumento, críticas e recepção. Estudar uma teoria não exige concordar com ela nem aplicá-la à vida pessoal.','Marque simplificações didáticas: empirismo e racionalismo possuem variações; tese-antítese-síntese não deve ser atribuída como fórmula literal universal de Hegel; termos de Nietzsche não autorizam hierarquia entre pessoas.')),
 jsonb_build_object('heading','Política, religião e identidade','content',jsonb_build_array('Use fontes históricas e casos fictícios. Não conduza propaganda partidária, votação política, campanha, ataque ao capitalismo ou defesa obrigatória de qualquer sistema econômico.','Não peça opinião sobre religião, política, trabalho da família, renda, classe social, gênero, deficiência, relacionamento, futuro ou experiência de discriminação.','Debate e defesa pública são opcionais. Avalie razões e evidências, não identidade, concordância com o professor ou firmeza da fala; permita posição suspensa e revisão.')),
 jsonb_build_object('heading','Segurança e acessibilidade','content',jsonb_build_array('Guerras, exploração e opressão recebem tratamento histórico informativo e não gráfico, sem encenação de dominação, trabalho explorado ou discriminação.','Existencialismo é estudado por conceitos e personagens fictícios, sem aconselhamento emocional, diagnóstico ou solicitação de experiência íntima. Encaminhe sinais de sofrimento pelo protocolo escolar, sem investigar diante da turma.','Ofereça texto segmentado, glossário, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Compara duas posições por problema, conceito, argumento, evidência, consequência e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Reconstruir o problema','instruction','Identifique autor, época, pergunta, conceitos e tese no material fornecido.','activity','Associe cartões de problema, tese e conceito sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Testar o argumento','instruction','Organize premissas, inferência, conclusão, objeção e resposta sem transformar teoria em identidade.','activity','Complete mapa de argumento e compare uma crítica documentada.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, contraste por forma e rótulo e mediação.'),jsonb_build_object('title','3. Aplicar a caso fictício','instruction','Use um cenário fictício para analisar conhecimento, trabalho, valores ou liberdade.','activity','Produza quadro, sequência, texto curto ou áudio privado, registrando consequência e limite.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa problema, tese e conceito sem atribuir posição pessoal ao estudante.'),jsonb_build_object('page',2,'answer','Reconstrói argumento, objeção e resposta com fonte e ressalva pertinente.'),jsonb_build_object('page',3,'answer','Aplica conceito a caso fictício e reconhece consequência e limite.','teacher_note','Registre apenas estratégia e apoio; não registre crença, política, renda, trabalho familiar, classe, gênero, deficiência, relação ou experiência íntima.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','comparison_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'right_to_suspend_judgment',true,'right_to_revise',true,'fictional_cases_only',true,'no_partisan_propaganda',true,'no_political_vote',true,'no_economic_system_advocacy_requirement',true,'no_belief_disclosure',true,'no_political_opinion_collection',true,'no_family_work_disclosure',true,'no_income_collection',true,'no_class_disclosure',true,'no_gender_disclosure',true,'no_disability_disclosure',true,'no_relationship_disclosure',true,'privacy_preserving',true,'historical_non_graphic',true,'no_oppression_roleplay',true,'no_exploitation_simulation',true,'no_emotional_counseling',true,'no_diagnosis',true,'school_support_protocol',true,'hegel_formula_caveat',true,'empiricism_rationalism_nuance',true,'nietzsche_term_no_human_hierarchy',true,'idea_not_person',true,'source_and_reception_check',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-8ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
-- Biblioteca Inclusiva · Filosofia do 9º ano completa.
-- EF09FI01–EF09FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF09FI01','src/escola-brilha/curso-v4/filosofia-9ano/unidade-1/aula-01-frankfurt.ts','Escola de Frankfurt e indústria cultural','Analisar indústria cultural, razão instrumental e mídia como teorias críticas, distinguindo consumo, interpretação e evidência sem condenar gostos pessoais.'),
('EF09FI02','src/escola-brilha/curso-v4/filosofia-9ano/unidade-2/aula-01-fenomenologia-hermeneutica.ts','Fenomenologia e hermenêutica','Comparar descrição da experiência e interpretação situada em Husserl, Heidegger e Gadamer sem exigir relatos íntimos.'),
('EF09FI03','src/escola-brilha/curso-v4/filosofia-9ano/unidade-3/aula-01-estruturalismo-pos.ts','Estruturalismo e pós-estruturalismo','Analisar discurso, poder, diferença e desconstrução como ferramentas interpretativas, sem vigilância ou exposição de identidades da turma.'),
('EF09FI04','src/escola-brilha/curso-v4/filosofia-9ano/unidade-4/aula-01-filosofia-linguagem.ts','Wittgenstein e jogos de linguagem','Investigar significado, uso, contexto e jogos de linguagem por exemplos fictícios, respeitando variação linguística e comunicação alternativa.'),
('EF09FI05','src/escola-brilha/curso-v4/filosofia-9ano/unidade-5/aula-01-etica-bioetica.ts','Ética contemporânea e bioética','Aplicar princípios bioéticos a casos hipotéticos adequados à idade, distinguindo análise filosófica de orientação médica, jurídica ou científica.'),
('EF09FI06','src/escola-brilha/curso-v4/filosofia-9ano/unidade-6/aula-01-filosofia-politica-atual.ts','Hannah Arendt e esfera pública','Analisar responsabilidade, ação, esfera pública e conceitos de Arendt em contexto histórico não gráfico, sem simulação de violência ou propaganda partidária.'),
('EF09FI07','src/escola-brilha/curso-v4/filosofia-9ano/unidade-7/aula-01-filosofia-brasileira-decolonial.ts','Filosofia brasileira e pensamento decolonial','Analisar contribuições de Paulo Freire, Ailton Krenak e pensamentos decoloniais com fontes, contexto e protagonismo dos povos citados.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','9º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Enquadramento e precisão','content',jsonb_build_array('Este material é currículo autoral complementar. O código '||code||' é interno do NeuroBrilha e não habilidade oficial da BNCC do Ensino Fundamental.','Apresente autor, contexto, problema, conceito, argumento, crítica e recepção; estudar uma teoria não exige concordar com ela. Diferencie descrição da tese, aplicação e avaliação.','Evite transformar escolas filosóficas em rótulos fechados. Reconheça divergências entre autores e leituras acadêmicas, além da autoria e diversidade dos pensamentos brasileiros, indígenas e decoloniais.')),
 jsonb_build_object('heading','Temas públicos e sensíveis','content',jsonb_build_array('Use casos fictícios, fontes públicas e dados agregados. Não faça propaganda, votação partidária, teste ideológico ou coleta de opinião política, religião, saúde, genética, família, consumo, identidade ou experiência de discriminação.','Bioética é análise de princípios e conflitos, não orientação médica, jurídica, genética ou científica. Não proponha experimento, procedimento corporal, diagnóstico ou decisão real de saúde; encaminhe dúvidas individuais a responsáveis e profissionais adequados.','Violência histórica, autoritarismo, perseguição e opressão recebem abordagem informativa e não gráfica, sem imagens perturbadoras, dramatização, simulação ou atribuição de papel de vítima ou agressor.')),
 jsonb_build_object('heading','Linguagem, mídia e acesso','content',jsonb_build_array('Não classifique gosto cultural, fala, sotaque, língua, comunicação alternativa ou repertório familiar como inferior. Analise produtos midiáticos fictícios ou fornecidos sem acessar conta pessoal.','Para pensamentos indígenas, use nome do povo quando a fonte permitir, autoria identificada e materiais produzidos ou validados por pessoas e instituições indígenas; não apresente uma voz como representante de todos os povos.','Ofereça texto segmentado, glossário, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa, modelo resolvido e múltiplos modos de resposta.')),
 jsonb_build_object('heading','Critério','content','Compara duas interpretações por fonte, contexto, conceito, argumento, efeito e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e definir','instruction','Identifique autor, época, problema, conceitos e fonte no material fornecido.','activity','Associe cartões de contexto, conceito e exemplo sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Reconstruir e comparar','instruction','Organize tese, razões, exemplo, objeção, resposta e limite de duas interpretações.','activity','Complete mapa de argumentos usando somente fontes e casos fornecidos.','support','Modelo resolvido, cartões móveis, matriz de fontes, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Aplicar com limites','instruction','Analise caso fictício de mídia, linguagem, bioética ou esfera pública, distinguindo reflexão de orientação profissional.','activity','Produza quadro, sequência, texto curto ou áudio privado com fonte, efeito, direito e limite.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa autor, fonte, problema e conceito sem atribuir identidade ou opinião ao estudante.'),jsonb_build_object('page',2,'answer','Compara argumentos, objeções e limites com evidência.'),jsonb_build_object('page',3,'answer','Aplica conceito a caso fictício e distingue análise filosófica de decisão ou serviço profissional.','teacher_note','Registre apenas estratégia e apoio; não registre voz, política, religião, saúde, genética, família, consumo, identidade ou discriminação pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'content_preview',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'fictional_cases_only',true,'aggregated_public_data_only',true,'no_partisan_propaganda',true,'no_political_vote',true,'no_ideological_test',true,'no_political_opinion_collection',true,'no_belief_disclosure',true,'no_health_disclosure',true,'no_genetic_disclosure',true,'no_family_disclosure',true,'no_consumption_profile_collection',true,'no_identity_disclosure',true,'no_discrimination_experience_collection',true,'privacy_preserving',true,'bioethics_not_medical_legal_or_genetic_advice',true,'no_body_experiment',true,'no_diagnosis',true,'professional_referral',true,'historical_non_graphic',true,'no_disturbing_images',true,'no_oppression_roleplay',true,'no_victim_aggressor_assignment',true,'no_personal_account_required',true,'no_cultural_taste_hierarchy',true,'linguistic_dignity',true,'aac_dignity',true,'indigenous_authorship_and_authority',true,'no_pan_indigenous_generalization',true,'source_context_reception_check',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-9ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
COMMIT;
