import type { AulaV4 } from "../../types";
import { url as bola } from "@/assets/neuro-treino/objetos/bola.png.asset.json";

export const aula06_eventosProvaveis: AulaV4 = {
  slug: "u7-06-eventos-provaveis", titulo: "Eventos e Possibilidades", iconeTrilha: "🎯", bncc: ["EF02MA21"], duracaoMin: 20,
  momento01_motivacao: { titulo: "A Sacola Surpresa", historia: "Uma sacola tem 8 bolas azuis, 2 amarelas e nenhuma verde. O que é muito provável, pouco provável ou impossível?", imagemUrl: bola },
  momento02_exploracao: { instrucao: "Compare as quantidades sem retirar nenhuma bola.", cenas: [{ tipo: "grupoItens", imagemUrl: bola, quantidade: 8, rotulo: "8 azuis" }, { tipo: "grupoItens", imagemUrl: bola, quantidade: 2, rotulo: "2 amarelas" }, { tipo: "texto", texto: "0 verdes", destaque: true }] },
  momento03_descoberta: { perguntaGuia: "Qual cor tem maior chance de sair?", pista: "Mais resultados favoráveis tornam um evento mais provável.", revelacao: "Azul é muito provável, amarela é pouco provável e verde é impossível nesta sacola." },
  momento04_explicacao: { titulo: "Classificar depende das condições", etapas: [{ texto: "Muito provável: há muitas possibilidades favoráveis.", exemplo: "8 azuis entre 10 bolas." }, { texto: "Pouco provável: pode acontecer, mas há poucas possibilidades.", exemplo: "2 amarelas entre 10." }, { texto: "Impossível: não há resultado favorável.", exemplo: "Nenhuma bola verde." }, { texto: "Se o conteúdo da sacola mudar, a classificação pode mudar.", exemplo: "Ao acrescentar verdes, verde deixa de ser impossível." }] },
  momento05_modelagem: { enunciado: "EU FAÇO — saco com 9 estrelas e 1 círculo", passos: ["Conto cada tipo.", "Estrela tem mais possibilidades.", "Círculo tem apenas uma."], resposta: "Estrela é muito provável; círculo é pouco provável.", visualUrl: bola },
  momento06_praticaGuiada: { enunciado: "NÓS FAZEMOS — 6 azuis e 1 amarela.", dica: "Compare quantidades.", interacao: { tipo: "contarQuiz", grupos: [{ imagemUrl: bola, quantidade: 6, rotulo: "Azuis" }, { imagemUrl: bola, quantidade: 1, rotulo: "Amarela" }], pergunta: "Retirar amarela é:", opcoes: ["Muito provável", "Pouco provável", "Impossível"], correta: 1, feedbackAcerto: "Existe uma, então pode sair, mas é pouco provável.", feedbackErro: "Há uma amarela: não é impossível." } },
  momento07_praticaIndependente: { enunciado: "VOCÊ FAZ — não há bolas verdes.", interacao: { tipo: "contarQuiz", grupos: [{ imagemUrl: bola, quantidade: 3, rotulo: "Outras cores" }], pergunta: "Retirar verde é:", opcoes: ["Muito provável", "Pouco provável", "Impossível"], correta: 2, feedbackAcerto: "Sem verdes, é impossível.", feedbackErro: "Procure bolas verdes: não há nenhuma." } },
  momento08_aplicacao: { contexto: "Uma caixa tem 7 cartões de animais e 1 de planta.", problema: "Qual tipo é muito provável?", interacao: { tipo: "contarQuiz", grupos: [{ imagemUrl: bola, quantidade: 7, rotulo: "Animais" }, { imagemUrl: bola, quantidade: 1, rotulo: "Planta" }], pergunta: "Mais provável", opcoes: ["Animal", "Planta", "São iguais"], correta: 0, feedbackAcerto: "Há mais cartões de animais.", feedbackErro: "Compare 7 com 1." } },
  momento09_revisao: { pontos: ["Defina a experiência.", "Conte possibilidades.", "Muitas: muito provável.", "Poucas: pouco provável.", "Nenhuma: impossível."], miniDesafio: { tipo: "contarQuiz", grupos: [{ imagemUrl: bola, quantidade: 5 }], pergunta: "Se todas são azuis, sair azul é:", opcoes: ["Certo", "Pouco provável", "Impossível"], correta: 0, feedbackAcerto: "Todos os resultados são azuis.", feedbackErro: "Não há outra cor." } },
  momento10_avaliacao: { perguntas: [
    { pergunta: "0 verdes: retirar verde é:", opcoes: ["Muito provável", "Pouco provável", "Impossível"], correta: 2, feedbackAcerto: "Certo.", feedbackErro: "Não há verdes." },
    { pergunta: "9 azuis e 1 amarela: azul é:", opcoes: ["Muito provável", "Impossível", "Pouco provável"], correta: 0, feedbackAcerto: "Há muitas azuis.", feedbackErro: "Compare 9 e 1." },
    { pergunta: "9 azuis e 1 amarela: amarela é:", opcoes: ["Impossível", "Pouco provável", "Certa"], correta: 1, feedbackAcerto: "Pode sair, mas há só uma.", feedbackErro: "Existe uma amarela." },
    { pergunta: "Se acrescentarmos verdes, retirar verde continua impossível?", opcoes: ["Sim", "Não", "Sempre"], correta: 1, feedbackAcerto: "As condições mudaram.", feedbackErro: "Agora há verdes." },
    { pergunta: "Para classificar, precisamos conhecer:", opcoes: ["As possibilidades", "Só a cor favorita", "A velocidade"], correta: 0, feedbackAcerto: "Isso.", feedbackErro: "Observe os resultados possíveis." },
  ] },
  momento11_missaoFamilia: { titulo: "Sacola de possibilidades", materiais: ["Objetos seguros de duas cores", "Sacola opaca"], passos: ["Coloquem muitos de uma cor e poucos de outra.", "Classifiquem antes de retirar.", "Retirem, devolvam e repitam cinco vezes."], registro: "Tabela simples dos resultados." },
  recompensa: { xp: 230, moedas: 110, medalha: "Detetive das Possibilidades" },
};
