import type { AulaGeoV1 } from "../../types";
import { url as sistema } from "@/assets/ciencias-5ano/u6-a1/sistema-solar.jpg.asset.json";
import { url as terra } from "@/assets/ciencias-5ano/u6-a1/terra-espaco.jpg.asset.json";
import { url as lua } from "@/assets/ciencias-5ano/u6-a1/lua-fases.jpg.asset.json";
import { url as tempestade } from "@/assets/ciencias-5ano/u6-a1/tempestade.jpg.asset.json";

export const aula02: AulaGeoV1 = {
  slug: "aula-02-fases-da-lua",
  titulo: "Fases da Lua e Sua Periodicidade",
  iconeTrilha: "🌙",
  bncc: ["EF05CI12"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela Lua. Ache o formato dela em diferentes noites do mês.",
    mapaUrl: lua,
    imagemDestaqueUrl: terra,
    aurora: "A Lua não muda de tamanho nem de forma de verdade — o que muda é o quanto dela conseguimos ver iluminada pelo Sol, conforme ela orbita a Terra. Esse ciclo se repete todo mês.",
    falaFinal: "As fases da Lua são o exemplo mais fácil de observar da periodicidade do céu.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Se você observar a Lua todas as noites por cerca de um mês, ela vai passar pelas mesmas fases de novo?",
    pergunta: "O ciclo das fases da Lua se repete?",
    fotoUrl: lua,
    opcoes: [
      { id: "sim", titulo: "SIM", subtitulo: "se repete a cada 29,5 dias", emoji: "🔄", cor: "from-fuchsia-400 to-purple-700" },
      { id: "nao", titulo: "NÃO", subtitulo: "cada mês é diferente e aleatório", emoji: "🎲", cor: "from-slate-400 to-slate-700" },
          { id: "c", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
    ],
    respostaCerta: "sim",
    feedbackAcerto: "Certo. O ciclo lunar é PERIÓDICO: nova, crescente, cheia, minguante, e recomeça a cada 29,5 dias.",
    feedbackErro: "Não é aleatório! O ciclo das fases se repete de forma PERIÓDICA, a cada 29,5 dias.",
    falaFinal: "Periodicidade é isso: um padrão que se repete de tempos em tempos, como um relógio no céu.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco palavras sobre as fases da Lua.",
    instrucao: "Vocabulário das fases lunares",
    cadernos: [
      { id: "fase", capa: "FASE LUNAR", emoji: "🌗", cor: "from-slate-500 to-slate-700",
        conteudo: "A aparência da Lua vista da Terra, que muda conforme o ângulo da luz do Sol que a ilumina.",
        exemplo: "Ex.: Lua nova, crescente, cheia e minguante.", fotoUrl: lua },
      { id: "periodicidade", capa: "PERIODICIDADE", emoji: "🔄", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Repetição de um fenômeno em intervalos de tempo regulares e previsíveis.",
        exemplo: "Ex.: as fases da Lua se repetem a cada 29,5 dias.", fotoUrl: sistema },
      { id: "cicloLunar", capa: "CICLO LUNAR", emoji: "🌙", cor: "from-teal-500 to-emerald-700",
        conteudo: "O tempo completo que a Lua leva para passar por todas as fases e voltar à mesma fase inicial.",
        exemplo: "Ex.: da Lua nova até a próxima Lua nova são cerca de 29,5 dias.", fotoUrl: lua },
      { id: "orbitalunar", capa: "ÓRBITA DA LUA", emoji: "🛰️", cor: "from-cyan-500 to-sky-700",
        conteudo: "Trajetória que a Lua faz ao redor da Terra, que dura cerca de 27 dias.",
        exemplo: "Ex.: é essa órbita que muda o ângulo de iluminação vista da Terra.", fotoUrl: terra },
      { id: "iluminacao", capa: "ILUMINAÇÃO SOLAR", emoji: "☀️", cor: "from-amber-500 to-orange-700",
        conteudo: "A luz do Sol que incide sobre a Lua e é refletida até nossos olhos na Terra.",
        exemplo: "Ex.: a Lua não tem luz própria, só reflete a luz do Sol.", fotoUrl: sistema },
    ],
    falaFinal: "Fase, periodicidade, ciclo lunar, órbita da Lua, iluminação solar. As chaves pra entender o calendário da Lua.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "As quatro fases principais da Lua. Toca em cada uma.",
    instrucao: "Toque em cada fase",
    mapaUrl: lua,
    pontos: [
      { id: "nova", x: 20, y: 50, emoji: "🌑", cor: "from-slate-700 to-slate-900",
        titulo: "Lua Nova", texto: "A face iluminada está voltada para o lado oposto da Terra — quase não vemos a Lua.",
        fotoUrl: lua },
      { id: "crescente", x: 40, y: 40, emoji: "🌒", cor: "from-slate-400 to-slate-600",
        titulo: "Lua Crescente", texto: "A parte iluminada visível vai aumentando dia após dia.",
        fotoUrl: lua },
      { id: "cheia", x: 65, y: 55, emoji: "🌕", cor: "from-amber-300 to-amber-500",
        titulo: "Lua Cheia", texto: "Toda a face voltada para a Terra está iluminada.",
        fotoUrl: lua },
      { id: "minguante", x: 85, y: 40, emoji: "🌖", cor: "from-slate-400 to-slate-600",
        titulo: "Lua Minguante", texto: "A parte iluminada visível vai diminuindo até chegar de novo à Lua nova.",
        fotoUrl: lua },
    ],
    falaFinal: "Nova, crescente, cheia, minguante — e o ciclo recomeça, sempre na mesma ordem.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas sobre as fases da Lua.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Quanto tempo dura, em média, um ciclo completo das fases da Lua?",
        fotoUrl: lua,
        cards: [
          { id: "a", emoji: "🔄", titulo: "Cerca de 29,5 dias", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "📅", titulo: "Cerca de 1 dia", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🗓️", titulo: "Cerca de 1 ano", cor: "from-cyan-500 to-sky-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. O ciclo lunar completo dura cerca de 29,5 dias — um mês lunar.",
        feedbackErro: "1 dia é curto demais e 1 ano é longo demais. O ciclo dura cerca de 29,5 DIAS." },
      { id: "q2", pergunta: "Por que a Lua muda de aparência no céu?",
        fotoUrl: terra,
        cards: [
          { id: "a", emoji: "☀️", titulo: "Muda o ângulo da luz do Sol sobre ela", cor: "from-amber-500 to-orange-700" },
          { id: "b", emoji: "☁️", titulo: "Nuvens cobrem partes da Lua", cor: "from-cyan-500 to-sky-700" },
          { id: "c", emoji: "🌍", titulo: "A Terra muda de tamanho", cor: "from-slate-500 to-slate-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Conforme a Lua orbita a Terra, o ângulo da luz do Sol sobre ela muda.",
        feedbackErro: "Não são nuvens nem a Terra. É o ÂNGULO da luz do Sol que muda." },
      { id: "q3", pergunta: "O que caracteriza um fenômeno periódico como as fases da Lua?",
        fotoUrl: sistema,
        cards: [
          { id: "a", emoji: "🔄", titulo: "Se repete em intervalos regulares", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "🎲", titulo: "Acontece de forma aleatória", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "⏹️", titulo: "Acontece só uma vez", cor: "from-slate-500 to-slate-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. PERIODICIDADE é a repetição regular de um fenômeno.",
        feedbackErro: "Não é aleatório nem único. PERIÓDICO é o que se repete em intervalos regulares." },
    ],
    falaFinal: "Você já entende o que torna as fases da Lua um fenômeno previsível.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "O ciclo lunar divide-se em duas metades: CRESCENTE (Lua ganhando luz) e MINGUANTE (Lua perdendo luz).",
    instrucao: "Toque nos interruptores",
    mapaUrl: lua,
    camadas: [
      { id: "crescente", rotulo: "Fase Crescente", emoji: "🌒", cor: "from-amber-400 to-amber-600",
        rect: { x: 5, y: 20, w: 45, h: 60 },
        descricao: "Da Lua nova até a cheia, a parte iluminada visível vai aumentando dia após dia.",
        fotoUrl: lua },
      { id: "minguante", rotulo: "Fase Minguante", emoji: "🌖", cor: "from-slate-500 to-slate-700",
        rect: { x: 50, y: 20, w: 45, h: 60 },
        descricao: "Da Lua cheia até a nova, a parte iluminada visível vai diminuindo dia após dia.",
        fotoUrl: terra },
    ],
    falaFinal: "Metade do ciclo a Lua cresce, metade ela mingua — sempre nessa ordem.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a ordem correta do ciclo lunar completo.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual a ordem das fases da Lua?",
    paradas: [
      { id: "nova", emoji: "🌑", rotulo: "1. Lua Nova", descricao: "Face iluminada voltada para o lado oposto da Terra.", fotoUrl: lua },
      { id: "crescente", emoji: "🌒", rotulo: "2. Lua Crescente", descricao: "A parte visível iluminada aumenta a cada noite.", fotoUrl: lua },
      { id: "cheia", emoji: "🌕", rotulo: "3. Lua Cheia", descricao: "Toda a face voltada pra Terra está iluminada.", fotoUrl: lua },
      { id: "minguante", emoji: "🌖", rotulo: "4. Lua Minguante", descricao: "A parte visível iluminada diminui até a próxima Lua nova.", fotoUrl: terra },
    ],
    ordemCerta: ["nova", "crescente", "cheia", "minguante"],
    feedbackAcerto: "Ciclo completo! Depois da minguante, recomeça na Lua nova — sempre nessa ordem, a cada 29,5 dias.",
    feedbackErro: "Repense: nova (escura) → crescente (ganhando luz) → cheia (toda iluminada) → minguante (perdendo luz).",
    falaFinal: "Esse ciclo se repete mês após mês, sem exceção — dá pra prever com precisão.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura. Estuda o diário do astrônomo sobre a Lua.",
    tituloLivro: "📓 Diário do Astrônomo",
    subtitulo: "O calendário da Lua",
    paragrafos: [
      { id: "p1", texto:
          "A Lua não tem luz própria — ela apenas reflete a ILUMINAÇÃO SOLAR. Conforme orbita a Terra, o ângulo dessa luz muda, e por isso vemos diferentes FASES da Lua ao longo do mês.",
        chaves: ["iluminação solar", "fases"],
        definicoes: {
          "iluminação solar": "Luz do Sol que incide sobre a Lua e é refletida até a Terra.",
          fases: "Diferentes aparências da Lua vistas da Terra.",
        }, fotoUrl: lua },
      { id: "p2", texto:
          "O CICLO LUNAR completo — da Lua nova até a próxima Lua nova — dura cerca de 29,5 dias. Esse número é maior que os 27 dias da ÓRBITA DA LUA porque a Terra também se move ao redor do Sol enquanto isso.",
        chaves: ["ciclo lunar", "órbita da lua"],
        definicoes: {
          "ciclo lunar": "Tempo que a Lua leva para passar por todas as fases e voltar à mesma.",
          "órbita da lua": "Trajetória que a Lua faz ao redor da Terra.",
        }, fotoUrl: terra },
      { id: "p3", texto:
          "Esse fenômeno é um exemplo de PERIODICIDADE: um padrão que se repete em intervalos regulares e previsíveis. Por isso, calendários antigos e atuais usam as fases da Lua para marcar os meses.",
        chaves: ["periodicidade"],
        definicoes: {
          periodicidade: "Repetição de um fenômeno em intervalos de tempo regulares.",
        }, fotoUrl: sistema },
    ],
    falaFinal: "Você agora entende por que dá pra prever a Lua cheia do mês que vem.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Identifique a fase da Lua descrita em cada rodada.",
    instrucao: "⏱️ Leia e escolha a fase correta",
    duracaoSegundos: 20,
    pecas: [
      { id: "nova", emoji: "🌑", rotulo: "Nova" },
      { id: "crescente", emoji: "🌒", rotulo: "Crescente" },
      { id: "cheia", emoji: "🌕", rotulo: "Cheia" },
      { id: "minguante", emoji: "🌖", rotulo: "Minguante" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Lua quase invisível no céu", emoji: "🌑", cor: "from-slate-700 to-slate-900" },
        municipioB: { nome: "Face escura voltada pra Terra", emoji: "🌌", cor: "from-slate-700 to-slate-900" },
        contexto: "Nessa fase, a face iluminada da Lua está voltada para o lado oposto da Terra.",
        pecaCertaId: "nova", fotoUrl: lua,
        feedbackAcerto: "Sim. Lua quase invisível é a fase NOVA.",
        feedbackErro: "Face escura para a Terra é a Lua NOVA." },
      { id: "r2", municipioA: { nome: "Parte iluminada aumentando", emoji: "🌒", cor: "from-amber-400 to-amber-600" },
        municipioB: { nome: "Rumo à Lua cheia", emoji: "⬆️", cor: "from-amber-400 to-amber-600" },
        contexto: "A cada noite, mais da Lua vai ficando visível e iluminada.",
        pecaCertaId: "crescente", fotoUrl: lua,
        feedbackAcerto: "Perfeito. Luz aumentando é a fase CRESCENTE.",
        feedbackErro: "Iluminação aumentando é a Lua CRESCENTE." },
      { id: "r3", municipioA: { nome: "Toda a face visível iluminada", emoji: "🌕", cor: "from-amber-300 to-amber-500" },
        municipioB: { nome: "Noite bem clara", emoji: "✨", cor: "from-amber-300 to-amber-500" },
        contexto: "A Lua aparece completamente redonda e iluminada no céu.",
        pecaCertaId: "cheia", fotoUrl: lua,
        feedbackAcerto: "Isso. Totalmente iluminada é a Lua CHEIA.",
        feedbackErro: "Face toda iluminada é a Lua CHEIA." },
      { id: "r4", municipioA: { nome: "Parte iluminada diminuindo", emoji: "🌖", cor: "from-slate-500 to-slate-700" },
        municipioB: { nome: "Rumo à Lua nova", emoji: "⬇️", cor: "from-slate-500 to-slate-700" },
        contexto: "Depois da Lua cheia, a iluminação visível vai ficando cada vez menor.",
        pecaCertaId: "minguante", fotoUrl: terra,
        feedbackAcerto: "Correto. Luz diminuindo é a fase MINGUANTE.",
        feedbackErro: "Iluminação diminuindo depois da cheia é a Lua MINGUANTE." },
      { id: "r5", municipioA: { nome: "29,5 dias completos", emoji: "🗓️", cor: "from-fuchsia-500 to-purple-700" },
        municipioB: { nome: "Início de um novo ciclo", emoji: "🔄", cor: "from-slate-700 to-slate-900" },
        contexto: "Depois de completar todas as fases, o ciclo recomeça do zero.",
        pecaCertaId: "nova", fotoUrl: sistema,
        feedbackAcerto: "Sim. O ciclo recomeça sempre na Lua NOVA.",
        feedbackErro: "O início de um novo ciclo é sempre a Lua NOVA." },
    ],
    falaFinal: "Você já reconhece cada fase da Lua e sua posição no ciclo.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "O ciclo lunar em duas metades: GANHANDO LUZ (nova até cheia) e PERDENDO LUZ (cheia até nova).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: lua,
    fatias: [
      { id: "ganhando", rotulo: "Ganhando luz", emoji: "🌒", percentual: 50, cor: "#f59e0b",
        descricao: "Da Lua nova até a Lua cheia, a parte iluminada visível aumenta a cada noite.",
        exemplos: ["Lua nova", "Lua crescente", "Lua cheia"], fotoUrl: lua },
      { id: "perdendo", rotulo: "Perdendo luz", emoji: "🌖", percentual: 50, cor: "#475569",
        descricao: "Da Lua cheia até a próxima Lua nova, a parte iluminada visível diminui.",
        exemplos: ["Lua cheia", "Lua minguante", "Lua nova"], fotoUrl: terra },
      ],
    falaFinal: "Ganhar e perder luz, sempre nessa ordem: essa é a periodicidade lunar.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Observador da Lua Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: lua,
    perguntas: [
      { id: "q1", pergunta: "Quanto tempo dura o ciclo completo das fases da Lua?",
        fotoUrl: lua,
        opcoes: [
          { id: "a", texto: "Cerca de 29,5 dias", correta: true },
          { id: "b", texto: "Cerca de 1 dia" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Sim. O ciclo lunar completo dura cerca de 29,5 dias.",
        feedbackErro: "1 dia é rápido demais. O ciclo completo dura cerca de 29,5 DIAS." },
      { id: "q2", pergunta: "Por que a Lua parece mudar de forma no céu?",
        fotoUrl: terra,
        opcoes: [
          { id: "a", texto: "O ângulo da luz do Sol sobre ela muda", correta: true },
          { id: "b", texto: "Nuvens cobrem partes dela" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Correto. É o ÂNGULO da luz solar que muda, não nuvens.",
        feedbackErro: "Não são nuvens. É o ângulo da LUZ DO SOL que muda." },
      { id: "q3", pergunta: "O que significa dizer que as fases da Lua são periódicas?",
        fotoUrl: sistema,
        opcoes: [
          { id: "a", texto: "Se repetem em intervalos regulares e previsíveis", correta: true },
          { id: "b", texto: "Acontecem de forma aleatória, sem padrão" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Sim. PERIÓDICO é o que se repete de forma regular e previsível.",
        feedbackErro: "Não é aleatório. PERIÓDICO significa que se repete em padrão regular." },
    ],
    selo: {
      nome: "Observador da Lua Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 7 concluído",
      emoji: "🌙",
      cor: "from-purple-400 via-fuchsia-500 to-slate-700",
    },
    falaFinal: "Observador da Lua júnior aprovado. Agora observe o céu e confira o ciclo você mesmo.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Observador da Lua Júnior" },
};
