import type { AulaGeoV1 } from "../../types";
import sistema from "@/assets/ciencias-5ano/u6-a1/sistema-solar.jpg";
import terra from "@/assets/ciencias-5ano/u6-a1/terra-espaco.jpg";
import lua from "@/assets/ciencias-5ano/u6-a1/lua-fases.jpg";
import tempestade from "@/assets/ciencias-5ano/u6-a1/tempestade.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-terra-universo-clima",
  titulo: "Terra, Universo e Clima",
  iconeTrilha: "🌍",
  bncc: ["EF05CI10"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pelo espaço. Ache nosso planeta no sistema solar.",
    mapaUrl: sistema,
    imagemDestaqueUrl: terra,
    aurora: "Aquele pontinho azul ali é a Terra. Um planeta girando em torno de uma estrela chamada Sol, num sistema com outros 7 planetas e milhões de rochas espaciais.",
    falaFinal: "Astronomia começa com uma pergunta simples: 'onde estamos?'.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Por que a Lua muda de forma no céu ao longo do mês?",
    pergunta: "O que causa as FASES da Lua?",
    fotoUrl: lua,
    opcoes: [
      { id: "sombra", titulo: "SOMBRA DA TERRA", subtitulo: "encobre a Lua", emoji: "🌑", cor: "from-slate-500 to-slate-700" },
      { id: "iluminacao", titulo: "ILUMINAÇÃO DO SOL", subtitulo: "muda com a órbita", emoji: "☀️", cor: "from-amber-400 to-orange-700" },
      { id: "nuvens", titulo: "NUVENS", subtitulo: "cobrem a Lua", emoji: "☁️", cor: "from-cyan-400 to-sky-700" },
    ],
    respostaCerta: "iluminacao",
    feedbackAcerto: "Sim. Conforme a Lua orbita a Terra, o SOL a ilumina de ângulos diferentes — daí as fases.",
    feedbackErro: "Sombra da Terra causa eclipse, não fase. O que muda é o ÂNGULO da luz do sol.",
    falaFinal: "As fases são um jogo de ângulos entre Sol, Terra e Lua. Puro geometria cósmica.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco palavras que abrem a porta pra astronomia.",
    instrucao: "Vocabulário do universo",
    cadernos: [
      { id: "planeta", capa: "PLANETA", emoji: "🪐", cor: "from-cyan-500 to-sky-700",
        conteudo: "Corpo celeste esférico que orbita uma estrela e não emite luz própria.",
        exemplo: "Ex.: Terra, Marte, Júpiter.", fotoUrl: terra },
      { id: "estrela", capa: "ESTRELA", emoji: "⭐", cor: "from-amber-500 to-orange-700",
        conteudo: "Corpo celeste que emite LUZ e CALOR próprios (reações nucleares).",
        exemplo: "Ex.: nosso Sol é uma estrela.", fotoUrl: sistema },
      { id: "orbita", capa: "ÓRBITA", emoji: "🔄", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Trajetória curva que um corpo faz ao redor de outro por causa da GRAVIDADE.",
        exemplo: "Ex.: Terra orbita Sol em 365 dias.", fotoUrl: sistema },
      { id: "rotacao", capa: "ROTAÇÃO", emoji: "🌀", cor: "from-teal-500 to-emerald-700",
        conteudo: "Movimento do planeta GIRANDO em torno do próprio eixo — causa dia e noite.",
        exemplo: "Ex.: Terra completa 1 rotação a cada 24 horas.", fotoUrl: terra },
      { id: "clima", capa: "CLIMA", emoji: "🌦️", cor: "from-slate-500 to-slate-700",
        conteudo: "Comportamento médio da atmosfera em uma região ao longo dos anos.",
        exemplo: "Ex.: Amazônia = clima equatorial úmido.", fotoUrl: tempestade },
    ],
    falaFinal: "Planeta, estrela, órbita, rotação, clima. Os cinco pilares pra entender nosso lugar no cosmos.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "O sistema solar. Toca em cada elemento pra ver a função.",
    instrucao: "Toque em cada elemento",
    mapaUrl: sistema,
    pontos: [
      { id: "sol", x: 50, y: 50, emoji: "☀️", cor: "from-amber-500 to-orange-700",
        titulo: "Sol", texto: "Estrela central. Fonte de toda energia do sistema. Gigante em relação aos planetas.",
        fotoUrl: sistema },
      { id: "terra", x: 30, y: 65, emoji: "🌍", cor: "from-cyan-500 to-sky-700",
        titulo: "Terra", texto: "Terceiro planeta a partir do Sol. Único conhecido com vida — a distância ideal do Sol.",
        fotoUrl: terra },
      { id: "lua", x: 25, y: 55, emoji: "🌕", cor: "from-slate-400 to-slate-700",
        titulo: "Lua", texto: "Satélite natural da Terra. Orbita nosso planeta e causa marés no oceano.",
        fotoUrl: lua },
      { id: "orbita", x: 70, y: 55, emoji: "🔄", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Órbitas", texto: "Trajetórias elípticas dos planetas. Gravidade do Sol mantém tudo no lugar.",
        fotoUrl: sistema },
      { id: "planetas", x: 75, y: 30, emoji: "🪐", cor: "from-teal-500 to-emerald-700",
        titulo: "Outros planetas", texto: "Mercúrio, Vênus, Marte, Júpiter, Saturno, Urano, Netuno — cada um único.",
        fotoUrl: sistema },
    ],
    falaFinal: "Sol no centro, planetas orbitando. Sistema simples, matemática precisa.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de astronomia.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "O que causa o dia e a noite na Terra?",
        fotoUrl: terra,
        cards: [
          { id: "a", emoji: "🌀", titulo: "Rotação (giro no próprio eixo)", cor: "from-teal-500 to-emerald-700" },
          { id: "b", emoji: "🔄", titulo: "Translação (volta ao Sol)", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "☁️", titulo: "Nuvens", cor: "from-cyan-500 to-sky-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Terra gira em 24h — lado iluminado é dia, lado escuro é noite.",
        feedbackErro: "Translação dura 1 ano e causa as estações. Dia/noite é ROTAÇÃO." },
      { id: "q2", pergunta: "O Sol é um planeta ou uma estrela?",
        fotoUrl: sistema,
        cards: [
          { id: "a", emoji: "⭐", titulo: "Estrela — emite luz própria", cor: "from-amber-500 to-orange-700" },
          { id: "b", emoji: "🪐", titulo: "Planeta — não emite luz", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "🌙", titulo: "Satélite", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Sol é uma estrela — planetas apenas refletem a luz dele.",
        feedbackErro: "Planetas não emitem luz. Sol EMITE luz própria — é ESTRELA." },
      { id: "q3", pergunta: "Qual força mantém a Terra em órbita ao redor do Sol?",
        fotoUrl: sistema,
        cards: [
          { id: "a", emoji: "🧲", titulo: "Gravidade do Sol", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "💨", titulo: "Vento espacial", cor: "from-cyan-500 to-sky-700" },
          { id: "c", emoji: "🔥", titulo: "Calor do Sol", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Massa gigante do Sol gera GRAVIDADE que puxa todos os planetas.",
        feedbackErro: "Vento e calor não mantêm órbita. É a GRAVIDADE do Sol." },
    ],
    falaFinal: "Você já entende os movimentos básicos do sistema solar. Astronomia começa aqui.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "O céu divide-se em duas grandes zonas: ESPAÇO (astros e órbitas) e ATMOSFERA (clima e tempo). Liga cada uma.",
    instrucao: "Toque nos interruptores",
    mapaUrl: terra,
    camadas: [
      { id: "espaco", rotulo: "Espaço", emoji: "🌌", cor: "from-slate-700 to-slate-900",
        rect: { x: 2, y: 2, w: 96, h: 30 },
        descricao: "Vazio cósmico onde a Terra orbita o Sol junto com outros planetas.",
        fotoUrl: sistema },
      { id: "atmosfera", rotulo: "Atmosfera", emoji: "☁️", cor: "from-cyan-500 to-sky-700",
        rect: { x: 2, y: 35, w: 96, h: 60 },
        descricao: "Camada de gases que envolve a Terra — onde acontece o clima e o tempo atmosférico.",
        fotoUrl: tempestade },
    ],
    falaFinal: "Espaço lá em cima; atmosfera ao redor. As duas juntas dão as condições da vida.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a sequência das fases da Lua num mês.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual a ordem das fases lunares?",
    paradas: [
      { id: "nova", emoji: "🌑", rotulo: "1. Nova", descricao: "Lua não é visível — face escura voltada pra Terra.", fotoUrl: lua },
      { id: "crescente", emoji: "🌒", rotulo: "2. Crescente", descricao: "Parte iluminada começa a aparecer.", fotoUrl: lua },
      { id: "cheia", emoji: "🌕", rotulo: "3. Cheia", descricao: "Face iluminada totalmente visível.", fotoUrl: lua },
      { id: "minguante", emoji: "🌖", rotulo: "4. Minguante", descricao: "Iluminação começa a diminuir.", fotoUrl: lua },
    ],
    ordemCerta: ["nova", "crescente", "cheia", "minguante"],
    feedbackAcerto: "Ciclo completo em cerca de 29,5 dias. Um mês lunar.",
    feedbackErro: "Ordem: nova (escura) → crescente → cheia → minguante.",
    falaFinal: "Todo mês a Lua faz esse ciclo. Você pode conferir olhando pro céu.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Leitura autônoma. Estuda o diário do astrônomo.",
    tituloLivro: "📓 Diário do Astrônomo",
    subtitulo: "Nossa posição no universo",
    paragrafos: [
      { id: "p1", texto:
          "A TERRA é um planeta rochoso que ORBITA uma estrela chamada Sol. Nosso sistema tem 8 planetas — Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno. Cada um com sua distância e órbita únicas.",
        chaves: ["terra", "orbita"],
        definicoes: {
          terra: "Terceiro planeta a partir do Sol; único com vida conhecida.",
          orbita: "Trajetória de um corpo ao redor de outro.",
        }, fotoUrl: sistema },
      { id: "p2", texto:
          "A ROTAÇÃO da Terra em torno do próprio eixo dura 24 horas — causa dia e noite. A TRANSLAÇÃO em torno do Sol dura 365 dias — define o ano. E a inclinação do eixo cria as estações.",
        chaves: ["rotação", "translação"],
        definicoes: {
          rotação: "Giro do planeta em torno do próprio eixo.",
          translação: "Volta completa do planeta ao redor do Sol.",
        }, fotoUrl: terra },
      { id: "p3", texto:
          "A LUA é nosso satélite natural. Orbita a Terra em cerca de 27 dias. As FASES que vemos dependem do ângulo da luz do sol que a ilumina. E a ATMOSFERA da Terra é onde acontece todo o CLIMA — chuvas, ventos, tempestades.",
        chaves: ["fases", "atmosfera", "clima"],
        definicoes: {
          fases: "Diferentes iluminações da Lua vistas da Terra.",
          atmosfera: "Camada de gases ao redor da Terra.",
          clima: "Comportamento médio da atmosfera.",
        }, fotoUrl: lua },
    ],
    falaFinal: "Você entende sua posição no universo. Não é pouco.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra um fenômeno — identifica o CONCEITO.",
    instrucao: "⏱️ Leia e escolha o conceito",
    duracaoSegundos: 20,
    pecas: [
      { id: "rotacao", emoji: "🌀", rotulo: "Rotação" },
      { id: "translacao", emoji: "🔄", rotulo: "Translação" },
      { id: "fase", emoji: "🌗", rotulo: "Fase Lunar" },
      { id: "clima", emoji: "🌦️", rotulo: "Clima" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Dia e noite", emoji: "🌞🌚", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "24 horas", emoji: "🕒", cor: "from-teal-500 to-emerald-700" },
        contexto: "A cada 24 horas, seu lado da Terra fica virado pro Sol (dia) e depois pra sombra (noite).",
        pecaCertaId: "rotacao", fotoUrl: terra,
        feedbackAcerto: "Sim. Giro em 24h = ROTAÇÃO da Terra.",
        feedbackErro: "24h de giro no próprio eixo = ROTAÇÃO." },
      { id: "r2", municipioA: { nome: "365 dias", emoji: "📅", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "1 volta ao Sol", emoji: "🔄", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Terra completa uma volta ao redor do Sol em 365 dias — que definimos como 1 ano.",
        pecaCertaId: "translacao", fotoUrl: sistema,
        feedbackAcerto: "Perfeito. Volta ao Sol em 365 dias = TRANSLAÇÃO.",
        feedbackErro: "Volta completa ao Sol = TRANSLAÇÃO. Dura 1 ano." },
      { id: "r3", municipioA: { nome: "Lua cheia", emoji: "🌕", cor: "from-slate-400 to-slate-700" },
        municipioB: { nome: "Face iluminada visível", emoji: "☀️", cor: "from-amber-500 to-orange-700" },
        contexto: "A Lua aparece totalmente iluminada no céu — face voltada pra Terra recebe luz do Sol.",
        pecaCertaId: "fase", fotoUrl: lua,
        feedbackAcerto: "Isso. Aparência da Lua no céu = FASE LUNAR.",
        feedbackErro: "Aparência mensal da Lua = FASE." },
      { id: "r4", municipioA: { nome: "Tempestade tropical", emoji: "⛈️", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Padrão de chuvas", emoji: "🌧️", cor: "from-slate-500 to-slate-700" },
        contexto: "Uma região que passa meses com muita chuva tem esse comportamento no seu CLIMA.",
        pecaCertaId: "clima", fotoUrl: tempestade,
        feedbackAcerto: "Sim. Padrão médio da atmosfera = CLIMA.",
        feedbackErro: "Comportamento típico da atmosfera de uma região = CLIMA." },
      { id: "r5", municipioA: { nome: "Estações do ano", emoji: "🍂🌸", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Inclinação do eixo", emoji: "🌍", cor: "from-cyan-500 to-sky-700" },
        contexto: "Verão, outono, inverno, primavera acontecem porque a Terra gira em volta do Sol com o eixo inclinado.",
        pecaCertaId: "translacao", fotoUrl: sistema,
        feedbackAcerto: "Perfeito. Estações dependem da posição durante a TRANSLAÇÃO.",
        feedbackErro: "As estações acontecem ao longo da órbita — durante a TRANSLAÇÃO." },
    ],
    falaFinal: "Você entende os movimentos e fenômenos básicos do céu. Astrônomo em formação.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "O tema divide-se em duas metades: MOVIMENTOS (rotação, translação, fases) e AMBIENTE (atmosfera, clima).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: terra,
    fatias: [
      { id: "movimentos", rotulo: "Movimentos", emoji: "🔄", percentual: 55, cor: "#7c3aed",
        descricao: "Rotação da Terra, translação ao redor do Sol, fases da Lua. Tudo é movimento e ângulo.",
        exemplos: ["Rotação", "Translação", "Fases"], fotoUrl: sistema },
      { id: "atmosfera", rotulo: "Atmosfera e Clima", emoji: "🌦️", percentual: 45, cor: "#0891b2",
        descricao: "A camada de gases que envolve a Terra determina o clima, o tempo e permite a vida.",
        exemplos: ["Chuvas", "Ventos", "Tempestades"], fotoUrl: tempestade },
    ],
    falaFinal: "Movimentos definem o tempo cósmico. Atmosfera define o tempo do dia a dia.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Astrônomo Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: terra,
    perguntas: [
      { id: "q1", pergunta: "O que a Terra faz em 24 horas?",
        fotoUrl: terra,
        opcoes: [
          { id: "a", texto: "Uma rotação — dia e noite", correta: true },
          { id: "b", texto: "Uma volta ao redor do Sol" },
        ],
        feedbackAcerto: "Sim. 24h = ROTAÇÃO. Volta ao Sol dura 365 dias.",
        feedbackErro: "Volta ao Sol dura 1 ano. Em 24h é uma ROTAÇÃO." },
      { id: "q2", pergunta: "O Sol é uma estrela ou um planeta?",
        fotoUrl: sistema,
        opcoes: [
          { id: "a", texto: "Estrela — emite luz própria", correta: true },
          { id: "b", texto: "Planeta — só reflete luz" },
        ],
        feedbackAcerto: "Correto. Sol emite luz e calor próprios — é ESTRELA.",
        feedbackErro: "Sol EMITE luz. Planetas só refletem. Sol é ESTRELA." },
      { id: "q3", pergunta: "O que causa as fases da Lua?",
        fotoUrl: lua,
        opcoes: [
          { id: "a", texto: "O ângulo da luz do Sol conforme a Lua orbita", correta: true },
          { id: "b", texto: "Nuvens cobrindo parte da Lua" },
        ],
        feedbackAcerto: "Sim. Órbita da Lua muda o ângulo de iluminação — daí as fases.",
        feedbackErro: "Nuvens não causam fases. É o ÂNGULO da luz do Sol." },
    ],
    selo: {
      nome: "Astrônomo Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 6 concluído",
      emoji: "🔭",
      cor: "from-purple-400 via-violet-500 to-indigo-700",
    },
    falaFinal: "Astrônomo júnior aprovado. Próxima etapa: sua Feira Científica final.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Astrônomo Júnior" },
};
