import type { AulaGeoV1 } from "../../types";
import { url as sistema } from "@/assets/ciencias-5ano/u6-a1/sistema-solar.jpg.asset.json";
import { url as terra } from "@/assets/ciencias-5ano/u6-a1/terra-espaco.jpg.asset.json";
import { url as lua } from "@/assets/ciencias-5ano/u6-a1/lua-fases.jpg.asset.json";
import { url as tempestade } from "@/assets/ciencias-5ano/u6-a1/tempestade.jpg.asset.json";

export const aula03: AulaGeoV1 = {
  slug: "aula-03-instrumentos-opticos",
  titulo: "Instrumentos Ópticos: Ver o Muito Longe e o Muito Pequeno",
  iconeTrilha: "🔭",
  bncc: ["EF05CI13"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela bancada. Ache os instrumentos que ajudam a enxergar o que o olho sozinho não alcança.",
    mapaUrl: sistema,
    imagemDestaqueUrl: lua,
    aurora: "Nossos olhos são ótimos, mas têm limite. Pra ver uma cratera da Lua ou uma bactéria, precisamos de instrumentos ópticos que usam lentes ou espelhos pra ampliar ou aproximar imagens.",
    falaFinal: "Cada instrumento óptico resolve um problema diferente de visão — longe, perto, minúsculo ou escondido.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Um cientista quer observar bactérias, seres tão pequenos que são invisíveis a olho nu. Qual instrumento ele deve usar?",
    pergunta: "Qual instrumento serve para ver seres microscópicos?",
    fotoUrl: terra,
    opcoes: [
      { id: "microscopio", titulo: "MICROSCÓPIO", subtitulo: "amplia objetos minúsculos", emoji: "🔬", cor: "from-emerald-400 to-green-700" },
      { id: "luneta", titulo: "LUNETA", subtitulo: "aproxima objetos distantes", emoji: "🔭", cor: "from-indigo-400 to-purple-700" },
    ],
    respostaCerta: "microscopio",
    feedbackAcerto: "Certo. O MICROSCÓPIO usa lentes para ampliar objetos extremamente pequenos, como células e bactérias.",
    feedbackErro: "Luneta é para objetos distantes, como estrelas. Para objetos minúsculos, o instrumento certo é o MICROSCÓPIO.",
    falaFinal: "Cada instrumento tem sua especialidade: distância ou tamanho.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco instrumentos ópticos importantes.",
    instrucao: "Vocabulário dos instrumentos ópticos",
    cadernos: [
      { id: "luneta", capa: "LUNETA", emoji: "🔭", cor: "from-indigo-500 to-purple-700",
        conteudo: "Instrumento com lentes que aproxima a imagem de objetos muito distantes, como estrelas e planetas.",
        exemplo: "Ex.: Galileu usou uma luneta para observar as luas de Júpiter em 1610.", fotoUrl: sistema },
      { id: "periscopio", capa: "PERISCÓPIO", emoji: "🪞", cor: "from-cyan-500 to-sky-700",
        conteudo: "Instrumento com espelhos inclinados que permite ver por cima de obstáculos ou de dentro de um esconderijo.",
        exemplo: "Ex.: usado em submarinos para observar a superfície do mar.", fotoUrl: terra },
      { id: "lupa", capa: "LUPA", emoji: "🔍", cor: "from-amber-500 to-orange-700",
        conteudo: "Lente simples que amplia objetos pequenos e próximos, facilitando ver detalhes.",
        exemplo: "Ex.: usada para examinar um inseto ou uma folha de perto.", fotoUrl: lua },
      { id: "microscopio", capa: "MICROSCÓPIO", emoji: "🔬", cor: "from-emerald-500 to-green-700",
        conteudo: "Instrumento com várias lentes que amplia MUITO objetos microscópicos, invisíveis a olho nu.",
        exemplo: "Ex.: usado para observar células e bactérias em laboratório.", fotoUrl: tempestade },
      { id: "cameraescura", capa: "CÂMERA FOTOGRÁFICA", emoji: "📷", cor: "from-slate-500 to-slate-700",
        conteudo: "Instrumento óptico que capta a luz através de uma lente e registra a imagem para ver depois.",
        exemplo: "Ex.: câmeras registram desde paisagens até imagens do espaço.", fotoUrl: sistema },
    ],
    falaFinal: "Luneta, periscópio, lupa, microscópio, câmera. Cinco jeitos diferentes de ampliar o que os olhos veem.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A bancada de instrumentos ópticos. Toca em cada um pra entender sua função.",
    instrucao: "Toque em cada instrumento",
    mapaUrl: sistema,
    pontos: [
      { id: "luneta", x: 20, y: 40, emoji: "🔭", cor: "from-indigo-500 to-purple-700",
        titulo: "Luneta", texto: "Usa lentes para aproximar objetos muito distantes, como planetas e estrelas.",
        fotoUrl: sistema },
      { id: "periscopio", x: 45, y: 60, emoji: "🪞", cor: "from-cyan-500 to-sky-700",
        titulo: "Periscópio", texto: "Usa espelhos inclinados para ver por cima de obstáculos, como em submarinos.",
        fotoUrl: terra },
      { id: "lupa", x: 65, y: 40, emoji: "🔍", cor: "from-amber-500 to-orange-700",
        titulo: "Lupa", texto: "Uma única lente que amplia objetos pequenos e próximos.",
        fotoUrl: lua },
      { id: "microscopio", x: 85, y: 60, emoji: "🔬", cor: "from-emerald-500 to-green-700",
        titulo: "Microscópio", texto: "Várias lentes juntas ampliam muito mais que a lupa — mostra o mundo microscópico.",
        fotoUrl: tempestade },
    ],
    falaFinal: "Cada instrumento amplia à sua maneira — o segredo está no arranjo das lentes e espelhos.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas sobre instrumentos ópticos.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Qual instrumento usa espelhos para ver por cima de obstáculos?",
        fotoUrl: terra,
        cards: [
          { id: "a", emoji: "🪞", titulo: "Periscópio", cor: "from-cyan-500 to-sky-700" },
          { id: "b", emoji: "🔬", titulo: "Microscópio", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "🔍", titulo: "Lupa", cor: "from-amber-500 to-orange-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. O PERISCÓPIO usa espelhos inclinados para desviar a visão por cima de obstáculos.",
        feedbackErro: "Microscópio e lupa ampliam objetos pequenos. Ver por cima de obstáculos é papel do PERISCÓPIO." },
      { id: "q2", pergunta: "Qual instrumento é usado para observar planetas e estrelas distantes?",
        fotoUrl: sistema,
        cards: [
          { id: "a", emoji: "🔭", titulo: "Luneta", cor: "from-indigo-500 to-purple-700" },
          { id: "b", emoji: "🔬", titulo: "Microscópio", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "🪞", titulo: "Periscópio", cor: "from-cyan-500 to-sky-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. A LUNETA aproxima objetos muito distantes, como astros no céu.",
        feedbackErro: "Microscópio é para objetos minúsculos. Para o céu distante, usamos a LUNETA." },
      { id: "q3", pergunta: "Qual instrumento amplia MAIS: a lupa ou o microscópio?",
        fotoUrl: tempestade,
        cards: [
          { id: "a", emoji: "🔬", titulo: "Microscópio, por usar várias lentes", cor: "from-emerald-500 to-green-700" },
          { id: "b", emoji: "🔍", titulo: "Lupa, por ser mais simples", cor: "from-amber-500 to-orange-700" },
          { id: "c", emoji: "⚖️", titulo: "Os dois ampliam igual", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. O MICROSCÓPIO combina várias lentes e amplia muito mais que a lupa, que tem só uma lente.",
        feedbackErro: "A lupa tem uma lente só. O MICROSCÓPIO combina várias lentes e amplia muito mais." },
    ],
    falaFinal: "Você já sabe diferenciar cada instrumento pela sua função principal.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "A bancada divide-se em duas zonas: VER LONGE (luneta, periscópio, câmera) e VER PEQUENO (lupa, microscópio).",
    instrucao: "Toque nos interruptores",
    mapaUrl: sistema,
    camadas: [
      { id: "verlonge", rotulo: "Ver Longe", emoji: "🔭", cor: "from-indigo-500 to-purple-700",
        rect: { x: 5, y: 20, w: 45, h: 60 },
        descricao: "Lunetas e periscópios aproximam ou desviam a visão para enxergar o que está distante ou fora do campo de visão direto.",
        fotoUrl: sistema },
      { id: "verpequeno", rotulo: "Ver Pequeno", emoji: "🔬", cor: "from-emerald-500 to-green-700",
        rect: { x: 50, y: 20, w: 45, h: 60 },
        descricao: "Lupas e microscópios ampliam objetos pequenos, do detalhe de um inseto até uma célula.",
        fotoUrl: tempestade },
    ],
    falaFinal: "Longe ou pequeno, sempre há um instrumento óptico feito pra resolver o problema.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a ordem de ampliação, do instrumento mais simples ao mais potente para ver pequenos detalhes.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual a ordem de poder de ampliação, do menor ao maior?",
    paradas: [
      { id: "olho", emoji: "👁️", rotulo: "1. Olho nu", descricao: "Enxerga sem ajuda, com limite de tamanho e distância.", fotoUrl: terra },
      { id: "lupa", emoji: "🔍", rotulo: "2. Lupa", descricao: "Uma lente simples amplia poucas vezes o tamanho original.", fotoUrl: lua },
      { id: "microscopio", emoji: "🔬", rotulo: "3. Microscópio", descricao: "Várias lentes juntas ampliam centenas ou milhares de vezes.", fotoUrl: tempestade },
      { id: "microscopioeletronico", emoji: "🧫", rotulo: "4. Microscópio eletrônico", descricao: "Usa feixes de elétrons e amplia ainda mais, mostrando até vírus.", fotoUrl: sistema },
    ],
    ordemCerta: ["olho", "lupa", "microscopio", "microscopioeletronico"],
    feedbackAcerto: "Sequência correta! Cada etapa amplia muito mais que a anterior, revelando um mundo cada vez menor.",
    feedbackErro: "Repense: olho nu vê menos, depois lupa, depois microscópio comum, e por fim o microscópio eletrônico, o mais potente.",
    falaFinal: "Quanto mais lentes e tecnologia, mais fundo enxergamos no mundo microscópico.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura. Estuda o diário do cientista sobre instrumentos ópticos.",
    tituloLivro: "📓 Diário do Cientista",
    subtitulo: "Instrumentos que ampliam a visão",
    paragrafos: [
      { id: "p1", texto:
          "A LUNETA usa lentes organizadas em um tubo para aproximar objetos muito distantes. Foi com uma luneta aperfeiçoada que Galileu Galilei observou, em 1610, as quatro maiores luas de Júpiter.",
        chaves: ["luneta"],
        definicoes: {
          luneta: "Instrumento com lentes que aproxima objetos distantes.",
        }, fotoUrl: sistema },
      { id: "p2", texto:
          "Já o PERISCÓPIO usa dois espelhos inclinados a 45 graus para desviar a visão e enxergar por cima de obstáculos ou através de paredes — por isso é usado em submarinos.",
        chaves: ["periscópio"],
        definicoes: {
          periscópio: "Instrumento com espelhos que permite ver por cima de obstáculos.",
        }, fotoUrl: terra },
      { id: "p3", texto:
          "Para objetos pequenos, usamos a LUPA, com uma única lente, ou o MICROSCÓPIO, que combina várias lentes e amplia muito mais — o suficiente para ver células e bactérias. E a CÂMERA FOTOGRÁFICA usa uma lente para captar a luz e registrar a imagem, seja de uma paisagem ou de uma estrela distante.",
        chaves: ["lupa", "microscópio", "câmera fotográfica"],
        definicoes: {
          lupa: "Lente simples que amplia objetos pequenos e próximos.",
          microscópio: "Instrumento com várias lentes que amplia muito objetos microscópicos.",
          "câmera fotográfica": "Instrumento que capta luz por uma lente e registra imagens.",
        }, fotoUrl: tempestade },
    ],
    falaFinal: "Você entende agora como cada instrumento amplia um pedaço diferente do mundo.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Identifique qual instrumento óptico resolve cada situação.",
    instrucao: "⏱️ Leia e escolha o instrumento correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "luneta", emoji: "🔭", rotulo: "Luneta" },
      { id: "periscopio", emoji: "🪞", rotulo: "Periscópio" },
      { id: "lupa", emoji: "🔍", rotulo: "Lupa" },
      { id: "microscopio", emoji: "🔬", rotulo: "Microscópio" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Observar anéis de Saturno", emoji: "🪐", cor: "from-indigo-500 to-purple-700" },
        municipioB: { nome: "Objeto muito distante", emoji: "🌌", cor: "from-indigo-500 to-purple-700" },
        contexto: "Você quer ver detalhes de um planeta que está a milhões de quilômetros.",
        pecaCertaId: "luneta", fotoUrl: sistema,
        feedbackAcerto: "Sim. Para objetos distantes no espaço, usamos a LUNETA.",
        feedbackErro: "Objetos muito distantes exigem a LUNETA." },
      { id: "r2", municipioA: { nome: "Dentro de um submarino", emoji: "🚢", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Ver a superfície do mar", emoji: "🌊", cor: "from-cyan-500 to-sky-700" },
        contexto: "Sem sair da água, a tripulação precisa enxergar o que está acima.",
        pecaCertaId: "periscopio", fotoUrl: terra,
        feedbackAcerto: "Perfeito. Ver por cima de um obstáculo é função do PERISCÓPIO.",
        feedbackErro: "Ver por cima de obstáculos usando espelhos é o PERISCÓPIO." },
      { id: "r3", municipioA: { nome: "Examinar as veias de uma folha", emoji: "🍃", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "Objeto pequeno e próximo", emoji: "🔍", cor: "from-amber-500 to-orange-700" },
        contexto: "Você quer ver detalhes de um objeto pequeno que já está na sua mão.",
        pecaCertaId: "lupa", fotoUrl: lua,
        feedbackAcerto: "Isso. Para objetos pequenos e próximos, basta a LUPA.",
        feedbackErro: "Um objeto pequeno já próximo se examina com a LUPA." },
      { id: "r4", municipioA: { nome: "Observar células de uma cebola", emoji: "🧅", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Invisível a olho nu", emoji: "🔬", cor: "from-emerald-500 to-green-700" },
        contexto: "As células são pequenas demais até para a lupa enxergar bem.",
        pecaCertaId: "microscopio", fotoUrl: tempestade,
        feedbackAcerto: "Correto. Estruturas microscópicas exigem o MICROSCÓPIO.",
        feedbackErro: "Células são pequenas demais até para a lupa. Use o MICROSCÓPIO." },
      { id: "r5", municipioA: { nome: "Ver as crateras da Lua de casa", emoji: "🌑", cor: "from-indigo-500 to-purple-700" },
        municipioB: { nome: "Astro no céu noturno", emoji: "🌃", cor: "from-indigo-500 to-purple-700" },
        contexto: "Você quer observar detalhes da superfície lunar do quintal de casa.",
        pecaCertaId: "luneta", fotoUrl: lua,
        feedbackAcerto: "Sim. Observar detalhes da Lua a olho é função da LUNETA.",
        feedbackErro: "Astros distantes no céu se observam com a LUNETA." },
    ],
    falaFinal: "Você já sabe escolher o instrumento certo para cada tipo de observação.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "Os instrumentos ópticos em duas metades: VER LONGE (luneta, periscópio, câmera) e VER PEQUENO (lupa, microscópio).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: sistema,
    fatias: [
      { id: "verlonge", rotulo: "Ver longe", emoji: "🔭", percentual: 50, cor: "#6d28d9",
        descricao: "Luneta e periscópio aproximam ou desviam a visão para enxergar o que está distante ou escondido.",
        exemplos: ["Luneta", "Periscópio", "Câmera"], fotoUrl: sistema },
      { id: "verpequeno", rotulo: "Ver pequeno", emoji: "🔬", percentual: 50, cor: "#059669",
        descricao: "Lupa e microscópio ampliam objetos pequenos, do detalhe de uma folha até uma célula.",
        exemplos: ["Lupa", "Microscópio"], fotoUrl: tempestade },
    ],
    falaFinal: "Ver longe e ver pequeno: dois desafios diferentes, resolvidos com lentes e espelhos.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Cientista da Óptica Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: sistema,
    perguntas: [
      { id: "q1", pergunta: "Qual instrumento é usado para observar planetas e estrelas?",
        fotoUrl: sistema,
        opcoes: [
          { id: "a", texto: "Luneta", correta: true },
          { id: "b", texto: "Microscópio" },
        ],
        feedbackAcerto: "Sim. A LUNETA aproxima objetos muito distantes, como astros.",
        feedbackErro: "Microscópio é para o muito pequeno. Para o céu, use a LUNETA." },
      { id: "q2", pergunta: "Qual instrumento usa espelhos para ver por cima de obstáculos?",
        fotoUrl: terra,
        opcoes: [
          { id: "a", texto: "Periscópio", correta: true },
          { id: "b", texto: "Lupa" },
        ],
        feedbackAcerto: "Correto. O PERISCÓPIO usa espelhos para desviar a visão.",
        feedbackErro: "Lupa amplia objetos pequenos. Ver por cima de obstáculos é o PERISCÓPIO." },
      { id: "q3", pergunta: "Por que o microscópio amplia mais do que a lupa?",
        fotoUrl: tempestade,
        opcoes: [
          { id: "a", texto: "Porque combina várias lentes", correta: true },
          { id: "b", texto: "Porque usa espelhos em vez de lentes" },
        ],
        feedbackAcerto: "Sim. Várias lentes juntas multiplicam a ampliação do microscópio.",
        feedbackErro: "O microscópio também usa lentes, mas VÁRIAS combinadas — por isso amplia mais." },
    ],
    selo: {
      nome: "Cientista da Óptica Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 8 concluído",
      emoji: "🔭",
      cor: "from-purple-400 via-indigo-500 to-emerald-700",
    },
    falaFinal: "Cientista da óptica júnior aprovado. Você já sabe escolher a ferramenta certa pra cada observação.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Cientista da Óptica Júnior" },
};
