import type { AulaGeoV1 } from "../types";
import { aula01 as base } from "./unidade-1/aula-01-principios-eticos";
import { url as diversidade } from "@/assets/ensino-religioso-5ano/01-diversidade.jpg.asset.json";
import { url as oralidade } from "@/assets/ensino-religioso-6ano/u2-oralidade.jpg.asset.json";

type Plano={slug:string;titulo:string;icone:string;bncc:string[];objetivo:string;conceitos:Array<[string,string]>;casos:Array<[string,string]>;pergunta:string;correta:string;distratores:[string,string,string];passos:string[];medalha:string};
const cores=["from-amber-500 to-orange-700","from-sky-500 to-blue-700","from-emerald-500 to-green-700","from-purple-500 to-fuchsia-700"];

function criar(p:Plano):AulaGeoV1{return{
 ...base,slug:p.slug,titulo:p.titulo,iconeTrilha:p.icone,bncc:p.bncc,duracaoMin:26,
 cena01_motivacao:{tipo:"mesaCartografo",instrucao:"Observe os contextos antes de formar conclusões.",mapaUrl:diversidade,imagemDestaqueUrl:diversidade,aurora:p.objetivo,falaFinal:"A abordagem é não confessional: conhecer, analisar e respeitar sem exigir crença ou participação."},
 cena02_previsao:{tipo:"votoExplorador",aurora:"Registre uma hipótese e depois confirme com os casos.",pergunta:p.pergunta,opcoes:[{id:"c",titulo:p.correta,subtitulo:"Resposta baseada no conteúdo",emoji:"🔎",cor:cores[0]},...p.distratores.map((titulo,i)=>({id:`e${i}`,titulo,subtitulo:"Confira as evidências",emoji:["💭","📘","🧭"][i],cor:cores[i+1]}))],respostaCerta:"c",feedbackAcerto:`Correto: ${p.correta}.`,feedbackErro:`Retome os casos: ${p.correta}.`,falaFinal:"Agora vamos justificar a resposta."},
 cena03_vocabulario:{tipo:"cadernosCampo",aurora:"Abra os conceitos necessários.",instrucao:"Toque nos quatro cadernos",cadernos:p.conceitos.map(([capa,conteudo],i)=>({id:`v${i}`,capa,emoji:["📘","🧠","🤝","⚖️"][i],cor:cores[i],conteudo,exemplo:`Use este conceito para analisar: ${p.casos[i]?.[0]??p.casos[0][0]}.`,fotoUrl:i%2?oralidade:diversidade})),falaFinal:"Conceitos aprendidos; agora aplique-os."},
 cena04_leituraGuiada:{tipo:"narrarMapa",aurora:"Leia os quatro casos sem generalizar pessoas ou tradições.",instrucao:"Toque em cada caso",mapaUrl:diversidade,pontos:p.casos.map(([titulo,texto],i)=>({id:`p${i}`,x:[24,72,27,74][i],y:[28,28,70,70][i],emoji:["🗣️","🧭","🤝","⚖️"][i],cor:cores[i],titulo,texto,fotoUrl:i%2?oralidade:diversidade})),falaFinal:"Casos diferentes pedem análise de contexto, finalidade, consequências e direitos."},
 cena05_compreensao:{tipo:"quizRadar",aurora:"Responda com base nos conceitos.",instrucao:"Escolha a análise correta",perguntas:[{id:"q1",pergunta:p.pergunta,fotoUrl:diversidade,cards:[{id:"c",emoji:"✅",titulo:p.correta,cor:cores[0]},...p.distratores.map((titulo,i)=>({id:`e${i}`,emoji:"🔎",titulo,cor:cores[i+1]}))],correta:"c",feedbackAcerto:`Isso: ${p.correta}.`,feedbackErro:`A resposta fundamentada é: ${p.correta}.`}],falaFinal:"Você respondeu por evidências, não por preferência religiosa."},
 cena06_personagensLugar:{tipo:"mapaBrasilInterativo",aurora:"O Brasil reúne muitas tradições, filosofias de vida e pessoas sem religião.",instrucao:"Selecione estados das cinco regiões",missao:{tipo:"selecionar",siglas:["AM","BA","DF","SP","RS"],pergunta:"Qual conjunto representa as cinco regiões brasileiras?"},falaFinal:"Direitos, convivência e diversidade dizem respeito ao país inteiro."},
 cena07_sequencia:{tipo:"linhaEstrada",aurora:"Organize um método de análise ética.",instrucao:"Toque na ordem",pergunta:"Como analisar uma situação?",paradas:p.passos.map((rotulo,i)=>({id:`s${i}`,emoji:["👀","📘","🧠","🤝","⚖️"][i%5],rotulo:`${i+1}. ${rotulo}`,descricao:"Etapa necessária para compreender o contexto e agir com respeito."})),ordemCerta:p.passos.map((_,i)=>`s${i}`),feedbackAcerto:"Sequência correta: contexto, informação, análise, diálogo e ação responsável.",feedbackErro:"Comece entendendo o contexto antes de decidir ou agir.",falaFinal:"Análise responsável evita preconceitos e generalizações."},
 cena08_voceLe:{tipo:"voceLeSozinho",aurora:"Leia e marque as ideias-chave.",tituloLivro:`Caderno do Investigador — ${p.titulo}`,subtitulo:p.bncc.join(" · "),paragrafos:[{id:"l1",texto:p.objetivo,chaves:["reconhecer","respeitar"]},...p.casos.map(([titulo,texto],i)=>({id:`l${i+2}`,texto:`${titulo}: ${texto}`,chaves:texto.split(" ").filter(x=>x.length>7).slice(0,2)}))],falaFinal:"Use os trechos como evidência."},
 cena09_minijogo:{tipo:"construtorMarcos",aurora:"Relacione cada caso ao conceito central.",instrucao:"Escolha a peça adequada",duracaoSegundos:20,pecas:p.conceitos.map(([rotulo],i)=>({id:`m${i}`,emoji:["📘","🧠","🤝","⚖️"][i],rotulo})),rodadas:p.casos.map(([titulo,texto],i)=>({id:`r${i}`,municipioA:{nome:titulo,emoji:"📍",cor:cores[i]},municipioB:{nome:"Conceito principal",emoji:"🔎",cor:cores[(i+1)%4]},contexto:texto,pecaCertaId:`m${i}`,feedbackAcerto:"Relação coerente com o caso.",feedbackErro:"Retome a definição do conceito e as palavras do caso."})),falaFinal:"Você aplicou conceitos a situações concretas."},
 cena10_revisao:{tipo:"pizzaMunicipio",aurora:"Revise os dois compromissos centrais.",instrucao:"Toque nas partes",fatias:[{id:"compreender",rotulo:"COMPREENDER",emoji:"🧠",percentual:50,cor:"#8b5cf6",descricao:p.objetivo,exemplos:p.casos.slice(0,2).map(c=>c[0])},{id:"respeitar",rotulo:"AGIR COM RESPEITO",emoji:"🤝",percentual:50,cor:"#10b981",descricao:"Aplicar direitos, diálogo e convivência ética sem impor religião ou convicção.",exemplos:["Escuta","Diálogo","Direitos"]}],falaFinal:"Conhecimento precisa orientar convivência respeitosa."},
 cena11_avaliacao:{tipo:"seloAtlas",aurora:"Avaliação final com quatro alternativas.",instrucao:"Responda com base nos casos",perguntas:[{id:"a1",pergunta:p.pergunta,opcoes:[{id:"a",texto:p.distratores[0],correta:false},{id:"b",texto:p.correta,correta:true},{id:"c",texto:p.distratores[1],correta:false},{id:"d",texto:p.distratores[2],correta:false}],feedbackAcerto:`Correto: ${p.correta}.`,feedbackErro:`Revise os casos: ${p.correta}.`},{id:"a2",pergunta:"Qual atitude combina com uma abordagem não confessional?",opcoes:[{id:"a",texto:"Estudar contextos e respeitar diferentes convicções",correta:true},{id:"b",texto:"Obrigar participação em uma prática",correta:false},{id:"c",texto:"Escolher qual tradição é superior",correta:false},{id:"d",texto:"Ridicularizar quem pensa diferente",correta:false}],feedbackAcerto:"Isso: conhecer sem impor.",feedbackErro:"Ensino não confessional estuda e respeita sem impor."},{id:"a3",pergunta:"Uma conclusão responsável precisa de:",opcoes:[{id:"a",texto:"Preferência pessoal",correta:false},{id:"b",texto:"Contexto, conceitos e evidências",correta:true},{id:"c",texto:"Generalização",correta:false},{id:"d",texto:"Estereótipo",correta:false}],feedbackAcerto:"Correto: contexto, conceito e evidência.",feedbackErro:"Evite generalizações e use evidências."}],selo:{nome:p.medalha,subtitulo:p.bncc.join(" · "),emoji:p.icone,cor:"from-amber-300 to-orange-500"},falaFinal:"Oficina concluída com análise crítica e respeito."},
 recompensa:{xp:500,moedas:350,medalha:p.medalha}
};}

export const oficinas7Ano:AulaGeoV1[]=[
 criar({slug:"oficina-comunicacao-espiritualidade",titulo:"Comunicação e Espiritualidade",icone:"🗣️",bncc:["EF07ER01","EF07ER02"],objetivo:"Reconhecer e respeitar práticas de comunicação com divindades e identificar práticas de espiritualidade utilizadas em situações específicas, sem afirmar que todas as pessoas respondem do mesmo modo.",conceitos:[["Comunicação com divindades","Práticas como oração, canto, silêncio, recitação, dança ou oferenda possuem sentidos definidos por cada tradição."],["Espiritualidade","Busca de sentido, conexão, reflexão ou cuidado, religiosa ou vinculada a filosofias de vida."],["Situação de vulnerabilidade","Acidentes, doenças e fenômenos climáticos podem levar algumas pessoas a buscar apoio espiritual, além de cuidados profissionais."],["Respeito e autonomia","Ninguém deve ser obrigado a praticar; apoio espiritual não substitui atendimento médico, proteção civil ou políticas públicas."]],casos:[["Oração comunitária","Uma comunidade se reúne para orar conforme sua tradição, enquanto respeita quem não deseja participar."],["Meditação e silêncio","Uma pessoa usa respiração, meditação ou silêncio para organizar emoções em uma situação difícil."],["Doença","Familiares buscam apoio espiritual e também seguem as orientações da equipe de saúde."],["Fenômeno climático","A comunidade oferece acolhimento espiritual sem substituir evacuação, abrigo e assistência pública."]],pergunta:"Como tratar práticas de espiritualidade em situações difíceis?",correta:"Com respeito e autonomia, junto dos cuidados profissionais necessários",distratores:["Como substitutas obrigatórias da medicina","Como práticas iguais para todas as pessoas","Como prova de que uma tradição é superior"],passos:["Identificar a situação","Reconhecer a prática e seu contexto","Distinguir apoio espiritual de serviço profissional","Respeitar autonomia","Garantir segurança e direitos"],medalha:"Analista da Espiritualidade"}),
 criar({slug:"oficina-liderancas-contribuicoes",titulo:"Lideranças e Contribuições Sociais",icone:"🧭",bncc:["EF07ER03","EF07ER04"],objetivo:"Reconhecer papéis atribuídos a diferentes lideranças religiosas e exemplificar contribuições sociais concretas sem transformar lideranças em representantes absolutos de toda uma tradição.",conceitos:[["Liderança religiosa","Pode orientar práticas, ensinar, mediar conflitos, cuidar de comunidades ou preservar memórias, conforme a tradição."],["Papel comunitário","Atribuições variam entre rabinos, padres, pastoras, imãs, mães e pais de santo, monges, pajés e outras lideranças."],["Contribuição social","Ação verificável em educação, paz, direitos, solidariedade, ambiente ou combate à discriminação."],["Contextualização","Uma liderança deve ser estudada por fontes, ações e contexto histórico, evitando culto à personalidade e generalizações."]],casos:[["Ensino e memória","Lideranças preservam narrativas, interpretam textos e formam novas gerações."],["Mediação e cuidado","Algumas organizam acolhimento, escuta e resolução de conflitos comunitários."],["Direitos e solidariedade","Há lideranças que participaram de movimentos por direitos civis, paz, assistência e dignidade."],["Responsabilidade pública","Contribuições devem ser avaliadas por ações e consequências, reconhecendo também limites e controvérsias."]],pergunta:"Como avaliar a contribuição social de uma liderança?",correta:"Por ações, contexto, fontes e efeitos na sociedade",distratores:["Pelo número de seguidores apenas","Como representante perfeita de toda a religião","Sem verificar fatos históricos"],passos:["Identificar o papel","Pesquisar fontes confiáveis","Descrever a ação","Analisar efeitos sociais","Evitar generalizações"],medalha:"Pesquisador de Lideranças"}),
 criar({slug:"oficina-convivencia-principios",titulo:"Convivência e Princípios Éticos",icone:"🤝",bncc:["EF07ER05","EF07ER06"],objetivo:"Discutir estratégias de convivência ética entre religiões e identificar princípios éticos de tradições religiosas e filosofias de vida, relacionando-os criticamente a condutas pessoais e práticas sociais.",conceitos:[["Convivência ética","Relação baseada em direitos, diálogo, limites e proteção contra discriminação."],["Princípio ético","Referência como justiça, compaixão, honestidade, responsabilidade ou cuidado, interpretada em contextos diversos."],["Conduta pessoal","Escolhas individuais influenciadas por valores, reflexão, leis e convivência."],["Prática social","Ações coletivas e institucionais devem ser avaliadas por seus impactos, não apenas por discursos."]],casos:[["Diálogo com regras","Pessoas discordam, mas escutam, justificam posições e não atacam identidades."],["Projeto comunitário","Grupos religiosos, filosofias de vida e pessoas sem religião cooperam numa ação social comum."],["Conflito na escola","A equipe protege a vítima, interrompe a discriminação e promove educação, sem obrigar reconciliação imediata."],["Princípio e prática","Uma instituição afirma solidariedade; a análise verifica se suas ações realmente incluem quem precisa."]],pergunta:"Qual estratégia promove convivência ética?",correta:"Garantir direitos, diálogo, limites e cooperação sem apagar diferenças",distratores:["Obrigar todos a concordar","Evitar qualquer contato entre grupos","Permitir ofensas em nome da opinião"],passos:["Reconhecer o conflito","Proteger direitos e segurança","Escutar perspectivas","Buscar ação comum possível","Avaliar resultados"],medalha:"Construtor da Convivência"}),
 criar({slug:"oficina-direitos-liberdade",titulo:"Lideranças, Direitos e Liberdade",icone:"⚖️",bncc:["EF07ER07","EF07ER08"],objetivo:"Discutir o papel de lideranças religiosas e seculares na promoção dos direitos humanos e reconhecer a liberdade de consciência, crença ou convicção, questionando práticas que a violam.",conceitos:[["Direitos humanos","Direitos universais ligados à dignidade, igualdade, liberdade e proteção de todas as pessoas."],["Liderança secular","Pessoa ou instituição de atuação não religiosa que pode defender direitos, como educadores, ativistas e agentes públicos."],["Liberdade de consciência","Direito de formar convicções, ter religião, mudar de religião ou não ter religião."],["Violação","Coerção, discriminação, violência ou impedimento de manifestação legítima exigem proteção e resposta responsável."]],casos:[["Coalizão por direitos","Lideranças religiosas e seculares cooperam contra fome ou discriminação sem exigir adesão religiosa."],["Escolha individual","Uma estudante decide não participar de prática religiosa e continua tendo direito a respeito e pertencimento."],["Mudança de convicção","Uma pessoa muda de religião ou deixa de ter religião sem sofrer coerção ou punição social."],["Intolerância","A escola interrompe perseguição, acolhe a vítima, registra o caso e aciona responsáveis e proteção adequada."]],pergunta:"O que a liberdade de consciência, crença ou convicção protege?",correta:"O direito de crer, mudar, não crer e expressar convicções dentro dos direitos humanos",distratores:["O direito de obrigar outras pessoas","Somente religiões majoritárias","A discriminação contra quem discorda"],passos:["Reconhecer o direito","Identificar possível violação","Proteger a pessoa afetada","Acionar apoio responsável","Promover educação e prevenção"],medalha:"Defensor da Liberdade"})
];
