import type { AulaGeoV1 } from "../../types";
import sintese from "@/assets/geografia-6ano/sintese-geografica.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-sintese-planeta",
  titulo: "Síntese: O Planeta Integrado",
  iconeTrilha: "🌐",
  bncc: ["EF06GE01", "EF06GE03", "EF06GE12", "EF06GE13"],
  duracaoMin: 25,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Tudo conectado: movimentos, rochas, clima, vida.",
    mapaUrl: sintese,
    imagemDestaqueUrl: sintese,
    aurora:
      "Explorador, chegamos ao FIM da jornada. Você viu: a Terra gira, viaja e é inclinada. A crosta é dividida em placas. O relevo se formou em milhões de anos. O clima depende da latitude. E os biomas nascem dessa combinação toda. Tudo é UM SISTEMA.",
    falaFinal: "Hora de juntar as peças. Um planeta, mil conexões.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Por que a AMAZÔNIA tem tanta chuva o ano todo?",
    pergunta: "O que explica isso?",
    opcoes: [
      { id: "sist", titulo: "SISTEMA: Equador + massas úmidas + relevo", subtitulo: "tudo conectado", emoji: "🌐", cor: "from-emerald-400 to-teal-600" },
      { id: "sorte", titulo: "SORTE geográfica", subtitulo: "puro acaso", emoji: "🎲", cor: "from-slate-400 to-gray-600" },
    ],
    respostaCerta: "sist",
    feedbackAcerto:
      "Exato! Amazônia está no Equador (sol direto) + recebe massa úmida do Atlântico + tem floresta que EVAPORA água = chuva constante. Ciclo integrado.",
    feedbackErro: "Nada em Geografia é sorte. Amazônia = latitude + massa de ar + floresta trabalhando junto.",
    falaFinal: "Geografia é sistema. Nada isolado.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "4 grandes ideias que amarram tudo que você aprendeu.",
    instrucao: "Toque em cada caderno",
    cadernos: [
      { id: "movim", capa: "1. Movimentos da Terra", emoji: "🌍", cor: "from-sky-500 to-indigo-700",
        conteudo: "ROTAÇÃO + TRANSLAÇÃO + INCLINAÇÃO criam dia/noite, estações e climas. Nossa vida inteira depende disso.",
        exemplo: "Ex.: sem inclinação, não haveria estações." },
      { id: "crosta", capa: "2. Crosta em movimento", emoji: "🌋", cor: "from-red-500 to-rose-700",
        conteudo: "PLACAS TECTÔNICAS moldam continentes, criam montanhas, vulcões e terremotos.",
        exemplo: "Ex.: Andes existem porque placa de Nazca bate na Sul-Americana." },
      { id: "atmos", capa: "3. Atmosfera dinâmica", emoji: "🌦️", cor: "from-emerald-500 to-teal-700",
        conteudo: "MASSAS DE AR + LATITUDE + CICLO DA ÁGUA definem o clima de cada canto do planeta.",
        exemplo: "Ex.: no Equador chove muito porque o sol evapora muita água." },
      { id: "vida", capa: "4. Vida se adapta", emoji: "🌳", cor: "from-amber-500 to-orange-700",
        conteudo: "BIOMAS surgem onde clima e relevo se encontram. Cada bioma é um sistema vivo único.",
        exemplo: "Ex.: Caatinga só existe porque o sertão é semiárido." },
    ],
    falaFinal: "4 grandes ideias, 1 planeta integrado.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "Aponte cada conexão entre os sistemas do planeta.",
    instrucao: "Toque em cada balão",
    mapaUrl: sintese,
    pontos: [
      { id: "movim", x: 25, y: 25, emoji: "🌍", cor: "from-sky-500 to-indigo-700",
        titulo: "MOVIMENTOS → CLIMA",
        texto: "Inclinação do eixo faz o Sol bater mais forte no Equador. Latitude puxa temperatura. Movimentos definem clima." },
      { id: "placa", x: 75, y: 30, emoji: "🌋", cor: "from-red-500 to-rose-700",
        titulo: "TECTÔNICA → RELEVO",
        texto: "Placas colidem e formam montanhas (Andes, Himalaia). Placas se afastam e criam vulcões. Relevo nasce do movimento." },
      { id: "relevo", x: 30, y: 70, emoji: "⛰️", cor: "from-amber-500 to-orange-700",
        titulo: "RELEVO → CLIMA",
        texto: "Serras bloqueiam massas de ar. Um lado chove, outro seca (sombra pluviométrica). Relevo molda clima local." },
      { id: "biomas", x: 70, y: 75, emoji: "🌳", cor: "from-emerald-500 to-green-700",
        titulo: "CLIMA + RELEVO → BIOMAS",
        texto: "Onde tem chuva forte + solo bom = floresta. Onde tem seca + calor = savana ou deserto. Bioma é fruto dessa combinação." },
    ],
    falaFinal: "4 conexões formam o sistema Terra. Nada isolado.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de síntese.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "O que causa as ESTAÇÕES do ano?",
        cards: [
          { id: "i", emoji: "📐", titulo: "Inclinação do eixo", cor: "from-emerald-500 to-teal-700" },
          { id: "d", emoji: "📏", titulo: "Distância ao Sol", cor: "from-amber-500 to-orange-700" },
          { id: "l", emoji: "🌙", titulo: "Fases da Lua", cor: "from-slate-500 to-gray-700" },
        ], correta: "i",
        feedbackAcerto: "Isso! INCLINAÇÃO.", feedbackErro: "INCLINAÇÃO do eixo." },
      { id: "q2", pergunta: "Onde acontece a MAIORIA dos terremotos?",
        cards: [
          { id: "b", emoji: "🌋", titulo: "Bordas de placas", cor: "from-red-500 to-rose-700" },
          { id: "m", emoji: "🌳", titulo: "Meio dos continentes", cor: "from-emerald-500 to-teal-700" },
          { id: "o", emoji: "🌊", titulo: "Nos oceanos calmos", cor: "from-sky-500 to-blue-700" },
        ], correta: "b",
        feedbackAcerto: "Isso! BORDAS de placa.", feedbackErro: "Sempre nas BORDAS de placa." },
      { id: "q3", pergunta: "Bioma EXCLUSIVAMENTE brasileiro:",
        cards: [
          { id: "c", emoji: "🌵", titulo: "Caatinga", cor: "from-amber-500 to-orange-700" },
          { id: "a", emoji: "🌳", titulo: "Amazônia", cor: "from-emerald-500 to-teal-700" },
          { id: "p", emoji: "🐎", titulo: "Pampa", cor: "from-lime-500 to-green-700" },
        ], correta: "c",
        feedbackAcerto: "Isso! CAATINGA.", feedbackErro: "CAATINGA só existe no Brasil." },
    ],
    falaFinal: "Revisão perfeita.",
  },

  cena06_personagensLugar: {
    tipo: "mapaBrasilInterativo",
    aurora:
      "Missão FINAL: acenda os 5 estados MAIS BIODIVERSOS do Brasil — onde a floresta amazônica é mais preservada.",
    instrucao: "Marque os 5 estados com mais Amazônia preservada",
    missao: {
      tipo: "selecionar",
      siglas: ["AM", "PA", "AC", "RR", "AP"],
      pergunta: "Onde está o coração da Amazônia?",
    },
    falaFinal:
      "AM, PA, AC, RR, AP — coração verde do país. Protegê-los é proteger o clima do planeta.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Organize a CADEIA DE INFLUÊNCIAS que forma um bioma.",
    instrucao: "Toque na ordem",
    pergunta: "Como um bioma surge?",
    paradas: [
      { id: "sol", emoji: "☀️", rotulo: "1. Sol e latitude",
        descricao: "Latitude define quanta luz chega." },
      { id: "clima", emoji: "🌦️", rotulo: "2. Clima se estabelece",
        descricao: "Massas de ar definem temperatura e umidade." },
      { id: "relevo", emoji: "⛰️", rotulo: "3. Relevo modifica",
        descricao: "Montanhas e planaltos mudam o clima local." },
      { id: "solo", emoji: "🌱", rotulo: "4. Solo se forma",
        descricao: "Rocha + clima + tempo = tipo de solo." },
      { id: "vegetacao", emoji: "🌳", rotulo: "5. Vegetação cresce",
        descricao: "Plantas adaptadas aparecem." },
      { id: "bioma", emoji: "🌍", rotulo: "6. Bioma completo",
        descricao: "Fauna, flora e ecossistemas se estabelecem." },
    ],
    ordemCerta: ["sol", "clima", "relevo", "solo", "vegetacao", "bioma"],
    feedbackAcerto: "Perfeita! Cadeia completa da natureza.",
    feedbackErro: "Sol → clima → relevo → solo → vegetação → bioma.",
    falaFinal: "6 passos, 1 bioma. Sempre nessa ordem.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua última leitura.",
    tituloLivro: "📘 Manual do Explorador Planetário",
    subtitulo: "Capítulo Final — Síntese",
    paragrafos: [
      { id: "p1", texto: "A Terra é um SISTEMA integrado onde movimentos, crosta, atmosfera e vida se INFLUENCIAM mutuamente.",
        chaves: ["sistema", "integrado", "influenciam"] },
      { id: "p2", texto: "Sem a INCLINAÇÃO do eixo não teríamos ESTAÇÕES. Sem placas em movimento não teríamos MONTANHAS.",
        chaves: ["inclinação", "estações", "montanhas"] },
      { id: "p3", texto: "O CLIMA depende da latitude, das massas de ar e do RELEVO. Ele define onde cada bioma pode existir.",
        chaves: ["clima", "latitude", "relevo", "bioma"] },
      { id: "p4", texto: "PROTEGER o planeta é entender que TUDO está conectado — mudança em um sistema afeta todos os outros.",
        chaves: ["proteger", "conectado", "sistema"] },
    ],
    falaFinal: "Leu tudo? Missão final chegando.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Minijogo GEÓGRAFO MESTRE! Qual FENÔMENO explica o cenário?",
    instrucao: "⏱️ Escolha a explicação certa",
    duracaoSegundos: 15,
    pecas: [
      { id: "rot", emoji: "🔄", rotulo: "Rotação da Terra" },
      { id: "trans", emoji: "🛰️", rotulo: "Translação" },
      { id: "incl", emoji: "📐", rotulo: "Inclinação" },
      { id: "placa", emoji: "🌋", rotulo: "Placas tectônicas" },
      { id: "massa", emoji: "💨", rotulo: "Massa de ar" },
      { id: "bioma", emoji: "🌳", rotulo: "Bioma adaptado" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Cactos no sertão", emoji: "🌵", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Caatinga", emoji: "🌾", cor: "from-yellow-400 to-red-600" },
        contexto: "Plantas espinhosas armazenam água pra sobreviver ao clima seco. Por quê?",
        pecaCertaId: "bioma",
        feedbackAcerto: "Isso! BIOMA adaptado ao semiárido.", feedbackErro: "Adaptação ao clima = BIOMA." },
      { id: "r2", municipioA: { nome: "Sol nasce no Japão antes de SP", emoji: "🌅", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Fusos horários", emoji: "🕐", cor: "from-sky-400 to-blue-600" },
        contexto: "Enquanto Tóquio amanhece, SP dorme. Por quê?",
        pecaCertaId: "rot",
        feedbackAcerto: "Isso! ROTAÇÃO da Terra.", feedbackErro: "Diferença de horas = ROTAÇÃO." },
      { id: "r3", municipioA: { nome: "Andes com 6.000 m", emoji: "🏔️", cor: "from-slate-400 to-gray-600" },
        municipioB: { nome: "Vulcões no Chile", emoji: "🌋", cor: "from-red-400 to-rose-600" },
        contexto: "Cordilheira imensa e vulcões ativos no oeste da América do Sul. Por quê?",
        pecaCertaId: "placa",
        feedbackAcerto: "Isso! PLACAS tectônicas em colisão.", feedbackErro: "Cordilheira + vulcões = PLACAS." },
      { id: "r4", municipioA: { nome: "Amazônia chuvosa", emoji: "🌧️", cor: "from-emerald-400 to-teal-600" },
        municipioB: { nome: "Umidade do Atlântico", emoji: "💨", cor: "from-sky-400 to-blue-600" },
        contexto: "Massa de ar úmida entra pelo Norte e faz chover o ano todo. Que fator?",
        pecaCertaId: "massa",
        feedbackAcerto: "Isso! MASSAS DE AR determinam a chuva.", feedbackErro: "Chuva vem da MASSA DE AR." },
      { id: "r5", municipioA: { nome: "Verão em dezembro no Brasil", emoji: "🏖️", cor: "from-sky-400 to-blue-600" },
        municipioB: { nome: "Inverno em julho", emoji: "🧥", cor: "from-slate-400 to-gray-600" },
        contexto: "Estações opostas entre hemisférios. Por quê?",
        pecaCertaId: "incl",
        feedbackAcerto: "Isso! INCLINAÇÃO do eixo.", feedbackErro: "Estações opostas = INCLINAÇÃO." },
      { id: "r6", municipioA: { nome: "Ano bissexto", emoji: "📅", cor: "from-purple-400 to-fuchsia-600" },
        municipioB: { nome: "365 dias e 6 h", emoji: "🎂", cor: "from-emerald-400 to-teal-600" },
        contexto: "A cada 4 anos, 1 dia extra em fevereiro. Por quê?",
        pecaCertaId: "trans",
        feedbackAcerto: "Isso! TRANSLAÇÃO dura 365,25 dias.", feedbackErro: "Ano bissexto = TRANSLAÇÃO." },
    ],
    falaFinal: "6 fenômenos identificados. Geógrafo formado!",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "Pizza SÍNTESE: Astronomia + Terra Física + Vida.",
    instrucao: "Toque em cada fatia",
    fatias: [
      { id: "fisica", rotulo: "Terra física (astronomia + placas + clima)", emoji: "🌍", percentual: 70, cor: "#6366f1",
        descricao: "Movimentos da Terra, tectônica, relevo e atmosfera — o palco físico do planeta.",
        exemplos: ["🔄 Rotação", "🌋 Placas", "🌦️ Clima"] },
      { id: "vida", rotulo: "Vida (biomas)", emoji: "🌳", percentual: 30, cor: "#059669",
        descricao: "Onde o físico encontra o biológico — 6 biomas brasileiros nascem dessa combinação.",
        exemplos: ["🌳 Amazônia", "🌵 Caatinga", "💧 Pantanal"] },
    ],
    falaFinal: "3 camadas, 1 planeta. Tudo estudado, tudo conectado.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 finais pra ganhar a insígnia MESTRE PLANETÁRIO.",
    instrucao: "Responda as 3",
    perguntas: [
      { id: "av1", pergunta: "A Terra é considerada um SISTEMA porque:",
        opcoes: [
          { id: "a", texto: "Cada camada funciona independente", correta: false },
          { id: "b", texto: "Movimentos, crosta, clima e vida se influenciam", correta: true },
          { id: "c", texto: "Tudo depende só do Sol", correta: false },
        ],
        feedbackAcerto: "Isso! Todas as partes se influenciam.", feedbackErro: "SISTEMA = tudo se conecta e se influencia." },
      { id: "av2", pergunta: "A ORDEM correta que forma um bioma é:",
        opcoes: [
          { id: "a", texto: "Bioma → clima → solo → vegetação", correta: false },
          { id: "b", texto: "Latitude → clima → relevo → solo → vegetação → bioma", correta: true },
          { id: "c", texto: "Vegetação → solo → clima → bioma", correta: false },
        ],
        feedbackAcerto: "Isso! Do sol pra planta.", feedbackErro: "Começa em latitude, termina em bioma." },
      { id: "av3", pergunta: "Proteger o meio ambiente exige entender que:",
        opcoes: [
          { id: "a", texto: "Cada bioma é isolado", correta: false },
          { id: "b", texto: "Tudo está conectado — mudança afeta o sistema todo", correta: true },
          { id: "c", texto: "Só a Amazônia importa", correta: false },
        ],
        feedbackAcerto: "Isso! Uma mudança afeta tudo.", feedbackErro: "TUDO conectado. Mudar 1 afeta o sistema TODO." },
    ],
    selo: { nome: "Mestre Planetário", subtitulo: "Insígnia Máxima do Explorador", emoji: "🌐", cor: "from-indigo-500 to-purple-700" },
    falaFinal: "Insígnia máxima conquistada! Você venceu o 6º ano. Rumo ao 7º!",
  },

  recompensa: { xp: 500, moedas: 400, medalha: "Mestre Planetário" },
};
