import type { AulaGeoV1 } from "../types";
import { url as diversidade } from "@/assets/ensino-religioso-5ano/01-diversidade.jpg.asset.json";
import { url as indigena } from "@/assets/ensino-religioso-5ano/05-indigena.jpg.asset.json";
import { url as afro } from "@/assets/ensino-religioso-5ano/06-afro-brasileira.jpg.asset.json";

type Tema={slug:string;titulo:string;icone:string;codigo:string;objetivo:string;pergunta:string;correta:string;erradas:[string,string,string];conceitos:Array<[string,string,string]>;leituras:Array<[string,string]>;sequencia:string[];ensinamentos:string[];medalha:string};
const cores=["from-amber-500 to-orange-700","from-emerald-500 to-green-700","from-sky-500 to-blue-700","from-purple-500 to-fuchsia-700"];
const imagens=[diversidade,indigena,afro,diversidade];

function criar(t:Tema):AulaGeoV1{return{
 slug:t.slug,titulo:t.titulo,iconeTrilha:t.icone,bncc:[t.codigo],duracaoMin:24,
 cena01_motivacao:{tipo:"mesaCartografo",instrucao:"Observe as histórias, pessoas e memórias.",mapaUrl:diversidade,imagemDestaqueUrl:diversidade,aurora:t.objetivo,falaFinal:"Vamos investigar sem comparar qual tradição seria melhor ou verdadeira."},
 cena02_previsao:{tipo:"votoExplorador",aurora:"Registre seu palpite antes da investigação.",pergunta:t.pergunta,opcoes:[{id:"c",titulo:t.correta,subtitulo:"Use as pistas da aula",emoji:"🔎",cor:cores[0]},{id:"e1",titulo:t.erradas[0],subtitulo:"Confira com atenção",emoji:"💭",cor:cores[1]},{id:"e2",titulo:t.erradas[1],subtitulo:"Confira com atenção",emoji:"📘",cor:cores[2]},{id:"e3",titulo:t.erradas[2],subtitulo:"Confira com atenção",emoji:"🧭",cor:cores[3]}],respostaCerta:"c",feedbackAcerto:`Isso: ${t.correta}.`,feedbackErro:`Retome a investigação: ${t.correta}.`,falaFinal:"O palpite será conferido com evidências."},
 cena03_vocabulario:{tipo:"cadernosCampo",aurora:"Abra os conceitos antes de aplicá-los.",instrucao:"Toque em cada caderno",cadernos:t.conceitos.map(([capa,conteudo,exemplo],i)=>({id:`c${i}`,capa,emoji:["📜","🧠","🗣️","🤝"][i%4],cor:cores[i%4],conteudo,exemplo,fotoUrl:imagens[i%4]})),falaFinal:"Agora use os conceitos para interpretar exemplos reais."},
 cena04_leituraGuiada:{tipo:"narrarMapa",aurora:"Leia cada exemplo e descubra o que ele comunica.",instrucao:"Toque nos quatro pontos",mapaUrl:diversidade,pontos:t.leituras.map(([titulo,texto],i)=>({id:`p${i}`,x:[25,72,28,74][i],y:[28,30,70,70][i],emoji:["📖","🪶","🌍","👵"][i],cor:cores[i],titulo,texto,fotoUrl:imagens[i]})),falaFinal:"Diversidade não é competição: cada narrativa deve ser estudada em seu contexto."},
 cena05_compreensao:{tipo:"quizRadar",aurora:"Confirme o que aprendeu.",instrucao:"Escolha uma resposta em cada questão",perguntas:[{id:"q1",pergunta:t.pergunta,fotoUrl:diversidade,cards:[{id:"c",emoji:"✅",titulo:t.correta,cor:cores[0]},{id:"e1",emoji:"❌",titulo:t.erradas[0],cor:cores[1]},{id:"e2",emoji:"❌",titulo:t.erradas[1],cor:cores[2]},{id:"e3",emoji:"❌",titulo:t.erradas[2],cor:cores[3]}],correta:"c",feedbackAcerto:`Correto: ${t.correta}.`,feedbackErro:`A resposta é: ${t.correta}.`}],falaFinal:"Você justificou a resposta pelo conteúdo, não por preferência pessoal."},
 cena06_personagensLugar:{tipo:"mapaBrasilInterativo",aurora:"A tradição oral está presente em todas as regiões brasileiras.",instrucao:"Explore estados de diferentes regiões",missao:{tipo:"selecionar",siglas:["AM","BA","GO","SP","RS"],pergunta:"Selecione um conjunto que represente as cinco regiões do Brasil."},falaFinal:"Norte, Nordeste, Centro-Oeste, Sudeste e Sul têm memórias e tradições diversas."},
 cena07_sequencia:{tipo:"linhaEstrada",aurora:"Organize o caminho do conhecimento.",instrucao:"Toque na ordem",pergunta:"Como uma tradição preserva e comunica conhecimentos?",paradas:t.sequencia.map((rotulo,i)=>({id:`s${i}`,emoji:["👂","🧠","🗣️","🤝","🌱"][i%5],rotulo:`${i+1}. ${rotulo}`,descricao:t.ensinamentos[i]??"Etapa da transmissão responsável."})),ordemCerta:t.sequencia.map((_,i)=>`s${i}`),feedbackAcerto:"Sequência correta: escutar, compreender, recontar com cuidado e aplicar com respeito.",feedbackErro:"Comece pela escuta e preserve o sentido antes de compartilhar.",falaFinal:"Conhecimento oral exige memória, responsabilidade e comunidade."},
 cena08_voceLe:{tipo:"voceLeSozinho",aurora:"Leia e encontre as ideias-chave.",tituloLivro:`Diário do 5º ano — ${t.titulo}`,subtitulo:t.codigo,paragrafos:t.ensinamentos.map((texto,i)=>({id:`l${i}`,texto,chaves:texto.split(" ").filter(x=>x.length>6).slice(0,2)})),falaFinal:"Use os trechos para responder; não adivinhe."},
 cena09_minijogo:{tipo:"construtorMarcos",aurora:"Relacione conceito e exemplo.",instrucao:"Escolha a peça coerente",duracaoSegundos:20,pecas:t.conceitos.map(([capa],i)=>({id:`m${i}`,emoji:["📜","🗣️","👵","🌱"][i%4],rotulo:capa})),rodadas:t.leituras.slice(0,4).map(([titulo,texto],i)=>({id:`r${i}`,municipioA:{nome:titulo,emoji:"📘",cor:cores[i]},municipioB:{nome:"O que o exemplo ensina?",emoji:"🔎",cor:cores[(i+1)%4]},contexto:texto,pecaCertaId:`m${i%t.conceitos.length}`,feedbackAcerto:"Relação coerente com a explicação.",feedbackErro:"Retome o conceito e procure as palavras-chave."})),falaFinal:"Conceitos aplicados em contexto."},
 cena10_revisao:{tipo:"pizzaMunicipio",aurora:"Revise os dois eixos centrais.",instrucao:"Toque nas duas partes",fatias:[{id:"conteudo",rotulo:"COMPREENDER",emoji:"🧠",percentual:50,cor:"#8b5cf6",descricao:t.objetivo,exemplos:t.leituras.slice(0,2).map(x=>x[0])},{id:"atitude",rotulo:"RESPEITAR",emoji:"🤝",percentual:50,cor:"#10b981",descricao:"Estudar diferentes tradições sem impor crença, ridicularizar ou hierarquizar.",exemplos:["Escuta","Contexto","Respeito"]}],falaFinal:"Conhecimento e respeito caminham juntos."},
 cena11_avaliacao:{tipo:"seloAtlas",aurora:"Avaliação final com quatro alternativas.",instrucao:"Responda com base na aula",perguntas:[{id:"a1",pergunta:t.pergunta,opcoes:[{id:"a",texto:t.erradas[0],correta:false},{id:"b",texto:t.correta,correta:true},{id:"c",texto:t.erradas[1],correta:false},{id:"d",texto:t.erradas[2],correta:false}],feedbackAcerto:`Isso: ${t.correta}.`,feedbackErro:`Revise: ${t.correta}.`},{id:"a2",pergunta:"Qual atitude combina com o Ensino Religioso não confessional?",opcoes:[{id:"a",texto:"Comparar para decidir qual crença vence",correta:false},{id:"b",texto:"Estudar contextos e respeitar diferenças",correta:true},{id:"c",texto:"Obrigar participação religiosa",correta:false},{id:"d",texto:"Zombar de tradições desconhecidas",correta:false}],feedbackAcerto:"Isso: estudar e respeitar sem impor crenças.",feedbackErro:"A abordagem correta estuda contextos e respeita diferenças."},{id:"a3",pergunta:"Como justificar uma resposta nesta aula?",opcoes:[{id:"a",texto:"Pela preferência pessoal",correta:false},{id:"b",texto:"Por evidências e conceitos estudados",correta:true},{id:"c",texto:"Pela resposta mais longa",correta:false},{id:"d",texto:"Por um palpite sem leitura",correta:false}],feedbackAcerto:"Correto: evidência e conceito.",feedbackErro:"Volte ao texto e use evidências."}],selo:{nome:t.medalha,subtitulo:`Habilidade ${t.codigo}`,emoji:t.icone,cor:"from-amber-300 to-orange-500"},falaFinal:`Habilidade ${t.codigo} concluída com respeito e compreensão.`},
 recompensa:{xp:400,moedas:300,medalha:t.medalha}
};}

export const aulaEF05ER02=criar({slug:"aula-01-mitos-de-criacao",titulo:"Mitos de Criação: Muitas Origens",icone:"🌎",codigo:"EF05ER02",objetivo:"Identificar mitos de criação de diferentes culturas e tradições religiosas, reconhecendo personagens, acontecimentos e contextos sem tratá-los como explicações científicas.",pergunta:"O que é um mito de criação?",correta:"Narrativa cultural sobre a origem do mundo, da vida ou de um povo",erradas:["Uma mentira inventada para enganar","Um relatório científico obrigatório","Uma história igual em todas as culturas"],conceitos:[["Mito de criação","Narrativa simbólica que comunica como uma cultura compreende suas origens.","Não significa mentira; significa narrativa com valor cultural e religioso."],["Origem","Começo explicado pela narrativa: mundo, humanidade, natureza ou povo.","Cada mito destaca perguntas e relações importantes para sua comunidade."],["Contexto cultural","História, território, língua e valores do grupo que preserva o mito.","O mito deve ser estudado dentro de seu contexto."],["Respeito","Reconhecer o valor cultural das narrativas sem exigir crença.","Conhecer não significa converter-se ou praticar."]],leituras:[["Narrativa Guarani","Em uma das tradições Guarani, a criação relaciona palavra, canto, território e cuidado com a vida."],["Narrativa Iorubá","Em narrativas iorubás, divindades participam da organização da terra e das forças da natureza."],["Narrativa judaico-cristã","O Gênesis apresenta a criação organizada em etapas e destaca a relação entre Criador, humanidade e mundo."],["Narrativas de outros povos","Muitos povos contam origens ligadas a águas, animais, montanhas, ancestrais ou seres criadores."]],sequencia:["Ouvir a narrativa","Identificar origem e personagens","Relacionar ao contexto","Comparar sem hierarquizar"],ensinamentos:["MITOS DE CRIAÇÃO explicam simbolicamente as origens dentro de uma cultura.","As narrativas variam porque povos diferentes vivem histórias e territórios diferentes.","Mito religioso não é relatório científico e não deve ser chamado simplesmente de mentira.","Comparar significa observar semelhanças e diferenças com respeito."],medalha:"Investigador das Origens"});

export const aulaEF05ER03=criar({slug:"aula-01-funcoes-mitos-criacao",titulo:"Mensagens dos Mitos de Criação",icone:"🧠",codigo:"EF05ER03",objetivo:"Reconhecer funções e mensagens religiosas presentes nos mitos de criação sobre mundo, natureza, humanidade, divindades, vida e morte.",pergunta:"Além de contar uma origem, o que um mito de criação comunica?",correta:"Concepções de mundo, valores, relações e responsabilidades",erradas:["Somente datas comprovadas","Uma receita idêntica para todos","A obrigação de aceitar aquela crença"],conceitos:[["Função","Papel que a narrativa exerce na comunidade.","Preservar memória, orientar relações e comunicar valores."],["Mensagem","Ideia transmitida pelos acontecimentos e símbolos do mito.","Pode tratar de cuidado, responsabilidade, pertencimento ou equilíbrio."],["Concepção de mundo","Modo como um grupo compreende humanidade, natureza e sagrado.","Pergunte que relações a narrativa apresenta."],["Interpretação","Conclusão apoiada em trechos e símbolos da narrativa.","Não basta repetir o enredo; é preciso explicar a mensagem."]],leituras:[["Humanidade e natureza","Quando pessoas surgem ligadas à terra, a narrativa pode comunicar pertencimento e responsabilidade ambiental."],["Divindades e organização","A participação de seres sagrados pode explicar ordem, limites e deveres comunitários."],["Vida e continuidade","A presença de ancestrais pode ensinar memória, continuidade e compromisso entre gerações."],["Conflito e consequência","Uma escolha seguida de consequência pode funcionar como orientação sobre modos de viver."]],sequencia:["Ler o acontecimento","Identificar símbolos e relações","Inferir a mensagem","Justificar com evidência"],ensinamentos:["A FUNÇÃO de um mito inclui preservar memória e orientar a comunidade.","A MENSAGEM aparece nas relações entre personagens, natureza e sagrado.","Uma interpretação precisa apontar evidências da narrativa.","Mitos diferentes podem comunicar valores semelhantes por caminhos distintos."],medalha:"Leitor de Mensagens"});

export const aulaEF05ER06=criar({slug:"aula-01-sabios-e-anciaos",titulo:"Sábios e Anciãos: Guardiões da Memória",icone:"👵",codigo:"EF05ER06",objetivo:"Identificar o papel de sábios, anciãos e outras lideranças na comunicação e preservação das tradições orais.",pergunta:"Por que sábios e anciãos são importantes para tradições orais?",correta:"Porque preservam, ensinam e contextualizam memórias coletivas",erradas:["Porque inventam qualquer história nova","Porque substituem toda a comunidade","Porque impedem os jovens de aprender"],conceitos:[["Ancião","Pessoa mais velha reconhecida por experiência e memória comunitária.","Idade sozinha não basta: há reconhecimento e responsabilidade."],["Sábio","Pessoa que conhece narrativas, valores, práticas e contextos.","Pode ensinar por histórias, cantos, conselhos e exemplos."],["Guardião da memória","Quem cuida para que conhecimentos sejam transmitidos com sentido.","Não é dono da tradição; serve à continuidade comunitária."],["Aprendizagem entre gerações","Troca responsável entre pessoas mais velhas e mais novas.","Jovens escutam, perguntam, praticam e também ajudam a preservar."]],leituras:[["Povos indígenas","Anciãos e lideranças podem ensinar histórias do povo, relações com o território, cantos e modos de cuidado."],["Culturas afro-brasileiras","Pessoas mais velhas e lideranças preservam memórias, cantos, narrativas, valores e práticas comunitárias."],["Comunidades ciganas","A oralidade familiar transmite histórias, pertencimento, regras de convivência e memória dos deslocamentos."],["Outras tradições","Contadores, mestres, avós, recitadores e lideranças ensinam de formas variadas conforme cada comunidade."]],sequencia:["Escutar o guardião","Perguntar com respeito","Praticar e compreender","Recontar com responsabilidade","Ensinar à próxima geração"],ensinamentos:["SÁBIOS E ANCIÃOS ajudam a preservar a memória coletiva.","Eles explicam contexto e sentido, não apenas decoram palavras.","A transmissão oral envolve escuta, repetição, prática e responsabilidade.","Jovens também participam da continuidade quando aprendem e compartilham com cuidado."],medalha:"Guardião da Memória"});

export const aulaEF05ER07=criar({slug:"aula-01-ensinamentos-orais",titulo:"Palavras que Ensinam a Viver",icone:"🗣️",codigo:"EF05ER07",objetivo:"Reconhecer em textos orais ensinamentos relacionados a modos de ser e viver, identificando mensagem e aplicação sem impor prática religiosa.",pergunta:"Como reconhecer um ensinamento em uma narrativa oral?",correta:"Identificando a mensagem e sua relação com atitudes e escolhas",erradas:["Decorando sem compreender","Escolhendo a tradição mais conhecida","Transformando toda história em regra obrigatória"],conceitos:[["Texto oral","Mensagem transmitida principalmente pela fala, canto, recitação ou narrativa.","Pode ser preservada por memória, repetição e performance."],["Ensinamento","Orientação ou reflexão sobre modos de ser, conviver e agir.","Pode tratar de cuidado, honestidade, solidariedade ou responsabilidade."],["Mensagem","Ideia construída pelo conjunto da narrativa.","É identificada por acontecimentos, consequências, repetições e falas."],["Aplicação","Relação consciente entre a mensagem e uma situação de convivência.","Aplicar não significa realizar rito ou aderir a uma crença."]],leituras:[["Cuidado com o próximo","Narrativas em que a ajuda transforma uma situação podem comunicar solidariedade."],["Responsabilidade com a natureza","Histórias que mostram consequências do desperdício podem ensinar cuidado com o território."],["Honestidade e confiança","Uma narrativa sobre promessa cumprida pode comunicar responsabilidade pela palavra dada."],["Convivência e diferença","Relatos de cooperação entre grupos podem ensinar respeito, diálogo e vida comunitária."]],sequencia:["Escutar o texto oral","Reconstruir os acontecimentos","Inferir o ensinamento","Relacionar a uma atitude","Compartilhar com respeito"],ensinamentos:["TEXTOS ORAIS comunicam ensinamentos por histórias, cantos, provérbios e relatos.","O ensinamento é inferido pelos acontecimentos e suas consequências.","Modos de ser e viver incluem cuidado, honestidade, respeito e responsabilidade.","Estudar o ensinamento não obriga a criança a praticar uma religião."],medalha:"Leitor da Palavra Viva"});
