import type { AulaGeoV1 } from "../../types";
import feira from "@/assets/ciencias-5ano/u7-a1/feira-cientifica.jpg";
import poster from "@/assets/ciencias-5ano/u7-a1/poster.jpg";
import apresentacao from "@/assets/ciencias-5ano/u7-a1/apresentacao.jpg";
import experimento from "@/assets/ciencias-5ano/u7-a1/experimento.jpg";
import medalha from "@/assets/ciencias-5ano/u7-a1/medalha.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-feira-cientifica",
  titulo: "Feira Científica",
  iconeTrilha: "🏆",
  bncc: ["EF05CI11"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela feira. Encontre os elementos que fazem uma boa apresentação científica.",
    mapaUrl: feira,
    imagemDestaqueUrl: poster,
    aurora: "Chegou o momento mais importante do ano: apresentar suas descobertas. Numa feira, você não é só cientista — é COMUNICADOR de ciência.",
    falaFinal: "Ciência que ninguém entende não muda o mundo. Comunicar é parte do método.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "O que MAIS convence uma banca na feira científica?",
    pergunta: "Qual elemento pesa mais numa apresentação?",
    fotoUrl: apresentacao,
    opcoes: [
      { id: "dados", titulo: "DADOS", subtitulo: "medidos e registrados", emoji: "📊", cor: "from-teal-400 to-emerald-700" },
      { id: "roupa", titulo: "ROUPA", subtitulo: "aparência elegante", emoji: "👔", cor: "from-slate-400 to-slate-700" },
      { id: "voz", titulo: "VOZ ALTA", subtitulo: "gritar convence", emoji: "📣", cor: "from-red-400 to-rose-700" },
    ],
    respostaCerta: "dados",
    feedbackAcerto: "Sim. DADOS reais registrados são o coração de qualquer apresentação científica.",
    feedbackErro: "Roupa e voz não convencem cientista. O que pesa são os DADOS.",
    falaFinal: "Sem dados, é opinião. Com dados, é ciência.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco elementos que toda apresentação científica tem que ter.",
    instrucao: "Vocabulário da comunicação científica",
    cadernos: [
      { id: "problema", capa: "PROBLEMA", emoji: "❓", cor: "from-red-500 to-rose-700",
        conteudo: "A pergunta central que sua pesquisa quer responder. Clara, específica, respondível.",
        exemplo: "Ex.: 'A luz do sol afeta o crescimento das plantas?'.", fotoUrl: poster },
      { id: "metodo", capa: "MÉTODO", emoji: "🔬", cor: "from-teal-500 to-emerald-700",
        conteudo: "Como você investigou. Detalhe cada passo pra que outros possam repetir.",
        exemplo: "Ex.: '3 vasos com mesma terra, só a luz muda'.", fotoUrl: experimento },
      { id: "resultados", capa: "RESULTADOS", emoji: "📊", cor: "from-cyan-500 to-sky-700",
        conteudo: "Os dados que você coletou. Tabelas, gráficos, fotos. Sem interpretação ainda.",
        exemplo: "Ex.: 'Grupo sol = 28cm; grupo escuro = 4cm'.", fotoUrl: poster },
      { id: "conclusao", capa: "CONCLUSÃO", emoji: "✅", cor: "from-emerald-500 to-green-700",
        conteudo: "O que os dados PROVAM. Respondeu o problema? Confirmou a hipótese?",
        exemplo: "Ex.: 'Luz é fator determinante no crescimento'.", fotoUrl: apresentacao },
      { id: "poster", capa: "PÔSTER", emoji: "🖼️", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Painel visual com problema, método, resultados e conclusão. Direto e claro.",
        exemplo: "Ex.: 3 painéis com gráficos e fotos.", fotoUrl: poster },
    ],
    falaFinal: "Problema, método, resultados, conclusão, pôster. Estrutura padrão da ciência.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A feira em pleno funcionamento. Toca em cada elemento pra ver o papel.",
    instrucao: "Toque em cada elemento",
    mapaUrl: feira,
    pontos: [
      { id: "poster", x: 30, y: 40, emoji: "🖼️", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Pôster", texto: "Painel visual da pesquisa. Fica visível o tempo todo pra visitantes lerem.",
        fotoUrl: poster },
      { id: "aluno", x: 55, y: 55, emoji: "🧑‍🔬", cor: "from-teal-500 to-emerald-700",
        titulo: "Apresentador", texto: "Cientista jovem que explica o projeto e responde perguntas.",
        fotoUrl: apresentacao },
      { id: "experimento", x: 25, y: 75, emoji: "🧪", cor: "from-red-500 to-rose-700",
        titulo: "Experimento", texto: "Demonstração ao vivo ou modelo funcional do que foi estudado.",
        fotoUrl: experimento },
      { id: "banca", x: 75, y: 40, emoji: "👥", cor: "from-cyan-500 to-sky-700",
        titulo: "Banca", texto: "Avaliadores que fazem perguntas técnicas e julgam o rigor científico.",
        fotoUrl: feira },
      { id: "medalha", x: 80, y: 80, emoji: "🏅", cor: "from-amber-500 to-orange-700",
        titulo: "Reconhecimento", texto: "Melhores projetos recebem premiação — reconhecimento do trabalho.",
        fotoUrl: medalha },
    ],
    falaFinal: "Pôster + apresentador + experimento + banca. Fórmula clássica de feira científica.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas sobre comunicação científica.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Qual é a estrutura padrão de uma apresentação científica?",
        fotoUrl: poster,
        cards: [
          { id: "a", emoji: "🔢", titulo: "Problema → Método → Resultados → Conclusão", cor: "from-teal-500 to-emerald-700" },
          { id: "b", emoji: "🎲", titulo: "Qualquer ordem funciona", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🎬", titulo: "Só resultados", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Essa é a estrutura universal — do primeiro cientista à NASA.",
        feedbackErro: "Ordem importa: primeiro o problema, depois como investigou, depois o que achou." },
      { id: "q2", pergunta: "Um bom pôster científico deve ser:",
        fotoUrl: poster,
        cards: [
          { id: "a", emoji: "🖼️", titulo: "Visual, claro, com gráficos", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "📃", titulo: "Só texto sem imagem", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "🎨", titulo: "Cheio de desenhos aleatórios", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Pôster comunica visualmente — gráficos, fotos, títulos grandes.",
        feedbackErro: "Ciência entra pelos olhos. Pôster tem que ser VISUAL e claro." },
      { id: "q3", pergunta: "Se a banca faz uma pergunta que você não sabe, o que faz?",
        fotoUrl: apresentacao,
        cards: [
          { id: "a", emoji: "🙋", titulo: "Reconhece: 'não sei, vou investigar'", cor: "from-emerald-500 to-green-700" },
          { id: "b", emoji: "🎭", titulo: "Inventa uma resposta qualquer", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "😶", titulo: "Fica em silêncio", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Honestidade > invenção. Bom cientista reconhece limites do próprio conhecimento.",
        feedbackErro: "Nunca invente resposta. Reconhecer o que não sabe é ato científico." },
    ],
    falaFinal: "Comunicação clara e honesta é marca de cientista sério.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "A feira divide-se em duas zonas: EXPOSIÇÃO (pôster e experimento) e INTERAÇÃO (apresentador + público). Liga cada uma.",
    instrucao: "Toque nos interruptores",
    mapaUrl: feira,
    camadas: [
      { id: "exposicao", rotulo: "Exposição", emoji: "🖼️", cor: "from-fuchsia-500 to-purple-700",
        rect: { x: 2, y: 25, w: 45, h: 65 },
        descricao: "Pôster, modelo, experimento. Elementos visuais que ficam expostos o tempo todo.",
        fotoUrl: poster },
      { id: "interacao", rotulo: "Interação", emoji: "🗣️", cor: "from-emerald-500 to-green-700",
        rect: { x: 50, y: 25, w: 48, h: 65 },
        descricao: "Apresentador explica, público pergunta, banca avalia. A ciência acontece na conversa.",
        fotoUrl: apresentacao },
    ],
    falaFinal: "Exposição atrai. Interação convence. As duas juntas fazem a diferença.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a sequência pra preparar seu projeto pra Feira Científica.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual a ordem pra montar um projeto de feira?",
    paradas: [
      { id: "escolher", emoji: "❓", rotulo: "1. Escolher tema", descricao: "Uma pergunta que te interessa e pode ser investigada.", fotoUrl: poster },
      { id: "investigar", emoji: "🔬", rotulo: "2. Investigar", descricao: "Experimento controlado com dados coletados.", fotoUrl: experimento },
      { id: "analisar", emoji: "📊", rotulo: "3. Analisar", descricao: "Fazer gráficos, calcular médias, interpretar.", fotoUrl: poster },
      { id: "montar", emoji: "🖼️", rotulo: "4. Montar pôster", descricao: "Colocar tudo num painel visual claro.", fotoUrl: poster },
      { id: "apresentar", emoji: "🎤", rotulo: "5. Apresentar", descricao: "Comunicar pra banca e visitantes com clareza.", fotoUrl: apresentacao },
    ],
    ordemCerta: ["escolher", "investigar", "analisar", "montar", "apresentar"],
    feedbackAcerto: "Rota completa. É assim que projetos de ciência de verdade nascem.",
    feedbackErro: "Repense: você precisa INVESTIGAR antes de analisar, e ANALISAR antes de montar o pôster.",
    falaFinal: "Um projeto científico não nasce pronto. Vem em etapas — cada uma essencial.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Leitura autônoma. Guia final da orientadora.",
    tituloLivro: "📓 Guia Final da Orientadora Aurora",
    subtitulo: "Como se preparar para a Feira Científica",
    paragrafos: [
      { id: "p1", texto:
          "O primeiro passo é escolher um PROBLEMA claro. Uma pergunta específica que possa ser investigada com um experimento. 'A luz afeta o crescimento?' funciona; 'plantas são legais?' não funciona.",
        chaves: ["problema"], definicoes: { problema: "Pergunta central que a pesquisa quer responder." },
        fotoUrl: poster },
      { id: "p2", texto:
          "Depois vem o MÉTODO: como você vai investigar. Descreva cada passo, cada material, cada variável. Escreva tão detalhado que outra pessoa possa REPRODUZIR seu experimento. Isso é rigor científico.",
        chaves: ["método", "reproduzir"],
        definicoes: {
          método: "Descrição detalhada de como a pesquisa foi feita.",
          reproduzir: "Refazer o experimento pra conferir se dá o mesmo resultado.",
        }, fotoUrl: experimento },
      { id: "p3", texto:
          "Por fim, RESULTADOS (o que você achou) e CONCLUSÃO (o que isso significa). Apresente com pôster visual, seja claro na fala e honesto: se algo não deu certo, diga. Ciência valoriza HONESTIDADE mais que perfeição.",
        chaves: ["resultados", "conclusão", "honestidade"],
        definicoes: {
          resultados: "Dados coletados durante o experimento.",
          conclusão: "Interpretação dos resultados.",
          honestidade: "Registrar tudo, mesmo o que não deu certo.",
        }, fotoUrl: apresentacao },
    ],
    falaFinal: "Você tem todas as ferramentas. Agora é fazer.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra uma situação — identifica QUAL parte do projeto é.",
    instrucao: "⏱️ Leia e escolha a parte correta",
    duracaoSegundos: 20,
    pecas: [
      { id: "problema", emoji: "❓", rotulo: "Problema" },
      { id: "metodo", emoji: "🔬", rotulo: "Método" },
      { id: "resultados", emoji: "📊", rotulo: "Resultados" },
      { id: "conclusao", emoji: "✅", rotulo: "Conclusão" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "'A luz afeta o crescimento?'", emoji: "❓", cor: "from-red-500 to-rose-700" },
        municipioB: { nome: "Pergunta inicial", emoji: "🤔", cor: "from-orange-500 to-amber-700" },
        contexto: "A frase que abre o pôster e define o que a pesquisa quer descobrir.",
        pecaCertaId: "problema", fotoUrl: poster,
        feedbackAcerto: "Sim. Pergunta inicial = PROBLEMA.",
        feedbackErro: "Pergunta que a pesquisa quer responder = PROBLEMA." },
      { id: "r2", municipioA: { nome: "'3 vasos idênticos'", emoji: "🪴", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Descrição de como fez", emoji: "📝", cor: "from-teal-500 to-emerald-700" },
        contexto: "A parte que descreve os materiais, os passos e as variáveis do experimento.",
        pecaCertaId: "metodo", fotoUrl: experimento,
        feedbackAcerto: "Perfeito. Descrição detalhada = MÉTODO.",
        feedbackErro: "Passo a passo do experimento = MÉTODO." },
      { id: "r3", municipioA: { nome: "'Vaso sol = 28 cm'", emoji: "📊", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Números medidos", emoji: "📏", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Os números concretos que a equipe mediu ao longo dos 30 dias.",
        pecaCertaId: "resultados", fotoUrl: poster,
        feedbackAcerto: "Isso. Dados numéricos coletados = RESULTADOS.",
        feedbackErro: "Números medidos = RESULTADOS." },
      { id: "r4", municipioA: { nome: "'Luz é essencial'", emoji: "✅", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Interpretação dos dados", emoji: "💡", cor: "from-amber-500 to-orange-700" },
        contexto: "A frase final que responde o problema com base nos dados coletados.",
        pecaCertaId: "conclusao", fotoUrl: apresentacao,
        feedbackAcerto: "Sim. Resposta ao problema = CONCLUSÃO.",
        feedbackErro: "Interpretação final que responde o problema = CONCLUSÃO." },
      { id: "r5", municipioA: { nome: "Gráfico de barras", emoji: "📊", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Visualização dos dados", emoji: "📈", cor: "from-teal-500 to-emerald-700" },
        contexto: "Uma imagem que mostra visualmente as diferenças entre os grupos medidos.",
        pecaCertaId: "resultados", fotoUrl: poster,
        feedbackAcerto: "Perfeito. Gráficos são forma visual dos RESULTADOS.",
        feedbackErro: "Gráficos representam RESULTADOS de forma visual." },
    ],
    falaFinal: "Você identifica cada parte de um projeto científico. Pronto pra apresentar o seu.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "A feira em duas metades: PREPARAR (semanas de trabalho antes) e APRESENTAR (poucas horas na feira).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: feira,
    fatias: [
      { id: "preparar", rotulo: "Preparar", emoji: "🔬", percentual: 80, cor: "#ea580c",
        descricao: "Escolher tema, investigar, coletar dados, analisar, montar pôster. É onde mora 80% do esforço.",
        exemplos: ["Investigar", "Analisar", "Montar pôster"], fotoUrl: experimento },
      { id: "apresentar", rotulo: "Apresentar", emoji: "🎤", percentual: 20, cor: "#e11d48",
        descricao: "Explicar com clareza, responder banca, mostrar experimento. Curto mas decisivo.",
        exemplos: ["Falar", "Responder banca", "Demonstrar"], fotoUrl: apresentacao },
    ],
    falaFinal: "Preparação valente. Apresentação confiante. Fórmula da Feira Científica.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "Última avaliação do Fundamental 1! 3 perguntas — e a medalha de Cientista Brilha é sua.",
    instrucao: "Responda 3 perguntas para receber o selo final",
    fotoUrl: medalha,
    perguntas: [
      { id: "q1", pergunta: "Qual a estrutura padrão de uma pesquisa científica?",
        fotoUrl: poster,
        opcoes: [
          { id: "a", texto: "Problema → Método → Resultados → Conclusão", correta: true },
          { id: "b", texto: "Qualquer ordem funciona igual" },
        ],
        feedbackAcerto: "Sim. Estrutura universal — do jovem cientista à NASA.",
        feedbackErro: "Ordem existe. Primeiro pergunta, depois investigação, depois dados, depois interpretação." },
      { id: "q2", pergunta: "Se sua hipótese não se confirmou, o que fazer?",
        fotoUrl: apresentacao,
        opcoes: [
          { id: "a", texto: "Apresentar honestamente — isso também é ciência", correta: true },
          { id: "b", texto: "Mudar os dados pra bater com a hipótese" },
        ],
        feedbackAcerto: "Sim. Refutar hipótese é resultado válido. Ciência valoriza honestidade.",
        feedbackErro: "JAMAIS alterar dados — é fraude científica. Apresenta honestamente." },
      { id: "q3", pergunta: "Por que a comunicação científica é importante?",
        fotoUrl: poster,
        opcoes: [
          { id: "a", texto: "Pra que outros possam verificar e continuar sua pesquisa", correta: true },
          { id: "b", texto: "Só pra ganhar prêmio" },
        ],
        feedbackAcerto: "Sim. Ciência avança quando é compartilhada e verificada por outros.",
        feedbackErro: "Prêmio é consequência. Comunicar serve pra CIÊNCIA AVANÇAR." },
    ],
    selo: {
      nome: "Cientista Brilha",
      subtitulo: "Missão Planeta Vivo · Fundamental 1 concluído · Medalha de Ouro",
      emoji: "🏆",
      cor: "from-amber-400 via-yellow-500 to-orange-700",
    },
    falaFinal: "PARABÉNS! Você fechou todo o Fundamental 1 de Ciências. Da observação com lupa aos gráficos científicos, do ecossistema ao sistema solar. Está pronto pro Fundamental 2 — onde a ciência vai ficar ainda mais fascinante.",
  },

  recompensa: { xp: 300, moedas: 100, medalha: "Cientista Brilha (Ouro)" },
};
