import { CheckSquare, Circle, Scissors } from "lucide-react";
import { PrintableImage } from "./PrintableImage";
import type { PrintableActivity } from "./activity-types";

export function PrintableActivityRenderer({ activity }: { activity: PrintableActivity }) {
  if (activity.kind === "guide") return <div className="printable-guide-grid"><InfoBlock title="Objetivo observável" items={[activity.objective]} /><InfoBlock title="Materiais" items={activity.materials} /><InfoBlock title="Preparação" items={activity.preparation} /><InfoBlock title="Condução" items={activity.steps} numbered /><InfoBlock title="O que observar" items={activity.observe} /></div>;
  if (activity.kind === "model") return <div><p className="printable-instruction">{activity.instruction}</p><div className="model-strip"><h3>{activity.modelTitle}</h3>{activity.modelSteps.map((step, index) => <div className="model-step" key={step.label}><b>{index + 1}</b>{step.media && <PrintableImage image={step.media} />}<span><strong>{step.label}</strong><br />{step.text}</span>{index < activity.modelSteps.length - 1 && <span className="model-arrow">→</span>}</div>)}</div></div>;
  if (activity.kind === "association") return <div><p className="printable-instruction">{activity.instruction}</p><div className="association-grid">{activity.choices.map(choice => <div className="association-choice" key={choice.label}><PrintableImage image={choice.media} /><b>{choice.label}</b><div className="association-options">{choice.options.map(option => <span key={option}><Circle /> {option}</span>)}</div></div>)}</div><div className="writing-line">{activity.response}</div></div>;
  if (activity.kind === "cut-sort") return <div><p className="printable-instruction"><Scissors className="inline-icon" /> {activity.instruction}</p><div className="cut-cards">{activity.cards.map(card => <div className="cut-card" key={card.label}>{card.media && <PrintableImage image={card.media} />}<b>{card.label}</b></div>)}</div><div className="sort-board">{activity.columns.map(column => <div key={column}><h3>{column}</h3><div className="sort-space" /></div>)}</div></div>;
  if (activity.kind === "complete") return <div><p className="printable-instruction">{activity.instruction}</p><div className="complete-list">{activity.items.map(item => <div className="complete-row" key={item.label}>{item.media && <PrintableImage image={item.media} />}<span className="exercise-mode">{item.mode === "write" ? "Escreva" : item.mode === "circle" ? "Circule" : "Ordene"}</span><b>{item.label}</b><span className={`blank ${item.answerWidth}`} /></div>)}</div><div className="writing-line">{activity.response}</div></div>;
  if (activity.kind === "levels") return <div><p className="printable-instruction">{activity.instruction}</p><div className="levels-grid">{activity.levels.map((level, index) => <div className="level-card" key={level.name}><span className="level-number">{index + 1}</span>{level.media && <PrintableImage image={level.media} /> }<h3>{level.name}</h3><p><b>Faça:</b> {level.task}</p><p><b>Apoio:</b> {level.support}</p><div className="level-response" /></div>)}</div></div>;
  if (activity.kind === "record") return <div><p className="printable-instruction">Registre a data e marque uma opção após a aplicação.</p><table className="record-table"><thead><tr><th>Data</th><th>Habilidade observada</th><th>Sozinho</th><th>Com apoio</th><th>Ainda não</th><th>Observações e próximo passo</th></tr></thead><tbody>{activity.rows.map(row => <tr key={row}><td /><td>{row}</td><td><CheckSquare /></td><td><CheckSquare /></td><td><CheckSquare /></td><td /></tr>)}</tbody></table></div>;
  return <div className="answer-panel"><h3>Respostas esperadas</h3><ol>{activity.answerKey.map(answer => <li key={answer}>{answer}</li>)}</ol><div className="answer-columns"><div><b>Erro provável</b><p>{activity.likelyError}</p></div><div><b>Intervenção curta</b><p>{activity.intervention}</p></div><div><b>Decisão</b><p>{activity.decision}</p></div></div>{activity.relatedActivity && <p className="related-answer"><b>Atividade relacionada no app:</b> {activity.relatedActivity}</p>}</div>;
}

function InfoBlock({ title, items, numbered = false }: { title: string; items: string[]; numbered?: boolean }) { return <div className="info-block"><h3>{title}</h3>{items.map((item, index) => <p key={item}>{numbered && <b>{index + 1}. </b>}{item}</p>)}</div>; }