import type { AulaGeoV1 } from "../../types";
import { url as imgConst } from "@/assets/historia-8ano/u6-constituicao-1824.jpg.asset.json";
import { url as imgFico } from "@/assets/historia-8ano/u6-dia-fico.jpg.asset.json";
import { url as imgPedro } from "@/assets/historia-8ano/u6-dom-pedro.jpg.asset.json";
import { url as imgFazenda } from "@/assets/historia-8ano/u6-fazenda-cafe.jpg.asset.json";
import { url as imgIpiranga } from "@/assets/historia-8ano/u6-ipiranga.jpg.asset.json";

export const aula04: AulaGeoV1 = {
  slug: "aula-04-fronteiras-conflitos",
  titulo: "Fronteiras em Disputa no Império",
  iconeTrilha: "🗺️",
  bncc: ["EF08HI17"],
  duracaoMin: 30,
  estilo: "teen",
  cena01_motivacao: { tipo: "mesaCartografo", instrucao: "Toque na imagem para começar.", mapaUrl: imgFazenda, imagemDestaqueUrl: imgConst, aurora: "O território do Império do Brasil não nasceu pronto. Ao sul, disputava-se a região do Prata com Argentina e Uruguai; a Guerra Cisplatina (1825-1828) terminou com a independência do Uruguai, que passou a servir de 'estado-tampão' entre Brasil e Argentina. Nas fronteiras internas, o Império avançava sobre terras indígenas no Sul, no Centro-Oeste e na Amazônia.", falaFinal: "Nesta aula você desbloqueia a Engrenagem: Fronteiras do Império." },
  cena02_previsao: { tipo: "votoExplorador", aurora: "Se o Brasil disputava território com vizinhos e ainda avançava sobre terras indígenas, o que isso revela sobre a formação das fronteiras nacionais?", pergunta: "Como se formaram as fronteiras do Império brasileiro?", fotoUrl: imgFazenda, opcoes: [ { id: "conf", titulo: "GUERRAS E NEGOCIAÇÕES", subtitulo: "disputas com vizinhos e povos indígenas", emoji: "⚔️", cor: "from-red-800 to-slate-950" }, { id: "pac", titulo: "ACORDO PACÍFICO ÚNICO", subtitulo: "sem nenhum conflito territorial", emoji: "❌", cor: "from-amber-900 to-slate-950" } ], respostaCerta: "conf", feedbackAcerto: "Correto. As fronteiras do Império resultaram de guerras (como a Cisplatina), tratados diplomáticos e do avanço militar sobre territórios indígenas — um processo violento, não pacífico.", feedbackErro: "Não. As fronteiras nasceram de GUERRAS, tratados diplomáticos tensos e do avanço sobre terras indígenas — um processo de conflito.", falaFinal: "Ideia-base: fronteira nacional = resultado de guerra, diplomacia e conquista." },
  cena03_vocabulario: { tipo: "cadernosCampo", aurora: "Quatro conceitos-chave sobre as fronteiras do Império.", instrucao: "", cadernos: [
    { id: "cis", capa: "Guerra Cisplatina", emoji: "⚔️", cor: "from-teal-700 to-slate-900", fotoUrl: imgFazenda, conteudo: "GUERRA CISPLATINA (1825-1828) opôs Brasil e Argentina (Províncias Unidas do Rio da Prata) pelo controle da Banda Oriental (atual Uruguai). Terminou com mediação britânica, criando o Uruguai como país independente.", exemplo: "Exemplo: a Inglaterra mediou o acordo porque tinha interesse comercial em um Rio da Prata livre de conflitos, aberto ao seu comércio." },
    { id: "tamp", capa: "Estado-tampão", emoji: "🛡️", cor: "from-amber-700 to-slate-900", fotoUrl: imgConst, conteudo: "ESTADO-TAMPÃO é um país pequeno criado entre duas potências rivais para evitar que elas fiquem com fronteira direta e entrem em guerra. O Uruguai cumpriu esse papel entre Brasil e Argentina no século XIX.", exemplo: "Exemplo: até hoje o Uruguai mantém identidade própria construída nesse contexto de disputa regional." },
    { id: "aval", capa: "Avanço sobre terras indígenas", emoji: "🏹", cor: "from-cyan-700 to-slate-900", fotoUrl: imgPedro, conteudo: "O Império expandiu fronteiras internas avançando militarmente sobre terras indígenas no Sul (contra Kaingang e Guarani), no Centro-Oeste e na Amazônia, para abrir espaço a fazendas e colonização.", exemplo: "Exemplo: no Rio Grande do Sul, colonos e o exército imperial expulsaram povos Kaingang para ocupar terras com plantações e criação de gado." },
    { id: "trat", capa: "Tratados de limites", emoji: "📜", cor: "from-slate-700 to-slate-900", fotoUrl: imgIpiranga, conteudo: "TRATADOS DE LIMITES foram acordos diplomáticos que definiram fronteiras entre o Brasil e países vizinhos como Bolívia, Peru e Paraguai, muitas vezes só formalizados décadas depois de disputas armadas.", exemplo: "Exemplo: a fronteira com o Paraguai só ficou plenamente definida após a Guerra do Paraguai (1864-1870)." }
  ], falaFinal: "Guerra Cisplatina + Estado-tampão + avanço indígena + tratados. As fronteiras nasceram de tensão, não de consenso." },
  cena04_leituraGuiada: { tipo: "narrarMapa", aurora: "Infográfico das principais frentes de disputa territorial do Império. Toque nos pontos.", instrucao: "Toque nos pontos", mapaUrl: imgFazenda, pontos: [
    { id: "cis", x: 30, y: 80, emoji: "⚔️", cor: "from-teal-700 to-slate-900", fotoUrl: imgFazenda, titulo: "BANDA ORIENTAL / URUGUAI", texto: "Guerra Cisplatina (1825-1828) contra a Argentina; termina com a independência do Uruguai como estado-tampão." },
    { id: "sul", x: 25, y: 70, emoji: "🏹", cor: "from-cyan-700 to-slate-900", fotoUrl: imgPedro, titulo: "SUL — POVOS KAINGANG E GUARANI", texto: "Avanço militar imperial sobre terras indígenas para expandir fazendas e colonização europeia." },
    { id: "par", x: 45, y: 60, emoji: "📜", cor: "from-slate-700 to-slate-900", fotoUrl: imgIpiranga, titulo: "FRONTEIRA COM O PARAGUAI", texto: "Disputas de limites que ajudaram a detonar a Guerra do Paraguai (1864-1870)." }
  ], falaFinal: "Três frentes, um mesmo processo: o Império se expandia à custa de vizinhos e povos originários." },
  cena05_compreensao: { tipo: "quizRadar", aurora: "Três perguntas rápidas sobre as fronteiras do Império.", instrucao: "Toque no card correto", perguntas: [
    { id: "q1", pergunta: "A Guerra Cisplatina (1825-1828) resultou na independência de qual país?", fotoUrl: imgFazenda, cards: [ { id: "u", emoji: "🇺🇾", titulo: "Uruguai", cor: "from-teal-600 to-slate-900" }, { id: "p", emoji: "🇵🇾", titulo: "Paraguai", cor: "from-amber-600 to-slate-900" }, { id: "b", emoji: "🇧🇴", titulo: "Bolívia", cor: "from-slate-600 to-slate-900" } ], correta: "u", feedbackAcerto: "Correto. O Uruguai nasceu como estado-tampão entre Brasil e Argentina.", feedbackErro: "É o Uruguai, criado como estado-tampão entre Brasil e Argentina." },
    { id: "q2", pergunta: "O que é um 'estado-tampão'?", fotoUrl: imgConst, cards: [ { id: "e", emoji: "🛡️", titulo: "País pequeno entre potências rivais", cor: "from-teal-600 to-slate-900" }, { id: "f", emoji: "🏰", titulo: "Fortaleza militar na fronteira", cor: "from-amber-600 to-slate-900" }, { id: "c", emoji: "🚢", titulo: "Colônia comercial britânica", cor: "from-slate-600 to-slate-900" } ], correta: "e", feedbackAcerto: "Correto. Um estado-tampão evita a fronteira direta entre dois rivais.", feedbackErro: "É um país pequeno criado entre duas potências rivais, para evitar guerra direta entre elas." },
    { id: "q3", pergunta: "Como o Império expandiu suas fronteiras internas no Sul do país?", fotoUrl: imgPedro, cards: [ { id: "m", emoji: "🏹", titulo: "Avanço militar sobre terras indígenas", cor: "from-teal-600 to-slate-900" }, { id: "n", emoji: "🤝", titulo: "Negociação pacífica com indígenas", cor: "from-amber-600 to-slate-900" }, { id: "d", emoji: "💰", titulo: "Compra das terras em leilão", cor: "from-slate-600 to-slate-900" } ], correta: "m", feedbackAcerto: "Correto. O avanço foi militar, expulsando povos como os Kaingang.", feedbackErro: "Foi por avanço militar, expulsando povos indígenas de suas terras." }
  ], falaFinal: "Radar afiado. Você já entende como as fronteiras do Império foram construídas." },
  cena06_personagensLugar: { tipo: "mapaCamadas", aurora: "Dois filtros sobre a expansão territorial do Império.", instrucao: "Toque nos filtros", mapaUrl: imgFazenda, camadas: [
    { id: "ext", rotulo: "Fronteiras externas", emoji: "⚔️", cor: "from-red-700 to-slate-900", rect: { x: 10, y: 10, w: 80, h: 40 }, descricao: "Guerras e tratados com Argentina, Uruguai, Paraguai e Bolívia definiram os limites externos do Império ao longo do século XIX." },
    { id: "int", rotulo: "Fronteiras internas", emoji: "🏹", cor: "from-cyan-700 to-slate-900", rect: { x: 5, y: 55, w: 90, h: 40 }, descricao: "Avanço militar sobre terras indígenas no Sul, Centro-Oeste e Amazônia ampliou o território efetivamente controlado pelo Estado imperial." }
  ], falaFinal: "Fronteira externa por guerra e diplomacia; fronteira interna por conquista sobre povos indígenas." },
  cena07_sequencia: { tipo: "linhaEstrada", aurora: "Ordene os marcos da formação territorial do Império.", instrucao: "Toque nas etapas na ordem certa", pergunta: "Marcos das fronteiras imperiais", paradas: [
    { id: "cis", emoji: "⚔️", rotulo: "1. Guerra Cisplatina (1825)", fotoUrl: imgFazenda, descricao: "Brasil x Argentina pela Banda Oriental." },
    { id: "uru", emoji: "🇺🇾", rotulo: "2. Independência do Uruguai (1828)", fotoUrl: imgConst, descricao: "Mediação britânica cria o estado-tampão." },
    { id: "sul", emoji: "🏹", rotulo: "3. Avanço sobre terras Kaingang (déc. 1840-1850)", fotoUrl: imgPedro, descricao: "Expulsão de indígenas para colonização do Sul." },
    { id: "gp", emoji: "📜", rotulo: "4. Tensões com o Paraguai (déc. 1860)", fotoUrl: imgIpiranga, descricao: "Disputas de fronteira ajudam a detonar a Guerra do Paraguai." }
  ], ordemCerta: ["cis", "uru", "sul", "gp"], feedbackAcerto: "Perfeito. Guerra Cisplatina → independência do Uruguai → avanço sobre indígenas → tensões com o Paraguai.", feedbackErro: "Essa não é a próxima etapa. Siga a ordem cronológica a partir de 1825.", falaFinal: "Quatro marcos, décadas de conflito territorial." },
  cena08_voceLe: { tipo: "voceLeSozinho", aurora: "Sua vez. Página do livro-atlas. Toque nos termos técnicos.", tituloLivro: "⚙️ As Engrenagens do Império", subtitulo: "Página — Fronteiras em Disputa", paragrafos: [
    { id: "p1", texto: "O território do Império não estava definido em 1822. Ao sul, a disputa pela Banda Oriental (atual Uruguai) com a Argentina gerou a GUERRA CISPLATINA (1825-1828), encerrada com mediação britânica.", chaves: ["Guerra Cisplatina"], definicoes: { "Guerra Cisplatina": "Conflito entre Brasil e Argentina (1825-1828) pelo controle da Banda Oriental, encerrado com a independência do Uruguai." }, fotoUrl: imgFazenda },
    { id: "p2", texto: "O resultado foi a criação do Uruguai como ESTADO-TAMPÃO — um país pequeno posicionado entre dois rivais, para evitar que Brasil e Argentina tivessem fronteira direta e entrassem em guerra novamente.", chaves: ["Estado-tampão"], definicoes: { "Estado-tampão": "País pequeno criado entre duas potências rivais para evitar conflito direto entre elas." }, fotoUrl: imgConst },
    { id: "p3", texto: "Internamente, o Império expandiu fronteiras avançando sobre terras indígenas. No Sul, povos como os Kaingang e Guarani foram expulsos de seus territórios para dar lugar a fazendas e à colonização europeia incentivada pelo governo.", chaves: ["Avanço sobre terras indígenas"], definicoes: { "Avanço sobre terras indígenas": "Expansão militar do Estado imperial sobre territórios ocupados por povos originários." }, fotoUrl: imgPedro },
    { id: "p4", texto: "Na fronteira com o Paraguai, disputas de limites territoriais e rivalidades diplomáticas se acumularam ao longo das décadas de 1850 e 1860, e ajudaram a criar o cenário que levaria à Guerra do Paraguai (1864-1870).", chaves: ["Tratados de limites"], definicoes: { "Tratados de limites": "Acordos diplomáticos que definiam as fronteiras entre países vizinhos, muitas vezes após anos de tensão." }, fotoUrl: imgIpiranga }
  ], falaFinal: "Leitura concluída. Você já entende que as fronteiras do Brasil nasceram de conflito, não de consenso." },
  cena09_minijogo: { tipo: "construtorMarcos", aurora: "Missão de historiador. Associe cada fronteira ao seu contexto.", instrucao: "⏱️ Toque na peça correta", duracaoSegundos: 22, pecas: [ { id: "cis", emoji: "⚔️", rotulo: "Cisplatina" }, { id: "sul", emoji: "🏹", rotulo: "Avanço no Sul" }, { id: "par", emoji: "📜", rotulo: "Paraguai" } ], rodadas: [
    { id: "r1", municipioA: { nome: "Banda Oriental", emoji: "🇺🇾", cor: "from-teal-700 to-slate-900" }, municipioB: { nome: "Independência do Uruguai", emoji: "🕊️", cor: "from-teal-600 to-slate-900" }, contexto: "Guerra entre Brasil e Argentina.", pecaCertaId: "cis", feedbackAcerto: "Correto. Guerra Cisplatina.", feedbackErro: "É a Guerra Cisplatina." },
    { id: "r2", municipioA: { nome: "Povos Kaingang expulsos", emoji: "🏹", cor: "from-cyan-700 to-slate-900" }, municipioB: { nome: "Colonização europeia no Sul", emoji: "🏡", cor: "from-cyan-600 to-slate-900" }, contexto: "Expansão interna de fronteiras.", pecaCertaId: "sul", feedbackAcerto: "Correto. Avanço sobre terras indígenas no Sul.", feedbackErro: "É o avanço sobre terras indígenas no Sul." },
    { id: "r3", municipioA: { nome: "Disputas de limites", emoji: "📜", cor: "from-slate-700 to-slate-900" }, municipioB: { nome: "Antecedente da Guerra do Paraguai", emoji: "⚔️", cor: "from-slate-600 to-slate-900" }, contexto: "Tensão fronteiriça na década de 1860.", pecaCertaId: "par", feedbackAcerto: "Correto. Fronteira com o Paraguai.", feedbackErro: "É a fronteira com o Paraguai." },
    { id: "r4", municipioA: { nome: "Mediação britânica", emoji: "🇬🇧", cor: "from-teal-700 to-slate-900" }, municipioB: { nome: "Fim da Guerra Cisplatina", emoji: "🕊️", cor: "from-teal-600 to-slate-900" }, contexto: "Interesse comercial inglês no Prata.", pecaCertaId: "cis", feedbackAcerto: "Correto. Cisplatina.", feedbackErro: "É a Cisplatina." },
    { id: "r5", municipioA: { nome: "Expulsão de Guarani", emoji: "🏹", cor: "from-cyan-700 to-slate-900" }, municipioB: { nome: "Expansão de fazendas", emoji: "🌾", cor: "from-cyan-600 to-slate-900" }, contexto: "Conquista de terras no Sul.", pecaCertaId: "sul", feedbackAcerto: "Correto. Avanço no Sul.", feedbackErro: "É o avanço no Sul." },
    { id: "r6", municipioA: { nome: "Limite definido só após guerra", emoji: "🗺️", cor: "from-slate-700 to-slate-900" }, municipioB: { nome: "Consequência de 1870", emoji: "📅", cor: "from-slate-600 to-slate-900" }, contexto: "Fronteira só fixada após conflito armado.", pecaCertaId: "par", feedbackAcerto: "Correto. Paraguai.", feedbackErro: "É o Paraguai." }
  ], falaFinal: "6 rodadas! Você já associa cada fronteira ao seu conflito." },
  cena10_revisao: { tipo: "pizzaMunicipio", aurora: "Pizza das duas grandes frentes de expansão territorial do Império.", instrucao: "Toque em cada fatia", fotoUrl: imgFazenda, fatias: [
    { id: "ext", rotulo: "Fronteiras externas (guerra/diplomacia)", emoji: "⚔️", percentual: 50, cor: "#b91c1c", descricao: "Guerra Cisplatina, tratados com Paraguai, Bolívia e Peru — limites definidos por conflito e negociação com países vizinhos.", exemplos: ["⚔️ Guerra Cisplatina", "📜 Tratados de limites"] },
    { id: "int", rotulo: "Fronteiras internas (avanço territorial)", emoji: "🏹", percentual: 50, cor: "#0e7490", descricao: "Expansão sobre terras indígenas no Sul, Centro-Oeste e Amazônia para colonização e agropecuária.", exemplos: ["🏹 Terras indígenas", "🌾 Colonização"] }
  ], falaFinal: "Duas frentes, um mesmo processo de expansão territorial do Império." },
  cena11_avaliacao: { tipo: "seloAtlas", aurora: "Três perguntas finais pra desbloquear a Engrenagem das Fronteiras.", instrucao: "Responda as 3 perguntas", fotoUrl: imgConst, perguntas: [
    { id: "av1", pergunta: "A Guerra Cisplatina (1825-1828) opôs o Brasil a:", opcoes: [ { id: "a", texto: "Argentina, pelo controle da Banda Oriental.", correta: true }, { id: "b", texto: "Inglaterra, pelo controle do comércio de escravizados.", correta: false }, { id: "c", texto: "Portugal, pela restauração da colônia.", correta: false } ], feedbackAcerto: "Correto. A disputa era pela Banda Oriental, atual Uruguai.", feedbackErro: "Foi contra a Argentina, pela Banda Oriental." },
    { id: "av2", pergunta: "O Uruguai nasceu, em 1828, como um exemplo de:", opcoes: [ { id: "a", texto: "Colônia britânica.", correta: false }, { id: "b", texto: "Estado-tampão entre Brasil e Argentina.", correta: true }, { id: "c", texto: "Território anexado ao Brasil.", correta: false } ], feedbackAcerto: "Correto. Um estado-tampão para evitar fronteira direta entre os rivais.", feedbackErro: "É um estado-tampão entre Brasil e Argentina." },
    { id: "av3", pergunta: "Como o Império expandiu suas fronteiras internas no Sul do país?", opcoes: [ { id: "a", texto: "Comprando terras dos povos indígenas.", correta: false }, { id: "b", texto: "Por meio de avanço militar sobre terras indígenas.", correta: true }, { id: "c", texto: "Por doação da Coroa portuguesa.", correta: false } ], feedbackAcerto: "Correto. Foi um avanço militar sobre povos como os Kaingang.", feedbackErro: "Foi por avanço militar sobre terras indígenas." }
  ], selo: { nome: "Fronteiras do Império", subtitulo: "Engrenagem das Disputas Territoriais", emoji: "🗺️", cor: "from-red-600 to-slate-900", fotoUrl: imgIpiranga }, falaFinal: "Engrenagem destravada. As fronteiras do Brasil nasceram de guerra, diplomacia e conquista." },
  recompensa: { xp: 500, moedas: 400, medalha: "Fronteiras do Império" },
};
