import type { LessonData } from "../ingles-1ano/types";
import { IMG } from "./_assets";

type Plan={slug:string;title:string;codes:string[];goal:string;text:string[];vocab:Array<[string,string]>;lesson:string;examples:Array<[string,string]>;project:string};
const wrong=["Ignore the evidence","Repeat without checking","Attack the other speaker"];

function make(p:Plan):LessonData{
 return{
  slug:p.slug,bnccCodes:p.codes,
  meta:{unitLabel:`BNCC Workshop — ${p.title}`,headerKicker:`English Academy · 9th Grade · ${p.codes.join(" · ")}`,coverKicker:"Argumentation · Critical literacy · Global citizenship",coverTitle:p.title,coverSubtitle:p.goal,storyTitle:`Mission: ${p.title}`,vocabularyTitle:"Evidence and communication",speakingTargets:p.examples.map(([en])=>en),listeningIntro:"Ouça, tome notas das ideias-chave e separe afirmações, argumentos, contra-argumentos e evidências.",listeningQuestion:`Qual ação cumpre a missão “${p.title}”?`,listeningOptions:[p.goal,...wrong],listeningCorrect:p.goal,listeningWrongHint:"Retome as notas e confirme o posicionamento e as evidências.",readingNarration:`Analise autoria, finalidade, recursos persuasivos, fatos, opiniões, argumentos e validade das fontes. ${p.goal}`,grammarNarration:p.lesson,finalProjectIntro:`Pesquise, planeje, produza e revise “${p.project}”. Digite seu nome:`,finalProjectPhrase:(name)=>`${p.project.toUpperCase()} — By ${name}. ${p.text.join(" ")}`,finalProjectSectionTitle:p.project},
  VOCAB:p.vocab.map(([en,pt],i)=>({id:`v${i}`,en,pt,img:[IMG.CLASS,IMG.LIBRARY,IMG.SCHOOL,IMG.FRIENDS][i%4]})),
  STORY:p.text.map((en,i)=>({img:[IMG.CLASS,IMG.LIBRARY,IMG.SCHOOL,IMG.FRIENDS][i%4],en,pt:`Parte ${i+1}: identifique a função desta informação na argumentação.`})),
  DIALOG:[{who:"Ms. Anna",img:IMG.ANNA,en:"What is your claim and which evidence supports it?",pt:"Qual é sua tese e qual evidência a sustenta?"},{who:"Maya",img:IMG.MAYA,en:p.examples[0][0],pt:p.examples[0][1]},{who:"Kenji",img:IMG.KENJI,en:"I see your point; however, this source presents a counterargument.",pt:"Entendo seu ponto; porém, esta fonte apresenta um contra-argumento."},{who:"Lucas",img:IMG.LUCAS,en:p.examples[1][0],pt:p.examples[1][1]}],
  READING:{title:p.title,img:IMG.LIBRARY,parts:p.text.map((en,i)=>({en,pt:`Trecho ${i+1}: marque tese, evidência, fato, opinião ou contexto.`,highlight:en.split(" ").slice(0,3)}))},
  WRITING:[{prompt:"Um argumento sólido começa com:",answer:"A clear claim and reliable evidence",hint:"Tese clara e evidência confiável.",options:["A clear claim and reliable evidence",...wrong]},{prompt:"Para organizar oposição, use:",answer:"However",hint:"Conector de contraste.",options:["However","Moreover","Therefore","In summary"]},{prompt:"Antes de compartilhar uma fonte:",answer:"Check author, date, evidence and purpose",hint:"Valide a informação.",options:["Check author, date, evidence and purpose","Count the images","Trust every post","Read only the title"]},{prompt:"Escolha a formulação fundamentada:",answer:p.examples[0][0],hint:p.examples[0][1],options:[p.examples[0][0],...wrong]}],
  QUIZ:[{q:"Qual é o objetivo desta oficina?",options:[{text:p.goal,correct:true},...wrong.map(text=>({text}))]},{q:"Fato é:",options:[{text:"Informação verificável por evidências",correct:true},{text:"Qualquer preferência"},{text:"Uma propaganda"},{text:"Uma frase longa"}]},{q:"Um contra-argumento:",options:[{text:"Responde a uma posição com razões",correct:true},{text:"Insulta o autor"},{text:"Muda de assunto"},{text:"Repete a tese"}]},{q:"Uma fonte confiável precisa ser:",options:[{text:"Identificável, atual e sustentada",correct:true},{text:"Anônima e viral"},{text:"Colorida"},{text:"Sempre curta"}]}],
  REAL_LIFE:p.examples.map(([answer,situation])=>({situation,answer})),
  GRAMMAR:{focus:p.title,why:p.lesson,examples:p.examples.map(([en,pt])=>({en,pt})),errors:[{wrong:"If we will act, things improve.",right:"If we act, things will improve.",why:"Na first conditional, if + presente; resultado com will."},{wrong:"People must to agree.",right:"People must agree.",why:"Depois de modal, use o verbo sem to."}]},
  HUNTER:{intro:"Encontre a escolha mais bem fundamentada.",rounds:[{promptEn:p.goal,promptPt:p.goal,targetLabel:p.examples[0][0],objects:[{id:"a",label:p.examples[0][0],img:"",isTarget:true},{id:"b",label:wrong[0],img:""},{id:"c",label:wrong[1],img:""},{id:"d",label:wrong[2],img:""}]}]},
  MEMORY:{intro:"Relacione os conceitos.",pairs:p.vocab.slice(0,4).map(([en,pt],i)=>({id:`p${i}`,en,pt,img:IMG.CLASS}))},
  BOOK:{title:p.project,intro:"Registre pesquisa, argumentos, revisão e versão final.",pages:p.text.map((en,i)=>({en,pt:`Seção ${i+1}`,img:[IMG.CLASS,IMG.LIBRARY][i%2],badge:"📙"}))},
  CULTURE:{title:"English, power and identities",emoji:"🌍",paragraphs:[{en:p.text[0],pt:"Analise história, circulação, poder e vozes representadas."},{pt:"O inglês pode ampliar intercâmbios, mas sua expansão também precisa ser debatida historicamente e sem apagar outras línguas."}]}
 };
}

export const BNCC_WORKSHOPS_9ANO:LessonData[]=[
 make({slug:"u9-a08-argument-lab",title:"Argument & Research Lab 🎙️📊",codes:["EF09LI01","EF09LI02","EF09LI03","EF09LI04"],goal:"Expor pontos de vista, argumentos e contra-argumentos, tomar notas de textos orais, analisar posicionamentos e apresentar resultados com dados e recursos visuais adequados.",text:["A student council researches safer routes to school.","One speaker argues for more bike lanes; another defends better bus connections.","Students take notes in columns: claim, reason, evidence and counterargument.","The final presentation uses a labeled graph, cites the survey sample and adapts language to the school audience."],vocab:[["claim","tese"],["argument","argumento"],["counterargument","contra-argumento"],["key idea","ideia-chave"],["notes","anotações"],["survey","pesquisa"],["graph","gráfico"],["sample","amostra"]],lesson:"Argumentação eficaz considera contexto, público e propósito. Anote palavras-chave, não frases inteiras; agrupe tese, razões, evidências e refutações. Ao expor pesquisa, explique fonte, método e limites dos dados e integre notas, gráficos ou tabelas à fala.",examples:[["The survey suggests more bike lanes because 62% of students support them.","Tese acompanhada de dado e justificativa."],["However, the sample included only one class, so we need more data.","Contra-argumento reconhece limite da pesquisa."],["According to the graph, bus use increased in May.","A fala interpreta o recurso visual."]],project:"Evidence-Based Oral Presentation"}),
 make({slug:"u9-a09-critical-media-campaign",title:"Critical Media & Campaign Studio 📰📣",codes:["EF09LI05","EF09LI06","EF09LI07","EF09LI08","EF09LI09","EF09LI10","EF09LI11","EF09LI12"],goal:"Analisar persuasão, separar fatos e opiniões, verificar argumentos, evidências e fontes, respeitar pontos de vista e criar textos multimodais críticos e persuasivos sobre tema coletivo.",text:["Two online posts make opposite claims about reducing plastic at school.","Students identify loaded words, color, image framing and font size as persuasive choices.","They classify verifiable data as fact and personal evaluations as opinion, then trace each claim to its source.","Groups plan an ethical campaign, select evidence, create an infographic and review whether words and images inform without manipulating."],vocab:[["persuasion","persuasão"],["fact","fato"],["opinion","opinião"],["headline","manchete"],["source","fonte"],["validity","validade"],["infographic","infográfico"],["campaign","campanha"]],lesson:"Persuasão combina escolhas verbais e visuais: palavras avaliativas, slogan, cores, enquadramento e tamanho. Diferencie fato verificável de opinião; identifique tese, argumentos e evidências. Valide autoria, data, instituição, referências e finalidade. Na escrita, pesquise dados, selecione argumentos em sequência lógica e use recursos não verbais com ética e adequação ao suporte.",examples:[["School records show a 30% reduction; therefore, the campaign had measurable impact.","Conclusão apoiada por dado identificável."],["The phrase 'the only solution' is persuasive, not a proven fact.","Análise de escolha linguística."],["I respect your view; my source leads me to a different conclusion.","Troca ética de pontos de vista."]],project:"Local Issue Critical Campaign"}),
 make({slug:"u9-a10-digital-global-english",title:"Digital & Global English 🌐",codes:["EF09LI13","EF09LI14","EF09LI15","EF09LI16","EF09LI17","EF09LI18","EF09LI19"],goal:"Interpretar escrita digital, construir argumentação com conectores, condicionais e modais e debater criticamente a expansão histórica e o papel científico, econômico, político e identitário do inglês.",text:["Digital messages combine abbreviations, emojis and symbols, but meaning changes with audience and context.","English expanded through migration, trade and British colonization, often alongside coercion and the suppression of local languages.","Today it supports international scientific, economic and political exchange, while access remains unequal.","If institutions value multilingualism, English may connect communities without replacing local languages or identities."],vocab:[["abbreviation","abreviação"],["pictogram","pictograma"],["connector","conector"],["condition","condição"],["colonization","colonização"],["exchange","intercâmbio"],["multilingualism","multilinguismo"],["identity","identidade"]],lesson:"Em gêneros digitais, abreviações, letras, números e pictogramas dependem de contexto e público. Organize argumentos com addition (moreover), opposition (however), condition (if), conclusion (therefore) e synthesis (in summary). First conditional trata possibilidade real; second, hipótese. Should recomenda; must/have to indicam obrigação ou necessidade; may/might, probabilidade. Debata a expansão do inglês considerando colonização, poder, ciência, economia, política, identidades e valorização do multilinguismo.",examples:[["Moreover, English supports research exchange; however, translation also matters.","Adição e oposição na argumentação."],["If access improves, more students will participate.","Condição possível e consequência futura."],["Schools should teach English, but they must also value local languages.","Recomendação e obrigação em posição equilibrada."],["BRB may be clear among friends, but it might confuse a formal audience.","Internetês adequado ao contexto."]],project:"Global English Debate Dossier"})
];
