import type { AulaGeoV1 } from "../../types";
import { aula01 as base } from "./aula-01-cuidado-vida";
const b=base as any;

/** EF09ER02 — valorização e desrespeito à vida por meio da análise crítica de mídias. */
export const aula02:AulaGeoV1={
 ...base,slug:"aula-02-vida-nas-midias",titulo:"Vida, Dignidade e Mídias",iconeTrilha:"📰",bncc:["EF09ER02"],duracaoMin:25,
 cena01_motivacao:{...b.cena01_motivacao,instrucao:"Compare manchete, imagem, fonte e contexto.",aurora:"Uma matéria pode valorizar a vida ao informar com respeito e apresentar soluções, ou desrespeitá-la ao humilhar pessoas, espalhar preconceito e esconder contexto. Nesta aula, você aprenderá a analisar mensagens sem compartilhar conteúdo ofensivo.",falaFinal:"Ler criticamente também é uma forma de cuidar da vida."},
 cena02_previsao:{...b.cena02_previsao,aurora:"Antes de acreditar ou compartilhar, investigue.",pergunta:"Qual é a primeira atitude diante de uma matéria impactante?",opcoes:[{id:"verificar",titulo:"Verificar fonte, data, evidências e contexto",subtitulo:"leitura crítica",emoji:"🔎",cor:"from-emerald-500 to-green-700"},{id:"repassar",titulo:"Repassar imediatamente",subtitulo:"aumenta o risco de desinformação",emoji:"📤",cor:"from-red-500 to-rose-700"},{id:"titulo",titulo:"Ler apenas o título",subtitulo:"não mostra o contexto",emoji:"📰",cor:"from-slate-400 to-gray-600"},{id:"atacar",titulo:"Atacar quem aparece",subtitulo:"desrespeita a dignidade",emoji:"⚠️",cor:"from-amber-500 to-orange-700"}],respostaCerta:"verificar",feedbackAcerto:"Correto: fonte, data, evidências e contexto vêm antes da conclusão.",feedbackErro:"Não compartilhe pelo impacto. Verifique fonte, data, evidências e contexto.",falaFinal:"Agora vamos aplicar um roteiro de análise."},
 cena03_vocabulario:{...b.cena03_vocabulario,aurora:"Quatro ferramentas para ler mídias.",instrucao:"Abra os quatro cadernos",cadernos:[{id:"fonte",capa:"Fonte",emoji:"📰",cor:"from-sky-500 to-blue-700",conteudo:"Quem produziu a matéria e quais responsabilidades editoriais assume.",exemplo:"Identifique veículo, autoria e canais de correção.",fotoUrl:b.cena03_vocabulario.cadernos[0].fotoUrl},{id:"evidencia",capa:"Evidência",emoji:"🔎",cor:"from-emerald-500 to-green-700",conteudo:"Dados, documentos, entrevistas e outras informações que sustentam uma afirmação.",exemplo:"Uma opinião não substitui dados verificáveis.",fotoUrl:b.cena03_vocabulario.cadernos[1].fotoUrl},{id:"enquadramento",capa:"Enquadramento",emoji:"🖼️",cor:"from-purple-500 to-fuchsia-700",conteudo:"Escolhas de palavras, imagens e vozes que orientam a interpretação.",exemplo:"Pergunte quem foi ouvido e quem ficou sem voz.",fotoUrl:b.cena03_vocabulario.cadernos[2].fotoUrl},{id:"dignidade",capa:"Dignidade",emoji:"🤝",cor:"from-amber-500 to-orange-700",conteudo:"Toda pessoa deve ser representada sem humilhação, estereótipo ou exposição desnecessária.",exemplo:"Informar um problema sem culpar ou ridicularizar grupos.",fotoUrl:b.cena03_vocabulario.cadernos[0].fotoUrl}],falaFinal:"Fonte, evidência, enquadramento e dignidade formam o nosso filtro."},
 cena04_leituraGuiada:{...b.cena04_leituraGuiada,aurora:"Analise quatro formas de representar a vida.",instrucao:"Toque em cada caso",pontos:[{...b.cena04_leituraGuiada.pontos[0],id:"valoriza",titulo:"VALORIZA",texto:"Apresenta pessoas com dignidade, explica causas e mostra caminhos de proteção ou cuidado."},{...b.cena04_leituraGuiada.pontos[1],id:"desrespeita",titulo:"DESRESPEITA",texto:"Usa preconceito, humilhação, culpa generalizada ou exposição desnecessária para gerar atenção."},{...b.cena04_leituraGuiada.pontos[2],id:"incompleta",titulo:"INFORMAÇÃO INCOMPLETA",texto:"Mostra números ou imagens sem explicar fonte, período, comparação e contexto."},{...b.cena04_leituraGuiada.pontos[3],id:"responsavel",titulo:"RESPOSTA RESPONSÁVEL",texto:"Confere a informação, não amplia a ofensa, denuncia violações e procura fontes confiáveis."}],falaFinal:"O efeito sobre a dignidade faz parte da análise da mensagem."},
 cena05_compreensao:{...b.cena05_compreensao,aurora:"Analise, não chute.",perguntas:[{id:"q1",pergunta:"Uma matéria valoriza a vida quando:",fotoUrl:b.cena05_compreensao.perguntas[0].fotoUrl,cards:[{id:"c",emoji:"🤝",titulo:"Informa com evidências, contexto e respeito",cor:"from-emerald-500 to-green-700"},{id:"a",emoji:"📣",titulo:"Humilha para chamar atenção",cor:"from-red-500 to-rose-700"},{id:"b",emoji:"❓",titulo:"Esconde a fonte",cor:"from-slate-400 to-gray-600"},{id:"d",emoji:"⚠️",titulo:"Generaliza um grupo inteiro",cor:"from-amber-500 to-orange-700"}],correta:"c",feedbackAcerto:"Isso: evidência, contexto e respeito.",feedbackErro:"Procure informação verificável e representação digna."}],falaFinal:"Você avaliou conteúdo e modo de representar pessoas."},
 cena08_voceLe:{...b.cena08_voceLe,tituloLivro:"Caderno do Leitor Crítico",subtitulo:"EF09ER02 — valorização e desrespeito à vida nas mídias",paragrafos:[{id:"p1",texto:"Mídias selecionam palavras, imagens, fontes e vozes. Essas escolhas podem valorizar ou desrespeitar a vida.",chaves:["escolhas","valorizar"]},{id:"p2",texto:"Uma análise responsável verifica autoria, data, evidências, contexto, pessoas ouvidas e possíveis interesses.",chaves:["evidências","contexto"]},{id:"p3",texto:"Humilhação, preconceito, exposição desnecessária e generalização ferem a dignidade, mesmo quando apresentados como entretenimento.",chaves:["dignidade","generalização"]},{id:"p4",texto:"Antes de compartilhar, confirme a informação, evite ampliar a ofensa e use canais responsáveis para denunciar violações.",chaves:["confirmar","denunciar"]}],falaFinal:"Use esse roteiro sempre que uma mensagem pedir reação imediata."},
 cena11_avaliacao:{...b.cena11_avaliacao,aurora:"Avaliação final de leitura crítica.",perguntas:[{id:"a1",pergunta:"Qual conjunto permite analisar uma matéria?",opcoes:[{id:"a",texto:"Título e quantidade de curtidas",correta:false},{id:"b",texto:"Fonte, data, evidências, contexto e dignidade",correta:true},{id:"c",texto:"Somente a imagem",correta:false},{id:"d",texto:"Opinião de um comentário",correta:false}],feedbackAcerto:"Correto: análise exige fonte, evidência, contexto e respeito.",feedbackErro:"Curtidas e impacto não substituem verificação."},{id:"a2",pergunta:"Qual expressão desrespeita a vida?",opcoes:[{id:"a",texto:"Informar com contexto e preservar a dignidade",correta:false},{id:"b",texto:"Ouvir as pessoas afetadas",correta:false},{id:"c",texto:"Humilhar e generalizar um grupo para gerar atenção",correta:true},{id:"d",texto:"Apresentar dados verificáveis",correta:false}],feedbackAcerto:"Isso: humilhação e generalização ferem a dignidade.",feedbackErro:"Procure a opção que expõe e reduz pessoas a estereótipos."},{id:"a3",pergunta:"Antes de compartilhar, o correto é:",opcoes:[{id:"a",texto:"Reagir só ao título",correta:false},{id:"b",texto:"Confirmar a informação e considerar seus efeitos",correta:true},{id:"c",texto:"Apagar a autoria",correta:false},{id:"d",texto:"Aumentar o tom ofensivo",correta:false}],feedbackAcerto:"Correto: verifique e aja com responsabilidade.",feedbackErro:"Compartilhar exige confirmação e cuidado."}],selo:{nome:"Leitor Crítico da Vida",subtitulo:"EF09ER02 concluída",emoji:"📰",cor:"from-sky-400 to-emerald-600"},falaFinal:"Você aprendeu a analisar mídias protegendo informação e dignidade."},
 recompensa:{xp:400,moedas:280,medalha:"Leitor Crítico da Vida"}
};
