import type { AulaGeoV1 } from "../../types";
import { url as equipe } from "@/assets/ciencias-5ano/u1-a1/equipe-cientistas.jpg.asset.json";
import { url as caderno } from "@/assets/ciencias-5ano/u1-a1/caderno-hipoteses.jpg.asset.json";
import { url as grafico } from "@/assets/ciencias-5ano/u1-a1/grafico-barras.jpg.asset.json";
import { url as vasos } from "@/assets/ciencias-5ano/u1-a1/experimento-vasos.jpg.asset.json";
import { url as tabela } from "@/assets/ciencias-5ano/u1-a1/tabela-dados.jpg.asset.json";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-laboratorio-cientista",
  titulo: "Laboratório do Cientista",
  iconeTrilha: "🔬",
  bncc: ["EF05CI01"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pela bancada da equipe. Encontre os elementos de uma investigação de verdade.",
    mapaUrl: equipe,
    imagemDestaqueUrl: caderno,
    aurora:
      "Bem-vindo de volta à Equipe de Pesquisa Escola Brilha. Este ano a barra sobe: vamos analisar gráficos, comparar dados e defender conclusões com evidências.",
    falaFinal:
      "Cientista sério não decora respostas — ele coleta dados, interpreta e comunica. É exatamente isso que a gente treina aqui.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Olha o gráfico: três grupos de plantas medidos por 30 dias. Qual grupo cresceu MAIS?",
    pergunta: "Analisando o gráfico de barras, qual condição gerou o maior crescimento?",
    fotoUrl: grafico,
    opcoes: [
      { id: "amber", titulo: "Barra AMBAR", subtitulo: "a mais alta", emoji: "📊", cor: "from-amber-400 to-orange-600" },
      { id: "teal", titulo: "Barra TEAL", subtitulo: "média", emoji: "📊", cor: "from-teal-400 to-emerald-600" },
      { id: "slate", titulo: "Barra SLATE", subtitulo: "a mais baixa", emoji: "📊", cor: "from-slate-500 to-slate-800" },
    ],
    respostaCerta: "amber",
    feedbackAcerto: "Leitura correta. A barra âmbar é visivelmente a mais alta — cresceu mais.",
    feedbackErro: "Olhe a altura das barras no eixo Y. A âmbar chega mais perto do topo.",
    falaFinal: "Ler gráfico é ler EVIDÊNCIA. Sem interpretar dados, você não é cientista — é palpiteiro.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco conceitos que separam pesquisa séria de achismo.",
    instrucao: "Vocabulário técnico da pesquisa",
    cadernos: [
      { id: "variavel", capa: "VARIÁVEL", emoji: "🎛️", cor: "from-teal-500 to-emerald-700",
        conteudo: "Fator que muda entre os grupos do experimento. O cientista muda UMA por vez.",
        exemplo: "Ex.: só a luz muda; água e terra são iguais.", fotoUrl: vasos },
      { id: "controle", capa: "CONTROLE", emoji: "⚖️", cor: "from-cyan-500 to-sky-700",
        conteudo: "Grupo que NÃO recebe a mudança. Serve pra comparar com os outros.",
        exemplo: "Ex.: planta com luz normal, sem alterar nada.", fotoUrl: vasos },
      { id: "amostra", capa: "AMOSTRA", emoji: "🧫", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Quantidade de coisas medidas. Quanto MAIOR a amostra, mais confiável o dado.",
        exemplo: "Ex.: 10 plantas por grupo é melhor que 1.", fotoUrl: equipe },
      { id: "media", capa: "MÉDIA", emoji: "➗", cor: "from-amber-500 to-orange-700",
        conteudo: "Valor típico do grupo. Soma tudo, divide pelo total de amostras.",
        exemplo: "Ex.: alturas 10, 12, 14 → média = 12 cm.", fotoUrl: tabela },
      { id: "evidencia", capa: "EVIDÊNCIA", emoji: "🔎", cor: "from-emerald-500 to-green-800",
        conteudo: "Dado registrado que sustenta a conclusão. Se não tem evidência, não é ciência.",
        exemplo: "Ex.: 'O gráfico mostra 28 cm no sol'.", fotoUrl: grafico },
    ],
    falaFinal: "Variável, controle, amostra, média, evidência. Esse é o kit básico do pesquisador.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "A bancada da equipe. Toca em cada item e descubra a função científica.",
    instrucao: "Toque em cada item",
    mapaUrl: equipe,
    pontos: [
      { id: "notebook", x: 30, y: 65, emoji: "💻", cor: "from-slate-500 to-slate-700",
        titulo: "Notebook", texto: "Registra dados em planilha, gera gráficos e permite compartilhar com outros pesquisadores.",
        fotoUrl: tabela },
      { id: "beaker", x: 70, y: 75, emoji: "🧪", cor: "from-cyan-500 to-sky-700",
        titulo: "Béquer", texto: "Vidraria calibrada — mede volume de líquidos em mililitros com precisão.",
        fotoUrl: equipe },
      { id: "caderno", x: 50, y: 60, emoji: "📓", cor: "from-teal-500 to-emerald-700",
        titulo: "Caderno de bancada", texto: "Anotações manuais com data, hora e observações — prova documental da pesquisa.",
        fotoUrl: caderno },
      { id: "grafico", x: 20, y: 40, emoji: "📊", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Gráfico", texto: "Visualiza dados numéricos. Barras comparam quantidades entre grupos.",
        fotoUrl: grafico },
      { id: "planta", x: 85, y: 45, emoji: "🌱", cor: "from-emerald-500 to-green-700",
        titulo: "Amostra vegetal", texto: "Objeto de estudo — sujeito da pesquisa. Cada amostra gera dados independentes.",
        fotoUrl: vasos },
    ],
    falaFinal: "Cada instrumento tem uma função. Escolher o certo é parte do rigor científico.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "Checkpoint técnico. 3 perguntas.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Pra que serve o GRUPO CONTROLE num experimento?",
        fotoUrl: vasos,
        cards: [
          { id: "a", emoji: "⚖️", titulo: "Pra comparar com os grupos que sofreram mudança", cor: "from-teal-500 to-emerald-700" },
          { id: "b", emoji: "👨‍🔬", titulo: "Pra o cientista mostrar autoridade", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "📋", titulo: "Pra listar os materiais", cor: "from-red-500 to-rose-700" },
        ], correta: "a",
        feedbackAcerto: "Isso. Sem grupo controle, você não sabe se a mudança teve efeito.",
        feedbackErro: "Grupo controle é o parâmetro de comparação — sem ele, não dá pra concluir nada." },
      { id: "q2", pergunta: "Se uma pesquisa tem só 2 amostras, o resultado é confiável?",
        fotoUrl: tabela,
        cards: [
          { id: "a", emoji: "✅", titulo: "Sim, 2 já é suficiente", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "❌", titulo: "Não, amostra pequena dá resultado incerto", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "🤷", titulo: "Depende do humor do cientista", cor: "from-slate-500 to-slate-700" },
        ], correta: "b",
        feedbackAcerto: "Exato. Amostras maiores tornam a média mais representativa da realidade.",
        feedbackErro: "Cuidado. Amostra pequena pode ter azar ou coincidência. Mais amostras = mais confiança." },
      { id: "q3", pergunta: "O que é uma EVIDÊNCIA científica?",
        fotoUrl: grafico,
        cards: [
          { id: "a", emoji: "💭", titulo: "Uma opinião forte de alguém importante", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "📊", titulo: "Dado registrado que apoia a conclusão", cor: "from-cyan-500 to-sky-700" },
          { id: "c", emoji: "🎬", titulo: "Uma cena de filme", cor: "from-slate-500 to-slate-700" },
        ], correta: "b",
        feedbackAcerto: "Sim. Evidência é dado — não é opinião, não é intuição.",
        feedbackErro: "Opinião não é evidência. Só dado registrado e verificável conta como evidência científica." },
    ],
    falaFinal: "Você já sabe distinguir pesquisa séria de achismo. Isso é ciência.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "A bancada tem duas zonas: PLANEJAMENTO (ideias, hipóteses, gráficos) e EXECUÇÃO (amostras, medições reais). Liga cada camada.",
    instrucao: "Toque nos interruptores",
    mapaUrl: equipe,
    camadas: [
      { id: "planejamento", rotulo: "Planejamento", emoji: "💡", cor: "from-amber-500 to-orange-700",
        rect: { x: 2, y: 30, w: 48, h: 65 },
        descricao: "Notebook e caderno de hipóteses. Aqui a equipe pensa, desenha o experimento e prevê resultados.",
        fotoUrl: caderno },
      { id: "execucao", rotulo: "Execução", emoji: "🧪", cor: "from-cyan-500 to-sky-700",
        rect: { x: 50, y: 30, w: 48, h: 65 },
        descricao: "Béqueres, amostras e instrumentos. Aqui os dados são coletados no mundo real.",
        fotoUrl: vasos },
    ],
    falaFinal: "Planejar bem economiza tempo. Executar com rigor gera dados confiáveis.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a ordem do método científico avançado.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual é a sequência de uma pesquisa completa?",
    paradas: [
      { id: "pergunta", emoji: "❓", rotulo: "1. Pergunta", descricao: "Formular uma pergunta clara que possa ser respondida com dados.", fotoUrl: caderno },
      { id: "hipotese", emoji: "💡", rotulo: "2. Hipótese", descricao: "Prever a resposta com base em observações anteriores.", fotoUrl: caderno },
      { id: "experimento", emoji: "🧪", rotulo: "3. Experimento", descricao: "Montar teste controlado com variável isolada e grupo controle.", fotoUrl: vasos },
      { id: "grafico", emoji: "📊", rotulo: "4. Dados & Gráfico", descricao: "Medir, calcular média e visualizar em gráfico.", fotoUrl: grafico },
      { id: "comunicar", emoji: "📣", rotulo: "5. Comunicar", descricao: "Publicar conclusão com evidências pra outros verificarem.", fotoUrl: equipe },
    ],
    ordemCerta: ["pergunta", "hipotese", "experimento", "grafico", "comunicar"],
    feedbackAcerto: "Rota completa. É assim que uma pesquisa científica de verdade acontece.",
    feedbackErro: "Repense: você precisa da PERGUNTA antes da hipótese, e dos DADOS antes de comunicar.",
    falaFinal: "Uma pesquisa que não comunica os dados fica invisível pra ciência. Comunicar é parte do método.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura autônoma. Estuda o resumo da pesquisa.",
    tituloLivro: "📓 Resumo Científico · Experimento 05",
    subtitulo: "Efeito da luz solar no crescimento vegetal",
    paragrafos: [
      { id: "p1", texto:
          "Nossa PERGUNTA foi: 'A intensidade de luz afeta o crescimento?'. Formulamos a HIPÓTESE de que MAIS luz gera MAIS crescimento. Montamos 3 grupos de 10 plantas — sol, sombra e escuro — mantendo água e solo idênticos. Somente a VARIÁVEL luz mudou.",
        chaves: ["pergunta", "hipótese", "variável"],
        definicoes: {
          pergunta: "Frase clara que a pesquisa quer responder.",
          hipótese: "Previsão baseada em observações anteriores.",
          variável: "Fator que muda entre os grupos do experimento.",
        }, fotoUrl: vasos },
      { id: "p2", texto:
          "Após 30 dias, calculamos a MÉDIA de altura de cada grupo. Sol: 28 cm. Sombra: 14 cm. Escuro: 4 cm. Registramos tudo em TABELA e transformamos em GRÁFICO de barras — que mostrou visualmente a diferença brutal entre os grupos.",
        chaves: ["média", "tabela", "gráfico"],
        definicoes: {
          média: "Soma dos valores dividida pela quantidade de amostras.",
          tabela: "Organização de dados em linhas e colunas.",
          gráfico: "Representação visual dos dados numéricos.",
        }, fotoUrl: grafico },
      { id: "p3", texto:
          "CONCLUSÃO: os dados são EVIDÊNCIA de que luz influencia diretamente o crescimento. A hipótese foi confirmada. Publicamos os dados pra que outros grupos possam REPRODUZIR o experimento e verificar. Ciência só vale se pode ser conferida.",
        chaves: ["evidência", "reproduzir"],
        definicoes: {
          evidência: "Dado registrado que sustenta a conclusão.",
          reproduzir: "Repetir o experimento pra conferir se dá o mesmo resultado.",
        }, fotoUrl: caderno },
    ],
    falaFinal: "Você acabou de ler o resumo de um artigo científico simplificado. É assim que ciência de verdade se comunica.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra uma situação — identifica qual conceito científico está em jogo.",
    instrucao: "⏱️ Leia e escolha o conceito correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "variavel", emoji: "🎛️", rotulo: "Variável" },
      { id: "controle", emoji: "⚖️", rotulo: "Controle" },
      { id: "amostra", emoji: "🧫", rotulo: "Amostra" },
      { id: "media", emoji: "➗", rotulo: "Média" },
      { id: "evidencia", emoji: "🔎", rotulo: "Evidência" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Só a luz muda", emoji: "☀️", cor: "from-amber-500 to-orange-700" },
        municipioB: { nome: "Água e terra iguais", emoji: "💧", cor: "from-cyan-500 to-sky-700" },
        contexto: "A equipe garante que os 3 vasos têm mesma água e mesma terra. Só a LUZ muda entre eles.",
        pecaCertaId: "variavel", fotoUrl: vasos,
        feedbackAcerto: "Isso. O fator que muda entre grupos é a VARIÁVEL.",
        feedbackErro: "O que muda entre os grupos é a variável do experimento." },
      { id: "r2", municipioA: { nome: "Planta normal", emoji: "🌿", cor: "from-emerald-500 to-green-700" },
        municipioB: { nome: "Sem intervenção", emoji: "⚖️", cor: "from-slate-500 to-slate-700" },
        contexto: "Uma planta fica no ambiente normal, sem nenhuma alteração. Serve pra comparar com as outras.",
        pecaCertaId: "controle", fotoUrl: vasos,
        feedbackAcerto: "Perfeito. Grupo sem intervenção = CONTROLE.",
        feedbackErro: "Grupo que não recebe a mudança é o grupo CONTROLE — referência de comparação." },
      { id: "r3", municipioA: { nome: "10 plantas por grupo", emoji: "🌱🌱🌱", cor: "from-teal-500 to-emerald-700" },
        municipioB: { nome: "Quantidade estudada", emoji: "🧫", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Em vez de testar com 1 planta só, a equipe usa 10 por grupo pra ter mais confiança.",
        pecaCertaId: "amostra", fotoUrl: equipe,
        feedbackAcerto: "Sim. Quantidade estudada é o tamanho da AMOSTRA.",
        feedbackErro: "Quantidade de indivíduos estudados é a AMOSTRA — maior amostra, mais confiança." },
      { id: "r4", municipioA: { nome: "10+12+14 ÷ 3", emoji: "➗", cor: "from-amber-500 to-yellow-700" },
        municipioB: { nome: "Valor típico do grupo", emoji: "📊", cor: "from-orange-500 to-red-700" },
        contexto: "A equipe soma as alturas e divide pela quantidade — obtém 12 cm como valor típico do grupo.",
        pecaCertaId: "media", fotoUrl: tabela,
        feedbackAcerto: "Isso. Soma dividida pela quantidade = MÉDIA.",
        feedbackErro: "Soma dividida pela quantidade é a MÉDIA do grupo." },
      { id: "r5", municipioA: { nome: "Gráfico mostra 28 cm", emoji: "📊", cor: "from-teal-500 to-emerald-700" },
        municipioB: { nome: "Dado apoia conclusão", emoji: "🔎", cor: "from-emerald-500 to-green-700" },
        contexto: "A equipe usa o gráfico com dados reais pra defender que 'luz aumenta o crescimento'.",
        pecaCertaId: "evidencia", fotoUrl: grafico,
        feedbackAcerto: "Perfeito. Dado registrado que apoia a conclusão = EVIDÊNCIA.",
        feedbackErro: "Dado registrado que sustenta uma conclusão é uma EVIDÊNCIA científica." },
    ],
    falaFinal: "Você aplica os conceitos em qualquer investigação. Está no nível de pesquisador de escola de ponta.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "A pesquisa dividida em dois grandes momentos: PENSAR (planejamento) e AGIR (execução e análise).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: equipe,
    fatias: [
      { id: "pensar", rotulo: "Pensar", emoji: "💡", percentual: 40, cor: "#f59e0b",
        descricao: "Pergunta, hipótese e desenho do experimento. Tudo antes de tocar em uma amostra.",
        exemplos: ["Formular pergunta", "Escrever hipótese", "Desenhar experimento"], fotoUrl: caderno },
      { id: "agir", rotulo: "Agir & Analisar", emoji: "📊", percentual: 60, cor: "#0d9488",
        descricao: "Medir, calcular médias, gerar gráficos, defender conclusão com evidências.",
        exemplos: ["Coletar dados", "Fazer gráfico", "Publicar conclusão"], fotoUrl: grafico },
    ],
    falaFinal: "As duas metades andam juntas. Pesquisa sem planejamento é confusa; planejamento sem execução é teoria vazia.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "Última missão. 3 perguntas técnicas e sua carteira de Pesquisador de Bancada é liberada.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: equipe,
    perguntas: [
      { id: "q1", pergunta: "Por que usar GRUPO CONTROLE?",
        fotoUrl: vasos,
        opcoes: [
          { id: "a", texto: "Pra comparar e saber se a variável teve efeito", correta: true },
          { id: "b", texto: "Pra deixar o experimento mais bonito" },
        ],
        feedbackAcerto: "Sim. Sem controle, você não sabe se o resultado veio da variável ou de outro fator.",
        feedbackErro: "Beleza não é critério científico. Controle serve pra COMPARAR." },
      { id: "q2", pergunta: "Qual amostra dá resultado mais confiável?",
        fotoUrl: tabela,
        opcoes: [
          { id: "a", texto: "10 plantas por grupo", correta: true },
          { id: "b", texto: "1 planta por grupo" },
        ],
        feedbackAcerto: "Correto. Amostra maior reduz influência de coincidências.",
        feedbackErro: "1 amostra pode ter azar. 10 amostras dão média mais representativa." },
      { id: "q3", pergunta: "Uma conclusão sem dados registrados vale como ciência?",
        fotoUrl: grafico,
        opcoes: [
          { id: "a", texto: "Não, sem evidência não é ciência", correta: true },
          { id: "b", texto: "Sim, se o cientista for famoso" },
        ],
        feedbackAcerto: "Isso. Ciência exige EVIDÊNCIA verificável — fama não substitui dado.",
        feedbackErro: "Nem o cientista mais famoso conclui sem dados. Sem evidência não é ciência." },
    ],
    selo: {
      nome: "Carteira de Pesquisador de Bancada",
      subtitulo: "Missão Planeta Vivo · Laboratório 1 concluído",
      emoji: "🎖️",
      cor: "from-teal-400 via-emerald-500 to-green-700",
    },
    falaFinal: "Carteira registrada. Você agora entra na Unidade 2 — os ecossistemas do planeta.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Pesquisador de Bancada" },
};
