/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TerapeutaBrilhaRouteImport } from './routes/terapeuta-brilha'
import { Route as RotinaRouteImport } from './routes/rotina'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ReforcoBrilhaRouteImport } from './routes/reforco-brilha'
import { Route as ProgressaoRouteImport } from './routes/progressao'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PerfilAlunoRouteImport } from './routes/perfil-aluno'
import { Route as PainelPaisRouteImport } from './routes/painel-pais'
import { Route as NeuroTreinoRouteImport } from './routes/neuro-treino'
import { Route as MissaoTrabalhoRouteImport } from './routes/missao-trabalho'
import { Route as MissaoTarefaRouteImport } from './routes/missao-tarefa'
import { Route as MissaoProvaRouteImport } from './routes/missao-prova'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MatrizPedagogicaRouteImport } from './routes/matriz-pedagogica'
import { Route as MascotesRouteImport } from './routes/mascotes'
import { Route as LojaMascotesRouteImport } from './routes/loja-mascotes'
import { Route as Jornada365RouteImport } from './routes/jornada-365'
import { Route as GeradorProceduralRouteImport } from './routes/gerador-procedural'
import { Route as CuradoriaAulasRouteImport } from './routes/curadoria-aulas'
import { Route as ColecaoPipRouteImport } from './routes/colecao-pip'
import { Route as BrilhaVidaRouteImport } from './routes/brilha-vida'
import { Route as BibliotecaPedagogicaRouteImport } from './routes/biblioteca-pedagogica'
import { Route as BibliotecaAlfaRouteImport } from './routes/biblioteca-alfa'
import { Route as BancoMidiasRouteImport } from './routes/banco-midias'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditoriaPedagogicaRouteImport } from './routes/auditoria-pedagogica'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlfabetizacaoRouteImport } from './routes/alfabetizacao'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscolaBrilhaIndexRouteImport } from './routes/escola-brilha.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NeuroTreinoConfigurarRouteImport } from './routes/neuro-treino.configurar'
import { Route as NeuroTreinoSlugRouteImport } from './routes/neuro-treino.$slug'
import { Route as EscolaBrilhaProfessoresRouteImport } from './routes/escola-brilha.professores'
import { Route as EscolaBrilhaCodigoRouteImport } from './routes/escola-brilha.$codigo'
import { Route as BnccCodigoRouteImport } from './routes/bncc.$codigo'
import { Route as AnamneseChildIdRouteImport } from './routes/anamnese.$childId'
import { Route as AjusteDificuldadesChildIdRouteImport } from './routes/ajuste-dificuldades.$childId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as EscolaBrilhaPortuguesEiIndexRouteImport } from './routes/escola-brilha.portugues-ei.index'
import { Route as EscolaBrilhaMatematicaEiIndexRouteImport } from './routes/escola-brilha.matematica-ei.index'
import { Route as EscolaBrilhaLerComAuroraIndexRouteImport } from './routes/escola-brilha.ler-com-aurora.index'
import { Route as EscolaBrilhaTrilhaInglesSerieRouteImport } from './routes/escola-brilha.trilha-ingles.$serie'
import { Route as EscolaBrilhaLerComAuroraPainelRouteImport } from './routes/escola-brilha.ler-com-aurora.painel'
import { Route as EscolaBrilhaLerComAuroraDiagnosticoRouteImport } from './routes/escola-brilha.ler-com-aurora.diagnostico'
import { Route as EscolaBrilhaLerComAuroraAulaRouteImport } from './routes/escola-brilha.ler-com-aurora.$aula'
import { Route as EscolaBrilhaGeo9anoUnidadeRouteImport } from './routes/escola-brilha.geo-9ano.$unidade'
import { Route as EscolaBrilhaGeo8anoUnidadeRouteImport } from './routes/escola-brilha.geo-8ano.$unidade'
import { Route as EscolaBrilhaGeo7anoUnidadeRouteImport } from './routes/escola-brilha.geo-7ano.$unidade'
import { Route as EscolaBrilhaGeo6anoUnidadeRouteImport } from './routes/escola-brilha.geo-6ano.$unidade'
import { Route as EscolaBrilhaCursoSlugRouteImport } from './routes/escola-brilha.curso.$slug'
import { Route as EscolaBrilhaAtlasFinalCursoRouteImport } from './routes/escola-brilha.atlas-final.$curso'
import { Route as AnamneseChildIdResultadoRouteImport } from './routes/anamnese.$childId.resultado'
import { Route as AnamneseChildIdEscalasRouteImport } from './routes/anamnese.$childId.escalas'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as EscolaBrilhaTrilhaSerieDiscRouteImport } from './routes/escola-brilha.trilha.$serie.$disc'
import { Route as EscolaBrilhaTrilhaFund2SerieDiscRouteImport } from './routes/escola-brilha.trilha-fund2.$serie.$disc'
import { Route as EscolaBrilhaPortuguesEiSerieAulaRouteImport } from './routes/escola-brilha.portugues-ei.$serie.$aula'
import { Route as EscolaBrilhaMatematicaEiSerieAulaRouteImport } from './routes/escola-brilha.matematica-ei.$serie.$aula'
import { Route as EscolaBrilhaInglesV1CursoAulaRouteImport } from './routes/escola-brilha.ingles-v1.$curso.$aula'
import { Route as EscolaBrilhaAulaV4CursoAulaRouteImport } from './routes/escola-brilha.aula-v4.$curso.$aula'
import { Route as EscolaBrilhaAulaPtV4CursoAulaRouteImport } from './routes/escola-brilha.aula-pt-v4.$curso.$aula'
import { Route as EscolaBrilhaAulaGeoV1CursoAulaRouteImport } from './routes/escola-brilha.aula-geo-v1.$curso.$aula'
import { Route as EscolaBrilhaAulaArteV1CursoAulaRouteImport } from './routes/escola-brilha.aula-arte-v1.$curso.$aula'

const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapeutaBrilhaRoute = TerapeutaBrilhaRouteImport.update({
  id: '/terapeuta-brilha',
  path: '/terapeuta-brilha',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaRoute = RotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReforcoBrilhaRoute = ReforcoBrilhaRouteImport.update({
  id: '/reforco-brilha',
  path: '/reforco-brilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressaoRoute = ProgressaoRouteImport.update({
  id: '/progressao',
  path: '/progressao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilAlunoRoute = PerfilAlunoRouteImport.update({
  id: '/perfil-aluno',
  path: '/perfil-aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPaisRoute = PainelPaisRouteImport.update({
  id: '/painel-pais',
  path: '/painel-pais',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuroTreinoRoute = NeuroTreinoRouteImport.update({
  id: '/neuro-treino',
  path: '/neuro-treino',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoTrabalhoRoute = MissaoTrabalhoRouteImport.update({
  id: '/missao-trabalho',
  path: '/missao-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoTarefaRoute = MissaoTarefaRouteImport.update({
  id: '/missao-tarefa',
  path: '/missao-tarefa',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoProvaRoute = MissaoProvaRouteImport.update({
  id: '/missao-prova',
  path: '/missao-prova',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrizPedagogicaRoute = MatrizPedagogicaRouteImport.update({
  id: '/matriz-pedagogica',
  path: '/matriz-pedagogica',
  getParentRoute: () => rootRouteImport,
} as any)
const MascotesRoute = MascotesRouteImport.update({
  id: '/mascotes',
  path: '/mascotes',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaMascotesRoute = LojaMascotesRouteImport.update({
  id: '/loja-mascotes',
  path: '/loja-mascotes',
  getParentRoute: () => rootRouteImport,
} as any)
const Jornada365Route = Jornada365RouteImport.update({
  id: '/jornada-365',
  path: '/jornada-365',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorProceduralRoute = GeradorProceduralRouteImport.update({
  id: '/gerador-procedural',
  path: '/gerador-procedural',
  getParentRoute: () => rootRouteImport,
} as any)
const CuradoriaAulasRoute = CuradoriaAulasRouteImport.update({
  id: '/curadoria-aulas',
  path: '/curadoria-aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoPipRoute = ColecaoPipRouteImport.update({
  id: '/colecao-pip',
  path: '/colecao-pip',
  getParentRoute: () => rootRouteImport,
} as any)
const BrilhaVidaRoute = BrilhaVidaRouteImport.update({
  id: '/brilha-vida',
  path: '/brilha-vida',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaPedagogicaRoute = BibliotecaPedagogicaRouteImport.update({
  id: '/biblioteca-pedagogica',
  path: '/biblioteca-pedagogica',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaAlfaRoute = BibliotecaAlfaRouteImport.update({
  id: '/biblioteca-alfa',
  path: '/biblioteca-alfa',
  getParentRoute: () => rootRouteImport,
} as any)
const BancoMidiasRoute = BancoMidiasRouteImport.update({
  id: '/banco-midias',
  path: '/banco-midias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaPedagogicaRoute = AuditoriaPedagogicaRouteImport.update({
  id: '/auditoria-pedagogica',
  path: '/auditoria-pedagogica',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabetizacaoRoute = AlfabetizacaoRouteImport.update({
  id: '/alfabetizacao',
  path: '/alfabetizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaBrilhaIndexRoute = EscolaBrilhaIndexRouteImport.update({
  id: '/escola-brilha/',
  path: '/escola-brilha/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NeuroTreinoConfigurarRoute = NeuroTreinoConfigurarRouteImport.update({
  id: '/configurar',
  path: '/configurar',
  getParentRoute: () => NeuroTreinoRoute,
} as any)
const NeuroTreinoSlugRoute = NeuroTreinoSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeuroTreinoRoute,
} as any)
const EscolaBrilhaProfessoresRoute = EscolaBrilhaProfessoresRouteImport.update({
  id: '/escola-brilha/professores',
  path: '/escola-brilha/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaBrilhaCodigoRoute = EscolaBrilhaCodigoRouteImport.update({
  id: '/escola-brilha/$codigo',
  path: '/escola-brilha/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const BnccCodigoRoute = BnccCodigoRouteImport.update({
  id: '/bncc/$codigo',
  path: '/bncc/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseChildIdRoute = AnamneseChildIdRouteImport.update({
  id: '/anamnese/$childId',
  path: '/anamnese/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const AjusteDificuldadesChildIdRoute =
  AjusteDificuldadesChildIdRouteImport.update({
    id: '/ajuste-dificuldades/$childId',
    path: '/ajuste-dificuldades/$childId',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaPortuguesEiIndexRoute =
  EscolaBrilhaPortuguesEiIndexRouteImport.update({
    id: '/escola-brilha/portugues-ei/',
    path: '/escola-brilha/portugues-ei/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaMatematicaEiIndexRoute =
  EscolaBrilhaMatematicaEiIndexRouteImport.update({
    id: '/escola-brilha/matematica-ei/',
    path: '/escola-brilha/matematica-ei/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaLerComAuroraIndexRoute =
  EscolaBrilhaLerComAuroraIndexRouteImport.update({
    id: '/escola-brilha/ler-com-aurora/',
    path: '/escola-brilha/ler-com-aurora/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaTrilhaInglesSerieRoute =
  EscolaBrilhaTrilhaInglesSerieRouteImport.update({
    id: '/escola-brilha/trilha-ingles/$serie',
    path: '/escola-brilha/trilha-ingles/$serie',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaLerComAuroraPainelRoute =
  EscolaBrilhaLerComAuroraPainelRouteImport.update({
    id: '/escola-brilha/ler-com-aurora/painel',
    path: '/escola-brilha/ler-com-aurora/painel',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaLerComAuroraDiagnosticoRoute =
  EscolaBrilhaLerComAuroraDiagnosticoRouteImport.update({
    id: '/escola-brilha/ler-com-aurora/diagnostico',
    path: '/escola-brilha/ler-com-aurora/diagnostico',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaLerComAuroraAulaRoute =
  EscolaBrilhaLerComAuroraAulaRouteImport.update({
    id: '/escola-brilha/ler-com-aurora/$aula',
    path: '/escola-brilha/ler-com-aurora/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaGeo9anoUnidadeRoute =
  EscolaBrilhaGeo9anoUnidadeRouteImport.update({
    id: '/escola-brilha/geo-9ano/$unidade',
    path: '/escola-brilha/geo-9ano/$unidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaGeo8anoUnidadeRoute =
  EscolaBrilhaGeo8anoUnidadeRouteImport.update({
    id: '/escola-brilha/geo-8ano/$unidade',
    path: '/escola-brilha/geo-8ano/$unidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaGeo7anoUnidadeRoute =
  EscolaBrilhaGeo7anoUnidadeRouteImport.update({
    id: '/escola-brilha/geo-7ano/$unidade',
    path: '/escola-brilha/geo-7ano/$unidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaGeo6anoUnidadeRoute =
  EscolaBrilhaGeo6anoUnidadeRouteImport.update({
    id: '/escola-brilha/geo-6ano/$unidade',
    path: '/escola-brilha/geo-6ano/$unidade',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaCursoSlugRoute = EscolaBrilhaCursoSlugRouteImport.update({
  id: '/escola-brilha/curso/$slug',
  path: '/escola-brilha/curso/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaBrilhaAtlasFinalCursoRoute =
  EscolaBrilhaAtlasFinalCursoRouteImport.update({
    id: '/escola-brilha/atlas-final/$curso',
    path: '/escola-brilha/atlas-final/$curso',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnamneseChildIdResultadoRoute =
  AnamneseChildIdResultadoRouteImport.update({
    id: '/resultado',
    path: '/resultado',
    getParentRoute: () => AnamneseChildIdRoute,
  } as any)
const AnamneseChildIdEscalasRoute = AnamneseChildIdEscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => AnamneseChildIdRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaTrilhaSerieDiscRoute =
  EscolaBrilhaTrilhaSerieDiscRouteImport.update({
    id: '/escola-brilha/trilha/$serie/$disc',
    path: '/escola-brilha/trilha/$serie/$disc',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaTrilhaFund2SerieDiscRoute =
  EscolaBrilhaTrilhaFund2SerieDiscRouteImport.update({
    id: '/escola-brilha/trilha-fund2/$serie/$disc',
    path: '/escola-brilha/trilha-fund2/$serie/$disc',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaPortuguesEiSerieAulaRoute =
  EscolaBrilhaPortuguesEiSerieAulaRouteImport.update({
    id: '/escola-brilha/portugues-ei/$serie/$aula',
    path: '/escola-brilha/portugues-ei/$serie/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaMatematicaEiSerieAulaRoute =
  EscolaBrilhaMatematicaEiSerieAulaRouteImport.update({
    id: '/escola-brilha/matematica-ei/$serie/$aula',
    path: '/escola-brilha/matematica-ei/$serie/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaInglesV1CursoAulaRoute =
  EscolaBrilhaInglesV1CursoAulaRouteImport.update({
    id: '/escola-brilha/ingles-v1/$curso/$aula',
    path: '/escola-brilha/ingles-v1/$curso/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaAulaV4CursoAulaRoute =
  EscolaBrilhaAulaV4CursoAulaRouteImport.update({
    id: '/escola-brilha/aula-v4/$curso/$aula',
    path: '/escola-brilha/aula-v4/$curso/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaAulaPtV4CursoAulaRoute =
  EscolaBrilhaAulaPtV4CursoAulaRouteImport.update({
    id: '/escola-brilha/aula-pt-v4/$curso/$aula',
    path: '/escola-brilha/aula-pt-v4/$curso/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaAulaGeoV1CursoAulaRoute =
  EscolaBrilhaAulaGeoV1CursoAulaRouteImport.update({
    id: '/escola-brilha/aula-geo-v1/$curso/$aula',
    path: '/escola-brilha/aula-geo-v1/$curso/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)
const EscolaBrilhaAulaArteV1CursoAulaRoute =
  EscolaBrilhaAulaArteV1CursoAulaRouteImport.update({
    id: '/escola-brilha/aula-arte-v1/$curso/$aula',
    path: '/escola-brilha/aula-arte-v1/$curso/$aula',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria-pedagogica': typeof AuditoriaPedagogicaRoute
  '/auth': typeof AuthRoute
  '/banco-midias': typeof BancoMidiasRoute
  '/biblioteca-alfa': typeof BibliotecaAlfaRoute
  '/biblioteca-pedagogica': typeof BibliotecaPedagogicaRoute
  '/brilha-vida': typeof BrilhaVidaRoute
  '/colecao-pip': typeof ColecaoPipRoute
  '/curadoria-aulas': typeof CuradoriaAulasRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/jornada-365': typeof Jornada365Route
  '/loja-mascotes': typeof LojaMascotesRoute
  '/mascotes': typeof MascotesRoute
  '/matriz-pedagogica': typeof MatrizPedagogicaRoute
  '/mcp': typeof McpRoute
  '/missao-prova': typeof MissaoProvaRoute
  '/missao-tarefa': typeof MissaoTarefaRoute
  '/missao-trabalho': typeof MissaoTrabalhoRoute
  '/neuro-treino': typeof NeuroTreinoRouteWithChildren
  '/painel-pais': typeof PainelPaisRoute
  '/perfil-aluno': typeof PerfilAlunoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRouteWithChildren
  '/bncc/$codigo': typeof BnccCodigoRoute
  '/escola-brilha/$codigo': typeof EscolaBrilhaCodigoRoute
  '/escola-brilha/professores': typeof EscolaBrilhaProfessoresRoute
  '/neuro-treino/$slug': typeof NeuroTreinoSlugRoute
  '/neuro-treino/configurar': typeof NeuroTreinoConfigurarRoute
  '/admin/': typeof AdminIndexRoute
  '/escola-brilha/': typeof EscolaBrilhaIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/anamnese/$childId/escalas': typeof AnamneseChildIdEscalasRoute
  '/anamnese/$childId/resultado': typeof AnamneseChildIdResultadoRoute
  '/escola-brilha/atlas-final/$curso': typeof EscolaBrilhaAtlasFinalCursoRoute
  '/escola-brilha/curso/$slug': typeof EscolaBrilhaCursoSlugRoute
  '/escola-brilha/geo-6ano/$unidade': typeof EscolaBrilhaGeo6anoUnidadeRoute
  '/escola-brilha/geo-7ano/$unidade': typeof EscolaBrilhaGeo7anoUnidadeRoute
  '/escola-brilha/geo-8ano/$unidade': typeof EscolaBrilhaGeo8anoUnidadeRoute
  '/escola-brilha/geo-9ano/$unidade': typeof EscolaBrilhaGeo9anoUnidadeRoute
  '/escola-brilha/ler-com-aurora/$aula': typeof EscolaBrilhaLerComAuroraAulaRoute
  '/escola-brilha/ler-com-aurora/diagnostico': typeof EscolaBrilhaLerComAuroraDiagnosticoRoute
  '/escola-brilha/ler-com-aurora/painel': typeof EscolaBrilhaLerComAuroraPainelRoute
  '/escola-brilha/trilha-ingles/$serie': typeof EscolaBrilhaTrilhaInglesSerieRoute
  '/escola-brilha/ler-com-aurora/': typeof EscolaBrilhaLerComAuroraIndexRoute
  '/escola-brilha/matematica-ei/': typeof EscolaBrilhaMatematicaEiIndexRoute
  '/escola-brilha/portugues-ei/': typeof EscolaBrilhaPortuguesEiIndexRoute
  '/escola-brilha/aula-arte-v1/$curso/$aula': typeof EscolaBrilhaAulaArteV1CursoAulaRoute
  '/escola-brilha/aula-geo-v1/$curso/$aula': typeof EscolaBrilhaAulaGeoV1CursoAulaRoute
  '/escola-brilha/aula-pt-v4/$curso/$aula': typeof EscolaBrilhaAulaPtV4CursoAulaRoute
  '/escola-brilha/aula-v4/$curso/$aula': typeof EscolaBrilhaAulaV4CursoAulaRoute
  '/escola-brilha/ingles-v1/$curso/$aula': typeof EscolaBrilhaInglesV1CursoAulaRoute
  '/escola-brilha/matematica-ei/$serie/$aula': typeof EscolaBrilhaMatematicaEiSerieAulaRoute
  '/escola-brilha/portugues-ei/$serie/$aula': typeof EscolaBrilhaPortuguesEiSerieAulaRoute
  '/escola-brilha/trilha-fund2/$serie/$disc': typeof EscolaBrilhaTrilhaFund2SerieDiscRoute
  '/escola-brilha/trilha/$serie/$disc': typeof EscolaBrilhaTrilhaSerieDiscRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria-pedagogica': typeof AuditoriaPedagogicaRoute
  '/auth': typeof AuthRoute
  '/banco-midias': typeof BancoMidiasRoute
  '/biblioteca-alfa': typeof BibliotecaAlfaRoute
  '/biblioteca-pedagogica': typeof BibliotecaPedagogicaRoute
  '/brilha-vida': typeof BrilhaVidaRoute
  '/colecao-pip': typeof ColecaoPipRoute
  '/curadoria-aulas': typeof CuradoriaAulasRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/jornada-365': typeof Jornada365Route
  '/loja-mascotes': typeof LojaMascotesRoute
  '/mascotes': typeof MascotesRoute
  '/matriz-pedagogica': typeof MatrizPedagogicaRoute
  '/mcp': typeof McpRoute
  '/missao-prova': typeof MissaoProvaRoute
  '/missao-tarefa': typeof MissaoTarefaRoute
  '/missao-trabalho': typeof MissaoTrabalhoRoute
  '/neuro-treino': typeof NeuroTreinoRouteWithChildren
  '/painel-pais': typeof PainelPaisRoute
  '/perfil-aluno': typeof PerfilAlunoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRouteWithChildren
  '/bncc/$codigo': typeof BnccCodigoRoute
  '/escola-brilha/$codigo': typeof EscolaBrilhaCodigoRoute
  '/escola-brilha/professores': typeof EscolaBrilhaProfessoresRoute
  '/neuro-treino/$slug': typeof NeuroTreinoSlugRoute
  '/neuro-treino/configurar': typeof NeuroTreinoConfigurarRoute
  '/admin': typeof AdminIndexRoute
  '/escola-brilha': typeof EscolaBrilhaIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/anamnese/$childId/escalas': typeof AnamneseChildIdEscalasRoute
  '/anamnese/$childId/resultado': typeof AnamneseChildIdResultadoRoute
  '/escola-brilha/atlas-final/$curso': typeof EscolaBrilhaAtlasFinalCursoRoute
  '/escola-brilha/curso/$slug': typeof EscolaBrilhaCursoSlugRoute
  '/escola-brilha/geo-6ano/$unidade': typeof EscolaBrilhaGeo6anoUnidadeRoute
  '/escola-brilha/geo-7ano/$unidade': typeof EscolaBrilhaGeo7anoUnidadeRoute
  '/escola-brilha/geo-8ano/$unidade': typeof EscolaBrilhaGeo8anoUnidadeRoute
  '/escola-brilha/geo-9ano/$unidade': typeof EscolaBrilhaGeo9anoUnidadeRoute
  '/escola-brilha/ler-com-aurora/$aula': typeof EscolaBrilhaLerComAuroraAulaRoute
  '/escola-brilha/ler-com-aurora/diagnostico': typeof EscolaBrilhaLerComAuroraDiagnosticoRoute
  '/escola-brilha/ler-com-aurora/painel': typeof EscolaBrilhaLerComAuroraPainelRoute
  '/escola-brilha/trilha-ingles/$serie': typeof EscolaBrilhaTrilhaInglesSerieRoute
  '/escola-brilha/ler-com-aurora': typeof EscolaBrilhaLerComAuroraIndexRoute
  '/escola-brilha/matematica-ei': typeof EscolaBrilhaMatematicaEiIndexRoute
  '/escola-brilha/portugues-ei': typeof EscolaBrilhaPortuguesEiIndexRoute
  '/escola-brilha/aula-arte-v1/$curso/$aula': typeof EscolaBrilhaAulaArteV1CursoAulaRoute
  '/escola-brilha/aula-geo-v1/$curso/$aula': typeof EscolaBrilhaAulaGeoV1CursoAulaRoute
  '/escola-brilha/aula-pt-v4/$curso/$aula': typeof EscolaBrilhaAulaPtV4CursoAulaRoute
  '/escola-brilha/aula-v4/$curso/$aula': typeof EscolaBrilhaAulaV4CursoAulaRoute
  '/escola-brilha/ingles-v1/$curso/$aula': typeof EscolaBrilhaInglesV1CursoAulaRoute
  '/escola-brilha/matematica-ei/$serie/$aula': typeof EscolaBrilhaMatematicaEiSerieAulaRoute
  '/escola-brilha/portugues-ei/$serie/$aula': typeof EscolaBrilhaPortuguesEiSerieAulaRoute
  '/escola-brilha/trilha-fund2/$serie/$disc': typeof EscolaBrilhaTrilhaFund2SerieDiscRoute
  '/escola-brilha/trilha/$serie/$disc': typeof EscolaBrilhaTrilhaSerieDiscRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/analytics': typeof AnalyticsRoute
  '/auditoria-pedagogica': typeof AuditoriaPedagogicaRoute
  '/auth': typeof AuthRoute
  '/banco-midias': typeof BancoMidiasRoute
  '/biblioteca-alfa': typeof BibliotecaAlfaRoute
  '/biblioteca-pedagogica': typeof BibliotecaPedagogicaRoute
  '/brilha-vida': typeof BrilhaVidaRoute
  '/colecao-pip': typeof ColecaoPipRoute
  '/curadoria-aulas': typeof CuradoriaAulasRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/jornada-365': typeof Jornada365Route
  '/loja-mascotes': typeof LojaMascotesRoute
  '/mascotes': typeof MascotesRoute
  '/matriz-pedagogica': typeof MatrizPedagogicaRoute
  '/mcp': typeof McpRoute
  '/missao-prova': typeof MissaoProvaRoute
  '/missao-tarefa': typeof MissaoTarefaRoute
  '/missao-trabalho': typeof MissaoTrabalhoRoute
  '/neuro-treino': typeof NeuroTreinoRouteWithChildren
  '/painel-pais': typeof PainelPaisRoute
  '/perfil-aluno': typeof PerfilAlunoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRouteWithChildren
  '/bncc/$codigo': typeof BnccCodigoRoute
  '/escola-brilha/$codigo': typeof EscolaBrilhaCodigoRoute
  '/escola-brilha/professores': typeof EscolaBrilhaProfessoresRoute
  '/neuro-treino/$slug': typeof NeuroTreinoSlugRoute
  '/neuro-treino/configurar': typeof NeuroTreinoConfigurarRoute
  '/admin/': typeof AdminIndexRoute
  '/escola-brilha/': typeof EscolaBrilhaIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/anamnese/$childId/escalas': typeof AnamneseChildIdEscalasRoute
  '/anamnese/$childId/resultado': typeof AnamneseChildIdResultadoRoute
  '/escola-brilha/atlas-final/$curso': typeof EscolaBrilhaAtlasFinalCursoRoute
  '/escola-brilha/curso/$slug': typeof EscolaBrilhaCursoSlugRoute
  '/escola-brilha/geo-6ano/$unidade': typeof EscolaBrilhaGeo6anoUnidadeRoute
  '/escola-brilha/geo-7ano/$unidade': typeof EscolaBrilhaGeo7anoUnidadeRoute
  '/escola-brilha/geo-8ano/$unidade': typeof EscolaBrilhaGeo8anoUnidadeRoute
  '/escola-brilha/geo-9ano/$unidade': typeof EscolaBrilhaGeo9anoUnidadeRoute
  '/escola-brilha/ler-com-aurora/$aula': typeof EscolaBrilhaLerComAuroraAulaRoute
  '/escola-brilha/ler-com-aurora/diagnostico': typeof EscolaBrilhaLerComAuroraDiagnosticoRoute
  '/escola-brilha/ler-com-aurora/painel': typeof EscolaBrilhaLerComAuroraPainelRoute
  '/escola-brilha/trilha-ingles/$serie': typeof EscolaBrilhaTrilhaInglesSerieRoute
  '/escola-brilha/ler-com-aurora/': typeof EscolaBrilhaLerComAuroraIndexRoute
  '/escola-brilha/matematica-ei/': typeof EscolaBrilhaMatematicaEiIndexRoute
  '/escola-brilha/portugues-ei/': typeof EscolaBrilhaPortuguesEiIndexRoute
  '/escola-brilha/aula-arte-v1/$curso/$aula': typeof EscolaBrilhaAulaArteV1CursoAulaRoute
  '/escola-brilha/aula-geo-v1/$curso/$aula': typeof EscolaBrilhaAulaGeoV1CursoAulaRoute
  '/escola-brilha/aula-pt-v4/$curso/$aula': typeof EscolaBrilhaAulaPtV4CursoAulaRoute
  '/escola-brilha/aula-v4/$curso/$aula': typeof EscolaBrilhaAulaV4CursoAulaRoute
  '/escola-brilha/ingles-v1/$curso/$aula': typeof EscolaBrilhaInglesV1CursoAulaRoute
  '/escola-brilha/matematica-ei/$serie/$aula': typeof EscolaBrilhaMatematicaEiSerieAulaRoute
  '/escola-brilha/portugues-ei/$serie/$aula': typeof EscolaBrilhaPortuguesEiSerieAulaRoute
  '/escola-brilha/trilha-fund2/$serie/$disc': typeof EscolaBrilhaTrilhaFund2SerieDiscRoute
  '/escola-brilha/trilha/$serie/$disc': typeof EscolaBrilhaTrilhaSerieDiscRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/alfabetizacao'
    | '/analytics'
    | '/auditoria-pedagogica'
    | '/auth'
    | '/banco-midias'
    | '/biblioteca-alfa'
    | '/biblioteca-pedagogica'
    | '/brilha-vida'
    | '/colecao-pip'
    | '/curadoria-aulas'
    | '/gerador-procedural'
    | '/jornada-365'
    | '/loja-mascotes'
    | '/mascotes'
    | '/matriz-pedagogica'
    | '/mcp'
    | '/missao-prova'
    | '/missao-tarefa'
    | '/missao-trabalho'
    | '/neuro-treino'
    | '/painel-pais'
    | '/perfil-aluno'
    | '/privacidade'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/termos'
    | '/trilhas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
    | '/bncc/$codigo'
    | '/escola-brilha/$codigo'
    | '/escola-brilha/professores'
    | '/neuro-treino/$slug'
    | '/neuro-treino/configurar'
    | '/admin/'
    | '/escola-brilha/'
    | '/.mcp/invoke-tool/$tool'
    | '/anamnese/$childId/escalas'
    | '/anamnese/$childId/resultado'
    | '/escola-brilha/atlas-final/$curso'
    | '/escola-brilha/curso/$slug'
    | '/escola-brilha/geo-6ano/$unidade'
    | '/escola-brilha/geo-7ano/$unidade'
    | '/escola-brilha/geo-8ano/$unidade'
    | '/escola-brilha/geo-9ano/$unidade'
    | '/escola-brilha/ler-com-aurora/$aula'
    | '/escola-brilha/ler-com-aurora/diagnostico'
    | '/escola-brilha/ler-com-aurora/painel'
    | '/escola-brilha/trilha-ingles/$serie'
    | '/escola-brilha/ler-com-aurora/'
    | '/escola-brilha/matematica-ei/'
    | '/escola-brilha/portugues-ei/'
    | '/escola-brilha/aula-arte-v1/$curso/$aula'
    | '/escola-brilha/aula-geo-v1/$curso/$aula'
    | '/escola-brilha/aula-pt-v4/$curso/$aula'
    | '/escola-brilha/aula-v4/$curso/$aula'
    | '/escola-brilha/ingles-v1/$curso/$aula'
    | '/escola-brilha/matematica-ei/$serie/$aula'
    | '/escola-brilha/portugues-ei/$serie/$aula'
    | '/escola-brilha/trilha-fund2/$serie/$disc'
    | '/escola-brilha/trilha/$serie/$disc'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alfabetizacao'
    | '/analytics'
    | '/auditoria-pedagogica'
    | '/auth'
    | '/banco-midias'
    | '/biblioteca-alfa'
    | '/biblioteca-pedagogica'
    | '/brilha-vida'
    | '/colecao-pip'
    | '/curadoria-aulas'
    | '/gerador-procedural'
    | '/jornada-365'
    | '/loja-mascotes'
    | '/mascotes'
    | '/matriz-pedagogica'
    | '/mcp'
    | '/missao-prova'
    | '/missao-tarefa'
    | '/missao-trabalho'
    | '/neuro-treino'
    | '/painel-pais'
    | '/perfil-aluno'
    | '/privacidade'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/termos'
    | '/trilhas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
    | '/bncc/$codigo'
    | '/escola-brilha/$codigo'
    | '/escola-brilha/professores'
    | '/neuro-treino/$slug'
    | '/neuro-treino/configurar'
    | '/admin'
    | '/escola-brilha'
    | '/.mcp/invoke-tool/$tool'
    | '/anamnese/$childId/escalas'
    | '/anamnese/$childId/resultado'
    | '/escola-brilha/atlas-final/$curso'
    | '/escola-brilha/curso/$slug'
    | '/escola-brilha/geo-6ano/$unidade'
    | '/escola-brilha/geo-7ano/$unidade'
    | '/escola-brilha/geo-8ano/$unidade'
    | '/escola-brilha/geo-9ano/$unidade'
    | '/escola-brilha/ler-com-aurora/$aula'
    | '/escola-brilha/ler-com-aurora/diagnostico'
    | '/escola-brilha/ler-com-aurora/painel'
    | '/escola-brilha/trilha-ingles/$serie'
    | '/escola-brilha/ler-com-aurora'
    | '/escola-brilha/matematica-ei'
    | '/escola-brilha/portugues-ei'
    | '/escola-brilha/aula-arte-v1/$curso/$aula'
    | '/escola-brilha/aula-geo-v1/$curso/$aula'
    | '/escola-brilha/aula-pt-v4/$curso/$aula'
    | '/escola-brilha/aula-v4/$curso/$aula'
    | '/escola-brilha/ingles-v1/$curso/$aula'
    | '/escola-brilha/matematica-ei/$serie/$aula'
    | '/escola-brilha/portugues-ei/$serie/$aula'
    | '/escola-brilha/trilha-fund2/$serie/$disc'
    | '/escola-brilha/trilha/$serie/$disc'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/alfabetizacao'
    | '/analytics'
    | '/auditoria-pedagogica'
    | '/auth'
    | '/banco-midias'
    | '/biblioteca-alfa'
    | '/biblioteca-pedagogica'
    | '/brilha-vida'
    | '/colecao-pip'
    | '/curadoria-aulas'
    | '/gerador-procedural'
    | '/jornada-365'
    | '/loja-mascotes'
    | '/mascotes'
    | '/matriz-pedagogica'
    | '/mcp'
    | '/missao-prova'
    | '/missao-tarefa'
    | '/missao-trabalho'
    | '/neuro-treino'
    | '/painel-pais'
    | '/perfil-aluno'
    | '/privacidade'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/termos'
    | '/trilhas'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
    | '/bncc/$codigo'
    | '/escola-brilha/$codigo'
    | '/escola-brilha/professores'
    | '/neuro-treino/$slug'
    | '/neuro-treino/configurar'
    | '/admin/'
    | '/escola-brilha/'
    | '/.mcp/invoke-tool/$tool'
    | '/anamnese/$childId/escalas'
    | '/anamnese/$childId/resultado'
    | '/escola-brilha/atlas-final/$curso'
    | '/escola-brilha/curso/$slug'
    | '/escola-brilha/geo-6ano/$unidade'
    | '/escola-brilha/geo-7ano/$unidade'
    | '/escola-brilha/geo-8ano/$unidade'
    | '/escola-brilha/geo-9ano/$unidade'
    | '/escola-brilha/ler-com-aurora/$aula'
    | '/escola-brilha/ler-com-aurora/diagnostico'
    | '/escola-brilha/ler-com-aurora/painel'
    | '/escola-brilha/trilha-ingles/$serie'
    | '/escola-brilha/ler-com-aurora/'
    | '/escola-brilha/matematica-ei/'
    | '/escola-brilha/portugues-ei/'
    | '/escola-brilha/aula-arte-v1/$curso/$aula'
    | '/escola-brilha/aula-geo-v1/$curso/$aula'
    | '/escola-brilha/aula-pt-v4/$curso/$aula'
    | '/escola-brilha/aula-v4/$curso/$aula'
    | '/escola-brilha/ingles-v1/$curso/$aula'
    | '/escola-brilha/matematica-ei/$serie/$aula'
    | '/escola-brilha/portugues-ei/$serie/$aula'
    | '/escola-brilha/trilha-fund2/$serie/$disc'
    | '/escola-brilha/trilha/$serie/$disc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AlfabetizacaoRoute: typeof AlfabetizacaoRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditoriaPedagogicaRoute: typeof AuditoriaPedagogicaRoute
  AuthRoute: typeof AuthRoute
  BancoMidiasRoute: typeof BancoMidiasRoute
  BibliotecaAlfaRoute: typeof BibliotecaAlfaRoute
  BibliotecaPedagogicaRoute: typeof BibliotecaPedagogicaRoute
  BrilhaVidaRoute: typeof BrilhaVidaRoute
  ColecaoPipRoute: typeof ColecaoPipRoute
  CuradoriaAulasRoute: typeof CuradoriaAulasRoute
  GeradorProceduralRoute: typeof GeradorProceduralRoute
  Jornada365Route: typeof Jornada365Route
  LojaMascotesRoute: typeof LojaMascotesRoute
  MascotesRoute: typeof MascotesRoute
  MatrizPedagogicaRoute: typeof MatrizPedagogicaRoute
  McpRoute: typeof McpRoute
  MissaoProvaRoute: typeof MissaoProvaRoute
  MissaoTarefaRoute: typeof MissaoTarefaRoute
  MissaoTrabalhoRoute: typeof MissaoTrabalhoRoute
  NeuroTreinoRoute: typeof NeuroTreinoRouteWithChildren
  PainelPaisRoute: typeof PainelPaisRoute
  PerfilAlunoRoute: typeof PerfilAlunoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgressaoRoute: typeof ProgressaoRoute
  ReforcoBrilhaRoute: typeof ReforcoBrilhaRoute
  RelatorioRoute: typeof RelatorioRoute
  RotinaRoute: typeof RotinaRoute
  TerapeutaBrilhaRoute: typeof TerapeutaBrilhaRoute
  TermosRoute: typeof TermosRoute
  TrilhasRoute: typeof TrilhasRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AjusteDificuldadesChildIdRoute: typeof AjusteDificuldadesChildIdRoute
  AnamneseChildIdRoute: typeof AnamneseChildIdRouteWithChildren
  BnccCodigoRoute: typeof BnccCodigoRoute
  EscolaBrilhaCodigoRoute: typeof EscolaBrilhaCodigoRoute
  EscolaBrilhaProfessoresRoute: typeof EscolaBrilhaProfessoresRoute
  EscolaBrilhaIndexRoute: typeof EscolaBrilhaIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  EscolaBrilhaAtlasFinalCursoRoute: typeof EscolaBrilhaAtlasFinalCursoRoute
  EscolaBrilhaCursoSlugRoute: typeof EscolaBrilhaCursoSlugRoute
  EscolaBrilhaGeo6anoUnidadeRoute: typeof EscolaBrilhaGeo6anoUnidadeRoute
  EscolaBrilhaGeo7anoUnidadeRoute: typeof EscolaBrilhaGeo7anoUnidadeRoute
  EscolaBrilhaGeo8anoUnidadeRoute: typeof EscolaBrilhaGeo8anoUnidadeRoute
  EscolaBrilhaGeo9anoUnidadeRoute: typeof EscolaBrilhaGeo9anoUnidadeRoute
  EscolaBrilhaLerComAuroraAulaRoute: typeof EscolaBrilhaLerComAuroraAulaRoute
  EscolaBrilhaLerComAuroraDiagnosticoRoute: typeof EscolaBrilhaLerComAuroraDiagnosticoRoute
  EscolaBrilhaLerComAuroraPainelRoute: typeof EscolaBrilhaLerComAuroraPainelRoute
  EscolaBrilhaTrilhaInglesSerieRoute: typeof EscolaBrilhaTrilhaInglesSerieRoute
  EscolaBrilhaLerComAuroraIndexRoute: typeof EscolaBrilhaLerComAuroraIndexRoute
  EscolaBrilhaMatematicaEiIndexRoute: typeof EscolaBrilhaMatematicaEiIndexRoute
  EscolaBrilhaPortuguesEiIndexRoute: typeof EscolaBrilhaPortuguesEiIndexRoute
  EscolaBrilhaAulaArteV1CursoAulaRoute: typeof EscolaBrilhaAulaArteV1CursoAulaRoute
  EscolaBrilhaAulaGeoV1CursoAulaRoute: typeof EscolaBrilhaAulaGeoV1CursoAulaRoute
  EscolaBrilhaAulaPtV4CursoAulaRoute: typeof EscolaBrilhaAulaPtV4CursoAulaRoute
  EscolaBrilhaAulaV4CursoAulaRoute: typeof EscolaBrilhaAulaV4CursoAulaRoute
  EscolaBrilhaInglesV1CursoAulaRoute: typeof EscolaBrilhaInglesV1CursoAulaRoute
  EscolaBrilhaMatematicaEiSerieAulaRoute: typeof EscolaBrilhaMatematicaEiSerieAulaRoute
  EscolaBrilhaPortuguesEiSerieAulaRoute: typeof EscolaBrilhaPortuguesEiSerieAulaRoute
  EscolaBrilhaTrilhaFund2SerieDiscRoute: typeof EscolaBrilhaTrilhaFund2SerieDiscRoute
  EscolaBrilhaTrilhaSerieDiscRoute: typeof EscolaBrilhaTrilhaSerieDiscRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapeuta-brilha': {
      id: '/terapeuta-brilha'
      path: '/terapeuta-brilha'
      fullPath: '/terapeuta-brilha'
      preLoaderRoute: typeof TerapeutaBrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina': {
      id: '/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof RotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforco-brilha': {
      id: '/reforco-brilha'
      path: '/reforco-brilha'
      fullPath: '/reforco-brilha'
      preLoaderRoute: typeof ReforcoBrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressao': {
      id: '/progressao'
      path: '/progressao'
      fullPath: '/progressao'
      preLoaderRoute: typeof ProgressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-aluno': {
      id: '/perfil-aluno'
      path: '/perfil-aluno'
      fullPath: '/perfil-aluno'
      preLoaderRoute: typeof PerfilAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-pais': {
      id: '/painel-pais'
      path: '/painel-pais'
      fullPath: '/painel-pais'
      preLoaderRoute: typeof PainelPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuro-treino': {
      id: '/neuro-treino'
      path: '/neuro-treino'
      fullPath: '/neuro-treino'
      preLoaderRoute: typeof NeuroTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-trabalho': {
      id: '/missao-trabalho'
      path: '/missao-trabalho'
      fullPath: '/missao-trabalho'
      preLoaderRoute: typeof MissaoTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-tarefa': {
      id: '/missao-tarefa'
      path: '/missao-tarefa'
      fullPath: '/missao-tarefa'
      preLoaderRoute: typeof MissaoTarefaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-prova': {
      id: '/missao-prova'
      path: '/missao-prova'
      fullPath: '/missao-prova'
      preLoaderRoute: typeof MissaoProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matriz-pedagogica': {
      id: '/matriz-pedagogica'
      path: '/matriz-pedagogica'
      fullPath: '/matriz-pedagogica'
      preLoaderRoute: typeof MatrizPedagogicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mascotes': {
      id: '/mascotes'
      path: '/mascotes'
      fullPath: '/mascotes'
      preLoaderRoute: typeof MascotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja-mascotes': {
      id: '/loja-mascotes'
      path: '/loja-mascotes'
      fullPath: '/loja-mascotes'
      preLoaderRoute: typeof LojaMascotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada-365': {
      id: '/jornada-365'
      path: '/jornada-365'
      fullPath: '/jornada-365'
      preLoaderRoute: typeof Jornada365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-procedural': {
      id: '/gerador-procedural'
      path: '/gerador-procedural'
      fullPath: '/gerador-procedural'
      preLoaderRoute: typeof GeradorProceduralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curadoria-aulas': {
      id: '/curadoria-aulas'
      path: '/curadoria-aulas'
      fullPath: '/curadoria-aulas'
      preLoaderRoute: typeof CuradoriaAulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao-pip': {
      id: '/colecao-pip'
      path: '/colecao-pip'
      fullPath: '/colecao-pip'
      preLoaderRoute: typeof ColecaoPipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilha-vida': {
      id: '/brilha-vida'
      path: '/brilha-vida'
      fullPath: '/brilha-vida'
      preLoaderRoute: typeof BrilhaVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca-pedagogica': {
      id: '/biblioteca-pedagogica'
      path: '/biblioteca-pedagogica'
      fullPath: '/biblioteca-pedagogica'
      preLoaderRoute: typeof BibliotecaPedagogicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca-alfa': {
      id: '/biblioteca-alfa'
      path: '/biblioteca-alfa'
      fullPath: '/biblioteca-alfa'
      preLoaderRoute: typeof BibliotecaAlfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banco-midias': {
      id: '/banco-midias'
      path: '/banco-midias'
      fullPath: '/banco-midias'
      preLoaderRoute: typeof BancoMidiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria-pedagogica': {
      id: '/auditoria-pedagogica'
      path: '/auditoria-pedagogica'
      fullPath: '/auditoria-pedagogica'
      preLoaderRoute: typeof AuditoriaPedagogicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabetizacao': {
      id: '/alfabetizacao'
      path: '/alfabetizacao'
      fullPath: '/alfabetizacao'
      preLoaderRoute: typeof AlfabetizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/': {
      id: '/escola-brilha/'
      path: '/escola-brilha'
      fullPath: '/escola-brilha/'
      preLoaderRoute: typeof EscolaBrilhaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/neuro-treino/configurar': {
      id: '/neuro-treino/configurar'
      path: '/configurar'
      fullPath: '/neuro-treino/configurar'
      preLoaderRoute: typeof NeuroTreinoConfigurarRouteImport
      parentRoute: typeof NeuroTreinoRoute
    }
    '/neuro-treino/$slug': {
      id: '/neuro-treino/$slug'
      path: '/$slug'
      fullPath: '/neuro-treino/$slug'
      preLoaderRoute: typeof NeuroTreinoSlugRouteImport
      parentRoute: typeof NeuroTreinoRoute
    }
    '/escola-brilha/professores': {
      id: '/escola-brilha/professores'
      path: '/escola-brilha/professores'
      fullPath: '/escola-brilha/professores'
      preLoaderRoute: typeof EscolaBrilhaProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/$codigo': {
      id: '/escola-brilha/$codigo'
      path: '/escola-brilha/$codigo'
      fullPath: '/escola-brilha/$codigo'
      preLoaderRoute: typeof EscolaBrilhaCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bncc/$codigo': {
      id: '/bncc/$codigo'
      path: '/bncc/$codigo'
      fullPath: '/bncc/$codigo'
      preLoaderRoute: typeof BnccCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese/$childId': {
      id: '/anamnese/$childId'
      path: '/anamnese/$childId'
      fullPath: '/anamnese/$childId'
      preLoaderRoute: typeof AnamneseChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuste-dificuldades/$childId': {
      id: '/ajuste-dificuldades/$childId'
      path: '/ajuste-dificuldades/$childId'
      fullPath: '/ajuste-dificuldades/$childId'
      preLoaderRoute: typeof AjusteDificuldadesChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/portugues-ei/': {
      id: '/escola-brilha/portugues-ei/'
      path: '/escola-brilha/portugues-ei'
      fullPath: '/escola-brilha/portugues-ei/'
      preLoaderRoute: typeof EscolaBrilhaPortuguesEiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/matematica-ei/': {
      id: '/escola-brilha/matematica-ei/'
      path: '/escola-brilha/matematica-ei'
      fullPath: '/escola-brilha/matematica-ei/'
      preLoaderRoute: typeof EscolaBrilhaMatematicaEiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/ler-com-aurora/': {
      id: '/escola-brilha/ler-com-aurora/'
      path: '/escola-brilha/ler-com-aurora'
      fullPath: '/escola-brilha/ler-com-aurora/'
      preLoaderRoute: typeof EscolaBrilhaLerComAuroraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/trilha-ingles/$serie': {
      id: '/escola-brilha/trilha-ingles/$serie'
      path: '/escola-brilha/trilha-ingles/$serie'
      fullPath: '/escola-brilha/trilha-ingles/$serie'
      preLoaderRoute: typeof EscolaBrilhaTrilhaInglesSerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/ler-com-aurora/painel': {
      id: '/escola-brilha/ler-com-aurora/painel'
      path: '/escola-brilha/ler-com-aurora/painel'
      fullPath: '/escola-brilha/ler-com-aurora/painel'
      preLoaderRoute: typeof EscolaBrilhaLerComAuroraPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/ler-com-aurora/diagnostico': {
      id: '/escola-brilha/ler-com-aurora/diagnostico'
      path: '/escola-brilha/ler-com-aurora/diagnostico'
      fullPath: '/escola-brilha/ler-com-aurora/diagnostico'
      preLoaderRoute: typeof EscolaBrilhaLerComAuroraDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/ler-com-aurora/$aula': {
      id: '/escola-brilha/ler-com-aurora/$aula'
      path: '/escola-brilha/ler-com-aurora/$aula'
      fullPath: '/escola-brilha/ler-com-aurora/$aula'
      preLoaderRoute: typeof EscolaBrilhaLerComAuroraAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/geo-9ano/$unidade': {
      id: '/escola-brilha/geo-9ano/$unidade'
      path: '/escola-brilha/geo-9ano/$unidade'
      fullPath: '/escola-brilha/geo-9ano/$unidade'
      preLoaderRoute: typeof EscolaBrilhaGeo9anoUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/geo-8ano/$unidade': {
      id: '/escola-brilha/geo-8ano/$unidade'
      path: '/escola-brilha/geo-8ano/$unidade'
      fullPath: '/escola-brilha/geo-8ano/$unidade'
      preLoaderRoute: typeof EscolaBrilhaGeo8anoUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/geo-7ano/$unidade': {
      id: '/escola-brilha/geo-7ano/$unidade'
      path: '/escola-brilha/geo-7ano/$unidade'
      fullPath: '/escola-brilha/geo-7ano/$unidade'
      preLoaderRoute: typeof EscolaBrilhaGeo7anoUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/geo-6ano/$unidade': {
      id: '/escola-brilha/geo-6ano/$unidade'
      path: '/escola-brilha/geo-6ano/$unidade'
      fullPath: '/escola-brilha/geo-6ano/$unidade'
      preLoaderRoute: typeof EscolaBrilhaGeo6anoUnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/curso/$slug': {
      id: '/escola-brilha/curso/$slug'
      path: '/escola-brilha/curso/$slug'
      fullPath: '/escola-brilha/curso/$slug'
      preLoaderRoute: typeof EscolaBrilhaCursoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/atlas-final/$curso': {
      id: '/escola-brilha/atlas-final/$curso'
      path: '/escola-brilha/atlas-final/$curso'
      fullPath: '/escola-brilha/atlas-final/$curso'
      preLoaderRoute: typeof EscolaBrilhaAtlasFinalCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese/$childId/resultado': {
      id: '/anamnese/$childId/resultado'
      path: '/resultado'
      fullPath: '/anamnese/$childId/resultado'
      preLoaderRoute: typeof AnamneseChildIdResultadoRouteImport
      parentRoute: typeof AnamneseChildIdRoute
    }
    '/anamnese/$childId/escalas': {
      id: '/anamnese/$childId/escalas'
      path: '/escalas'
      fullPath: '/anamnese/$childId/escalas'
      preLoaderRoute: typeof AnamneseChildIdEscalasRouteImport
      parentRoute: typeof AnamneseChildIdRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/trilha/$serie/$disc': {
      id: '/escola-brilha/trilha/$serie/$disc'
      path: '/escola-brilha/trilha/$serie/$disc'
      fullPath: '/escola-brilha/trilha/$serie/$disc'
      preLoaderRoute: typeof EscolaBrilhaTrilhaSerieDiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/trilha-fund2/$serie/$disc': {
      id: '/escola-brilha/trilha-fund2/$serie/$disc'
      path: '/escola-brilha/trilha-fund2/$serie/$disc'
      fullPath: '/escola-brilha/trilha-fund2/$serie/$disc'
      preLoaderRoute: typeof EscolaBrilhaTrilhaFund2SerieDiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/portugues-ei/$serie/$aula': {
      id: '/escola-brilha/portugues-ei/$serie/$aula'
      path: '/escola-brilha/portugues-ei/$serie/$aula'
      fullPath: '/escola-brilha/portugues-ei/$serie/$aula'
      preLoaderRoute: typeof EscolaBrilhaPortuguesEiSerieAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/matematica-ei/$serie/$aula': {
      id: '/escola-brilha/matematica-ei/$serie/$aula'
      path: '/escola-brilha/matematica-ei/$serie/$aula'
      fullPath: '/escola-brilha/matematica-ei/$serie/$aula'
      preLoaderRoute: typeof EscolaBrilhaMatematicaEiSerieAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/ingles-v1/$curso/$aula': {
      id: '/escola-brilha/ingles-v1/$curso/$aula'
      path: '/escola-brilha/ingles-v1/$curso/$aula'
      fullPath: '/escola-brilha/ingles-v1/$curso/$aula'
      preLoaderRoute: typeof EscolaBrilhaInglesV1CursoAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/aula-v4/$curso/$aula': {
      id: '/escola-brilha/aula-v4/$curso/$aula'
      path: '/escola-brilha/aula-v4/$curso/$aula'
      fullPath: '/escola-brilha/aula-v4/$curso/$aula'
      preLoaderRoute: typeof EscolaBrilhaAulaV4CursoAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/aula-pt-v4/$curso/$aula': {
      id: '/escola-brilha/aula-pt-v4/$curso/$aula'
      path: '/escola-brilha/aula-pt-v4/$curso/$aula'
      fullPath: '/escola-brilha/aula-pt-v4/$curso/$aula'
      preLoaderRoute: typeof EscolaBrilhaAulaPtV4CursoAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/aula-geo-v1/$curso/$aula': {
      id: '/escola-brilha/aula-geo-v1/$curso/$aula'
      path: '/escola-brilha/aula-geo-v1/$curso/$aula'
      fullPath: '/escola-brilha/aula-geo-v1/$curso/$aula'
      preLoaderRoute: typeof EscolaBrilhaAulaGeoV1CursoAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha/aula-arte-v1/$curso/$aula': {
      id: '/escola-brilha/aula-arte-v1/$curso/$aula'
      path: '/escola-brilha/aula-arte-v1/$curso/$aula'
      fullPath: '/escola-brilha/aula-arte-v1/$curso/$aula'
      preLoaderRoute: typeof EscolaBrilhaAulaArteV1CursoAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface NeuroTreinoRouteChildren {
  NeuroTreinoSlugRoute: typeof NeuroTreinoSlugRoute
  NeuroTreinoConfigurarRoute: typeof NeuroTreinoConfigurarRoute
}

const NeuroTreinoRouteChildren: NeuroTreinoRouteChildren = {
  NeuroTreinoSlugRoute: NeuroTreinoSlugRoute,
  NeuroTreinoConfigurarRoute: NeuroTreinoConfigurarRoute,
}

const NeuroTreinoRouteWithChildren = NeuroTreinoRoute._addFileChildren(
  NeuroTreinoRouteChildren,
)

interface AnamneseChildIdRouteChildren {
  AnamneseChildIdEscalasRoute: typeof AnamneseChildIdEscalasRoute
  AnamneseChildIdResultadoRoute: typeof AnamneseChildIdResultadoRoute
}

const AnamneseChildIdRouteChildren: AnamneseChildIdRouteChildren = {
  AnamneseChildIdEscalasRoute: AnamneseChildIdEscalasRoute,
  AnamneseChildIdResultadoRoute: AnamneseChildIdResultadoRoute,
}

const AnamneseChildIdRouteWithChildren = AnamneseChildIdRoute._addFileChildren(
  AnamneseChildIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AlfabetizacaoRoute: AlfabetizacaoRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditoriaPedagogicaRoute: AuditoriaPedagogicaRoute,
  AuthRoute: AuthRoute,
  BancoMidiasRoute: BancoMidiasRoute,
  BibliotecaAlfaRoute: BibliotecaAlfaRoute,
  BibliotecaPedagogicaRoute: BibliotecaPedagogicaRoute,
  BrilhaVidaRoute: BrilhaVidaRoute,
  ColecaoPipRoute: ColecaoPipRoute,
  CuradoriaAulasRoute: CuradoriaAulasRoute,
  GeradorProceduralRoute: GeradorProceduralRoute,
  Jornada365Route: Jornada365Route,
  LojaMascotesRoute: LojaMascotesRoute,
  MascotesRoute: MascotesRoute,
  MatrizPedagogicaRoute: MatrizPedagogicaRoute,
  McpRoute: McpRoute,
  MissaoProvaRoute: MissaoProvaRoute,
  MissaoTarefaRoute: MissaoTarefaRoute,
  MissaoTrabalhoRoute: MissaoTrabalhoRoute,
  NeuroTreinoRoute: NeuroTreinoRouteWithChildren,
  PainelPaisRoute: PainelPaisRoute,
  PerfilAlunoRoute: PerfilAlunoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgressaoRoute: ProgressaoRoute,
  ReforcoBrilhaRoute: ReforcoBrilhaRoute,
  RelatorioRoute: RelatorioRoute,
  RotinaRoute: RotinaRoute,
  TerapeutaBrilhaRoute: TerapeutaBrilhaRoute,
  TermosRoute: TermosRoute,
  TrilhasRoute: TrilhasRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AjusteDificuldadesChildIdRoute: AjusteDificuldadesChildIdRoute,
  AnamneseChildIdRoute: AnamneseChildIdRouteWithChildren,
  BnccCodigoRoute: BnccCodigoRoute,
  EscolaBrilhaCodigoRoute: EscolaBrilhaCodigoRoute,
  EscolaBrilhaProfessoresRoute: EscolaBrilhaProfessoresRoute,
  EscolaBrilhaIndexRoute: EscolaBrilhaIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  EscolaBrilhaAtlasFinalCursoRoute: EscolaBrilhaAtlasFinalCursoRoute,
  EscolaBrilhaCursoSlugRoute: EscolaBrilhaCursoSlugRoute,
  EscolaBrilhaGeo6anoUnidadeRoute: EscolaBrilhaGeo6anoUnidadeRoute,
  EscolaBrilhaGeo7anoUnidadeRoute: EscolaBrilhaGeo7anoUnidadeRoute,
  EscolaBrilhaGeo8anoUnidadeRoute: EscolaBrilhaGeo8anoUnidadeRoute,
  EscolaBrilhaGeo9anoUnidadeRoute: EscolaBrilhaGeo9anoUnidadeRoute,
  EscolaBrilhaLerComAuroraAulaRoute: EscolaBrilhaLerComAuroraAulaRoute,
  EscolaBrilhaLerComAuroraDiagnosticoRoute:
    EscolaBrilhaLerComAuroraDiagnosticoRoute,
  EscolaBrilhaLerComAuroraPainelRoute: EscolaBrilhaLerComAuroraPainelRoute,
  EscolaBrilhaTrilhaInglesSerieRoute: EscolaBrilhaTrilhaInglesSerieRoute,
  EscolaBrilhaLerComAuroraIndexRoute: EscolaBrilhaLerComAuroraIndexRoute,
  EscolaBrilhaMatematicaEiIndexRoute: EscolaBrilhaMatematicaEiIndexRoute,
  EscolaBrilhaPortuguesEiIndexRoute: EscolaBrilhaPortuguesEiIndexRoute,
  EscolaBrilhaAulaArteV1CursoAulaRoute: EscolaBrilhaAulaArteV1CursoAulaRoute,
  EscolaBrilhaAulaGeoV1CursoAulaRoute: EscolaBrilhaAulaGeoV1CursoAulaRoute,
  EscolaBrilhaAulaPtV4CursoAulaRoute: EscolaBrilhaAulaPtV4CursoAulaRoute,
  EscolaBrilhaAulaV4CursoAulaRoute: EscolaBrilhaAulaV4CursoAulaRoute,
  EscolaBrilhaInglesV1CursoAulaRoute: EscolaBrilhaInglesV1CursoAulaRoute,
  EscolaBrilhaMatematicaEiSerieAulaRoute:
    EscolaBrilhaMatematicaEiSerieAulaRoute,
  EscolaBrilhaPortuguesEiSerieAulaRoute: EscolaBrilhaPortuguesEiSerieAulaRoute,
  EscolaBrilhaTrilhaFund2SerieDiscRoute: EscolaBrilhaTrilhaFund2SerieDiscRoute,
  EscolaBrilhaTrilhaSerieDiscRoute: EscolaBrilhaTrilhaSerieDiscRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
