/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerapeutaBrilhaRouteImport } from './routes/terapeuta-brilha'
import { Route as RotinaRouteImport } from './routes/rotina'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as ReforcoBrilhaRouteImport } from './routes/reforco-brilha'
import { Route as ProgressaoRouteImport } from './routes/progressao'
import { Route as ProfessorIaRouteImport } from './routes/professor-ia'
import { Route as Pre2RouteImport } from './routes/pre-2'
import { Route as PainelPaisRouteImport } from './routes/painel-pais'
import { Route as NeuroTreinoRouteImport } from './routes/neuro-treino'
import { Route as Jornada365RouteImport } from './routes/jornada-365'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as GeradorProceduralRouteImport } from './routes/gerador-procedural'
import { Route as EscolaBrilhaRouteImport } from './routes/escola-brilha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmigoVirtualRouteImport } from './routes/amigo-virtual'
import { Route as AlfabetizacaoRouteImport } from './routes/alfabetizacao'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnamneseChildIdRouteImport } from './routes/anamnese.$childId'
import { Route as AjusteDificuldadesChildIdRouteImport } from './routes/ajuste-dificuldades.$childId'

const TerapeutaBrilhaRoute = TerapeutaBrilhaRouteImport.update({
  id: '/terapeuta-brilha',
  path: '/terapeuta-brilha',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinaRoute = RotinaRouteImport.update({
  id: '/rotina',
  path: '/rotina',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReforcoBrilhaRoute = ReforcoBrilhaRouteImport.update({
  id: '/reforco-brilha',
  path: '/reforco-brilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressaoRoute = ProgressaoRouteImport.update({
  id: '/progressao',
  path: '/progressao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIaRoute = ProfessorIaRouteImport.update({
  id: '/professor-ia',
  path: '/professor-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const Pre2Route = Pre2RouteImport.update({
  id: '/pre-2',
  path: '/pre-2',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelPaisRoute = PainelPaisRouteImport.update({
  id: '/painel-pais',
  path: '/painel-pais',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuroTreinoRoute = NeuroTreinoRouteImport.update({
  id: '/neuro-treino',
  path: '/neuro-treino',
  getParentRoute: () => rootRouteImport,
} as any)
const Jornada365Route = Jornada365RouteImport.update({
  id: '/jornada-365',
  path: '/jornada-365',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorProceduralRoute = GeradorProceduralRouteImport.update({
  id: '/gerador-procedural',
  path: '/gerador-procedural',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaBrilhaRoute = EscolaBrilhaRouteImport.update({
  id: '/escola-brilha',
  path: '/escola-brilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigoVirtualRoute = AmigoVirtualRouteImport.update({
  id: '/amigo-virtual',
  path: '/amigo-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const AlfabetizacaoRoute = AlfabetizacaoRouteImport.update({
  id: '/alfabetizacao',
  path: '/alfabetizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseChildIdRoute = AnamneseChildIdRouteImport.update({
  id: '/anamnese/$childId',
  path: '/anamnese/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const AjusteDificuldadesChildIdRoute =
  AjusteDificuldadesChildIdRouteImport.update({
    id: '/ajuste-dificuldades/$childId',
    path: '/ajuste-dificuldades/$childId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/amigo-virtual': typeof AmigoVirtualRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/escola-brilha': typeof EscolaBrilhaRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/historias': typeof HistoriasRoute
  '/jornada-365': typeof Jornada365Route
  '/neuro-treino': typeof NeuroTreinoRoute
  '/painel-pais': typeof PainelPaisRoute
  '/pre-2': typeof Pre2Route
  '/professor-ia': typeof ProfessorIaRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/amigo-virtual': typeof AmigoVirtualRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/escola-brilha': typeof EscolaBrilhaRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/historias': typeof HistoriasRoute
  '/jornada-365': typeof Jornada365Route
  '/neuro-treino': typeof NeuroTreinoRoute
  '/painel-pais': typeof PainelPaisRoute
  '/pre-2': typeof Pre2Route
  '/professor-ia': typeof ProfessorIaRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alfabetizacao': typeof AlfabetizacaoRoute
  '/amigo-virtual': typeof AmigoVirtualRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/escola-brilha': typeof EscolaBrilhaRoute
  '/gerador-procedural': typeof GeradorProceduralRoute
  '/historias': typeof HistoriasRoute
  '/jornada-365': typeof Jornada365Route
  '/neuro-treino': typeof NeuroTreinoRoute
  '/painel-pais': typeof PainelPaisRoute
  '/pre-2': typeof Pre2Route
  '/professor-ia': typeof ProfessorIaRoute
  '/progressao': typeof ProgressaoRoute
  '/reforco-brilha': typeof ReforcoBrilhaRoute
  '/relatorio': typeof RelatorioRoute
  '/rotina': typeof RotinaRoute
  '/terapeuta-brilha': typeof TerapeutaBrilhaRoute
  '/ajuste-dificuldades/$childId': typeof AjusteDificuldadesChildIdRoute
  '/anamnese/$childId': typeof AnamneseChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alfabetizacao'
    | '/amigo-virtual'
    | '/analytics'
    | '/auth'
    | '/escola-brilha'
    | '/gerador-procedural'
    | '/historias'
    | '/jornada-365'
    | '/neuro-treino'
    | '/painel-pais'
    | '/pre-2'
    | '/professor-ia'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alfabetizacao'
    | '/amigo-virtual'
    | '/analytics'
    | '/auth'
    | '/escola-brilha'
    | '/gerador-procedural'
    | '/historias'
    | '/jornada-365'
    | '/neuro-treino'
    | '/painel-pais'
    | '/pre-2'
    | '/professor-ia'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alfabetizacao'
    | '/amigo-virtual'
    | '/analytics'
    | '/auth'
    | '/escola-brilha'
    | '/gerador-procedural'
    | '/historias'
    | '/jornada-365'
    | '/neuro-treino'
    | '/painel-pais'
    | '/pre-2'
    | '/professor-ia'
    | '/progressao'
    | '/reforco-brilha'
    | '/relatorio'
    | '/rotina'
    | '/terapeuta-brilha'
    | '/ajuste-dificuldades/$childId'
    | '/anamnese/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlfabetizacaoRoute: typeof AlfabetizacaoRoute
  AmigoVirtualRoute: typeof AmigoVirtualRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  EscolaBrilhaRoute: typeof EscolaBrilhaRoute
  GeradorProceduralRoute: typeof GeradorProceduralRoute
  HistoriasRoute: typeof HistoriasRoute
  Jornada365Route: typeof Jornada365Route
  NeuroTreinoRoute: typeof NeuroTreinoRoute
  PainelPaisRoute: typeof PainelPaisRoute
  Pre2Route: typeof Pre2Route
  ProfessorIaRoute: typeof ProfessorIaRoute
  ProgressaoRoute: typeof ProgressaoRoute
  ReforcoBrilhaRoute: typeof ReforcoBrilhaRoute
  RelatorioRoute: typeof RelatorioRoute
  RotinaRoute: typeof RotinaRoute
  TerapeutaBrilhaRoute: typeof TerapeutaBrilhaRoute
  AjusteDificuldadesChildIdRoute: typeof AjusteDificuldadesChildIdRoute
  AnamneseChildIdRoute: typeof AnamneseChildIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terapeuta-brilha': {
      id: '/terapeuta-brilha'
      path: '/terapeuta-brilha'
      fullPath: '/terapeuta-brilha'
      preLoaderRoute: typeof TerapeutaBrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotina': {
      id: '/rotina'
      path: '/rotina'
      fullPath: '/rotina'
      preLoaderRoute: typeof RotinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforco-brilha': {
      id: '/reforco-brilha'
      path: '/reforco-brilha'
      fullPath: '/reforco-brilha'
      preLoaderRoute: typeof ReforcoBrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressao': {
      id: '/progressao'
      path: '/progressao'
      fullPath: '/progressao'
      preLoaderRoute: typeof ProgressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor-ia': {
      id: '/professor-ia'
      path: '/professor-ia'
      fullPath: '/professor-ia'
      preLoaderRoute: typeof ProfessorIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-2': {
      id: '/pre-2'
      path: '/pre-2'
      fullPath: '/pre-2'
      preLoaderRoute: typeof Pre2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel-pais': {
      id: '/painel-pais'
      path: '/painel-pais'
      fullPath: '/painel-pais'
      preLoaderRoute: typeof PainelPaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuro-treino': {
      id: '/neuro-treino'
      path: '/neuro-treino'
      fullPath: '/neuro-treino'
      preLoaderRoute: typeof NeuroTreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada-365': {
      id: '/jornada-365'
      path: '/jornada-365'
      fullPath: '/jornada-365'
      preLoaderRoute: typeof Jornada365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador-procedural': {
      id: '/gerador-procedural'
      path: '/gerador-procedural'
      fullPath: '/gerador-procedural'
      preLoaderRoute: typeof GeradorProceduralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola-brilha': {
      id: '/escola-brilha'
      path: '/escola-brilha'
      fullPath: '/escola-brilha'
      preLoaderRoute: typeof EscolaBrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigo-virtual': {
      id: '/amigo-virtual'
      path: '/amigo-virtual'
      fullPath: '/amigo-virtual'
      preLoaderRoute: typeof AmigoVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alfabetizacao': {
      id: '/alfabetizacao'
      path: '/alfabetizacao'
      fullPath: '/alfabetizacao'
      preLoaderRoute: typeof AlfabetizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese/$childId': {
      id: '/anamnese/$childId'
      path: '/anamnese/$childId'
      fullPath: '/anamnese/$childId'
      preLoaderRoute: typeof AnamneseChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuste-dificuldades/$childId': {
      id: '/ajuste-dificuldades/$childId'
      path: '/ajuste-dificuldades/$childId'
      fullPath: '/ajuste-dificuldades/$childId'
      preLoaderRoute: typeof AjusteDificuldadesChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlfabetizacaoRoute: AlfabetizacaoRoute,
  AmigoVirtualRoute: AmigoVirtualRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  EscolaBrilhaRoute: EscolaBrilhaRoute,
  GeradorProceduralRoute: GeradorProceduralRoute,
  HistoriasRoute: HistoriasRoute,
  Jornada365Route: Jornada365Route,
  NeuroTreinoRoute: NeuroTreinoRoute,
  PainelPaisRoute: PainelPaisRoute,
  Pre2Route: Pre2Route,
  ProfessorIaRoute: ProfessorIaRoute,
  ProgressaoRoute: ProgressaoRoute,
  ReforcoBrilhaRoute: ReforcoBrilhaRoute,
  RelatorioRoute: RelatorioRoute,
  RotinaRoute: RotinaRoute,
  TerapeutaBrilhaRoute: TerapeutaBrilhaRoute,
  AjusteDificuldadesChildIdRoute: AjusteDificuldadesChildIdRoute,
  AnamneseChildIdRoute: AnamneseChildIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
