-- Biblioteca Inclusiva · Ciências do 2º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF02CI01','src/escola-brilha/curso-v4/ciencias-2ano/unidade-1/aula-01-metodo-cientista.ts','Materiais dos objetos','Identificar materiais usados em objetos cotidianos, comparar seus usos no presente e no passado.','Separe objetos ou fotos por material e compare um objeto atual com outro usado antigamente.','Escolha um objeto, nomeie o material e explique uma mudança em seu uso ou fabricação.','Identificar material e apresentar comparação temporal coerente com a evidência.'),
('EF02CI02','src/escola-brilha/curso-v4/ciencias-2ano/unidade-2/aula-01-materiais.ts','Propriedades e escolha de materiais','Relacionar propriedades como flexibilidade, transparência e resistência à finalidade dos objetos.','Teste apenas objetos seguros e registre qual dobra, deixa passar luz ou resiste à pressão leve.','Escolha o melhor material para um objeto e justifique pela propriedade necessária.','Aceitar soluções diferentes quando propriedade e uso estiverem bem relacionados.'),
('EF02CI03','src/escola-brilha/curso-v4/ciencias-2ano/unidade-3/aula-01-seguranca.ts','Prevenção de acidentes domésticos','Reconhecer situações de risco e propor atitudes seguras, buscando ajuda de um adulto.','Classifique cenas em segura, precisa de cuidado e chamar um adulto, sem encenar o risco.','Escolha uma cena e explique como torná-la mais segura.','A ação deve afastar-se do risco, avisar um adulto e não experimentar a situação perigosa.'),
('EF02CI04','src/escola-brilha/curso-v4/ciencias-2ano/unidade-4/aula-01-seres-vivos.ts','Características de plantas e animais','Descrever características de plantas e animais do cotidiano e relacioná-las ao ambiente em que vivem.','Compare dois seres vivos por cobertura, partes, movimento, alimentação ou ambiente.','Registre um ser vivo, duas características e uma relação com seu ambiente.','Características observáveis e relação coerente; evitar definir seres vivos apenas pelo movimento.'),
('EF02CI05','src/escola-brilha/curso-v4/ciencias-2ano/unidade-5/aula-01-agua-luz.ts','Água e luz para as plantas','Investigar a importância da água e da luz para a manutenção da vida das plantas.','Compare plantas semelhantes sob condições planejadas pelo adulto, alterando somente água ou luz e registrando ao longo dos dias.','Observe registros e conclua qual condição mudou e qual efeito foi percebido.','Conclusão limitada aos dados observados; não arrancar ou ingerir plantas e não usar espécies desconhecidas.'),
('EF02CI06','src/escola-brilha/curso-v4/ciencias-2ano/unidade-6/aula-01-partes-planta.ts','Partes da planta e suas funções','Identificar raiz, caule, folhas, flores e frutos e relacionar cada parte a funções básicas.','Monte um diagrama de planta e ligue partes a absorção, sustentação, trocas com o ambiente e reprodução.','Indique três partes em foto ou desenho e explique uma função.','Raiz absorve água e fixa; caule sustenta e transporta; folhas participam da produção de alimento e trocas gasosas.'),
('EF02CI07','src/escola-brilha/curso-v4/ciencias-2ano/unidade-7/aula-01-sol-sombra.ts','Posição do Sol e sombras','Observar posições aparentes do Sol e relacioná-las à direção e ao tamanho das sombras.','Compare fotos ou medições feitas por adulto em horários distintos, sem olhar diretamente para o Sol.','Ordene três registros e descreva como a sombra mudou.','A sombra muda de direção e tamanho conforme a posição aparente do Sol; usar dados do registro.'),
('EF02CI08','src/escola-brilha/curso-v4/ciencias-2ano/unidade-7/aula-01-sol-sombra.ts','Luz, calor e materiais','Comparar o efeito da radiação solar em superfícies de cores e materiais diferentes com procedimento seguro.','Compare temperaturas registradas por adulto em superfícies claras e escuras, sem tocar superfícies muito quentes.','Leia o registro e indique qual superfície aqueceu mais, sem generalizar além do teste.','Conclusão baseada nos dados; diferenças dependem também do material, tempo e condições do ambiente.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Segurança primeiro','content',jsonb_build_array('O professor seleciona materiais e demonstra procedimentos; a criança não manipula calor, eletricidade, vidro, substâncias desconhecidas ou situações de risco.','Não olhar diretamente para o Sol nem provar plantas ou materiais.')),
  jsonb_build_object('heading','Pensar como cientista','content',jsonb_build_array('Registre pergunta, hipótese, observação e conclusão em campos separados.','Mude uma condição por vez quando houver comparação e ensine que a conclusão vale para o que foi observado.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Use instruções curtas, modelo visual e pausa planejada conforme a resposta observada.','Aceite fala, apontamento, objeto, cartões, desenho, foto, digitação ou escrita.','Retire apoios gradualmente sem diminuir o objetivo científico.')),
  jsonb_build_object('heading','Critério','content','Observa, compara, registra e explica quatro de cinco situações com evidência pertinente.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Perguntar e prever','instruction','Observe o caso e registre uma hipótese sem tratá-la como resposta final.','activity','Escolha uma previsão e diga qual pista levou a ela.','support','Foto ampliada, escolha visual e leitura em voz alta.'),
  jsonb_build_object('title','2. Investigar com apoio','instruction','Compare mantendo visível o que mudou e o que permaneceu igual.','activity',guided,'support','Tabela visual, cartões e modelagem do professor.'),
  jsonb_build_object('title','3. Concluir com evidência','instruction','Responda à pergunta usando somente o que foi observado.','activity',independent,'support','Resposta oral, apontada, montada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese ligada a uma pista observável.'),jsonb_build_object('page',2,'answer','Comparação registrada de modo coerente.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre hipótese, evidência, nível de ajuda e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','objects','cards','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'adult_supervision',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-2ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
