-- Biblioteca Inclusiva · Ensino Religioso do 9º ano completo.
-- Fontes mapeadas pelos campos BNCC ativos; a unidade 4 é aprofundamento complementar desativado no curso.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF09ER01','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-1/aula-01-cuidado-vida.ts','Princípios para o cuidado da vida','Analisar princípios e orientações para o cuidado da vida em tradições religiosas e filosofias de vida sem prescrição religiosa ou coleta de experiência pessoal.'),
('EF09ER02','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-1/aula-02-vida-nas-midias.ts','Valorização da vida nas mídias','Analisar como mídias podem valorizar ou desrespeitar a vida e a dignidade usando materiais selecionados, não gráficos e com leitura crítica.'),
('EF09ER03','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-5/aula-01-sentido-vida.ts','Sentidos do viver e do morrer','Identificar sentidos do viver e do morrer em mitos fundantes por análise cultural informativa, sem depoimentos pessoais ou prática religiosa.'),
('EF09ER04','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-2/aula-01-vida-morte.ts','Concepções de vida, morte e ritos fúnebres','Identificar concepções de vida e morte por descrições contextualizadas de ritos fúnebres, sem imagens gráficas, encenação ou exposição de perda.'),
('EF09ER05','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-3/aula-01-imortalidade-ancestralidade.ts','Ideias de imortalidade','Analisar ideias de ancestralidade, reencarnação, transmigração, ressurreição e memória com diversidade interna e sem hierarquizar crenças.'),
('EF09ER06','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-7/aula-01-sociedades-justas.ts','Coexistência e dignidade humana','Reconhecer coexistência, respeito à vida e dignidade humana como referências éticas para relações plurais e respostas à discriminação.'),
('EF09ER07','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-6/aula-01-projeto-vida.ts','Princípios éticos e projetos de vida','Identificar princípios familiares, religiosos, culturais e seculares que podem sustentar projetos de vida sem exigir revelação de convicções ou planos pessoais.'),
('EF09ER08','src/escola-brilha/curso-v4/ensino-religioso-9ano/unidade-6/aula-01-projeto-vida.ts','Construção ética de projetos de vida','Construir ou analisar projeto de vida assentado em valores éticos, com opção fictícia, direito de revisão e proteção de dados pessoais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional e sensível','content',jsonb_build_array('Apresente doutrinas, mitos, ritos, valores e filosofias como objetos de estudo. Conhecer não significa acreditar, concordar, aderir ou praticar.','Vida e morte recebem tratamento informativo e não gráfico. Não mostre conteúdo perturbador, não simule rito fúnebre ou situação de perda e não solicite relato de luto, saúde, risco, crença ou experiência íntima.','Não conduza oração, rito, aconselhamento espiritual, debate confessional ou representação de identidade. Ofereça material alternativo neutro, pausa ou recusa sem prejuízo.')),
 jsonb_build_object('heading','Mídia, dignidade e coexistência','content',jsonb_build_array('Use matérias fictícias, anonimizadas ou previamente selecionadas; não peça busca aberta por violência, sofrimento ou conteúdo sensível. Prefira descrição verbal neutra e avise previamente o tema.','Verifique autoria, data, fonte, evidência, contexto, enquadramento, pessoas ouvidas, interesse e efeito. Não compartilhe humilhação nem exposição para demonstrar desrespeito.','Em discriminação, interrompa a conduta, proteja a pessoa afetada e siga o protocolo escolar. Não obrigue confronto, relato público, mediação ou reconciliação.')),
 jsonb_build_object('heading','Projeto de vida acessível e privado','content',jsonb_build_array('Permita analisar personagem fictício ou plano hipotético em vez de expor objetivos, religião, família, relacionamento, saúde, finanças ou futuro do estudante.','Apresente projeto de vida como flexível e revisável, não como promessa permanente nem previsão de sucesso; evite comparar ritmos, carreiras ou escolhas entre estudantes.','Aceite cartões, linha do tempo fictícia, mapa de valores, comunicação alternativa, escrita, digitação, fala opcional ou áudio privado. Compartilhamento com turma ou família depende de escolha explícita do estudante.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com fonte, contexto, dignidade, princípio ético e justificativa, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler e contextualizar','instruction','Identifique gênero, fonte, comunidade, época, princípio, mensagem e finalidade no material fornecido.','activity','Classifique quatro elementos relacionados a '||lower(title)||' sem revelar crença, perda ou plano pessoal.','support','Texto segmentado, leitura fácil, aviso prévio do tema, glossário visual, fonte ampliada, descrição neutra, legenda, transcrição e áudio regulável.'),jsonb_build_object('title','2. Comparar com dignidade','instruction','Compare concepções, princípios ou representações por evidências, sem hierarquia e sem imagens perturbadoras.','activity','Complete quadro com contexto, princípio, evidência, semelhança, diferença e cuidado ético.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, pausa, alternativa neutra e mediação.'),jsonb_build_object('title','3. Aplicar a caso fictício','instruction','Use os princípios estudados para analisar mídia, convivência ou projeto hipotético.','activity','Produza sequência, mapa, texto curto ou áudio privado com escolha justificada e possibilidade de revisão.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fonte, contexto e princípio sem presumir crença, perda ou experiência.'),jsonb_build_object('page',2,'answer','Compara concepções e representações com dignidade, evidência e sem hierarquização.'),jsonb_build_object('page',3,'answer','Aplica princípio ético a caso fictício com justificativa, proteção e possibilidade de revisão.','teacher_note','Registre somente estratégia e apoio eficaz; não registre crença, saúde, perda, plano pessoal, voz, família, relacionamento, finanças ou futuro.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','fictional_timeline','values_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'neutral_image_description',true,'visual_glossary',true,'visual_schedule',true,'content_preview',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_sharing',true,'no_forced_religious_practice',true,'no_funeral_simulation',true,'non_graphic_life_and_death',true,'no_open_search_for_distressing_media',true,'fictional_anonymized_or_curated_media',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_grief_disclosure',true,'no_health_disclosure',true,'no_risk_disclosure',true,'no_personal_project_disclosure',true,'privacy_preserving',true,'source_context_framing_effect_check',true,'do_not_reshare_humiliation',true,'anti_discrimination_response',true,'no_forced_confrontation',true,'no_forced_reconciliation',true,'internal_diversity',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'fictional_project_option',true,'project_is_flexible_and_revisable',true,'no_student_comparison',true,'student_controlled_sharing',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-9ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
