-- Biblioteca Inclusiva · Filosofia do 7º ano completa.
-- EF07FI01–EF07FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF07FI01','src/escola-brilha/curso-v4/filosofia-7ano/unidade-1/aula-01-justica-agora.ts','Platão e a pergunta pela justiça','Analisar concepções platônicas de justiça por conceitos e situações fictícias, distinguindo descrição histórica de concordância pessoal.'),
('EF07FI02','src/escola-brilha/curso-v4/filosofia-7ano/unidade-2/aula-01-aristoteles-vida-boa.ts','Aristóteles, virtude e vida boa','Relacionar virtude, hábito, meio-termo e florescimento humano sem prescrever um modelo único de vida boa.'),
('EF07FI03','src/escola-brilha/curso-v4/filosofia-7ano/unidade-3/aula-01-estoicos-epicuristos.ts','Estoicos, epicuristas e modos de viver','Comparar propostas estoicas e epicuristas em contexto histórico sem convertê-las em aconselhamento emocional ou regra de conduta.'),
('EF07FI04','src/escola-brilha/curso-v4/filosofia-7ano/unidade-4/aula-01-fe-e-razao.ts','Fé e razão na filosofia medieval','Analisar relações entre fé e razão em pensadores medievais com abordagem histórica, não confessional e sem hierarquizar crença ou não crença.'),
('EF07FI05','src/escola-brilha/curso-v4/filosofia-7ano/unidade-5/aula-01-contrato-social.ts','Teorias do contrato social','Comparar ideias de Hobbes, Locke e Rousseau sobre autoridade, direitos e pacto político usando sociedades hipotéticas.'),
('EF07FI06','src/escola-brilha/curso-v4/filosofia-7ano/unidade-6/aula-01-liberdade-igualdade.ts','Liberdade, igualdade e direitos','Investigar ideias iluministas, Revolução Francesa e direitos humanos, reconhecendo contexto, exclusões históricas e ampliação de direitos.'),
('EF07FI07','src/escola-brilha/curso-v4/filosofia-7ano/unidade-7/aula-01-justica-hoje.ts','Rawls e justiça contemporânea','Aplicar critérios de justiça e o recurso hipotético do véu da ignorância a casos coletivos sem coletar vulnerabilidades ou posições políticas pessoais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','7º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Identificação e contexto','content',jsonb_build_array('Este é currículo autoral complementar. O código '||code||' organiza o NeuroBrilha e não é habilidade oficial da BNCC do Ensino Fundamental.','Apresente cada teoria com autor, época, problema, conceitos, argumentos, críticas e limites; estudar uma teoria não exige concordar com ela.','Evite narrativas de progresso simples: reconheça contribuições, exclusões históricas e outras tradições de pensamento sem declarar um povo, período ou autor superior.')),
 jsonb_build_object('heading','Diálogo, religião e política','content',jsonb_build_array('Debate, exposição oral e defesa de posição são opcionais. Use cidades, regras, dilemas e decisões fictícias ou coletivas, nunca votação partidária ou avaliação da opinião pessoal.','Na relação fé e razão, não conduza prática religiosa nem peça crença, não crença ou tradição familiar. Apresente interpretações religiosas, seculares e acadêmicas com respeito.','Ataque ideias e argumentos, não pessoas. Não aceite ridicularização, pressão do grupo ou obrigação de representar identidade, grupo político, classe social, religião ou personagem histórico.')),
 jsonb_build_object('heading','Segurança, direitos e acessibilidade','content',jsonb_build_array('Revoluções, punições e conflitos históricos recebem abordagem informativa e não gráfica, sem dramatização imersiva. Direitos humanos funcionam como referência de dignidade e proteção.','Exercícios de justiça usam dados públicos agregados ou cenários fictícios; não coletem renda, religião, saúde, deficiência, conflito familiar, opinião política ou experiência de discriminação da turma.','Ofereça texto segmentado, glossário visual, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Compara duas posições por problema, conceito, argumento, consequência e limite, justificando no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar a teoria','instruction','Identifique autor, época, problema e conceitos no material fornecido.','activity','Associe cartões de contexto e conceitos sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Comparar argumentos','instruction','Reconstrua duas posições por premissas, conclusão, consequência e crítica.','activity','Complete matriz comparativa usando casos fictícios e evidências do material.','support','Modelo resolvido, cartões móveis, mapa de argumentos, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Aplicar critério de justiça','instruction','Avalie um caso coletivo fictício por direitos, distribuição, liberdade, igualdade e efeitos.','activity','Produza quadro, sequência, texto curto ou áudio privado e indique um limite da solução.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa teoria, problema e conceitos sem atribuir posição ao estudante.'),jsonb_build_object('page',2,'answer','Compara argumentos, consequências e críticas com evidência.'),jsonb_build_object('page',3,'answer','Aplica critério de justiça e reconhece direito, efeito e limite.','teacher_note','Registre somente estratégia e apoio; não registre crença, política, renda, saúde, deficiência, família ou discriminação pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','comparison_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'fictional_or_collective_cases',true,'no_partisan_vote',true,'non_confessional_faith_reason',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_identity_impersonation',true,'idea_not_person',true,'no_ridicule',true,'no_peer_pressure',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'human_rights_framework',true,'aggregated_or_fictional_data',true,'no_income_collection',true,'no_health_collection',true,'no_disability_disclosure',true,'no_family_conflict_disclosure',true,'no_political_opinion_collection',true,'no_discrimination_experience_collection',true,'privacy_preserving',true,'historical_exclusions_acknowledged',true,'no_cultural_hierarchy',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-7ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
