-- Biblioteca Inclusiva · Ciências do 9º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF09CI01','unidade-3/aulas-materia-transformacoes.ts','Estados físicos e modelo de partículas'),
('EF09CI02','unidade-3/aulas-materia-transformacoes.ts','Proporções e conservação nas reações'),
('EF09CI03','unidade-3/aula-01.ts','Estrutura da matéria e transformações químicas'),
('EF09CI04','unidade-4/aulas-luz-radiacoes.ts','Luz, cores e sistema RGB'),
('EF09CI05','unidade-4/aulas-luz-radiacoes.ts','Comunicação e espectro eletromagnético'),
('EF09CI06','unidade-4/aulas-luz-radiacoes.ts','Ondas eletromagnéticas e tecnologias'),
('EF09CI07','unidade-4/aulas-luz-radiacoes.ts','Radiações na saúde e na medicina'),
('EF09CI08','unidade-1/aula-01.ts','Hereditariedade e transmissão de características'),
('EF09CI09','unidade-1/aula-01.ts','Ideias de Mendel e probabilidade genética'),
('EF09CI10','unidade-1/aulas-evolucao-conservacao.ts','Lamarck, Darwin e seleção natural'),
('EF09CI11','unidade-1/aula-01.ts','Evolução e diversidade biológica'),
('EF09CI12','unidade-1/aulas-evolucao-conservacao.ts','Unidades de conservação e biodiversidade'),
('EF09CI13','unidade-6/aula-01.ts','Sustentabilidade e ações coletivas'),
('EF09CI14','unidade-5/aula-01.ts','Sistema Solar e estrutura do Universo'),
('EF09CI15','unidade-5/aulas-astronomia.ts','Céus, culturas e modelos de origem'),
('EF09CI16','unidade-5/aulas-astronomia.ts','Condições para vida fora da Terra'),
('EF09CI17','unidade-5/aulas-astronomia.ts','Nascimento, evolução e morte das estrelas')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-9ano/'||rel source_key,title,'Investigar, analisar, modelar e argumentar sobre '||lower(title)||' com dados, cálculos, fontes confiáveis e linguagem científica do 9º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto, vocabulário e critério; use apoio visual sem reduzir a complexidade científica.','Professor controla materiais e demonstra procedimentos; não usar rede elétrica, laser, fontes de radiação, chama, reagentes, pressão, medicamentos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar, calcular e argumentar','content',jsonb_build_array('Separe observação, medida, modelo, inferência e conclusão; declare variável, escala, período, incerteza e fonte.','Use modelos de partículas, diagramas, proporções, heredogramas fictícios, gráficos, escalas e linhas do tempo, explicitando limites de cada representação.','Em genética e saúde, não fazer diagnóstico, previsão individual ou coleta de dados familiares reais; usar casos fictícios, privacidade, linguagem não determinista e orientação de adulto ou profissional.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida a investigação em etapas curtas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo termos científicos explicados e linguagem adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, cálculo, dado, mecanismo causal ou evidência pertinente e reconhece limites.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o problema e o modelo','instruction','Identifique sistema, componentes, variável, escala, período, fonte, incerteza e pergunta.','activity','Construa hipótese, previsão ou modelo inicial e indique o que ele representa e não representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar dados e explicações','instruction','Compare medidas, cálculos, fontes, modelos ou teorias e diferencie evidência de opinião e associação de causalidade.','activity','Complete tabela, gráfico, proporção, linha do tempo ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar e avaliar limites','instruction','Aplique o modelo em nova situação, justifique uma conclusão e explicite incertezas, implicações e limites.','activity','Produza argumento baseado em evidências e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Problema, variáveis, hipótese e limites do modelo delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com cálculo, dado e fonte indicada.'),jsonb_build_object('page',3,'answer','Argumento limitado às evidências e incertezas.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo; preserve privacidade.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'non_deterministic_language',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-9ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
