-- Biblioteca Inclusiva · Ciências do 1º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF01CI01','src/escola-brilha/curso-v4/ciencias-1ano/unidade-1/aula-01-objetos.ts','Objetos e materiais','Comparar características de materiais presentes em objetos do cotidiano e discutir descarte responsável.','Classifique objetos seguros por material, rigidez, transparência e flexibilidade.','Escolha um objeto, identifique o material e explique por que ele é adequado ao uso.','A resposta deve relacionar propriedade, material e uso; aceite mais de uma solução bem justificada.'),
('EF01CI02','src/escola-brilha/curso-v4/ciencias-1ano/unidade-2/aula-01-corpo.ts','Partes do corpo','Localizar, nomear e representar partes do corpo, relacionando-as a funções e respeitando diferentes corpos.','Monte uma figura corporal com cartões e associe partes a ações possíveis, sem pressupor que todos se movem do mesmo modo.','Indique em desenho, modelo ou no próprio corpo três partes e uma função de cada.','Exemplos: olhos ajudam a ver; mãos podem tocar; pernas podem apoiar movimentos. Respostas devem respeitar diferenças corporais.'),
('EF01CI03','src/escola-brilha/curso-v4/ciencias-1ano/unidade-3/aula-01-higiene.ts','Hábitos de higiene','Explicar por que hábitos de higiene do corpo ajudam a cuidar da saúde.','Ordene cartões de uma rotina de lavar as mãos e explique a função de cada etapa.','Escolha uma situação cotidiana e mostre o cuidado de higiene adequado.','Relacionar o hábito à redução de sujeira e microrganismos, sem prometer prevenção absoluta de doenças.'),
('EF01CI04','src/escola-brilha/curso-v4/ciencias-1ano/unidade-7/aula-01-diversidade.ts','Semelhanças, diferenças e respeito','Comparar características físicas entre pessoas, reconhecendo diversidade e respeito sem hierarquizar corpos.','Observe personagens diversos e registre semelhanças e diferenças com linguagem neutra e respeitosa.','Faça autorretrato ou descrição por cartões e diga uma característica compartilhada com outra pessoa.','Não há aparência certa; avaliar observação, respeito e reconhecimento da diversidade.'),
('EF01CI05','src/escola-brilha/curso-v4/ciencias-1ano/unidade-4/aula-01-dia-noite.ts','Escalas de tempo','Identificar e nomear períodos do dia e sequências de dias, semanas, meses e anos.','Organize cenas de manhã, tarde e noite usando pistas de luz e atividades, discutindo exceções de rotina.','Monte uma sequência de três acontecimentos e indique quando ocorrem.','A ordem deve ser coerente com a rotina apresentada; diferentes rotinas podem ter respostas distintas.'),
('EF01CI06','src/escola-brilha/curso-v4/ciencias-1ano/unidade-5/aula-01-escalas-tempo.ts','Ritmos do cotidiano','Relacionar sucessão de dias e noites a ritmos de atividades de pessoas e outros seres vivos.','Compare uma rotina humana e a de um animal diurno ou noturno em linha do tempo.','Marque uma atividade do dia e outra da noite e explique a pista temporal.','Resposta deve usar uma pista observável e reconhecer que rotinas variam.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Prepare com segurança','content',jsonb_build_array('Use somente objetos limpos, sem pontas, peças pequenas soltas, calor, vidro quebrável ou substâncias desconhecidas.','Apresente o objetivo com imagem real e uma frase curta; deixe visível a sequência observar, comparar, registrar e explicar.')),
  jsonb_build_object('heading','Ensine investigando','content',jsonb_build_array('Pergunte o que a criança percebe antes de explicar; aceite hipótese e depois teste com evidência observável.','Modele uma comparação por vez e ensine a diferença entre eu observei e eu acho.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Use blocos curtos definidos pela resposta da criança, não por diagnóstico.','Dê uma instrução por vez, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, objetos, cartões, desenho, foto, digitação ou escrita.')),
  jsonb_build_object('heading','Critério','content','Observa, compara e explica quatro de cinco situações usando ao menos uma evidência.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Observar de verdade','instruction','Olhe, toque somente quando for seguro e descreva sem adivinhar.','activity','Registre duas características do exemplo.','support','Objeto real ou foto ampliada, escolha visual e leitura em voz alta.'),
  jsonb_build_object('title','2. Investigar com apoio','instruction','Compare dois casos e mostre a evidência.','activity',guided,'support','Quadro igual-diferente, cartões e modelagem do professor.'),
  jsonb_build_object('title','3. Explicar com autonomia','instruction','Aplique a descoberta em uma nova situação.','activity',independent,'support','Resposta oral, apontada, montada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Duas características observáveis.'),jsonb_build_object('page',2,'answer','Comparação coerente e evidência indicada.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre a hipótese, evidência usada, apoio eficaz e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','objects','cards','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-1ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
