-- Biblioteca Inclusiva · Geografia do 8º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF08GE01','Regionalização e distribuição populacional','Interpretar regionalizações e distribuição populacional mundial por mapas e dados agregados.'),
('EF08GE02','Ordem mundial e regionalizações','Comparar critérios de regionalização, relações de poder e mudanças na ordem mundial.'),
('EF08GE03','Dinâmica demográfica mundial','Analisar indicadores e deslocamentos populacionais sem coletar dados pessoais ou familiares.'),
('EF08GE04','Migrações, refúgio e xenofobia','Explicar migrações e refúgio e combater xenofobia com abordagem informativa, não gráfica e baseada em direitos.'),
('EF08GE05','Globalização e divisão do trabalho','Analisar globalização e divisão internacional do trabalho por redes, agentes e desigualdades.'),
('EF08GE06','Produção e trabalho no mundo','Relacionar cadeias globais, trabalho, tecnologia e distribuição desigual de valor.'),
('EF08GE07','Corporações e organizações econômicas','Avaliar a influência territorial de corporações e organismos econômicos internacionais.'),
('EF08GE08','Integração mundial e tecnologia','Relacionar transporte e comunicação a fluxos globais de capital, mercadorias e informação.'),
('EF08GE09','Recursos naturais e geopolítica','Analisar recursos estratégicos, cooperação e disputas sem simular conflitos ou naturalizar violência.'),
('EF08GE10','Estados Unidos e poder global','Examinar dimensões econômica, política, tecnológica e cultural do poder dos Estados Unidos.'),
('EF08GE11','Relações econômicas e influência','Comparar redes de influência e dependência usando fontes múltiplas e escalas distintas.'),
('EF08GE12','Integração americana','Comparar objetivos e limites de blocos e organismos de integração nas Américas.'),
('EF08GE13','Organizações internacionais','Analisar funções, limites e interesses em organizações internacionais e blocos econômicos.'),
('EF08GE14','África e fronteiras coloniais','Explicar efeitos territoriais do colonialismo e da descolonização de modo histórico e não gráfico.'),
('EF08GE15','África: diversidade e desafios','Analisar diversidade regional africana e desafios socioeconômicos sem generalizações ou estereótipos.'),
('EF08GE16','América Latina na ordem mundial','Avaliar inserções latino-americanas na economia mundial e relações de dependência e cooperação.'),
('EF08GE17','Características da América Latina','Comparar sub-regiões latino-americanas por aspectos físicos, populacionais, urbanos, políticos e econômicos.'),
('EF08GE18','Economias latino-americanas','Relacionar atividades econômicas, redes urbanas, infraestrutura e fluxos de exportação.'),
('EF08GE19','Cartografia da América e África','Interpretar mapas temáticos da América e África por variável, fonte, escala e método.'),
('EF08GE20','Desigualdades urbanas','Analisar segregação e acesso desigual a serviços como processos socioespaciais, sem culpabilizar moradores.'),
('EF08GE21','Indicadores latino-americanos','Comparar países por conjuntos de indicadores sem transformar médias em retratos individuais.'),
('EF08GE22','Recursos hídricos latino-americanos','Explicar bacias e aquíferos transfronteiriços e a necessidade de gestão compartilhada.'),
('EF08GE23','Paisagens da América Latina','Relacionar relevo, clima, vegetação e ocupação humana na formação das paisagens.'),
('EF08GE24','Biodiversidade e ambientes','Avaliar pressões sobre domínios naturais, biodiversidade e clima em diferentes escalas.'),
('EF08GE25','Povos e territórios','Reconhecer territorialidades e direitos de povos indígenas, afrodescendentes e comunidades tradicionais.'),
('EF08GE26','Antártica e geopolítica','Analisar acordos, pesquisa científica e proteção ambiental na Antártica.'),
('EF08GE27','Sustentabilidade na América Latina','Avaliar políticas e ações cooperativas para problemas ambientais latino-americanos.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-8ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise geopolítica e territorial — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes seguras e plurais','content',jsonb_build_array('Use mapas, gráficos, documentos e dados públicos agregados de mais de uma fonte; nunca peça nacionalidade, etnia, religião, renda, opinião política, endereço, geolocalização ou história migratória da criança e da família.','Migrações forçadas, xenofobia, colonialismo, disputas territoriais e conflitos devem receber tratamento histórico e informativo, sem detalhes gráficos, encenação ou simulação imersiva.')),
 jsonb_build_object('heading','Evite visões únicas e estereótipos','content',jsonb_build_array('Não apresente África, América Latina, migrantes, refugiados, povos indígenas, afrodescendentes ou comunidades tradicionais como grupos homogêneos; mostre diversidade, agência, produção de conhecimento e direitos.','Termos como desenvolvimento, centro, periferia, hegemonia e dependência devem ser tratados como conceitos debatidos, definidos pelo contexto e sustentados por indicadores múltiplos.')),
 jsonb_build_object('heading','Modele a análise multiescalar','content',jsonb_build_array('Verifique autoria, instituição, data, recorte, escala, variável, unidade, método e interesse; compare fontes e identifique silêncios ou divergências.','Mapeie atores, redes, fluxos, interesses, relações de poder, causas e consequências; diferencie fato, inferência, opinião, correlação e causalidade.','Mapas e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual, tabela equivalente ou alternativa tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos densos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e ofereça pistas graduadas e pausa.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, diagrama, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões com fontes, escala, atores e evidências pertinentes.'))))),
jsonb_build_array(jsonb_build_object('title','1. Examinar a fonte','instruction','Identifique autoria, data, recorte, escala, variável, método, propósito e contexto.','activity','Registre duas evidências, um silêncio ou divergência e uma pergunta investigável.','support','Glossário, texto segmentado, leitura mediada e versão ampliada, descrita ou tabular.'),jsonb_build_object('title','2. Mapear relações','instruction','Compare fontes e localize atores, redes, fluxos, interesses, padrões e exceções.','activity','Construa mapa, gráfico acessível, matriz de atores ou cadeia causal sobre '||lower(title)||'.','support','Exemplo resolvido, dados em camadas e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com limites','instruction','Apresente conclusão, evidências, explicação alternativa e limites das fontes.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade e cooperação.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, evidências e silêncio ou divergência relevante.'),jsonb_build_object('page',2,'answer','Representa atores e relações sem generalizar territórios ou grupos.'),jsonb_build_object('page',3,'answer','Argumento multiescalar sustentado, com alternativa e limites reconhecidos.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, localização, renda, migração ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','actor_matrix','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_nationality_collection',true,'no_ethnicity_collection',true,'no_religion_collection',true,'no_income_collection',true,'no_political_opinion_collection',true,'no_family_migration_disclosure',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'migration_rights_context',true,'africa_latin_america_anti_stereotype',true,'indigenous_afrodescendant_rights_context',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-8ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
