-- Biblioteca Inclusiva · Geografia do 5º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF05GE01','src/escola-brilha/curso-v4/geografia-5ano/unidade-1/aula-01-populacao-crescimento.ts','Dinâmica populacional','Interpretar crescimento, distribuição e características populacionais por dados contextualizados.'),
('EF05GE02','src/escola-brilha/curso-v4/geografia-5ano/unidade-1/aula-02-migracoes-internas.ts','Migrações internas e diversidade','Analisar migrações internas e diversidade cultural sem exigir trajetória familiar ou origem pessoal.'),
('EF05GE03','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-01-urbanizacao.ts','Urbanização e funções das cidades','Distinguir funções e características de cidades de diferentes tamanhos sem hierarquizar seus habitantes.'),
('EF05GE04','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-02-campo-cidade-conectados.ts','Campo e cidade conectados','Explicar interdependências entre campo e cidade por fluxos de produtos, pessoas, informação e serviços.'),
('EF05GE05','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-03-trabalho-tecnologia.ts','Trabalho e tecnologia','Analisar mudanças no trabalho provocadas pela tecnologia, considerando benefícios, desigualdades e acessibilidade.'),
('EF05GE06','src/escola-brilha/curso-v4/geografia-5ano/unidade-2/aula-04-transportes-comunicacoes.ts','Transportes e comunicações','Comparar redes de transporte e comunicação e seus efeitos na integração territorial e no acesso a serviços.'),
('EF05GE07','src/escola-brilha/curso-v4/geografia-5ano/unidade-4/aula-02-impactos-energia.ts','Fontes de energia e impactos','Comparar fontes de energia por disponibilidade, usos e impactos socioambientais sem soluções simplistas.'),
('EF05GE08','src/escola-brilha/curso-v4/geografia-5ano/unidade-3/aula-03-paisagens-no-tempo.ts','Transformações das paisagens urbanas','Comparar paisagens urbanas de tempos diferentes e relacionar mudanças a processos sociais e econômicos.'),
('EF05GE09','src/escola-brilha/curso-v4/geografia-5ano/unidade-3/aula-01-mapas-tematicos.ts','Mapas temáticos e diferenças regionais','Interpretar mapas temáticos, legendas e dados regionais usando símbolos que não dependam apenas de cor.'),
('EF05GE10','src/escola-brilha/curso-v4/geografia-5ano/unidade-5/aula-02-qualidade-ambiental.ts','Qualidade ambiental urbana','Analisar indicadores ambientais urbanos e comparar propostas coletivas de melhoria e acessibilidade.'),
('EF05GE11','src/escola-brilha/curso-v4/geografia-5ano/unidade-6/aula-01-consumo-residuos.ts','Consumo, resíduos e tecnologia','Relacionar consumo, geração de resíduos e soluções tecnológicas sem expor renda ou hábitos familiares.'),
('EF05GE12','src/escola-brilha/curso-v4/geografia-5ano/unidade-7/aula-02-participacao-ambiental.ts','Participação e soluções para a cidade','Avaliar propostas para problemas socioambientais e planejar participação cidadã segura em cenários fictícios.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare dados e cenários protegidos','content',jsonb_build_array('Use cidades, trajetórias migratórias, perfis populacionais, consumo, trabalho e problemas ambientais fictícios ou dados públicos agregados; nunca peça endereço, geolocalização, renda, conta doméstica, ocupação dos responsáveis, hábitos de consumo, origem ou trajetória familiar da criança.','Contextualize desigualdades como fenômenos sociais e territoriais; não associe condição econômica, lugar de origem, deficiência ou tipo de trabalho a mérito pessoal.')),
 jsonb_build_object('heading','Modele a análise crítica','content',jsonb_build_array('Ensine a verificar título, fonte, data, escala, legenda, unidade de medida e recorte territorial antes de interpretar.','Compare dados e mapas, identifique padrões, conecte causas e consequências e diferencie evidência, inferência e opinião.','Em propostas ambientais, considere impacto, viabilidade, responsabilidade pública e coletiva, acessibilidade e possíveis efeitos não previstos.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe conceitos, divida gráficos e mapas em camadas, dê uma instrução por vez e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala, cálculo ou coordenação motora como medida isolada da compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com dado, elemento cartográfico ou relação territorial pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Verificar a fonte','instruction','Localize título, fonte, data, legenda, escala, unidade e recorte quando disponíveis.','activity','Registre duas informações verificáveis e uma limitação do material.','support','Leitura mediada, ampliação, tabela simplificada e descrição verbal ou tátil.'),jsonb_build_object('title','2. Identificar padrões e relações','instruction','Compare dados, mapas, paisagens, redes ou fluxos de cenários fictícios.','activity','Monte quadro, gráfico acessível, mapa ou cadeia causa-consequência sobre '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Avaliar e argumentar','instruction','Apresente uma conclusão, cite a evidência e considere outra explicação possível.','activity','Compare propostas por impacto, viabilidade, equidade e responsabilidade coletiva.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, duas informações e uma limitação.'),jsonb_build_object('page',2,'answer','Reconhece padrão ou relação sem extrapolar os dados.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidência e avaliação equilibrada da proposta.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, renda, consumo ou trajetória familiar real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_income_collection',true,'no_household_consumption_disclosure',true,'no_family_origin_disclosure',true,'no_parent_occupation_collection',true,'inequality_contextualized',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-5ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
