-- Biblioteca Inclusiva · Ensino Religioso do 7º ano completo.
-- O curso ativo zera os códigos das sete aulas antigas e concentra EF07ER01–08 nas oficinas BNCC.
WITH lessons(code,title,goal) AS (VALUES
('EF07ER01','Práticas de comunicação com divindades','Reconhecer práticas de comunicação com divindades em diferentes tradições por análise contextual, sem participação devocional.'),
('EF07ER02','Espiritualidade em situações específicas','Identificar práticas de espiritualidade usadas por algumas pessoas em situações específicas, preservando autonomia e distinguindo apoio espiritual de serviços profissionais.'),
('EF07ER03','Papéis das lideranças religiosas','Reconhecer papéis atribuídos a lideranças religiosas conforme cada tradição, sem tratá-las como representantes absolutos de grupos diversos.'),
('EF07ER04','Contribuições sociais de lideranças','Exemplificar contribuições sociais verificáveis de lideranças religiosas em diferentes tempos e espaços, analisando fontes, contexto, efeitos e limites.'),
('EF07ER05','Estratégias de convivência ética','Discutir estratégias que promovam convivência ética entre religiões, filosofias de vida e pessoas sem religião, com direitos, diálogo e limites.'),
('EF07ER06','Princípios éticos e práticas sociais','Identificar princípios éticos em tradições religiosas e filosofias de vida e relacioná-los criticamente a condutas e práticas sociais.'),
('EF07ER07','Lideranças e direitos humanos','Discutir o papel de lideranças religiosas e seculares na defesa e promoção dos direitos humanos com base em ações e fontes verificáveis.'),
('EF07ER08','Liberdade de consciência, crença e convicção','Reconhecer o direito de ter, mudar ou não ter religião ou convicção e questionar coerção e discriminação sem exigir relato pessoal.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/ensino-religioso-7ano/oficinas-bncc.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional','content',jsonb_build_array('Apresente religião, espiritualidade, filosofia de vida, liderança, ética e direitos como objetos de estudo; conhecer não significa acreditar, concordar, aderir ou praticar.','Não conduza oração, meditação religiosa, canto, recitação, oferenda, rito, gesto, dança, dramatização, aconselhamento espiritual ou simulação de situação vulnerável. Use casos fictícios e análise documental.','Não peça crença, ausência de crença, mudança de religião, prática familiar, liderança frequentada, experiência difícil, opinião íntima ou posicionamento público. Sempre aceite alternativa neutra e recusa sem prejuízo.')),
 jsonb_build_object('heading','Direitos, segurança e serviços','content',jsonb_build_array('Ensine liberdade de consciência como direito de ter, mudar ou não ter religião ou convicção, dentro do respeito aos direitos das outras pessoas.','Em casos de discriminação, priorize interromper a conduta, proteger a pessoa afetada, registrar pelos canais institucionais e acionar responsáveis e rede de proteção conforme o protocolo escolar; não obrigue confronto, mediação ou reconciliação.','Apoio religioso ou espiritual pode coexistir com cuidado profissional, mas não substitui saúde, emergência, proteção civil, assistência social ou políticas públicas. O professor não diagnostica nem recomenda prática religiosa.')),
 jsonb_build_object('heading','Investigação crítica e acessível','content',jsonb_build_array('Pesquise contribuições e controvérsias por ações, datas, contexto, fontes confiáveis e efeitos; não use número de seguidores, fama ou identidade religiosa como prova de mérito.','Reconheça diversidade interna, lideranças religiosas e seculares, filosofias de vida e pessoas sem religião. Evite generalizar, hierarquizar ou transformar uma liderança em porta-voz total.','Ofereça texto segmentado, glossário visual, legenda, transcrição, descrição de imagem, áudio regulável, casos fictícios, cartões e organizadores; aceite comunicação alternativa, seleção, escrita, digitação, fala opcional ou áudio privado.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com direito aplicável, evidência, contexto, efeito e proposta segura, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Identificar o caso','instruction','Leia um caso fictício e identifique prática, pessoas envolvidas, direito, papel de liderança e serviço profissional quando pertinente.','activity','Classifique cartões de fato, interpretação, direito, apoio e ação segura sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, áudio regulável, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Verificar fontes e efeitos','instruction','Compare duas fontes, separe afirmação de evidência e reconheça diversidade interna e limites.','activity','Complete quadro com autoria, data, contexto, ação, efeito, direito e informação ainda necessária.','support','Modelo resolvido, cartões móveis, pistas graduadas, código por forma e rótulo, tempo ampliado e mediação.'),jsonb_build_object('title','3. Propor resposta ética','instruction','Escolha uma resposta que preserve autonomia, dignidade, segurança, direitos e serviços adequados.','activity','Monte sequência de ação para caso fictício, sem revelar crença ou experiência pessoal e sem apresentação pública obrigatória.','support','Apontar, selecionar, comunicação alternativa, mapa, digitação, escrita, fala opcional, áudio privado ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fato, direito e papel sem presumir crença, intenção ou identidade.'),jsonb_build_object('page',2,'answer','Usa fonte e contexto para avaliar ação, efeito, contribuição ou limite sem generalização.'),jsonb_build_object('page',3,'answer','Propõe resposta que protege autonomia e direitos e encaminha ao serviço adequado quando necessário.','teacher_note','Registre estratégia e apoio eficaz; não registre religião, não religião, mudança de crença, voz, experiência difícil, opinião ou vínculo comunitário.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','rights_map','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_position',true,'no_forced_prayer',true,'no_forced_meditation',true,'no_forced_recitation',true,'no_forced_ritual',true,'no_spiritual_counseling_by_teacher',true,'no_vulnerability_simulation',true,'fictional_cases_only',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_conversion_history_disclosure',true,'no_family_religion_disclosure',true,'no_worship_place_disclosure',true,'no_vulnerability_disclosure',true,'privacy_preserving',true,'freedom_of_conscience',true,'human_rights_framework',true,'anti_discrimination_response',true,'no_forced_confrontation',true,'no_forced_reconciliation',true,'professional_services_not_replaced',true,'no_diagnosis',true,'source_context_effect_check',true,'internal_diversity',true,'religious_secular_and_nonreligious_inclusion',true,'no_leader_generalization',true,'no_belief_hierarchy',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-7ano/oficinas-bncc/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
