-- Biblioteca Inclusiva · História do 6º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF06HI01','unidade-1/aula-02-tempo-periodizacao.ts','Tempo histórico e formas de periodização'),
('EF06HI02','unidade-1/aula-01-ciencia-da-historia.ts','Fontes e produção do conhecimento histórico'),
('EF06HI03','unidade-2/aula-02-origens-povoamento.ts','Origens humanas e deslocamentos'),
('EF06HI04','unidade-2/aula-02-origens-povoamento.ts','Povoamento das Américas'),
('EF06HI05','unidade-3/aula-01-civilizacoes-hidraulicas.ts','Sociedades antigas, natureza e cultura'),
('EF06HI06','unidade-2/aula-02-origens-povoamento.ts','Povos originários das Américas'),
('EF06HI07','unidade-4/aula-02-mundos-antigo-medieval.ts','Formação do mundo antigo'),
('EF06HI08','unidade-4/aula-02-mundos-antigo-medieval.ts','Espaços e culturas do mundo antigo'),
('EF06HI09','unidade-4/aula-02-mundos-antigo-medieval.ts','Passagens do mundo antigo ao medieval'),
('EF06HI10','unidade-4/aula-01-grecia-antiga.ts','Grécia antiga, pólis e cultura'),
('EF06HI11','unidade-5/aula-01-roma-antiga.ts','Roma: monarquia, república e império'),
('EF06HI12','unidade-4/aula-01-grecia-antiga.ts','Cidadania, política e exclusões na Antiguidade'),
('EF06HI13','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Impérios, contatos e circulação mediterrânica'),
('EF06HI14','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Culturas, religiões e poder no Mediterrâneo'),
('EF06HI15','unidade-6/aula-02-imperios-contatos-mediterraneo.ts','Reinos e sociedades africanas antigas'),
('EF06HI16','unidade-7/aula-02-cidades-trabalho.ts','Cidades, abastecimento e organização social'),
('EF06HI17','unidade-7/aula-02-cidades-trabalho.ts','Trabalho livre, servidão e escravização'),
('EF06HI18','unidade-7/aula-03-cristianismo-mulheres.ts','Cristianismo, poder e transformações sociais'),
('EF06HI19','unidade-7/aula-03-cristianismo-mulheres.ts','Experiências e papéis das mulheres na Antiguidade e no medievo')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-6ano/'||rel source_key,title,'Analisar e explicar '||lower(title)||' usando fontes, cronologia, espacialização, conceitos e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize sem simplificar demais','content',jsonb_build_array('Apresente periodizações como escolhas de historiadores, não como divisões naturais ou universais; inclua cronologias africanas, americanas, asiáticas e europeias.','Evite a ideia de civilização superior, evolução linear ou povo sem história; povos originários e sociedades africanas aparecem com diversidade, conhecimentos, agência e presença atual.','Ao tratar guerras, escravização, perseguições e desigualdades, use descrição informativa e não gráfica; não faça simulações de opressão ou sofrimento.')),
 jsonb_build_object('heading','Analisar evidências e conceitos','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de fontes arqueológicas, materiais, escritas, orais e visuais.','Relacione território, ambiente, trabalho, religião, gênero, cidadania, poder e intercâmbios sem reduzir processos a uma causa única.','Diferencie escravização, servidão e trabalho livre e reconheça resistência e ação histórica das pessoas submetidas à coerção.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida textos e tarefas em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, digitada, escrita ou com tecnologia assistiva.','Use glossário, linha do tempo, mapa, fonte ampliada e prática guiada, retirando pistas gradualmente.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco situações usando contexto, cronologia, espaço, conceito, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar problema e fontes','instruction','Identifique período, espaço, grupos, autoria, finalidade, pistas, silêncios e limites.','activity','Compare duas fontes ou periodizações e formule pergunta histórica.','support','Glossário, linha do tempo, mapa, leitura apoiada e exemplo resolvido.'),jsonb_build_object('title','2. Relacionar processos','instruction','Compare organizações sociais e conecte ambiente, trabalho, cultura, poder, gênero e religião.','activity','Monte quadro causal, mapa, linha do tempo ou diagrama de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar historicamente','instruction','Formule explicação com evidências, reconheça agência, outra perspectiva e limites.','activity','Produza argumento curto, cite fontes e revise diante de contraexemplo.','support','Resposta oral, apontada, mapeada, diagramada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fontes e identifica pistas, silêncios e limites.'),jsonb_build_object('page',2,'answer','Relaciona processos sem hierarquia cultural ou causa única.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidências e múltiplas perspectivas.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre religião, origem ou experiência pessoal sensível.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_african_agency',true,'periodization_plurality',true,'forced_labor_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-6ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
