-- Biblioteca Inclusiva · História do 1º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF01HI01','src/escola-brilha/data/EF01HI01.ts','O álbum das descobertas','Identificar aspectos do próprio crescimento por meio de registros e lembranças, respeitando diferentes trajetórias.'),
('EF01HI02','src/escola-brilha/data/EF01HI02.ts','Minha família, minha história','Reconhecer relações entre histórias pessoais e histórias de grupos familiares e comunitários diversos.'),
('EF01HI03','src/escola-brilha/data/EF01HI03.ts','Meus papéis em cada lugar','Distinguir papéis e responsabilidades na família, escola e comunidade sem estereótipos.'),
('EF01HI04','src/escola-brilha/data/EF01HI04.ts','Casa, escola e comunidade','Comparar características, hábitos e regras de diferentes ambientes de convivência.'),
('EF01HI05','src/escola-brilha/data/EF01HI05.ts','As brincadeiras de ontem e de hoje','Comparar brincadeiras atuais e de outras épocas e lugares usando fontes acessíveis.'),
('EF01HI06','src/escola-brilha/data/EF01HI06.ts','Cada pessoa tem sua história','Conhecer histórias da família e da escola preservando privacidade e acolhendo diferentes configurações.'),
('EF01HI07','src/escola-brilha/data/EF01HI07.ts','Famílias que mudam com o tempo','Identificar mudanças e permanências nas formas de organização familiar.'),
('EF01HI08','src/escola-brilha/data/EF01HI08.ts','As festas que nos unem','Reconhecer sentidos de festas e comemorações escolares e comunitárias, respeitando participação e diversidade cultural ou religiosa.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com acolhimento','content',jsonb_build_array('Use personagens, fotografias públicas, objetos ou cartões fornecidos pela escola; nunca exija fotografia, documento, endereço, religião ou relato familiar da criança.','Apresente objetivo e sequência visual: observar, ordenar, comparar e contar.')),
 jsonb_build_object('heading','Ensine a pensar historicamente','content',jsonb_build_array('Modele a diferença entre antes, agora e depois e entre mudança e permanência.','Compare duas fontes simples e pergunte quem produziu, o que mostra e o que não permite saber.','Mostre famílias, moradias, culturas, corpos e modos de viver diversos sem tratar um modelo como padrão.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, desenho, foto fornecida pela escola, digitação, escrita ou tecnologia assistiva.','Não avalie memória familiar, habilidade de leitura ou fala como se fossem compreensão histórica.')),
 jsonb_build_object('heading','Critério','content','Ordena, compara ou explica quatro de cinco situações usando uma pista temporal ou evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar a fonte','instruction','Observe personagem, imagem, objeto ou relato fictício e identifique pistas.','activity','Marque o que a fonte mostra e uma coisa que ela não permite saber.','support','Vocabulário visual, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Ordenar e comparar','instruction','Organize cenas em antes, agora e depois; compare mudança e permanência.','activity','Monte linha do tempo de cartões ou tabela de duas colunas sobre '||lower(title)||'.','support','Modelo pronto, pistas graduadas e Prática guiada antes da independente.'),jsonb_build_object('title','3. Contar com evidência','instruction','Conte o que mudou ou permaneceu e aponte a pista usada.','activity','Escolha fala, sequência, desenho, cartões ou escrita para apresentar a conclusão.','support','Resposta oral, apontada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica ao menos uma pista observável e um limite da fonte.'),jsonb_build_object('page',2,'answer','Ordena ou compara com coerência temporal.'),jsonb_build_object('page',3,'answer','Conclusão ligada à pista selecionada.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre informações familiares sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'family_diversity',true,'cultural_religious_respect',true,'fictional_alternative',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
