-- Biblioteca Inclusiva · História do 3º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF03HI01','unidade-5/aula-02-grupos-perspectivas.ts','Grupos que formam a história local'),
('EF03HI02','unidade-1/aula-02-fontes-historia-local.ts','Fontes da história local'),
('EF03HI03','unidade-5/aula-02-grupos-perspectivas.ts','Perspectivas sobre acontecimentos locais'),
('EF03HI04','unidade-4/aula-01-surgimento-cidades-patrimonio.ts','Formação das cidades e patrimônio'),
('EF03HI05','unidade-4/aula-01-surgimento-cidades-patrimonio.ts','Marcos históricos e memória coletiva'),
('EF03HI06','unidade-4/aula-02-nomes-memoria.ts','Nomes, monumentos e disputas de memória'),
('EF03HI07','unidade-2/aulas-comunidades-trabalho.ts','Comunidades da cidade e do campo'),
('EF03HI08','unidade-2/aulas-comunidades-trabalho.ts','Modos de vida urbanos e rurais'),
('EF03HI09','unidade-6/aula-02-espacos-cidade.ts','Espaços públicos, privados e protegidos'),
('EF03HI10','unidade-6/aula-02-espacos-cidade.ts','Diferenças entre espaços domésticos, públicos e de conservação'),
('EF03HI11','unidade-2/aulas-comunidades-trabalho.ts','Trabalho na cidade e no campo'),
('EF03HI12','unidade-7/aula-02-lazer-tempo.ts','Lazer e uso do tempo na cidade e no campo')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-3ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, mapas, sequências temporais, comparações e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes e perspectivas','content',jsonb_build_array('Use mapas fictícios ou públicos, imagens, objetos, depoimentos publicados e cartões fornecidos pela escola; não exija endereço, fotografia, origem familiar, renda, profissão ou relato pessoal.','Inclua indígenas, povos africanos e afro-brasileiros, migrantes e outros grupos como sujeitos históricos diversos, com presente e agência; não os reduza a uma mistura homogênea ou contribuição folclórica.')),
 jsonb_build_object('heading','Investigar história local','content',jsonb_build_array('Compare autoria, data, finalidade, contexto, evidências, silêncios e limites de fontes materiais, escritas, orais, visuais e cartográficas.','Organize mudança e permanência; conecte campo e cidade sem hierarquizar modos de vida.','Trate nomes de ruas, monumentos e patrimônios como escolhas de memória que podem incluir, excluir ou ser debatidas.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, mapa, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem não estigmatizante ao tratar território, trabalho, moradia, lazer, cultura e ambiente.')),
 jsonb_build_object('heading','Critério','content','Compara ou explica quatro de cinco situações usando marcador temporal, localização, perspectiva e evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e ler fontes','instruction','Localize tempo e espaço e identifique autoria, finalidade, pistas, silêncios e limites.','activity','Marque o que duas fontes mostram, em que divergem e uma pergunta ainda aberta.','support','Vocabulário visual, mapa simples, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar mudanças e perspectivas','instruction','Organize acontecimentos e compare permanências, grupos e pontos de vista.','activity','Monte linha do tempo, quadro comparativo ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar com evidências','instruction','Relacione tempo, território, grupos, trabalho, cultura e ambiente e cite as fontes usadas.','activity','Apresente uma conclusão e reconheça outra perspectiva ou limite.','support','Resposta oral, apontada, mapeada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fonte, identifica pista, perspectiva e limite.'),jsonb_build_object('page',2,'answer','Compara com coerência temporal e espacial sem hierarquizar grupos.'),jsonb_build_object('page',3,'answer','Conclusão ligada às evidências e aberta a outra perspectiva.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre dados pessoais sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'contested_memory',true,'non_stigmatizing_language',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-3ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
