-- Biblioteca Inclusiva · Ciências do 3º ano completa.
WITH lessons(code,source_key,title,goal,guided,independent,answer) AS (VALUES
('EF03CI01','src/escola-brilha/curso-v4/ciencias-3ano/unidade-6/aula-01-som-vibracao.ts','Som e vibração','Produzir sons com objetos seguros e explicar que diferentes vibrações geram sons.','Observe grãos sobre uma membrana vibrando com som moderado e compare vibração visível e som ouvido.','Escolha um objeto sonoro seguro, indique o que vibra e compare som forte/fraco sem elevar o volume.','O som resulta de vibração; intensidade e altura não são a mesma característica.'),
('EF03CI02','src/escola-brilha/curso-v4/ciencias-3ano/unidade-5/aula-01-luz-sombras.ts','Luz e interação com materiais','Investigar passagem, reflexão e bloqueio da luz em materiais transparentes, translúcidos e opacos.','Com lanterna de baixa intensidade, compare materiais sem direcionar luz aos olhos.','Classifique um material pela passagem de luz e mostre a evidência.','Transparente deixa passar mais luz; translúcido parcialmente; opaco bloqueia a passagem.'),
('EF03CI03','src/escola-brilha/curso-v4/ciencias-3ano/unidade-7/aula-01-saude-sentidos.ts','Saúde auditiva e visual','Reconhecer condições prejudiciais à audição e à visão e propor cuidados cotidianos.','Classifique cenas de volume, distância de telas, iluminação e proteção como cuidado ou risco.','Escolha uma situação e proponha uma mudança segura, procurando adulto ou profissional quando necessário.','Reduzir volume e exposição, usar iluminação adequada e não olhar fontes intensas; sintomas exigem avaliação de adulto/profissional.'),
('EF03CI04','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Características e modos de vida dos animais','Comparar alimentação, deslocamento, reprodução, cobertura corporal e ambiente de animais.','Preencha tabela de dois animais usando somente informações de fotos e textos curtos.','Descreva um animal por três características e relacione uma ao ambiente.','Descrição coerente com a fonte; não usar apenas tamanho ou aparência para classificar.'),
('EF03CI05','src/escola-brilha/curso-v4/ciencias-3ano/unidade-3/aula-01-ciclo-vida.ts','Ciclo de vida dos animais','Descrever mudanças desde o nascimento até a fase adulta e reconhecer reprodução e desenvolvimento.','Ordene etapas documentadas de um ciclo de vida sem afirmar que todos os animais seguem o mesmo padrão.','Compare o ciclo de dois animais e indique uma semelhança e uma diferença.','A sequência e comparação devem corresponder às espécies estudadas.'),
('EF03CI06','src/escola-brilha/curso-v4/ciencias-3ano/unidade-2/aula-01-vertebrados-invertebrados.ts','Agrupamento de animais','Comparar animais e formar grupos por características externas observáveis.','Agrupe cartões por cobertura, número de patas, presença de asas ou modo de locomoção e explicite o critério.','Crie um agrupamento diferente e explique por que cada animal pertence a ele.','Mais de um agrupamento é válido quando o critério é observável e usado de forma consistente.'),
('EF03CI07','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Características da Terra','Reconhecer forma aproximadamente esférica, presença de água e continentes em representações e observações indiretas.','Compare globo, mapa e imagem da Terra, discutindo o que cada representação mostra e distorce.','Indique duas evidências ou representações usadas para estudar a Terra.','A Terra é aproximadamente esférica; mapa plano e globo são modelos com vantagens e limites.'),
('EF03CI08','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Observação do céu','Registrar posições aparentes do Sol, Lua, estrelas e outros astros em horários distintos com segurança.','Analise registros preparados pelo professor e organize data, horário, direção e desenho observado.','Compare dois registros e descreva uma mudança sem concluir além dos dados.','Mudanças aparentes dependem do horário e da posição do observador; nunca olhar diretamente para o Sol.'),
('EF03CI09','src/escola-brilha/curso-v4/ciencias-3ano/unidade-1/aula-01-composicao-solo.ts','Características do solo','Comparar amostras seguras de solo por cor, textura, tamanho dos grãos, cheiro e permeabilidade.','Observe amostras previamente verificadas, usando colher e recipiente, sem tocar rosto ou levar material à boca.','Registre duas diferenças e proponha uma explicação que possa ser testada.','Descrever dados observáveis; hipótese não deve ser apresentada como certeza.'),
('EF03CI10','src/escola-brilha/curso-v4/ciencias-3ano/unidade-8/aulas-consolidacao.ts','Usos do solo','Identificar usos do solo na agricultura, construção e conservação e discutir impactos e cuidados.','Compare imagens de solo coberto por vegetação, cultivado e pavimentado, relacionando uso e efeito.','Escolha um uso e proponha um cuidado para reduzir erosão, contaminação ou desperdício.','A proposta deve se relacionar ao problema observado e reconhecer que diferentes usos exigem cuidados distintos.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','Ciências',title,goal,
 ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
 jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
  jsonb_build_object('heading','Segurança e materiais','content',jsonb_build_array('O professor seleciona materiais limpos e seguros; não usar alto volume, luz nos olhos, calor, substâncias desconhecidas ou observação direta do Sol.','Antecipe regras em sequência visual e interrompa a atividade se houver desconforto sensorial.')),
  jsonb_build_object('heading','Investigue sem entregar a resposta','content',jsonb_build_array('Separe pergunta, hipótese, procedimento, observação e conclusão.','Compare uma variável por vez e ensine a citar dados; hipótese diferente do resultado não é erro.')),
  jsonb_build_object('heading','Rotina ajustável','content',jsonb_build_array('Alterne demonstração, investigação guiada, pausa e retomada conforme resposta observada.','Dê uma instrução por vez e ofereça participação por fala, apontamento, tabela, desenho, foto, digitação ou escrita.','Retire apoios gradualmente sem reduzir o objetivo.')),
  jsonb_build_object('heading','Critério','content','Registra comparação e explica quatro de cinco situações usando evidência pertinente.')
 ))),
 jsonb_build_array(
  jsonb_build_object('title','1. Formular hipótese','instruction','Observe o problema, escolha uma previsão e diga qual pista a sustenta.','activity','Registre hipótese sem apagar depois do resultado.','support','Foto ampliada, leitura em voz alta e opções visuais.'),
  jsonb_build_object('title','2. Observar e comparar','instruction','Siga o procedimento seguro e registre o que aconteceu.','activity',guided,'support','Tabela antes-durante-depois e modelagem do professor.'),
  jsonb_build_object('title','3. Concluir e aplicar','instruction','Responda à pergunta usando dados e aplique a ideia em novo caso.','activity',independent,'support','Resposta oral, apontada, tabelada, desenhada, fotografada, digitada ou escrita.')
 ),
 jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese associada a uma pista.'),jsonb_build_object('page',2,'answer','Observação e comparação coerentes.'),jsonb_build_object('page',3,'answer',answer,'teacher_note','Registre evidência citada, apoio eficaz e próximo passo.')),
 jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','table','drawing','photo','typing','writing'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'sensory_exit',true,'low_distraction',true,'hands_on',true,'safety_screened',true,'adult_supervision',true,'print','grayscale-safe'),
 true,true,true,'published','/escola-brilha/curso/ciencias-3ano'
FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
