-- Biblioteca Inclusiva · Geografia do 9º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF09GE01','Da bipolaridade à multipolaridade','Analisar mudanças da ordem mundial por atores, alianças, redes e diferentes escalas.'),
('EF09GE02','Poder e nova ordem mundial','Comparar dimensões econômica, política, militar, tecnológica e cultural do poder global.'),
('EF09GE03','Corporações e organismos mundiais','Avaliar como corporações e organismos econômicos influenciam decisões e territórios.'),
('EF09GE04','Manifestações culturais e minorias','Reconhecer diversidade cultural e reivindicações por direitos sem expor identidades pessoais.'),
('EF09GE05','Europa e Ásia na ordem mundial','Comparar papéis e interdependências de países e blocos europeus e asiáticos.'),
('EF09GE06','Integração europeia','Analisar formação, funcionamento, potencialidades e tensões da integração europeia.'),
('EF09GE07','Europa: economia, política e população','Relacionar redes econômicas, dinâmicas populacionais e desigualdades territoriais europeias.'),
('EF09GE08','Espaço pós-soviético','Analisar fragmentação territorial, redes e relações de poder no espaço pós-soviético.'),
('EF09GE09','Rússia e Leste Europeu','Comparar fatores energéticos, econômicos e geopolíticos no Leste Europeu com fontes atualizadas.'),
('EF09GE10','Ascensão chinesa','Explicar transformações econômicas e territoriais ligadas à ascensão chinesa.'),
('EF09GE11','Redes e disputas tecnológicas','Analisar infraestrutura, comércio e tecnologia nas relações entre China, Ásia e mundo.'),
('EF09GE12','Oriente Médio e recursos estratégicos','Relacionar fronteiras, petróleo, água e redes de poder com abordagem informativa e não gráfica.'),
('EF09GE13','Diversidade e geopolítica do Oriente Médio','Analisar diversidade cultural, religiosa e política sem reduzir grupos a conflitos ou estereótipos.'),
('EF09GE14','Produção agropecuária europeia e asiática','Comparar sistemas agropecuários por fatores naturais, tecnologia, políticas e relações de trabalho.'),
('EF09GE15','Industrialização europeia e asiática','Relacionar indústria, energia, inovação, redes urbanas, trabalho e impactos ambientais.'),
('EF09GE16','Globalização e impactos ambientais','Analisar impactos ambientais globais, responsabilidades diferenciadas e escalas de ação.'),
('EF09GE17','Acordos e sustentabilidade global','Avaliar acordos climáticos e soluções por evidência, equidade, viabilidade e governança.'),
('EF09GE18','Cartografia da Europa, Ásia e Oceania','Interpretar mapas temáticos e anamorfoses sem confundir variável representada com área territorial.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-9ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de síntese geopolítica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes atuais, plurais e seguras','content',jsonb_build_array('Use mapas, gráficos, documentos e dados públicos agregados de instituições identificadas; nunca peça religião, etnia, nacionalidade, renda, posicionamento político, endereço, geolocalização ou história familiar do estudante.','Guerra Fria, colonialismo, migrações, extremismo, disputas e conflitos atuais devem ser abordados historicamente, de modo informativo e não gráfico, sem encenação, simulação estratégica ou atribuição de culpa coletiva.')),
 jsonb_build_object('heading','Evite simplificações culturais e geopolíticas','content',jsonb_build_array('Não reduza povos, religiões, minorias, Europa, Ásia, Oriente Médio ou Oceania a blocos homogêneos; mostre diversidade interna, agência, direitos e mudanças no tempo.','Diferencie descrição, interpretação e julgamento; sinalize quando dados ou alianças podem ter mudado e exija data e fonte.')),
 jsonb_build_object('heading','Modele a síntese multicausal','content',jsonb_build_array('Verifique autoria, instituição, data, recorte, escala, variável, método e interesse; triangule ao menos duas fontes quando houver controvérsia.','Construa matriz de atores, interesses, recursos, redes, escalas, causas e consequências; teste explicações alternativas e reconheça incertezas.','Mapas, anamorfoses e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual, tabela equivalente ou alternativa tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos densos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e ofereça pistas graduadas e pausa.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, matriz de atores, mapa conceitual, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões triangulando fontes, escalas, atores e evidências.'))))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar e verificar','instruction','Defina questão, período, território, escala e conceitos; verifique autoria, data, método e propósito.','activity','Registre duas evidências, uma divergência e uma informação que precisa ser atualizada.','support','Glossário, texto segmentado, leitura mediada e fonte ampliada, descrita ou tabular.'),jsonb_build_object('title','2. Triangular e modelar','instruction','Compare ao menos duas fontes e mapeie atores, interesses, redes, causas e consequências.','activity','Construa matriz de atores, mapa conceitual, gráfico acessível ou cenário comparativo sobre '||lower(title)||'.','support','Exemplo resolvido, dados em camadas e pistas graduadas.'),jsonb_build_object('title','3. Sintetizar e avaliar','instruction','Apresente tese, evidências convergentes e divergentes, alternativa e grau de incerteza.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade, governança e efeitos indiretos.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Delimita questão e identifica evidências, divergência e necessidade de atualização.'),jsonb_build_object('page',2,'answer','Triangula fontes e representa relações sem atribuir culpa coletiva.'),jsonb_build_object('page',3,'answer','Síntese sustentada, incerteza explícita e proposta avaliada por critérios.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, religião, localização, renda ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','actor_matrix','concept_map','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'current_source_date_required',true,'source_triangulation',true,'no_live_geolocation',true,'no_nationality_collection',true,'no_ethnicity_collection',true,'no_religion_collection',true,'no_income_collection',true,'no_political_opinion_collection',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'no_collective_blame',true,'minority_rights_context',true,'religious_cultural_anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-9ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
