-- Biblioteca Inclusiva · História do 9º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF09HI01','unidade-4/aula-02-republica-pos-abolicao.ts','República e pós-abolição'),('EF09HI02','unidade-4/aula-01-era-vargas.ts','República e transformações políticas'),('EF09HI03','unidade-4/aula-02-republica-pos-abolicao.ts','Protagonismo negro na República'),('EF09HI04','unidade-4/aula-02-republica-pos-abolicao.ts','Povos indígenas na República'),('EF09HI05','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Urbanização e modernização'),('EF09HI06','unidade-4/aula-01-era-vargas.ts','Era Vargas e mundo do trabalho'),('EF09HI07','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Diversidade e cidadania'),('EF09HI08','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Direitos das mulheres'),('EF09HI09','unidade-4/aula-03-urbanizacao-diversidade-direitos.ts','Questões indígena e negra contemporâneas'),
('EF09HI10','unidade-1/aula-01-primeira-guerra-russa.ts','Primeira Guerra Mundial'),('EF09HI11','unidade-1/aula-01-primeira-guerra-russa.ts','Revolução Russa e seus desdobramentos'),('EF09HI12','unidade-2/aula-01-crise-totalitarismo.ts','Crise de 1929 e totalitarismos'),('EF09HI13','unidade-3/aula-01-segunda-guerra-holocausto.ts','Segunda Guerra Mundial e genocídio nazista'),('EF09HI14','unidade-3/aula-02-colonialismo-resistencias.ts','Colonialismo e resistências na África e Ásia'),('EF09HI15','unidade-7/aula-07-onu-organismos.ts','Organização das Nações Unidas'),('EF09HI16','unidade-7/aula-07-onu-organismos.ts','Organismos multilaterais e ordem mundial'),
('EF09HI17','unidade-6/aula-07-brasil-1946-1964.ts','Brasil entre 1946 e 1964'),('EF09HI18','unidade-6/aula-07-brasil-1946-1964.ts','Transformações sociais e culturais no Brasil'),('EF09HI19','unidade-6/aula-02-golpe-memoria-justica.ts','Golpe de 1964, memória e justiça'),('EF09HI20','unidade-6/aula-03-resistencias-reorganizacao.ts','Resistências e reorganização democrática'),('EF09HI21','unidade-6/aula-04-indigenas-quilombolas-desenvolvimentismo.ts','Indígenas, quilombolas e desenvolvimentismo'),('EF09HI22','unidade-6/aula-05-diretas-ja.ts','Diretas Já e redemocratização'),('EF09HI23','unidade-6/aula-06-cf88-direitos.ts','Constituição de 1988 e direitos'),
('EF09HI24','unidade-7/aula-02-brasil-pos-1989.ts','Brasil pós-1989'),('EF09HI25','unidade-7/aula-03-sociedade-civil.ts','Sociedade civil e participação'),('EF09HI26','unidade-7/aula-04-violencia-marginalizados.ts','Direitos humanos e populações marginalizadas'),('EF09HI27','unidade-7/aula-05-brasil-globalizacao.ts','Brasil e globalização'),('EF09HI28','unidade-5/aula-02-tensoes-dentro-dos-blocos.ts','Tensões dentro dos blocos da Guerra Fria'),('EF09HI29','unidade-5/aula-03-ditaduras-america-latina.ts','Ditaduras na América Latina'),('EF09HI30','unidade-5/aula-03-ditaduras-america-latina.ts','Contestações e resistências latino-americanas'),('EF09HI31','unidade-5/aula-04-descolonizacao.ts','Descolonização da África e Ásia'),
('EF09HI32','unidade-7/aula-01-globalizacao-digital.ts','Globalização e mudanças sociais'),('EF09HI33','unidade-7/aula-01-globalizacao-digital.ts','Era digital, informação e trabalho'),('EF09HI34','unidade-7/aula-06-neoliberalismo.ts','Políticas neoliberais e globalização'),('EF09HI35','unidade-7/aula-08-terrorismo-migracoes.ts','Terrorismo, migrações e conflitos contemporâneos'),('EF09HI36','unidade-7/aula-09-diversidades.ts','Diversidades e identidades no século XXI')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-9ano/'||rel source_key,title,'Analisar criticamente '||lower(title)||' usando fontes, cronologia, causalidade, conceitos, memória e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize o tempo presente','content',jsonb_build_array('Diferencie democracia, autoritarismo, totalitarismo, golpe, revolução, genocídio, colonialismo e terrorismo sem banalizar ou igualar fenômenos distintos.','Guerras, genocídios, ditaduras, perseguições e violações de direitos devem ser tratados de modo informativo, não gráfico e adequado à idade; não exiba imagens chocantes nem proponha encenação de violência, opressão ou sofrimento.','Inclua protagonismo negro, indígena, quilombola, feminino, juvenil, trabalhador, migrante e de pessoas com deficiência sem reduzir grupos a vítimas.')),
 jsonb_build_object('heading','Verificar fontes, memória e desinformação','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de documentos, imprensa, propaganda, estatísticas, testemunhos publicados e mídias digitais.','Diferencie fato documentado, interpretação historiográfica, memória, opinião, propaganda e desinformação; verifique afirmações controversas em fontes institucionais e pesquisas reconhecidas.','Analise causas múltiplas, escalas local e global, continuidades, rupturas, responsabilidades institucionais e resistências, sem falsa equivalência entre evidência e negação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida fontes e textos em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, gravada, digitada, escrita ou com tecnologia assistiva.','Não solicite posição partidária, experiência de violência, discriminação, migração, religião, raça ou identidade pessoal do estudante.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco processos usando contexto, cronologia, causalidade, conceito, fonte verificada, perspectiva e limite interpretativo.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e verificar fontes','instruction','Identifique período, escala, grupos, autoria, finalidade, linguagem, evidências, silêncios e limites.','activity','Compare fontes e classifique fato documentado, interpretação, memória, propaganda ou opinião.','support','Glossário, linha do tempo, mapa, fonte ampliada e exemplo resolvido.'),jsonb_build_object('title','2. Explicar processos e disputas','instruction','Relacione causas, estruturas, decisões, resistências, mudanças, permanências e consequências.','activity','Monte matriz causal, mapa de fluxos ou cronologia de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar e revisar','instruction','Formule argumento com evidências verificadas, reconheça agência, outra interpretação e limites sem falsa equivalência.','activity','Cite fontes, confronte contraexemplo e revise a conclusão.','support','Resposta oral, apontada, mapeada, diagramada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa e verifica fontes, perspectivas e limites.'),jsonb_build_object('page',2,'answer','Explica processo por causas múltiplas e evidências.'),jsonb_build_object('page',3,'answer','Argumento verificável, contextualizado e aberto a revisão.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados pessoais e políticos sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'source_verification',true,'anti_disinformation',true,'marginalized_groups_agency',true,'memory_and_justice',true,'non_graphic',true,'no_violence_roleplay',true,'no_shocking_media',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-9ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
