-- Biblioteca Inclusiva · Ensino Religioso do 6º ano completo.
-- Abordagem não confessional, com estudo contextualizado de textos, narrativas, ritos e símbolos.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06ER01','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-1/aula-01-tradicao-escrita.ts','Tradição escrita e memória','Reconhecer o papel da tradição escrita no registro e na preservação de memórias, acontecimentos e ensinamentos religiosos.'),
('EF06ER02','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-2/aula-01-diversidade-textos.ts','Diversidade de textos religiosos','Reconhecer e valorizar a diversidade de textos religiosos escritos e tradições orais, considerando autoria, comunidade e contexto.'),
('EF06ER03','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-3/aula-01-ensinamentos-viver.ts','Ensinamentos sobre modos de viver','Reconhecer em textos religiosos ensinamentos relacionados a modos de ser, conviver e cuidar, sem convertê-los em regra obrigatória para a turma.'),
('EF06ER04','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-4/aula-01-usos-diversos.ts','Diferentes usos dos textos religiosos','Identificar diferentes usos de textos religiosos pelas comunidades, estudando finalidade e contexto sem executar práticas sagradas.'),
('EF06ER05','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-5/aula-01-interpretacao-textos.ts','Interpretação dos textos religiosos','Discutir como diferentes tradições e lideranças interpretam seus textos, reconhecendo diversidade interna e autoridade comunitária.'),
('EF06ER06','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-6/aula-01-mitos-ritos-textos.ts','Mitos, ritos, símbolos e textos','Reconhecer relações entre narrativas, textos, ritos e símbolos em diferentes tradições por análise documental não imersiva.'),
('EF06ER07','src/escola-brilha/curso-v4/ensino-religioso-6ano/unidade-7/aula-01-relacao-mito-rito-simbolo.ts','Relações entre mito, rito e símbolo','Explicar como mito, rito e símbolo se relacionam em práticas celebrativas sem reproduzir ou dramatizar a prática estudada.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Ensino não confessional','content',jsonb_build_array('Explique que a aula estuda textos, narrativas, símbolos e práticas como manifestações religiosas e culturais; conhecer não significa acreditar, aderir, concordar ou praticar.','Não conduza oração, recitação devocional, meditação religiosa, rito, canto, dança, gesto, dramatização, oferenda, uso ritual de objeto ou representação de divindade. Ofereça análise documental neutra.','Não peça religião, não religião, tradição familiar, texto sagrado pessoal, local frequentado, fotografia, experiência íntima ou justificativa de crença. Recusa e alternativa neutra não reduzem a avaliação.')),
 jsonb_build_object('heading','Fontes e interpretação','content',jsonb_build_array('Utilize excertos breves, paráfrases e imagens autorizadas, licenciadas ou em domínio público; informe fonte, tradução, autoria quando conhecida, comunidade, gênero, época e finalidade. Não reproduza obra extensa.','Diferencie descrição, interpretação acadêmica e interpretação interna da tradição. Apresente diversidade dentro de cada comunidade e não transforme uma liderança em porta-voz de todas as pessoas.','Mito não significa mentira. Compare função, estrutura e contexto sem hierarquizar tradições nem usar textos religiosos para validar ou invalidar explicações científicas.')),
 jsonb_build_object('heading','Análise acessível e respeitosa','content',jsonb_build_array('Antecipe vocabulário potencialmente desconhecido; use organizador visual com texto ou narrativa, contexto, ensinamento, uso, símbolo e evidência.','Quando houver rito ou celebração, analise material fornecido por descrição, fotografia autorizada, diagrama ou vídeo com legenda e transcrição; não peça encenação, imitação, vestimenta ou manuseio de objeto sagrado.','Aceite apontar, selecionar, ordenar cartões, comunicação alternativa, quadro comparativo, digitação, escrita, fala opcional ou áudio privado; nunca obrigue leitura pública.')),
 jsonb_build_object('heading','Critério','content','Identifica e relaciona quatro de cinco elementos da habilidade com evidência, contexto, linguagem respeitosa e o modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler o contexto','instruction','Identifique fonte, comunidade, gênero, época, finalidade e modo de transmissão no material fornecido.','activity','Associe cartões de contexto a excertos breves, paráfrases, descrições ou imagens sobre '||lower(title)||'.','support','Texto segmentado, leitura fácil, glossário visual, fonte ampliada, descrição de imagem, áudio regulável, legenda e transcrição.'),jsonb_build_object('title','2. Analisar relações','instruction','Relacione narrativa ou texto, ensinamento, uso, rito e símbolo somente quando os elementos estiverem documentados.','activity','Complete quadro comparativo e destaque uma evidência para cada relação, sem hierarquizar tradições.','support','Modelo resolvido, cartões móveis, código por forma e rótulo, pista gradual, mediador e tempo ampliado.'),jsonb_build_object('title','3. Explicar sem praticar','instruction','Explique a relação observada como estudo cultural e religioso, sem reproduzir a prática.','activity','Produza mapa de conceitos, sequência visual, resposta curta ou áudio privado e revise fonte, contexto e termos.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica fonte, comunidade, gênero, época e finalidade sem inferir a crença do estudante.'),jsonb_build_object('page',2,'answer','Relaciona elementos documentados e reconhece interpretações possíveis sem generalização ou hierarquia.'),jsonb_build_object('page',3,'answer','Explica com evidência, contexto e linguagem respeitosa sem executar prática religiosa.','teacher_note','Registre somente estratégia e apoio eficaz; não registre crença, não crença, voz, imagem, comunidade frequentada ou dado familiar.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','concept_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_public_reading',true,'no_forced_prayer',true,'no_forced_recitation',true,'no_forced_ritual',true,'no_sacred_practice_simulation',true,'no_sacred_object_handling',true,'documentary_analysis_only',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_personal_sacred_text_request',true,'no_worship_place_disclosure',true,'no_personal_experience_request',true,'privacy_preserving',true,'compare_provided_materials_only',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'science_religion_method_distinction',true,'internal_diversity',true,'community_authority',true,'no_identity_impersonation',true,'brief_authorized_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
