-- Biblioteca Inclusiva · Ensino Religioso do 8º ano completo (EF08ER01–EF08ER07).
-- A BNCC oficial inclui EF08ER07; a aula antiga da unidade 6 tem o código EF08ER06 desativado pelo curso.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF08ER01','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-1/aula-01-crencas-escolhas.ts','Crenças, convicções e escolhas','Discutir como crenças e convicções podem influenciar escolhas pessoais e coletivas sem solicitar posicionamento íntimo do estudante.'),
('EF08ER02','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-2/aula-01-etica-tradicoes.ts','Princípios éticos das tradições e filosofias','Analisar filosofias de vida, manifestações e tradições religiosas, destacando princípios éticos com contexto e diversidade interna.'),
('EF08ER03','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-3/aula-01-vida-e-morte.ts','Concepções de mundo, vida e morte','Analisar concepções de mundo, vida e morte em diferentes doutrinas de modo informativo, não gráfico e sem relatos pessoais.'),
('EF08ER04','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-4/aula-01-religiao-esfera-publica.ts','Religião e esfera pública','Discutir como filosofias, tradições e instituições religiosas podem influenciar política, saúde, educação e economia usando fontes e casos coletivos.'),
('EF08ER05','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-5/aula-01-estado-laico.ts','Possibilidades e limites na esfera pública','Debater possibilidades e limites da atuação de tradições religiosas na esfera pública à luz do Estado laico, dos direitos e da igualdade.'),
('EF08ER06','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-5/aula-02-liberdade-politicas-publicas.ts','Liberdade em práticas, projetos e políticas','Analisar práticas, projetos e políticas públicas que promovam liberdade de pensamento, crença e convicção com evidências verificáveis.'),
('EF08ER07','src/escola-brilha/curso-v4/ensino-religioso-8ano/unidade-7/aula-01-transmissao-tradicoes.ts','Religiões, mídias e tecnologias','Analisar usos de mídias e tecnologias por diferentes denominações religiosas, considerando finalidade, autoria, alcance, privacidade e segurança digital.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional e segura','content',jsonb_build_array('Estude crenças, filosofias, doutrinas e instituições como fenômenos culturais e sociais; conhecer não significa acreditar, concordar, aderir ou praticar.','Não conduza oração, rito, debate confessional, campanha política ou religiosa, simulação de luto, cerimônia, aconselhamento espiritual ou representação de identidade. Use casos fictícios ou coletivos.','Não solicite crença, não crença, religião familiar, opinião política, experiência de perda, informação de saúde, comunidade frequentada ou conteúdo de conta pessoal. Aceite alternativa neutra e recusa sem prejuízo.')),
 jsonb_build_object('heading','Esfera pública e direitos','content',jsonb_build_array('Estado laico não significa Estado contra religiões: garante liberdade de consciência e tratamento público igual, sem religião oficial nem imposição de crença.','Analise influência na política, saúde, educação e economia por fontes, ações, interesses, efeitos, direitos e limites. Diferencie opinião religiosa, evidência científica, norma jurídica e política pública.','Não apresente prática religiosa como substituta de saúde, proteção, educação ou serviço público. O professor não diagnostica, prescreve, recomenda adesão religiosa nem dirige posição político-partidária.')),
 jsonb_build_object('heading','Mídia, fontes e acessibilidade','content',jsonb_build_array('Use postagens e perfis fictícios ou capturas anonimizadas fornecidas pelo professor. Não exija conta, acesso a rede social, contato com desconhecidos, publicação, rastreamento, geolocalização ou coleta de dados.','Verifique autoria, data, fonte, finalidade, patrocínio, edição e evidência; discuta alcance e recomendação algorítmica sem afirmar que popularidade comprova verdade ou representatividade.','Antecipe vocabulário; ofereça texto segmentado, descrição de imagem, legenda, transcrição, áudio regulável, cartões e matriz de fontes. Aceite apontar, comunicação alternativa, escrita, digitação, fala opcional ou áudio privado.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco elementos da habilidade com fonte, contexto, direito, evidência e efeito, no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Identificar e classificar','instruction','Leia caso fictício ou fonte fornecida e diferencie crença, princípio ético, fato, opinião, evidência, norma e política.','activity','Classifique quatro elementos relacionados a '||lower(title)||' sem declarar opinião ou experiência pessoal.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, descrição de imagem, legenda, transcrição e áudio regulável.'),jsonb_build_object('title','2. Verificar contexto e direitos','instruction','Registre autoria, data, finalidade, interesse, público, direito envolvido, evidência e limite.','activity','Compare duas fontes ou propostas usando matriz acessível e dados públicos agregados ou fictícios.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, código por forma e rótulo e mediação.'),jsonb_build_object('title','3. Explicar efeitos e limites','instruction','Explique influência, efeito, direito e limite sem campanha, exposição pessoal ou publicação.','activity','Produza quadro, mapa, sequência, texto curto ou áudio privado para o caso fornecido.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Classifica elementos sem presumir crença, convicção, saúde, luto ou posição política.'),jsonb_build_object('page',2,'answer','Compara fontes e identifica direito, evidência, interesse e limite pertinente.'),jsonb_build_object('page',3,'answer','Explica influência e efeito com linguagem respeitosa, fonte e proposta compatível com direitos.','teacher_note','Registre apenas estratégia e apoio eficaz; não registre crença, política, saúde, perda, voz, conta, comunidade ou histórico digital.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','rights_map','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_public_position',true,'no_forced_religious_practice',true,'no_grief_simulation',true,'historical_and_doctrinal_non_graphic',true,'fictional_or_collective_cases',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_political_opinion_collection',true,'no_health_disclosure',true,'no_loss_disclosure',true,'privacy_preserving',true) || jsonb_build_object('secular_state_accuracy',true,'freedom_of_conscience',true,'human_rights_framework',true,'science_law_religion_distinction',true,'professional_services_not_replaced',true,'no_diagnosis',true,'no_partisan_direction',true,'provided_fictional_or_anonymized_media',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_tracking',true,'no_geolocation',true,'source_date_purpose_sponsorship_check',true,'algorithmic_literacy',true,'popularity_is_not_evidence',true,'internal_diversity',true,'no_belief_hierarchy',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-8ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
