-- Biblioteca Inclusiva · Arte do 1º ao 5º ano · códigos compartilhados EF15AR.
WITH lessons(code,title,goal) AS (VALUES
('EF15AR01','Artes visuais de diferentes contextos','Apreciar formas distintas de artes visuais, reconhecendo contextos, sentidos e diversidade cultural.'),
('EF15AR02','Elementos das artes visuais','Explorar ponto, linha, forma, cor, espaço, movimento, textura, luz e volume por diferentes percepções.'),
('EF15AR03','Matrizes estéticas e culturais','Reconhecer influências culturais nas artes visuais sem hierarquizar povos ou apropriar práticas sagradas.'),
('EF15AR04','Materialidades nas artes visuais','Experimentar materiais e suportes seguros, acessíveis e adequados às necessidades sensoriais e motoras.'),
('EF15AR05','Criação em artes visuais','Criar individual e coletivamente, fazendo escolhas, experimentando e revisando processos.'),
('EF15AR06','Diálogo sobre a criação','Descrever escolhas e dialogar sobre produções sem classificar trabalhos ou corpos como melhores.'),
('EF15AR07','Sistemas das artes visuais','Relacionar artistas, artesãos, curadores, educadores, públicos, espaços e instituições culturais.'),
('EF15AR08','Danças de diferentes contextos','Apreciar e experimentar danças diversas com respeito cultural, consentimento e alternativas de participação.'),
('EF15AR09','Relações corporais na dança','Perceber relações entre partes do corpo e corpo inteiro sem impor padrão corporal ou amplitude de movimento.'),
('EF15AR10','Espaço e ritmo na dança','Explorar direções, níveis, trajetórias, pausas e ritmos por movimentos possíveis para cada estudante.'),
('EF15AR11','Criação e improvisação em dança','Criar e revisar sequências de movimento individualmente e em grupo, sem contato físico obrigatório.'),
('EF15AR12','Reflexão e respeito na dança','Compartilhar percepções sobre dança sem ridicularização, comparação corporal ou exposição forçada.'),
('EF15AR13','Músicas de diferentes contextos','Apreciar músicas de culturas e épocas diversas com escuta regulável e respeito à autoria.'),
('EF15AR14','Elementos da música','Explorar altura, intensidade, timbre, melodia e ritmo com recursos visuais, táteis e sonoros reguláveis.'),
('EF15AR15','Fontes sonoras','Investigar sons do corpo, natureza, objetos, voz e instrumentos com segurança auditiva e material.'),
('EF15AR16','Notação e registro musical','Criar e interpretar registros convencionais ou inventados em formatos visuais, táteis ou digitais.'),
('EF15AR17','Criação musical','Improvisar, compor e sonorizar histórias em processos colaborativos com papéis flexíveis.'),
('EF15AR18','Teatro em diferentes contextos','Apreciar manifestações teatrais e reconhecer múltiplas funções, espaços e modos de participação.'),
('EF15AR19','Teatralidades no cotidiano','Investigar gesto, voz, ação e espaço sem imitar pessoas reais para ridicularizar ou expor.'),
('EF15AR20','Elementos teatrais','Experimentar corpo, voz, espaço e transformação simbólica usando objetos e cenários seguros.'),
('EF15AR21','Criação teatral coletiva','Planejar, improvisar, apresentar e revisar cenas com escuta, consentimento e divisão flexível de papéis.'),
('EF15AR22','Personagens, movimento e voz','Criar personagens sem caricaturar deficiência, etnia, religião, gênero, sotaque ou condição social.'),
('EF15AR23','Artes integradas','Integrar artes visuais, dança, música e teatro em torno de uma intenção compartilhada.'),
('EF15AR24','Matrizes culturais brasileiras','Conhecer brincadeiras, danças, histórias e canções de diferentes matrizes com fonte, contexto e respeito.'),
('EF15AR25','Patrimônio cultural','Distinguir patrimônio material e imaterial e propor valorização sem tocar, remover ou danificar bens.'),
('EF15AR26','Arte e tecnologia','Criar com recursos digitais respeitando autoria, privacidade, consentimento e proteção de dados.')
), normalized AS (
 SELECT code,'src/escola-brilha/data/'||code||'.ts' AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º ao 5º Ano','Arte',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia de experiência artística inclusiva — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com segurança e escolha','content',jsonb_build_array('Ofereça materiais atóxicos e sem pontas, lâminas, chama, solventes ou cola quente ao alcance dos estudantes; verifique alergias e disponibilize alternativa sem contato com o material.','Antecipe som, luz, textura, cheiro, movimento e contato; permita abafador, volume reduzido, pausa, lugar calmo e participação sem tocar, dançar, cantar, atuar ou ser fotografado.','Não publique voz, imagem, nome, localização ou obra identificável sem autorização apropriada; use cenário e dados fictícios.')),
 jsonb_build_object('heading','Garanta cultura, autoria e dignidade','content',jsonb_build_array('Contextualize autoria, povo, território, época e função; não apresente cultura como fantasia, não reproduza prática sagrada fora do contexto e não classifique uma matriz como superior.','Use obras autorizadas, licenciadas ou em domínio público conforme aplicável; trabalhe trechos necessários sem reproduzir letras ou obras integrais protegidas.','Não avalie aparência, corpo, fala, visão, audição, coordenação, afinação ou virtuosismo como se fossem compreensão artística.')),
 jsonb_build_object('heading','Diferencie a progressão','content',jsonb_build_array('1º–2º anos: observar, escolher e experimentar uma variável com modelo concreto e instrução única.','3º–4º anos: comparar referências, combinar duas ou mais escolhas, explicar intenção e revisar um detalhe.','5º ano: pesquisar fonte, planejar processo, testar alternativas, documentar decisões, realizar curadoria e avaliar o resultado.')),
 jsonb_build_object('heading','Critério inclusivo','content','Registre intenção, experimentação, percepção, escolhas, revisão e diálogo; aceite participação individual, em dupla, coletiva, de bastidor ou por tecnologia assistiva.')))),
jsonb_build_array(jsonb_build_object('title','1. Apreciar e perceber','instruction','Observe, escute ou explore uma referência artística em modalidade acessível.','activity','Escolha dois elementos percebidos e uma pergunta sobre '||lower(title)||'.','support','Audiodescrição, legenda, imagem ampliada, recurso tátil, volume regulável e tempo de processamento.'),jsonb_build_object('title','2. Experimentar e criar','instruction','Escolha materiais, movimentos, sons, palavras, imagens ou funções compatíveis com seu modo de participar.','activity','Crie uma versão, compare o efeito de uma mudança e revise uma escolha.','support','Modelo concreto, etapas visuais, ferramenta adaptada, papel de bastidor e alternativa sem desempenho público.'),jsonb_build_object('title','3. Compartilhar e refletir','instruction','Apresente processo ou resultado apenas no formato consentido e explique uma escolha.','activity','Descreva intenção, descoberta, revisão e próximo teste sem julgar pessoas ou corpos.','support','Fala, apontamento, cartões, exposição silenciosa, áudio, vídeo sem identificação, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Percebe dois elementos por modalidade acessível e formula pergunta pertinente.'),jsonb_build_object('page',2,'answer','Experimenta, faz escolha intencional e revisa ao menos um aspecto.'),jsonb_build_object('page',3,'answer','Comunica processo ou reflexão no formato consentido e respeita leituras diferentes.','teacher_note','Registre escolhas e apoios eficazes; não registre diagnóstico, recusa sensorial como falha, imagem, voz ou identidade cultural pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','visual_art','movement_optional','sound_optional','backstage_role','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'sensory_preview',true,'volume_control',true,'no_forced_touch',true,'no_forced_performance',true,'no_forced_recording',true,'privacy_preserving',true,'fictional_scenarios',true,'safe_nontoxic_materials',true,'no_student_access_to_blades_flame_solvents_hot_glue',true,'allergy_alternative',true,'body_dignity',true,'cultural_context_required',true,'sacred_practice_respect',true,'anti_stereotype',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
