-- Biblioteca Inclusiva · Geografia do 7º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF07GE01','Formação territorial do Brasil','Analisar a formação territorial brasileira por mapas, tratados e processos históricos de modo crítico e não gráfico.'),
('EF07GE02','Fluxos econômicos, populacionais e território','Relacionar fluxos de mercadorias, pessoas e capitais à organização do território brasileiro.'),
('EF07GE03','Territorialidades e direitos','Reconhecer territorialidades, direitos e protagonismo de povos indígenas, quilombolas e comunidades tradicionais.'),
('EF07GE04','Dinâmica demográfica','Interpretar indicadores, pirâmides etárias e transição demográfica usando dados públicos agregados.'),
('EF07GE05','Do mercantilismo ao capitalismo','Comparar processos econômicos históricos e sua influência na organização territorial e nas desigualdades.'),
('EF07GE06','Produção, circulação e consumo','Analisar redes de produção, circulação e consumo e seus efeitos sociais, econômicos e ambientais.'),
('EF07GE07','Redes de transporte e comunicação','Avaliar como redes de transporte e comunicação integram territórios e distribuem acessos de modo desigual.'),
('EF07GE08','Industrialização e urbanização','Relacionar industrialização, urbanização, metropolização e desigualdades socioespaciais no Brasil.'),
('EF07GE09','Mapas temáticos do Brasil','Interpretar mapas temáticos brasileiros por título, fonte, legenda, escala, recorte e variável representada.'),
('EF07GE10','Gráficos e indicadores','Ler e comparar gráficos e indicadores socioeconômicos sem confundir associação estatística com causalidade.'),
('EF07GE11','Complexos regionais e diversidade','Analisar diversidade natural, econômica e cultural das regiões sem reduzir territórios a estereótipos.'),
('EF07GE12','Unidades de conservação','Distinguir tipos e objetivos de unidades de conservação e avaliar proteção ambiental e participação social.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-7ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise territorial — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes seguras e contextualizadas','content',jsonb_build_array('Use mapas históricos, mapas temáticos, gráficos e dados públicos agregados; nunca peça endereço, geolocalização, renda, origem familiar, migração pessoal, autodeclaração étnica, opinião política ou dados demográficos da turma.','Ao tratar expansão territorial, colonização, conflitos e regimes políticos, use linguagem histórica, informativa e não gráfica, explicando direitos, agentes, disputas e consequências sem simulação imersiva.')),
 jsonb_build_object('heading','Garanta respeito territorial e regional','content',jsonb_build_array('Apresente povos indígenas, quilombolas e comunidades tradicionais no presente, com diversidade, protagonismo e direitos; não solicite que estudante represente identidade que não é a sua.','Evite reduzir Norte, Nordeste, áreas rurais, periferias ou qualquer população a pobreza, atraso, clima ou um único costume.')),
 jsonb_build_object('heading','Modele a análise','content',jsonb_build_array('Verifique autoria, fonte, data, escala, recorte, variável e método; compare materiais e identifique ausências ou interesses na representação.','Relacione território, população, economia, redes e ambiente; diferencie correlação, causalidade, dado absoluto, proporção e taxa.','Mapas e gráficos devem combinar cor com rótulo, forma, textura, contorno ou padrão e oferecer descrição textual ou tátil.')),
 jsonb_build_object('heading','Rotina adaptativa e critério','content',jsonb_build_array('Segmente textos, antecipe vocabulário, revele dados em camadas, dê uma instrução por vez e aceite pausas e pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, linha do tempo, esquema, áudio, digitação, escrita ou tecnologia assistiva.','Critério: resolve quatro de cinco situações e sustenta três conclusões com evidência, escala e contexto adequados.'))))),
jsonb_build_array(jsonb_build_object('title','1. Interrogar a fonte','instruction','Identifique autoria, data, escala, recorte, variável, método e contexto.','activity','Registre duas evidências, uma ausência e uma pergunta investigável sobre '||lower(title)||'.','support','Glossário, texto segmentado, leitura mediada e fonte ampliada ou descrita.'),jsonb_build_object('title','2. Comparar e explicar','instruction','Cruze mapa, gráfico, texto ou linha do tempo e procure padrões, contrastes e exceções.','activity','Construa quadro comparativo, mapa, gráfico acessível ou cadeia causal.','support','Exemplo resolvido, informação em camadas e pistas graduadas.'),jsonb_build_object('title','3. Argumentar e avaliar','instruction','Apresente conclusão, evidências, limite e explicação alternativa.','activity','Avalie uma proposta por direitos, impacto, escala, viabilidade, equidade e responsabilidade pública.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos da fonte, duas evidências e uma ausência relevante.'),jsonb_build_object('page',2,'answer','Compara materiais e explica padrão sem extrapolar os dados.'),jsonb_build_object('page',3,'answer','Argumento sustentado, limite reconhecido e proposta avaliada por critérios.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre identidade, localização, renda ou opinião política pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','timeline','diagram','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_income_collection',true,'no_family_origin_disclosure',true,'no_ethnicity_collection',true,'no_political_opinion_collection',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'indigenous_quilombola_present_day_respect',true,'territorial_rights_context',true,'regional_anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-7ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
