-- Biblioteca Inclusiva · Filosofia do 9º ano completa.
-- EF09FI01–EF09FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF09FI01','src/escola-brilha/curso-v4/filosofia-9ano/unidade-1/aula-01-frankfurt.ts','Escola de Frankfurt e indústria cultural','Analisar indústria cultural, razão instrumental e mídia como teorias críticas, distinguindo consumo, interpretação e evidência sem condenar gostos pessoais.'),
('EF09FI02','src/escola-brilha/curso-v4/filosofia-9ano/unidade-2/aula-01-fenomenologia-hermeneutica.ts','Fenomenologia e hermenêutica','Comparar descrição da experiência e interpretação situada em Husserl, Heidegger e Gadamer sem exigir relatos íntimos.'),
('EF09FI03','src/escola-brilha/curso-v4/filosofia-9ano/unidade-3/aula-01-estruturalismo-pos.ts','Estruturalismo e pós-estruturalismo','Analisar discurso, poder, diferença e desconstrução como ferramentas interpretativas, sem vigilância ou exposição de identidades da turma.'),
('EF09FI04','src/escola-brilha/curso-v4/filosofia-9ano/unidade-4/aula-01-filosofia-linguagem.ts','Wittgenstein e jogos de linguagem','Investigar significado, uso, contexto e jogos de linguagem por exemplos fictícios, respeitando variação linguística e comunicação alternativa.'),
('EF09FI05','src/escola-brilha/curso-v4/filosofia-9ano/unidade-5/aula-01-etica-bioetica.ts','Ética contemporânea e bioética','Aplicar princípios bioéticos a casos hipotéticos adequados à idade, distinguindo análise filosófica de orientação médica, jurídica ou científica.'),
('EF09FI06','src/escola-brilha/curso-v4/filosofia-9ano/unidade-6/aula-01-filosofia-politica-atual.ts','Hannah Arendt e esfera pública','Analisar responsabilidade, ação, esfera pública e conceitos de Arendt em contexto histórico não gráfico, sem simulação de violência ou propaganda partidária.'),
('EF09FI07','src/escola-brilha/curso-v4/filosofia-9ano/unidade-7/aula-01-filosofia-brasileira-decolonial.ts','Filosofia brasileira e pensamento decolonial','Analisar contribuições de Paulo Freire, Ailton Krenak e pensamentos decoloniais com fontes, contexto e protagonismo dos povos citados.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','9º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Enquadramento e precisão','content',jsonb_build_array('Este material é currículo autoral complementar. O código '||code||' é interno do NeuroBrilha e não habilidade oficial da BNCC do Ensino Fundamental.','Apresente autor, contexto, problema, conceito, argumento, crítica e recepção; estudar uma teoria não exige concordar com ela. Diferencie descrição da tese, aplicação e avaliação.','Evite transformar escolas filosóficas em rótulos fechados. Reconheça divergências entre autores e leituras acadêmicas, além da autoria e diversidade dos pensamentos brasileiros, indígenas e decoloniais.')),
 jsonb_build_object('heading','Temas públicos e sensíveis','content',jsonb_build_array('Use casos fictícios, fontes públicas e dados agregados. Não faça propaganda, votação partidária, teste ideológico ou coleta de opinião política, religião, saúde, genética, família, consumo, identidade ou experiência de discriminação.','Bioética é análise de princípios e conflitos, não orientação médica, jurídica, genética ou científica. Não proponha experimento, procedimento corporal, diagnóstico ou decisão real de saúde; encaminhe dúvidas individuais a responsáveis e profissionais adequados.','Violência histórica, autoritarismo, perseguição e opressão recebem abordagem informativa e não gráfica, sem imagens perturbadoras, dramatização, simulação ou atribuição de papel de vítima ou agressor.')),
 jsonb_build_object('heading','Linguagem, mídia e acesso','content',jsonb_build_array('Não classifique gosto cultural, fala, sotaque, língua, comunicação alternativa ou repertório familiar como inferior. Analise produtos midiáticos fictícios ou fornecidos sem acessar conta pessoal.','Para pensamentos indígenas, use nome do povo quando a fonte permitir, autoria identificada e materiais produzidos ou validados por pessoas e instituições indígenas; não apresente uma voz como representante de todos os povos.','Ofereça texto segmentado, glossário, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa, modelo resolvido e múltiplos modos de resposta.')),
 jsonb_build_object('heading','Critério','content','Compara duas interpretações por fonte, contexto, conceito, argumento, efeito e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar e definir','instruction','Identifique autor, época, problema, conceitos e fonte no material fornecido.','activity','Associe cartões de contexto, conceito e exemplo sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Reconstruir e comparar','instruction','Organize tese, razões, exemplo, objeção, resposta e limite de duas interpretações.','activity','Complete mapa de argumentos usando somente fontes e casos fornecidos.','support','Modelo resolvido, cartões móveis, matriz de fontes, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Aplicar com limites','instruction','Analise caso fictício de mídia, linguagem, bioética ou esfera pública, distinguindo reflexão de orientação profissional.','activity','Produza quadro, sequência, texto curto ou áudio privado com fonte, efeito, direito e limite.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa autor, fonte, problema e conceito sem atribuir identidade ou opinião ao estudante.'),jsonb_build_object('page',2,'answer','Compara argumentos, objeções e limites com evidência.'),jsonb_build_object('page',3,'answer','Aplica conceito a caso fictício e distingue análise filosófica de decisão ou serviço profissional.','teacher_note','Registre apenas estratégia e apoio; não registre voz, política, religião, saúde, genética, família, consumo, identidade ou discriminação pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','source_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'content_preview',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'fictional_cases_only',true,'aggregated_public_data_only',true,'no_partisan_propaganda',true,'no_political_vote',true,'no_ideological_test',true,'no_political_opinion_collection',true,'no_belief_disclosure',true,'no_health_disclosure',true,'no_genetic_disclosure',true,'no_family_disclosure',true,'no_consumption_profile_collection',true,'no_identity_disclosure',true,'no_discrimination_experience_collection',true,'privacy_preserving',true,'bioethics_not_medical_legal_or_genetic_advice',true,'no_body_experiment',true,'no_diagnosis',true,'professional_referral',true,'historical_non_graphic',true,'no_disturbing_images',true,'no_oppression_roleplay',true,'no_victim_aggressor_assignment',true,'no_personal_account_required',true,'no_cultural_taste_hierarchy',true,'linguistic_dignity',true,'aac_dignity',true,'indigenous_authorship_and_authority',true,'no_pan_indigenous_generalization',true,'source_context_reception_check',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-9ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
