-- Biblioteca Inclusiva · História do 2º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF02HI01','unidade-7/aula-02-comunidades-convivencia.ts','Comunidades e espaços de convivência'),
('EF02HI02','unidade-7/aula-02-comunidades-convivencia.ts','Práticas, papéis e convivência'),
('EF02HI03','unidade-6/aula-01-costumes-que-mudaram.ts','Costumes, relações e mudanças'),
('EF02HI04','unidade-2/aula-01-arvore-genealogica.ts','Fontes de histórias pessoais e familiares'),
('EF02HI05','unidade-5/aula-01-objetos-do-passado.ts','Objetos, documentos e memória'),
('EF02HI06','unidade-1/aula-01-ontem-hoje-amanha.ts','Sucessão do tempo: antes, durante e depois'),
('EF02HI07','unidade-1/aula-02-marcadores-tempo.ts','Calendários, relógios e marcadores do tempo'),
('EF02HI08','unidade-4/aula-01-historia-do-bairro.ts','Memórias e história da comunidade'),
('EF02HI09','unidade-3/aula-01-historia-da-escola.ts','Mudanças e permanências na escola'),
('EF02HI10','unidade-6/aula-02-trabalho-ambiente.ts','Trabalho, sobrevivência e natureza'),
('EF02HI11','unidade-6/aula-02-trabalho-ambiente.ts','Impactos do trabalho no ambiente')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-2ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, sequências temporais, comparações e linguagem histórica do 2º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare com acolhimento','content',jsonb_build_array('Use personagens, mapas fictícios, fotografias públicas, objetos ou cartões fornecidos pela escola; nunca exija fotografia, certidão, endereço, religião, ocupação ou relato familiar da criança.','Troque árvore genealógica obrigatória por rede de pessoas importantes ou família fictícia quando necessário.')),
 jsonb_build_object('heading','Investigar fontes e tempo','content',jsonb_build_array('Modele passado, presente e futuro; antes, durante e depois; mudança e permanência.','Compare fonte material, escrita, oral e visual perguntando quem produziu, quando, para quê, o que mostra e o que não permite saber.','Diferencie evidência, lembrança e opinião; memórias podem variar sem que uma pessoa esteja mentindo.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem não estigmatizante ao tratar trabalho, moradia, família, comunidade e mudanças ambientais.')),
 jsonb_build_object('heading','Critério','content','Ordena, compara ou explica quatro de cinco situações usando marcador temporal e evidência da fonte.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler a fonte','instruction','Observe fonte fictícia ou pública e identifique autoria, tempo, pistas e limites.','activity','Marque o que a fonte mostra e uma pergunta que ela não responde.','support','Vocabulário visual, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Ordenar e comparar','instruction','Organize acontecimentos e compare mudanças, permanências e pontos de vista.','activity','Monte linha do tempo, quadro ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar com evidência','instruction','Relacione tempo, espaço, pessoas e ambiente e indique a fonte usada.','activity','Apresente conclusão por fala, sequência, desenho, cartões ou escrita.','support','Resposta oral, apontada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica pista, tempo e limite da fonte.'),jsonb_build_object('page',2,'answer','Ordena ou compara com coerência temporal.'),jsonb_build_object('page',3,'answer','Conclusão ligada à evidência selecionada.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre dados familiares sensíveis.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'family_diversity',true,'fictional_alternative',true,'multiple_perspectives',true,'non_stigmatizing_language',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-2ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
