-- Biblioteca Inclusiva · Ensino Religioso do 5º ano completo.
-- Abordagem não confessional: estudar tradições não exige crença, prática ou exposição pessoal.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF05ER01','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-1/aula-01-acontecimentos-sagrados.ts','Acontecimentos sagrados e memória','Identificar acontecimentos sagrados de diferentes culturas e tradições como parte da preservação da memória, sem hierarquizar crenças.'),
('EF05ER02','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Mitos de criação em diferentes culturas','Identificar mitos de criação em diferentes culturas, distinguindo narrativa religiosa ou cultural de explicação científica sem chamar mito de mentira.'),
('EF05ER03','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Funções e mensagens dos mitos de criação','Reconhecer concepções de mundo, valores, relações e responsabilidades comunicadas por mitos de criação.'),
('EF05ER04','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-4/aula-01-tradicao-oral.ts','Tradição oral e memória religiosa','Reconhecer a importância da tradição oral para preservar memórias e conhecimentos religiosos e culturais.'),
('EF05ER05','src/escola-brilha/curso-v4/ensino-religioso-5ano/unidade-5/aula-01-oralidade-culturas.ts','Oralidade em culturas diversas','Identificar elementos da tradição oral em culturas indígenas, afro-brasileiras e dos povos Rom, Calon e Sinti com linguagem respeitosa e contextualizada.'),
('EF05ER06','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Sábios, anciãos e memória coletiva','Identificar o papel de pessoas mais velhas, sábios e lideranças reconhecidas pelas comunidades na transmissão responsável de memórias.'),
('EF05ER07','src/escola-brilha/curso-v4/ensino-religioso-5ano/aulas-corrigidas.ts','Ensinamentos em textos orais','Reconhecer ensinamentos sobre modos de ser e viver em textos orais sem transformar o conteúdo estudado em regra religiosa obrigatória.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','Ensino Religioso',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Ensino Religioso — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Abordagem não confessional','content',jsonb_build_array('Apresente o conteúdo como conhecimento histórico, cultural e religioso: estudar não significa acreditar, aderir, concordar ou praticar.','Não conduza oração, rito, oferenda, canto, recitação, dramatização de prática sagrada, uso de vestimenta ritual ou representação de divindade. Sempre ofereça atividade neutra equivalente.','Nunca peça que estudante revele religião, ausência de religião, tradição familiar, objeto sagrado, fotografia, experiência íntima ou participação comunitária.')),
 jsonb_build_object('heading','Investigação respeitosa','content',jsonb_build_array('Use excertos breves, paráfrases, imagens autorizadas e fontes produzidas ou validadas pelas próprias comunidades; preserve autoria, contexto, diversidade interna e contemporaneidade.','Diferencie narrativa religiosa ou cultural e explicação científica por finalidade e método. Mito não significa mentira, e nenhuma tradição deve ser tratada como superior, exótica ou homogênea.','Ao abordar povos indígenas, culturas afro-brasileiras e povos Rom, Calon e Sinti, use os nomes específicos disponíveis, reconheça protagonismo atual e não peça imitação de sotaque, canto, rito, liderança ou identidade.')),
 jsonb_build_object('heading','Acesso, escolha e privacidade','content',jsonb_build_array('Antecipe vocabulário e sequência; ofereça leitura segmentada, descrição de imagem, áudio regulável, legenda, transcrição, pausa planejada, cartões e modelo resolvido.','Aceite apontar, selecionar, ordenar cartões, completar quadro comparativo, comunicação alternativa, digitação, escrita, fala opcional ou áudio privado.','Evite exposição individual. Compare apenas materiais fornecidos pelo professor e permita recusa ou troca de qualquer atividade sem redução da avaliação.')),
 jsonb_build_object('heading','Critério','content','Identifica e relaciona pelo menos quatro de cinco elementos da habilidade usando evidências do material, linguagem respeitosa e o modo de resposta acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e contextualizar','instruction','Localize autoria, comunidade, tempo, lugar, gênero e finalidade no material fornecido.','activity','Associe quatro cartões de contexto a trechos, imagens ou resumos sobre '||lower(title)||'.','support','Leitura fácil, pictogramas, fonte ampliada, contraste, descrição de imagem, áudio com legenda e transcrição.'),jsonb_build_object('title','2. Comparar sem hierarquizar','instruction','Organize semelhanças e diferenças sem decidir qual tradição seria melhor ou verdadeira.','activity','Complete quadro com contexto, forma de transmissão, mensagem, evidência e cuidado de linguagem.','support','Modelo resolvido, banco de palavras, cartões móveis, pista gradual e mediador de comunicação.'),jsonb_build_object('title','3. Explicar com respeito','instruction','Escolha uma evidência e explique a relação com a habilidade, sem falar sobre crença pessoal.','activity','Produza resposta curta, sequência visual, mapa de conceitos ou áudio privado e revise termos respeitosos.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica contexto e evidência pertinentes sem atribuir crença ao estudante ou à comunidade inteira.'),jsonb_build_object('page',2,'answer','Compara elementos por finalidade, mensagem e contexto sem hierarquização.'),jsonb_build_object('page',3,'answer','Explicação coerente, respeitosa e sustentada pelo material.','teacher_note','Registre estratégia e apoio eficaz; não registre religião, não religião, tradição familiar, voz, fotografia ou experiência pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','sequencing_cards','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_prayer',true,'no_forced_ritual',true,'no_forced_recitation',true,'no_sacred_practice_simulation',true,'neutral_equivalent_activity',true,'opt_out_without_penalty',true,'non_confessional',true,'no_belief_disclosure',true,'no_nonbelief_disclosure',true,'no_family_religion_disclosure',true,'no_sacred_object_request',true,'no_personal_experience_request',true,'privacy_preserving',true,'compare_provided_materials_only',true,'no_belief_hierarchy',true,'myth_is_not_lie',true,'science_religion_method_distinction',true,'community_authority',true,'indigenous_afro_brazilian_romani_dignity',true,'no_identity_impersonation',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/ensino-religioso-5ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
