-- Biblioteca Inclusiva · História do 4º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF04HI01','unidade-1/aula-02-historia-cidades.ts','História, ação humana e transformações'),
('EF04HI02','unidade-1/aula-01-primeiros-deslocamentos.ts','Mudanças e permanências ao longo do tempo'),
('EF04HI03','unidade-1/aula-02-historia-cidades.ts','Formação e transformação das cidades'),
('EF04HI04','unidade-1/aula-01-primeiros-deslocamentos.ts','Nomadismo, agricultura e ocupação humana'),
('EF04HI05','unidade-2/aula-02-ocupacao-comunicacao.ts','Ocupação do campo e relação com a natureza'),
('EF04HI06','unidade-2/aula-02-ocupacao-comunicacao.ts','Comunicação, circulação e transformações sociais'),
('EF04HI07','unidade-4/aula-01-diaspora-africana.ts','Rotas, comércio e deslocamentos humanos'),
('EF04HI08','unidade-4/aula-01-diaspora-africana.ts','Migração forçada, diáspora africana e resistência'),
('EF04HI09','unidade-5/aula-01-imigracao.ts','Imigrações para o Brasil nos séculos XIX e XX'),
('EF04HI10','unidade-6/aula-01-migracoes-internas.ts','Migrações internas no Brasil'),
('EF04HI11','unidade-6/aula-01-migracoes-internas.ts','Migrações e transformações regionais')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-4ano/'||rel source_key,title,'Investigar e explicar '||lower(title)||' usando fontes, mapas, cronologia, causas, consequências e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','4º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize sem apagar sujeitos','content',jsonb_build_array('Use mapas, linhas do tempo e fontes públicas ou fictícias; não solicite origem, situação migratória ou história familiar da criança.','Diferencie migração voluntária, deslocamento forçado e escravização; não use linguagem que transforme pessoas em mercadorias ou apresente violência de modo gráfico.','Apresente povos africanos e afro-brasileiros e povos indígenas como diversos, com conhecimentos, decisões, resistências, continuidades e presença atual.')),
 jsonb_build_object('heading','Investigue rotas e transformações','content',jsonb_build_array('Compare autoria, contexto, finalidade, evidências, silêncios e limites de mapas, objetos, textos, imagens e relatos publicados.','Relacione deslocamentos a causas e consequências políticas, econômicas, ambientais, culturais e tecnológicas, evitando explicações únicas.','Analise circulação e ocupação territorial também pelos impactos sobre povos originários, populações locais e natureza.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, mapa, linha do tempo, desenho, digitação, escrita ou tecnologia assistiva.','Use linguagem adequada à idade, não estigmatizante e sem simulações de opressão ou encenação de sofrimento.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco processos usando localização, cronologia, causa, consequência, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar rotas e fontes','instruction','Localize tempo, espaço, grupos, autoria, finalidade, pistas e limites.','activity','Leia mapa e duas fontes para identificar percurso, contexto e perguntas abertas.','support','Vocabulário visual, mapa simplificado, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar causas e experiências','instruction','Compare migrações, permanências, interesses, escolhas, coerções e perspectivas.','activity','Monte linha do tempo, quadro causal ou mapa de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar transformações','instruction','Relacione deslocamentos, circulação, território, tecnologia, cultura e ambiente com evidências.','activity','Apresente conclusão que reconheça agência dos grupos, consequência e limite das fontes.','support','Resposta oral, apontada, mapeada, desenhada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa rota, grupos, fonte e limite.'),jsonb_build_object('page',2,'answer','Compara causas e experiências sem apagar coerção ou agência.'),jsonb_build_object('page',3,'answer','Explicação causal ligada às evidências e perspectivas.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados familiares e migratórios.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','timeline','drawing','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'forced_migration_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-4ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
