-- Biblioteca Inclusiva · História do 5º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF05HI01','unidade-1/aula-02-povos-identidades.ts','Povos, culturas e formação social'),
('EF05HI02','unidade-3/aula-01-formas-governo.ts','Formas de organização política e social'),
('EF05HI03','unidade-1/aula-02-povos-identidades.ts','Territórios, identidades e culturas'),
('EF05HI04','unidade-1/aula-01-cidadania-antiguidade.ts','Cidadania na Antiguidade e no presente'),
('EF05HI05','unidade-4/aula-01-direitos-sociais.ts','Conquistas sociais e cidadania'),
('EF05HI06','unidade-7/aula-02-linguagens-tempo.ts','Linguagens e transmissão de saberes'),
('EF05HI07','unidade-5/aula-02-memoria-marcos.ts','Marcos, calendários e memória'),
('EF05HI08','unidade-7/aula-02-linguagens-tempo.ts','Formas de marcar e organizar o tempo'),
('EF05HI09','unidade-6/aula-02-temas-contemporaneos.ts','Fontes e temas contemporâneos'),
('EF05HI10','unidade-5/aula-01-patrimonio-unesco.ts','Patrimônios materiais, imateriais e diversidade')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-5ano/'||rel source_key,title,'Investigar, comparar e argumentar sobre '||lower(title)||' usando fontes, cronologia, conceitos históricos e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','5º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize conceitos','content',jsonb_build_array('Explique que cidadania, direitos, governo, tempo e patrimônio mudam entre sociedades e períodos; evite apresentar modelos antigos ou atuais como universais.','Mostre quem participou, quem foi excluído, quem reivindicou mudanças e quais limites permaneceram, usando linguagem adequada à idade e sem detalhes gráficos.','Apresente povos indígenas, africanos e afro-brasileiros e pessoas com deficiência como sujeitos diversos, produtores de conhecimento, cultura e ação política.')),
 jsonb_build_object('heading','Investigue fontes e argumentos','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de textos, imagens, objetos, relatos e patrimônios.','Diferencie fato verificável, interpretação, opinião e desinformação; confirme temas contemporâneos em mais de uma fonte confiável.','Analise marcos e patrimônios perguntando quem escolheu preservar, quais memórias aparecem e quais podem estar ausentes.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, linha do tempo, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não peça que a criança revele religião, posição política, deficiência, origem, renda ou experiência de discriminação.')),
 jsonb_build_object('heading','Critério','content','Compara ou argumenta em quatro de cinco situações usando contexto, cronologia, conceito, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Contextualizar e ler fontes','instruction','Identifique sociedade, período, grupos, autoria, finalidade, pistas, silêncios e limites.','activity','Compare duas fontes e registre convergência, diferença e pergunta aberta.','support','Glossário visual, linha do tempo, leitura pelo adulto e exemplo resolvido.'),jsonb_build_object('title','2. Comparar conceitos e perspectivas','instruction','Compare cidadania, poder, linguagem, tempo, memória ou patrimônio entre contextos.','activity','Monte quadro, linha do tempo ou mapa conceitual de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com evidências','instruction','Formule conclusão, cite fontes, reconheça outra perspectiva e limite do argumento.','activity','Apresente argumento curto em formato acessível e revise após uma pergunta crítica.','support','Resposta oral, apontada, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Contextualiza fonte, grupos e limite.'),jsonb_build_object('page',2,'answer','Compara conceitos sem anacronismo ou universalização.'),jsonb_build_object('page',3,'answer','Argumento ligado às evidências e aberto a revisão.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; preserve dados sensíveis e opiniões pessoais.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','timeline','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_afro_brazilian_agency',true,'disability_agency',true,'source_verification',true,'contested_memory',true,'non_graphic',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-5ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
