-- Biblioteca Inclusiva · Língua Inglesa do 9º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF09LI01','Pontos de vista e argumentação oral','Expor tese, razões e evidências em formato acessível, sem debate público obrigatório.'),
('EF09LI02','Notas de textos orais','Registrar palavras-chave, tese, razões, evidências e contra-argumentos com organizador visual.'),
('EF09LI03','Análise de posicionamentos','Comparar argumentos e contra-argumentos sem coletar opinião política ou crença pessoal.'),
('EF09LI04','Apresentação de pesquisa','Apresentar método, amostra, dados e limites por fala opcional ou produto multimodal.'),
('EF09LI05','Recursos de persuasão','Analisar palavras, imagens, enquadramento, cor e tamanho usados para persuadir.'),
('EF09LI06','Fato e opinião','Distinguir afirmações verificáveis, interpretações e avaliações pessoais.'),
('EF09LI07','Argumentos e evidências','Avaliar pertinência, suficiência e relação entre tese, argumento e evidência.'),
('EF09LI08','Validade das fontes','Verificar autoria, instituição, data, referências, método, finalidade e conflitos de interesse.'),
('EF09LI09','Pesquisa para produção textual','Pesquisar em fontes seguras, registrar referências e selecionar informações relevantes.'),
('EF09LI10','Organização argumentativa','Ordenar tese, argumentos, evidências, contraponto e conclusão com conectores.'),
('EF09LI11','Recursos multimodais','Integrar texto, tabela, gráfico e imagem de forma acessível e sem manipulação.'),
('EF09LI12','Campanha ética','Criar campanha sobre situação fictícia ou coletiva usando evidência e circulação controlada.'),
('EF09LI13','Escrita digital e contexto','Interpretar abreviações, símbolos e pictogramas conforme público, gênero e propósito.'),
('EF09LI14','Conectores argumentativos','Usar conectores de adição, oposição, condição, conclusão e síntese.'),
('EF09LI15','Orações condicionais','Distinguir condições possíveis e hipotéticas em problemas fictícios.'),
('EF09LI16','Verbos modais','Expressar recomendação, obrigação, necessidade e probabilidade com precisão.'),
('EF09LI17','Expansão histórica do inglês','Analisar migração, comércio e colonialismo de modo histórico, informativo e não gráfico.'),
('EF09LI18','Inglês em ciência, economia e política','Avaliar usos internacionais do inglês e desigualdades de acesso sem apresentar uma língua como superior.'),
('EF09LI19','Inglês, identidades e multilinguismo','Debater língua, poder e identidade valorizando multilinguismo e direitos linguísticos.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-9ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','9º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Argumentação acessível e segura','content',jsonb_build_array('Antecipe tema, conceitos e vocabulário; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição, notas guiadas e pausas.','Fala pública, debate, campanha, gravação e revisão por colegas são opcionais. Aceite texto, infográfico acessível, apresentação gravada privada, comunicação alternativa ou mediação do professor.','Use temas fictícios ou questões coletivas não partidárias; nunca peça posicionamento político, religião, identidade, experiência sensível ou confronto com colegas.')),
 jsonb_build_object('heading','Pesquisa, mídia e dados','content',jsonb_build_array('Verifique autoria, instituição, data, método, amostra, referências, finalidade, financiamento e conflitos de interesse; diferencie fato, opinião, inferência e evidência.','Use apenas dados públicos agregados ou conjuntos fictícios; não colete localização, rota escolar, contato, perfil digital, saúde, renda, opinião ou comportamento da turma.','Gráficos combinam cor com rótulo, padrão e forma, possuem descrição textual e não distorcem eixos, proporções ou amostras.')),
 jsonb_build_object('heading','Autoria, história e circulação','content',jsonb_build_array('Planeje tese, público e propósito; pesquise, rascunhe, revise, cite fontes e compartilhe somente em ambiente escolar controlado.','Use textos, imagens e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.','Colonialismo, coerção e supressão linguística recebem abordagem histórica informativa e não gráfica, sem encenação imersiva; valorize multilinguismo e direitos linguísticos.')),
 jsonb_build_object('heading','Critério','content','Interpreta quatro de cinco itens e produz argumento adequado com tese, evidência, fonte, contraponto e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Verificar e anotar','instruction','Identifique autoria, propósito, tese, fatos, opiniões, evidências, método e limites.','activity','Registre palavras-chave e classifique quatro elementos sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, tabela de notas e leitor de tela.'),jsonb_build_object('title','2. Comparar e argumentar','instruction','Compare fontes, argumentos, evidências e recursos verbais ou visuais.','activity','Monte mapa argumentativo com tese, razão, evidência, contraponto e resposta.','support','Modelo resolvido, cartões, matriz de fonte, dados acessíveis e pistas graduadas.'),jsonb_build_object('title','3. Produzir e revisar','instruction','Crie produto para cenário fictício ou coletivo, cite fontes e revise ética e acessibilidade.','activity','Explique escolha, limite, revisão e efeito esperado sem apresentação pública obrigatória.','support','Comunicação alternativa, fala opcional, áudio privado, infográfico acessível, portfólio local, digitação ou escrita.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Classifica elementos e registra fonte, método e limite pertinente.'),jsonb_build_object('page',2,'answer','Relaciona tese, evidência e contraponto sem ataque pessoal.'),jsonb_build_object('page',3,'answer','Produção fundamentada, citada, revisada, acessível e de circulação controlada.','teacher_note','Registre estratégias e apoio eficaz; não registre voz, opinião, identidade, perfil ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','accessible_infographic','local_portfolio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_campaign',true,'no_forced_peer_review',true,'accent_dignity',true,'privacy_preserving',true,'fictional_or_collective_topics',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_route_collection',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_behavioral_tracking',true,'no_political_opinion_collection',true,'no_sensitive_identity_disclosure',true,'source_method_sample_check',true,'accessible_nonmisleading_charts',true,'historical_non_graphic',true,'no_immersive_oppression_simulation',true,'multilingual_rights',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-9ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
