-- Biblioteca Inclusiva · Geografia do 3º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF03GE01','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-01-nosso-municipio.ts','Cidade, campo e diversidade cultural','Comparar aspectos culturais de grupos do campo e da cidade sem hierarquizar modos de vida.'),
('EF03GE02','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-02-marcas-dos-vovos.ts','Marcas culturais nas paisagens','Identificar contribuições culturais presentes em paisagens e comunidades sem exigir história familiar pessoal.'),
('EF03GE03','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-03-modos-de-vida.ts','Modos de vida tradicionais','Reconhecer modos de vida de povos e comunidades tradicionais com respeito, contexto e sem estereótipos.'),
('EF03GE04','src/escola-brilha/curso-v4/geografia-3ano/unidade-1/aula-04-paisagens-em-transformacao.ts','Paisagens naturais e transformadas','Explicar mudanças nas paisagens por evidências, diferenciando elementos naturais e ações humanas.'),
('EF03GE05','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-02-de-onde-vem.ts','Produtos, matéria-prima e trabalho','Relacionar produtos a matérias-primas, trabalho e circulação em cadeias simples de produção.'),
('EF03GE06','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-03-mapa-vivo.ts','Representações cartográficas','Interpretar diferentes representações de paisagens usando ponto de vista, símbolos e organização espacial.'),
('EF03GE07','src/escola-brilha/curso-v4/geografia-3ano/unidade-2/aula-04-legendas-simbolos.ts','Legendas e símbolos nos mapas','Ler e elaborar legendas com símbolos acessíveis, distinguíveis também sem depender apenas de cor.'),
('EF03GE08','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-05-producao-consumo-lixo.ts','Produção, consumo e resíduos','Relacionar produção, consumo e resíduos e propor ações coletivas de redução, reutilização e descarte correto.'),
('EF03GE09','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-06-usos-da-agua.ts','Usos e importância da água','Investigar usos da água no campo e na cidade por dados e cenários, sem expor hábitos domésticos pessoais.'),
('EF03GE10','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-07-cuidados-com-agua.ts','Cuidados com a água','Comparar usos responsáveis da água e formular soluções coletivas adequadas a diferentes contextos.'),
('EF03GE11','src/escola-brilha/curso-v4/geografia-3ano/unidade-3/aula-08-impactos-ambientais.ts','Impactos ambientais no campo e na cidade','Analisar impactos ambientais e responsabilidades compartilhadas sem culpabilizar indivíduos ou comunidades.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','3º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes e cenários protegidos','content',jsonb_build_array('Use municípios, comunidades, moradias, mapas, hábitos de consumo e histórias familiares fictícios; nunca peça endereço, geolocalização, rota, foto da moradia, conta de água, origem familiar ou hábitos domésticos pessoais.','Selecione fontes que representem povos, comunidades tradicionais, campo, cidade, trabalhos e condições de vida com dignidade e contexto.')),
 jsonb_build_object('heading','Modele a investigação','content',jsonb_build_array('Ensine a observar, formular hipótese, localizar evidência, comparar fontes e justificar uma conclusão.','Trabalhe paisagem, território, representação, cadeia produtiva, consumo, água e impacto ambiental conectando causas, consequências e responsabilidades coletivas.','Em mapas e legendas, combine cor com forma, textura, contorno, texto ou padrão; ofereça versão tátil quando possível.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida a tarefa em blocos curtos, antecipe termos, modele um exemplo e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, objetos, maquete, mapa, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não confunda velocidade, memória, leitura, fala, visão ou coordenação motora com compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e justifica ao menos três respostas com evidência espacial, ambiental, cultural ou produtiva.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e perguntar','instruction','Observe mapa, imagem, objeto, sequência ou tabela de um cenário fictício.','activity','Identifique duas pistas e formule uma pergunta investigável.','support','Vocabulário visual, leitura mediada, ampliação e exploração tátil opcional.'),jsonb_build_object('title','2. Comparar e relacionar','instruction','Compare lugares, tempos, representações, etapas produtivas, usos de recursos ou impactos.','activity','Organize cartões, mapa, quadro causa-consequência ou cadeia relacionada a '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Concluir com evidência','instruction','Escolha uma conclusão e indique a pista que a sustenta.','activity','Explique uma relação e proponha uma ação coletiva quando pertinente.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica duas pistas pertinentes e uma pergunta possível.'),jsonb_build_object('page',2,'answer','Compara ou organiza relações de modo coerente.'),jsonb_build_object('page',3,'answer','Conclusão sustentada por evidência; solução coletiva viável quando solicitada.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, origem familiar ou hábitos domésticos reais.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','map','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_family_origin_disclosure',true,'no_household_consumption_disclosure',true,'housing_dignity',true,'cultural_respect',true,'traditional_communities_respect',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-3ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
