-- Biblioteca Inclusiva · História do 7º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF07HI01','unidade-1/aula-02-modernidade-conexoes.ts','Modernidade, conexões e exclusões'),
('EF07HI02','unidade-1/aula-02-modernidade-conexoes.ts','Humanismos e transformações da modernidade'),
('EF07HI03','unidade-2/aula-01-renascimento-ciencia.ts','Renascimentos artísticos e culturais'),
('EF07HI04','unidade-2/aula-01-renascimento-ciencia.ts','Ciência, imprensa e circulação de ideias'),
('EF07HI05','unidade-3/aula-01-reformas-religiosas.ts','Reformas religiosas e conflitos europeus'),
('EF07HI06','unidade-5/aula-01-grandes-navegacoes.ts','Expansões marítimas europeias'),
('EF07HI07','unidade-4/aula-01-absolutismo-mercantilismo.ts','Monarquias europeias e centralização política'),
('EF07HI08','unidade-6/aula-02-sociedades-antes-conquista.ts','Áfricas e Américas antes da conquista'),
('EF07HI09','unidade-6/aula-01-conquista-america.ts','Conquista europeia e sociedades americanas'),
('EF07HI10','unidade-6/aula-01-conquista-america.ts','Alianças, conflitos e resistências indígenas'),
('EF07HI11','unidade-7/aula-02-territorios-populacoes.ts','Territórios e populações da América colonial'),
('EF07HI12','unidade-7/aula-02-territorios-populacoes.ts','Distribuição territorial e diversidade étnico-cultural'),
('EF07HI13','unidade-4/aula-01-absolutismo-mercantilismo.ts','Mercantilismo e dominação colonial'),
('EF07HI14','unidade-7/aula-03-comercio-africa-asia.ts','Redes comerciais africanas e asiáticas'),
('EF07HI15','unidade-7/aula-01-brasil-colonial.ts','Economia açucareira e sociedade colonial'),
('EF07HI16','unidade-7/aula-01-brasil-colonial.ts','Escravização, resistências e quilombos'),
('EF07HI17','unidade-4/aula-01-absolutismo-mercantilismo.ts','Comércio atlântico e circulação colonial')
), p AS (SELECT code,'src/escola-brilha/curso-v4/historia-7ano/'||rel source_key,title,'Analisar e argumentar sobre '||lower(title)||' usando fontes, mapas, cronologia, causalidade e múltiplas perspectivas.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','História',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de análise histórica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Contextualize encontros e conflitos','content',jsonb_build_array('Problematize termos como descobrimento, conquista, civilização e Novo Mundo, identificando quem os produziu e quais perspectivas silenciam.','Apresente Áfricas e Américas antes da conquista como espaços diversos, complexos e conectados; povos indígenas e africanos aparecem com conhecimentos, decisões, alianças, conflitos, resistências e presença atual.','Trate epidemias, guerras, perseguições e escravização de modo informativo e não gráfico; não proponha encenação de opressão, sofrimento ou negociação de pessoas.')),
 jsonb_build_object('heading','Analisar fontes, redes e poder','content',jsonb_build_array('Compare autoria, data, contexto, finalidade, linguagem, evidências, silêncios e limites de mapas, crônicas, imagens, objetos e relatos.','Relacione religião, ciência, comércio, Estado, território, trabalho e circulação sem atribuir superioridade cultural ou uma causa única.','Diferencie comércio entre sociedades de sistemas coloniais coercitivos e analise a agência de indígenas, africanos, afro-brasileiros e quilombolas.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida textos e tarefas em etapas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, mapeada, diagramada, digitada, escrita ou com tecnologia assistiva.','Use glossário, mapas comparáveis, cronologia, fonte ampliada e prática guiada, retirando pistas gradualmente.')),
 jsonb_build_object('heading','Critério','content','Analisa quatro de cinco processos usando contexto, cronologia, território, causalidade, perspectiva e evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Situar fontes e conceitos','instruction','Identifique período, território, grupos, autoria, finalidade, linguagem, pistas, silêncios e limites.','activity','Compare duas fontes e questione um conceito ou representação histórica.','support','Glossário, mapa, linha do tempo, leitura apoiada e exemplo resolvido.'),jsonb_build_object('title','2. Relacionar redes, interesses e coerções','instruction','Compare conexões, interesses, alianças, conflitos, resistências e relações de poder.','activity','Monte quadro causal, mapa de fluxos ou linha do tempo de '||lower(title)||'.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Argumentar com múltiplas perspectivas','instruction','Formule explicação com evidências, reconheça agência, consequência, outra perspectiva e limites.','activity','Produza argumento curto, cite fontes e revise diante de contraexemplo.','support','Resposta oral, apontada, mapeada, diagramada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa fontes, conceitos, perspectivas e limites.'),jsonb_build_object('page',2,'answer','Relaciona redes e poder sem superioridade cultural ou causa única.'),jsonb_build_object('page',3,'answer','Argumento sustentado por evidências e agência histórica.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre religião, origem ou experiência pessoal sensível.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','map','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'multiple_perspectives',true,'anti_stereotype',true,'indigenous_african_quilombola_agency',true,'contested_terms',true,'forced_labor_context',true,'non_graphic',true,'no_oppression_roleplay',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/historia-7ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
