-- Biblioteca Inclusiva · Geografia do 2º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF02GE01','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-01-lugares-onde-vivemos.ts','Convivência, histórias e migrações','Comparar costumes, relações e histórias de pessoas em diferentes lugares com respeito às origens e aos deslocamentos.'),
('EF02GE02','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-06-costumes-tradicoes.ts','Costumes e tradições da comunidade','Reconhecer costumes e tradições de diferentes grupos sem hierarquizar culturas ou exigir relato familiar.'),
('EF02GE03','src/escola-brilha/curso-v4/geografia-2ano/unidade-2/aula-03-transportes-e-comunicacao.ts','Transportes e comunicação','Comparar meios de transporte e comunicação, seus usos e mudanças, considerando acessibilidade.'),
('EF02GE04','src/escola-brilha/curso-v4/geografia-2ano/unidade-1/aula-03-trabalho-campo-cidade.ts','Trabalho no campo e na cidade','Relacionar atividades e trabalhos de diferentes lugares sem estereótipos de gênero, território ou condição social.'),
('EF02GE05','src/escola-brilha/curso-v4/geografia-2ano/unidade-5/aula-01-maquina-do-tempo-da-paisagem.ts','Mudanças e permanências nas paisagens','Analisar mudanças e permanências por imagens de tempos diferentes, distinguindo ação humana e processos naturais.'),
('EF02GE06','src/escola-brilha/curso-v4/geografia-2ano/unidade-2/aula-05-dia-noite-atividades.ts','Atividades do dia e da noite','Relacionar atividades sociais a diferentes períodos do dia sem apresentar uma única rotina como padrão.'),
('EF02GE07','src/escola-brilha/curso-v4/geografia-2ano/unidade-3/aula-01-do-campo-pra-mesa.ts','Campo, cidade, transportes e comunicação','Explicar conexões entre campo e cidade pela produção, circulação, transporte e comunicação.'),
('EF02GE08','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-02-seguranca-no-transito.ts','Riscos e cuidados nos lugares','Identificar situações de risco em cenários ilustrados e propor cuidados coletivos e acessíveis.'),
('EF02GE09','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-06-visoes-representacoes.ts','Visões e representações dos objetos','Comparar objetos e lugares vistos de cima, de frente e de lado com apoio visual ou tátil.'),
('EF02GE10','src/escola-brilha/curso-v4/geografia-2ano/unidade-4/aula-07-localizacao-referencias.ts','Localização e pontos de referência','Aplicar referenciais espaciais em mapas e maquetes fictícios, admitindo diferentes lateralidades e mobilidades.'),
('EF02GE11','src/escola-brilha/curso-v4/geografia-2ano/unidade-5/aula-05-solo-agua.ts','Solo e água: usos e cuidados','Reconhecer usos do solo e da água e propor formas coletivas de cuidado em diferentes contextos.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','2º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare o cenário protegido','content',jsonb_build_array('Use município, bairro, moradia, trajeto, rotina e história familiar fictícios; nunca peça endereço, geolocalização, fotografia da moradia, caminho real, horário ou história migratória pessoal da criança.','Apresente moradias, culturas, famílias, trabalhos e modos de deslocamento diversos sem classificar um como superior.')),
 jsonb_build_object('heading','Modele o raciocínio geográfico','content',jsonb_build_array('Ensine a observar pistas, localizar, comparar, relacionar e justificar com imagem, mapa, maquete, sequência temporal ou objetos.','Diferencie fato observado de hipótese e mostre relações entre pessoas, lugares, natureza, trabalho, transporte e comunicação.','Referenciais espaciais devem admitir diferentes lateralidades, percepções visuais, mobilidades e formas de orientação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, reduza estímulos concorrentes, modele um exemplo e use pistas graduadas.','Aceite fala, apontamento, cartões, objetos, maquete, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não avalie memória, leitura, visão, fala ou coordenação motora como se fossem compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações usando ao menos uma pista espacial, temporal, ambiental ou social coerente.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar e identificar','instruction','Observe imagem, objeto, mapa ou maquete fictícia e identifique pistas relevantes.','activity','Separe o que pode ser observado do que ainda precisa ser investigado.','support','Vocabulário visual, exploração tátil opcional e exemplo resolvido.'),jsonb_build_object('title','2. Localizar, ordenar ou comparar','instruction','Use posição, visão, sequência temporal, mudança, permanência ou conexão entre lugares.','activity','Organize cartões, símbolos, objetos ou trechos de mapa relacionados a '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Relacionar e explicar','instruction','Explique a relação entre pessoas, natureza, trabalho, circulação e usos do espaço.','activity','Apresente uma conclusão e a pista que a sustenta.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos e uma pista observável.'),jsonb_build_object('page',2,'answer','Localiza, ordena ou compara com referência coerente.'),jsonb_build_object('page',3,'answer','Explica uma relação apoiada em evidência.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre localização, rota, rotina ou história familiar real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_personal_migration_disclosure',true,'housing_dignity',true,'cultural_respect',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-2ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
