-- Biblioteca Inclusiva · lote 02 · EF01MA06–EF01MA10.
-- Rotinas são ajustáveis pela observação; diagnóstico não define tempo fixo.
INSERT INTO public.teacher_inclusive_lessons (
 source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,
 knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,
 accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route
) VALUES
('src/escola-brilha/data/EF01MA06.ts','audit-2026-09-03','EF01MA06','Somar é juntar e acrescentar','fundamental_1','1º Ano','Matemática','Construção de fatos básicos da adição','Construir fatos básicos da adição com objetos, desenhos e contagem a partir do maior número.',ARRAY['tea','tdah','dislexia','discalculia','deficiencia_intelectual','comunicacao','motora_escrita'],
$j$[{"title":"Guia de mediação — EF01MA06","purpose":"Ensinar o significado antes da memorização.","sections":[{"heading":"Ensine","content":["Juntar: aproxime dois grupos e conte o total.","Acrescentar: coloque mais itens no grupo inicial.","Depois comece pelo maior número e conte para a frente."]},{"heading":"Rotina ajustável","content":["Mostre as etapas visualmente.","Faça demonstrar, fazer junto e tentar em bloco curto.","Planeje a pausa conforme a resposta individual usando o Guia baseado em evidências."]},{"heading":"Critério","content":"Resolve 4 de 5 adições até 10 e explica que o total aumentou."}]}]$j$::jsonb,
$j$[{"title":"Junte","instruction":"Aproxime e conte.","content":"● ● ● + ● ●","activity":"3 + 2 = __","support":"Mova tudo para uma fila."},{"title":"Acrescente","instruction":"Havia 4 flores e chegou mais 1.","activity":"4 + 1 = __","support":"Comece no 4 e diga o próximo."},{"title":"Conte do maior","instruction":"Resolva 2 + 5.","activity":"Comece no 5: 6, __.","support":"Marque dois passos com os dedos."}]$j$::jsonb,
$j$[{"page":1,"answer":"5"},{"page":2,"answer":"5"},{"page":3,"answer":"7"}]$j$::jsonb,
$j${"response_modes":["oral","pointing","cards","writing"],"routine":"adjustable","one_instruction_at_a_time":true,"print":"grayscale-safe"}$j$::jsonb,true,true,true,'published','/escola-brilha/EF01MA06'),

('src/escola-brilha/data/EF01MA07.ts','audit-2026-09-03','EF01MA07','Partes que formam o número','fundamental_1','1º Ano','Matemática','Composição e decomposição de números naturais','Compor e decompor números de até duas ordens por diferentes adições.',ARRAY['tea','tdah','dislexia','discalculia','deficiencia_intelectual','comunicacao','motora_escrita'],
$j$[{"title":"Guia de mediação — EF01MA07","purpose":"Mostrar que separar o total não muda a quantidade.","sections":[{"heading":"Ensine","content":["Conte o total, separe em duas partes e reconte.","Mude a divisão e registre outra adição.","Depois use barra de dez e unidades."]},{"heading":"Rotina ajustável","content":["Uma decomposição por vez.","Use pausa antes de mudar para dezenas e unidades.","Aceite cartões numéricos no lugar da escrita."]},{"heading":"Critério","content":"Produz duas decomposições e identifica dezena e unidades."}]}]$j$::jsonb,
$j$[{"title":"Duas partes","instruction":"Separe 6.","activity":"6 = 5 + __ e 6 = 4 + __","support":"Monte com seis objetos."},{"title":"Forme 10","instruction":"Escolha a dupla.","activity":"6 + 3 | 6 + 4 | 7 + 4","support":"Separe seis de um grupo de dez."},{"title":"Dezena e unidades","content":"[10] ● ● ● ● ● ● ●","activity":"17 = 10 + __","support":"Aponte a dezena e depois as unidades."}]$j$::jsonb,
$j$[{"page":1,"answer":["1","2"]},{"page":2,"answer":"6 + 4"},{"page":3,"answer":"7"}]$j$::jsonb,
$j${"response_modes":["oral","pointing","cards","manipulation"],"routine":"adjustable","cra_sequence":true,"print":"grayscale-safe"}$j$::jsonb,true,true,true,'published','/escola-brilha/EF01MA07'),

('src/escola-brilha/data/EF01MA08.ts','audit-2026-09-03','EF01MA08','Histórias de somar e tirar','fundamental_1','1º Ano','Matemática','Problemas de adição e subtração','Resolver e elaborar problemas identificando começo, mudança e pergunta.',ARRAY['tea','tdah','dislexia','discalculia','deficiencia_intelectual','comunicacao','motora_escrita'],
$j$[{"title":"Guia de mediação — EF01MA08","purpose":"Compreender a situação antes de escolher a operação.","sections":[{"heading":"Mapa da história","content":["Como começou?","O que entrou, saiu ou foi separado?","O que a pergunta quer descobrir?"]},{"heading":"Rotina ajustável","content":["Leia uma frase por vez e represente com objetos.","Trabalhe juntar e retirar em blocos separados.","Não escolha a conta por uma palavra isolada."]},{"heading":"Critério","content":"Resolve 4 de 5 problemas e responde com número e unidade."}]}]$j$::jsonb,
$j$[{"title":"O que mudou?","instruction":"Lia tinha 6 estrelas e ganhou 3.","activity":"6 + 3 = __ estrelas","support":"Monte seis e acrescente três."},{"title":"Algo saiu","instruction":"Havia 10 moedas; quatro saíram.","activity":"10 − 4 = __ moedas","support":"Risque quatro e conte o restante."},{"title":"Descubra o começo","instruction":"Caio ganhou 2 e ficou com 7.","activity":"Antes tinha __ estrelas.","support":"Retire do total as duas recebidas."}]$j$::jsonb,
$j$[{"page":1,"answer":"9 estrelas"},{"page":2,"answer":"6 moedas"},{"page":3,"answer":"5 estrelas"}]$j$::jsonb,
$j${"response_modes":["oral","pointing","drawing","writing"],"routine":"adjustable","story_map":true,"print":"grayscale-safe"}$j$::jsonb,true,true,true,'published','/escola-brilha/EF01MA08'),

('src/escola-brilha/data/EF01MA09.ts','audit-2026-09-03','EF01MA09','Organizar por uma regra','fundamental_1','1º Ano','Matemática','Classificação e ordenação por atributos','Organizar objetos por cor, forma, tamanho, espessura ou material e explicar o critério.',ARRAY['tea','tdah','dislexia','discalculia','deficiencia_intelectual','comunicacao','motora_escrita'],
$j$[{"title":"Guia de mediação — EF01MA09","purpose":"Ensinar um atributo por vez.","sections":[{"heading":"Ensine","content":["Escolha e mostre a regra.","Classifique todos os objetos.","Mude a regra para reorganizar a coleção."]},{"heading":"Rotina ajustável","content":["Mostre poucos objetos para reduzir excesso visual.","Separe classificação e ordenação com pausa planejada.","Aceite resposta falada, apontada ou com cartão."]},{"heading":"Critério","content":"Classifica por dois atributos e ordena por tamanho ou espessura."}]}]$j$::jsonb,
$j$[{"title":"Pela forma","content":"○ □ ○ △ □","activity":"Quantos são redondos?","support":"Observe apenas a forma."},{"title":"Mude a regra","instruction":"Agora organize por cor.","activity":"Eu observei a ______.","support":"Escolha COR, FORMA ou TAMANHO."},{"title":"Coloque em ordem","activity":"grande | pequeno | médio → __ | __ | __","support":"Compare dois tamanhos de cada vez."}]$j$::jsonb,
$j$[{"page":1,"answer":"2"},{"page":2,"answer":"cor"},{"page":3,"answer":["pequeno","médio","grande"]}]$j$::jsonb,
$j${"response_modes":["oral","pointing","sorting_cards"],"routine":"adjustable","one_attribute_at_a_time":true,"print":"grayscale-safe"}$j$::jsonb,true,true,true,'published','/escola-brilha/EF01MA09'),

('src/escola-brilha/data/EF01MA10.ts','audit-2026-09-03','EF01MA10','Descobrir a regra da sequência','fundamental_1','1º Ano','Matemática','Sequências recursivas e elementos ausentes','Reconhecer, explicar e completar padrões de números, objetos e figuras.',ARRAY['tea','tdah','dislexia','discalculia','deficiencia_intelectual','comunicacao','motora_escrita'],
$j$[{"title":"Guia de mediação — EF01MA10","purpose":"Ensinar a regra do padrão e evitar adivinhação.","sections":[{"heading":"Ensine","content":["Aponte e fale o menor bloco que se repete.","Cubra um elemento e descubra o que falta.","Confira o anterior e o seguinte."]},{"heading":"Rotina ajustável","content":["Apresente uma linha por vez.","Faça pausa antes de mudar de figuras para números.","No erro, volte ao padrão concreto."]},{"heading":"Critério","content":"Completa 4 de 5 sequências e explica duas regularidades."}]}]$j$::jsonb,
$j$[{"title":"Encontre o bloco","content":"○ △ | ○ △ | ○ __","activity":"Qual figura falta?","support":"Fale: círculo, triângulo."},{"title":"Lacuna no meio","content":"4, 6, __, 10","activity":"Qual falta e qual é a regra?","support":"Compare números vizinhos."},{"title":"Três elementos","content":"★ ♥ ♥ | ★ ♥ ♥ | ★ __ __","activity":"Complete os espaços.","support":"Aponte um bloco completo."}]$j$::jsonb,
$j$[{"page":1,"answer":"triângulo"},{"page":2,"answer":{"missing":"8","rule":"acrescentar 2"}},{"page":3,"answer":["coração","coração"]}]$j$::jsonb,
$j${"response_modes":["oral","pointing","drawing","object_cards"],"routine":"adjustable","pattern_frames":true,"print":"grayscale-safe"}$j$::jsonb,true,true,true,'published','/escola-brilha/EF01MA10')
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET
 source_version=EXCLUDED.source_version,title=EXCLUDED.title,knowledge_object=EXCLUDED.knowledge_object,
 learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,
 teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,
 accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,
 pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,
 status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
