-- Biblioteca Inclusiva · Língua Inglesa do 6º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06LI01','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Interação oral em inglês','Interagir em situações escolares com preparação, apoio visual e fala opcional.'),
('EF06LI02','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Coleta de informações no grupo','Solicitar e registrar informações de personagens fictícios sem exposição pessoal.'),
('EF06LI03','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Pedidos de esclarecimento','Pedir repetição, ajuda e explicação usando expressões respeitosas e acessíveis.'),
('EF06LI04','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Assunto e informações em textos orais','Reconhecer assunto e informações por palavras-chave, entonação e contexto.'),
('EF06LI05','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Sentimentos, gostos e preferências','Comunicar preferências de personagens sem exigir sentimento ou experiência pessoal.'),
('EF06LI06','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Planejamento de apresentação','Planejar apresentação curta com roteiro, ensaio privado e formatos alternativos.'),
('EF06LI07','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Hipóteses sobre finalidade textual','Formular hipóteses sobre público e finalidade por título, imagens e organização.'),
('EF06LI08','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Assunto de um texto','Identificar tema e ideia central com skimming e pistas contextuais.'),
('EF06LI09','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Informações específicas','Localizar detalhes com scanning sem exigir tradução palavra por palavra.'),
('EF06LI10','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Uso de dicionário bilíngue','Consultar verbete, classe, acepção e exemplo em dicionário seguro.'),
('EF06LI11','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Ferramentas digitais de aprendizagem','Usar recursos digitais sem conta pessoal, rastreamento ou publicação de dados.'),
('EF06LI12','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Compartilhamento de interpretações','Comparar interpretações e citar pistas textuais com discordância respeitosa.'),
('EF06LI13','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Planejamento por lista de ideias','Gerar e selecionar ideias adequadas a objetivo, gênero e público.'),
('EF06LI14','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Organização de ideias','Ordenar ideias em abertura, desenvolvimento e fechamento.'),
('EF06LI15','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Produção escrita autoral','Planejar, redigir, revisar e compartilhar texto sem expor dados pessoais.'),
('EF06LI16','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Expressões de sala de aula','Compreender e usar instruções e pedidos escolares em modalidades acessíveis.'),
('EF06LI17','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Inglês no mundo','Reconhecer inglês como língua materna, oficial ou franca em contextos diversos.'),
('EF06LI18','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Pronúncia e inteligibilidade','Comparar sons e tonicidade respeitando sotaques e variedades linguísticas.'),
('EF06LI19','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Presente simples','Usar presente simples para fatos e rotinas de personagens fictícios.'),
('EF06LI20','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Presente contínuo','Descrever ações em andamento com apoio de imagens e sequência.'),
('EF06LI21','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Imperativo em instruções','Interpretar e produzir instruções claras e respeitosas sem obediência corporal obrigatória.'),
('EF06LI22','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Caso genitivo','Expressar pertencimento e relações em cenários fictícios.'),
('EF06LI23','src/escola-brilha/ingles-6ano/u6-a01-academy/data.ts','Adjetivos possessivos','Usar adjetivos possessivos com referentes claros e perfis fictícios.'),
('EF06LI24','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Países e usos do inglês','Investigar usos do inglês sem reduzir a língua a um país ou sotaque.'),
('EF06LI25','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Inglês no contexto brasileiro','Analisar palavras e usos do inglês no Brasil com fontes e contexto.'),
('EF06LI26','src/escola-brilha/ingles-6ano/bncc-lessons.ts','Produtos culturais em inglês','Avaliar autoria, público, circulação, pontos de vista e representações em produtos culturais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Compreensão e comunicação acessíveis','content',jsonb_build_array('Apresente contexto, objetivo e palavras-chave antes do áudio ou texto; permita repetição, velocidade reduzida, legenda, transcrição e pausas.','Fala pública, leitura em voz alta e repetição coral são opcionais. Aceite apontamento, cartões, comunicação alternativa, ensaio privado, áudio privado, digitação ou escrita.','Avalie compreensão e inteligibilidade, não imitação de sotaque nativo; reconheça variedades do inglês e repertórios multilíngues.')),
 jsonb_build_object('heading','Leitura e escrita estratégicas','content',jsonb_build_array('Modele previsão, skimming, scanning, inferência por contexto e consulta de dicionário; não exija tradução palavra por palavra.','Divida escrita em propósito, público, ideias, organização, rascunho, revisão e versão final; forneça modelo parcial, banco de palavras e organizador visual.','Use textos e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.')),
 jsonb_build_object('heading','Privacidade e segurança cultural','content',jsonb_build_array('Use nomes, famílias, rotinas, escolas, fotos, perfis e localizações fictícios; nunca peça endereço, geolocalização, conta digital, foto pessoal, rotina real, diagnóstico, religião, nacionalidade ou história familiar.','Ferramentas digitais devem funcionar sem perfil público; não publique voz, imagem, texto identificável ou localização.','Temas culturais devem mostrar diversidade e evitar que inglês, país, sotaque ou cultura sejam apresentados como superiores.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz três significados adequados ao contexto por qualquer modo acessível, citando pista quando a tarefa for interpretativa.')))),
jsonb_build_array(jsonb_build_object('title','1. Antecipar e compreender','instruction','Observe gênero, contexto, título e pistas antes de ler ou escutar.','activity','Identifique assunto, palavras-chave e duas informações sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável e repetível, tradução seletiva, texto segmentado e leitor de tela.'),jsonb_build_object('title','2. Praticar com apoio','instruction','Associe significado, estrutura e uso em exemplos fictícios.','activity','Ordene, complete ou transforme três itens com banco de palavras e modelo.','support','Exemplo resolvido, cartões, organizador visual, pistas graduadas e tempo ampliado.'),jsonb_build_object('title','3. Comunicar e revisar','instruction','Produza resposta adequada ao propósito no formato escolhido e revise o sentido.','activity','Explique uma escolha ou cite pista do texto, áudio ou contexto.','support','Apontamento, comunicação alternativa, fala opcional, áudio privado, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica assunto e informações por pistas pertinentes.'),jsonb_build_object('page',2,'answer','Relaciona forma, significado e uso com apoio adequado.'),jsonb_build_object('page',3,'answer','Comunica sentido e revisa com base no propósito; sotaque não é penalizado.','teacher_note','Registre compreensão, estratégia e apoio eficaz; não registre voz, localização, saúde ou identidade pessoal.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'accent_dignity',true,'multilingual_respect',true,'privacy_preserving',true,'fictional_personal_context',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_public_posting',true,'no_family_disclosure',true,'no_health_disclosure',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
