-- Biblioteca Inclusiva · Filosofia do 6º ano completa.
-- EF06FI01–EF06FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF06FI01','src/escola-brilha/curso-v4/filosofia-6ano/unidade-1/aula-01-espanto-filosofico.ts','Espanto e pergunta filosófica','Reconhecer admiração, dúvida e pergunta como pontos de partida da investigação filosófica.'),
('EF06FI02','src/escola-brilha/curso-v4/filosofia-6ano/unidade-2/aula-01-mito-ao-logos.ts','Mito, logos e primeiros filósofos','Comparar explicações míticas e investigações racionais em seus contextos históricos sem tratar mito como simples mentira.'),
('EF06FI03','src/escola-brilha/curso-v4/filosofia-6ano/unidade-3/aula-01-socrates-maieutica.ts','Sócrates e investigação por perguntas','Aplicar perguntas de esclarecimento, razões e consequências a afirmações fictícias sem constranger ou interrogar colegas.'),
('EF06FI04','src/escola-brilha/curso-v4/filosofia-6ano/unidade-4/aula-01-argumento-vs-opiniao.ts','Argumento, opinião e falácias','Distinguir opinião, premissa, conclusão, evidência e falácias em exemplos adequados à idade.'),
('EF06FI05','src/escola-brilha/curso-v4/filosofia-6ano/unidade-5/aula-01-etica-amizade.ts','Ética e concepções de amizade','Analisar concepções filosóficas de amizade e vida boa sem avaliar, classificar ou expor relações pessoais do estudante.'),
('EF06FI06','src/escola-brilha/curso-v4/filosofia-6ano/unidade-6/aula-01-caverna-platao.ts','Alegoria da caverna e conhecimento','Interpretar a alegoria da caverna como investigação sobre aparência, opinião, conhecimento e educação, com abordagem histórica não gráfica.'),
('EF06FI07','src/escola-brilha/curso-v4/filosofia-6ano/unidade-7/aula-01-coragem-pensar.ts','Autonomia intelectual','Desenvolver autonomia para perguntar, verificar, mudar de posição diante de razões e reconhecer limites do próprio conhecimento.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar', 'fundamental_2','6º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Identificação curricular correta','content',jsonb_build_array('Este material é um componente autoral complementar do NeuroBrilha. O código '||code||' é interno e não deve ser apresentado como habilidade oficial da BNCC do Ensino Fundamental.','Use os códigos para organização e busca dentro do aplicativo, mantendo nos relatórios a indicação currículo complementar.','Apresente ideias filosóficas com contexto, autoria, época e possibilidade de crítica; não transforme a posição de um filósofo em resposta obrigatória ou verdade final.')),
 jsonb_build_object('heading','Diálogo protegido','content',jsonb_build_array('Discussão oral, debate, pergunta socrática e apresentação são opcionais. Aceite análise silenciosa, cartões, escrita, digitação, comunicação alternativa ou áudio privado.','Use afirmações, dilemas e personagens fictícios. Não peça exposição de religião, política, amizade, conflito, medo, família, identidade, experiência íntima ou opinião diante da turma.','Discordâncias devem examinar ideias e razões, sem ataque pessoal, ridicularização, pressão do grupo ou obrigação de defender posição contrária à própria convicção. Permita mudar de resposta.')),
 jsonb_build_object('heading','Fontes, história e acessibilidade','content',jsonb_build_array('Use paráfrases, excertos breves autorizados ou em domínio público e traduções identificadas. Diferencie citação, paráfrase e interpretação; não reproduza obras extensas.','Aborde conflitos e acontecimentos históricos de forma informativa e não gráfica, sem encenação imersiva. Mito é narrativa cultural, não sinônimo de mentira; logos não torna povos ou épocas inferiores.','Antecipe vocabulário; ofereça texto segmentado, glossário visual, mapa de argumento, legenda, transcrição, descrição de imagem, áudio regulável, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Identifica pergunta, conceito, razão, evidência e conclusão em quatro de cinco itens, justificando no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Perguntar e definir','instruction','Escolha um caso fictício, destaque a pergunta e esclareça os conceitos sem perguntar sobre a vida do colega.','activity','Associe quatro perguntas de esclarecimento a afirmações sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, fonte ampliada, áudio regulável, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Mapear razões','instruction','Separe afirmação, premissa, evidência, inferência, conclusão e possível falácia.','activity','Complete mapa de argumento e indique qual informação ainda seria necessária.','support','Modelo resolvido, cartões móveis, cores com rótulos e formas, pistas graduadas, tempo ampliado e mediação.'),jsonb_build_object('title','3. Comparar e revisar','instruction','Compare duas interpretações e revise a resposta quando surgir razão melhor.','activity','Produza quadro, sequência, texto curto ou áudio privado, citando o material fornecido.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Formula pergunta pertinente e define conceito sem exposição pessoal.'),jsonb_build_object('page',2,'answer','Distingue premissa, evidência e conclusão e identifica limite ou falácia.'),jsonb_build_object('page',3,'answer','Compara interpretações, justifica e admite revisão diante de nova razão.','teacher_note','Registre somente estratégia e apoio eficaz; não registre voz, opinião, amizade, medo, crença, política, família ou experiência pessoal.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','comparison_chart','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_public_opinion',true,'fictional_cases_only',true,'no_personal_friendship_disclosure',true,'no_belief_disclosure',true,'no_political_opinion_collection',true,'no_fear_disclosure',true,'privacy_preserving',true,'idea_not_person',true,'no_ridicule',true,'no_peer_pressure',true,'right_to_revise',true,'historical_non_graphic',true,'no_immersive_conflict_simulation',true,'myth_is_not_lie',true,'no_cultural_hierarchy',true,'brief_authorized_or_public_domain_excerpts',true,'citation_paraphrase_interpretation_distinction',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-6ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
