-- Biblioteca Inclusiva · Filosofia do 8º ano completa.
-- EF08FI01–EF08FI07 são códigos INTERNOS do NeuroBrilha, não habilidades oficiais da BNCC.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF08FI01','src/escola-brilha/curso-v4/filosofia-8ano/unidade-1/aula-01-duvida-metodica.ts','Descartes e dúvida metódica','Distinguir dúvida metódica de negar tudo indiscriminadamente e reconstruir o argumento cartesiano em contexto histórico.'),
('EF08FI02','src/escola-brilha/curso-v4/filosofia-8ano/unidade-2/aula-01-empirismo-racionalismo.ts','Empirismo e racionalismo','Comparar teses empiristas e racionalistas sobre conhecimento, experiência e razão sem reduzir tradições diversas a dois times rígidos.'),
('EF08FI03','src/escola-brilha/curso-v4/filosofia-8ano/unidade-3/aula-01-kant-revolucao-copernicana.ts','Kant, conhecimento e moral','Analisar a proposta kantiana sobre experiência, categorias e universalização moral, reconhecendo interpretações e limites.'),
('EF08FI04','src/escola-brilha/curso-v4/filosofia-8ano/unidade-4/aula-01-hegel-dialetica.ts','Hegel, dialética e história','Interpretar contradição, reconhecimento e mudança histórica em Hegel, indicando que a fórmula tese-antítese-síntese é uma simplificação didática contestada.'),
('EF08FI05','src/escola-brilha/curso-v4/filosofia-8ano/unidade-5/aula-01-marx-trabalho-alienacao.ts','Marx, trabalho e alienação','Analisar trabalho, alienação, classe e crítica do capitalismo como teoria histórica, sem propaganda partidária ou coleta de situação econômica pessoal.'),
('EF08FI06','src/escola-brilha/curso-v4/filosofia-8ano/unidade-6/aula-01-nietzsche-alem-bem-mal.ts','Nietzsche e genealogia dos valores','Examinar a genealogia dos valores e a transvaloração em contexto, esclarecendo que o termo além-do-humano não define superioridade racial, corporal, de gênero ou deficiência.'),
('EF08FI07','src/escola-brilha/curso-v4/filosofia-8ano/unidade-7/aula-01-existencialismo-liberdade.ts','Existencialismo, liberdade e responsabilidade','Analisar liberdade, situação, responsabilidade e construção social em Sartre e Beauvoir sem transformar a aula em aconselhamento pessoal ou cobrança por escolhas de vida.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'complementary-internal-code-audit-2026-09-04',code,title||' — currículo complementar','fundamental_2','8º Ano','Filosofia (componente complementar)',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Filosofia — código interno '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Enquadramento e precisão','content',jsonb_build_array('Este é currículo autoral complementar. O código '||code||' é interno do NeuroBrilha e não uma habilidade oficial da BNCC do Ensino Fundamental.','Apresente autor, época, problema, conceitos, argumento, críticas e recepção. Estudar uma teoria não exige concordar com ela nem aplicá-la à vida pessoal.','Marque simplificações didáticas: empirismo e racionalismo possuem variações; tese-antítese-síntese não deve ser atribuída como fórmula literal universal de Hegel; termos de Nietzsche não autorizam hierarquia entre pessoas.')),
 jsonb_build_object('heading','Política, religião e identidade','content',jsonb_build_array('Use fontes históricas e casos fictícios. Não conduza propaganda partidária, votação política, campanha, ataque ao capitalismo ou defesa obrigatória de qualquer sistema econômico.','Não peça opinião sobre religião, política, trabalho da família, renda, classe social, gênero, deficiência, relacionamento, futuro ou experiência de discriminação.','Debate e defesa pública são opcionais. Avalie razões e evidências, não identidade, concordância com o professor ou firmeza da fala; permita posição suspensa e revisão.')),
 jsonb_build_object('heading','Segurança e acessibilidade','content',jsonb_build_array('Guerras, exploração e opressão recebem tratamento histórico informativo e não gráfico, sem encenação de dominação, trabalho explorado ou discriminação.','Existencialismo é estudado por conceitos e personagens fictícios, sem aconselhamento emocional, diagnóstico ou solicitação de experiência íntima. Encaminhe sinais de sofrimento pelo protocolo escolar, sem investigar diante da turma.','Ofereça texto segmentado, glossário, linha do tempo, mapa de argumentos, legenda, transcrição, descrição de imagem, áudio regulável, cartões, pausa e modelo resolvido.')),
 jsonb_build_object('heading','Critério','content','Compara duas posições por problema, conceito, argumento, evidência, consequência e limite no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Reconstruir o problema','instruction','Identifique autor, época, pergunta, conceitos e tese no material fornecido.','activity','Associe cartões de problema, tese e conceito sobre '||lower(title)||'.','support','Leitura fácil, texto segmentado, glossário visual, linha do tempo, fonte ampliada, áudio, legenda, transcrição e descrição de imagem.'),jsonb_build_object('title','2. Testar o argumento','instruction','Organize premissas, inferência, conclusão, objeção e resposta sem transformar teoria em identidade.','activity','Complete mapa de argumento e compare uma crítica documentada.','support','Modelo resolvido, cartões móveis, pistas graduadas, tempo ampliado, contraste por forma e rótulo e mediação.'),jsonb_build_object('title','3. Aplicar a caso fictício','instruction','Use um cenário fictício para analisar conhecimento, trabalho, valores ou liberdade.','activity','Produza quadro, sequência, texto curto ou áudio privado, registrando consequência e limite.','support','Apontar, selecionar, comunicação alternativa, digitar, escrever, fala opcional ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Situa problema, tese e conceito sem atribuir posição pessoal ao estudante.'),jsonb_build_object('page',2,'answer','Reconstrói argumento, objeção e resposta com fonte e ressalva pertinente.'),jsonb_build_object('page',3,'answer','Aplica conceito a caso fictício e reconhece consequência e limite.','teacher_note','Registre apenas estratégia e apoio; não registre crença, política, renda, trabalho familiar, classe, gênero, deficiência, relação ou experiência íntima.')),
jsonb_build_object('curriculum_status','complementary','code_authority','neurobrilha_internal','not_official_bncc',true,'response_modes',jsonb_build_array('pointing','selection','argument_cards','argument_map','timeline','comparison_matrix','aac','oral_optional','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'image_description',true,'visual_glossary',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_debate',true,'no_forced_position_defense',true,'right_to_suspend_judgment',true,'right_to_revise',true,'fictional_cases_only',true,'no_partisan_propaganda',true,'no_political_vote',true,'no_economic_system_advocacy_requirement',true,'no_belief_disclosure',true,'no_political_opinion_collection',true,'no_family_work_disclosure',true,'no_income_collection',true,'no_class_disclosure',true,'no_gender_disclosure',true,'no_disability_disclosure',true,'no_relationship_disclosure',true,'privacy_preserving',true,'historical_non_graphic',true,'no_oppression_roleplay',true,'no_exploitation_simulation',true,'no_emotional_counseling',true,'no_diagnosis',true,'school_support_protocol',true,'hegel_formula_caveat',true,'empiricism_rationalism_nuance',true,'nietzsche_term_no_human_hierarchy',true,'idea_not_person',true,'source_and_reception_check',true,'brief_authorized_or_public_domain_excerpts',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso-v4/filosofia-8ano/'||lower(code) FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
