-- Biblioteca Inclusiva · Ciências do 8º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF08CI01','unidade-5/aula-01.ts','Fontes e tipos de energia'),
('EF08CI02','unidade-5/aula-01.ts','Circuitos elétricos'),
('EF08CI03','unidade-5/aula-01.ts','Transformações de energia'),
('EF08CI04','unidade-5/aula-01.ts','Consumo de energia elétrica'),
('EF08CI05','unidade-5/aula-01.ts','Uso consciente da energia'),
('EF08CI06','unidade-5/aula-01.ts','Usinas e impactos socioambientais'),
('EF08CI07','unidade-1/aula-02-processos-reprodutivos.ts','Processos reprodutivos em seres vivos'),
('EF08CI08','unidade-2/aula-01.ts','Puberdade e ação hormonal'),
('EF08CI09','unidade-2/aula-02-saude-respeito-prevencao.ts','Métodos contraceptivos e responsabilidade'),
('EF08CI10','unidade-2/aula-02-saude-respeito-prevencao.ts','Dimensões da sexualidade, respeito e direitos'),
('EF08CI11','unidade-2/aula-02-saude-respeito-prevencao.ts','Prevenção de infecções sexualmente transmissíveis'),
('EF08CI12','unidade-6/aulas-sol-terra-lua-clima.ts','Fases da Lua e eclipses'),
('EF08CI13','unidade-6/aulas-sol-terra-lua-clima.ts','Estações do ano'),
('EF08CI14','unidade-6/aulas-sol-terra-lua-clima.ts','Circulação atmosférica, oceânica e climas'),
('EF08CI15','unidade-7/aula-01.ts','Variáveis meteorológicas e previsão do tempo'),
('EF08CI16','unidade-7/aula-01.ts','Alterações climáticas e ações humanas')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-8ano/'||rel source_key,title,'Investigar, analisar e explicar '||lower(title)||' com modelos, dados, fontes confiáveis, relações causais e linguagem científica do 8º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto e critério; use apoio visual sem reduzir o conteúdo científico.','Professor controla materiais e demonstra procedimentos; não montar circuito na rede elétrica nem usar tomadas, fios desencapados, chama, pressão, reagentes, medicamentos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar, comparar e argumentar','content',jsonb_build_array('Separe observação, dado, modelo, inferência e conclusão; identifique variável, escala, período e fonte.','Use diagramas de fluxo, sistemas, escalas, gráficos e linhas do tempo; explicite que modelos representam aspectos e têm limites.','Em saúde e sexualidade, use informação científica apropriada à idade, respeito, privacidade, consentimento, prevenção e busca de adulto ou profissional; não diagnosticar, não expor vivências pessoais e não solicitar relatos íntimos.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida tarefas longas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo vocabulário científico explicado e linguagem adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, cálculo, dado, relação causal ou evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o problema','instruction','Identifique sistema, componentes, variável, escala, período, fonte e pergunta.','activity','Construa hipótese, previsão ou modelo inicial e marque o que ele representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar dados e fontes','instruction','Compare dados, cálculos, fontes, modelos ou procedimentos e diferencie associação de causalidade.','activity','Complete tabela, gráfico, linha do tempo, circuito esquemático ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Explicar, decidir e avaliar limites','instruction','Aplique o modelo em nova situação, justifique uma decisão e explique incertezas ou limites.','activity','Produza conclusão baseada nos dados e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Problema, variáveis e hipótese delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com cálculo, dado e fonte indicada.'),jsonb_build_object('page',3,'answer','Conclusão limitada ao modelo e às evidências.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo; preserve privacidade.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-8ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
