-- Biblioteca Inclusiva · Língua Inglesa do 7º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF07LI01','Interação oral colaborativa','Participar de trocas com preparação, turnos flexíveis e fala opcional.'),
('EF07LI02','Entrevistas e coleta de informações','Formular perguntas e registrar respostas de personagens ou fontes públicas, sem exposição pessoal.'),
('EF07LI03','Conhecimentos prévios na compreensão oral','Ativar repertório, contexto e previsões antes de escutar.'),
('EF07LI04','Contexto e finalidade de textos orais','Identificar interlocutores, assunto, intenção e situação comunicativa.'),
('EF07LI05','Informações principais em textos orais','Selecionar fatos e acontecimentos relevantes em narrativas e relatos.'),
('EF07LI06','Composição de textos orais','Planejar sequência, palavras-chave e recursos de apoio para comunicação multimodal.'),
('EF07LI07','Leitura rápida para sentido geral','Usar título, início, fim e palavras repetidas para captar assunto.'),
('EF07LI08','Objetivos de leitura','Definir estratégia conforme finalidade, gênero e informação procurada.'),
('EF07LI09','Informações específicas em textos','Localizar detalhes e citar pistas sem tradução palavra por palavra.'),
('EF07LI10','Relações entre parágrafos','Reconhecer continuidade, contraste, causa, consequência e sequência.'),
('EF07LI11','Pesquisa e fontes confiáveis','Avaliar autoria, instituição, data, evidências e finalidade em fontes digitais.'),
('EF07LI12','Planejamento da escrita','Definir público, objetivo, gênero, suporte e recursos antes de produzir.'),
('EF07LI13','Organização em parágrafos','Agrupar ideias e usar títulos, tópicos e conectores para orientar o leitor.'),
('EF07LI14','Produção de textos diversos','Produzir e revisar textos com cenários e personagens fictícios.'),
('EF07LI15','Passado simples e contínuo','Distinguir fatos concluídos e ações em andamento em narrativas.'),
('EF07LI16','Conectores de sequência e causa','Usar before, after, when, while e because para articular acontecimentos.'),
('EF07LI17','Polissemia e contexto','Inferir sentidos de palavras polissêmicas pelo contexto e gênero.'),
('EF07LI18','Pronúncia do passado regular','Reconhecer variantes de pronúncia de -ed sem penalizar sotaque.'),
('EF07LI19','Pronomes sujeito e objeto','Usar pronomes conforme função sintática e referente claro.'),
('EF07LI20','Can e could','Expressar habilidades presentes e passadas em personagens fictícios.'),
('EF07LI21','Inglês como língua global','Analisar circulação mundial do inglês sem tratar uma variedade como superior.'),
('EF07LI22','Variação linguística','Reconhecer sotaques e vocabulários diversos como legítimos e contextuais.'),
('EF07LI23','Língua, identidade e respeito','Combater preconceito linguístico e valorizar repertórios multilíngues.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-7ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Entrada acessível e comunicação consentida','content',jsonb_build_array('Antecipe gênero, contexto, finalidade e palavras-chave; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição e pausas.','Fala pública, leitura em voz alta e entrevista entre colegas são opcionais. Use personagem fictício, fonte pública, roteiro escrito, comunicação alternativa, ensaio ou áudio privado.','Avalie compreensão e inteligibilidade, não imitação de sotaque; aceite tempo de processamento e formas multilíngues de construir sentido.')),
 jsonb_build_object('heading','Pesquisa, leitura e escrita','content',jsonb_build_array('Modele previsão, leitura global, busca de detalhes, relações entre parágrafos e verificação de autoria, instituição, data, evidência e finalidade.','Escrita segue público, propósito, ideias, organização, rascunho, revisão e versão final; biografia e entrevista devem usar personagens ou figuras públicas com fontes adequadas.','Ferramentas digitais não exigem perfil público, contato com desconhecidos ou publicação; dados e exemplos devem ser fictícios ou públicos agregados.')),
 jsonb_build_object('heading','Privacidade, identidade e autoria','content',jsonb_build_array('Nunca peça história de vida, memória difícil, foto, nome completo, endereço, geolocalização, rotina, habilidade pessoal, diagnóstico, religião, nacionalidade, etnia ou informação familiar.','Não apresente sotaque, país, inglês nativo ou cultura como superiores; discuta língua e identidade sem exigir autodeclaração.','Use textos e áudios autorizados, licenciados ou em domínio público conforme aplicável; não reproduza letras ou obras integrais protegidas.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz três significados adequados ao contexto, citando evidência e revisando a resposta no modo acessível escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Prever e compreender','instruction','Ative repertório, identifique contexto e escolha estratégia antes de ler ou escutar.','activity','Registre assunto, finalidade, duas informações e uma pista sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, glossário e leitor de tela.'),jsonb_build_object('title','2. Relacionar e praticar','instruction','Conecte forma, significado, função e evidência em exemplos fictícios.','activity','Organize, complete ou transforme três itens e explique uma escolha.','support','Modelo resolvido, cartões, linha do tempo, banco de palavras e pistas graduadas.'),jsonb_build_object('title','3. Produzir e revisar','instruction','Planeje resposta para propósito e público, produza no formato escolhido e revise sentido e forma.','activity','Cite evidência ou explique estratégia sem fala pública obrigatória.','support','Apontamento, comunicação alternativa, fala opcional, áudio privado, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica contexto, finalidade, informações e pista pertinente.'),jsonb_build_object('page',2,'answer','Relaciona forma e significado e explica escolha com apoio adequado.'),jsonb_build_object('page',3,'answer','Produz e revisa resposta adequada; sotaque e comunicação alternativa não são penalizados.','teacher_note','Registre compreensão, estratégia e apoio eficaz; não registre voz, história pessoal, identidade ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'no_peer_interview_required',true,'accent_dignity',true,'multilingual_respect',true,'privacy_preserving',true,'fictional_biography_only',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_life_story_disclosure',true,'no_health_disclosure',true,'no_religion_ethnicity_nationality_collection',true,'source_verification',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-7ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
