-- Biblioteca Inclusiva · Língua Inglesa do 8º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF08LI01','Negociação de sentido','Esclarecer mal-entendidos por paráfrase, pergunta e confirmação em formatos acessíveis.'),
('EF08LI02','Opiniões com justificativa','Expressar e comparar pontos de vista com razões e evidências, sem exposição pessoal.'),
('EF08LI03','Recursos paralinguísticos','Interpretar pausas, entonação e expressão sem exigir contato visual ou gesto corporal.'),
('EF08LI04','Planos e previsões','Comunicar planos e previsões de personagens e cenários fictícios.'),
('EF08LI05','Sentido global em textos orais','Relacionar partes, assunto e informações relevantes em textos orais e multimodais.'),
('EF08LI06','Apreciação literária','Apreciar narrativas legalmente acessíveis, observando linguagem, cenário e efeitos no leitor.'),
('EF08LI07','Manifestações culturais','Comparar manifestações em inglês com contexto, autoria e respeito cultural.'),
('EF08LI08','Inferências e perspectivas','Inferir informações implícitas e comparar seleção de fatos, vozes e evidências.'),
('EF08LI09','Planejamento da escrita','Definir finalidade, público, gênero, suporte e recursos antes de escrever.'),
('EF08LI10','Revisão entre pares','Usar critérios objetivos para oferecer e receber retorno respeitoso, com alternativa privada.'),
('EF08LI11','Reconstrução e edição textual','Cortar, acrescentar, reformular e editar preservando autoria e sentido.'),
('EF08LI12','Produção sobre o futuro','Criar textos sobre futuros fictícios sem exigir projeto de vida ou dado pessoal.'),
('EF08LI13','Formação de palavras','Inferir e formar palavras com prefixos e sufixos em contexto.'),
('EF08LI14','Comparativos e superlativos','Comparar características e quantidades sem classificar pessoas ou corpos.'),
('EF08LI15','Quantificadores','Usar some, any, many e much conforme substantivos e contexto.'),
('EF08LI16','Pronomes relativos','Articular informações com who, which, that e whose, usando referentes claros.'),
('EF08LI17','Futuro e possibilidade','Distinguir be going to, will, may e might em planos, previsões e possibilidades.'),
('EF08LI18','Publicação responsável','Preparar produto final acessível sem postagem pública, nome real ou imagem identificável.'),
('EF08LI19','Comunicação intercultural','Investigar diferenças de sentido em gestos e expressões sem imitar identidades.'),
('EF08LI20','Prevenção de ruídos culturais','Perguntar, esclarecer e reparar mal-entendidos com respeito e sem generalizações.')
), normalized AS (
 SELECT code,'src/escola-brilha/ingles-8ano/bncc-workshops.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','8º Ano','Língua Inglesa',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita','sensorial_auditiva','sensorial_visual'],
jsonb_build_array(jsonb_build_object('title','Guia inclusivo de Língua Inglesa — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Comunicação multimodal e consentida','content',jsonb_build_array('Antecipe contexto, gênero, finalidade e vocabulário; ofereça áudio repetível, velocidade e volume reguláveis, legenda, transcrição e pausas.','Fala pública, leitura em voz alta, gesto, contato visual, dramatização e revisão por colega são opcionais; aceite retorno privado do professor e comunicação alternativa.','Avalie compreensão, inteligibilidade, argumentação e uso de evidências, não imitação de sotaque, rapidez ou performance corporal.')),
 jsonb_build_object('heading','Leitura crítica, literatura e mídia','content',jsonb_build_array('Diferencie informação explícita, inferência e opinião; compare enquadramento, vozes presentes, ausências, argumentos e evidências.','Use contos, imagens, vídeos e outros materiais autorizados, licenciados ou em domínio público conforme aplicável; não reproduza obras integrais protegidas.','Não exponha estudante a fórum público, comentários abertos, contato com desconhecidos ou coleta de comportamento digital.')),
 jsonb_build_object('heading','Escrita e interculturalidade protegidas','content',jsonb_build_array('Planeje finalidade e público, produza rascunho, revise por critérios, reformule e prepare versão final acessível; publicação significa circulação controlada na atividade, não postagem aberta.','Use personagens e futuros fictícios; nunca peça projeto de vida, carreira, crença, identidade, foto, localização, perfil digital, diagnóstico ou história familiar.','Investigue gestos e expressões como variáveis de contexto; não peça imitação de povo, sotaque, deficiência, religião ou identidade.')),
 jsonb_build_object('heading','Critério','content','Compreende quatro de cinco itens e produz argumento ou texto adequado ao contexto com evidência, revisão e respeito intercultural no modo escolhido.')))),
jsonb_build_array(jsonb_build_object('title','1. Interpretar perspectivas','instruction','Identifique contexto, propósito, explícitos, implícitos, vozes e evidências.','activity','Compare duas perspectivas e registre uma inferência sustentada sobre '||lower(title)||'.','support','Legenda, transcrição, áudio regulável, texto segmentado, glossário e leitor de tela.'),jsonb_build_object('title','2. Construir e negociar','instruction','Relacione forma, significado, interlocutor e efeito; use paráfrase ou pergunta para confirmar.','activity','Organize ou transforme três exemplos e justifique uma escolha.','support','Modelo resolvido, cartões, matriz de perspectivas, banco de palavras e pistas graduadas.'),jsonb_build_object('title','3. Produzir, revisar e compartilhar','instruction','Planeje, produza, revise por critérios e circule apenas no ambiente controlado e consentido.','activity','Explique decisões, evidências, mudança feita e cuidado intercultural.','support','Comunicação alternativa, fala opcional, áudio privado, portfólio local, digitação, escrita ou tecnologia assistiva.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Distingue explícito e inferência e compara perspectivas por evidências.'),jsonb_build_object('page',2,'answer','Negocia sentido e relaciona forma, uso e efeito com apoio adequado.'),jsonb_build_object('page',3,'answer','Produz e revisa resposta autoral, acessível e interculturalmente respeitosa.','teacher_note','Registre estratégias e apoio eficaz; não registre voz, projeto de vida, perfil, identidade ou localização.')),
jsonb_build_object('response_modes',jsonb_build_array('pointing','selection','cards','aac','oral_optional','private_rehearsal','private_feedback','private_audio','local_portfolio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'captions',true,'transcript',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'audio_replay',true,'playback_speed_control',true,'volume_control',true,'no_forced_speaking',true,'no_forced_read_aloud',true,'no_forced_eye_contact',true,'no_forced_gesture',true,'no_forced_peer_review',true,'accent_dignity',true,'privacy_preserving',true,'fictional_future_only',true,'no_live_geolocation',true,'no_personal_account_required',true,'no_contact_with_strangers',true,'no_public_posting',true,'no_behavioral_tracking',true,'no_life_plan_disclosure',true,'licensed_materials_only',true,'perspective_and_source_analysis',true,'no_identity_impersonation',true,'cultural_respect',true,'copyright_respect',true,'mobility_vision_hearing_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/ingles-8ano/'||lower(code) FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,subject=EXCLUDED.subject,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
