-- Biblioteca Inclusiva · Geografia do 4º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF04GE01','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-02-culturas-brasileiras.ts','Território brasileiro e diversidade cultural','Reconhecer a formação cultural brasileira com respeito aos diferentes povos, grupos e territórios.'),
('EF04GE02','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-01-populacao-e-migracoes.ts','População e migrações','Analisar fluxos populacionais e contribuições culturais sem exigir origem ou trajetória familiar pessoal.'),
('EF04GE03','src/escola-brilha/curso-v4/geografia-4ano/unidade-2/aula-03-poder-publico-participacao.ts','Poder público e participação social','Distinguir funções públicas e formas seguras e coletivas de participação cidadã em situações fictícias.'),
('EF04GE04','src/escola-brilha/curso-v4/geografia-4ano/unidade-3/aula-02-campo-cidade.ts','Campo e cidade interligados','Explicar relações de interdependência entre campo e cidade por fluxos de pessoas, produtos e serviços.'),
('EF04GE05','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-02-estados-e-df.ts','Unidades político-administrativas','Localizar município, unidade federativa, região e país em mapas de escalas diferentes.'),
('EF04GE06','src/escola-brilha/curso-v4/geografia-4ano/unidade-4/aula-02-territorios-tradicionais.ts','Territórios indígenas e quilombolas','Reconhecer territórios indígenas e quilombolas, seus direitos e sua diversidade sem generalizações ou estereótipos.'),
('EF04GE07','src/escola-brilha/curso-v4/geografia-4ano/unidade-5/aula-01-trabalho-e-economia.ts','Trabalho e atividades econômicas','Comparar atividades econômicas e tipos de trabalho sem hierarquização social ou estereótipos de gênero.'),
('EF04GE08','src/escola-brilha/curso-v4/geografia-4ano/unidade-5/aula-02-producao-circulacao-consumo.ts','Produção, circulação e consumo','Representar etapas e fluxos entre produção, circulação e consumo, incluindo efeitos socioambientais.'),
('EF04GE09','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-03-rosa-dos-ventos.ts','Direções e localização','Aplicar direções cardeais em mapas e grades fictícias com alternativas visuais, táteis e corporais acessíveis.'),
('EF04GE10','src/escola-brilha/curso-v4/geografia-4ano/unidade-1/aula-04-ler-o-mapa.ts','Elementos constitutivos dos mapas','Interpretar título, legenda, orientação, escala e fonte em mapas que não dependam apenas de cores.'),
('EF04GE11','src/escola-brilha/curso-v4/geografia-4ano/unidade-3/aula-01-relevo-e-rios.ts','Paisagens naturais e antrópicas','Comparar relevo, hidrografia e transformações das paisagens usando evidências cartográficas e visuais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','4º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Selecione fontes seguras e contextualizadas','content',jsonb_build_array('Use mapas, municípios, trajetórias migratórias, problemas públicos e cadeias produtivas fictícios; nunca peça endereço, geolocalização, rota, origem familiar, documento, fotografia da moradia ou posicionamento político da criança.','Apresente povos indígenas e comunidades quilombolas no presente, em sua diversidade, com direitos territoriais e protagonismo; evite fantasias, caricaturas e generalizações.')),
 jsonb_build_object('heading','Modele a análise geográfica','content',jsonb_build_array('Ensine a formular pergunta, verificar título e fonte, localizar evidências, comparar escalas e justificar conclusões.','Conecte território, população, campo e cidade, trabalho, produção, circulação, consumo, relevo e rios por relações de causa, consequência e interdependência.','Em mapas, combine cor com texto, forma, textura, contorno e padrão; disponibilize orientação verbal ou versão tátil quando necessário.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe conceitos, divida mapas complexos em camadas, dê uma instrução por vez e ofereça pistas graduadas.','Aceite fala, apontamento, cartões, objetos, mapa, maquete, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala ou coordenação motora como medida isolada de compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com elemento cartográfico, territorial, econômico ou ambiental pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Ler a fonte','instruction','Identifique título, fonte, escala, legenda, orientação, lugar e período quando estiverem disponíveis.','activity','Registre duas informações observáveis e uma dúvida sobre o material.','support','Leitura mediada, ampliação, camadas reduzidas e exploração tátil opcional.'),jsonb_build_object('title','2. Comparar e conectar','instruction','Compare mapas, paisagens, territórios, fluxos ou situações sociais de um cenário fictício.','activity','Monte quadro, mapa, esquema de fluxo ou relação causa-consequência sobre '||lower(title)||'.','support','Exemplo resolvido, prática guiada e pistas graduadas.'),jsonb_build_object('title','3. Argumentar com evidência','instruction','Escolha uma conclusão, indique a evidência e reconheça limites da fonte.','activity','Explique a relação e proponha ação coletiva quando pertinente.','support','Resposta oral, apontada, tátil, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Localiza elementos da fonte e duas informações verificáveis.'),jsonb_build_object('page',2,'answer','Compara ou conecta elementos com coerência espacial.'),jsonb_build_object('page',3,'answer','Conclusão sustentada por evidência e com limite reconhecido.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização, origem familiar ou opinião política real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','map','model','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'no_family_origin_disclosure',true,'no_political_opinion_collection',true,'cultural_respect',true,'indigenous_quilombola_present_day_respect',true,'territorial_rights_context',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-4ano/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
