-- Biblioteca Inclusiva · Geografia do 6º ano completa.
WITH lessons(code,title,goal) AS (VALUES
('EF06GE01','Paisagens e transformações','Comparar paisagens em tempos distintos e identificar mudanças, permanências e agentes transformadores.'),
('EF06GE02','Paisagens de diferentes sociedades','Analisar transformações territoriais realizadas por diferentes sociedades com respeito a conhecimentos e direitos.'),
('EF06GE03','Movimentos da Terra e dinâmica climática','Relacionar movimentos da Terra, circulação atmosférica e ritmos climáticos usando modelos e evidências.'),
('EF06GE04','Ciclo da água e bacias hidrográficas','Explicar ciclo da água, escoamento e bacias relacionando cobertura vegetal, solo e ações humanas.'),
('EF06GE05','Clima e circulação atmosférica','Distinguir tempo e clima e interpretar fatores e elementos climáticos em diferentes escalas.'),
('EF06GE06','Geodinâmica e tectônica de placas','Explicar processos internos da Terra e sua relação com relevo e distribuição de fenômenos geológicos.'),
('EF06GE07','Paisagens climatobotânicas','Relacionar clima, relevo, solo, água e vegetação em grandes conjuntos de paisagens mundiais.'),
('EF06GE08','Escalas e distâncias','Aplicar escala gráfica e numérica para comparar distâncias e níveis de detalhamento cartográfico.'),
('EF06GE09','Curvas de nível e perfil topográfico','Interpretar curvas de nível e perfis topográficos por altitude, declividade e forma do relevo.'),
('EF06GE10','Uso do solo e da água','Analisar transformações do solo e da água no campo e na cidade por atividades econômicas e infraestrutura.'),
('EF06GE11','Sociedade, natureza e biodiversidade','Explicar interações entre componentes naturais, biodiversidade e ações sociais em diferentes escalas.'),
('EF06GE12','Consumo de água','Comparar usos da água por setor, território e tecnologia sem reduzir a questão ao consumo individual.'),
('EF06GE13','Práticas humanas e consequências ambientais','Avaliar consequências ambientais de práticas humanas, grupos envolvidos e alternativas sustentáveis.')
), normalized AS (
 SELECT code,'src/escola-brilha/curso-v4/geografia-6ano/dados-fund2.ts'::text AS source_key,title,goal FROM lessons
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','6º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare fontes verificáveis e seguras','content',jsonb_build_array('Use mapas, imagens, modelos, séries históricas e dados públicos agregados; cenários locais devem ser fictícios e nunca solicitar endereço, geolocalização, rota, conta de água, consumo doméstico, local de trabalho familiar ou fotografia da moradia.','Contextualize povos originários, comunidades e atividades econômicas com diversidade, protagonismo, direitos e fontes confiáveis, evitando generalizações.')),
 jsonb_build_object('heading','Modele o raciocínio científico-geográfico','content',jsonb_build_array('Comece por pergunta, hipótese e previsão; identifique escala espacial e temporal; compare evidências; revise a hipótese e comunique a conclusão.','Diferencie correlação de causalidade e fenômeno natural de risco socialmente construído; não apresente desastre ou impacto como culpa inevitável de moradores.','Em mapas, gráficos, diagramas e modelos, combine cor com rótulo, forma, textura, contorno ou padrão e ofereça descrição textual ou tátil.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Antecipe vocabulário, segmente textos densos, revele mapas e gráficos em camadas e ofereça exemplo resolvido e pistas graduadas.','Aceite fala, apontamento, cartões, mapa, tabela, gráfico, modelo, esquema, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não use rapidez, memória, leitura, visão, fala, cálculo ou coordenação motora como medida isolada do domínio conceitual.')),
 jsonb_build_object('heading','Critério','content','Resolve quatro de cinco situações e sustenta ao menos três conclusões com evidência, escala e relação geográfica adequadas.')))),
jsonb_build_array(jsonb_build_object('title','1. Formular e prever','instruction','Leia a questão, defina conceitos, escala e evidências necessárias.','activity','Registre hipótese e previsão antes de observar os dados de '||lower(title)||'.','support','Glossário visual, texto segmentado, leitura mediada e organizador de hipótese.'),jsonb_build_object('title','2. Analisar evidências','instruction','Compare mapa, gráfico, imagem, modelo ou dados e procure padrões e exceções.','activity','Construa tabela, perfil, mapa, diagrama ou cadeia causal adequada ao problema.','support','Camadas de informação, exemplo resolvido e pistas graduadas.'),jsonb_build_object('title','3. Concluir e revisar','instruction','Responda à questão, cite evidências, revise a hipótese e reconheça limites.','activity','Explique a relação e avalie alternativas por impacto, escala, viabilidade e equidade.','support','Resposta oral, apontada, esquemática, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Hipótese pertinente, previsão verificável e escala identificada.'),jsonb_build_object('page',2,'answer','Representação coerente com padrões, exceções e unidades preservadas.'),jsonb_build_object('page',3,'answer','Conclusão sustentada, hipótese revisada e limite reconhecido.','teacher_note','Registre raciocínio, autonomia, apoio eficaz e próximo passo; não registre localização ou consumo doméstico real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','map','table','chart','model','diagram','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'segmented_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_local_scenarios',true,'aggregated_public_data_only',true,'no_live_geolocation',true,'no_household_consumption_disclosure',true,'no_family_workplace_collection',true,'indigenous_community_rights_context',true,'disaster_risk_contextualized',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'color_independent_symbols',true,'accessible_charts',true,'tactile_option',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/geografia-6ano/'||code FROM normalized
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
