
UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 27 + 35?","resolution":[{"line":"Some as unidades: 7 + 5 = 12","note":"vai 1"},{"line":"Some as dezenas: 2 + 3 + 1 = 6"},{"line":"Resultado: 62"}],"answer":"62","why":"Somamos coluna por coluna, fazendo a reserva quando passa de 9."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Calcule 48 + 25.","hint":"Some unidades primeiro; se passar de 9, vai 1 para as dezenas.","options":[{"text":"73","isCorrect":true,"reason":"8+5=13 (vai 1); 4+2+1=7 → 73."},{"text":"63","isCorrect":false,"reason":"Esqueceu de somar o 1 que veio das unidades."},{"text":"713","isCorrect":false,"reason":"Juntou os algarismos sem fazer a reserva."}]}]'::jsonb,
  exercicios = '[{"question":"Calcule 19 + 24.","options":[{"text":"43","isCorrect":true,"reason":"9+4=13 (vai 1); 1+2+1=4."},{"text":"33","isCorrect":false,"reason":"Não fez a reserva."},{"text":"53","isCorrect":false,"reason":"Somou dezenas a mais."}]},{"question":"Calcule 56 + 37.","options":[{"text":"93","isCorrect":true,"reason":"6+7=13 (vai 1); 5+3+1=9."},{"text":"83","isCorrect":false,"reason":"Esqueceu da reserva."},{"text":"813","isCorrect":false,"reason":"Concatenou os algarismos."}]},{"question":"Calcule 125 + 76.","options":[{"text":"201","isCorrect":true,"reason":"5+6=11; 2+7+1=10; 1+0+1=2."},{"text":"191","isCorrect":false,"reason":"Esqueceu uma reserva."},{"text":"211","isCorrect":false,"reason":"Reservou demais."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Ana tinha R$ 138 e ganhou mais R$ 96.","question":"Com quanto ela está agora?","options":[{"text":"R$ 234","isCorrect":true,"reason":"138+96: 8+6=14; 3+9+1=13; 1+0+1=2."},{"text":"R$ 224","isCorrect":false,"reason":"Esqueceu de levar o 1."},{"text":"R$ 134","isCorrect":false,"reason":"Trocou algarismos."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Alinhe as colunas (U, D, C)"},{"label":"Some unidades primeiro"},{"label":"Reserve 1 quando passar de 9"}],"takeaways":["Somar é juntar quantidades.","A reserva mantém o valor posicional certo."]}'::jsonb
WHERE slug = 'mat-adicao';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 72 − 28?","resolution":[{"line":"Não dá para 2 − 8 nas unidades","note":"empresta 1 da dezena"},{"line":"12 − 8 = 4"},{"line":"6 − 2 = 4"},{"line":"Resultado: 44"}],"answer":"44","why":"Quando a unidade de cima é menor, pedimos 1 emprestado da dezena."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Calcule 53 − 17.","hint":"Se a unidade de cima for menor, peça emprestado.","options":[{"text":"36","isCorrect":true,"reason":"13−7=6; 4−1=3."},{"text":"46","isCorrect":false,"reason":"Não emprestou da dezena."},{"text":"44","isCorrect":false,"reason":"Subtraiu errado as dezenas."}]}]'::jsonb,
  exercicios = '[{"question":"81 − 35 = ?","options":[{"text":"46","isCorrect":true,"reason":"11−5=6; 7−3=4."},{"text":"56","isCorrect":false,"reason":"Não emprestou."},{"text":"54","isCorrect":false,"reason":"Erro nas dezenas."}]},{"question":"100 − 47 = ?","options":[{"text":"53","isCorrect":true,"reason":"Empréstimo duplo."},{"text":"63","isCorrect":false,"reason":"Empréstimo errado."},{"text":"57","isCorrect":false,"reason":"Subtraiu invertendo."}]},{"question":"245 − 128 = ?","options":[{"text":"117","isCorrect":true,"reason":"15−8=7; 3−2=1; 2−1=1."},{"text":"127","isCorrect":false,"reason":"Não emprestou."},{"text":"107","isCorrect":false,"reason":"Erro na dezena."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Um livro custa R$ 62 e Pedro tem R$ 25.","question":"Quanto falta para ele comprar o livro?","options":[{"text":"R$ 37","isCorrect":true,"reason":"62−25: 12−5=7; 5−2=3."},{"text":"R$ 47","isCorrect":false,"reason":"Não emprestou."},{"text":"R$ 43","isCorrect":false,"reason":"Subtraiu na ordem errada."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Alinhe U, D, C"},{"label":"Peça emprestado quando precisar"},{"label":"Confira somando o resultado"}],"takeaways":["Subtrair é tirar.","O empréstimo preserva o valor posicional."]}'::jsonb
WHERE slug = 'mat-subtracao';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 23 × 4?","resolution":[{"line":"4 × 3 = 12","note":"escreve 2, vai 1"},{"line":"4 × 2 = 8; 8 + 1 = 9"},{"line":"Resultado: 92"}],"answer":"92","why":"Multiplicamos cada algarismo pela unidade, somando a reserva."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Calcule 16 × 5.","hint":"5×6=30 (vai 3); 5×1+3=8.","options":[{"text":"80","isCorrect":true,"reason":"5×6=30; 5×1+3=8."},{"text":"55","isCorrect":false,"reason":"Esqueceu a reserva."},{"text":"75","isCorrect":false,"reason":"Reserva errada."}]}]'::jsonb,
  exercicios = '[{"question":"12 × 6 = ?","options":[{"text":"72","isCorrect":true,"reason":"6×2=12; 6×1+1=7."},{"text":"62","isCorrect":false,"reason":"Esqueceu a reserva."},{"text":"76","isCorrect":false,"reason":"Trocou algarismos."}]},{"question":"25 × 4 = ?","options":[{"text":"100","isCorrect":true,"reason":"4×5=20; 4×2+2=10."},{"text":"80","isCorrect":false,"reason":"Esqueceu reserva."},{"text":"90","isCorrect":false,"reason":"Erro na reserva."}]},{"question":"14 × 9 = ?","options":[{"text":"126","isCorrect":true,"reason":"9×4=36; 9×1+3=12."},{"text":"116","isCorrect":false,"reason":"Reserva errada."},{"text":"136","isCorrect":false,"reason":"Reserva a mais."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Uma caixa tem 18 lápis. Há 7 caixas.","question":"Quantos lápis ao todo?","options":[{"text":"126","isCorrect":true,"reason":"18×7: 7×8=56; 7×1+5=12."},{"text":"116","isCorrect":false,"reason":"Reserva errada."},{"text":"135","isCorrect":false,"reason":"Multiplicou errado."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Multiplique unidade por unidade"},{"label":"Reserve quando passar de 9"},{"label":"Some a reserva à próxima"}],"takeaways":["Multiplicar é somar parcelas iguais."]}'::jsonb
WHERE slug = 'mat-multiplicacao';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 84 ÷ 4?","resolution":[{"line":"8 ÷ 4 = 2"},{"line":"4 ÷ 4 = 1"},{"line":"Resultado: 21"}],"answer":"21","why":"Dividimos algarismo por algarismo, da esquerda para a direita."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Calcule 96 ÷ 3.","hint":"Comece pelo algarismo mais à esquerda.","options":[{"text":"32","isCorrect":true,"reason":"9÷3=3; 6÷3=2."},{"text":"23","isCorrect":false,"reason":"Inverteu a ordem."},{"text":"33","isCorrect":false,"reason":"Dividiu o 6 errado."}]}]'::jsonb,
  exercicios = '[{"question":"72 ÷ 6 = ?","options":[{"text":"12","isCorrect":true,"reason":"6×12=72."},{"text":"11","isCorrect":false,"reason":"6×11=66."},{"text":"13","isCorrect":false,"reason":"6×13=78."}]},{"question":"144 ÷ 12 = ?","options":[{"text":"12","isCorrect":true,"reason":"12×12=144."},{"text":"14","isCorrect":false,"reason":"12×14=168."},{"text":"10","isCorrect":false,"reason":"12×10=120."}]},{"question":"60 ÷ 5 = ?","options":[{"text":"12","isCorrect":true,"reason":"5×12=60."},{"text":"15","isCorrect":false,"reason":"5×15=75."},{"text":"10","isCorrect":false,"reason":"5×10=50."}]}]'::jsonb,
  desafio = '{"contextualScenario":"36 balas serão divididas entre 4 crianças.","question":"Quantas cada criança recebe?","options":[{"text":"9","isCorrect":true,"reason":"4×9=36."},{"text":"8","isCorrect":false,"reason":"4×8=32."},{"text":"7","isCorrect":false,"reason":"4×7=28."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Divida da esquerda para a direita"},{"label":"Use a tabuada inversa"},{"label":"Confira: quociente × divisor + resto = dividendo"}],"takeaways":["Dividir é repartir em partes iguais."]}'::jsonb
WHERE slug = 'mat-divisao';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Resolva x + 5 = 12.","resolution":[{"line":"x + 5 = 12"},{"line":"x = 12 − 5","note":"isolar x"},{"line":"x = 7"}],"answer":"x = 7","why":"O que está somando passa subtraindo para o outro lado."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Resolva 2x = 14.","hint":"O que multiplica passa dividindo.","options":[{"text":"x = 7","isCorrect":true,"reason":"14 ÷ 2 = 7."},{"text":"x = 12","isCorrect":false,"reason":"Subtraiu em vez de dividir."},{"text":"x = 16","isCorrect":false,"reason":"Somou em vez de dividir."}]}]'::jsonb,
  exercicios = '[{"question":"x − 4 = 9. x = ?","options":[{"text":"13","isCorrect":true,"reason":"x = 9 + 4."},{"text":"5","isCorrect":false,"reason":"Subtraiu errado."},{"text":"36","isCorrect":false,"reason":"Multiplicou."}]},{"question":"3x = 21. x = ?","options":[{"text":"7","isCorrect":true,"reason":"21 ÷ 3 = 7."},{"text":"18","isCorrect":false,"reason":"Subtraiu."},{"text":"24","isCorrect":false,"reason":"Somou."}]},{"question":"x/2 = 6. x = ?","options":[{"text":"12","isCorrect":true,"reason":"6 × 2 = 12."},{"text":"3","isCorrect":false,"reason":"Dividiu de novo."},{"text":"8","isCorrect":false,"reason":"Somou 2."}]}]'::jsonb,
  desafio = '{"contextualScenario":"O dobro da idade de Léo mais 3 é 17.","question":"Qual é a idade de Léo?","options":[{"text":"7","isCorrect":true,"reason":"2x+3=17 → 2x=14 → x=7."},{"text":"10","isCorrect":false,"reason":"Não dividiu por 2."},{"text":"14","isCorrect":false,"reason":"Parou em 2x=14."}]}'::jsonb,
  revisao = '{"format":"flow","nodes":[{"label":"Isolar x"},{"label":"Inverter a operação"},{"label":"Conferir substituindo"}],"takeaways":["Resolver equação = descobrir o valor de x."]}'::jsonb
WHERE slug = 'mat-equacoes';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 1/2 + 1/4?","resolution":[{"line":"MMC(2,4) = 4"},{"line":"1/2 = 2/4"},{"line":"2/4 + 1/4 = 3/4"}],"answer":"3/4","why":"Para somar frações, igualamos os denominadores."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Quanto é 2/3 de 9?","hint":"Divida por 3 e multiplique por 2.","options":[{"text":"6","isCorrect":true,"reason":"9 ÷ 3 = 3; 3 × 2 = 6."},{"text":"3","isCorrect":false,"reason":"Parou na divisão."},{"text":"9","isCorrect":false,"reason":"Não dividiu."}]}]'::jsonb,
  exercicios = '[{"question":"1/3 + 1/3 = ?","options":[{"text":"2/3","isCorrect":true,"reason":"Mesmo denominador: soma os numeradores."},{"text":"1/6","isCorrect":false,"reason":"Multiplicou denominadores."},{"text":"2/6","isCorrect":false,"reason":"Somou denominadores."}]},{"question":"3/4 de 20 = ?","options":[{"text":"15","isCorrect":true,"reason":"20 ÷ 4 = 5; 5 × 3 = 15."},{"text":"5","isCorrect":false,"reason":"Parou na divisão."},{"text":"60","isCorrect":false,"reason":"Multiplicou direto."}]},{"question":"Simplifique 4/8.","options":[{"text":"1/2","isCorrect":true,"reason":"Dividiu por 4."},{"text":"2/4","isCorrect":false,"reason":"Simplificou parcialmente."},{"text":"4/2","isCorrect":false,"reason":"Inverteu."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Uma pizza foi cortada em 8 pedaços. Comeram 3.","question":"Que fração sobrou?","options":[{"text":"5/8","isCorrect":true,"reason":"8 − 3 = 5; total 8 → 5/8."},{"text":"3/8","isCorrect":false,"reason":"Isso é o que comeram."},{"text":"5/3","isCorrect":false,"reason":"Inverteu."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Numerador / Denominador"},{"label":"Mesmo denominador → soma direta"},{"label":"Simplificar pelo MDC"}],"takeaways":["Fração é parte de um todo."]}'::jsonb
WHERE slug = 'mat-fracoes';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 20% de 50?","resolution":[{"line":"20% = 20/100 = 0,2"},{"line":"0,2 × 50 = 10"}],"answer":"10","why":"Porcentagem é uma fração de denominador 100."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Quanto é 10% de 80?","hint":"10% é dividir por 10.","options":[{"text":"8","isCorrect":true,"reason":"80 ÷ 10 = 8."},{"text":"10","isCorrect":false,"reason":"Confundiu com a taxa."},{"text":"80","isCorrect":false,"reason":"Não calculou."}]}]'::jsonb,
  exercicios = '[{"question":"25% de 200 = ?","options":[{"text":"50","isCorrect":true,"reason":"200 ÷ 4 = 50."},{"text":"25","isCorrect":false,"reason":"Confundiu com a taxa."},{"text":"75","isCorrect":false,"reason":"Conta errada."}]},{"question":"50% de 90 = ?","options":[{"text":"45","isCorrect":true,"reason":"Metade de 90."},{"text":"50","isCorrect":false,"reason":"Confundiu taxa com valor."},{"text":"40","isCorrect":false,"reason":"Erro de cálculo."}]},{"question":"5% de 200 = ?","options":[{"text":"10","isCorrect":true,"reason":"200 × 0,05."},{"text":"20","isCorrect":false,"reason":"Calculou 10%."},{"text":"5","isCorrect":false,"reason":"Confundiu com taxa."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Um tênis custa R$ 250 e tem 20% de desconto.","question":"Por quanto sai com desconto?","options":[{"text":"R$ 200","isCorrect":true,"reason":"20% de 250 = 50; 250 − 50 = 200."},{"text":"R$ 230","isCorrect":false,"reason":"Calculou só 10%."},{"text":"R$ 50","isCorrect":false,"reason":"Esse é o desconto, não o preço."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"X% = X/100"},{"label":"Multiplicar pelo valor total"},{"label":"Desconto = total − porcentagem"}],"takeaways":["Porcentagem facilita comparar partes do todo."]}'::jsonb
WHERE slug = 'mat-porcentagem';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 2³?","resolution":[{"line":"2³ = 2 × 2 × 2"},{"line":"= 4 × 2 = 8"}],"answer":"8","why":"Potência é multiplicação repetida da base por ela mesma."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Quanto é 5²?","hint":"5² = 5 × 5.","options":[{"text":"25","isCorrect":true,"reason":"5 × 5 = 25."},{"text":"10","isCorrect":false,"reason":"Somou em vez de multiplicar."},{"text":"55","isCorrect":false,"reason":"Concatenou os algarismos."}]}]'::jsonb,
  exercicios = '[{"question":"3³ = ?","options":[{"text":"27","isCorrect":true,"reason":"3×3=9; 9×3=27."},{"text":"9","isCorrect":false,"reason":"Parou em 3²."},{"text":"33","isCorrect":false,"reason":"Não multiplicou."}]},{"question":"10⁴ = ?","options":[{"text":"10000","isCorrect":true,"reason":"10×10×10×10."},{"text":"1000","isCorrect":false,"reason":"Calculou 10³."},{"text":"40","isCorrect":false,"reason":"Multiplicou base por expoente."}]},{"question":"7¹ = ?","options":[{"text":"7","isCorrect":true,"reason":"Base elevada a 1 é ela mesma."},{"text":"1","isCorrect":false,"reason":"Confundiu com expoente 0."},{"text":"0","isCorrect":false,"reason":"Não é zero."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Uma bactéria dobra a cada hora. Começa com 1.","question":"Quantas serão depois de 5 horas?","options":[{"text":"32","isCorrect":true,"reason":"2⁵ = 32."},{"text":"10","isCorrect":false,"reason":"Multiplicou 2×5."},{"text":"16","isCorrect":false,"reason":"Parou em 2⁴."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Base × Base × ... (expoente vezes)"},{"label":"Base¹ = base"},{"label":"Base⁰ = 1"}],"takeaways":["Potência acelera multiplicações repetidas."]}'::jsonb
WHERE slug = 'mat-potenciacao';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quanto é 2 + 3 × 4?","resolution":[{"line":"Resolva a multiplicação primeiro: 3 × 4 = 12"},{"line":"Some: 2 + 12 = 14"}],"answer":"14","why":"Multiplicação tem prioridade sobre a soma."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Quanto é 10 − 2 × 3?","hint":"× antes de −.","options":[{"text":"4","isCorrect":true,"reason":"2×3=6; 10−6=4."},{"text":"24","isCorrect":false,"reason":"Fez (10−2)×3."},{"text":"30","isCorrect":false,"reason":"Multiplicou tudo."}]}]'::jsonb,
  exercicios = '[{"question":"(2 + 3) × 4 = ?","options":[{"text":"20","isCorrect":true,"reason":"Parênteses primeiro: 5×4."},{"text":"14","isCorrect":false,"reason":"Ignorou os parênteses."},{"text":"24","isCorrect":false,"reason":"Multiplicou errado."}]},{"question":"6 + 4 ÷ 2 = ?","options":[{"text":"8","isCorrect":true,"reason":"4÷2=2; 6+2."},{"text":"5","isCorrect":false,"reason":"Somou antes de dividir."},{"text":"12","isCorrect":false,"reason":"Multiplicou."}]},{"question":"2³ + 1 = ?","options":[{"text":"9","isCorrect":true,"reason":"2³=8; 8+1=9."},{"text":"7","isCorrect":false,"reason":"Calculou 2×3."},{"text":"6","isCorrect":false,"reason":"Erro na potência."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Resolva: 3 × (4 + 2) − 5.","question":"Qual o resultado?","options":[{"text":"13","isCorrect":true,"reason":"4+2=6; 3×6=18; 18−5=13."},{"text":"9","isCorrect":false,"reason":"Esqueceu os parênteses."},{"text":"15","isCorrect":false,"reason":"Não subtraiu."}]}'::jsonb,
  revisao = '{"format":"flow","nodes":[{"label":"1º Parênteses"},{"label":"2º Potências e raízes"},{"label":"3º × e ÷"},{"label":"4º + e −"}],"takeaways":["Sempre respeite a ordem de operações."]}'::jsonb
WHERE slug = 'mat-expressoes-numericas';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Compare 248 e 284.","resolution":[{"line":"Centenas iguais: 2 = 2"},{"line":"Compare dezenas: 4 < 8"},{"line":"Logo 248 < 284"}],"answer":"248 < 284","why":"Compare casa por casa, começando pela maior ordem."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Qual é maior: 1.205 ou 1.250?","hint":"Compare casa por casa.","options":[{"text":"1.250","isCorrect":true,"reason":"Mesma centena; dezena 5 > 0."},{"text":"1.205","isCorrect":false,"reason":"Dezena menor."},{"text":"São iguais","isCorrect":false,"reason":"Diferem nas dezenas."}]}]'::jsonb,
  exercicios = '[{"question":"Qual é menor: 89 ou 98?","options":[{"text":"89","isCorrect":true,"reason":"Dezena 8 < 9."},{"text":"98","isCorrect":false,"reason":"É o maior."},{"text":"Iguais","isCorrect":false,"reason":"Não são."}]},{"question":"Ordene em ordem crescente: 12, 21, 2.","options":[{"text":"2, 12, 21","isCorrect":true,"reason":"Do menor para o maior."},{"text":"21, 12, 2","isCorrect":false,"reason":"Decrescente."},{"text":"12, 2, 21","isCorrect":false,"reason":"Fora de ordem."}]},{"question":"Qual é maior: 1.000 ou 999?","options":[{"text":"1.000","isCorrect":true,"reason":"Tem uma casa a mais."},{"text":"999","isCorrect":false,"reason":"Menos algarismos."},{"text":"Iguais","isCorrect":false,"reason":"Não são."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Três alunos tiraram 87, 78 e 88.","question":"Quem ficou em primeiro?","options":[{"text":"O do 88","isCorrect":true,"reason":"88 > 87 > 78."},{"text":"O do 87","isCorrect":false,"reason":"Ficou em segundo."},{"text":"Todos empataram","isCorrect":false,"reason":"São diferentes."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Conte os algarismos"},{"label":"Compare casa por casa"},{"label":"Use <, >, ="}],"takeaways":["Mais algarismos geralmente significa número maior."]}'::jsonb
WHERE slug = 'mat-comparacao-numeros';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Leia o número 3.405.","resolution":[{"line":"3 → 3 mil"},{"line":"4 → 4 centenas"},{"line":"0 → 0 dezena"},{"line":"5 → 5 unidades"}],"answer":"três mil, quatrocentos e cinco","why":"Cada algarismo tem valor pela posição."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Como se lê 1.207?","hint":"Identifique milhar, centena, dezena, unidade.","options":[{"text":"mil, duzentos e sete","isCorrect":true,"reason":"1 milhar, 2 centenas, 7 unidades."},{"text":"mil e vinte e sete","isCorrect":false,"reason":"Ignorou a centena."},{"text":"doze mil e sete","isCorrect":false,"reason":"Leu o 12 junto."}]}]'::jsonb,
  exercicios = '[{"question":"Como se lê 405?","options":[{"text":"quatrocentos e cinco","isCorrect":true,"reason":"4 centenas, 5 unidades."},{"text":"quarenta e cinco","isCorrect":false,"reason":"Ignorou a centena."},{"text":"quatro mil e cinco","isCorrect":false,"reason":"Não há milhar."}]},{"question":"Qual número equivale a dois mil e dez?","options":[{"text":"2.010","isCorrect":true,"reason":"2 milhares + 1 dezena."},{"text":"2.100","isCorrect":false,"reason":"Trocou ordens."},{"text":"210","isCorrect":false,"reason":"Falta o milhar."}]},{"question":"Valor do algarismo 7 em 372?","options":[{"text":"70","isCorrect":true,"reason":"Casa das dezenas."},{"text":"7","isCorrect":false,"reason":"Seria nas unidades."},{"text":"700","isCorrect":false,"reason":"Seria nas centenas."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Um estádio comporta cinco mil, trezentas e vinte pessoas.","question":"Qual é esse número?","options":[{"text":"5.320","isCorrect":true,"reason":"5 milhares + 3 centenas + 2 dezenas."},{"text":"5.032","isCorrect":false,"reason":"Trocou ordens."},{"text":"532","isCorrect":false,"reason":"Faltou o milhar."}]}'::jsonb,
  revisao = '{"format":"table","nodes":[{"label":"UM","detail":"unidade de milhar"},{"label":"C","detail":"centena"},{"label":"D","detail":"dezena"},{"label":"U","detail":"unidade"}],"takeaways":["A posição define o valor do algarismo."]}'::jsonb
WHERE slug = 'mat-leitura-numeros';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Decomponha 347.","resolution":[{"line":"3 centenas = 300"},{"line":"4 dezenas = 40"},{"line":"7 unidades = 7"},{"line":"300 + 40 + 7 = 347"}],"answer":"300 + 40 + 7","why":"O sistema decimal organiza os números em ordens de 10."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Decomponha 502.","hint":"Olhe centena, dezena, unidade.","options":[{"text":"500 + 0 + 2","isCorrect":true,"reason":"5C + 0D + 2U."},{"text":"50 + 2","isCorrect":false,"reason":"Ignorou a centena."},{"text":"5 + 0 + 2","isCorrect":false,"reason":"Esqueceu o valor posicional."}]}]'::jsonb,
  exercicios = '[{"question":"Quanto vale o 9 em 1.937?","options":[{"text":"900","isCorrect":true,"reason":"Está nas centenas."},{"text":"90","isCorrect":false,"reason":"Seria nas dezenas."},{"text":"9","isCorrect":false,"reason":"Seria nas unidades."}]},{"question":"75 = ?","options":[{"text":"70 + 5","isCorrect":true,"reason":"7D + 5U."},{"text":"7 + 5","isCorrect":false,"reason":"Ignorou a dezena."},{"text":"700 + 5","isCorrect":false,"reason":"Não há centena."}]},{"question":"1.000 tem quantos zeros?","options":[{"text":"3","isCorrect":true,"reason":"1 + 3 zeros."},{"text":"2","isCorrect":false,"reason":"Isso é cem."},{"text":"4","isCorrect":false,"reason":"Isso é dez mil."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Some 2 centenas + 13 dezenas + 4 unidades.","question":"Qual é o número?","options":[{"text":"334","isCorrect":true,"reason":"200 + 130 + 4."},{"text":"234","isCorrect":false,"reason":"Não juntou 13 dezenas."},{"text":"2.134","isCorrect":false,"reason":"Concatenou."}]}'::jsonb,
  revisao = '{"format":"diagram","nodes":[{"label":"Base 10"},{"label":"Ordens (U, D, C, UM)"},{"label":"Valor posicional"}],"takeaways":["Cada casa vale 10 vezes a anterior."]}'::jsonb
WHERE slug = 'mat-sistema-decimal';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Um retângulo tem 5 cm × 3 cm. Qual a área?","resolution":[{"line":"Área = base × altura"},{"line":"= 5 × 3 = 15"}],"answer":"15 cm²","why":"A área é o número de quadradinhos de 1 cm que cabem dentro."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Perímetro de um quadrado de lado 4 cm?","hint":"P = 4 × lado.","options":[{"text":"16 cm","isCorrect":true,"reason":"4 × 4 = 16."},{"text":"8 cm","isCorrect":false,"reason":"Somou só 2 lados."},{"text":"12 cm","isCorrect":false,"reason":"Somou 3 lados."}]}]'::jsonb,
  exercicios = '[{"question":"Quantos lados tem um triângulo?","options":[{"text":"3","isCorrect":true,"reason":"Tri = 3."},{"text":"4","isCorrect":false,"reason":"Isso é quadrilátero."},{"text":"5","isCorrect":false,"reason":"Isso é pentágono."}]},{"question":"Área de um quadrado de lado 6?","options":[{"text":"36","isCorrect":true,"reason":"6 × 6."},{"text":"24","isCorrect":false,"reason":"Calculou o perímetro."},{"text":"12","isCorrect":false,"reason":"Apenas 2 lados."}]},{"question":"O círculo tem quantos lados retos?","options":[{"text":"Nenhum","isCorrect":true,"reason":"É uma curva fechada."},{"text":"1","isCorrect":false,"reason":"Não tem lado reto."},{"text":"Infinitos","isCorrect":false,"reason":"Não conta lados num círculo."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Uma sala mede 4 m × 5 m e será forrada com piso.","question":"Quantos m² de piso são necessários?","options":[{"text":"20 m²","isCorrect":true,"reason":"Área = 4 × 5."},{"text":"9 m²","isCorrect":false,"reason":"Somou os lados."},{"text":"18 m²","isCorrect":false,"reason":"Calculou perímetro."}]}'::jsonb,
  revisao = '{"format":"diagram","nodes":[{"label":"Perímetro = soma dos lados"},{"label":"Área = espaço dentro"},{"label":"Volume = espaço 3D"}],"takeaways":["Geometria estuda formas e medidas."]}'::jsonb
WHERE slug = 'mat-geometria';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Quantos centímetros há em 2 metros?","resolution":[{"line":"1 m = 100 cm"},{"line":"2 × 100 = 200"}],"answer":"200 cm","why":"As unidades mudam de 10 em 10."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Quantos gramas há em 1,5 kg?","hint":"1 kg = 1000 g.","options":[{"text":"1500 g","isCorrect":true,"reason":"1,5 × 1000."},{"text":"150 g","isCorrect":false,"reason":"Multiplicou por 100."},{"text":"15 g","isCorrect":false,"reason":"Multiplicou por 10."}]}]'::jsonb,
  exercicios = '[{"question":"500 ml = ? L","options":[{"text":"0,5 L","isCorrect":true,"reason":"1 L = 1000 ml."},{"text":"5 L","isCorrect":false,"reason":"Multiplicou."},{"text":"50 L","isCorrect":false,"reason":"Erro de vírgula."}]},{"question":"3 horas = ? min","options":[{"text":"180","isCorrect":true,"reason":"3 × 60."},{"text":"30","isCorrect":false,"reason":"Confundiu."},{"text":"300","isCorrect":false,"reason":"Multiplicou por 100."}]},{"question":"1 m = ? mm","options":[{"text":"1000","isCorrect":true,"reason":"1 m = 1000 mm."},{"text":"100","isCorrect":false,"reason":"Isso é cm."},{"text":"10","isCorrect":false,"reason":"Isso é dm para cm."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Uma receita pede 250 g e a balança é em kg.","question":"Quanto é em kg?","options":[{"text":"0,25 kg","isCorrect":true,"reason":"250 ÷ 1000."},{"text":"2,5 kg","isCorrect":false,"reason":"Vírgula errada."},{"text":"25 kg","isCorrect":false,"reason":"Multiplicou."}]}'::jsonb,
  revisao = '{"format":"table","nodes":[{"label":"Comprimento","detail":"km, m, cm, mm"},{"label":"Massa","detail":"kg, g, mg"},{"label":"Capacidade","detail":"L, ml"},{"label":"Tempo","detail":"h, min, s"}],"takeaways":["Converter unidades é multiplicar ou dividir por 10, 100, 1000…"]}'::jsonb
WHERE slug = 'mat-medidas';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Notas: 7, 8, 9, 6. Qual a média?","resolution":[{"line":"Some: 7+8+9+6 = 30"},{"line":"Divida por 4: 30 ÷ 4 = 7,5"}],"answer":"7,5","why":"Média é a soma dividida pela quantidade."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Média de 10 e 20?","hint":"Some e divida por 2.","options":[{"text":"15","isCorrect":true,"reason":"(10+20)/2."},{"text":"30","isCorrect":false,"reason":"Não dividiu."},{"text":"10","isCorrect":false,"reason":"Só o menor."}]}]'::jsonb,
  exercicios = '[{"question":"Moda de [2,3,3,4,5]?","options":[{"text":"3","isCorrect":true,"reason":"Valor que mais aparece."},{"text":"4","isCorrect":false,"reason":"É a mediana."},{"text":"5","isCorrect":false,"reason":"É o máximo."}]},{"question":"Mediana de [1,2,3,4,5]?","options":[{"text":"3","isCorrect":true,"reason":"Valor do meio."},{"text":"2,5","isCorrect":false,"reason":"Seria com pares."},{"text":"1","isCorrect":false,"reason":"É o mínimo."}]},{"question":"Média de 4, 8 e 12?","options":[{"text":"8","isCorrect":true,"reason":"24 ÷ 3."},{"text":"6","isCorrect":false,"reason":"Dividiu por 4."},{"text":"12","isCorrect":false,"reason":"Soma sem dividir."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Idades: 10, 12, 14, 12, 12.","question":"Qual é a moda?","options":[{"text":"12","isCorrect":true,"reason":"Aparece 3 vezes."},{"text":"10","isCorrect":false,"reason":"Só uma vez."},{"text":"14","isCorrect":false,"reason":"Só uma vez."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Média = soma ÷ quantidade"},{"label":"Moda = mais frequente"},{"label":"Mediana = do meio"}],"takeaways":["Estatística resume conjuntos de dados."]}'::jsonb
WHERE slug = 'mat-estatistica';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Num gráfico de barras, A=10, B=20, C=15. Qual a maior?","resolution":[{"line":"Compare alturas"},{"line":"20 > 15 > 10"}],"answer":"B (20)","why":"Em gráficos de barras, a altura representa a quantidade."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Um setor é metade do círculo. Que porcentagem ele representa?","hint":"Metade = 50%.","options":[{"text":"50%","isCorrect":true,"reason":"Metade do total."},{"text":"25%","isCorrect":false,"reason":"Isso é um quarto."},{"text":"100%","isCorrect":false,"reason":"Seria o círculo inteiro."}]}]'::jsonb,
  exercicios = '[{"question":"Gráfico de barras serve para…","options":[{"text":"Comparar quantidades","isCorrect":true,"reason":"Função principal."},{"text":"Evolução no tempo","isCorrect":false,"reason":"Isso é gráfico de linhas."},{"text":"Calcular médias","isCorrect":false,"reason":"Não é função do gráfico."}]},{"question":"Gráfico de linhas mostra…","options":[{"text":"Evolução no tempo","isCorrect":true,"reason":"Conecta pontos no tempo."},{"text":"Partes de um todo","isCorrect":false,"reason":"Isso é setores."},{"text":"Apenas máximo","isCorrect":false,"reason":"Mostra a série toda."}]},{"question":"O eixo X é…","options":[{"text":"Horizontal","isCorrect":true,"reason":"X = horizontal."},{"text":"Vertical","isCorrect":false,"reason":"Isso é o Y."},{"text":"Diagonal","isCorrect":false,"reason":"Não existe."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Vendas: jan 100; fev 150; mar 120.","question":"Qual mês teve maior venda?","options":[{"text":"Fevereiro","isCorrect":true,"reason":"150 é o maior."},{"text":"Janeiro","isCorrect":false,"reason":"É o menor."},{"text":"Março","isCorrect":false,"reason":"Está no meio."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"Barras → comparar"},{"label":"Linhas → evolução"},{"label":"Setores → partes do todo"}],"takeaways":["O gráfico certo facilita ler a informação."]}'::jsonb
WHERE slug = 'mat-graficos';

UPDATE public.pedagogical_templates SET
  exemplos = '[{"question":"Ao lançar um dado, qual a probabilidade de sair 6?","resolution":[{"line":"Casos favoráveis: 1"},{"line":"Casos possíveis: 6"},{"line":"P = 1/6"}],"answer":"1/6","why":"Probabilidade = favoráveis ÷ possíveis."}]'::jsonb,
  pratica_guiada = '[{"prompt":"Probabilidade de tirar cara em uma moeda?","hint":"2 faces igualmente possíveis.","options":[{"text":"1/2","isCorrect":true,"reason":"1 favorável em 2."},{"text":"1","isCorrect":false,"reason":"Significa certeza."},{"text":"0","isCorrect":false,"reason":"Significa impossível."}]}]'::jsonb,
  exercicios = '[{"question":"P(par) num dado?","options":[{"text":"3/6 = 1/2","isCorrect":true,"reason":"Pares: 2, 4, 6."},{"text":"1/6","isCorrect":false,"reason":"Só 1 par."},{"text":"2/6","isCorrect":false,"reason":"Faltou um par."}]},{"question":"Evento impossível tem probabilidade…","options":[{"text":"0","isCorrect":true,"reason":"Nunca acontece."},{"text":"1","isCorrect":false,"reason":"Isso é certeza."},{"text":"1/2","isCorrect":false,"reason":"Isso é meio a meio."}]},{"question":"Urna com 3 azuis e 2 vermelhas. P(azul)?","options":[{"text":"3/5","isCorrect":true,"reason":"3 em 5."},{"text":"2/5","isCorrect":false,"reason":"Isso é vermelhas."},{"text":"3/2","isCorrect":false,"reason":"Inverteu."}]}]'::jsonb,
  desafio = '{"contextualScenario":"Você lança 2 moedas.","question":"P(2 caras)?","options":[{"text":"1/4","isCorrect":true,"reason":"Casos: CC, CK, KC, KK."},{"text":"1/2","isCorrect":false,"reason":"Só vale para uma moeda."},{"text":"2/4","isCorrect":false,"reason":"Contou outras combinações."}]}'::jsonb,
  revisao = '{"format":"list","nodes":[{"label":"P = favoráveis ÷ possíveis"},{"label":"0 ≤ P ≤ 1"},{"label":"Soma das probabilidades = 1"}],"takeaways":["Probabilidade mede a chance de algo acontecer."]}'::jsonb
WHERE slug = 'mat-probabilidade';

-- limpa cache pré-construído para forçar remontagem com o novo conteúdo
DELETE FROM public.pedagogical_lessons_cache
WHERE bncc_code IN (
  SELECT bncc_code FROM public.bncc_template_map
  WHERE template_id IN (SELECT id FROM public.pedagogical_templates WHERE disciplina ILIKE 'Matem%')
);
