-- Biblioteca Inclusiva · Geografia do 1º ano completa.
WITH lessons(code,source_key,title,goal) AS (VALUES
('EF01GE01','src/escola-brilha/data/EF01GE01.ts','Comparando os lugares onde vivemos','Descrever características de lugares de vivência por imagens e cenários fictícios.'),
('EF01GE02','src/escola-brilha/data/EF01GE02.ts','Brincadeiras de tempos e lugares diferentes','Comparar jogos e brincadeiras de diferentes épocas e lugares sem hierarquizar culturas.'),
('EF01GE03','src/escola-brilha/data/EF01GE03.ts','Como usamos os espaços públicos','Identificar usos e possibilidades de participação em espaços públicos acessíveis.'),
('EF01GE04','src/escola-brilha/data/EF01GE04.ts','Regras para conviver bem','Discutir acordos de convivência em diferentes espaços com inclusão e segurança.'),
('EF01GE05','src/escola-brilha/data/EF01GE05.ts','Ritmos da natureza','Observar ritmos naturais e relacioná-los a atividades cotidianas diversas.'),
('EF01GE06','src/escola-brilha/data/EF01GE06.ts','Moradias e materiais','Comparar tipos e materiais de moradias sem associá-los a valor, mérito ou condição pessoal.'),
('EF01GE07','src/escola-brilha/data/EF01GE07.ts','Trabalhos e vida em comunidade','Reconhecer diferentes trabalhos e sua contribuição sem estereótipos de gênero ou classe.'),
('EF01GE08','src/escola-brilha/data/EF01GE08.ts','Mapas e trajetos','Criar e ler mapas simples de cenários fictícios usando símbolos, legendas e trajetos.'),
('EF01GE09','src/escola-brilha/data/EF01GE09.ts','Referenciais espaciais','Usar referenciais espaciais por diferentes formas de percepção, orientação e movimento.'),
('EF01GE10','src/escola-brilha/data/EF01GE10.ts','O lugar muda com as épocas','Comparar mudanças e permanências em paisagens por imagens de diferentes tempos.'),
('EF01GE11','src/escola-brilha/data/EF01GE11.ts','Tempo, estações e cuidados','Relacionar condições do tempo a escolhas cotidianas seguras, considerando variações regionais.')
)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_1','1º Ano','Geografia',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia de investigação geográfica — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare um espaço seguro','content',jsonb_build_array('Use mapas, trajetos, casas, quartos, bairros e rotinas fictícios; nunca peça endereço, geolocalização, fotografia da moradia, trajeto real, planta do quarto ou horário da criança.','Escolha imagens de moradias, trabalhos, corpos, famílias, culturas e modos de deslocamento diversos sem classificar um tipo como melhor.')),
 jsonb_build_object('heading','Ensine a observar e representar','content',jsonb_build_array('Modele lugar, paisagem, posição, direção, distância aproximada, trajeto, símbolo e legenda com objetos e imagens.','Compare elemento natural e construído, uso do espaço, mudança e permanência sem culpar indivíduos por problemas coletivos.','Referenciais corporais devem admitir diferentes lateralidades, mobilidades, percepções visuais e formas de orientação.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Dê uma instrução por vez, use etapas curtas, permita pausa planejada e anuncie a retomada.','Aceite fala, apontamento, cartões, objetos, maquete, desenho, áudio, digitação, escrita ou tecnologia assistiva.','Não avalie coordenação motora, visão, leitura ou fala como se fossem compreensão geográfica.')),
 jsonb_build_object('heading','Critério','content','Localiza, compara ou representa quatro de cinco situações usando referência espacial ou evidência da paisagem.')))),
jsonb_build_array(jsonb_build_object('title','1. Observar o lugar','instruction','Identifique elementos, usos, pessoas, condições e pistas em imagem ou maquete fictícia.','activity','Separe o que observa do que imagina e escolha uma pergunta.','support','Vocabulário visual, exploração tátil opcional e exemplo resolvido.'),jsonb_build_object('title','2. Localizar e comparar','instruction','Use posição, direção, trajeto, símbolo, legenda, mudança ou permanência.','activity','Monte mapa, sequência, maquete ou quadro de '||lower(title)||'.','support','Prática guiada antes da independente e pistas graduadas.'),jsonb_build_object('title','3. Explicar ou representar','instruction','Mostre a relação entre elementos, pessoas, natureza e usos do espaço.','activity','Apresente conclusão por fala, cartões, mapa, maquete, desenho ou escrita.','support','Resposta oral, apontada, tátil, desenhada, gravada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Identifica elementos e uma pista observável.'),jsonb_build_object('page',2,'answer','Localiza ou compara usando referência coerente.'),jsonb_build_object('page',3,'answer','Representação ou explicação ligada às evidências.','teacher_note','Registre autonomia, apoio eficaz e próximo passo; não registre localização ou rotina real.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','cards','objects','model','drawing','audio','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'privacy_preserving',true,'fictional_location_only',true,'no_live_geolocation',true,'housing_dignity',true,'anti_stereotype',true,'mobility_vision_inclusive',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/habilidade/'||code FROM lessons
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
