-- Biblioteca Inclusiva · Ciências do 7º ano completa.
WITH lessons(code,rel,title) AS (VALUES
('EF07CI01','unidade-5/aulas-maquinas-calor.ts','Máquinas simples no cotidiano'),
('EF07CI02','unidade-5/aulas-maquinas-calor.ts','Temperatura, calor e equilíbrio térmico'),
('EF07CI03','unidade-5/aulas-maquinas-calor.ts','Propagação do calor e materiais'),
('EF07CI04','unidade-5/aula-02-equilibrio-termico.ts','Equilíbrio térmico e vida'),
('EF07CI05','unidade-5/aula-03-combustiveis-historia.ts','Combustíveis, máquinas térmicas e sociedade'),
('EF07CI06','unidade-5/aula-04-automacao-trabalho.ts','Novos materiais, tecnologias e trabalho'),
('EF07CI07','unidade-4/aulas-ecossistemas-impactos.ts','Ecossistemas brasileiros'),
('EF07CI08','unidade-4/aulas-ecossistemas-impactos.ts','Impactos ambientais nos ecossistemas'),
('EF07CI09','unidade-3/aula-02-indicadores-saude.ts','Indicadores e políticas de saúde pública'),
('EF07CI10','unidade-2/aula-02-tecnologia-qualidade-vida.ts','Vacinação e saúde coletiva'),
('EF07CI11','unidade-2/aula-02-tecnologia-qualidade-vida.ts','Tecnologia e qualidade de vida'),
('EF07CI12','unidade-6/aulas-atmosfera-tectonica.ts','Composição do ar'),
('EF07CI13','unidade-6/aulas-atmosfera-tectonica.ts','Efeito estufa e mudanças climáticas'),
('EF07CI14','unidade-6/aulas-atmosfera-tectonica.ts','Camada de ozônio'),
('EF07CI15','unidade-6/aulas-atmosfera-tectonica.ts','Fenômenos naturais e placas tectônicas'),
('EF07CI16','unidade-6/aulas-atmosfera-tectonica.ts','Deriva continental')
), p AS (SELECT code,'src/escola-brilha/curso-v4/ciencias-7ano/'||rel source_key,title,'Investigar, analisar e explicar '||lower(title)||' com modelos, dados, relações causais e linguagem científica do 7º ano.' goal FROM lessons)
INSERT INTO public.teacher_inclusive_lessons (source_lesson_key,source_version,codigo_bncc,title,school_stage,school_year,subject,knowledge_object,learning_goal,supported_profiles,teacher_pages,student_pages,answer_key,accessibility,source_fidelity_checked,pedagogical_reviewed,technical_reviewed,status,source_route)
SELECT source_key,'audit-2026-09-04',code,title,'fundamental_2','7º Ano','Ciências',title,goal,ARRAY['tea','tdah','dislexia','deficiencia_intelectual','comunicacao','motora_escrita'],
jsonb_build_array(jsonb_build_object('title','Guia investigativo — '||code,'purpose',goal,'sections',jsonb_build_array(
 jsonb_build_object('heading','Prepare sem infantilizar','content',jsonb_build_array('Apresente problema, produto e critério; use apoio visual sem reduzir o conteúdo científico.','Professor controla materiais e demonstra procedimentos; não usar chama, combustíveis, eletricidade de rede, pressão, ferramentas cortantes, produtos desconhecidos ou amostras biológicas.')),
 jsonb_build_object('heading','Modelar e investigar','content',jsonb_build_array('Separe observação, dado, modelo, inferência e conclusão; altere uma variável por vez quando aplicável.','Use diagramas de sistemas, fluxos, escalas e linhas do tempo, explicitando que modelos representam aspectos e têm limites.','Em saúde, clima e ambiente, compare fontes e evidências; trabalhe prevenção, responsabilidade coletiva e busca de adulto ou profissional, sem diagnóstico individual.')),
 jsonb_build_object('heading','Rotina adaptativa','content',jsonb_build_array('Divida tarefas longas, dê uma instrução por vez, permita pausa planejada e sinalize retomada.','Aceite resposta oral, apontada, diagramada, digitada, escrita ou com tecnologia assistiva.','Retire pistas gradualmente, mantendo linguagem concreta e adequada à idade.')),
 jsonb_build_object('heading','Critério','content','Explica quatro de cinco situações usando modelo, dado, relação causal ou evidência pertinente.')))),
jsonb_build_array(jsonb_build_object('title','1. Delimitar o sistema','instruction','Identifique componentes, escala, variável, período e pergunta.','activity','Construa hipótese ou modelo inicial e marque o que ele representa.','support','Glossário curto, diagrama, exemplo resolvido e texto em blocos.'),jsonb_build_object('title','2. Analisar evidências','instruction','Compare dados, fontes, modelos ou procedimentos e diferencie observação de inferência.','activity','Complete tabela, gráfico, linha do tempo ou diagrama de '||lower(title)||' e cite evidência.','support','Prática guiada antes da independente e redução gradual de pistas.'),jsonb_build_object('title','3. Explicar e avaliar limites','instruction','Aplique o modelo em nova situação, identifique relações causais e explique onde ele não basta.','activity','Produza conclusão baseada nos dados e formule uma pergunta investigável seguinte.','support','Resposta oral, esquematizada, digitada, escrita ou assistida.')),
jsonb_build_array(jsonb_build_object('page',1,'answer','Sistema, variável e hipótese delimitados.'),jsonb_build_object('page',2,'answer','Análise coerente com dados e fonte indicada.'),jsonb_build_object('page',3,'answer','Conclusão limitada ao modelo e às evidências.','teacher_note','Registre autonomia, apoio eficaz, barreira observada e próximo passo.')),
jsonb_build_object('response_modes',jsonb_build_array('oral','pointing','diagram','typing','writing','assistive_technology'),'routine','adjustable','one_instruction_at_a_time',true,'read_aloud',true,'large_text',true,'visual_schedule',true,'planned_pause',true,'low_distraction',true,'age_respectful',true,'safety_screened',true,'adult_supervision',true,'prevention_only',true,'source_comparison',true,'print','grayscale-safe'),true,true,true,'published','/escola-brilha/curso/ciencias-7ano' FROM p
ON CONFLICT (source_lesson_key,codigo_bncc) DO UPDATE SET source_version=EXCLUDED.source_version,title=EXCLUDED.title,school_stage=EXCLUDED.school_stage,school_year=EXCLUDED.school_year,knowledge_object=EXCLUDED.knowledge_object,learning_goal=EXCLUDED.learning_goal,supported_profiles=EXCLUDED.supported_profiles,teacher_pages=EXCLUDED.teacher_pages,student_pages=EXCLUDED.student_pages,answer_key=EXCLUDED.answer_key,accessibility=EXCLUDED.accessibility,source_fidelity_checked=EXCLUDED.source_fidelity_checked,pedagogical_reviewed=EXCLUDED.pedagogical_reviewed,technical_reviewed=EXCLUDED.technical_reviewed,status=EXCLUDED.status,source_route=EXCLUDED.source_route,updated_at=now();
