import type { AulaGeoV1 } from "../../types";
import corpo from "@/assets/ciencias-5ano/u3-a1/corpo-humano.jpg";
import coracao from "@/assets/ciencias-5ano/u3-a1/coracao.jpg";
import pulmoes from "@/assets/ciencias-5ano/u3-a1/pulmoes.jpg";
import digestivo from "@/assets/ciencias-5ano/u3-a1/digestivo.jpg";
import alimentacao from "@/assets/ciencias-5ano/u3-a1/alimentacao.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-corpo-humano",
  titulo: "Corpo Humano por Dentro",
  iconeTrilha: "❤️",
  bncc: ["EF05CI06"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pelo modelo anatômico. Encontre os 3 grandes sistemas que trabalham juntos.",
    mapaUrl: corpo,
    imagemDestaqueUrl: coracao,
    aurora: "Seu corpo é uma FÁBRICA em movimento 24h por dia. Coração, pulmões e sistema digestivo formam uma equipe — se um falha, os outros sofrem.",
    falaFinal: "Nada no corpo funciona sozinho. Todo sistema depende dos outros.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Qual órgão bombeia sangue pra todo o corpo, 24h por dia, sem parar?",
    pergunta: "Quem é o motor da circulação?",
    fotoUrl: coracao,
    opcoes: [
      { id: "coracao", titulo: "CORAÇÃO", subtitulo: "músculo bombeador", emoji: "❤️", cor: "from-red-400 to-rose-700" },
      { id: "pulmao", titulo: "PULMÃO", subtitulo: "captura ar", emoji: "🫁", cor: "from-cyan-400 to-sky-700" },
      { id: "estomago", titulo: "ESTÔMAGO", subtitulo: "digere comida", emoji: "🫃", cor: "from-orange-400 to-amber-700" },
    ],
    respostaCerta: "coracao",
    feedbackAcerto: "Certo. Coração é um músculo especial que bombeia sangue sem parar.",
    feedbackErro: "Pulmão respira, estômago digere. Quem bombeia é o CORAÇÃO.",
    falaFinal: "Coração é o único órgão que trabalha 24h sem descanso. Nunca para.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco conceitos de anatomia — sem eles, o corpo é caixa preta.",
    instrucao: "Vocabulário do corpo humano",
    cadernos: [
      { id: "coracao", capa: "CORAÇÃO", emoji: "❤️", cor: "from-red-500 to-rose-700",
        conteudo: "Músculo do tamanho de um punho que bombeia sangue por todo o corpo.",
        exemplo: "Ex.: bate cerca de 100.000 vezes por dia.", fotoUrl: coracao },
      { id: "pulmao", capa: "PULMÃO", emoji: "🫁", cor: "from-cyan-500 to-sky-700",
        conteudo: "Órgão que capta OXIGÊNIO do ar e libera GÁS CARBÔNICO.",
        exemplo: "Ex.: você respira cerca de 20.000 vezes por dia.", fotoUrl: pulmoes },
      { id: "estomago", capa: "SISTEMA DIGESTIVO", emoji: "🫃", cor: "from-orange-500 to-amber-700",
        conteudo: "Do esôfago ao intestino: quebra o alimento em nutrientes minúsculos que o sangue carrega.",
        exemplo: "Ex.: digerir uma refeição leva 4 a 6 horas.", fotoUrl: digestivo },
      { id: "nutriente", capa: "NUTRIENTE", emoji: "🥗", cor: "from-emerald-500 to-green-700",
        conteudo: "Substância presente no alimento que o corpo usa como energia e matéria-prima.",
        exemplo: "Ex.: proteína, carboidrato, vitamina.", fotoUrl: alimentacao },
      { id: "sangue", capa: "SANGUE", emoji: "🩸", cor: "from-red-600 to-rose-800",
        conteudo: "Líquido que transporta oxigênio dos pulmões E nutrientes do intestino pra cada célula.",
        exemplo: "Ex.: um adulto tem cerca de 5 litros de sangue.", fotoUrl: coracao },
    ],
    falaFinal: "Coração, pulmão, digestivo, nutriente, sangue. A química da vida em 5 palavras.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "O modelo anatômico. Toca em cada órgão e veja a função.",
    instrucao: "Toque em cada órgão",
    mapaUrl: corpo,
    pontos: [
      { id: "coracao", x: 45, y: 40, emoji: "❤️", cor: "from-red-500 to-rose-700",
        titulo: "Coração", texto: "Bombeia sangue oxigenado para todo o corpo e recebe sangue usado de volta.",
        fotoUrl: coracao },
      { id: "pulmoes", x: 45, y: 32, emoji: "🫁", cor: "from-cyan-500 to-sky-700",
        titulo: "Pulmões", texto: "Trocam gases: absorvem oxigênio do ar e liberam gás carbônico.",
        fotoUrl: pulmoes },
      { id: "estomago", x: 45, y: 55, emoji: "🫃", cor: "from-orange-500 to-amber-700",
        titulo: "Estômago", texto: "Mistura o alimento com ácidos e enzimas — inicia a digestão profunda.",
        fotoUrl: digestivo },
      { id: "intestino", x: 45, y: 68, emoji: "〰️", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Intestino", texto: "Absorve nutrientes e água. Envia o resto pra ser eliminado.",
        fotoUrl: digestivo },
      { id: "esqueleto", x: 20, y: 50, emoji: "🦴", cor: "from-slate-400 to-slate-700",
        titulo: "Esqueleto", texto: "Estrutura de sustentação — protege órgãos vitais e permite o movimento.",
        fotoUrl: corpo },
    ],
    falaFinal: "Cinco sistemas essenciais. Todos conectados, todos dependentes um do outro.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de anatomia.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Qual órgão trabalha 24h sem parar por toda a sua vida?",
        fotoUrl: coracao,
        cards: [
          { id: "a", emoji: "❤️", titulo: "Coração", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "🧠", titulo: "Cérebro (só em vigília)", cor: "from-slate-500 to-slate-700" },
          { id: "c", emoji: "👁️", titulo: "Olhos", cor: "from-cyan-500 to-sky-700" },
        ], correta: "a",
        feedbackAcerto: "Isso. Coração nunca descansa completamente — mesmo dormindo, bate.",
        feedbackErro: "Cérebro descansa em partes, olhos fecham. Coração NUNCA para." },
      { id: "q2", pergunta: "Onde os nutrientes do alimento entram no sangue?",
        fotoUrl: digestivo,
        cards: [
          { id: "a", emoji: "🫃", titulo: "Estômago (só mistura)", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "〰️", titulo: "Intestino (absorve)", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "👄", titulo: "Boca", cor: "from-slate-500 to-slate-700" },
        ], correta: "b",
        feedbackAcerto: "Correto. Intestino tem parede fininha que deixa nutrientes passarem pro sangue.",
        feedbackErro: "Estômago só quebra. Absorção real é no INTESTINO." },
      { id: "q3", pergunta: "O que os pulmões fazem com o oxigênio?",
        fotoUrl: pulmoes,
        cards: [
          { id: "a", emoji: "🩸", titulo: "Passam para o sangue", cor: "from-cyan-500 to-sky-700" },
          { id: "b", emoji: "🔥", titulo: "Queimam direto", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "💾", titulo: "Guardam pra depois", cor: "from-slate-500 to-slate-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Oxigênio atravessa a parede fina do pulmão e entra na circulação.",
        feedbackErro: "Pulmão não estoca nem queima. Ele TRANSFERE oxigênio pro sangue." },
    ],
    falaFinal: "Você entende o básico da fisiologia — como corpo humano realmente funciona.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "O corpo tem duas grandes zonas: TRONCO SUPERIOR (respiração + circulação) e TRONCO INFERIOR (digestão). Liga as camadas.",
    instrucao: "Toque nos interruptores",
    mapaUrl: corpo,
    camadas: [
      { id: "superior", rotulo: "Tronco Superior", emoji: "🫁", cor: "from-cyan-500 to-sky-700",
        rect: { x: 20, y: 20, w: 60, h: 30 },
        descricao: "Coração e pulmões trabalhando juntos: um respira, o outro distribui o oxigênio.",
        fotoUrl: pulmoes },
      { id: "inferior", rotulo: "Tronco Inferior", emoji: "🫃", cor: "from-orange-500 to-amber-700",
        rect: { x: 20, y: 50, w: 60, h: 40 },
        descricao: "Estômago e intestinos processando o alimento e enviando nutrientes ao sangue.",
        fotoUrl: digestivo },
    ],
    falaFinal: "Duas zonas, uma equipe. Ar em cima, comida embaixo — e sangue circulando entre elas.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte a jornada de um pedaço de pão desde a boca até virar energia.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual o caminho do alimento no corpo?",
    paradas: [
      { id: "boca", emoji: "👄", rotulo: "1. Boca", descricao: "Dentes mastigam, saliva começa a quebrar.", fotoUrl: alimentacao },
      { id: "esofago", emoji: "⬇️", rotulo: "2. Esôfago", descricao: "Tubo que leva o alimento ao estômago.", fotoUrl: digestivo },
      { id: "estomago", emoji: "🫃", rotulo: "3. Estômago", descricao: "Ácidos e enzimas fazem a digestão pesada.", fotoUrl: digestivo },
      { id: "intestino", emoji: "〰️", rotulo: "4. Intestino", descricao: "Nutrientes passam para o sangue.", fotoUrl: digestivo },
      { id: "sangue", emoji: "🩸", rotulo: "5. Sangue", descricao: "Sangue leva nutrientes pra cada célula do corpo.", fotoUrl: coracao },
    ],
    ordemCerta: ["boca", "esofago", "estomago", "intestino", "sangue"],
    feedbackAcerto: "Rota completa. Todo alimento faz essa jornada em 4 a 6 horas.",
    feedbackErro: "Repense: começa na boca, passa pelo tubo (esôfago), estômago, intestino, e vira sangue.",
    falaFinal: "Digestão é uma linha de montagem. Cada órgão faz uma etapa específica.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura. Estuda o diário do médico.",
    tituloLivro: "📓 Diário do Cardiologista",
    subtitulo: "Como funciona o sistema circulatório",
    paragrafos: [
      { id: "p1", texto:
          "O CORAÇÃO é um músculo do tamanho de um punho. Ele bombeia SANGUE oxigenado por todo o corpo através de tubos chamados ARTÉRIAS. Cada batida empurra o sangue pra frente com força.",
        chaves: ["coração", "sangue", "artérias"],
        definicoes: {
          coração: "Músculo bombeador central da circulação.",
          sangue: "Líquido que transporta oxigênio e nutrientes.",
          artérias: "Tubos que levam sangue pra fora do coração.",
        }, fotoUrl: coracao },
      { id: "p2", texto:
          "O sangue leva OXIGÊNIO dos PULMÕES até cada célula. As células usam esse oxigênio pra produzir ENERGIA — e devolvem gás carbônico como resíduo, que volta pros pulmões pra ser exalado.",
        chaves: ["oxigênio", "pulmões", "energia"],
        definicoes: {
          oxigênio: "Gás do ar que as células precisam pra viver.",
          pulmões: "Órgãos que trocam gases com o ambiente.",
          energia: "Combustível que faz o corpo funcionar.",
        }, fotoUrl: pulmoes },
      { id: "p3", texto:
          "Do INTESTINO, os NUTRIENTES entram no sangue e são distribuídos pra cada parte do corpo. Coração, pulmão e digestivo formam uma EQUIPE: sem qualquer um deles, o corpo falha.",
        chaves: ["nutrientes", "equipe"],
        definicoes: {
          nutrientes: "Substâncias do alimento que viram matéria e energia.",
          equipe: "Sistemas que só funcionam trabalhando juntos.",
        }, fotoUrl: alimentacao },
    ],
    falaFinal: "Você acabou de ler como sua própria vida acontece por dentro. Impressionante, né?",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Cada rodada mostra uma função — escolhe qual sistema faz isso.",
    instrucao: "⏱️ Leia e escolha o sistema correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "coracao", emoji: "❤️", rotulo: "Circulatório" },
      { id: "pulmao", emoji: "🫁", rotulo: "Respiratório" },
      { id: "digestivo", emoji: "🫃", rotulo: "Digestivo" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Bombear sangue", emoji: "❤️", cor: "from-red-500 to-rose-700" },
        municipioB: { nome: "Distribuir oxigênio", emoji: "🩸", cor: "from-red-500 to-rose-700" },
        contexto: "Levar o sangue oxigenado a cada parte do corpo, sem parar.",
        pecaCertaId: "coracao", fotoUrl: coracao,
        feedbackAcerto: "Sim. Bombear e distribuir sangue = CIRCULATÓRIO.",
        feedbackErro: "Bombeamento e distribuição de sangue é responsabilidade do CIRCULATÓRIO." },
      { id: "r2", municipioA: { nome: "Trocar gases", emoji: "🫁", cor: "from-cyan-500 to-sky-700" },
        municipioB: { nome: "Captar oxigênio do ar", emoji: "💨", cor: "from-cyan-500 to-sky-700" },
        contexto: "Absorver oxigênio da atmosfera e devolver gás carbônico.",
        pecaCertaId: "pulmao", fotoUrl: pulmoes,
        feedbackAcerto: "Perfeito. Troca de gases = RESPIRATÓRIO.",
        feedbackErro: "Trocar gases com o ar é papel do sistema RESPIRATÓRIO." },
      { id: "r3", municipioA: { nome: "Digerir alimento", emoji: "🫃", cor: "from-orange-500 to-amber-700" },
        municipioB: { nome: "Absorver nutrientes", emoji: "🥗", cor: "from-orange-500 to-amber-700" },
        contexto: "Quebrar o alimento em pedacinhos e absorver o que serve como nutriente.",
        pecaCertaId: "digestivo", fotoUrl: digestivo,
        feedbackAcerto: "Isso. Quebrar e absorver comida = DIGESTIVO.",
        feedbackErro: "Digestão e absorção de nutrientes = sistema DIGESTIVO." },
      { id: "r4", municipioA: { nome: "Batidas por minuto", emoji: "💓", cor: "from-red-500 to-rose-700" },
        municipioB: { nome: "Pulsação", emoji: "📉", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "O órgão que pulsa cerca de 60 a 80 vezes por minuto em repouso.",
        pecaCertaId: "coracao", fotoUrl: coracao,
        feedbackAcerto: "Sim. Pulsação = CORAÇÃO = sistema CIRCULATÓRIO.",
        feedbackErro: "Pulsação é do CORAÇÃO — sistema circulatório." },
      { id: "r5", municipioA: { nome: "Estômago + intestino", emoji: "〰️", cor: "from-orange-500 to-amber-700" },
        municipioB: { nome: "Processar comida", emoji: "🍽️", cor: "from-emerald-500 to-green-700" },
        contexto: "Sistema formado por esôfago, estômago e intestinos que processa a comida ingerida.",
        pecaCertaId: "digestivo", fotoUrl: digestivo,
        feedbackAcerto: "Perfeito. Estômago + intestinos = sistema DIGESTIVO.",
        feedbackErro: "Órgãos que processam alimento formam o sistema DIGESTIVO." },
    ],
    falaFinal: "Você mapeia o corpo inteiro. Cada função tem um responsável.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "O corpo em dois grandes serviços: TRANSPORTE (levar oxigênio e nutrientes) e PROCESSAMENTO (transformar ar e comida em combustível).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: corpo,
    fatias: [
      { id: "transporte", rotulo: "Transporte", emoji: "❤️", percentual: 45, cor: "#e11d48",
        descricao: "Coração + sangue: rede logística que entrega oxigênio e nutrientes em cada célula.",
        exemplos: ["Coração bombeia", "Sangue circula", "Chegada nas células"], fotoUrl: coracao },
      { id: "processamento", rotulo: "Processamento", emoji: "🫃", percentual: 55, cor: "#f59e0b",
        descricao: "Pulmões + digestivo: transformam ar e comida em oxigênio e nutrientes prontos pra viajar.",
        exemplos: ["Pulmão capta O₂", "Estômago quebra comida", "Intestino absorve"], fotoUrl: digestivo },
    ],
    falaFinal: "Processar cria os insumos; transportar entrega. Sem os dois, o corpo para em minutos.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas de anatomia — carteira de Biomédico Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: corpo,
    perguntas: [
      { id: "q1", pergunta: "O que o coração faz?",
        fotoUrl: coracao,
        opcoes: [
          { id: "a", texto: "Bombeia sangue pra todo o corpo", correta: true },
          { id: "b", texto: "Digere alimentos" },
        ],
        feedbackAcerto: "Sim. Coração bombeia — é a bomba central da circulação.",
        feedbackErro: "Digestão é do sistema digestivo. Coração BOMBEIA." },
      { id: "q2", pergunta: "Onde entra o oxigênio no corpo?",
        fotoUrl: pulmoes,
        opcoes: [
          { id: "a", texto: "Pelos pulmões", correta: true },
          { id: "b", texto: "Pelo estômago" },
        ],
        feedbackAcerto: "Correto. Oxigênio vem do ar, pelos pulmões, e passa ao sangue.",
        feedbackErro: "Estômago recebe comida, não ar. Oxigênio entra pelos PULMÕES." },
      { id: "q3", pergunta: "O que os sistemas do corpo têm em comum?",
        fotoUrl: alimentacao,
        opcoes: [
          { id: "a", texto: "Trabalham em equipe — dependem uns dos outros", correta: true },
          { id: "b", texto: "Trabalham cada um por conta própria" },
        ],
        feedbackAcerto: "Sim. Nenhum sistema funciona sozinho. Um depende do outro.",
        feedbackErro: "Isolado nenhum sistema funciona. Corpo é sempre em EQUIPE." },
    ],
    selo: {
      nome: "Biomédico Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 3 concluído",
      emoji: "🩺",
      cor: "from-red-400 via-rose-500 to-pink-700",
    },
    falaFinal: "Biomédico júnior aprovado. Próximo laboratório: a matéria e suas transformações.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Biomédico Júnior" },
};
