import type { AulaGeoV1 } from "../../types";
import { url as corpo } from "@/assets/ciencias-5ano/u3-a1/corpo-humano.jpg.asset.json";
import { url as coracao } from "@/assets/ciencias-5ano/u3-a1/coracao.jpg.asset.json";
import { url as pulmoes } from "@/assets/ciencias-5ano/u3-a1/pulmoes.jpg.asset.json";
import { url as digestivo } from "@/assets/ciencias-5ano/u3-a1/digestivo.jpg.asset.json";
import { url as alimentacao } from "@/assets/ciencias-5ano/u3-a1/alimentacao.jpg.asset.json";

export const aula02: AulaGeoV1 = {
  slug: "aula-02-sistema-circulatorio",
  titulo: "O Sistema Circulatório em Ação",
  iconeTrilha: "🩸",
  bncc: ["EF05CI07"],
  duracaoMin: 30,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Passe a lupa pelo modelo. Siga o caminho do sangue saindo e voltando ao coração.",
    mapaUrl: corpo,
    imagemDestaqueUrl: coracao,
    aurora: "O sangue é uma rede de entrega que nunca para. Ele leva nutrientes e oxigênio até a última célula do seu dedão do pé — e ainda recolhe o lixo que essas células produzem.",
    falaFinal: "Sem circulação, nutrientes nunca chegariam e resíduos nunca sairiam.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Depois que o intestino absorve os nutrientes do alimento, como eles chegam até as células dos músculos e do cérebro?",
    pergunta: "Como os nutrientes viajam pelo corpo?",
    fotoUrl: coracao,
    opcoes: [
      { id: "sangue", titulo: "PELO SANGUE", subtitulo: "bombeado pelo coração", emoji: "🩸", cor: "from-red-400 to-rose-700" },
      { id: "ar", titulo: "PELO AR DOS PULMÕES", subtitulo: "junto com oxigênio", emoji: "🫁", cor: "from-cyan-400 to-sky-700" },
          { id: "c", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
    ],
    respostaCerta: "sangue",
    feedbackAcerto: "Certo. O SANGUE é o transportador — leva nutrientes do intestino e oxigênio dos pulmões pra cada célula.",
    feedbackErro: "O ar só carrega oxigênio até o pulmão. Quem distribui nutrientes pelo corpo é o SANGUE.",
    falaFinal: "O sangue é a estrada única que liga todos os órgãos do corpo.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "Cinco palavras do sistema circulatório.",
    instrucao: "Vocabulário da circulação",
    cadernos: [
      { id: "arterias", capa: "ARTÉRIAS", emoji: "➡️", cor: "from-red-500 to-rose-700",
        conteudo: "Vasos que levam sangue rico em oxigênio DO coração para o corpo.",
        exemplo: "Ex.: a aorta é a maior artéria do corpo.", fotoUrl: coracao },
      { id: "veias", capa: "VEIAS", emoji: "⬅️", cor: "from-blue-500 to-indigo-700",
        conteudo: "Vasos que trazem o sangue com gás carbônico e resíduos DE VOLTA para o coração.",
        exemplo: "Ex.: veias das pernas levam sangue de volta contra a gravidade.", fotoUrl: coracao },
      { id: "capilares", capa: "CAPILARES", emoji: "🕸️", cor: "from-fuchsia-500 to-purple-700",
        conteudo: "Vasos finíssimos onde acontece a troca real: nutrientes e oxigênio saem do sangue e entram na célula.",
        exemplo: "Ex.: um capilar é mais fino que um fio de cabelo.", fotoUrl: alimentacao },
      { id: "nutrientes", capa: "NUTRIENTES", emoji: "🥗", cor: "from-emerald-500 to-green-700",
        conteudo: "Substâncias do alimento absorvidas pelo intestino e levadas pelo sangue até as células.",
        exemplo: "Ex.: glicose (energia), proteínas, vitaminas.", fotoUrl: alimentacao },
      { id: "residuos", capa: "RESÍDUOS", emoji: "🚮", cor: "from-slate-500 to-slate-700",
        conteudo: "Substâncias que a célula não usa mais (gás carbônico, ureia) e que o sangue recolhe para eliminar.",
        exemplo: "Ex.: gás carbônico sai pelos pulmões; ureia é filtrada pelos rins.", fotoUrl: pulmoes },
    ],
    falaFinal: "Artérias, veias, capilares, nutrientes, resíduos. A logística completa do corpo.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "O trajeto do sangue no corpo. Toca em cada ponto.",
    instrucao: "Toque em cada ponto",
    mapaUrl: corpo,
    pontos: [
      { id: "coracao", x: 45, y: 40, emoji: "❤️", cor: "from-red-500 to-rose-700",
        titulo: "Coração", texto: "Bombeia o sangue pra fora pelas artérias e recebe de volta pelas veias.",
        fotoUrl: coracao },
      { id: "arterias", x: 25, y: 55, emoji: "➡️", cor: "from-red-500 to-rose-700",
        titulo: "Artérias", texto: "Levam sangue rico em oxigênio e nutrientes até todo o corpo.",
        fotoUrl: coracao },
      { id: "capilares", x: 70, y: 65, emoji: "🕸️", cor: "from-fuchsia-500 to-purple-700",
        titulo: "Capilares", texto: "Vasos finíssimos onde nutrientes e oxigênio saem do sangue e entram na célula.",
        fotoUrl: alimentacao },
      { id: "veias", x: 30, y: 75, emoji: "⬅️", cor: "from-blue-500 to-indigo-700",
        titulo: "Veias", texto: "Recolhem o sangue com resíduos e gás carbônico de volta ao coração.",
        fotoUrl: pulmoes },
    ],
    falaFinal: "Um circuito fechado: sai do coração, entrega, recolhe, volta.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de circulação.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "Qual vaso leva sangue DO coração para o corpo?",
        fotoUrl: coracao,
        cards: [
          { id: "a", emoji: "➡️", titulo: "Artéria", cor: "from-red-500 to-rose-700" },
          { id: "b", emoji: "⬅️", titulo: "Veia", cor: "from-blue-500 to-indigo-700" },
          { id: "c", emoji: "🕸️", titulo: "Capilar", cor: "from-fuchsia-500 to-purple-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Artéria leva sangue PARA FORA do coração.",
        feedbackErro: "Veia traz de volta. Quem leva PRA FORA é a ARTÉRIA." },
      { id: "q2", pergunta: "Onde acontece a troca real de nutrientes com a célula?",
        fotoUrl: alimentacao,
        cards: [
          { id: "a", emoji: "🕸️", titulo: "Capilares (vasos finíssimos)", cor: "from-fuchsia-500 to-purple-700" },
          { id: "b", emoji: "❤️", titulo: "Dentro do coração", cor: "from-red-500 to-rose-700" },
          { id: "c", emoji: "🫁", titulo: "Nos pulmões só", cor: "from-cyan-500 to-sky-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Correto. Nos CAPILARES, tão finos que só passa uma célula de sangue por vez, ocorre a troca.",
        feedbackErro: "A troca acontece nos vasos mais finos: os CAPILARES." },
      { id: "q3", pergunta: "O que as veias trazem de volta pro coração?",
        fotoUrl: pulmoes,
        cards: [
          { id: "a", emoji: "🚮", titulo: "Gás carbônico e resíduos", cor: "from-slate-500 to-slate-700" },
          { id: "b", emoji: "🥗", titulo: "Nutrientes recém-absorvidos", cor: "from-emerald-500 to-green-700" },
          { id: "c", emoji: "💨", titulo: "Ar puro", cor: "from-cyan-500 to-sky-700" },
          { id: "d", emoji: "🔎", titulo: "Preciso comparar outras evidências", cor: "from-blue-500 to-indigo-700" },
        ], correta: "a",
        feedbackAcerto: "Sim. Veias recolhem RESÍDUOS e gás carbônico das células.",
        feedbackErro: "Nutrientes chegam pelas artérias. Veias trazem RESÍDUOS de volta." },
    ],
    falaFinal: "Você entende o ciclo completo de entrega e coleta do sangue.",
  },

  cena06_personagensLugar: {
    tipo: "mapaCamadas",
    aurora: "Duas zonas: ENTREGA (artérias levando nutrientes) e COLETA (veias recolhendo resíduos).",
    instrucao: "Toque nos interruptores",
    mapaUrl: corpo,
    camadas: [
      { id: "entrega", rotulo: "Zona de Entrega", emoji: "➡️", cor: "from-red-500 to-rose-700",
        rect: { x: 10, y: 20, w: 40, h: 60 },
        descricao: "Artérias e capilares entregam oxigênio e nutrientes a cada célula do corpo.",
        fotoUrl: coracao },
      { id: "coleta", rotulo: "Zona de Coleta", emoji: "⬅️", cor: "from-blue-500 to-indigo-700",
        rect: { x: 50, y: 20, w: 40, h: 60 },
        descricao: "Veias recolhem gás carbônico e resíduos das células e levam de volta ao coração.",
        fotoUrl: pulmoes },
    ],
    falaFinal: "Entregar e coletar — as duas metades do trabalho da circulação.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Monte o caminho completo de uma gota de sangue.",
    instrucao: "Toque nas paradas na ORDEM correta",
    pergunta: "Qual o circuito do sangue?",
    paradas: [
      { id: "coracao1", emoji: "❤️", rotulo: "1. Sai do coração", descricao: "Sangue rico em oxigênio é bombeado pelas artérias.", fotoUrl: coracao },
      { id: "arteria", emoji: "➡️", rotulo: "2. Pelas artérias", descricao: "Vai se ramificando em vasos cada vez menores.", fotoUrl: coracao },
      { id: "capilar", emoji: "🕸️", rotulo: "3. Nos capilares", descricao: "Entrega oxigênio e nutrientes, recolhe resíduos.", fotoUrl: alimentacao },
      { id: "veia", emoji: "⬅️", rotulo: "4. Pelas veias", descricao: "Sangue com resíduos volta em direção ao coração.", fotoUrl: pulmoes },
      { id: "coracao2", emoji: "❤️", rotulo: "5. Volta ao coração", descricao: "O ciclo recomeça, sangue é reoxigenado nos pulmões.", fotoUrl: coracao },
    ],
    ordemCerta: ["coracao1", "arteria", "capilar", "veia", "coracao2"],
    feedbackAcerto: "Circuito completo. O sangue faz essa volta cerca de 1.000 vezes por dia.",
    feedbackErro: "Repense: sai do coração pelas artérias, troca nos capilares, retorna pelas veias.",
    falaFinal: "É um circuito fechado — sem começo nem fim, funcionando sem parar.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua leitura. Estuda o diário do cardiologista.",
    tituloLivro: "📓 Diário do Cardiologista",
    subtitulo: "Distribuição e eliminação pelo sangue",
    paragrafos: [
      { id: "p1", texto:
          "O coração bombeia sangue pelas ARTÉRIAS, que se ramificam em vasos cada vez menores até chegar aos CAPILARES — tão finos que as células trocam substâncias direto com o sangue.",
        chaves: ["artérias", "capilares"],
        definicoes: {
          artérias: "Vasos que levam sangue do coração para o corpo.",
          capilares: "Vasos finíssimos onde ocorre a troca com as células.",
        }, fotoUrl: coracao },
      { id: "p2", texto:
          "Nos capilares, os NUTRIENTES absorvidos no intestino e o OXIGÊNIO dos pulmões saem do sangue e entram nas células. Em troca, o sangue recolhe GÁS CARBÔNICO e outros RESÍDUOS que a célula não usa mais.",
        chaves: ["nutrientes", "resíduos"],
        definicoes: {
          nutrientes: "Substâncias do alimento usadas pela célula.",
          resíduos: "Substâncias que a célula descarta.",
        }, fotoUrl: alimentacao },
      { id: "p3", texto:
          "Esse sangue com resíduos volta pelas VEIAS até o coração, que o envia aos pulmões para trocar gás carbônico por oxigênio novo. É um circuito sem fim: entrega, coleta, renovação.",
        chaves: ["veias"],
        definicoes: {
          veias: "Vasos que trazem sangue de volta ao coração.",
        }, fotoUrl: pulmoes },
    ],
    falaFinal: "Você entende como o corpo distribui e elimina substâncias, o tempo todo.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Simulador. Identifique se a função é de ARTÉRIA, CAPILAR ou VEIA.",
    instrucao: "⏱️ Leia e escolha o vaso correto",
    duracaoSegundos: 20,
    pecas: [
      { id: "arteria", emoji: "➡️", rotulo: "Artéria" },
      { id: "capilar", emoji: "🕸️", rotulo: "Capilar" },
      { id: "veia", emoji: "⬅️", rotulo: "Veia" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Leva sangue do coração pro corpo", emoji: "➡️", cor: "from-red-500 to-rose-700" },
        municipioB: { nome: "Rico em oxigênio", emoji: "🫁", cor: "from-red-500 to-rose-700" },
        contexto: "Sangue sai do coração cheio de oxigênio, rumo aos órgãos.",
        pecaCertaId: "arteria", fotoUrl: coracao,
        feedbackAcerto: "Sim. Sair do coração é função da ARTÉRIA.",
        feedbackErro: "Levar sangue PARA FORA do coração é papel da ARTÉRIA." },
      { id: "r2", municipioA: { nome: "Vaso finíssimo", emoji: "🕸️", cor: "from-fuchsia-500 to-purple-700" },
        municipioB: { nome: "Troca com a célula", emoji: "🔄", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "Aqui nutrientes e oxigênio saem do sangue e entram na célula.",
        pecaCertaId: "capilar", fotoUrl: alimentacao,
        feedbackAcerto: "Perfeito. Troca real com a célula = CAPILAR.",
        feedbackErro: "A troca acontece nos vasos mais finos, os CAPILARES." },
      { id: "r3", municipioA: { nome: "Traz sangue de volta", emoji: "⬅️", cor: "from-blue-500 to-indigo-700" },
        municipioB: { nome: "Cheio de resíduos", emoji: "🚮", cor: "from-blue-500 to-indigo-700" },
        contexto: "Sangue com gás carbônico retorna em direção ao coração.",
        pecaCertaId: "veia", fotoUrl: pulmoes,
        feedbackAcerto: "Isso. Retornar ao coração com resíduos é função da VEIA.",
        feedbackErro: "Trazer sangue DE VOLTA é papel da VEIA." },
      { id: "r4", municipioA: { nome: "Aorta", emoji: "❤️", cor: "from-red-500 to-rose-700" },
        municipioB: { nome: "Maior vaso que sai do coração", emoji: "📏", cor: "from-red-500 to-rose-700" },
        contexto: "É o maior vaso sanguíneo do corpo humano, que sai direto do coração.",
        pecaCertaId: "arteria", fotoUrl: coracao,
        feedbackAcerto: "Sim. A aorta é a maior ARTÉRIA do corpo.",
        feedbackErro: "A aorta é uma ARTÉRIA — leva sangue pra fora do coração." },
      { id: "r5", municipioA: { nome: "Célula recebe oxigênio", emoji: "🫁", cor: "from-fuchsia-500 to-purple-700" },
        municipioB: { nome: "Entrega direta", emoji: "📦", cor: "from-fuchsia-500 to-purple-700" },
        contexto: "O ponto exato em que a célula recebe o oxigênio do sangue.",
        pecaCertaId: "capilar", fotoUrl: alimentacao,
        feedbackAcerto: "Correto. Entrega direta à célula = CAPILAR.",
        feedbackErro: "A entrega final acontece nos CAPILARES." },
    ],
    falaFinal: "Você já distingue cada vaso e sua função no corpo.",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "O trabalho da circulação em duas partes: DISTRIBUIÇÃO (levar) e ELIMINAÇÃO (recolher).",
    instrucao: "🍕 Toque nas fatias",
    fotoUrl: corpo,
    fatias: [
      { id: "distribuicao", rotulo: "Distribuição", emoji: "➡️", percentual: 50, cor: "#e11d48",
        descricao: "Artérias e capilares levam oxigênio e nutrientes a cada célula do corpo.",
        exemplos: ["Artérias", "Capilares", "Nutrientes", "Oxigênio"], fotoUrl: coracao },
      { id: "eliminacao", rotulo: "Eliminação", emoji: "⬅️", percentual: 50, cor: "#2563eb",
        descricao: "Veias recolhem gás carbônico e resíduos das células e levam de volta ao coração e pulmões.",
        exemplos: ["Veias", "Gás carbônico", "Resíduos"], fotoUrl: pulmoes },
    ],
    falaFinal: "Distribuir e eliminar são as duas faces da mesma moeda: a circulação.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas — carteira de Cardiologista Júnior te espera.",
    instrucao: "Responda 3 perguntas para receber o selo",
    fotoUrl: corpo,
    perguntas: [
      { id: "q1", pergunta: "Qual vaso leva sangue do coração para o corpo?",
        fotoUrl: coracao,
        opcoes: [
          { id: "a", texto: "Artéria", correta: true },
          { id: "b", texto: "Veia" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Sim. ARTÉRIA leva sangue pra fora do coração.",
        feedbackErro: "Veia traz de volta. ARTÉRIA leva pra fora." },
      { id: "q2", pergunta: "Onde ocorre a troca de nutrientes com as células?",
        fotoUrl: alimentacao,
        opcoes: [
          { id: "a", texto: "Nos capilares", correta: true },
          { id: "b", texto: "Dentro do coração" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Correto. É nos CAPILARES, vasos finíssimos.",
        feedbackErro: "A troca é nos CAPILARES, não dentro do coração." },
      { id: "q3", pergunta: "O que as veias recolhem das células?",
        fotoUrl: pulmoes,
        opcoes: [
          { id: "a", texto: "Gás carbônico e resíduos", correta: true },
          { id: "b", texto: "Nutrientes prontos para usar" },
          { id: "c", texto: "Preciso comparar outras evidências" },
          { id: "d", texto: "Preciso comparar outras evidências" },
        ],
        feedbackAcerto: "Sim. Veias recolhem RESÍDUOS para eliminação.",
        feedbackErro: "Nutrientes vão pelas artérias. Veias recolhem RESÍDUOS." },
    ],
    selo: {
      nome: "Cardiologista Júnior",
      subtitulo: "Missão Planeta Vivo · Laboratório 3 concluído",
      emoji: "🩺",
      cor: "from-red-400 via-rose-500 to-pink-700",
    },
    falaFinal: "Cardiologista júnior aprovado. Próxima parada: nutrição e cardápio equilibrado.",
  },

  recompensa: { xp: 150, moedas: 30, medalha: "Cardiologista Júnior" },
};
