import type { AulaGeoV1 } from "../../types";
import relevo from "@/assets/geografia-6ano/relevo-brasil.jpg";

export const aula01: AulaGeoV1 = {
  slug: "aula-01-relevo-brasil",
  titulo: "Relevo do Brasil",
  iconeTrilha: "⛰️",
  bncc: ["EF06GE03", "EF06GE11"],
  duracaoMin: 25,

  cena01_motivacao: {
    tipo: "mesaCartografo",
    instrucao: "Olhe: o Brasil não é plano. Tem 4 tipos de relevo.",
    mapaUrl: relevo,
    imagemDestaqueUrl: relevo,
    aurora:
      "Explorador, quando você viaja de carro percebe: sobe, desce, planície, morro. Isso é RELEVO — o formato da superfície. O Brasil tem MONTANHAS, PLANALTOS, PLANÍCIES e DEPRESSÕES, cada um com sua história.",
    falaFinal: "Sem montanha alta, com planalto antigo, muitas planícies. Brasil de terra velha.",
  },

  cena02_previsao: {
    tipo: "votoExplorador",
    aurora: "Por que o Brasil não tem montanhas gigantes como o Himalaia ou os Andes?",
    pergunta: "O que explica isso?",
    opcoes: [
      { id: "borda", titulo: "Está no MEIO da placa", subtitulo: "sem colisão, sem crescer", emoji: "🧩", cor: "from-emerald-400 to-teal-600" },
      { id: "clima", titulo: "Por causa do CLIMA quente", subtitulo: "calor derrete montanhas", emoji: "🌡️", cor: "from-amber-400 to-orange-600" },
    ],
    respostaCerta: "borda",
    feedbackAcerto:
      "Exato! Brasil fica no MEIO da placa Sul-Americana, longe de colisões. Nossas montanhas são ANTIGAS, já foram gastas pela erosão.",
    feedbackErro: "Clima não faz montanha sumir. Nossas montanhas são ANTIGAS e desgastadas.",
    falaFinal: "Placa parada + tempo = montanhas gastas. Isso é o Brasil.",
  },

  cena03_vocabulario: {
    tipo: "cadernosCampo",
    aurora: "4 formas do relevo brasileiro.",
    instrucao: "Toque em cada caderno",
    cadernos: [
      { id: "montanha", capa: "1. Montanha", emoji: "🏔️", cor: "from-slate-500 to-gray-700",
        conteudo: "MONTANHA é elevação superior a 300 m com pico definido. No Brasil, as mais altas ficam no Norte (Pico da Neblina, 2.995 m).",
        exemplo: "Ex.: Serra do Mar (SP-RJ), Serra da Mantiqueira." },
      { id: "planalto", capa: "2. Planalto", emoji: "🗻", cor: "from-amber-500 to-orange-700",
        conteudo: "PLANALTO é área ALTA e PLANA no topo. Ocupa a maior parte do Brasil. Bordas em degrau — as ‘chapadas’.",
        exemplo: "Ex.: Chapada Diamantina (BA), Planalto Central (DF)." },
      { id: "planicie", capa: "3. Planície", emoji: "🌾", cor: "from-emerald-500 to-green-700",
        conteudo: "PLANÍCIE é área BAIXA e PLANA, formada por acúmulo de sedimentos. Comum perto de rios e do mar.",
        exemplo: "Ex.: Planície do Pantanal, Planície Amazônica." },
      { id: "depressao", capa: "4. Depressão", emoji: "🕳️", cor: "from-purple-500 to-fuchsia-700",
        conteudo: "DEPRESSÃO é área ainda MAIS BAIXA que a região ao redor. Formada por desgaste da crosta ao longo de milhões de anos.",
        exemplo: "Ex.: Depressão Sertaneja (NE), Depressão do Araguaia." },
    ],
    falaFinal: "Montanha, planalto, planície, depressão. 4 formas, 1 país.",
  },

  cena04_leituraGuiada: {
    tipo: "narrarMapa",
    aurora: "Aponte cada relevo importante do Brasil.",
    instrucao: "Toque em cada balão",
    mapaUrl: relevo,
    pontos: [
      { id: "amazonia", x: 25, y: 30, emoji: "🌾", cor: "from-emerald-500 to-green-700",
        titulo: "PLANÍCIE AMAZÔNICA",
        texto: "Terra baixa e plana, cortada pelo rio Amazonas. Alaga na cheia. Cobre 20% do país." },
      { id: "central", x: 55, y: 55, emoji: "🗻", cor: "from-amber-500 to-orange-700",
        titulo: "PLANALTO CENTRAL",
        texto: "Área alta e plana onde fica Brasília. Cerrado por cima. Chapadas nas bordas." },
      { id: "serramar", x: 70, y: 70, emoji: "🏔️", cor: "from-slate-500 to-gray-700",
        titulo: "SERRA DO MAR",
        texto: "Cadeia de montanhas no litoral SE-S. Barreira que separa mar de sertão. Faz nevoeiro em SP." },
      { id: "pantanal", x: 35, y: 65, emoji: "💧", cor: "from-sky-500 to-blue-700",
        titulo: "PLANÍCIE DO PANTANAL",
        texto: "Maior planície alagável do mundo. Enchentes trazem vida. Cheia de bichos." },
    ],
    falaFinal: "Amazônia baixa, Centro alto, Serras no leste, Pantanal alagado. Brasil variado.",
  },

  cena05_compreensao: {
    tipo: "quizRadar",
    aurora: "3 perguntas de geógrafo.",
    instrucao: "Toque no card certo",
    perguntas: [
      { id: "q1", pergunta: "O relevo que MAIS ocupa o Brasil é:",
        cards: [
          { id: "p", emoji: "🗻", titulo: "Planaltos", cor: "from-amber-500 to-orange-700" },
          { id: "m", emoji: "🏔️", titulo: "Montanhas", cor: "from-slate-500 to-gray-700" },
          { id: "d", emoji: "🕳️", titulo: "Depressões", cor: "from-purple-500 to-fuchsia-700" },
        ], correta: "p",
        feedbackAcerto: "Isso! PLANALTOS ocupam quase 60% do território.", feedbackErro: "Não temos montanhas altas. Planaltos dominam." },
      { id: "q2", pergunta: "Pico mais alto do Brasil:",
        cards: [
          { id: "n", emoji: "🌫️", titulo: "Pico da Neblina (2.995 m)", cor: "from-emerald-500 to-teal-700" },
          { id: "e", emoji: "🏔️", titulo: "Everest", cor: "from-slate-500 to-gray-700" },
          { id: "p", emoji: "⛰️", titulo: "Pão de Açúcar", cor: "from-amber-500 to-orange-700" },
        ], correta: "n",
        feedbackAcerto: "Isso! Pico da Neblina, no Amazonas (fronteira com Venezuela).", feedbackErro: "Everest é no Himalaia. Pão de Açúcar é pequeno. Pico da Neblina = 2.995 m." },
      { id: "q3", pergunta: "Planície do PANTANAL fica no:",
        cards: [
          { id: "mt", emoji: "🌾", titulo: "Centro-Oeste", cor: "from-emerald-500 to-teal-700" },
          { id: "ne", emoji: "🌵", titulo: "Nordeste", cor: "from-amber-500 to-orange-700" },
          { id: "sul", emoji: "❄️", titulo: "Sul", cor: "from-sky-500 to-indigo-700" },
        ], correta: "mt",
        feedbackAcerto: "Isso! Pantanal está no MT e MS (Centro-Oeste).", feedbackErro: "Pantanal fica no CENTRO-OESTE (MT/MS)." },
    ],
    falaFinal: "3 acertos. Bora ver o mapa.",
  },

  cena06_personagensLugar: {
    tipo: "mapaBrasilInterativo",
    aurora:
      "A SERRA DO MAR atravessa 3 estados criando uma parede natural entre litoral e interior. Marque quais.",
    instrucao: "Acenda os estados da Serra do Mar",
    missao: {
      tipo: "selecionar",
      siglas: ["SP", "RJ", "PR"],
      pergunta: "Por onde passa a Serra do Mar?",
    },
    falaFinal:
      "SP, RJ, PR. É por isso que subir a serra pra descer pro litoral é sempre uma viagem sinuosa e cheia de neblina.",
  },

  cena07_sequencia: {
    tipo: "linhaEstrada",
    aurora: "Organize a formação de um planalto ao longo do tempo geológico.",
    instrucao: "Toque na ordem",
    pergunta: "Como o Brasil ganhou seus planaltos?",
    paradas: [
      { id: "rochas", emoji: "🪨", rotulo: "1. Rochas antigas se formam",
        descricao: "Há bilhões de anos, magma esfria e vira rocha dura no fundo." },
      { id: "sobem", emoji: "⬆️", rotulo: "2. Crosta sobe lentamente",
        descricao: "Movimento tectônico ergue essas rochas devagar." },
      { id: "montanhas", emoji: "🏔️", rotulo: "3. Montanhas altas surgem",
        descricao: "Há milhões de anos, tivemos serras tão altas quanto os Andes." },
      { id: "erosao", emoji: "💨", rotulo: "4. Vento e chuva erodem",
        descricao: "Chuva, vento, calor gastam as montanhas ao longo de milhões de anos." },
      { id: "planalto", emoji: "🗻", rotulo: "5. Sobram planaltos gastos",
        descricao: "Hoje temos o topo desgastado das antigas montanhas — os planaltos." },
    ],
    ordemCerta: ["rochas", "sobem", "montanhas", "erosao", "planalto"],
    feedbackAcerto: "Perfeito! Bilhões de anos numa história só.",
    feedbackErro: "Começa com rochas antigas, sobe, forma montanhas, erode, vira planalto.",
    falaFinal: "Brasil já foi Andes. Hoje é planalto gasto. Tempo é engenheiro.",
  },

  cena08_voceLe: {
    tipo: "voceLeSozinho",
    aurora: "Sua vez. Leia e marque as chaves.",
    tituloLivro: "📘 Manual do Explorador Planetário",
    subtitulo: "Capítulo 4 — Relevo brasileiro",
    paragrafos: [
      { id: "p1", texto: "O relevo brasileiro é formado principalmente por PLANALTOS antigos e desgastados.",
        chaves: ["planaltos", "antigos"] },
      { id: "p2", texto: "As PLANÍCIES do Brasil ficam na Amazônia, no Pantanal e nos litorais.",
        chaves: ["planícies", "amazônia", "pantanal"] },
      { id: "p3", texto: "O Brasil NÃO TEM montanhas jovens e altas porque está no MEIO da placa Sul-Americana.",
        chaves: ["montanhas", "meio", "placa"] },
      { id: "p4", texto: "A SERRA DO MAR atravessa SP, RJ e PR criando uma barreira entre litoral e interior.",
        chaves: ["serra", "sp", "rj", "pr"] },
    ],
    falaFinal: "Leu tudo? Minijogo.",
  },

  cena09_minijogo: {
    tipo: "construtorMarcos",
    aurora: "Minijogo GEÓGRAFO EXPRESS! Que RELEVO é esse?",
    instrucao: "⏱️ Identifique o relevo",
    duracaoSegundos: 12,
    pecas: [
      { id: "mont", emoji: "🏔️", rotulo: "Montanha" },
      { id: "plan", emoji: "🗻", rotulo: "Planalto" },
      { id: "plnc", emoji: "🌾", rotulo: "Planície" },
      { id: "depr", emoji: "🕳️", rotulo: "Depressão" },
    ],
    rodadas: [
      { id: "r1", municipioA: { nome: "Amazônia baixa", emoji: "🌳", cor: "from-emerald-400 to-teal-600" },
        municipioB: { nome: "Rio corta terra plana", emoji: "🌊", cor: "from-sky-400 to-blue-600" },
        contexto: "Terra baixa, plana, cortada pelo Amazonas. Que relevo?",
        pecaCertaId: "plnc",
        feedbackAcerto: "Isso! Baixa e plana = PLANÍCIE.", feedbackErro: "Baixa e plana = PLANÍCIE." },
      { id: "r2", municipioA: { nome: "Brasília", emoji: "🏛️", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Alto e chato", emoji: "🗻", cor: "from-purple-400 to-fuchsia-600" },
        contexto: "Área alta, plana no topo, borda em degrau. Que relevo?",
        pecaCertaId: "plan",
        feedbackAcerto: "Isso! Alto e plano no topo = PLANALTO.", feedbackErro: "Alto e plano = PLANALTO." },
      { id: "r3", municipioA: { nome: "Pico da Neblina", emoji: "🌫️", cor: "from-slate-400 to-gray-600" },
        municipioB: { nome: "2.995 metros", emoji: "🏔️", cor: "from-sky-400 to-blue-600" },
        contexto: "Elevação com quase 3 km de altura e pico definido. Que relevo?",
        pecaCertaId: "mont",
        feedbackAcerto: "Isso! Pico alto = MONTANHA.", feedbackErro: "Pico alto = MONTANHA." },
      { id: "r4", municipioA: { nome: "Sertão nordestino", emoji: "🌵", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Mais baixo ao redor", emoji: "⬇️", cor: "from-purple-400 to-fuchsia-600" },
        contexto: "Área rebaixada em relação ao entorno. Que relevo?",
        pecaCertaId: "depr",
        feedbackAcerto: "Isso! Mais baixo que o entorno = DEPRESSÃO.", feedbackErro: "Rebaixamento = DEPRESSÃO." },
      { id: "r5", municipioA: { nome: "Pantanal", emoji: "💧", cor: "from-emerald-400 to-teal-600" },
        municipioB: { nome: "Alaga na chuva", emoji: "🌊", cor: "from-sky-400 to-blue-600" },
        contexto: "Planície gigante que enche de água nas cheias. Que relevo?",
        pecaCertaId: "plnc",
        feedbackAcerto: "Isso! Baixa e alagável = PLANÍCIE.", feedbackErro: "Pantanal = PLANÍCIE alagada." },
      { id: "r6", municipioA: { nome: "Chapada Diamantina", emoji: "🗻", cor: "from-amber-400 to-orange-600" },
        municipioB: { nome: "Topo plano na Bahia", emoji: "⬆️", cor: "from-red-400 to-rose-600" },
        contexto: "Elevação alta com topo plano — chapada. Que relevo?",
        pecaCertaId: "plan",
        feedbackAcerto: "Isso! Chapada é uma forma de PLANALTO.", feedbackErro: "Chapada = PLANALTO com topo chato." },
    ],
    falaFinal: "6 relevos, 6 acertos!",
  },

  cena10_revisao: {
    tipo: "pizzaMunicipio",
    aurora: "Pizza do RELEVO brasileiro.",
    instrucao: "Toque em cada fatia",
    fatias: [
      { id: "plan", rotulo: "Planaltos (60%)", emoji: "🗻", percentual: 60, cor: "#d97706",
        descricao: "Domínio absoluto: são planaltos gastos que cobrem a maior parte do país.",
        exemplos: ["🏛️ Brasília", "🗻 Chapada Diamantina", "☕ Sul de Minas"] },
      { id: "plnc", rotulo: "Planícies + Depressões (40%)", emoji: "🌾", percentual: 40, cor: "#059669",
        descricao: "Áreas baixas: Amazônia, Pantanal, litorais e depressões sertanejas.",
        exemplos: ["🌳 Amazônia", "💧 Pantanal", "🌵 Depressão do Sertão"] },
    ],
    falaFinal: "Brasil é país de planalto. Terra antiga, forma gasta.",
  },

  cena11_avaliacao: {
    tipo: "seloAtlas",
    aurora: "3 perguntas finais.",
    instrucao: "Responda as 3",
    perguntas: [
      { id: "av1", pergunta: "O relevo que MAIS aparece no Brasil é:",
        opcoes: [
          { id: "a", texto: "Montanhas altas", correta: false },
          { id: "b", texto: "Planaltos antigos", correta: true },
          { id: "c", texto: "Vulcões", correta: false },
        ],
        feedbackAcerto: "Isso! PLANALTOS dominam.", feedbackErro: "Não temos montanhas altas nem vulcões. PLANALTOS." },
      { id: "av2", pergunta: "A Planície do Pantanal fica no:",
        opcoes: [
          { id: "a", texto: "Nordeste", correta: false },
          { id: "b", texto: "Centro-Oeste (MT/MS)", correta: true },
          { id: "c", texto: "Sul", correta: false },
        ],
        feedbackAcerto: "Isso! MT e MS.", feedbackErro: "Pantanal = CENTRO-OESTE." },
      { id: "av3", pergunta: "Por que o Brasil não tem montanhas gigantes?",
        opcoes: [
          { id: "a", texto: "Por causa do clima quente", correta: false },
          { id: "b", texto: "Está no meio da placa tectônica", correta: true },
          { id: "c", texto: "Por causa do desmatamento", correta: false },
        ],
        feedbackAcerto: "Isso! Placa parada = sem colisão = sem montanhas jovens.", feedbackErro: "Clima e desmate não fazem montanha. É estar no MEIO DA PLACA." },
    ],
    selo: { nome: "Cartógrafo de Relevo", subtitulo: "Insígnia do Explorador Planetário", emoji: "⛰️", cor: "from-amber-500 to-orange-700" },
    falaFinal: "Insígnia conquistada!",
  },

  recompensa: { xp: 400, moedas: 300, medalha: "Cartógrafo de Relevo" },
};
